__tests__/DeletePostModal.tsx, components/DeletePostModal.tsx, graphql/posts.ts, lib/user.ts, pages/posts/[id].tsx
Add a button to delete the post if the logged-in user is a moderator
=> feat: delete post button for moderators

__tests__/CommentActionButtons.tsx, __tests__/MainComment.tsx, __tests__/PostPage.tsx, __tests__/SubComment.tsx, components/CommentActionButtons.tsx, graphql/comments.ts, graphql/posts.ts, pages/posts/[id].tsx
Show the number of upvotes and comments for every post and comment
=> feat(posts): show number of upvotes and comments

__tests__/PostPage.tsx, components/AuthContext.ts, components/MainLayout.tsx, components/ProfileLayout.tsx, lib/fetcher.ts, lib/ssr.ts, lib/useLoggedUser.ts, lib/user.ts, pages/_app.tsx, pages/index.tsx, pages/posts/[id].tsx, pages/register.tsx
To improve performance the user is now fetched in the background instead of SSR
=> refactor: fetch logged user in the client

__tests__/PostPage.tsx, components/AuthContext.ts, components/MainLayout.tsx, components/ProfileLayout.tsx, lib/fetcher.ts, lib/ssr.ts, lib/useLoggedUser.ts, lib/user.ts, pages/_app.tsx, pages/index.tsx, pages/posts/[id].tsx, pages/register.tsx
To improve performance the user is now fetched in the background instead of SSR
=> refactor: fetch logged user in the client 

components/MainLayout.tsx, package-lock.json, package.json, pages/_app.tsx
Next link prefecthes the page and use client routing which increase the navigiation speed between pages
=> refactor(header): use next links in the header

components/profile/ProfileForm.tsx, lib/form.ts, lib/user.ts, pages/[userId]/index.tsx
If the user has no articles, a text box is shown to help them fill it easily
=> feat: add text box to set twitter handle from the profile empty screen

__tests__/MainLayout.tsx, components/layouts/MainLayout/SecondPhaseButtons.tsx, components/layouts/MainLayout/index.tsx, pages/register.tsx
Following recent changes of implementing incremental page load, it caused the header buttons to flow as they load.
=> fix: header buttons flow

__tests__/AccountDetailsModal.tsx, __tests__/CommentActionButtons.tsx, __tests__/MainComment.tsx, __tests__/MainLayout.tsx, __tests__/NewCommentModal.tsx, __tests__/PostPage.tsx, __tests__/ProfileForm.tsx, __tests__/ProfileLayout.tsx, __tests__/ProfilePage.tsx, __tests__/SubComment.tsx, __tests__/register.tsx, components/AuthContext.ts, lib/useLoggedUser.ts, lib/user.ts, pages/[userId]/index.tsx, pages/_app.tsx, pages/posts/[id].tsx
Call the /users/me endpoint to refresh the access token before dispatching any other request
=> refactor: validate authentication before proceeding with other requests

components/comments/CommentActionButtons.tsx, pages/posts/[id].tsx
If the user upvoted and canceled the upvote in the same session the counter went off.
Closes dailydotdev/daily#242
=> fix: optimistic ui of comment action buttons

components/profile/ProfileForm.tsx
Following dailydotdev/daily#251, I update the regex patterns to allow more flexibility
=> fix: social handles validation

.env, __tests__/SearchPage.tsx, __tests__/setup.ts, components/fields/SearchField.tsx, components/layouts/MainFeedPage.tsx, components/utilities.tsx, graphql/feed.ts, lib/canonical.ts, pages/index.tsx, pages/search.tsx
* Add search page at /search
* Add rich structured data in the home screen for search engines
=> feat: search page

.env, __tests__/MostUpvotedPage.tsx, __tests__/PopularPage.tsx, __tests__/RecentPage.tsx, __tests__/SearchPage.tsx, components/PostsSearch.tsx, components/layouts/MainFeedPage.tsx, hooks/useFeed.ts, pages/index.tsx, pages/popular.tsx, pages/recent.tsx, pages/search.tsx, pages/upvoted.tsx
Change the MainFeedPage to be a layout to reuse most of the DOM between page changes.
This provides a smoother user experience when opening the search box and querying.
=> refactor: improve search user experience

components/cards/PostCard.tsx, pages/_app.tsx
* memoize card date format
* preconnect to cloudinary
=> refactor: optimize performance

packages/shared/src/components/modals/NewSourceModal.tsx
Updated the `suggest new source` popup.
=> NewSourceModal.tsx

packages/webapp/components/FooterNavBar.module.css, packages/webapp/pages/_app.tsx
Related to https://github.com/dailydotdev/daily/issues/285
=> fix: solves padding issue of navbar on mobile safari

packages/webapp/pages/posts/[id].tsx
Related to [this](https://github.com/dailydotdev/daily/issues/298) issue.
=> Make the article title clickable on the article page

packages/extension/webpack.config.js, packages/webapp/next.config.js
Fixing [this issue](https://github.com/dailydotdev/daily/issues/299).
=> Fix Windows support

packages/shared/src/hooks/useSettings.ts
Fixes the minor delay that occurs when selecting a theme and the option actually getting reflected on the select tag.
=> Fix theme option selection update delay

packages/shared/src/components/Feed.tsx, packages/shared/src/components/FeedItemComponent.tsx, packages/shared/src/components/VirtualizedFeedGrid.tsx, packages/shared/src/hooks/feed/useCommentPopup.ts, packages/shared/src/hooks/feed/useFeedBookmarkPost.ts, packages/shared/src/hooks/feed/useFeedInfiniteScroll.ts, packages/shared/src/hooks/feed/useFeedOnPostClick.ts, packages/shared/src/hooks/feed/useFeedReportMenu.ts, packages/shared/src/hooks/feed/useFeedUpvotePost.ts, packages/shared/src/hooks/feed/useVirtualFeedGrid.ts, packages/shared/src/lib/feed.ts
Split the Feed component into custom hooks and child components to improve the readability and maintainability of this component.
=> refactor: refactor the feed component

packages/extension/src/newtab/App.tsx, packages/extension/src/newtab/MainFeedPage.tsx, packages/shared/src/hooks/analytics/useTrackPageView.ts, packages/shared/src/hooks/useThirdPartyAnalytics.ts, packages/webapp/hooks/useWebappVersion.ts, packages/webapp/pages/_app.tsx
=> fix: in-house page tracking in the extension

packages/shared/src/components/filters/BlockedFilter.tsx, packages/shared/src/components/filters/FilterRedDot.tsx, packages/shared/src/components/filters/TagButton.tsx, packages/shared/src/components/filters/TagCategoryDropdown.tsx, packages/shared/src/components/filters/TagItemList.tsx, packages/shared/src/components/filters/TagItemRow.tsx, packages/shared/src/components/filters/TagOptionsMenu.tsx, packages/shared/src/components/filters/TagsFilter.tsx, packages/shared/src/components/filters/common.tsx, packages/shared/src/components/modals/UnblockModal.tsx, packages/shared/src/contexts/BootProvider.tsx, packages/shared/src/graphql/feedSettings.ts, packages/shared/src/hooks/useAlertContext.ts, packages/shared/src/hooks/useMutateFilters.ts, packages/shared/src/hooks/useTag.ts, packages/shared/src/hooks/useTagContext.ts, packages/shared/src/lib/boot.ts
Fixed testing issues and cleanup code by doing small refactors.
- Text error on blocked page
- Styling issue for search rows
- Added new hook for tagContext state
=> fix: :art: Refactored some code and fixed testing bugs

packages/shared/src/components/filters/common.tsx
Small fix where the outline on mobile was making the UI look weird.
DD-292 #done
=> style: remove outline for mobile click

packages/webapp/pages/devcard.tsx
=> fix: devcard responsiveness

packages/shared/src/components/PostOptionsMenu.tsx, packages/shared/src/components/Sidebar.tsx, packages/shared/src/components/filters/BlockedFilter.spec.tsx, packages/shared/src/components/filters/BlockedFilter.tsx, packages/shared/src/components/filters/TagItemList.tsx, packages/shared/src/components/filters/TagItemRow.tsx, packages/shared/src/components/filters/TagsFilter.tsx, packages/shared/src/components/filters/common.tsx, packages/shared/src/components/modals/UnblockModal.tsx, packages/shared/src/hooks/useMutateFilters.ts
Fixed some small bugs from our QA session
- Remove UTM
- Search tags changed icon to three dots
- Block item actions are now direct
- Duplicate tags from context feed menu are now removed
- Tooltip when sidebar is open changed
DD-303 #done
=> fix: refactor some small bugs in the sidebar icons

packages/shared/src/components/Sidebar.tsx, packages/shared/src/components/filters/FilterMenu.tsx, packages/shared/src/hooks/useFeedSettings.ts
Fixed the mobile issue, refactored the load as we use it in two places
Also added the timeout for the client side refresh as discussed.
DD-304 #done
=> fix: bug on mobile filter menu and added timeout for client refresh

packages/shared/src/components/PostOptionsMenu.tsx, packages/shared/src/components/buttons/OptionsButton.tsx, packages/webapp/pages/posts/[id].tsx
The position on the button was offset too much.
Used the old position of the report button.
Also hide if on desktop to only show on hover.
And added the moderation buttons inside.
=> fix: hotfix tooltip position and admin buttons

packages/shared/src/components/ProfilePicture.tsx, packages/shared/src/components/cards/Card.tsx, packages/shared/src/components/cards/PostCard.spec.tsx, packages/shared/src/components/cards/PostCard.tsx, packages/shared/src/components/comments/MainComment.spec.tsx, packages/shared/src/components/comments/SubComment.spec.tsx, packages/shared/src/components/modals/AccountDetailsModal.spec.tsx, packages/shared/src/components/modals/NewCommentModal.spec.tsx, packages/shared/src/components/modals/NewCommentModal.tsx, packages/shared/src/components/modals/UpvotedPopupModal.spec.tsx, packages/shared/src/components/profile/EditImageWithJoinedDate.spec.tsx, packages/shared/src/components/profile/ProfileLink.tsx, packages/shared/src/graphql/comments.ts, packages/shared/src/graphql/feed.ts, packages/shared/src/graphql/furtherReading.ts, packages/shared/src/graphql/posts.ts, packages/shared/src/lib/config.ts, packages/shared/src/lib/user.ts, packages/webapp/__tests__/MainLayout.tsx, packages/webapp/__tests__/PostPage.tsx, packages/webapp/__tests__/ProfileLayout.tsx, packages/webapp/__tests__/register.tsx, packages/webapp/components/widgets/BestDiscussions.tsx, packages/webapp/pages/posts/[id].tsx
Now that we have our ProfilePicture component, I took this chance in fixing the fallback image to utilize the said component on some other part of the apps where it displays a user image.
=> refactor: utilizing profile picture component while including a fallback image

packages/shared/src/components/modals/NewCommentModal.spec.tsx, packages/shared/src/components/modals/NewCommentModal.tsx, packages/webapp/__tests__/PostPage.tsx, packages/webapp/pages/posts/[id].tsx
Tests have turned green and the preview now shows the appropriate author the user is replying to 🚀 
Preview:
=> fix: new comment reply to mismatch

packages/shared/src/components/MainLayout.module.css, packages/shared/src/components/MainLayout.tsx, packages/shared/src/components/profile/ProfileButton.tsx, packages/webapp/components/layouts/MainLayout.module.css
Removed the header buttons and rank in this PR.
Looks super empty now.
Non breaking for the main branch, will be re-introduced in separate
PR.
=> feat: removed header buttons and rank

packages/shared/src/components/LazyImage.tsx, packages/webapp/.env
Tested locally using env variable for production api
=> refactor: forward ref of lazy image

packages/shared/src/components/markdown.module.css, packages/shared/src/styles/base.css, packages/shared/tailwind.config.js
Tsahi adjusted the spacing for certain elements and adjusted the color scheme for the code blocks.
=> fix: refactor spacing and color theme for markdown comments

packages/webapp/pages/devcard.tsx
DD-341 #done
Removed DevCard themes:
- Halloween
- DailyDev's 4th Anniversary
=> refactor: finished devcard themes

packages/shared/src/components/tooltips/BaseTooltip.module.css, packages/shared/src/components/tooltips/BaseTooltip.tsx, packages/shared/src/components/tooltips/BaseTooltipContainer.tsx, packages/shared/src/components/tooltips/SimpleTooltip.tsx, packages/webapp/components/CalendarHeatmap.tsx, packages/webapp/pages/[userId]/index.tsx
In this commit, I have included the customization capability of the tooltip which will also be utilized in the Profile Tooltip.
=> refactor: profile heatmap tooltip

packages/webapp/pages/[userId]/index.tsx
[Related issue](https://github.com/dailydotdev/daily/issues/373)
=> fix: date dropdown using fit-content

packages/shared/src/components/BookmarkEmptyScreen.tsx, packages/shared/src/components/sidebar/Sidebar.tsx
- cd70929636b3fa7246160bded5c23cf1cd38cc0e : Bookmark empty screen was not responsive
- 575a1ed2f2de1da41291c10c7b1d5a36e946e501 : Sidebar expanded evaluation for mobile view was not correct
=> fix: feedback round 2

packages/shared/src/components/sidebar/common.tsx
=> fix: desktop version share link color

packages/shared/src/components/RankProgress.tsx, packages/shared/src/components/sidebar/Sidebar.tsx, packages/shared/src/components/sidebar/common.tsx, packages/shared/src/contexts/AlertContext.tsx, packages/shared/src/contexts/BootProvider.tsx
Fixed that we need to wait for the settings to be loaded before even showing the sidebar.
=> fix: Fix boot settings load for sidebar

packages/shared/src/components/MainLayout.tsx
We removed the sidebar rendered, but it's needed for this function.
Feel free to merge on accept.
=> fix: hotfix for the mobile title showing with the logo

packages/shared/src/components/MainLayout.tsx, packages/shared/src/components/profile/ProfileForm.tsx, packages/webapp/pages/register.tsx
Made sure the register page is centered and the timezone is part of the main fields as this is important information for the onboarding.
DD-391 #done
=> fix: register was not centered and timezone was not in default set

packages/shared/src/components/LoginButton.tsx, packages/shared/src/components/MainFeedLayout.tsx
We recently introduced the default value for the feature flagged variables.
However we were not leveraging this in all places.
This PR solves that by switching the or cases to the default values
=> fix: fixed the default values for existing feature flags

CODEOWNERS
After a discussion with @idoshamun we've decided to remove the codeowners file.
This will give myself and @sshanzel more control as being the active code reviewers for the apps repo.
=> fix: :bug: Removing the codeowners file

packages/shared/src/components/sidebar/MyFeedButton.tsx, packages/shared/src/components/sidebar/Sidebar.spec.tsx, packages/shared/src/lib/featureManagement.ts
Introducing a new flagsmith value to determine if we should show the my feed in general or not.
DD-440 #done
=> feat: added the generic wrapper for the my feed ab test

packages/shared/src/components/Feed.spec.tsx, packages/shared/src/components/LoginButtons.tsx, packages/shared/src/components/Settings.spec.tsx, packages/shared/src/components/Settings.tsx, packages/shared/src/components/filters/AdvancedSettings.tsx, packages/shared/src/components/modals/LoginModal.tsx, packages/shared/src/contexts/AuthContext.tsx, packages/shared/src/hooks/feed/useFeedUpvotePost.ts, packages/shared/src/lib/featureManagement.ts, packages/shared/src/types/LoginModalMode.ts, packages/webapp/components/posts/PostActions.tsx, packages/webapp/components/posts/PostComments.tsx, packages/webapp/pages/posts/[id].tsx
Added AB testing for login modal buttons and description copy. 
Removed LoginModalMode because it is no longer used. 
DD-412 #done
=> refactor: ab signup popup

packages/shared/src/components/sidebar/Sidebar.tsx
Changed the feedback page url to /feedback
=> refactor: add new feedback page url

packages/shared/src/components/profile/ProfileForm.tsx, packages/shared/src/lib/featureManagement.ts, packages/webapp/pages/register.tsx
Added AB testing for signup modal title and buttons copies. 
Added AB testing to hide a profile image.
DD-416 #done
=> refactor: make signup modal copies dynamic

packages/shared/src/components/AlertDot.tsx, packages/shared/src/components/sidebar/MyFeedAlert.tsx, packages/shared/src/components/sidebar/MyFeedButton.tsx, packages/shared/src/components/sidebar/Sidebar.tsx
=> fix: my feed alert close button

packages/shared/src/components/sidebar/MyFeedButton.tsx, packages/shared/src/components/sidebar/Sidebar.tsx
- Fixes the my-feed being active (displaying active CSS)
- Fixes extension navigation
=> fix: my feed navigation item styles

packages/shared/src/components/filters/FeedFilters.tsx, packages/shared/src/components/filters/FilterMenu.tsx, packages/shared/src/components/multiLevelMenu/MultiLevelMenu.tsx
When the user clicks the "Create my feed" button, it should display the "Tags menu" tab automatically.
=> refactor: multi-level menu directly opened tab

packages/shared/src/components/MainFeedLayout.tsx, packages/shared/src/components/sidebar/Sidebar.tsx
Fixed some small bugs.
- My feed didn't have a title showing
- Sidebar was not active when coming from the default feed option
- Anonymous user could set my-feed as default without having access to it.
DD-462 #done
=> fix: :bug: Fix active my-feed issues

packages/shared/src/components/Feed.tsx, packages/shared/src/components/FeedItemComponent.tsx, packages/shared/src/hooks/feed/useCommentPopup.ts, packages/shared/src/hooks/feed/useFeedBookmarkPost.ts, packages/shared/src/hooks/feed/useFeedOnPostClick.ts, packages/shared/src/hooks/feed/useFeedUpvotePost.ts, packages/shared/src/hooks/feed/useTrackImpression.ts, packages/shared/src/lib/feed.ts
Added the ranking property to our feed extra's.
This only gets added if it's available and passed through to all the individual tracking options.
DD-481 #done
=> feat: added ranking analytics

packages/shared/src/components/MainFeedLayout.tsx, packages/shared/src/hooks/usePersistentContext.ts
DD-482 #done 
We now persist the value for the value applied on which ranking algorithm to use.
=> refactor: feed ranking algo persistence

.github/pull_request_template.md
- Introducing a PR template
- It will allow us to quickly create PR
- Focus on describing tests and reminding us to check both webapp and extension
- N/A
DD-479 #done
=> docs: proposing a PR template to remind us of certain tests and format

packages/shared/src/components/history/ReadingHistory.spec.tsx, packages/shared/src/components/history/ReadingHistoryItem.tsx, packages/shared/src/graphql/posts.ts, packages/shared/src/graphql/users.ts
- We changed the timezone for reading history to be reflecting the users timezone
- We delete based on a UTC timezone, so we need to pass along that value instead
N/A
https://github.com/dailydotdev/daily-api/pull/865
DD-498 #done
=> fix: :bug: Fix for the hiding of the read history

.github/pull_request_template.md
Just fixed a typo and made the checkbox actually require the requestor to tick. My bad I think I was not clear about the checkbox and what the requestor needs to keep in mind when creating one.
=> refactor: pull request template description

.github/pull_request_template.md, packages/extension/src/newtab/ShortcutLinks.spec.tsx, packages/shared/src/components/Feed.spec.tsx, packages/shared/src/components/Settings.spec.tsx, packages/shared/src/components/Settings.tsx, packages/shared/src/components/SidebarRankProgress.spec.tsx, packages/shared/src/components/sidebar/Sidebar.tsx, packages/shared/src/contexts/BootProvider.spec.tsx, packages/shared/src/contexts/SettingsContext.tsx, packages/shared/src/graphql/settings.ts, packages/shared/src/hooks/useReadingRank.ts
Control the visibility of the sidebar rank badge based on the user settings.
✅ 
DD-506 #done
=> refactor: opt-out weekly goals

packages/shared/src/components/modals/RanksModal/index.tsx, packages/shared/src/components/profile/ActivitySection.tsx, packages/shared/src/graphql/users.ts, packages/webapp/__tests__/ProfilePage.tsx, packages/webapp/pages/[userId]/index.tsx
- Describe what this PR does
- top tags space vertically is too big
- top tags is missing 1
- userReadingRankHIstory is offset incorrectly
- max width modal 420px
- links profile should open a new tab
=> fix: gamification feedback

packages/shared/src/graphql/users.ts
Fixes the missing params on weekly goals graphQL
=> fix: date params on weekly goals

packages/shared/src/graphql/users.ts, packages/webapp/__tests__/ProfileLayout.tsx, packages/webapp/components/layouts/ProfileLayout/index.tsx
- Describe what this PR does
Rank in profile utilizing v2.
=> refactor: profile rank utilizing v2

packages/shared/src/components/RankProgress.tsx, packages/shared/src/components/RankProgressWrapper.tsx, packages/shared/src/hooks/useIncrementReadingRank.ts, packages/shared/src/lib/rank.ts
- Fixes missed indexes in the `RANKS` object.
=> fix: missed rank index

packages/shared/src/components/SidebarRankProgress.spec.tsx
- Added tests for all the ranks when there is no current rank
- Added tests for all the ranks when there is a previous week rank
=> fix: :test_tube: Added rank tests

packages/shared/src/components/modals/SharedBookmarksModal.tsx
- change share bookmarks docs link
=> refactor: change docs link

packages/shared/src/components/utilities.tsx
This PR fixes horizontal scroll on Bookmarks mobile page.
Before:
After:
=> fix: horizontal scroll on bookmarks mobile page

packages/shared/src/components/PostsSearch.tsx, packages/shared/src/graphql/users.ts, packages/shared/src/hooks/useInfiniteReadingHistory.ts, packages/webapp/__tests__/HistoryPage.spec.tsx, packages/webapp/pages/history.tsx
- Added the search field for the reading history
- Added the suggestion query
- Added the actual search query
https://github.com/dailydotdev/daily-api/pull/878
DD-472 #done
=> feat: :sparkles: Added the option to search your reading history

packages/shared/src/components/Markdown.tsx, packages/shared/src/components/modals/CommentBox.tsx, packages/shared/src/components/modals/NewCommentModal.tsx
- Should now include a button in preview to submit the comment
- Should now have the close button for the modal
- Should now fix the alignment of the footer - also removed the border-top based on the design spec
=> fix: preview markdown styling

.github/pull_request_template.md
- Just changed the heading to proper md equivalent
Preview:
https://github.com/dailydotdev/apps/blob/dec860b557c3b6c5037a69688b59137c316f21b2/.github/pull_request_template.md
=> refactor: readme to have proper heading

packages/shared/src/components/Markdown.tsx, packages/shared/src/components/modals/CommentBox.tsx
- The mention button should be borderless
Reference: https://dailydotdev.slack.com/archives/C01L0QXQJNB/p1648105921187879
=> fix: at button borderless and on comment hover

packages/webapp/pages/devcard.tsx
- Removal of the Christmas themed devcard
- Commented what the option is used for, so we can quickly add new themes
n/a
DD-584 #done
=> fix: remove Christmas themed devcard

packages/shared/src/components/history/ReadingHistory.spec.tsx, packages/webapp/pages/my-feed.tsx
- I remember we have decided not to apply SEO stuff on my-feed page, so I thought the other parts won't be necessary. What do you think?
=> fix: page title on my-feed

packages/webapp/pages/devcard.tsx
Introducing three new limited edition devCards
- Three new limited edition devCards
DD-612 #done
=> feat: add three custom 4th of may limited edition DevCards

packages/webapp/pages/devcard.tsx
=> fix: correct the image URLs

packages/shared/src/components/modals/PostModal.tsx, packages/shared/src/components/post/PostContent.tsx, packages/shared/src/components/post/PostNavigation.tsx, packages/webapp/pages/posts/[id].tsx
- Refactored the post navigation to be displayable even without left and right functions
- Refactored the post content to accommodate the styling for the post page header
Thoroughly tested across different sizes on both article modal and post page.
Preview:
=> refactor: post page to include header for post options

packages/shared/src/graphql/settings.ts
- We had some unused queries and types that could safely be removed
WT-79 #done
=> chore: remove unused query and type

packages/extension/src/companion/Companion.tsx, packages/extension/src/companion/CompanionContent.tsx, packages/extension/src/companion/CompanionContextMenu.tsx, packages/extension/src/companion/CompanionDiscussion.tsx, packages/extension/src/companion/CompanionMenu.tsx, packages/extension/src/companion/CompanionPermission.tsx, packages/extension/src/companion/common.tsx, packages/extension/src/companion/useBackgroundPaginatedRequest.ts, packages/extension/src/companion/useBackgroundRequest.ts, packages/extension/src/companion/useCompanionPostComment.ts, packages/shared/src/components/buttons/ClickableText.tsx, packages/shared/src/components/post/PostContent.tsx, packages/shared/src/components/utilities.module.css, packages/shared/src/components/utilities.tsx, packages/shared/src/hooks/usePostComment.ts, packages/shared/src/lib/featureManagement.ts
- Fixes font for TLDR fallback text
- Reduced TLDR font to 15px
- Open the video link on a new tab
- Video link to behave as our ClickableText component
- Border theme accuracy
- Companion pointer alignment
Note: the new behavior of the comment button will be raised in a different PR. Thank you!
=> refactor: companion feat internal testing feedback

packages/shared/src/components/widgets/PostUsersHighlights.tsx
- There was an issue with the extension when navigating to a source since the value of the URL is incomplete.
DD-632 #done
=> fix: post modal source using extension

docker-compose.yml
Replace the wait-for.sh in docker-compose with depends-on and healthcheck
Closes #635 
=> refactor(docker-compose): add health-check and depends-on

packages/extension/src/companion/CompanionMenu.tsx
=> fix: companion menu comment tooltip

packages/extension/src/background/index.ts, packages/extension/src/companion/App.tsx, packages/extension/src/companion/Companion.spec.tsx, packages/extension/src/companion/Companion.tsx, packages/extension/src/companion/CompanionMenu.tsx, packages/extension/src/companion/index.tsx, packages/extension/src/companion/useBackgroundRequest.ts, packages/extension/src/companion/useCompanionPostComment.ts, packages/extension/src/content/index.tsx, packages/shared/src/contexts/BootProvider.tsx, packages/shared/src/contexts/SettingsContext.tsx, packages/shared/src/hooks/useRefreshToken.ts
The intermediate branch for all the fixes. Nothing specific.
=> fix: companion beta feedback

packages/extension/src/companion/Companion.tsx, packages/extension/src/companion/CompanionContent.tsx, packages/extension/src/companion/CompanionDiscussion.tsx, packages/extension/src/companion/CompanionEngagements.tsx
- Changed the comment section to be always expanded
- Refactored some styling behaviour to match the sketch
- The empty comments seems slightly off, but it seems to match our existing behaviour now
WT-121 #done
=> feat: expanded comment companion mode

packages/extension/src/companion/CompanionDiscussion.tsx, packages/extension/src/companion/CompanionMenu.tsx, packages/shared/src/components/post/PostContent.tsx, packages/shared/src/hooks/usePostComment.ts, packages/webapp/pages/posts/[id].tsx
- Added tracking for the comment modals 
- 1. comment button
- 2. start discussion button
- added both in companion and webapp/extension
- also removed the popup mode as we don't use it
WT-126 #done
=> feat: tracking for comment modal

packages/extension/src/companion/CompanionPopupButton.tsx, packages/extension/src/newtab/MainFeedPage.tsx
=> fix: impression on display for companion button

.github/pull_request_template.md
- Since the companion app is now part of our major features, I think it is a great idea to always be reminded that it won't break when we introduce a new thing.
=> chore: pr template to remind about companion

.gitignore, .idea/.gitignore, .idea/codeStyles/Project.xml, .idea/codeStyles/codeStyleConfig.xml, .idea/daily-webapp.iml, .idea/dbnavigator.xml, .idea/inspectionProfiles/Project_Default.xml, .idea/jsLibraryMappings.xml, .idea/jsLinters/eslint.xml, .idea/misc.xml, .idea/modules.xml, .idea/vcs.xml
- This causes the IDE to behave strangly
=> fix: reintroduce .idea folder

packages/shared/src/components/utilities.tsx, packages/shared/src/hooks/usePostComment.ts
- We had some missing/wrong tracking events
=> fix: refactor tracking events

packages/shared/src/components/modals/SubmitArticleModal.spec.tsx, packages/shared/src/components/modals/SubmitArticleModal.tsx, packages/shared/src/components/sidebar/Sidebar.tsx, packages/shared/src/graphql/submitArticle.ts
=> fix: utilization of submission availability

packages/shared/src/components/Icon.tsx, packages/shared/src/components/MainFeedLayout.tsx, packages/shared/src/components/MyFeedIntro.tsx, packages/shared/src/components/modals/CreateMyFeedModal.tsx, packages/shared/src/contexts/AuthContext.tsx, packages/shared/src/graphql/feed.ts, packages/shared/src/lib/featureManagement.ts, packages/shared/src/lib/user.ts
- New onboarding flow for My feed modal
- Tracking events added to track the auto flow
WT-3 #done
=> Wt 3 my feed onboarding

packages/shared/src/components/buttons/Button.tsx, packages/shared/src/components/filters/TagButton.tsx
Now classNames are passed to button icon when doing close, so they are applied. It resolves all the issues with icon buttons (mostly rotation). Also some classes were removed from tag button icon, because we don't need them
=> fix: tag button icon changes when selected 

packages/shared/src/components/post/PostContent.tsx
=> fix: post content origin

packages/shared/src/components/cards/AdCard.tsx, packages/shared/src/components/cards/Card.module.css
=> fix: list options button and ad card image

.github/pull_request_template.md
=> feat: update PR template to include events

packages/shared/src/components/RankProgressWrapper.tsx, packages/shared/src/components/modals/NewRankModal.tsx, packages/shared/src/components/modals/RanksModal/DevCardFooter.tsx, packages/shared/src/components/modals/RanksModal/common.tsx, packages/shared/src/components/modals/RanksModal/index.tsx, packages/shared/src/lib/featureManagement.ts, packages/webapp/pages/devcard.tsx
- Remove dev card limit from the rank modals
WT-230 #done
=> chore: remove dev card limit

packages/shared/src/lib/featureManagement.ts
- Cleanup heading font title
WT-260 #done
=> chore: cleanup winner for heading font title

packages/extension/src/companion/CompanionContent.tsx, packages/shared/src/components/cards/ShowMoreContent.tsx
Previews of the fix:
Fixes: https://github.com/dailydotdev/daily/issues/628
WT-257 #done
=> fix: tldr word breaks

packages/extension/src/companion/CompanionDiscussion.tsx, packages/shared/src/components/post/PostContent.tsx, packages/shared/src/components/post/PostWidgets.tsx, packages/shared/src/hooks/useShareComment.ts, packages/shared/src/hooks/useShareOrCopyLink.ts, packages/shared/src/hooks/useSharePost.ts
- Added a concatenated version of the text including text + url
- Also added the native share feature to the comments
WT-272 #done
=> fix: native share text concat and comment addition

packages/extension/src/companion/CompanionDiscussion.tsx, packages/shared/src/components/comments/CommentActionButtons.spec.tsx, packages/shared/src/components/comments/CommentActionButtons.tsx, packages/shared/src/components/comments/MainComment.tsx, packages/shared/src/components/comments/SubComment.tsx, packages/shared/src/components/post/PostComments.tsx, packages/shared/src/components/post/PostContent.tsx, packages/shared/src/components/utilities.tsx, packages/shared/src/lib/featureManagement.ts
- Introduced tracking for comment upvote and removal of the comment upvote
|New | upvote comment  | extra: { origin, commentId } |
|New | remove comment upvote  | extra: { origin, commentId } |
WT-258 #done
=> feat: added tracking for comment upvotes

packages/shared/src/components/auth/AuthDefault.tsx, packages/shared/src/components/auth/AuthOptions.tsx, packages/shared/src/components/auth/RegistrationForm.tsx, packages/shared/src/hooks/useWindowEvents.ts, packages/shared/src/lib/auth.ts, packages/webapp/pages/callback.tsx
- Introducing the google OIDC provider and changes
- It's still viable we have 2 redirects to the social oauth flow 
- Can probably use some cleanup with Lee's other refactor.
=> Feat OIDC provider

packages/webapp/.gitignore, packages/webapp/next-env.d.ts
- There is this annoying file getting created again and again for the TypeScript compiler
- As per NextJS docs, this should not be committed and ignored in git.
- Kindly re-run your webapp dev if you experience any issues.
Reference: https://nextjs.org/docs/basic-features/typescript#existing-projects
=> chore: ignore next-env.d.ts file

packages/shared/src/components/alert/AlertContainer.tsx, packages/shared/src/components/utilities.tsx, packages/webapp/components/layouts/AccountLayout/AccountContentSection.tsx, packages/webapp/components/layouts/AccountLayout/EmailSentSection.tsx, packages/webapp/components/layouts/AccountLayout/Security/AccountLoginSection.tsx, packages/webapp/components/layouts/AccountLayout/Security/EmailFormPage.tsx, packages/webapp/components/layouts/AccountLayout/Security/index.tsx, packages/webapp/components/layouts/AccountLayout/common.tsx, packages/webapp/pages/account/others.tsx, packages/webapp/pages/account/profile.tsx, packages/webapp/pages/account/security.tsx
- Created multiple isolated components for easier management.
WT-301 #done
=> refactor: security page tabs individual components

packages/webapp/components/layouts/AccountLayout/SidebarNav.tsx, packages/webapp/components/layouts/AccountLayout/common.tsx
- Add sidebar menu to account pages
WT-335 #done
=> Wt 335 account sidebar menu

packages/shared/src/components/auth/RegistrationForm.tsx, packages/shared/src/components/fields/ImageInput.tsx
- Uneditable image input
WT-348 #done
=> refactor: uneditable image upload on social provider

packages/shared/src/components/auth/AuthOptions.tsx, packages/shared/src/components/auth/LoginForm.spec.tsx, packages/shared/src/components/auth/LoginForm.tsx, packages/shared/src/components/auth/RegistrationForm.spec.tsx, packages/shared/src/contexts/AuthContext.tsx, packages/shared/src/contexts/BootProvider.tsx
=> refactor: boot refetch on login and registration success

packages/shared/src/components/MainLayout.tsx, packages/shared/src/components/auth/IncompleteRegistrationModal.tsx, packages/shared/src/contexts/AuthContext.tsx, packages/shared/src/hooks/useProfileForm.ts
- Utilized custom hook for easier update
- Fixed dependency cycle
=> fix: timezone completion

packages/shared/src/components/auth/AuthOptions.tsx, packages/shared/src/contexts/AuthContext.tsx, packages/shared/src/lib/auth.ts
- Add the referral to the register call if it exists
WT-345 #done
=> feat: add referral push based on boot data

packages/shared/src/graphql/users.ts, packages/shared/src/lib/user.ts, packages/webapp/components/layouts/AccountLayout/Security/index.tsx
- Introducing the user deletion flow
WT-333 #done
=> feat: introduce user deletion

packages/shared/src/components/auth/AuthOptions.tsx, packages/shared/src/components/auth/AuthSignBack.tsx
- Add footer (register) to re-login screen
WT-365 #done
=> Wt 365 register re login

packages/shared/src/lib/kratos.ts, packages/webapp/components/layouts/AccountLayout/Security/index.tsx
=> fix: heimdall cors issues

packages/shared/__tests__/fixture/auth.ts, packages/shared/src/components/auth/AuthDefault.tsx, packages/shared/src/components/auth/AuthOptions.tsx, packages/shared/src/components/auth/ForgotPasswordForm.spec.tsx, packages/shared/src/components/auth/LoginForm.spec.tsx, packages/shared/src/components/auth/LoginForm.tsx, packages/shared/src/components/auth/RegistrationForm.spec.tsx, packages/shared/src/components/auth/VerifySessionModal.module.css, packages/shared/src/components/auth/VerifySessionModal.tsx, packages/shared/src/hooks/useLogin.ts, packages/shared/src/hooks/usePrivilegedSession.ts, packages/shared/src/hooks/useWindowEvents.ts, packages/shared/src/lib/auth.ts, packages/shared/src/lib/kratos.ts, packages/webapp/components/layouts/AccountLayout/EmailForm.tsx, packages/webapp/components/layouts/AccountLayout/Security/AccountLoginSection.tsx, packages/webapp/components/layouts/AccountLayout/Security/ChangePasswordForm.tsx, packages/webapp/components/layouts/AccountLayout/Security/EmailFormPage.tsx, packages/webapp/components/layouts/AccountLayout/Security/index.tsx, packages/webapp/components/layouts/AccountLayout/common.tsx, packages/webapp/pages/account/security.tsx, packages/webapp/pages/callback.tsx
WIP: Tests
- New custom hook for login for reusability
- A hook for privileged sessions for future usage.
WT-362 #done
=> feat: privileged session modal

packages/shared/__tests__/fixture/auth.ts, packages/shared/src/components/fields/PasswordField.tsx, packages/shared/src/lib/kratos.ts, packages/webapp/components/layouts/AccountLayout/AccountPageContainer.tsx, packages/webapp/components/layouts/AccountLayout/EmailForm.tsx, packages/webapp/components/layouts/AccountLayout/EmailSentSection.tsx, packages/webapp/components/layouts/AccountLayout/Security/AccountLoginSection.tsx, packages/webapp/components/layouts/AccountLayout/Security/EmailFormPage.tsx, packages/webapp/components/layouts/AccountLayout/Security/index.tsx, packages/webapp/pages/account/security.tsx
- By just setting the password, it would automatically allow email login.
WT-336 #done
=> feat: connect email and set password

packages/extension/webpack.config.js, packages/shared/src/lib/boot.ts, packages/webapp/next.config.js
- Added current extension package version to boot query.
WT-374 #done
=> Wt 374 boot version

packages/shared/src/components/auth/AuthOptions.tsx, packages/shared/src/components/auth/AuthSignBack.tsx, packages/shared/src/components/auth/LoginForm.tsx, packages/shared/src/components/auth/common.tsx
- Removed twitter temporarily
- Centered list from sign back in layout based from [discussion](https://dailydotdev.slack.com/archives/C03KATZEKDW/p1661921604847019?thread_ts=1661921269.944869&cid=C03KATZEKDW)
- Fixed login props requirements
- Fix missing props in using the login form
- Fix missing label for sign back in layout.
WT-379 #done
=> refactor: twitter removal temporarily

packages/shared/src/components/fields/PasswordField.tsx
=> refactor: default password visibility

README.md
- Add config line for the local kubernetes config needed
=> chore: add explanation for kubernetes config

packages/webapp/tailwind.config.js
- We finally have a fix for the hot reload issue with "new" arbitrary classes
- Tested and verified via garden locally
WT-6 #done
=> fix: tailwind hot reload issue for arbitrary values

packages/shared/src/components/profile/PostsSection.tsx
- Update post section twitter update to work with new flow
WT-394 #done
=> fix: update twitter from post section

packages/shared/src/components/auth/RegistrationForm.spec.tsx, packages/shared/src/hooks/useRegistration.ts, packages/shared/src/lib/auth.ts
=> fix: registration hook to include gateway id

packages/shared/src/components/auth/AuthModal.tsx, packages/shared/src/components/auth/RegistrationForm.tsx, packages/shared/src/components/fields/ImageInput.tsx, packages/webapp/components/layouts/AccountLayout/common.tsx, packages/webapp/components/layouts/AccountLayout/index.tsx
- Fixes the responsiveness of the account page container
- Fixes the image input component
=> fix: account pages responsiveness

packages/shared/src/components/MainLayout.tsx, packages/shared/src/lib/kratos.ts, packages/webapp/pages/error.tsx
=> feat: kratos error management

packages/shared/src/components/MainLayout.tsx, packages/shared/src/components/auth/AuthModal.tsx, packages/shared/src/components/auth/AuthOptions.tsx, packages/shared/src/components/auth/RegistrationForm.tsx, packages/shared/src/components/auth/SocialRegistrationForm.tsx, packages/shared/src/hooks/useAuthForms.ts, packages/shared/src/hooks/useRegistration.ts, packages/shared/src/lib/auth.ts, packages/shared/src/lib/kratos.ts, packages/webapp/pages/_app.tsx, packages/webapp/pages/login.tsx, project.garden.yml
- New social flow
WT-399 #done
=> Wt 399 new auth flow

packages/shared/src/components/auth/AuthSignBack.tsx, packages/shared/src/hooks/useRegistration.ts
=> fix: on provider click for auth sign back layout

packages/shared/src/components/auth/IncompleteRegistrationModal.tsx, packages/shared/src/components/auth/SocialRegistrationForm.tsx, packages/shared/src/components/fields/TextField.tsx
- Add the close button action
WT-436 #done
=> fix: timezone close button

packages/webapp/components/layouts/AccountLayout/Security/AccountLoginSection.tsx
- Make the prefix text for connected accounts dynamic based on action.
WT-434 #done
=> fix: copy existing provider

packages/shared/src/components/MainLayout.tsx, packages/shared/src/components/auth/AuthDefault.tsx, packages/shared/src/components/auth/AuthModal.tsx, packages/shared/src/components/auth/AuthSignBack.tsx, packages/shared/src/components/auth/EmailSignupForm.tsx, packages/shared/src/components/auth/IncompleteRegistrationModal.tsx, packages/shared/src/components/auth/ProviderButton.tsx, packages/shared/src/components/auth/RegistrationForm.tsx, packages/shared/src/components/auth/SocialRegistrationForm.tsx, packages/shared/src/components/auth/common.tsx, packages/shared/src/components/fields/ImageInput.tsx, packages/shared/src/components/fields/PasswordField.tsx
- All changes here were based on the following link: https://miro.com/app/board/uXjVPYAKeHQ=/?fromRedirect=1
This still lacks the SVG requirement of not being sliced from the sides. Tomer will provide the assets: https://dailydotdev.slack.com/archives/C03KATZEKDW/p1662985570388149
WT-455 #done
=> fix: tomer design concerns

packages/shared/src/components/auth/IncompleteRegistrationModal.tsx
=> fix: timezone dropdown responsiveness

packages/shared/src/components/MainLayout.tsx, packages/shared/src/components/auth/AuthOptions.tsx, packages/shared/src/components/auth/SocialRegistrationForm.tsx, packages/shared/src/hooks/useProfileForm.ts
- Issues mentioned were the registration gets stuck and nothing happens. After further investigation, some of the criteria were not met and error logs were not shown.
- This should allow the form to receive the feedback from the integration.
WT-416 #done
WT-452 #done
=> fix: registration unresponsive

packages/shared/src/components/auth/AuthModal.tsx
- Copy changes for the bullet points in the auth modal
WT-464 #done
=> fix: copy changes

packages/shared/src/components/auth/AuthDefault.tsx, packages/shared/src/components/auth/AuthOptions.tsx
- Remember the login state for coming back from forgot password flow
WT-469 #done
=> fix: forgot password flow

packages/shared/src/components/auth/AuthDefault.tsx, packages/shared/src/components/auth/AuthOptions.tsx, packages/shared/src/components/auth/LoginForm.tsx, packages/shared/src/hooks/useLogin.ts
=> fix: login loading indicator and hint color

packages/shared/src/components/auth/LoginForm.tsx
=> fix: email icon size

packages/shared/src/components/auth/EmailSignupForm.tsx
- We accidentally overwrote the onInput which handles the states, we should use the valueChanged callback
WT-475 #done
=> fix: email primary

packages/shared/src/components/auth/AuthOptions.tsx, packages/shared/src/components/auth/RegistrationForm.tsx
- Manual error states as Kratos no longer handles these
WT-473 #done
=> fix: manual errors

packages/shared/src/components/auth/IncompleteRegistrationModal.tsx, packages/shared/src/styles/components/buttons.css
WT-500 #done
WT-501 #done
WT-502 #done
WT-503 #done
=> fix: timezone modal design issues

packages/shared/src/components/MainLayout.tsx, packages/shared/src/components/auth/AuthOptions.tsx, packages/shared/src/components/auth/SocialRegistrationForm.tsx, packages/shared/src/components/fields/ImageInput.tsx
Fixes the following:
- Image input border
- image input spacing
- Icons sizes
- Submit button disabled state
WT-504 #done
WT-505 #done
WT-506 #done
WT-507 #done
=> fix: social form ui

README.md
=> Update README.md - fixed typos

packages/shared/src/components/auth/AuthModal.tsx, packages/shared/src/components/modals/DiscardActionModal.spec.tsx, packages/shared/src/components/modals/DiscardActionModal.tsx, packages/shared/src/components/modals/NewCommentModal.tsx
- Made the discard modal more dynamic
WT-508 #done
=> fix: dynamic discard

packages/shared/src/components/DailyCircle.tsx
Preview (removed bg for easier visibility on the changes):
WT-492 #done
=> refactor: wider spread on backdrop

packages/webapp/pages/account/security.tsx, packages/webapp/pages/reset-password.tsx
- Related discussion: https://dailydotdev.atlassian.net/browse/WT-449?focusedCommentId=10560
WT-449 #done
=> refactor: password reset message

packages/shared/src/components/auth/RegistrationForm.tsx, packages/shared/src/components/auth/SocialRegistrationForm.tsx
- We didn't apply the new responsive guide to all forms
WT-515 #done
=> fix: small responsive issues

packages/shared/src/components/auth/AuthModal.tsx, packages/shared/src/contexts/AuthContext.tsx, packages/shared/src/contexts/BootProvider.tsx, packages/shared/src/lib/boot.ts
- A way to auto show the auth modal based on logout state
WT-402 #done
=> feat: logout popup

packages/shared/src/components/auth/EmailVerificationSent.tsx
=> fix: scrollable email verification sent

packages/shared/src/components/auth/AccountCompletionModals.tsx, packages/shared/src/components/auth/RegistrationForm.spec.tsx, packages/shared/src/components/auth/RegistrationForm.tsx, packages/shared/src/components/auth/SocialRegistrationForm.tsx, packages/shared/src/hooks/useRegistration.ts, packages/shared/src/lib/auth.ts
=> refactor: opt out marketing related emails

packages/shared/src/components/auth/ForgotPasswordForm.tsx, packages/shared/src/hooks/useAccountEmailFlow.ts, packages/shared/src/lib/auth.ts, packages/webapp/components/layouts/AccountLayout/EmailSentSection.tsx, packages/webapp/pages/account/security.tsx
- Fixes the change email to Kratos request
- Refactors the sending of email verification to be reusable
Was thinking to include the dedicated section for whether the email is verified or not, but it is not yet available and probably still in the works.
https://dailydotdev.slack.com/archives/C03KATZEKDW/p1663568291856469
WT-534 #done
=> fix: change email

packages/webapp/pages/account/profile.tsx
- Added a toast message so people know it updated
WT-568 #done
=> Wt 568 profile toast

packages/webapp/pages/account/profile.tsx
- Added invalid states to the profile form fields
WT-577 #done
=> fix: profile invalid states

packages/shared/src/lib/kratos.ts, packages/webapp/components/layouts/AccountLayout/EmailForm.tsx, packages/webapp/pages/account/security.tsx
- Add hint for when email exists
WT-564 #done
=> Wt 564 change email hint

packages/shared/src/components/auth/AuthOptions.tsx, packages/shared/src/components/auth/RegistrationForm.spec.tsx, packages/shared/src/contexts/AuthContext.tsx, packages/shared/src/hooks/useRegistration.ts, packages/shared/src/lib/auth.ts
- Referral was never working for social flow, this fixes it
- Also added timezone to the initial registration call.
WT-590 #done
=> fix: fixed referral and added timezone field

packages/shared/src/components/auth/SocialRegistrationForm.tsx
- Adjust the form to fit on one page with no scroll
WT-550 #done
=> fix: social registration form spacing

packages/shared/src/components/auth/RegistrationForm.tsx, packages/webapp/components/layouts/AccountLayout/Security/index.tsx
- Made the password field minimum 6 chars and required (browser based)
WT-605 #done
=> fix: password field

packages/shared/src/components/auth/AuthOptions.tsx
- Login page error fix
WT-606 #done
=> fix: login page error call

packages/shared/src/components/auth/AuthOptions.tsx
- A fix for the OIDC social form to actually show the error and only close on valid submit.
WT-602 #done
=> fix: OIDC username

packages/extension/src/companion/CompanionMenu.tsx, packages/webapp/pages/signup.tsx
Rename login to signup page
WT-619 #done
=> refactor: rename login page to signup page

packages/extension/src/manifest.json
- This is just to make local development work.
=> fix: manifest to allow cookie sharing in dev env

packages/shared/src/components/modals/DeleteAccountModal.tsx
=> fix: delete account modal confirm label color

packages/extension/.env, packages/shared/src/components/auth/AuthOptions.tsx, packages/webapp/pages/signup.tsx
Signup page had a few edge cases of callbacks there were not defined. This is fixed now
WT-617 #done
=> fix: signup page flow

packages/shared/src/components/auth/AuthDefault.tsx, packages/shared/src/components/auth/AuthOptions.tsx, packages/shared/src/components/auth/LoginForm.spec.tsx, packages/shared/src/components/auth/LoginForm.tsx
- Autofocus on the email input when clicking "Login" button.
- Autofocus on the password input when the email is filled.
Preview
https://user-images.githubusercontent.com/13744167/193819884-5886093e-41ef-4682-b9c8-78110787797e.mov
WT-627 #done
=> fix: login and registration auto focus

packages/shared/src/components/auth/ProviderButton.tsx
- Key was set on singular component, which causes side effects ([see here](https://betterprogramming.pub/common-mistakes-with-react-keys-384ec8c8044d#1350))
WT-633 #done
=> fix: re login color

packages/shared/src/components/auth/EmailVerified.tsx
- Copy change as we always verify and login now
WT-642 #done
=> fix: verified email copy

packages/shared/src/components/auth/AuthModal.tsx
- Small mismatch in copy 
WT-644 #done
=> fix: we had a mismatch in copy

packages/webapp/pages/account/profile.tsx
- Small english grammar typo
WT-647 #done
=> fix: english grammar typo

packages/shared/src/lib/constants.ts
- Fix links for profile section
WT-648 #done
=> fix: updated the profile section links

docker-compose.yml
- Adds the missing environment variable
Thanks @idoshamun for the fix
=> fix: add missing environement variable

packages/shared/src/components/Feed.tsx, packages/shared/src/components/post/PostContent.tsx, packages/shared/src/hooks/feed/useFeedBookmarkPost.ts, packages/shared/src/hooks/useBookmarkPost.ts
Simple fix for the bookmark toast message
WT-309 #done
=> fix: toast message in bookmarking

Dockerfile
Closes #1328 
Improve the `Dockerfile`
It will reduce the layering and faster the Image built process
All the tests and apps are working normally.
=> fix: Improve Dockerfile

packages/webapp/pages/devcard.tsx
- Fixed the copy embed code function
WT-725 #done
=> fix: devcard copy embed function

packages/shared/src/components/Feed.tsx
Created a new branch and reopened a pr
=> fix: share article native share

packages/shared/src/components/modals/common/Modal.tsx, packages/shared/src/components/modals/common/ModalBody.tsx, packages/shared/src/components/modals/common/ModalHeader.tsx
- Support responsive designs for the modals
WT-729 #done
=> feat: support responsive design in modals

packages/shared/src/components/modals/ConfirmationModal.tsx, packages/shared/src/components/modals/common/ModalHeader.tsx, packages/shared/src/components/modals/common/Prompt.tsx
- My first idea was to create whole new prompt component but it would change everything with not much added benefit, so just updating the wrapper component will be enough once we transition.
WT-733 #done
=> feat: confirmation modal update for the new modal guidelines

packages/shared/src/components/CloseButton.tsx, packages/shared/src/components/RecommendedMention.tsx, packages/shared/src/components/modals/UpvotedPopupModal.tsx, packages/shared/src/components/modals/common/ModalBody.tsx, packages/shared/src/components/modals/common/ModalClose.tsx, packages/shared/src/components/profile/UpvoterList.tsx, packages/shared/src/components/profile/UserShortInfo.tsx
=> Revert "feat: [modal migration] upvoted by"

packages/shared/src/components/alert/AlertPointer.tsx, packages/shared/src/components/filters/MyFeedHeading.tsx
- Small fix for the bottom position feed alert
WT-737 #done
=> fix: bottom tooltip position

packages/webapp/pages/callback.tsx
- Added tracking to debug login issue more througouhly
|New | registration callback  | extra: { params } |
=> fix: added tracking event for callback page

packages/shared/src/components/modals/RanksModal/DevCardFooter.tsx, packages/shared/src/components/modals/RanksModal/IntroSection.tsx, packages/shared/src/components/modals/RanksModal/RanksBadges.tsx, packages/shared/src/components/modals/RanksModal/RanksTags.tsx, packages/shared/src/components/modals/RanksModal/common.tsx, packages/shared/src/components/modals/RanksModal/index.tsx, packages/shared/src/components/modals/common.tsx, packages/shared/src/components/modals/common/Modal.tsx
https://www.sketch.com/s/2867ec63-0966-4647-b1d7-b6fe696ba251/a/ZOmO1Z7
WT-756 #done
=> feat: [modal migration] weekly reading goal

packages/shared/src/components/modals/CommentBox.tsx, packages/shared/src/components/modals/NewCommentModal.tsx, packages/shared/src/components/modals/common/ModalHeader.tsx, packages/shared/src/components/modals/common/ModalTabs.tsx, packages/shared/src/hooks/useUserMention.ts
=> feat: [modal migration] comments modal

packages/shared/src/components/auth/AuthOptions.tsx, packages/shared/src/hooks/useRegistration.ts
- Added better tracking for error events
=> fix: added better login error tracking

packages/shared/src/components/modals/PostModal.module.css, packages/shared/src/components/modals/PostModal.tsx, packages/shared/src/components/modals/common/Modal.tsx, packages/shared/src/components/modals/common/ModalTabs.tsx
Fixes the modal overlay colors according to the request from design 
=> fix: fixed the modal overlay background

packages/shared/src/components/modals/NewCommentModal.spec.tsx, packages/shared/src/components/modals/SubmitArticleModal.spec.tsx, packages/shared/src/components/modals/SubmitArticleModal.tsx, packages/shared/src/components/notifications/EnableNotification.tsx, packages/shared/src/lib/image.ts
=> feat: permission prompt for new article

packages/extension/src/newtab/MostVisitedSitesModal.tsx, packages/shared/src/components/modals/NewSourceModal.spec.tsx, packages/shared/src/components/modals/NewSourceModal.tsx, packages/shared/src/components/modals/SubmitArticleModal.tsx, packages/shared/src/components/modals/common/Modal.tsx, packages/shared/src/components/notifications/EnableNotification.tsx, packages/shared/src/contexts/NotificationsContext.tsx, packages/shared/src/lib/image.ts, packages/webapp/__tests__/NotificationsPage.tsx
=> feat: notification prompt after new source

packages/shared/src/components/notifications/InAppNotification.tsx, packages/shared/src/hooks/useInAppNotification.ts
=> fix: toast notification fix

packages/shared/src/contexts/OnboardingContext.tsx
=> feat: only display the feed modal on the homescreen

packages/shared/src/components/notifications/InAppNotification.tsx, packages/shared/src/contexts/FeaturesContext.tsx, packages/shared/src/hooks/useInAppNotification.ts, packages/shared/src/lib/featureManagement.ts, packages/shared/src/lib/featureValues.ts
=> feat: add a queue to the in-app notifications

packages/shared/src/components/squads/SelectArticle.tsx, packages/shared/src/graphql/squads.ts
=> fix: create squad fixes

packages/shared/src/components/notifications/EnableNotification.tsx
=> fix: hide banner until everything is initialized

packages/shared/src/components/filters/FeedFilters.tsx, packages/shared/src/components/modals/NewCommentModal.tsx, packages/shared/src/components/modals/common/Modal.tsx, packages/shared/src/components/modals/common/ModalBody.tsx, packages/shared/src/components/modals/common/ModalFooter.tsx, packages/shared/src/components/modals/common/ModalHeader.tsx, packages/shared/src/components/modals/common/ModalSidebar.tsx, packages/shared/src/components/modals/common/ModalStepsWrapper.tsx, packages/shared/src/components/modals/common/ModalTabs.tsx, packages/shared/src/components/modals/common/types.ts
=> feat: stepped modal for modal guidelines

packages/shared/src/components/notifications/EnableNotification.tsx, packages/shared/src/lib/analytics.ts
WT-904 #done
[WT-904]: https://dailydotdev.atlassian.net/browse/WT-904?atlOrigin=eyJpIjoiNWRkNTljNzYxNjVmNDY3MDlhMDU5Y2ZhYzA5YTRkZjUiLCJwIjoiZ2l0aHViLWNvbS1KU1cifQ
=> feat: track enable notifications impression

packages/shared/src/components/Feed.tsx, packages/shared/src/components/FeedItemComponent.tsx, packages/shared/src/components/ShareOptionsMenu.tsx, packages/shared/src/components/cards/ActionButtons.tsx, packages/shared/src/components/cards/PostCard.spec.tsx, packages/shared/src/components/cards/PostCard.tsx, packages/shared/src/components/cards/PostList.tsx, packages/shared/src/components/modals/ShareModal.tsx, packages/shared/src/components/post/common.tsx, packages/shared/src/contexts/FeaturesContext.tsx, packages/shared/src/lib/featureManagement.ts, packages/shared/src/lib/featureValues.ts
- Cleanup post card share experiment
WT-915 #done
=> feat: cleanup post card share experiment

packages/shared/src/components/squads/SquadPageHeader.tsx, packages/shared/src/graphql/squads.ts, packages/webapp/pages/squads/[handle].tsx
- Added the actual squad member count from the API result
WT-932 #done
=> fix: added actual squad member count

packages/shared/src/components/squads/SquadHeaderBar.tsx, packages/shared/src/components/squads/SquadHeaderMenu.tsx, packages/shared/src/components/squads/SquadPageHeader.tsx, packages/shared/src/graphql/squads.ts
- Option to leave a squad as a member
- Will open a seperate PR to delete the squad as the owner
WT-911 #done
=> Wt 911 leave squad

packages/shared/src/components/containers/FeedTopicCard.tsx, packages/shared/src/components/onboarding/FilterOnboarding.tsx
Applied resolution-based classes.
Preview deployment quick link: https://daily-webapp-q9mfp1qqx-dailydotdev.vercel.app/
Sample recording:
https://user-images.githubusercontent.com/13744167/212343251-90f6f24b-1720-4b9c-8432-bc5796199576.mov
=> fix: onboarding filters mobile view

packages/shared/src/components/modals/SquadMemberModal.tsx, packages/shared/src/components/modals/common.tsx, packages/shared/src/components/modals/common/types.ts, packages/shared/src/components/profile/SquadMemberList.tsx, packages/shared/src/components/profile/UpvoterList.tsx, packages/shared/src/components/profile/UserShortInfo.tsx, packages/shared/src/components/profile/UserShortInfoPlaceholder.tsx, packages/shared/src/components/squads/SquadHeaderBar.tsx, packages/shared/src/graphql/squads.ts
- Modal for squad members
- Modified existing upvoter modal a bit for it.
- Report is a seperate ticket
WT-849 #done
=> feat: squad member modal

packages/shared/src/components/squads/SelectArticle.tsx
https://user-images.githubusercontent.com/13744167/213246198-9fa7f12e-848e-4f55-a230-649d87fefe4e.mov
WT-923 #done
=> fix: missing right arrow on hover

packages/shared/src/components/errors/SquadLoading.tsx, packages/shared/tailwind.config.js, packages/webapp/pages/squads/[handle]/index.tsx
- Skeleton loading placeholder for Squad page.
- Added the max height page tailwind config.
WT-944 #done
=> feat: squad page loading skeleton

packages/shared/src/components/comments/MainComment.tsx, packages/shared/src/components/notifications/EnableNotification.tsx, packages/shared/src/components/squads/SquadPageHeader.tsx, packages/shared/src/hooks/useEnableNotification.tsx
=> feat: squads notification strip

packages/shared/src/components/sidebar/Sidebar.tsx, packages/shared/src/components/sidebar/SquadsList.tsx, packages/shared/src/components/squads/SquadHeaderBar.tsx
=> fix: squad sidebar and squad header buttons

packages/webapp/pages/notifications.tsx
Preview of the fix:
WT-947 #done
=> fix: notification title page template

packages/shared/src/components/sidebar/common.tsx
=> feat: truncate long squad names

packages/shared/src/components/modals/EditSquadModal.tsx, packages/shared/src/components/squads/Details.tsx, packages/shared/src/graphql/squads.ts
- Small changes to make the edit function work.
WT-946 #done
=> feat: changes for the edit squad function

packages/shared/src/components/Feed.tsx, packages/shared/src/components/sidebar/Sidebar.tsx, packages/shared/src/graphql/feed.ts, packages/shared/src/graphql/posts.ts, packages/shared/src/hooks/useFeed.ts, packages/webapp/pages/squads/[handle]/index.tsx
=> feat: display the feed for the squad source

packages/shared/src/graphql/feed.ts, packages/webapp/pages/squads/[handle]/index.tsx
- Modify supported feed type defaults
WT-954 #done
=> feat: feed types

packages/shared/src/components/squads/Details.tsx, packages/shared/src/graphql/squads.ts
- Changed the query being used to check whether the source exists or not.
WT-956 #done
=> refactor: usage of new query to check handle availability

packages/shared/src/hooks/useCreateSquadModal.ts
- Auto prompt squad creation 1st time
WT-844 #done
=> feat: prompt squad beta to users 1st time

packages/shared/__tests__/fixture/feed.ts, packages/shared/src/components/Feed.spec.tsx, packages/shared/src/components/cards/PostCard.spec.tsx
- Fixing the test cases
- We previously always expected the card to be the direct link, this experiment is long gone, so we now should test against the button rather.
=> fix: test cases

packages/webapp/__tests__/AccountNotificationsPage.tsx
- Hotfix where restore causes a issue by restoring the previous failed test
=> fix: test restore issue

packages/shared/src/components/fields/ImageInput.tsx, packages/shared/src/components/modals/EditSquadModal.tsx, packages/shared/src/components/squads/Details.tsx
=> fix: squad image upload

packages/shared/src/components/auth/AuthModal.tsx
- Users got logged out on register
- Needs new extension
WT- #done
=> fix: logout on register issue

packages/shared/src/components/widgets/PostUsersHighlights.tsx
- Combined with @sshanzel PR this will render the handle if available for sources.
- (His PR fixes the permalink issue)
WT-964 #done
=> fix: handle source

packages/shared/src/graphql/squads.ts
- Fix infinite scroll and always limit 5 on initial load (overview page)
WT-989 #done
=> fix: squad member list scroll

packages/shared/src/components/squads/ModalHeader.tsx
=> fix: locked squad modal image

packages/shared/src/components/cards/SharePostCard.tsx, packages/shared/src/components/squads/InviteTextField.tsx, packages/shared/src/components/squads/Ready.tsx
=> fix: margins in shared post action button

packages/shared/src/graphql/squads.ts
=> fix: edit squad update object

packages/shared/src/components/post/BasePostContent.tsx, packages/shared/src/components/post/PostContent.tsx, packages/shared/src/components/post/SquadPostContent.tsx, packages/shared/src/components/post/SquadPostPageNavigation.tsx, packages/shared/src/hooks/usePostModalNavigation.ts, packages/webapp/pages/posts/[id].tsx
- Since the content here was just reused from what we have in the modal for squad feed, there is not much change required.
- The major part this PR introduces is the navigation that is custom for the Squad page.
Currently deployed at preview.
WT-995 #done
=> feat: squad post page

packages/shared/src/components/post/SquadPostContent.tsx, packages/shared/src/graphql/posts.ts, packages/webapp/pages/posts/[id].tsx
- Send a view post event when the modal opens up or the post page has been rendered. This is only for Squad related posts.
WT-978 #done
=> feat: view post

packages/shared/src/components/post/SquadPostContent.tsx
=> feat: post page link on shared post modal

packages/shared/src/components/auth/AuthModal.tsx, packages/shared/src/contexts/AuthContext.tsx, packages/shared/src/graphql/squads.ts, packages/webapp/pages/squads/[handle]/[token].tsx
- Don't wait for the boot to refresh its data but locally add the squad to boot manually.
WT-1005 #done
=> fix: join squad race condition

packages/shared/src/graphql/squads.ts, packages/webapp/pages/squads/[handle]/[token].tsx
- The squad being added was undefined resulting in error.
WT-1010 #done
=> fix: join squad adding data

packages/shared/src/graphql/comments.ts, packages/shared/src/graphql/posts.ts
=> fix: misused fragments

packages/shared/src/components/squads/SquadHeaderMenu.tsx
=> fix: update squad list after delete/leave

packages/shared/src/components/squads/Comment.tsx
=> fix: add a tooltip to squad post comment button

packages/shared/src/components/post/SquadPostContent.tsx
- Trigger send mutation whenever the dependency (post id) changes.
=> fix: sending view mutation when navigating on post modal

packages/shared/src/components/sidebar/SquadsList.tsx
=> fix: use permalink instead of relative path

packages/shared/src/components/post/SquadPostPageNavigation.tsx
=> fix: update back to squad text

packages/shared/src/graphql/feed.ts
=> fix: display shared posts in bookmarks

packages/shared/src/components/sidebar/InvitePeople.tsx, packages/shared/src/components/sidebar/MyFeedButton.tsx, packages/shared/src/components/sidebar/Section.tsx, packages/shared/src/components/sidebar/Sidebar.tsx, packages/shared/src/components/sidebar/SidebarBottomSection.tsx, packages/shared/src/components/sidebar/SquadsList.tsx, packages/shared/src/components/sidebar/common.tsx
- Ido mentioned this was a known issue before, I'm not sure what was the fix before but if you do remember, kindly drop in the comments. Thank you! @rebelchris 
WT-1013 #done
=> fix: sidebar title z-index

packages/shared/src/components/sidebar/Sidebar.tsx, packages/shared/src/hooks/useCreateSquadModal.ts
=> fix: race condition by ensuring flags are fetched

packages/shared/src/components/auth/AuthOptions.tsx
=> hotfix: catch duplicate accounts

packages/shared/src/components/modals/common/Modal.tsx
=> fix: comment modal on ios

packages/shared/src/components/sidebar/SquadAccessIntro.tsx
=> fix: squad beta modal text

packages/shared/src/components/squads/SquadPageHeader.tsx
- Added squad ID to feedback URL
WT-1039 #done
=> fix: add squad id for feedback URL

packages/shared/src/components/auth/AuthModal.tsx, packages/shared/src/components/modals/OnboardingModal.tsx
- Only execute the logout when the user info is not confirmed by checking the username.
- Tested the flow for both OIDC and password, both works as intended.
- Currently deployed at https://preview.app.daily.dev
=> fix: password flow

packages/shared/src/components/modals/NewSquadModal.tsx, packages/shared/src/components/squads/Details.tsx, packages/shared/src/components/squads/Ready.tsx, packages/shared/src/components/squads/SteppedComment.tsx, packages/shared/src/components/squads/SteppedDetails.tsx, packages/shared/src/components/squads/utils.tsx, packages/shared/src/graphql/squads.ts
- Used try catch to check if the request failed and display the error message.
- Ensured to lowercase the handle sent to the server.
- Did some small cleanups.
WT-1015 #done
=> fix: squad form displaying error message

packages/webapp/__tests__/AccountNotificationsPage.tsx, packages/webapp/__tests__/NotificationsPage.tsx
- Since all the release blocker tasks for Squad are finished, and I am a bit annoyed with the flaky test cases, I tried a fix 🤣 
- Hopefully, this helps.
=> test: notifications flaky test cases

packages/shared/src/components/cards/SharedPostCardHeader.tsx, packages/shared/src/lib/dateFormat.ts
=> fix: card header line clamp

packages/shared/src/components/squads/Comment.tsx
- Auto focus the comment box when sharing something to a Squad.
WT-1033 #done
=> refactor: auto focus share comment field

packages/shared/src/components/Feed.tsx, packages/shared/src/hooks/usePostModalNavigation.ts
=> fix: next article button on last page

packages/shared/src/components/squads/SelectArticle.tsx, packages/shared/src/graphql/fragments.ts
- Added tracking props
- Added better loading for new squad post modal
=> fix: small issues from testing

packages/shared/src/components/modals/CommentBox.tsx, packages/shared/src/components/modals/NewCommentModal.spec.tsx, packages/shared/src/components/tooltips/RecommendedMentionTooltip.tsx, packages/shared/src/hooks/useUserMention.ts, packages/shared/src/lib/element.ts
The primary issue was, in Android, `keydown` or `keyup` events are not recognized, hence, the functions were not getting triggered.
The listener that works across platforms is `oninput` but they have some differences (keyboard events are not recognized, since there is no change on the input). I have introduced the `enums` to identify whether the event was a `KeyboardEvent` such as navigating, etc. to properly execute the necessary functions.
I've also made some refactoring to remove magic strings for better maintainability.
For those with android devices, kindly test this out at our preview deployment below 🙏 
https://preview.app.daily.dev/
Don't forget to …
=> fix: user mention on mobile issue

packages/shared/src/components/modals/SubmitArticleModal.spec.tsx, packages/shared/src/components/modals/SubmitArticleModal.tsx, packages/shared/src/components/squads/SelectArticle.tsx, packages/shared/src/lib/featureManagement.ts
- Some small copy changes from Nimrod's feedback round
WT-1050 #done
=> fix: small copy changes

packages/shared/src/components/widgets/SocialShare.tsx, packages/shared/src/graphql/fragments.ts, packages/shared/src/graphql/posts.ts
=> fix: missing properties on post fragments

packages/webapp/pages/sources/[source].tsx
=> fix: border radius on source image

packages/shared/src/components/squads/SquadHeaderBar.tsx, packages/shared/src/components/squads/SquadHeaderMenu.tsx, packages/shared/src/components/squads/SquadPageHeader.tsx, packages/shared/src/components/utilities.tsx, packages/shared/src/graphql/squads.ts, packages/webapp/pages/squads/[handle]/index.tsx
- There was a lot of implementation that was inaccurate with the design spec. So there were a lot of spacing changes.
- I have also refactored some areas where there were unnecessary nested containers.
- The intended changes from the design team are:
- The "Create new post" button is now fully white (primary)
- Invite button:
- We add "Invite" wording next and changed the icon to +
- Reduce the avatars preview on mobile to only 3
- On mobile view:
- We centered the entire top information
- We removed the icon from the feedback button …
=> refactor: squad ui improvements

packages/shared/src/components/cards/PostList.tsx
Post without author should render the list correctly
=> fix: list without author

packages/shared/src/components/fields/Radio.tsx, packages/shared/src/components/modals/NewSourceModal.tsx
- Added the missing source submission open link button.
- Refactored the radio button label to be a ReactNode.
- Also: not a fan of nested if conditions. I kinda prefer defensive programming where you return as early as possible to avoid unexpected behaviors. Not sure what you think about it but feel free to let me know.
Deployed at preview2.
=> fix: source submission feed link

packages/shared/src/components/cards/ActionButtons.tsx
- Classed still gave issues, so inline seems to do the trick.
=> fix: noticed classed still gives issues

packages/shared/src/components/ScrollFeedFiltersOnboarding.tsx, packages/shared/src/components/notifications/EnableNotification.tsx, packages/shared/src/components/post/PostFeedFiltersOnboarding.tsx, packages/shared/src/styles/components/buttons.css, packages/shared/tailwind/buttons.js, packages/shared/tailwind/colors.js, packages/webapp/pages/_app.tsx
- I decided to address the guidelines in sections
- First part is button color guidelines.
@sshanzel / @capJavert design requested if we see buttons that are not aligned with the guidelines described color wise, we should tag them in Sketch.
WT-1100
=> fix: button color guidelines

.vscode/apps.code-workspace, .vscode/extensions.json
- After merging Jest runner extension will be recommended on the next VSCode launch
- I also added codelens config to make it work on __tests__ and `.spec` files as we use both
- After extension installation it gives you a nice overlay above test cases and describe sections to run tests selectively
=> feat: add jest runner extension and config

packages/webapp/pages/squads/[handle]/[token].tsx
- Fix the OG texts
- Return if not available to adhere load of OG
WT-1142 #done
=> fix: squad share OG and load

packages/shared/src/components/squads/Comment.tsx
- fixed dimensions for squad image
WT-{WT-1141} #done
=> feat: fix aspect and image fit

packages/webapp/pages/account/profile.tsx
- Automatically upload profile picture after selection
WT-1082 #done
=> feat: auto upload profile picture after change

packages/extension/src/manifest.json, packages/webapp/pages/index.tsx, packages/webapp/pages/search.tsx
- Changed default titles to new format
- @idoshamun Is it ok to change the manifest for this purpose? (It's the name of the app)
WT-1150 #done
=> fix: update title description

packages/shared/src/hooks/useCreateSquadModal.ts
- Avoid the create new squad popup on the invite page (beta people only)
WT-1172 #done
=> Wt 1172 avoid popup

packages/shared/src/hooks/useInputField.ts
- From the snippet below, we already pass the `hasInput` if it is available, but it seems to be coming from a state where it is not getting updated in some instances. So now when it detects a change that is not coming from an `input` change event, we would be able to make the state up-to date.
https://github.com/dailydotdev/apps/blob/main/packages/shared/src/components/fields/TextField.tsx#L144-L174
WT-1180 #done
=> fix: activated textfield has input

packages/shared/src/components/modals/PostToSquadModal.tsx
- Change toast message for squad post
WT-1178 #done
=> fix: squad post update message

packages/shared/src/components/modals/PostToSquadModal.tsx
- Small typo we missed in copy-paste action
=> hotfix: missed typo

packages/shared/src/components/squads/SquadEmptyScreen.tsx, packages/shared/src/lib/image.ts, packages/webapp/pages/squads/[handle]/index.tsx
- Empty screen for squads
- [desktop](https://user-images.githubusercontent.com/9803078/228828096-1904a168-414c-4439-9f2e-bb8cc9206bc9.png)
- [tablet](https://user-images.githubusercontent.com/9803078/228828455-8a043bdd-203b-4e4a-b515-da3f5c9ec784.png)
- [mobile](https://user-images.githubusercontent.com/9803078/228828584-3fc8736e-0f49-4d21-b26b-21eadbc608ef.png)
(copy may vary in code due to changes being made by product)
WT-1204 #done
=> feat: squad add empty screen

packages/shared/src/graphql/sources.ts, packages/shared/src/graphql/squads.ts, packages/webapp/__tests__/SquadTokenPage.tsx, packages/webapp/pages/squads/[handle]/[token].tsx
- Introduce blocked role
- Refactor evaluation on token page
WT-1215 #done
=> fix: blocked squad member

packages/webapp/next-seo.ts
- Updated OG default image to new version
=> fix: update OG default image

packages/shared/src/components/modals/EditSquadModal.tsx, packages/shared/src/components/squads/Details.tsx, packages/shared/src/components/squads/SquadHeaderMenu.tsx, packages/shared/src/components/squads/utils.tsx, packages/shared/src/graphql/fragments.ts, packages/shared/src/graphql/sources.ts, packages/shared/src/graphql/squads.ts
- Add permissions to edit squad form
- API implementation here https://github.com/dailydotdev/daily-api/pull/1228
WT-1196 #done
=> feat(squads) update posting permission

packages/shared/src/components/notifications/utils.ts
- Added the new icon and color options for notifications
WT-1226 #done
=> feat: notification icons

packages/shared/src/components/squads/SquadMemberItemAdditionalContent.tsx, packages/shared/src/components/squads/SquadMemberMenu.tsx
- Copy updates for prompts and inclusion of toast messages.
WT-1239 #done
WT-1240 #done
WT-1244 #done
=> refactor: copy updates

packages/shared/src/components/squads/Details.tsx
=> feat: rename all members option

packages/shared/src/components/squads/SquadMemberItemAdditionalContent.tsx
=> feat: align current member role to other roles in list

packages/extension/src/companion/CompanionContextMenu.tsx, packages/shared/src/components/PostOptionsMenu.tsx, packages/shared/src/components/modals/ReportPostModal.tsx
- Fix the typo error from Repost -> Report
WT-1256 #done
=> fix: report typo on modal

packages/shared/src/components/squads/SharePostBar.tsx
=> feat: adjust post bar style

Tiltfile
Add support for post scraper for adhoc env.
Please make sure to follow the instructions in the [changelog](https://dailydotdev.atlassian.net/wiki/spaces/HAN/pages/448725013/Adhoc+infra#Changelog).
Please merge whenever you want :)
=> ci: support post-scraper in adhoc env

.vscode/apps.code-workspace, .vscode/extensions.json
- Add some more recommended vscode extensions for our repo
- Adjust workspace config for eslint
=> feat(vscode): add tailwind and lint extensions

packages/webapp/pages/posts/[id].tsx
Before: 
- After: tested out the post that Ido has provided and works as shown below:
=> fix: seo is undefined on some posts

packages/shared/src/components/fields/Checkbox.module.css
- Updating per spec as we discovered [here](https://dailydotdev.slack.com/archives/C0506KU4RH9/p1682430982399919?thread_ts=1682430552.981599&cid=C0506KU4RH9)
=> fix(checkbox): update color to cabbage per design spec

packages/shared/src/components/checklist/ChecklistStep.tsx, packages/shared/src/components/checklist/InstallExtensionChecklistStep.tsx, packages/shared/src/lib/constants.ts
- Add step completion logic
WT-1310 #done
=> feat(checklist): install browser extension step

packages/shared/src/components/checklist/InviteMemberChecklistStep.tsx, packages/shared/src/hooks/useSquadChecklist.tsx, packages/shared/src/hooks/useSquadInvitation.ts
- Add step completion logic and component
WT-1319 #done
=> feat(checklist): add invite members step

packages/shared/src/components/checklist/ChecklistStep.tsx
- Following this https://github.com/dailydotdev/apps/pull/1782#discussion_r1186280404 making checklist steps expandable even when completed
=> feat(checklist): make completed steps expandable

packages/shared/src/hooks/useChecklist.ts
- I evaluated to do this on the API side but since user actions on the API are generic interface and they just happen to be sorted in checklist steps based on completion I decided to do it inside `useChecklist` hook that contains other checklist specific logic
WT-1309 #done
=> feat(checklist): sort steps by completedAt

packages/shared/src/components/checklist/SharePostChecklistStep.tsx, packages/shared/src/components/modals/PostToSquadModal.tsx, packages/shared/src/hooks/useSquadChecklist.tsx
- Add step completion logic and components
WT-1261 #done
=> feat(checklist): add share first post step

packages/shared/src/hooks/useNotificationPermissionPopup.ts
- Small issue where this would send as false and not execute correctly
- Went with more verbose to avoid errors
Test show the tracking complete, only downside is manually enabling notifications don't trigger, which might be the cause.
=> fix: conditional execution fix

packages/shared/src/components/modals/PostToSquadModal.tsx
This optimistically updates the action from the client to make sure correct action state is shown to the user immediately.
This is also done on the API side in postAdded worker to catch all other cases of post being created by user.
Additional thread [here](https://dailydotdev.slack.com/archives/C02E2C3C13R/p1683628137961029)
=> feat: optimistically update action state from the frontend

packages/shared/src/components/checklist/NotificationChecklistStep.tsx, packages/shared/src/components/notifications/EnableNotification.tsx, packages/shared/src/contexts/NotificationsContext.tsx, packages/shared/src/lib/analytics.ts
- Add step completion logic and components
WT-1311 #done
=> feat(checklist): add enable notification step

packages/shared/src/components/checklist/ChecklistCard.spec.tsx, packages/shared/src/components/checklist/ChecklistCard.tsx, packages/shared/src/components/checklist/ChecklistStep.spec.tsx, packages/shared/src/components/checklist/ChecklistStep.tsx, packages/shared/src/hooks/useChecklist.spec.tsx
- Add tests for checklist components and hook
=> feat(checklist): tests for component and the hook

packages/shared/src/components/BookmarkFeedLayout.tsx, packages/shared/src/components/FeedItemComponent.tsx, packages/shared/src/components/cards/WelcomePostCard.tsx, packages/shared/src/components/cards/WelcomePostCardFooter.tsx, packages/shared/src/components/cards/WelcomePostCardHeader.tsx, packages/shared/src/graphql/feed.ts, packages/shared/src/graphql/posts.ts, packages/webapp/__tests__/BookmarksPage.tsx, packages/webapp/__tests__/SquadFeedPage.tsx, packages/webapp/pages/squads/[handle]/index.tsx
- Add welcome post card, will be potentially refactored to match freeform post card in v6
- Used existing components, added custom header and footer to match other extensions (as SharedPostCard)
WT-1292 #done
=> feat: add WelcomePostCard

packages/shared/src/hooks/useGenerateUsername.ts
When I try to login with Google the flow fails.
Please see discussion here:
https://dailydotdev.slack.com/archives/C01L0QXQJNB/p1683961122534589
=> fix: support profiles with empty name

packages/shared/src/components/squads/SquadHeaderBar.tsx
- Changes the button type from Primary to Secondary.
WT-1338 #done
=> refactor: invitation link button type

packages/shared/src/components/fields/MarkdownInput/MarkdownUploadLabel.tsx, packages/shared/src/components/fields/MarkdownInput/index.tsx, packages/shared/src/components/post/freeform/write/WriteFreeformContent.tsx
- Fixed the UI for tablet and mobile.
- Fixed button sizes.
WT-1410 #done
=> fix: write page responsiveness on mobile and tablet

packages/shared/src/hooks/usePostMenuActions.ts, packages/shared/src/hooks/usePrompt.ts
- As mentioned in [the thread](https://dailydotdev.slack.com/archives/C01L0QXQJNB/p1683805834859899) the cause could be related to the hooks that are using memoization.
- Removed the memoization as those are unnecessary with the new implementation.
WT-1332 #done
=> refactor: unnecessary use memo usages

packages/shared/src/components/LegoReferralBadge.tsx, packages/shared/src/components/ProfileMenu.tsx, packages/shared/src/components/modals/LegoReferralCampaignModal.tsx, packages/shared/src/components/modals/common.tsx, packages/shared/src/components/modals/common/types.ts, packages/shared/src/graphql/actions.ts, packages/shared/src/lib/constants.ts, packages/shared/src/lib/image.ts, packages/shared/src/lib/storage.ts
- Implement pop-up modal and connect with CTAs
- add progress and completed state
- API implementation here https://github.com/dailydotdev/daily-api/pull/1298
=> feat: lego referral campaign pop-up modal

packages/eslint-rules/lib/rules/no-custom-color.js, packages/shared/src/components/LegoReferralBadge.tsx, packages/shared/src/components/ProfileMenu.tsx, packages/shared/src/components/layout/MainLayoutHeader.tsx, packages/shared/src/components/modals/LegoReferralCampaignModal.tsx, packages/shared/src/components/modals/common.tsx, packages/shared/src/components/modals/common/types.ts, packages/shared/src/components/sidebar/SidebarUserButton.tsx, packages/shared/src/components/utilities.tsx, packages/shared/src/contexts/AuthContext.tsx, packages/shared/src/graphql/actions.ts, packages/shared/src/graphql/users.ts, packages/shared/src/hooks/index.ts, packages/shared/src/hooks/useReferralCampaign.ts, packages/shared/src/hooks/useRegistration.ts, packages/shared/src/lib/auth.ts, packages/shared/src/lib/constants.ts, packages/shared/src/lib/featureManagement.ts, packages/shared/src/lib/image.ts, packages/shared/src/lib/query.ts, packages/shared/src/lib/storage.ts, packages/shared/src/lib/user.ts, packages/webapp/pages/_app.tsx, packages/webapp/pages/join.tsx, packages/webapp/pages/squads/[handle]/[token].tsx
- Lego referral campaign implementation  
- [DR here](https://dailydotdev.atlassian.net/wiki/spaces/HAN/pages/535986177/Lego+referral+campaign)
=> feat: lego referral camapign

packages/shared/src/components/Markdown.tsx, packages/shared/src/components/post/SharePostContent.tsx, packages/shared/src/components/post/share/SharePostTitle.tsx, packages/shared/src/components/post/share/index.ts, packages/shared/src/graphql/posts.ts
- Mentioning in the title should only work on Shared posts, hence, the change was only towards the `SharePostContent`.
WT-1393 #done
=> refactor: share post modal to display mentions

packages/shared/src/components/LegoReferralBadge.tsx
=> feat: referral popup is showed after 7 days of new user lifetime

.circleci/config.yml, packages/shared/__tests__/helpers/utilities.ts, packages/shared/src/components/auth/LoginForm.spec.tsx, packages/shared/src/components/auth/RegistrationForm.spec.tsx
=> fix: adjust timeout for flaky test

packages/shared/src/components/auth/SocialRegistrationForm.tsx
- Fix for social registration username being stuck
- Basically could get stuck in infinite loop
WT- #done
=> fix: username stuck in social login

packages/shared/src/components/modals/SubmitArticleModal.tsx, packages/shared/src/lib/constants.ts
- Request from product to change link and text
- Retro old link still exists so doesn't fail
WT-1505 #done
=> fix: modify submission guidelines to content guidelines

packages/shared/src/components/fields/MarkdownInput/index.tsx
It was requested the MarkdownInput placeholder text changes from 
"Start a discussion, ask a question or write about anything that you believe would benefit the squad. (Optional)"
To
"Thoughts/questions/ideas/rants - Tell the Squad what’s up. (Optional)"
WT-1458 #done
=> feat: Changing the MarkdownInput placeholder text

packages/shared/src/components/auth/AuthOptions.tsx, packages/shared/src/hooks/useRegistration.ts
=> fix: wait for one call to finish

packages/shared/src/hooks/useSquadChecklist.tsx
=> fix: optional check for currentMember in squad checklist

packages/shared/src/components/auth/AuthDefault.tsx, packages/shared/src/components/auth/AuthModalHeader.tsx, packages/shared/src/components/auth/LoginForm.spec.tsx, packages/shared/src/components/auth/LoginForm.tsx, packages/shared/src/components/auth/RegistrationForm.spec.tsx, packages/shared/src/components/fields/PasswordField.tsx, packages/shared/src/hooks/useLogin.ts
Changed the modal header text size for the auth modals as well as fixing the validation / error states for the inputs in login. As well as adding a toast when a user try's to register with an existing email
WT-1164 #done
=> feat: Updating the error messages on the login form

packages/shared/src/components/crypto.ts
- skip decrypt in development since features are returned as JSON
- full discussion here https://dailydotdev.slack.com/archives/C02E2C3C13R/p1690276223652159
=> feat: skip decrypt in development for growthbook

packages/shared/src/hooks/useSquadNavigation.ts
- Missing location - tested and worked on both ends.
WT-1573 #done
=> fix: redirection from extension to webapp

packages/shared/src/components/squads/Details.tsx, packages/shared/src/components/squads/SquadTypeCard.tsx
- Missing flex-col on mobile
Preview:
https://github.com/dailydotdev/apps/assets/13744167/dd5762c2-e74b-408e-a6a7-c2d9292f584f
WT-1564 #done
=> fix: squad page create page responsiveness

packages/shared/src/components/squads/SquadHeaderMenu.tsx, packages/shared/src/components/squads/SquadJoinButton.tsx, packages/shared/src/hooks/useLeaveSquad.ts
- Refactored an in-line function.
- Fixed the on success to check whether the user left or not.
WT-1572 #done
=> fix: leaving squad but confirmed to stay

packages/shared/src/components/checklist/SquadChecklistCard.tsx
- The checklist popup text was static, needed to be based on amount of steps
WT-1582 #done
=> fix: make dynamic step text

packages/shared/src/components/modals/squads/SquadNotificationsModal.tsx, packages/shared/src/components/tooltips/notifications/NotificationPreferenceMenu.tsx, packages/shared/src/graphql/notifications.ts
- We recently realized a concern with the references used on the notification and in order to make the muting work, we had to make a few adjustments with the query and mutations.
- This is blocked until this PR is merged https://github.com/dailydotdev/daily-api/pull/1377
- Have manually tested and works as intended now.
https://github.com/dailydotdev/apps/assets/13744167/52e3fb40-a682-4cd9-8c8d-5b3f685334f7
| …
=> refactor: updating notification preference

packages/shared/src/components/modals/NewSourceModal.tsx
- Additional small copy change, to make it more clear
=> fix: small copy change

packages/shared/src/components/post/PostItemCard.tsx
Added a link for each ReadList item to fix the accessibility of the page as well as the attributes the link should have
WT-1559 #done
=> feat: adding link to reading history items to fix ux and accessiblity

packages/shared/src/components/modals/squads/SquadNotificationsModal.tsx, packages/shared/src/components/squads/SquadHeaderBar.tsx, packages/shared/src/components/squads/SquadPageHeader.tsx
- Notification modal to change the title.
- Name and handle being centered.
- Avoid using ClickableText on links (we might need a new component).
WT-1613 #done
=> fix: squads mvp mobile page responsiveness

packages/extension/package.json, packages/shared/package.json, packages/shared/tailwind.config.js, packages/webapp/package.json, pnpm-lock.yaml
- Upgraded out tailwind version.
- Bringing 3 new releases in one go!
https://tailwindcss.com/blog/tailwindcss-v3-1
https://tailwindcss.com/blog/tailwindcss-v3-2
https://tailwindcss.com/blog/tailwindcss-v3-3
=> fix: upgraded tailwind

packages/shared/src/components/auth/AuthOptions.tsx, packages/shared/src/components/auth/EmailVerificationSent.tsx, packages/shared/src/components/auth/EmailVerified.tsx, packages/shared/src/contexts/SettingsContext.tsx
After signup the user settings were not updating correctly, so this has been fixed as well as forcing the email icons being forced to white for both light and dark mode
WT-1557 #done
=> feat: updating settings on boot

packages/shared/src/components/layout/MainLayoutHeader.tsx, packages/shared/src/components/modals/common/Modal.tsx, packages/shared/src/components/squads/SquadHeaderBar.tsx, packages/shared/tailwind.config.js
- We had a few overwrites with tailwind upgrade that showed up
=> fix: small tailwind overwrite issues

packages/shared/src/components/Settings.tsx, packages/shared/src/components/fields/Dropdown.tsx, packages/shared/src/components/fields/MarkdownInput/index.tsx, packages/shared/src/components/fields/common.tsx
- Found a couple more tailwind issues.
I ran through all screens and modals I could test locally, and didn't see anything other weirdly out of place.
However do notify me as soon as you see anything odd *(or unsure off)
=> fix: minor tailwind issues

packages/shared/src/components/fields/MarkdownInput/index.tsx
- Small color issues (from design spec change) to markdown buttons
- And mobile alignment issue 
=> fix: tailwind upload issues

packages/shared/src/components/feeds/FeedContainer.tsx, packages/shared/src/components/search/SearchBar.spec.tsx, packages/shared/src/components/search/SearchBar.tsx, packages/shared/src/components/search/SearchBarInput.tsx, packages/webapp/__tests__/SearchPage.tsx, packages/webapp/pages/search/index.tsx
This was just an extra intermediate branch. The only commit here was approved PRs already. Merging to reduce this intermediate branch.
=> refactor: search input as a standalone component (#2032)

packages/shared/src/components/search/SearchContainer.tsx, packages/shared/src/components/search/SearchResult.tsx, packages/shared/src/graphql/search.ts, packages/shared/src/hooks/useChat.ts, packages/shared/src/lib/query.ts, packages/webapp/components/search/SearchV1Page.tsx
- Updated the types to follow what was explained in the DR.
- Simplified state management.
- Moved away from using a `useEffect` for triggering the prompt instead of executing right there and then.
- Introduced a SearchContainer to be used for mobile app's modal version.
- Updated the stream types handlers.
- Should be ready for what is expected in the DR.
WT-1653 #done
=> fix: types and managing of stream data

packages/shared/src/graphql/comments.ts, packages/shared/src/graphql/common.ts, packages/shared/src/graphql/posts.ts
Per comments in API PRs the interface types need to be updated. This is not a braking change since actual code does not use those fields currently. Just a future proof for the interfaces when we do use them.
- https://github.com/dailydotdev/daily-api/pull/1398#discussion_r1297301635
- https://github.com/dailydotdev/daily-api/pull/1398#discussion_r1299338123
=> chore: update user upvote types to match new API interface

packages/shared/src/components/search/SearchBar.tsx, packages/shared/src/components/search/SearchBarInput.tsx, packages/shared/src/components/search/SearchContainer.tsx, packages/shared/src/lib/dateFormat.ts, packages/webapp/components/search/SearchV1Page.tsx
- Display error message and error code.
- Calculate the difference on how much was the completed time.
WT-1644 #done
=> feat: manage search errors

packages/shared/src/components/search/SearchFeedback.tsx, packages/shared/src/lib/constants.ts
- Added new links
WT-1641 #done
=> fix: search links

packages/shared/src/components/search/SearchBar.tsx, packages/shared/src/components/search/SearchContainer.tsx
- Adjust search page to be wider for better visible results
WT-1688 #done
=> fix: new width for search page

packages/shared/src/graphql/search.ts, packages/shared/src/hooks/useChat.ts
- Set correct chunk. ID
WT-1697 #done
=> fix: feedback option on new queries

packages/shared/src/hooks/useChat.ts
- Catch generic errors.
- The error event doesn't seem to provide useful error info. Not even the status code, or anything related to error.
WT-1678 #done
=> feat: catch generic errors

packages/shared/src/components/buttons/ClickableText.tsx, packages/shared/src/components/search/SearchSourceList.tsx
- Fix source list styling
WT-1707 #done
=> fix: source list styling

packages/shared/src/graphql/search.ts
- Fix types for sources
WT-1713 #done
=> fix: typecasting for sources

packages/shared/src/components/sidebar/ManageSection.tsx, packages/webapp/pages/history.tsx
- Reading history fixes to make it dynamic based on experiment
WT-1716 #done
=> fix: history page fixes

packages/shared/src/graphql/search.ts
- Ensure parameter has value first.
=> fix: undefined parameter

packages/extension/src/companion/CompanionPermission.tsx, packages/extension/src/lib/extensionScripts.ts, packages/shared/src/components/modals/CompanionModal.tsx, packages/shared/src/hooks/useCompanionTrigger.tsx, packages/shared/src/hooks/useExtensionPermission.ts, packages/shared/src/styles/base.css, packages/shared/tailwind.config.js
- redirect to the post link when accepting/denying the extension permissions (was redirecting to the companion blog post page)
- fix layout issues
- add close button as per spec
- update icons as per spec
- update secondary button color as per spec
_no events changes_
WT-1729 #done
=> fix: companion modal redirect on activation + other small fixes

packages/shared/src/components/search/SearchContainer.tsx
=> fix: progress bar shows only while searching

packages/shared/src/components/search/SearchResult.tsx, packages/shared/src/lib/labels.ts
=> feat: search feedback toast

packages/shared/src/components/search/MobileSearch.tsx
=> feat: clear button disable on mobile when no input

packages/shared/src/hooks/search/useSearchSuggestions.ts
- This should also fix https://dailydotdev.atlassian.net/browse/WT-1715
=> feat: disable suggestions refetch

packages/shared/src/components/buttons/Button.tsx, packages/shared/src/components/search/SearchBarSuggestion.tsx
- Had to manipulate buttons as it's not technically in our button design system.
=> fix: mobile pills

packages/shared/src/components/markdown.module.css, packages/shared/src/styles/typography.ts, packages/shared/tailwind/typography.js
- Did a debug session with Nimrod/Tsahi to make the font more readable for our markdown render
WT-1742 #done
=> fix: up the readability

packages/shared/src/components/search/SearchBarInput.tsx, packages/shared/src/components/search/SearchContainer.tsx, packages/shared/src/components/search/SearchResult.tsx, packages/webapp/__tests__/SearchPage.tsx, packages/webapp/components/search/SearchV1Page.tsx
- Applied the missing skeleton loader for the search result while it is still processing.
Preview:
https://github.com/dailydotdev/apps/assets/13744167/f2ca4af6-414f-46dc-924a-aacfde445bf8
WT-1718 #done
=> fix: missing skeleton loader on search result

packages/shared/src/components/MainLayout.tsx
- Make all fonts antialiased as per design request
- Makes it a lot cleaner
Before:
After:
WT-1748 #done
=> fix: make fonts antialiased

packages/shared/src/components/search/SearchBar.tsx, packages/shared/src/components/search/SearchBarInput.tsx
- We decided to not show the error code as the number doesn't represent anything.
WT-1747 #done
=> fix: remove error code number

packages/shared/src/components/search/SearchBar.tsx
- The evaluation would succeed as code would not exist therefor not be null
WT-1749 #done
=> fix: generic error to only show if error code

packages/shared/src/graphql/search.ts, packages/shared/src/hooks/chat/useChatStream.ts, packages/shared/src/lib/labels.ts
- handle rate limit errors and show custom message
=> feat: rate limit error handling

packages/shared/src/components/search/MobileSearch.tsx, packages/shared/src/components/search/SearchBarInput.tsx
- Added support to refocus on clearing button click
WT-1760 #done
=> fix: reset focus on clear action

packages/shared/src/lib/featureManagement.ts
- Switch control value
WT-1771 #done
=> fix: revert default value

packages/shared/src/components/search/SearchResult.tsx
_no event changes_
WT-1766 #done
=> fix: adjust search action buttons sizes & spacing

packages/shared/__tests__/fixture/squads.ts, packages/shared/src/lib/image.ts
- Update squad image placeholder
- API PR https://github.com/dailydotdev/daily-api/pull/1420
WT-1679 #done
=> feat: update squad image placeholder

packages/shared/src/components/auth/AuthOptions.tsx
- OIDC login -> logout -> login: works.
- Password login -> logout -> login: works.
- OIDC registration -> logout -> login: works.
- Password registration -> logout -> login: crashes.
- They both run under the same callback. One distinction is whether the chosen provider is available, meaning the user has selected OIDC, else it is password.
=> fix: password registration

packages/shared/src/components/auth/AuthDefault.tsx, packages/shared/src/components/auth/AuthHeader.tsx, packages/shared/src/components/auth/VerifySessionModal.tsx, packages/shared/src/components/auth/common.tsx, packages/shared/src/components/modals/common.tsx, packages/shared/src/components/modals/common/types.ts, packages/shared/src/hooks/useLazyModal.ts, packages/shared/src/hooks/useLogin.ts, packages/shared/src/hooks/usePrivilegedSession.ts, packages/shared/src/lib/query.ts, packages/webapp/__tests__/AccountSecurityPage.tsx, packages/webapp/components/layouts/AccountLayout/Security/AccountLoginSection.tsx, packages/webapp/components/layouts/AccountLayout/Security/index.tsx, packages/webapp/pages/account/security.tsx
- Fix verify session modal.
- Use lazy modal (so much cleaner without manually managing the state).
Deployed at preview.
=> fix: verify session modal

packages/webapp/cache.js, packages/webapp/next.config.js
We found that the issue with authentication actually has to do with service worker caching some stuff
=> fix: set sw to ignore requests which are not static

packages/shared/src/components/profile/UserShortInfo.tsx
- Fix forward ref to fix internal NextJS issue
WT-1848 #done
=> fix: forward ref

.github/CODEOWNERS
=> fix: add codeowners

packages/extension/src/newtab/App.tsx
=> feat(extension): newtab react-query devtools

packages/shared/src/components/post/SharePostContent.tsx
- fix: anchor tag inside anchor tag on squad shared post
Removes wrapping anchor tag and adds anchor tag for title and image
N/A
=> fix: anchor tag inside anchor tag on squad shared post

packages/shared/src/components/filters/MyFeedHeading.tsx, packages/shared/src/lib/featureManagement.ts
- Product wanted different text
=> fix: small fix for product team

packages/shared/src/contexts/OnboardingContext.tsx
- Remove the auto onboarding popup
=> fix: remove auto onboarding

packages/shared/src/hooks/useRegistration.ts, packages/shared/src/lib/analytics.ts, packages/shared/src/lib/auth.ts
- Add tracking error event for registration fails (CORS 99% of time)
WT-1863 #done
=> fix: add tracking error event

packages/webapp/next.config.js
- Added x-frame-options to prevent loading inside iframes
- Added a task WT-1870 to evaluate other headers 
=> feat: added x-frame-options to prevent loading inside iframes

packages/shared/src/lib/image.ts, packages/webapp/pages/onboarding.tsx
- fix: update onboarding video links
=> fix: update onboarding video links

packages/webapp/pages/onboarding.tsx
<table>
<tr>
<td><img src="https://github.com/dailydotdev/apps/assets/1681525/a3365616-24cc-4403-a53b-cd3a1c2303ce" />
<td><img src="https://github.com/dailydotdev/apps/assets/1681525/342e4f16-35d5-485a-a7b7-93bcb38891ac" />
</table>
- changes the background colour to be the same as the video
I think the preact->react migration fixed something here
- fixes the hidden image on onboarding V2
=> fix: minor onboarding v3 fixes

packages/webapp/pages/onboarding.tsx
|-|-|
| ![image](https://github.com/dailydotdev/apps/assets/1681525/63b67ae9-bfb3-4753-96f8-244803e200a9) | ![image](https://github.com/dailydotdev/apps/assets/1681525/d64a1e60-c58c-40f2-a42a-e194d897b5bd) |
- fix: height of AuthOptions on onboarding v3
=> fix: height of AuthOptions on onboarding v3

packages/shared/src/components/ShareOptionsMenu.tsx
- Remove the extra list on the context menu for sharing directly to squads
- This is basically part of the modal already
New:
WT-1887 #done
=> fix: remove squad share options from context menu

packages/shared/src/components/search/MobileSearch.tsx, packages/shared/src/components/search/SearchBar.spec.tsx, packages/shared/src/components/search/SearchBarInput.tsx
Product asked to update the copy
=> refactor: update search bar placeholder

packages/extension/src/companion/App.tsx, packages/extension/src/companion/Companion.tsx, packages/extension/src/companion/CompanionContextMenu.tsx, packages/extension/src/companion/CompanionDiscussion.tsx, packages/extension/src/companion/CompanionMenu.tsx, packages/extension/src/companion/common.tsx, packages/extension/src/companion/index.tsx, packages/shared/src/components/modals/UpvotedPopupModal.tsx, packages/shared/src/components/profile/SourceProfilePicture.tsx, packages/shared/src/components/tooltips/Portal.tsx, packages/shared/src/lib/extension.ts
Misc fixes to companion:
- fix upvotes count not opening upvote modal (it was missing modal element in CompanionMenu)
- comment options not showing tooltip (portal was mounting in page root instead of companion element)
- moved `getCompanionWrapper` to shared to reuse
- comment button in menu did nothing, now opens and focuses comment box when clicked for the first time
- sharing to squad would break companion (was missing `NotificationContext` because of `useEnableNotification` hook usage)
- squad images not working in share modal (was bugging me for a while, just used native lazy loading in companion to fix)
Don't forget to update the [Analytics Taxonomy sheet](https://docs.google.com/spreadsheets/d/18Lv7zXges9QfVX5VYL1a-Hyl0e1sQ3sLr0OK8YZWKXI/e …
=> feat: companion fixes

packages/extension/src/newtab/App.tsx, packages/shared/__tests__/helpers/boot.tsx, packages/shared/src/components/GrowthBookProvider.tsx, packages/shared/src/components/MainLayout.tsx, packages/shared/src/components/index.ts, packages/shared/src/components/withFeaturesBoundary.spec.tsx, packages/shared/src/components/withFeaturesBoundary.tsx, packages/shared/src/contexts/BootProvider.tsx, packages/shared/src/lib/boot.ts, packages/webapp/pages/onboarding.tsx
- reopened from https://github.com/dailydotdev/apps/pull/2262
- original was reverted due to SEO issues https://github.com/dailydotdev/apps/pull/2273
- it is still worth to merge features loading optimizations I think ✅ 
- removed features boundary from `MainLayout` to allow for SEO to work
- usage on `newtab/App` prevents the flashing of onboarding screen
- boundary is still ok idea I think but would like to hear other's thoughts, we can always bring back Ole-Martin's fix from before that also prevented flashing https://github.com/dailydotdev/apps/commit/9fbb24d2ea2e26c4fdd6a2d08a815b15ae7096f7
Available on [preview3](https://preview3.app.daily.dev/) …
=> feat: boot and features loading optimizations 2

packages/shared/src/contexts/OnboardingContext.tsx, packages/shared/src/lib/analytics.ts
- Remove legacy tracking event
| Remove | complete_onboarding  | extra: { ... } |
=> fix: remove legacy tracking event

packages/shared/src/components/search/SearchContainer.tsx, packages/shared/src/components/search/SearchResult.tsx, packages/shared/src/hooks/utils/usePagination.ts, packages/webapp/components/search/SearchV1Page.tsx
- Fix the distance between the search bar and the result.
=> fix: search spacing between the bar and the result

packages/shared/src/components/layout/MainLayoutHeader.tsx, packages/shared/src/hooks/referral/useReferralCampaign.ts
- Fix the layout shift by waiting for data to load before rendering.
=> fix: main layout header shift

packages/webapp/components/invite/AISearchInvite.tsx
- Fix accepting key as an existing user.
- I thought the [initial commit suggestion](https://github.com/dailydotdev/apps/pull/2277/commits/4e45e89617d7782e6e0d34c93430050e92920f48) relevant to this was to include the parenthesis that I missed, seems to be the other way around 😭 
=> fix: invite acceptance on existing user

packages/shared/src/hooks/referral/useReferralCampaign.ts
- On production, everything works as intended (tested with a new user).
- Though on local, it doesn't seem to display the header. To make sure the local is literally a replica of production, I have added some properties to ensure they are on the same page.
- Also, the documentation I shared in the previous PR seems to be for v4 and we are at v3.
=> fix(local): is idle query

packages/webapp/components/invite/AISearchInvite.tsx
- Fixed tablet mode and spacings.
Previews:
=> feat: join page for search invite tablet mode

packages/shared/src/components/search/SearchSourceList.tsx
- There was a option where `sources` is undefined so not lengthy, this should fix that.
=> fix: undefined eval

packages/shared/src/components/modals/SquadMemberModal.tsx, packages/shared/src/components/modals/UserListModal.tsx
- Fixed issues based on the discussion of this thread.
- Search bar spacing.
- Remove copy link when searching.
Previews:
=> fix: squad members search ui minor issues

README.md
- modified readme to latest method on running extension locally
- Adds documentation on running the extension locally
=> docs: update how to run extension locally

packages/shared/src/components/cards/SourceButton.tsx
- https://dailydotdev.slack.com/archives/C01L0QXQJNB/p1698752052916979
=> fix: squad user icon position

packages/shared/src/components/ProfileMenu.tsx, packages/shared/src/components/referral/SearchReferralButton.tsx, packages/shared/src/hooks/referral/useReferralCampaign.ts
- Change the key invite [copy](https://dailydotdev.slack.com/archives/C05NRH3U31C/p1698841892063899?thread_ts=1698840039.219559&cid=C05NRH3U31C) 
=> fix: change invite key copy

packages/webapp/pages/onboarding.tsx
=> fix: onboarding v3 typo

packages/shared/src/components/squads/Details.tsx
- Added user ID to the squad waitlist form 
WT-1945 #done
=> fix: add user id to waitlist form

packages/webapp/pages/account/invite.tsx
- Fix the missing loading ui by passing the `isLoading` value.
=> fix: missing loading param

.github/dependabot.yml
- Delete dependabot as we don't follow it's updates, and prefer manual ones.
- We still get auto security patches as it's a seperate setting
=> chore: delete .github/dependabot.yml

packages/shared/src/components/modals/referral/GenericReferralModal.tsx, packages/shared/src/components/referral/InviteLinkInput.tsx, packages/shared/src/components/widgets/ReferralWidget.tsx, packages/webapp/components/invite/Referral.tsx, packages/webapp/pages/account/invite.tsx
- Copy changes from the Miro link below:
https://miro.com/app/board/uXjVNe2aNY8=/?messenger=slack&utm_source=slack&utm_medium=messenger&utm_campaign=notifications&utm_content=unfurled_chat_link&utm_term=messenger_analytics
WT-1972 #done
=> refactor: referral program copy changes

packages/webapp/pages/onboarding.tsx
- Fixes the clickability of the footer links on the onboarding page
- reported [here](https://dailydotdev.slack.com/archives/C01L0QXQJNB/p1700137930745979)
=> fix: remove full height on non-authenticating view on onboarding

docker-compose.yml
- Add the user id for which user will be mocked when using our docker image (which is used in GitPod).
=> chore: gitpod env for api to mock user

.vscode/apps.code-workspace
- storybook it was missing from workspace
=> feat: add storybook package to vscode workspace

packages/shared/src/components/MainLayout.tsx, packages/shared/src/components/layout/MainLayoutHeader.tsx, packages/webapp/components/layouts/BookmarkFeedPage.tsx, packages/webapp/components/layouts/SearchLayout.tsx, packages/webapp/components/search/SearchControlPage.tsx, packages/webapp/pages/filters.tsx, packages/webapp/pages/settings.tsx
Hi,
Fix App's Logo Missing in Mobile.
=> #1000 fix BUG: on mobile the header is missing the app's logo

packages/shared/src/components/BookmarkFeedLayout.tsx, packages/shared/src/components/Feed.tsx, packages/shared/src/components/FeedItemComponent.tsx, packages/shared/src/components/PostOptionsMenu.tsx, packages/shared/src/graphql/feed.ts, packages/shared/src/graphql/posts.ts, packages/shared/src/hooks/feed/useAdvancedSettings.ts, packages/shared/src/hooks/useFeedSettings.ts, packages/shared/src/hooks/useFindSquadWelcomePost.ts, packages/webapp/__tests__/BookmarksPage.tsx, packages/webapp/__tests__/SquadFeedPage.tsx, packages/webapp/pages/posts/[id]/index.tsx, packages/webapp/pages/squads/[handle]/index.tsx
- Disable video type of posts through the post context menu.
WT-1990 #done
=> feat: post options menu for disabling videos

packages/shared/src/hooks/mutationSubscription/types.ts, packages/shared/src/hooks/mutationSubscription/useMutationSubscription.ts, packages/shared/src/hooks/vote/types.ts, packages/shared/src/hooks/vote/useFeedVotePost.ts, packages/shared/src/lib/query.ts
Refactored useMutationSubscription to use MutationCache, can't use subscribe [anymore due to changes in query v4 ](https://tanstack.com/query/v4/docs/react/guides/migrating-to-react-query-4#mutationcachenotifyevent)
Also using variables from `onSuccess` instead of `options.variables` in v4 due to [changes in type](https://tanstack.com/query/v4/docs/react/guides/migrating-to-react-query-4#removed-undocumented-methods-from-the-queryclient-query-and-mutation). 
Available to test on [preview](https://preview.app.daily.dev/)
This fixes:
- when downvoting from feed card options the option state properly changes
- when downvoting from feed card options the card vote state properly changes
- when upvoting from feed card downvote options state properly changes
- Short and concise, bullet points …
=> fix: feed vote state

packages/webapp/components/layouts/ProfileLayout/index.tsx
- We abused the rules of hooks on this page a lot, which resulted in breaking it now.
- Decided to follow the right approach, confirmed it now works without breaking.
WT-2040 #done
=> fix: react rules of hooks

packages/shared/src/components/cards/FeedbackCard.tsx, packages/shared/src/lib/featureManagement.ts
- Make the feedback copy experimentable.
- Experiment key `card_feedback_copy`.
WT-2051 #done
=> refactor: feedback card copy experimentable

packages/shared/src/hooks/useFeedLayout.ts, packages/shared/src/lib/featureManagement.ts, packages/shared/src/lib/featureValues.ts
- added new hook for feed layout changes to return object based on the changes required for the feed to keep them centralised
- added experiment values and management
- Sets the stage for the new feed layout changed
WT-1997 #done
=> feat: adding hook and experiment values

packages/shared/src/components/search/PlaceholderSearchSuggestion.tsx, packages/shared/src/components/search/SearchBarSuggestion.tsx
=> Hotfix buttonsize

packages/webapp/.gitignore
Just annoying so wanted to add.
=> feat: when building locally sw files get generated in public

packages/shared/src/components/post/PostHeaderActions.tsx
=> fix: watch button header

packages/shared/src/components/post/PostContent.tsx, packages/shared/src/components/post/PostUpvotesCommentsCount.tsx
- fix margin on post metadata and upvotes
WT-2060 #done
=> fix: margin on post metadata and upvotes

packages/shared/src/components/post/SharePostContent.tsx, packages/shared/src/components/post/ShareYouTubeContent.tsx
- fix margins in shared content
WT-2065 #done
=> fix: margins shared content

packages/shared/src/components/cards/SharedPostCardFooter.tsx
Potential solution for https://dailydotdev.slack.com/archives/C059GQ5RFP0/p1702912778957629
=> Fix: shared postcard width

packages/shared/src/components/cards/PostCardFooter.tsx
Fix my own mess introduced in:
- #2443
I did a copy&paste and forgot to do the replace part 🤦 😢
=> fix: bad copy&paste error from #2443

packages/shared/src/components/squads/SharePostBar.tsx
- hotfix for the failing test issue
=> fix: failing tests

packages/shared/src/components/layout/MainLayoutHeader.tsx
- The whole element needed to display/hide
=> hotfix: notification alignment fix

packages/shared/src/components/Custom404.tsx, packages/webapp/__tests__/SquadFeedPage.tsx
- 404 copy change to match main page
=> hotfix: 404 copy

packages/shared/src/components/cards/CollectionCard/CollectionCard.spec.tsx, packages/shared/src/components/cards/SharePostCard.spec.tsx
=> test: fix broken tests due to new year

packages/shared/src/components/Custom404.tsx
- Tsahi mentioned this should be largeTitle :) 
=> fix: typo size after design discussion

packages/shared/src/components/cards/FeedbackCard.tsx, packages/shared/src/lib/featureManagement.ts, packages/webapp/pages/onboarding.tsx
- We had 2 winning micro experiments that can be closed for now.
- More discussion on [slack](https://dailydotdev.slack.com/archives/C02JAUF8HJL/p1704633428603579).
AS-24 #done
=> chore: cleanup winning micro experiments

packages/shared/src/components/ProfilePictureGroup.tsx, packages/shared/src/components/cards/CollectionCard/CollectionCardHeader.tsx, packages/shared/src/components/cards/PostList.tsx, packages/shared/src/components/cards/ReadArticleButton.tsx, packages/shared/src/components/cards/common/SquadHeaderPicture.tsx, packages/shared/src/components/cards/v1/ArticlePostCard.tsx, packages/shared/src/components/cards/v1/Card.tsx, packages/shared/src/components/cards/v1/CollectionCard.tsx, packages/shared/src/components/cards/v1/PostCardHeader.tsx, packages/shared/src/components/cards/v1/PostDate.tsx, packages/shared/src/components/cards/v1/PostMetadata.tsx, packages/shared/src/components/cards/v1/PostReadTime.tsx, packages/shared/src/components/cards/v1/SharePostCard.tsx, packages/shared/src/components/cards/v1/WelcomePostCard.tsx, packages/shared/src/components/cards/v1/hooks.ts, packages/shared/src/components/post/collection/CollectionPillSources.tsx, packages/shared/src/styles/media.ts
Changes the card headers to align to [Figma designs](https://www.figma.com/file/nmfWPS7x3kzLUvYMkBx2kW/daily.dev---Dev-Mode?node-id=222%3A7863&mode=dev)
MI-09 #done
=> feat: align card header with designs for feed layout v1

packages/shared/src/components/image/VideoImage.tsx
=> hotfix: Update VideoImage.tsx

packages/shared/src/components/cards/v1/ActionButtons.tsx, packages/shared/src/components/cards/v1/ArticlePostCard.tsx, packages/shared/src/components/cards/v1/CollectionCard.tsx, packages/shared/src/components/cards/v1/SharePostCard.tsx, packages/shared/src/components/cards/v1/WelcomePostCard.tsx
- Card not clickable on Action buttons div to open the card
- added pointer events none to div and pointer events auto to action buttons to give proper click functionality to buttons and the rest of the div
Before:
https://github.com/dailydotdev/apps/assets/36197304/020d2048-43fb-4227-9c5b-f1e29f3d20ee
After:
https://github.com/dailydotdev/apps/assets/36197304/ed2ec43e-6e34-473c-a3f9-45f48b2f1d8a
MI-109 #done
=> fix: fix pointer events on actions block

packages/shared/src/components/feeds/FeedContainer.tsx, packages/shared/src/lib/image.ts
- Used the new asset for the background on v1.
MI-103 #done
=> fix: gradient background getting cut off

packages/shared/src/components/feeds/FeedContainer.tsx, packages/shared/src/components/search/SearchBar.tsx, packages/shared/src/hooks/search/index.ts, packages/shared/src/hooks/search/useSearchQuestionRecommendations.ts
We will have new generic hook for search suggestions of different search providers so we rename useSearchSuggestions to useSearchQuestionRecommendations for now to avoid any confusion. 
Discussion from search merge: https://github.com/dailydotdev/apps/pull/2544#discussion_r1463207212
=> refactor: useSearchSuggestions -> useSearchQuestionRecommendations

packages/shared/src/components/auth/OnboardingAnalytics.tsx, packages/webapp/public/scripts/gtag.js
=> refactor: some adjustments required by marketing

packages/shared/src/lib/featureManagement.ts, packages/webapp/pages/onboarding.tsx
- Add experiment for onboarding visual change
AS-70 #done
=> feat: add onboarding visual experiment

packages/shared/src/graphql/posts.ts
=> chore: image limit up to 20mb

packages/shared/src/components/buttons/ButtonV2.tsx
- Enable the loader :) 
MI-141  #done
=> fix: fix the loader on button v2

packages/shared/src/hooks/useAutomation.ts, packages/shared/src/lib/auth.ts, packages/shared/src/lib/errors.ts, packages/shared/src/lib/labels.ts, packages/webapp/pages/roast.tsx
Ain't found a way to kill me yet
Eyes burn with stinging sweat
Seems every path leads me to nowhere
Wife and kids, household pet
Army green was no safe bet
The bullets scream to me from somewhere
Here they come to snuff the rooster, oh yeah
Yeah here come the rooster, yeah
You know he ain't gonna die
No, no, no oh, you know he ain't gonna die
Here they come to snuff the rooster, oh yeah
Yeah here come the rooster, yeah
You know he ain't gonna die, oh
No, no, no oh, you know he ain't gonna die
Walkin' tall machine gun men
They spit on me in my home land
Gloria sent me pictures of my boy
Got my pills 'gainst mosquito death
My buddy's breathing his dyin' breath
Oh God please won't you help me make it through
Here they come to snuff the rooster, oh yeah
Yeah here come the rooster, yeah
You …
=> feat: here they come to snuff the rooster, oh yeah

packages/shared/src/components/Feed.tsx, packages/shared/src/hooks/index.ts, packages/shared/src/hooks/usePostModalNavigation.ts, packages/shared/src/hooks/useScrollRestoration.ts, packages/webapp/pages/_app.tsx
- playing with manual scroll restoration to fix the issues on mobile platforms
=> fix: scroll restoration in new layout feed

packages/shared/src/hooks/usePostModalNavigation.ts, packages/shared/src/hooks/useScrollRestoration.ts, packages/webapp/pages/_app.tsx, packages/webapp/pages/posts/[id]/index.tsx
=> fix: remove extra reloads and use auto scroll restore

packages/webapp/pages/_app.tsx
=> feat: enable manual scroll restoration

packages/shared/src/components/profile/devcard/DevCard.tsx, packages/shared/src/components/profile/devcard/DevCardContainer.tsx, packages/shared/src/components/profile/devcard/DevCardFooter.tsx, packages/shared/src/components/profile/devcard/DevCardStats.tsx, packages/shared/src/components/profile/devcard/DevCardStatsSection.tsx, packages/shared/src/components/profile/devcard/DevCardTwitterCover.tsx, packages/shared/src/components/profile/devcard/common.ts, packages/shared/src/components/profile/devcard/index.ts, packages/shared/src/graphql/users.ts, packages/shared/src/hooks/profile/useDevCard.ts, packages/shared/src/lib/image.ts
- I did a lot of refactoring in order to reuse the components we already have and everything still works.
- All the changes related to twitter BG is in this commit https://github.com/dailydotdev/apps/pull/2594/commits/2701750dc3f238167cc8a81b0fe079ff6b78e0cf - so feel free to check just this commit.
=> feat: twitter header download

packages/shared/src/components/profile/devcard/DevCardFooter.tsx, packages/webapp/pages/devcard.tsx
- Encountered an error where the page is not yet ready. Hence, user was null at some point.
- Fix the devcard issue for any layout shift or when the sources list empty to apply some offset. Preview of the issue.
=> fix: minor issues on devcard

packages/shared/src/components/profile/devcard/DevCardFooter.tsx, packages/shared/src/components/profile/devcard/common.ts, packages/webapp/pages/devcard.tsx
- Customize the DevCard itself.
Preview:
Note: it was intentionally made to enable all options just for preview.
https://github.com/dailydotdev/apps/assets/13744167/794362c6-76d6-440e-ae25-1815dc9f9e35
=> feat: customize tab and downloading image

packages/shared/src/lib/featureManagement.ts, packages/webapp/pages/onboarding.tsx
- Make the trusted companies part also AB testable (simply on/off)
=> fix: onboarding json addition

packages/shared/src/components/profile/devcard/DevCard.tsx
- Fix object fit cover for devcard's user avatar.
=> fix: object fit of devcard image

packages/shared/src/components/profile/devcard/DevCardFooter.tsx, packages/shared/src/components/profile/devcard/common.ts, packages/webapp/graphql/devcard.ts, packages/webapp/pages/devcard.tsx
- This was in conjunction of the PR for customize tabs.
- Removed most of the unused code around the devcard's previous implementation.
- Centralized state management.
=> refactor: devcard state management and cleanups

packages/shared/src/graphql/users.ts, packages/webapp/graphql/devcard.ts, packages/webapp/pages/devcards/[userId].tsx
=> feat: add devcard page

packages/webapp/pages/onboarding.tsx
- Added option to pass `image` prop to render simple images
=> fix: enable image experiments

packages/shared/src/components/filters/MyFeedHeading.tsx
- Adjust back from this https://github.com/dailydotdev/apps/pull/2611/commits/ee843157a8f99ad8b32843ac43aef53165e0b228
=> feat: move alert tooltip to bottom to not obscure sort button

packages/shared/src/components/profile/devcard/DevCard.tsx
- scaled component based on breakpoints
- fixes devcard on horizontal mobile
=> Fix horizontal image mobile

packages/shared/src/components/profile/devcard/DevCard.tsx, packages/webapp/pages/devcard.tsx
=> Add line clamps

packages/shared/src/components/profile/devcard/DevCard.tsx
=> fix: horizontal card has text centered vertically

packages/shared/src/components/profile/devcard/DevCard.tsx, packages/shared/src/graphql/users.ts, packages/shared/src/hooks/profile/useDevCard.ts, packages/webapp/pages/devcard.tsx
=> fix: use profile cover not having any effect

packages/webapp/pages/devcard.tsx
Adds a save button to the bottom of the customize form. Calls the generateDevCardV2 mutation when clicked.
=> feat: add save button to devcard customize form

packages/webapp/components/layouts/ProfileLayout/index.tsx
No way to test, we need to test in preview.
=> feat: opengraph image from devcard

packages/webapp/pages/devcard.tsx
fix image url to point to v2 instead by default
=> fix: devcard image url pointing to the old one

packages/webapp/components/layouts/ProfileLayout/index.tsx, packages/webapp/pages/devcard.tsx
- Added random parameter to og image URL, so that when the image is changed, we get around the caching
- Use the same random parameter generation as we do in the API side.
As before, we can only test this in preview.
=> fix: og image url random parameter

packages/shared/src/components/profile/devcard/DevCard.tsx, packages/shared/src/components/profile/devcard/DevCardFooter.tsx, packages/shared/src/lib/strings.ts, packages/webapp/pages/devcard.tsx
- There were some discrepancies with the equality check. Sometimes it is in uppercase, sometimes it is in lowercase.
Tested on preview, seems to be gone for me, at least.
=> Fix reset layout

packages/shared/src/hooks/profile/useDevCard.ts, packages/webapp/pages/devcard.tsx
~~Ugly fix~~ Thanks to @capJavert now a nice fix to always make sure we have devcard data defined, regardless of the order of execution.
=> fix: missing download devcard button

packages/shared/src/components/LoginButton.tsx, packages/shared/src/components/auth/AuthenticationBanner.tsx, packages/shared/src/components/banners/common.ts, packages/shared/src/components/banners/index.ts, packages/shared/src/components/layout/MainLayoutHeader.tsx, packages/shared/src/components/modals/NewRankModal.tsx, packages/shared/src/components/sidebar/SidebarUserButton.tsx, packages/shared/src/hooks/auth/useOnboarding.tsx, packages/webapp/pages/onboarding.tsx
- Refactored the `LoginButton` to accept more props and classes.
- Introduced the UI for mobile users.
Previews:
MI-170 #done
=> feat: mobile post page authentication experiment

packages/shared/src/components/TrustedCompanies.tsx
- update users nr based on request in [slack](https://dailydotdev.slack.com/archives/C01L0QXQJNB/p1707940988994149)
=> chore: update users nr

packages/shared/src/components/LoginButton.tsx, packages/shared/src/components/auth/AuthenticationBanner.tsx, packages/shared/tailwind.config.js
- Use tailwind classes over inline style implementation.
- @rebelchris there was something wrong with my initial implementation at the color declaration in tailwind config 😅 
=> refactor: tailwind usage over inline style

packages/shared/src/components/MainLayout.tsx, packages/shared/src/components/post/block/PostTagsPanel.tsx, packages/webapp/__tests__/PostPage.tsx, packages/webapp/pages/posts/[id]/index.tsx
- Remove the instance of `useFeature` on any other page but the post page.
- Render the banner through `customBanner`.
=> fix: placement of experiment allocation

packages/shared/src/components/feeds/FeedContainer.tsx
- Ensure the rendering position of the feed settings is correct
- Added gradient when in welcome mode (open discussion [here](https://dailydotdev.slack.com/archives/C068F77M8Q7/p1708070792752139?thread_ts=1708070437.547879&cid=C068F77M8Q7))
=> fix: changes for my feed component rendering

packages/shared/src/lib/labels.ts
- changes description for twitter share
MI-172 #done
=> fix: change copy on devcard share

packages/shared/src/lib/image.ts
Design optimized the assets to reduce our bill 🙈
=> refactor: update 404 assets

packages/shared/src/components/auth/OnboardingAnalytics.tsx, packages/webapp/pages/onboarding.tsx
=> fix: add hotjar tracking code to onboarding page

packages/shared/src/components/notifications/utils.ts
- Another `rounded-full` that started working 😅 
=> fix: toast notification progress roundness

packages/shared/src/components/onboarding/OnboardingFeedHeader.tsx, packages/shared/src/styles/base.css, packages/shared/tailwind.config.js
=> fix: minor design adjustments

packages/shared/src/components/fields/form/FormWrapper.tsx, packages/shared/src/components/fields/form/index.ts, packages/storybook/stories/FormWrapper.stories.tsx
- Form wrapper with built-in buttons that copy is modifiable.
- Storybook is also available.
MI-137 #done
=> feat: form wrapper

packages/shared/src/components/MainFeedLayout.tsx, packages/shared/src/components/auth/AuthModal.tsx, packages/shared/src/components/auth/AuthOptions.tsx, packages/shared/src/components/auth/OnboardingRegistrationForm4d5.tsx, packages/shared/src/components/feeds/FeedContainer.tsx, packages/shared/src/components/layout/common.tsx, packages/shared/src/components/onboarding/FilterOnboardingV4.tsx, packages/shared/src/components/onboarding/OnboardingFeedHeader.tsx, packages/shared/src/components/post/PostFeedFiltersOnboarding.tsx, packages/shared/src/lib/featureValues.ts
Sets the default auth display to be the new onboarding 4.5 view on signups
=> feat: use the new onboarding auth display as default for all signups

packages/shared/src/components/post/SharePostContent.tsx
<table>
<tr>
<td>Before
<td>After
<tr>
<td><img src="https://github.com/dailydotdev/apps/assets/1681525/f8680cae-05e5-4983-abd9-857d91012e7a">
<td><img src="https://github.com/dailydotdev/apps/assets/1681525/b86b856c-003d-4251-826f-4d4f908262f3">
</table>
- Adds TLDR section to shared links
AS-125
=> feat: add summary to shared links

packages/shared/src/components/post/SharePostContent.tsx
- minor style tweaks on large mobile devices
=> fix: mobileL fixes on shared posts

packages/shared/src/hooks/auth/useOnboarding.tsx, packages/shared/src/lib/featureManagement.ts, packages/shared/src/lib/featureValues.ts
- cleanup post page onboarding experiment since experiment was concluded ([thread](https://dailydotdev.slack.com/archives/C06K1LYU716/p1708690792715929?thread_ts=1708660588.090829&cid=C06K1LYU716))
=> chore: cleanup post page onboarding experiment

packages/shared/src/components/auth/AuthModal.tsx, packages/webapp/pages/onboarding.tsx
- update the target_id for events if onboarding v4.5
=> fix: update targetId for onboarding v4.5

packages/shared/src/components/fields/SearchField.tsx, packages/shared/src/components/onboarding/OnboardingFeedHeader.tsx
Left is new, right is old side.
- changes the button to but Float variant
=> fix: button colour on onboarding tags filter

packages/shared/src/components/auth/AuthDefault.tsx, packages/shared/src/components/auth/OnboardingRegistrationForm.tsx, packages/shared/src/components/auth/OnboardingRegistrationForm4d5.tsx, packages/shared/src/components/onboarding/MemberAlready.tsx, packages/shared/src/components/onboarding/OnboardingHeader.tsx
- Nimrod's [request](https://dailydotdev.slack.com/archives/D05UA50PW6T/p1709111182164489) 
> I need your help with changing two minor copy things in the app (no need to experiment on that)
Anywhere we have the sign up button (see #1) it should say Sign up - Free forever
Anywhere we have the log in option (see #2) it should say Already using [daily.dev](http://daily.dev/)? Log in
=> Chore update text

packages/shared/src/components/MainLayout.tsx
=> fix: we had a duplicate element

packages/shared/src/components/comments/CommentBox.tsx, packages/shared/src/components/comments/MainComment.spec.tsx, packages/shared/src/components/comments/SubComment.spec.tsx, packages/shared/src/components/post/AuthorOnboarding.tsx
- Rename instances visually from author to creator
WT-1541 #done
=> fix: rename author to creator

packages/shared/src/components/profile/devcard/DevCard.tsx, packages/shared/src/components/profile/devcard/DevCardFooter.tsx
- Missed these 2 color migrations
=> fix: minor color issues

packages/shared/src/components/post/write/CreatePostButton.tsx
- replace LinkWithTooltip with SimpleTooltip
=> fix: replace LinkWithTooltip with SimpleTooltip

packages/shared/src/components/filters/MyFeedHeading.tsx, packages/shared/src/lib/analytics.ts
- Missed a new event addition
|New | refresh feed  |  |
=> fix: add missing tracking event

packages/shared/src/components/auth/ActiveUsersCounter.tsx
- Convert to local string to add either a comma or a period on numbers.
=> fix: active users count format

packages/shared/src/components/auth/AuthOptions.tsx, packages/shared/src/components/auth/OnboardingHeadline.tsx, packages/shared/src/components/auth/OnboardingRegistrationForm.tsx, packages/shared/src/components/onboarding/common.ts, packages/shared/src/lib/featureManagement.ts, packages/shared/src/lib/featureValues.ts, packages/webapp/pages/onboarding.tsx
=> feat: micro experiment onboarding less text copy

packages/shared/src/components/cards/common/CardCover.tsx, packages/shared/src/components/cards/v1/Card.tsx, packages/shared/src/components/cards/v1/CollectionCard.tsx, packages/shared/src/components/cards/v1/SharedPostCardFooter.tsx, packages/shared/src/components/image/VideoImage.tsx
- The primary issue was, that no matter what kind of changes we made for the mobile side, it will never get reflected since we are still using the same component for desktop. Hence, the desktop is getting most of the changes.
- There should be no changes here for desktop.
- On mobile, we are setting the max height to be larger.
Currently deployed on preview3. Quick links:
https://preview3.app.daily.dev/sources/awscommunity
https://preview3.app.daily.dev/sources/fireship
https://preview3.app.daily.dev/squads/ai
https://preview3.app.daily.dev
| Type   | event_name  | …
=> fix: mobile image

packages/storybook/stories/experiments/Helpers.mdx
- Add docs page for our experiment hook and HOCs
- Explains how to use them to make our experiments easier to manage
- Shows some patterns on how to properly allocate users to experiments or delay rendering depending on feature values
- [Preview](https://storybook-git-experiments-helpers-story-dailydotdev.vercel.app/?path=/docs/experiments-helpers--docs)
=> feat: add story for our current experiment helpers

packages/shared/src/components/cards/FeedbackCard.tsx
Fix x on feedback loop https://dailydotdev.slack.com/archives/C01L0QXQJNB/p1709751916071319
=> fix: x feedback loop

packages/shared/src/components/filters/TagsFilter.tsx
- We removed the x spacing on this specific component.
AS-190 #done
=> fix: filter spacing issue

packages/shared/src/components/cards/common/CardCover.tsx
- Fix by making the container a flex div.
Before:
After:
=> fix: share post upvote

packages/shared/src/components/ProfileMenu.tsx, packages/shared/src/components/auth/AuthModal.tsx, packages/shared/src/contexts/AuthContext.tsx, packages/shared/src/hooks/useRegistration.ts, packages/shared/src/lib/user.ts
Adds an optional `reason=something` as a query parameter to the logout request, this is used in API for logout metrics
=> feat: add logout reason to logout request

packages/shared/src/components/modals/NewRankModal.tsx
fix: split if name defined
https://dailydotdev.slack.com/archives/C01L0QXQJNB/p1710834548807209
=> fix: split if name defined

packages/extension/src/lib/extensionScripts.ts
=> fix: prevent injection of scripts over and over

packages/shared/src/components/modals/BasePostModal.tsx, packages/shared/src/components/post/PostContentContainer.tsx, packages/shared/src/components/post/SquadPostContent.tsx
=> fix: modal bg

packages/shared/src/components/Feed.tsx, packages/shared/src/components/drawers/ListDrawer.tsx, packages/shared/src/components/drawers/ListDrawerItem.tsx, packages/shared/src/components/feeds/FeedContainer.tsx, packages/shared/src/components/fields/Dropdown.tsx, packages/shared/src/components/post/write/SquadsDropdown.tsx, packages/shared/src/components/squads/SquadsDirectoryHeader.tsx, packages/shared/src/components/squads/YourSquadItem.tsx, packages/shared/src/components/squads/index.ts, packages/shared/src/hooks/useFeedLayout.ts, packages/shared/src/lib/query.ts, packages/webapp/pages/squads/index.tsx
- Should be ready for initial review but I still have some concerns I will relay to the design team. Regarding width size - so on that side, feel free to ignore it.
- Deployed on preview. Quick link: https://preview.app.daily.dev/squads
Previews:
MI-132 #done
=> refactor: squad directory on tablet and mobile

.github/workflows/add-preview-domain.yml, .github/workflows/remove-preview-domain.yml
😎
https://as-203.preview.app.daily.dev
=> feat: preview domains

packages/shared/src/contexts/WritePostContext.tsx
- Router back when the user clicks cancel.
https://fix-write-post.preview.app.daily.dev
=> fix: cancel button

packages/shared/src/components/auth/AuthOptions.tsx, packages/shared/src/components/auth/AuthenticationBanner.tsx, packages/shared/src/components/auth/OnboardingRegistrationForm.tsx, packages/shared/src/components/widgets/FurtherReading.tsx, packages/shared/src/components/widgets/SimilarPosts.tsx, packages/shared/src/lib/featureValues.ts
- removed PostPageOnboarding.V4 as it was inconclusive
- added PostPageOnboarding.V5
- adjusted auth buttons and text based on PostPageOnboarding.V5
New micro experiment see:
- https://dailydotdev.slack.com/archives/C06K1LYU716/p1710242084719649 
- https://www.figma.com/file/nmfWPS7x3kzLUvYMkBx2kW/daily.dev---Dev-Mode?type=design&node-id=5250-8641&mode=dev
MI-237 #done
https://mi-237-post-page-compact.preview.app.daily.dev
=> feat: post page compact

packages/shared/src/components/auth/OnboardingAnalytics.tsx, packages/webapp/pages/onboarding.tsx, packages/webapp/public/scripts/tiktok.js
Request to add tiktok tracking on onboarding just as we did for gtag and fb and twitter and reddit.
Slack message here: https://dailydotdev.slack.com/archives/C038JGDR2JK/p1711623247480689?thread_ts=1710745205.293519&cid=C038JGDR2JK
https://feat-tiktok-tracking.preview.app.daily.dev
=> feat: new tiktok tracking script

packages/shared/src/styles/base.css
- Small issue
https://fix-highlight-color.preview.app.daily.dev
=> fix: had to be cabbage not bacon

packages/shared/src/components/auth/OnboardingAnalytics.tsx, packages/webapp/public/scripts/tiktok.js
Marketing reinitialized the pixel settings because something was off.
I redid it.
https://tiktok-fix.preview.app.daily.dev
=> fix: tiktok pixel and event

packages/shared/src/components/post/PostContentHeaderMobile.tsx, packages/shared/src/components/post/PostHeaderActions.tsx, packages/shared/src/components/post/collection/CollectionSubscribeButton.tsx, packages/webapp/pages/posts/[id]/index.tsx
- Back button should be displayed.
- Header spacing.
- Header actions button variant.
https://github.com/dailydotdev/apps/assets/13744167/49869932-4462-4e28-8cab-2ada60cae7fc
MI-249 #done
https://mi-249.preview.app.daily.dev
=> fix: post page innaccuracies

packages/extension/src/newtab/App.tsx
Page views on the extension were tracked with the wrong event page for a long time.
This is now fixed, hopefully 😬
https://page-view-fix.preview.app.daily.dev
=> fix: set right event_page for page view events on extension

packages/shared/src/components/squads/Details.tsx
- Nothing changed functionality wise. Just an unused prop.
https://fix-unused-prop.preview.app.daily.dev
=> refactor: unused prop on squad details component

packages/webapp/pages/account/notifications.tsx
- Since we have daily digest as well setting [should be a bit more generic](https://dailydotdev.slack.com/archives/C06L6UB03U0/p1712059710159739?thread_ts=1712037602.731229&cid=C06L6UB03U0)
https://digest-notification-label.preview.app.daily.dev
=> feat: adjust digest notif label to be more generic

packages/shared/src/components/Feed.spec.tsx, packages/shared/src/components/cards/AcquisitionFormCard.tsx, packages/shared/src/graphql/users.ts, packages/shared/src/lib/featureManagement.ts, packages/shared/src/lib/featureValues.ts, packages/webapp/pages/onboarding.tsx
- new values on acquisition card
- remove experiment as this has won
related PR: https://github.com/dailydotdev/daily-api/pull/1796
#done
https://feat-acquisition-form-update.preview.app.daily.dev
=> feat: new values on acquisition card

packages/webapp/components/FooterNavBar.tsx, packages/webapp/components/footer/FooterNavBarV1.tsx
- Apply proper spacing on the footer.
- The changes here helps on actual mobile device.
Previews:
https://fix-footer-spacing.preview.app.daily.dev
=> fix: footer navbar spacing

packages/webapp/components/FooterNavBar.tsx, packages/webapp/components/footer/FooterNavBarV1.tsx
Reverts dailydotdev/apps#2926
there seem to be issues with it https://dailydotdev.slack.com/archives/C0650M2KX8E/p1712305755183529
=> Revert "fix: footer navbar spacing"

packages/webapp/pages/posts/[id]/index.tsx
https://hotfix-canonical.preview.app.daily.dev
=> hotfix: canonical URL

packages/webapp/components/FooterNavBar.tsx
Changes done based on Figma. Related slack discussion: https://dailydotdev.slack.com/archives/C0650M2KX8E/p1712309188705039
MI-278 #done
https://mi-278-new-comment-shadow.preview.app.daily.dev
=> fix: footer navbar new comment button shadow

packages/shared/__tests__/fixture/auth.ts, packages/shared/src/components/auth/RegistrationForm.spec.tsx, packages/shared/src/components/auth/RegistrationForm.tsx, packages/shared/src/components/auth/SocialRegistrationForm.tsx, packages/shared/src/components/profile/ProfileTooltipContent.spec.tsx, packages/webapp/__tests__/AccountProfilePage.tsx, packages/webapp/pages/account/profile.tsx
- Change `full name` to `name`
AS-238 #done
https://as-238-full-name-to-name.preview.app.daily.dev
=> fix: change full name to name

packages/shared/src/components/feeds/FeedNav.tsx
- Fix the glitchy icon when scrolling the screen. See ticket for more details on how to reproduce it. UI-wise, no change.
- `fixed` and `absolute` doesn't work since `sticky` behaves differently (which is the parent element).
MI-268 #done
https://mi-268.preview.app.daily.dev
=> fix: glitchy icon on scroll

packages/extension/src/newtab/MainFeedPage.tsx, packages/extension/src/newtab/ShortcutLinks.spec.tsx, packages/extension/src/newtab/ShortcutLinks.tsx, packages/extension/src/newtab/ShortcutOptionsMenu.tsx, packages/shared/src/components/Icon.tsx, packages/shared/src/components/MainFeedLayout.tsx, packages/shared/src/components/feeds/FeedContainer.tsx, packages/shared/src/components/feeds/FeedNav.tsx, packages/shared/src/hooks/constants.ts, packages/shared/src/hooks/useConditionalFeature.spec.tsx, packages/shared/src/hooks/useConditionalFeature.ts, packages/shared/src/lib/analytics.ts, packages/shared/src/lib/featureManagement.ts
- Added feature for new shortcut system
- Personally find it a little bit messy because of the 3 different placements depending on 3 other experiments 😢  (but for the sake of shipping fast this was the cleanest way)
|--------|------------|-------|
| Change| impression (shortcuts)  | added sources `browser, custom, placeholder, button` |
(Basically it can now trigger 2 impressions (one for the button/placeholder and one for the actual rendered element)
AS-200 #done
https://as-200-shortcut-experiment.preview.app.daily.dev
=> fix: add shortcut experiment version

packages/shared/src/components/feeds/FeedNav.tsx
Different approach to the fix, related to:
- https://github.com/dailydotdev/apps/pull/2960
MI-282 #done
https://mi-282-feed-nav-fix2.preview.app.daily.dev
=> fix: feed nav reacts to route changes

packages/shared/src/components/cards/Card.tsx
- With all the recent changes we had some outdated issue on cards alignment.
- Discussion here: https://dailydotdev.slack.com/archives/C06RTT16F16/p1712729006721939
- So far only the article card was what I found to be off. (Still awaiting full design so we might have more later)
https://hotfix-card-spacing.preview.app.daily.dev
=> fix: card spacing issue

packages/shared/src/components/auth/OnboardingAnalytics.tsx, packages/webapp/pages/onboarding.tsx
- Tracking updates as proposed [here](https://dailydotdev.slack.com/archives/C02AA18RD1D/p1712570146219739)
https://chore-tracking-update.preview.app.daily.dev
=> chore: tracking updates

packages/shared/src/graphql/keywords.ts, packages/shared/src/lib/query.ts, packages/webapp/__tests__/TagPage.tsx, packages/webapp/pages/tags/[tag].tsx
- Decided to split the task to keep the PRs small and easy to review.
- This one introduces the header part on the tag page.
https://as-247-tag-header.preview.app.daily.dev
=> fix: add tag page header changes

packages/webapp/pages/onboarding.tsx
=> chore: turn off hotjar

packages/extension/src/newtab/MainFeedPage.tsx, packages/shared/src/components/BookmarkFeedLayout.tsx, packages/shared/src/components/Feed.spec.tsx, packages/shared/src/components/MainFeedLayout.tsx, packages/shared/src/components/Settings.tsx, packages/shared/src/components/feeds/FeedContainer.tsx, packages/shared/src/hooks/useFeedLayout.ts, packages/shared/src/hooks/useOnPostClick.ts, packages/shared/src/lib/feed.ts, packages/shared/src/lib/query.ts, packages/webapp/pages/[userId]/posts.tsx, packages/webapp/pages/[userId]/upvoted.tsx, packages/webapp/pages/sources/[source].tsx, packages/webapp/pages/squads/[handle]/index.tsx, packages/webapp/pages/tags/[tag].tsx
Reverts dailydotdev/apps#2978
https://revert-2978-mi-254-feed-layout.preview.app.daily.dev
=> Revert "feat: add feed layout without filters"

packages/shared/src/components/tabs/TabList.tsx
Fixed tab indicator not moving to the correct active tab on first click.
- changed from `useEffect` to `useLayoutEffect`, since that's more appropriate to dealing with component refs (e.g. we need to do it after render, not before)
- changed the calculation of the variables based on the ref
- put it in useLayoutEffect as well
- result is set into state - which makes sure the component is rerendered when it happens
https://www.loom.com/share/245f46980c1e42d5ab079b037fb1b006?sid=9458744e-9e4c-4cc0-8e2f-e86926a46f45
MI-298 #done
https://mi-298-fix-comment-active-tabs.preview.app.daily.dev
=> fix: tab list component not showing indicator in correct spot

packages/webapp/components/footer/FooterPlusButton.tsx
- Fix the uneven spacing on the drawer items.
https://fix-drawer-items.preview.app.daily.dev
=> fix: even spacing on plus button drawer

packages/webapp/components/FooterNavBar.tsx
- Update footer navbar for mobile ux background.
- Figma link: https://www.figma.com/file/nmfWPS7x3kzLUvYMkBx2kW/daily.dev---Dev-Mode?node-id=7191%3A25201&mode=dev
MI-279 #done
https://mi-279-background-update.preview.app.daily.dev
=> refactor: footer navbar bg

docker-compose.yml
- To make the upcoming session next week, I am opening this PR.
- The versions are taken from what we have in our `docker-compose.yml` for the api repo. 
https://github.com/dailydotdev/daily-api/blob/d1efcb1a83f3b49408e838d7f8c0c288899255e9/docker-compose.yml#L14-L29
Haven't been able to successfully test this locally, hence, the session.
This is to fix the GitPod concern here: https://github.com/dailydotdev/daily/issues/1094#issuecomment-2035281087 …
=> chore: gitpod settings update

packages/shared/src/components/BookmarkFeedLayout.tsx, packages/shared/src/components/Feed.spec.tsx, packages/shared/src/components/MainFeedLayout.tsx, packages/shared/src/components/feeds/FeedContainer.tsx, packages/shared/src/hooks/useFeedLayout.ts, packages/shared/src/lib/feed.ts, packages/shared/src/lib/query.ts, packages/webapp/pages/[userId]/posts.tsx, packages/webapp/pages/[userId]/upvoted.tsx, packages/webapp/pages/sources/[source].tsx, packages/webapp/pages/squads/[handle]/index.tsx, packages/webapp/pages/tags/[tag].tsx
Reverts dailydotdev/apps#2990
https://dailydotdev.slack.com/archives/C01L0QXQJNB/p1713252987081529
https://revert-2990-mi-254-feed-layout.preview.app.daily.dev
=> Revert "Mi 254 feed layout"

.circleci/config.yml
- Pin the pnpm version to avoid conflicts
https://chore-pin-pnpm.preview.app.daily.dev
=> chore: pin pnpm version

packages/shared/src/graphql/furtherReading.ts
- There are some missing properties from our query.
- Made the properties a part of the Fragment to make it all easier.
MI-304 #done
https://mi-304.preview.app.daily.dev
=> fix: missing query properties

packages/shared/src/components/cards/AcquisitionFormCard.tsx, packages/shared/src/graphql/users.ts
- Change requested from product on [slack](https://dailydotdev.slack.com/archives/C02AA18RD1D/p1713762001610129) 
- see api PR as well https://github.com/dailydotdev/daily-api/pull/1846
MI-328 #done
https://mi-328-user-acquisition.preview.app.daily.dev
=> feat: add youtube instead of x

packages/shared/src/components/auth/OnboardingHeadline.tsx, packages/shared/src/lib/featureManagement.ts, packages/shared/src/lib/featureValues.ts, packages/webapp/pages/onboarding.tsx
onboardinCopy experiment didn't win, PR to clean up. 
See thread for reference: https://dailydotdev.slack.com/archives/C02JAUF8HJL/p1713439790250789
https://chore-remove-onboarding-copy.preview.app.daily.dev
=> chore: remove onboarding copy experiment as it lost

packages/shared/src/components/auth/AuthOptions.tsx, packages/shared/src/components/auth/AuthenticationBanner.tsx, packages/shared/src/components/auth/OnboardingRegistrationForm.tsx, packages/shared/src/lib/featureManagement.ts, packages/shared/src/lib/featureValues.ts, packages/shared/src/lib/image.ts
- remove postPageOnboarding experiment as it lost
- see thread for reference: https://dailydotdev.slack.com/archives/C02JAUF8HJL/p1712560236807179?thread_ts=1712043187.075239&cid=C02JAUF8HJL
https://chore-post-page-compact-banner-cleanup.preview.app.daily.dev
=> chore: remove post page onboaring experiment

packages/shared/src/hooks/useShareComment.ts
- Remove the unwanted extra characters when sharing a comment.
MI-327 #done
https://mi-327.preview.app.daily.dev
=>  fix: copy comment link unnecessary characters

packages/shared/src/components/cards/v1/WelcomePostCard.tsx
- fix: missing spacing on freeform/welcome post card
Preview:
MI-145 #done
https://mi-145.preview.app.daily.dev
=> fix: missing spacing on freeform/welcome post card

packages/shared/src/components/modals/generic/common.ts, packages/shared/src/lib/image.ts
- As the title says.
https://fix-bookmark-loops-image.preview.app.daily.dev
=> fix: bookmark loops popup image and streaks cta

packages/shared/src/components/post/GoBackHeaderMobile.tsx, packages/webapp/__tests__/PostPage.tsx
- There are two things fixed here, one is the design/spacing of the icon itself.
- Second is that it should not be available on laptop.
https://github.com/dailydotdev/apps/assets/13744167/5de66d4a-45a8-4e52-aa54-a7fd747a2e6b
MI-332 #done
https://mi-332.preview.app.daily.dev
=> fix: unwanted logo on laptop

packages/shared/src/components/fields/form/FormWrapper.tsx, packages/shared/src/components/modals/report/ReportModal.tsx, packages/shared/src/components/squads/Details.tsx, packages/shared/src/components/squads/MangeSquadPageSkeleton.tsx, packages/shared/src/components/squads/utils.tsx, packages/webapp/pages/account/profile.tsx, packages/webapp/pages/squads/[handle]/edit.tsx, packages/webapp/pages/squads/new.tsx
- Put the actions on the header even on laptop, then remove the footer.
- Removed a lot of avoidable extra wrappers.
- Cleaned up some unused components after the changes.
Previews:
MI-318 #done
https://mi-318.preview.app.daily.dev
=> refactor: squads creation page

packages/webapp/components/FooterNavBar.tsx
- fixes https://dailydotdev.slack.com/archives/C01L0QXQJNB/p1714114049659419
https://hotfix-footernav-post-page.preview.app.daily.dev
=> fix: navbar footer for mobile

packages/webapp/pages/onboarding.tsx
- https://dailydotdev.slack.com/archives/C01L0QXQJNB/p1714120778069439 fixes dropdown on onboarding
https://hotfix-onboarding-experience.preview.app.daily.dev
=> fix: z-index at onboarding

packages/shared/src/components/notifications/NotificationsBell.tsx
- fix https://dailydotdev.slack.com/archives/C01L0QXQJNB/p1714124833535939
https://hotfix-notification-item.preview.app.daily.dev
=> fix: notification icon

packages/shared/src/components/auth/AuthOptions.tsx
- We [introduced](https://github.com/dailydotdev/apps/commit/7d2dcfdd42c98e27a7837ec8346342d7b99c4ec0) a layout component, but the modals don't use this so it would result in not being available.
- Make it optional to exist or not
https://fix-optional-state-update.preview.app.daily.dev
=> fix: make state update optional

packages/shared/src/components/auth/ReadingReminder.tsx
- We had a prop so just added it. 
AS-230 #done
https://as-230-reading-reminder-scroll.preview.app.daily.dev
=> feat: enable scroll for reading reminder dropdown

packages/shared/src/components/layout/MainLayoutHeader.tsx, packages/shared/src/components/search/SearchContainer.tsx
- fixes https://dailydotdev.slack.com/archives/C01L0QXQJNB/p1714138510191369
https://hotfix-search.preview.app.daily.dev
=> hotfix-search

packages/shared/src/components/profile/source/SourceShortInfo.tsx
- Fixed a small squad handle alignment issue on mobile
| ![Screenshot 2024-04-29 at 08 48 01](https://github.com/dailydotdev/apps/assets/554874/e63d48d3-aa2b-4633-86dd-5c69ff7fc38f) | ![Screenshot 2024-04-29 at 08 48 11](https://github.com/dailydotdev/apps/assets/554874/203d6bfe-5747-456d-a8de-5366c481e737) | 
AS-278 #done
https://as-278-squad-alignment.preview.app.daily.dev
=> fix: squad handle alignment

packages/shared/src/graphql/fragments.ts, packages/shared/src/graphql/squads.ts
- Add the new properties for the squad requests.
MI-321 #done
https://mi-321.preview.app.daily.dev
=> refactor: squad requests to include flags property

packages/shared/src/components/search/SearchPanel/SearchPanel.tsx, packages/shared/src/components/search/SearchPanel/SearchPanelTagSuggestions.tsx, packages/shared/src/components/search/SearchPanel/common.tsx, packages/shared/src/graphql/search.ts, packages/shared/src/hooks/search/useSearchProvider.spec.tsx, packages/shared/src/hooks/search/useSearchProvider.ts, packages/shared/src/hooks/search/useSearchProviderSuggestions.spec.tsx, packages/shared/src/hooks/search/useSearchProviderSuggestions.ts, packages/shared/src/hooks/usePostModalNavigation.ts, packages/shared/src/lib/featureManagement.ts, packages/storybook/stories/experiments/Helpers.mdx
- Add search tags provider to search panel
API needs to be merged to show tag suggestions https://github.com/dailydotdev/daily-api/pull/1870
AS-281 #done
https://as-281-search-tags-provider.preview.app.daily.dev
=> feat(search): add tag provider

packages/shared/src/components/Feed.tsx, packages/shared/src/components/PostOptionsMenu.tsx, packages/shared/src/components/feeds/FeedContainer.tsx, packages/shared/src/components/post/PostEngagements.tsx, packages/shared/src/contexts/ActiveFeedContext.tsx, packages/shared/src/graphql/feed.ts, packages/shared/src/lib/analytics.ts, packages/shared/src/lib/featureManagement.ts, packages/shared/src/lib/query.ts, packages/webapp/pages/posts/[id]/similar.tsx
- Adds a experiment to show similar post feed
- Open point if analytics are needed on [slack](https://dailydotdev.slack.com/archives/C06QH19LR27/p1714746813056189) (but shouldn't block review)
AS-291 #done
https://as-291-similar-post-feed.preview.app.daily.dev
=> feat: added similar post feed

packages/shared/src/components/checklist/EditSquadStep.tsx, packages/shared/src/components/checklist/GoPublicStep.tsx, packages/shared/src/components/checklist/InviteMemberChecklistStep.tsx, packages/shared/src/components/checklist/SharePostChecklistStep.tsx, packages/shared/src/components/checklist/SquadChecklistCard.tsx, packages/shared/src/components/checklist/SquadFirstCommentChecklistStep.tsx, packages/shared/src/components/checklist/actionUtils.ts, packages/shared/src/components/icons/index.ts, packages/shared/src/components/squads/PublicSquadEligibilityCard.tsx, packages/shared/src/components/squads/SquadPostsProgressBar.tsx, packages/shared/src/graphql/actions.ts, packages/shared/src/graphql/sources.ts, packages/shared/src/graphql/squads.ts, packages/shared/src/hooks/useSquadChecklist.tsx, packages/shared/src/lib/checklist.ts, packages/shared/src/lib/constants.ts
- Modified the squad checklist based on [new requirements](https://dailydotdev.atlassian.net/browse/MI-340)
- [Figma designs](https://www.figma.com/file/nmfWPS7x3kzLUvYMkBx2kW/daily.dev---Dev-Mode?node-id=2537-19740&mode=dev)
- Changed the order of steps, removed some steps from the checklist, so that we only have 5
- 2 new steps:
- Edit squad details - is marked as finished when squad has `name`, `description` and `image`. For the `image` field, we compare on the client if it matches the default value in the DB. [Slack discussion here](https://dailydotdev.slack.com/archives/C069XNYMDGV/p1715690893211259).
- Make squad public - marked as finished when squad is public.
MI-340 #done
https://mi-340-squad-checklist-updates.preview.app.daily.dev
=> feat: Modified squad checklist

packages/shared/src/components/modals/squads/SubmitSquadForReviewModal.tsx
Simple copy change.
https://chore-change-tooltip-copy.preview.app.daily.dev
=> chore: change tooltip copy

packages/extension/src/newtab/CustomLinks.tsx, packages/extension/src/newtab/MainFeedPage.tsx, packages/extension/src/newtab/ShortcutLinks.spec.tsx, packages/extension/src/newtab/ShortcutLinks.tsx, packages/shared/src/components/BookmarkFeedLayout.tsx, packages/shared/src/components/Feed.tsx, packages/shared/src/components/FeedItemComponent.tsx, packages/shared/src/components/MainFeedLayout.tsx, packages/shared/src/components/PostOptionsMenu.tsx, packages/shared/src/components/Settings.tsx, packages/shared/src/components/ShareOptionsMenu.tsx, packages/shared/src/components/cards/AcquisitionFormCard.tsx, packages/shared/src/components/feeds/FeedContainer.tsx, packages/shared/src/components/feeds/HorizontalFeed.tsx, packages/shared/src/components/filters/MyFeedHeading.tsx, packages/shared/src/components/layout/common.tsx, packages/shared/src/components/squads/SquadHeaderBar.tsx, packages/shared/src/components/squads/SquadMemberShortList.tsx, packages/shared/src/components/squads/SquadPageHeader.tsx, packages/shared/src/components/utilities/common.tsx, packages/shared/src/hooks/useFeedLayout.ts, packages/shared/src/hooks/useOnPostClick.ts, packages/shared/src/lib/featureManagement.ts, packages/shared/src/lib/featureValues.ts, packages/webapp/pages/[userId]/posts.tsx, packages/webapp/pages/[userId]/upvoted.tsx, packages/webapp/pages/sources/[source].tsx, packages/webapp/pages/squads/[handle]/index.tsx, packages/webapp/pages/tags/[tag].tsx
Reverts dailydotdev/apps#3071
issue here: https://dailydotdev.slack.com/archives/C01L0QXQJNB/p1715866920025429
https://revert-3071-mi-146-list-view.preview.app.daily.dev
=> Revert "feat: add new list feed and adjust feed layout conditions"

.gitpod.yml
- Small hotfix for gitpod to use right version :)
https://hotfix-pnpm-version-gitpod.preview.app.daily.dev
=> hotfix: pnpm version for gitpod

packages/shared/src/components/search/SearchPanel/SearchPanel.tsx, packages/shared/src/lib/featureManagement.ts
- Experiment won, this cleans it up.
AS-325 #done
https://as-325-cleanup-search-tags.preview.app.daily.dev
=> chore: cleanup search tags experiment

packages/shared/src/components/modals/report/ReportComentModal.spec.tsx, packages/shared/src/components/onboarding/FilterOnboardingV4.tsx, packages/shared/src/components/utilities/common.tsx, packages/shared/src/lib/analytics.ts, packages/shared/src/lib/feed.ts, packages/webapp/pages/feeds/[slugOrId]/edit.tsx, packages/webapp/pages/feeds/new.tsx
- Analytics for custom feeds, [see](https://docs.google.com/spreadsheets/d/18Lv7zXges9QfVX5VYL1a-Hyl0e1sQ3sLr0OK8YZWKXI/edit#gid=1128580129)
- Merges into custom feeds epic 🙏 https://github.com/dailydotdev/apps/pull/3106
| New | start custom feed | |
| New | create custom feed | target_id: feedId |
| New | update custom feed | target_id: feedId |
| New | delete custom feed | target_id: feedId |
| Change | any | extra: { feed_id } |
| Change | any | extra: { feed: custom } |
AS-308 #done …
=> feat: custom feeds analytics

packages/shared/src/components/auth/OnboardingAnalytics.tsx
Simplify experience level tracking according to marketing request
https://experience-level-simplification.preview.app.daily.dev
=> refactor: simplify fb tracking

packages/webapp/pages/feeds/[slugOrId]/edit.tsx
- Just adjusting label, requested by Product
https://custom-feeds-edit-label.preview.app.daily.dev
=> feat: adjust custom feeds edit label

packages/shared/src/components/feeds/FeedNav.tsx
- show notification icon in tablet (issue reported here: https://dailydotdev.slack.com/archives/C01L0QXQJNB/p1715498458516419)
https://fix-notification-tablet.preview.app.daily.dev
=> fix: show notification icon on tablet

packages/shared/src/components/auth/ReadingReminder.tsx, packages/shared/src/components/fields/HourDropdown.tsx, packages/shared/src/graphql/users.ts, packages/shared/src/hooks/analytics/useAnalyticsContextData.ts, packages/shared/src/hooks/usePersonalizedDigest.spec.tsx, packages/shared/src/hooks/usePersonalizedDigest.ts, packages/shared/src/lib/analytics.ts, packages/webapp/__tests__/AccountNotificationsPage.tsx, packages/webapp/components/layouts/AccountLayout/AccountContentSection.tsx, packages/webapp/pages/account/notifications.tsx
- Related backend: https://github.com/dailydotdev/daily-api/pull/1932
- Figma: https://www.figma.com/design/nmfWPS7x3kzLUvYMkBx2kW/daily.dev---Dev-Mode?node-id=9439-24492&m=dev
- Streaks is out of scope
- TODO: Analytics seem a bit off, need to sync with Ido I think. 
AS-339 AS-340 #done
https://as-340-notification-settings.preview.app.daily.dev
=> fix: add new notification settings frontend

packages/shared/src/lib/featureManagement.ts, packages/shared/src/lib/featureValues.ts, packages/webapp/pages/onboarding.tsx
- Micro experiment to flip order on onboarding page
<table>
<tr>
<td>Control
<td>Experiment
<tr>
<td><img src="https://github.com/dailydotdev/apps/assets/1681525/5fd42c23-7c53-4510-b14d-f4a8bb4893de">
<td><img src="https://github.com/dailydotdev/apps/assets/1681525/70cdfc63-4390-4bc4-9689-f2391b65cd6d">
</table>
AS-348
https://as-348-flip-onboarding.preview.app.daily.dev
=> feat: micro flip onboarding

packages/shared/src/components/referral/HypeCampaign.tsx
Updates copy on hype campaign CTA
https://as-341-update-copy.preview.app.daily.dev
=> fix: update hype copy

packages/shared/src/graphql/feed.ts
- Adding params to client query that were missing on API so proper resolver is loaded
https://fix-custom-feeds-args.preview.app.daily.dev
=> fix: add custom feed args

packages/shared/src/components/modals/ReputationAlert.tsx
Fixes https://github.com/dailydotdev/daily/issues/1184
https://fix-create-squad-url.preview.app.daily.dev
=> fix: new squad link on community picks warning

packages/shared/src/components/cards/SharePostCard.tsx, packages/shared/src/components/cards/v1/SharePostCard.tsx, packages/shared/src/lib/featureManagement.ts
Makes the shared posts cards look like the article posts cards.
https://dailydotdev.slack.com/archives/C015T1Y237Z/p1715776043294589
AS-349
https://as-349-micro-improve-shared-post-card.preview.app.daily.dev
=> feat: improved shared post cards

packages/shared/src/graphql/fragments.ts, packages/shared/src/graphql/squads.ts
https://fix-created-at-squads.preview.app.daily.dev
=> fix: privileged members should not include created at

packages/shared/src/components/squads/SquadPageHeader.tsx
- Fix unnecessary pointer events on squad status
MI-371 #done
https://mi-371.preview.app.daily.dev
=> fix: unnecessary pointer events on squad status

packages/shared/src/components/buttons/Button.tsx, packages/shared/src/components/cards/survey/FeedSurveyCard.tsx, packages/shared/src/styles/custom.ts, packages/shared/tailwind/boxShadow.ts
I tweaked it a little bit
#3174 
<table>
<tr>
<td>Before
<td>After
<tr>
<td><img src=https://github.com/dailydotdev/apps/assets/1681525/c0a24261-b67a-4383-9c98-2c4bd43edbcc>
<td><img src=https://github.com/dailydotdev/apps/assets/1681525/4065ce4c-38df-4245-8a79-d5c8c50431d2>
</table>
https://mi-355-tweaks.preview.app.daily.dev
=> fix: feed settings survey border tweaks

.github/workflows/remove-preview-domain.yml
Forgot to add the replace on the remove actions
https://fix-domain-unassign.preview.app.daily.dev
=> fix: domain unassign

packages/webapp/pages/account/notifications.tsx
Re-adds the possibility to actually toggle reading reminder that got removed in #3151
https://fix-reading-reminder-toggle.preview.app.daily.dev
=> fix: re-enable reading reminder toggle

packages/shared/src/components/PromotionalBanner.tsx, packages/shared/src/components/layout/MainLayoutHeader.tsx, packages/shared/src/components/post/GoBackHeaderMobile.tsx
- fixes banner on tablet for all pages
https://fix-top-banner.preview.app.daily.dev
=> fix: promotional banner

packages/shared/__tests__/helpers/boot.tsx, packages/shared/src/components/fields/Checkbox.module.css, packages/shared/src/components/fields/Checkbox.tsx, packages/shared/src/contexts/SettingsContext.tsx, packages/shared/src/graphql/users.ts, packages/shared/src/lib/analytics.ts, packages/webapp/__tests__/AccountNotificationsPage.tsx, packages/webapp/pages/account/notifications.tsx
AS-359
Needs https://github.com/dailydotdev/daily-api/pull/1968 to be able to verify the toggle
https://preview.app.daily.dev
=> feat: reading streak reminder toggle

packages/shared/src/components/modals/BootPopups.tsx
- check isActionFetched
https://fix-action-streaks-modal.preview.app.daily.dev
=> fix: check is action fetched

packages/shared/src/components/checklist/SquadChecklistCard.tsx
- Fixed a bg issue on the squad checklist
- The rounded-none is a fix for a nicer border, but required a transparent bg
| ![Screenshot 2024-06-12 at 11 56 43](https://github.com/dailydotdev/apps/assets/554874/10ee6f11-791d-45a2-a533-e0ce80ee676e) | ![Screenshot 2024-06-12 at 11 56 46](https://github.com/dailydotdev/apps/assets/554874/f15cc235-cf91-4398-b8a6-7ccbaa3167ef) |  …
=> fix: squad checklist bg

packages/shared/src/components/search/SearchPanel/SearchPanel.tsx, packages/shared/src/components/search/SearchPanel/SearchPanelContext.ts, packages/shared/src/components/search/SearchPanel/SearchPanelProvider.tsx, packages/shared/src/components/search/SearchPanel/SearchPanelSourceSuggestions.tsx, packages/shared/src/components/search/SearchPanel/common.tsx, packages/shared/src/components/search/SearchPanel/useSearchPanelAction.ts, packages/shared/src/graphql/search.ts, packages/shared/src/hooks/search/useSearchProvider.ts, packages/shared/src/lib/featureManagement.ts
- Add possibility to search for sources
- API changes: https://github.com/dailydotdev/daily-api/pull/1985
AS-371 #done 
https://as-371-search-sources.preview.app.daily.dev
=> feat: add search source suggestions option

packages/shared/src/components/cards/PostCardFooter.tsx, packages/shared/src/components/cards/SharePostCard.tsx, packages/shared/src/components/cards/SharedPostCardFooter.tsx
This reverts commit 18a9d5b21cfc52787ad9fafcbb5725b31b649851.
https://hotfix-card-images.preview.app.daily.dev
=> fix: card images

packages/webapp/pages/devcard.tsx
Bug introduced in the adding streaks in devcard PR since data structure changed. Fixes updating user preferences on devcard
=> fix: update user devcard preferences

packages/shared/src/components/auth/AuthModal.tsx, packages/shared/src/components/auth/AuthOptions.tsx, packages/shared/src/components/auth/AuthenticationBanner.tsx, packages/shared/src/contexts/AuthContext.tsx
- getting email and passing it to the registration form from authentication banner
- Fixes the issue of user going through multiple steps and reentering email
- decision was made to skip the first authentication modal step and move to the second one if the email was already provided 
- issue raised here https://dailydotdev.slack.com/archives/C01L0QXQJNB/p1718282650057529
MI-388 #done
https://fix-email-autocomplete.preview.app.daily.dev
=> fix: email autocomplete

packages/webapp/components/common.tsx, packages/webapp/pages/tags/index.tsx
- sort tags inside groups
- add padding/radius to list items
AS-375 #done
https://as-375-tags-fixes.preview.app.daily.dev
=> feat: tag adjustments
