.stylelintrc, __tests__/CommentActionButtons.tsx, __tests__/MainComment.tsx, __tests__/MainLayout.tsx, __tests__/NewCommentModal.tsx, __tests__/PostPage.tsx, __tests__/ProfileModal.tsx, __tests__/SubComment.tsx, components/AuthContext.ts, components/LoginModal.tsx, components/MainLayout.tsx, components/ProfileModal.tsx, components/Switch.tsx, components/utilities.tsx, lib/constants.ts, lib/user.ts, pages/_app.tsx, pages/posts/[id].tsx
Opens a profile modal when clicking on the profile image.
In addition, added a switch to opt-in/out from marketing emails
=> feat: profile modal

pages/posts/[id].tsx
There was a weird behavior when the post read time is set to zero.
This fix converts read time to boolean to decide whether to show it or not
=> fix: showing 00 when read time is zero

components/MainLayout.tsx, pages/_app.tsx, pages/index.tsx
Add temporary home page with link to the extension
=> feat: home page

__tests__/PostPage.tsx, pages/posts/[id].tsx
=> feat: set post image to be link to the article

components/modals/NewCommentModal.tsx
There was a race condition for the focus between the newly created dialog and its text area element.
The issue was fixed by moving the focus call to the on mounted use effect.
This makes sure that focus will be invoked only after the dialog was created
Closes dailydotdev/daily#246
=> fix: new comment dialog focus issue

components/buttons/BaseButton.tsx, components/buttons/QuandaryButton.tsx, components/cards/PostCard.tsx
Quandary button is based on label elements which does not have the same behavior with buttons and anchors.
This commit add full support for triggering anchor click when the label is clicked
=> fix: quandary button support for anchor elements

.circleci/config.yml
Updates CircleCI config file:
- Update docker image
- change `environment` value from list to map
The `cimg/node` docker image supercedes the legacy CircleCI Node.js image, `circleci/node`.
Early 2020, CircleCI released [smaller, faster, more deterministic images](https://circleci.com/blog/announcing-our-next-generation-convenience-images-smaller-faster-more-deterministic). The node images can be found [here](https://circleci.com/developer/images/image/cimg/node). The intention of this commit is to [optimise the build](https://circleci.com/blog/tips-for-optimizing-docker-builds).
[Reference](https://circleci.com/docs/2.0/configuration-reference/#environment)
=> ci: Update config file

packages/extension/src/manifest.json, packages/shared/src/hooks/useAnalytics.ts, packages/shared/src/lib/analytics.ts
The lazy-load of Amplitude SDK caused a race condition of the first revenue event and initialization.
To fix it we save the events in temporary queue until the client is loaded
=> fix: amplitude race condition

packages/shared/src/components/profile/PostsSection.tsx
Changing the text from "Add your articles retroactively" to "Email us to add your articles retroactively" for extra clarity.
=> Change texts in profile page

packages/shared/src/components/DevCardPlaceholder.tsx, packages/shared/src/components/HeaderRankProgress.tsx, packages/shared/src/components/modals/NewRankModal.tsx, packages/shared/src/components/modals/RanksModal.tsx, packages/shared/src/hooks/useGoToDevCardButton.ts, packages/shared/src/lib/analytics.ts, packages/webapp/pages/devcard.tsx
To expose the Dev Card feature, we embed a dedicated button in the new rank popup and in the ranks instructions.
Amplitude events were added to track the funnel
=> feat: ask to generate dev card in the ranks popups

.idea/dataSources.local.xml, packages/shared/src/components/Feed.spec.tsx, packages/shared/src/components/Feed.tsx, packages/shared/src/components/MainFeedLayout.tsx, packages/shared/src/hooks/useFeed.ts, packages/webapp/pages/_app.tsx, packages/webapp/pages/bookmarks.tsx, packages/webapp/pages/sources/[source].tsx, packages/webapp/pages/tags/[tag].tsx
react-query handles caching, retries, and everything needed to make our app more resilient.
This is a much preferred implementation than using the Fetch API.
=> refactor: use react-query to fetch feed

packages/shared/src/components/cards/PostCard.tsx
Overflowing text will be hidden with ellipsis
=> fix: author name no longer overflows article card

packages/extension/package-lock.json, packages/shared/src/components/modals/LoginModal.tsx
I was exploring the chrome extension interface and, when I tried to log in, I saw these things that might be typos.
The current pull request aims to solve this.
It's worth saying that after I bootstrapped the project, I ran the tests and a bunch of them are giving warnings. One of them is failing: the [PostCard test, in line 109](https://github.com/dailydotdev/apps/blob/master/packages/shared/src/components/cards/PostCard.spec.tsx#L109).  However, it seems to be caused by the function [postDateFormat](https://github.com/dailydotdev/apps/blob/master/packages/shared/src/lib/dateFormat.ts#L8), which is not formatting the date as expected.
Hope I can help!
=> fix: remove typos from LoginModal

packages/webapp/pages/devcard.tsx
When hovering over the devcard, while the image has border-radius as part of the png, the glare on top of the image does not, leaving sharp corners only when hovering. Overflow hidden is added using the tailwind class while the border-radius was added as an inline style
=> Adding border-radius to glare container

packages/shared/src/components/MainLayout.tsx
Issue item: [DD-204 #done](https://dailydotdev.atlassian.net/browse/DD-204)
Removal of the `Win Free Gift` button before the bookmarks button.
Since this is a `shared` component that is used by both `webapp` and `extension`, changes are only needed from this component.
Extension preview:
=> refactor: removal of win free gift button from the extension and webapp

packages/shared/src/components/comments/CommentActionButtons.tsx
Jira Ticket: DD-216#done
After further investigation, it is much better to use the local state declared in the `CommentActionButton` component since it is much expensive to `refetch` the value using `react-query` from the server passing down to where the upvote has happened.
=> fix: update comment upvote label when interaction is made

packages/shared/src/components/comments/PlaceholderComment.tsx, packages/shared/src/components/comments/PlaceholderCommentList.tsx, packages/webapp/pages/posts/[id].tsx
Added a skeleton loader for the comment section of a post
This feature adds a skeleton loader to the post detail page while loading the comments.
It defaults to show three skeletons which are styled according to a potential comment.
DD-62 #done
=> feat: :art: Added skeleton loader

packages/shared/src/components/fields/Switch.tsx, packages/shared/src/components/filters/AdvancedSettings.spec.tsx, packages/shared/src/components/filters/AdvancedSettings.tsx, packages/shared/src/components/filters/FilterMenu.tsx, packages/shared/src/components/filters/FilterSwitch.tsx, packages/shared/src/graphql/feedSettings.ts, packages/shared/src/hooks/useFeedSettings.ts, packages/shared/src/hooks/useMutateFilters.ts
DD-245 #done
Advanced Settings page:
- Created a new property in `feedSettings` which will hold the actual list of advanced settings and the user's preferences itself.
- New component that might be used for future switches namely `FilterSwitch`. The component requires a `title` and `description`.
Enabled = true:
Enabled = false:
Notice the first few articles were tagged as part of "Tech magazines" in my local DB and it went away after the change.
=> feat: advanced settings page

packages/shared/src/styles/base.css
DD-218 #done
`react-modal` attaches a class on the body whenever it is opened, I included some styles to disable scrolling once it happened.
As per the Jira ticket's comment of Tsahi, this should be applied across all popup/modal, hence, did not create any sort of condition.
Reference to the fix applied: https://github.com/reactjs/react-modal/issues/99#issuecomment-265402455
=> fix: body scrolling when modal is open should be disabled

docker-compose.yml
Docker was using our old mysql instance,
switching to Mariadb will actually load on the M1.
=> build: rewrite docker to use mariadb instance

packages/shared/src/components/PostOptionsMenu.tsx, packages/shared/src/hooks/useFeedSettings.ts
We had a issue where the background refetch would happen if you use a block action from the context menu.
This would only happen on the second article in a row.
Due to this, we introduced a new state manager inside the useFeedSettings hook, that is not bound to singular states, making the refresh temporary disabled when using it from there.
Also a super small issue where empty tags where displayed was solved.
=> fix: refetch issue

packages/shared/src/components/fields/AutoCompleteMenu.tsx, packages/shared/src/styles/components/menu.css
The react context menu was wrong for the both search dropdowns.
This fixed that issue by removing the transform for these dropdowns.
DD-306 #done
=> fix: hotfix the search bar position being off

packages/shared/src/components/multiLevelMenu/MultiLevelMenuMaster.tsx
The padding was set on the `li` instead of the button making it non clickable.
DD-308 #done
closing https://github.com/dailydotdev/daily/issues/343
=> refactor: clickable area was wrong for the multi menu master

packages/shared/src/components/fields/Checkbox.tsx, packages/shared/src/components/modals/NewRankModal.tsx
DD-291 #done
In our design spec, our checkbox has `4px` padding = `0.25rem` and a right padding of `12px` = `0.75rem`.
Affected existing implementations:
=> fix: missing padding on checkbox

packages/shared/src/components/filters/TagsFilter.tsx
The tracking was hard coded to "tags search" because of the last change to uniform the tracking.
I've now made this dynamic based on the search query.
Meaning if the search query is active we can assume someone is one the search page.
In this case we should track on "tags search"
Else they are on the main page so track: "tags filter"
DD-309 #done
=> refactor: tracking for tags filter event was always search

packages/shared/src/styles/base.css
DD-311 #done
Removed the `touch-action` property that prevented scrolling on mobile.
Also checked other modals that use scrolling for mobile and it worked.
=> fix: scroll on mobile for modal

packages/extension/src/newtab/MostVisitedSites.tsx, packages/shared/src/components/Feed.spec.tsx, packages/shared/src/components/Settings.spec.tsx, packages/shared/src/components/Settings.tsx, packages/shared/src/contexts/AnalyticsContext.spec.tsx, packages/shared/src/contexts/SettingsContext.tsx, packages/shared/src/graphql/settings.ts, packages/webapp/__tests__/BookmarksPage.tsx, packages/webapp/__tests__/BookmarksSearchPage.tsx, packages/webapp/__tests__/MostDiscussedPage.tsx, packages/webapp/__tests__/MostUpvotedPage.tsx, packages/webapp/__tests__/PopularPage.tsx, packages/webapp/__tests__/RecentPage.tsx, packages/webapp/__tests__/SearchPage.tsx, packages/webapp/__tests__/SourcePage.tsx, packages/webapp/__tests__/TagPage.tsx
DD-252 #done 
We used to have a toggle to turn off the top sites that are shown in the extension.
Since this is an extension only feature, I decided to only show the settings toggle on the extension.
For reference:
The webapp:
Then the default state for the extension:
You can see the toggle default to true and the top sites are shown.
When toggled off the top sites are removed:
Added the following tests 🧪
- Check if the switch is not shown in the webapp
- Check that the switch is shown in the extension
- - And the default is true
- - And that it changes the mutation to false on click
Note:
Be aware I needed to add the `showTopSites` and `toggleShowTopSites` to the SettingsContext so it includes a lot of test where this is added.
=> feat: reintroduced the show top sites toggle in the webapp

packages/shared/src/components/fields/Dropdown.tsx, packages/shared/src/components/profile/ProfileForm.tsx, packages/shared/src/styles/base.css, packages/shared/src/styles/components/menu.css
DD-314 #done 
The current dropdown already uses the new styleguide for formfields.
However, as a quick fix, we decided to make this inline with the overall used form field styles (old one)
This means we now render this dropdown in 15px (callout) instead of the previous body (17px)
Also made sure the content for this scrollable dropdown is rendering in the primary color.
Lastly I've added a new ticket in Jira so we can pick up the new form styleguide.
https://dailydotdev.atlassian.net/jira/software/projects/DD/boards/1?selectedIssue=DD-315
For reference the new render:
=> fix: render the dropdown as primary menu and smaller text

packages/shared/src/components/modals/AccountDetailsModal.tsx, packages/shared/src/components/modals/DeleteAccountModal.spec.tsx, packages/shared/src/components/modals/DeleteAccountModal.tsx, packages/shared/src/components/modals/DeletedAccountConfirmationModal.tsx, packages/shared/src/contexts/AuthContext.tsx, packages/shared/src/lib/user.ts
DD-59 #done
Related PRs:
[API](https://github.com/dailydotdev/daily-api/pull/800) and [Gateway](https://github.com/dailydotdev/daily-gateway/pull/384)
**Description of work:**
Added a danger zone section to the account details modal.
Clicking on delete account will first invoke a confirmation popup
After which a confirmation success popup is shown, clicking this or out of it, will invoke page refresh to cleanup.
**Introduced test:**
`DeleteAccountModal` => This test makes sure the deleteAccount function is called.
**Actions:**
Behind the scenes, this will invoke the `me/delete` endpoint on the Gateway,
This will invoke a cleanup for all gateway tables and send a CDC which tells the API to also cleanup in the background.
=> feat: delete account

packages/shared/src/components/Markdown.tsx, packages/shared/src/components/markdown.module.css
Solved a hotfix for the comment links not opening in a new tab.
Also fixed a small issue with inline code styles.
=> fix: hotfix markdown links

packages/shared/src/components/Feed.tsx, packages/shared/src/components/FeedItemComponent.tsx, packages/shared/src/components/cards/PostCard.spec.tsx, packages/shared/src/components/cards/PostMetadata.tsx, packages/shared/src/hooks/feed/useVirtualFeedGrid.ts
DD-340 #done
The separator now has 2 conditions for whether to be displayed or not.
The article publication date should also now be depending on our flagsmith value.
=> refactor: hide publication date

packages/shared/src/components/modals/ResponsiveModal.tsx, packages/shared/src/components/tooltips/SimpleTooltip.tsx
There was an issue with the re-focus from closing modal which would always trigger the focus on tooltips.
To fix this I introduced a local variable that keeps track if the modal was the previous cause.
Do note we can not solve this with setState as this will not trigger since the component is technically still mounting.
Hate to use `let` here but it seems to be the only viable fix.
See video for resolution: (Tab still works, hover works and refocus doesn't show now)
https://user-images.githubusercontent.com/554874/144201177-42188cae-1dbf-47a5-8d02-54921528a041.mp4
=> fix: fix re focus state for tooltips

packages/shared/src/components/modals/FeedSettingsModal.tsx, packages/shared/src/components/modals/ResponsiveModal.module.css, packages/shared/src/components/modals/ResponsiveModal.tsx, packages/shared/src/components/modals/StyledModal.tsx, packages/shared/src/components/modals/UpvotedPopupModal.tsx
We re-use the responsive modal quite a lot, which is great.
However in some cases we want to remove the main modal's padding as this is per design for the new modal types.
There are quite a lot of these new ones coming, so decided to abstract by adding a padding parameter which is defaulted to true (as still most ones need the padding now)
Example of the first one that doesn't need it is actually the new FeedSettingsModal, but also the UpvotedPopupModal already had a hotfix for this issue.
=> fix: added optional padding to the responsive modal

.idea/vcs.xml, packages/extension/package-lock.json, packages/shared/package-lock.json, packages/shared/package.json, packages/shared/src/contexts/SubscriptionContext.tsx, packages/shared/src/graphql/subscriptions.ts, packages/shared/src/hooks/useSubscription.ts
`subscriptions-transport-ws` is no longer maintained and the suggested package for GraphQL Subscription is now `graphql-ws` which is also supported by our new API.
DD-288
=> refactor: use graphql-ws as new transport layer

packages/extension/src/newtab/MainFeedPage.tsx, packages/shared/src/components/MainLayout.tsx, packages/shared/src/components/PromotionalBanner.tsx, packages/webapp/components/layouts/BookmarkFeedPage.tsx, packages/webapp/components/layouts/MainFeedPage.tsx, packages/webapp/components/layouts/ProfileLayout/index.tsx, packages/webapp/pages/devcard.tsx, packages/webapp/pages/posts/[id].tsx
We had some unused occurrences of the responsive prop for the MainLayout.
This actually broke the layout for the reading history page, as it was not passed.
Since we don't use it anywhere, we decided to remove this prop.
This only caused jest not to acknowledge this component use, so decided to render an empty once in Jest only.
Sidenote:
This is also needed for the re-layout
=> feat: remove all responsive props on the MainLayout

packages/shared/src/components/fields/Dropdown.tsx
DD-351 #done
As reported [in this issue](https://github.com/dailydotdev/daily/issues/373), the content of our `Dropdown` component overflows or breaks up into two lines:
We applied truncating of the content and both cases should now be fixed. The `truncate` class has the following properties:
```
overflow: hidden;
text-overflow: ellipsis;
white-space: nowrap;
```
Preview of the fix:
=> fix: dropdown content overflow

packages/extension/src/newtab/dnd.ts, packages/shared/src/lib/constants.ts
In chrome we use the default new tab as: `chrome-search://local-ntp/local-ntp.html`.
Brave however doesn't provide a inner tab url, so we have to resolve to setting the chrome search default like so: `chrome://new-tab-page`.
I've added a constant check for brave browser.
Running it in Chrome:
And in Brave:
=> fix: fixed a testing case for brave browser

packages/shared/src/components/modals/RanksModal.tsx
There was an issue where a non-logged in user could not click the ranks modal.
Because of a user check that was not optionally chained.
=> fix: hotfix where the timezone can't be read if the user doesn't exist

packages/shared/src/components/TagLinks.tsx, packages/shared/src/components/comments/CommentAuthor.tsx, packages/shared/src/components/comments/MainComment.tsx, packages/shared/src/components/comments/SubComment.tsx, packages/shared/src/components/comments/comments.module.css, packages/shared/src/components/comments/common.tsx, packages/shared/src/components/profile/ProfileImageLink.tsx, packages/shared/src/components/profile/ProfileLink.tsx, packages/shared/src/components/profile/ProfileTolltipContent.tsx, packages/shared/src/components/profile/ProfileTooltip.tsx, packages/shared/src/components/profile/ProfileTooltipContent.spec.tsx, packages/shared/src/components/tooltips/BaseTooltip.module.css, packages/shared/src/components/tooltips/BaseTooltip.tsx, packages/shared/src/components/tooltips/LinkWithTooltip.tsx, packages/shared/src/components/tooltips/SimpleTooltip.tsx, packages/shared/src/graphql/comments.ts, packages/shared/src/graphql/users.ts, packages/shared/tailwind.config.js, packages/webapp/components/CalendarHeatmap.tsx, packages/webapp/pages/posts/[id].tsx
DD-36 #done
I have included a tailwind [extended config](https://github.com/tailwindlabs/tailwindcss/discussions/2727#discussioncomment-686642) that I used to use which has now been merged. But since we haven't upgraded yet. I am applying it explicitly.
New component:
- `ProfileTooltip` - this has all the necessary styling and configuration for a custom tooltip.
Details that must be present in the tooltip:
- Profile picture (rank to be on the lower right corner) - must be a link
- Name - must be a link
- Handle - must be a link
- Bio
I have also refactored the `ProfileLink` component which now doesn't have a `tooltip` (and `disableTooltip` props) out of the box. We made the `tooltip` component a wrapper which if you don't really need it, then just don't wrap the `children` in itself.
I …
=> feat: profile tooltip

packages/shared/src/components/RankProgress.tsx
There was a bug in level up not firing when the previous week rank was the same as the new rank.
Decided to add a double check on this.
Also added a whole section in confluence for all new rank text:
https://dailydotdev.atlassian.net/wiki/spaces/HAN/pages/113901569/Weekly+goal+texts
=> fix: level up bug

packages/shared/src/components/markdown.module.css
With the latest removal of the comment css we missed the actual markdown link color.
Reintroduced it as to color provided in spec.
=> fix: markdown link color was missing

packages/shared/src/components/RankProgress.tsx, packages/shared/src/hooks/useReadingRank.ts
We decided to remove the "reading" part from the text.
This way it will always show up nicely and still inform the user what's going on.
I've also added a check to see if the newly introduced "rankLastWeek" exists in the local cached rank.
If not we should always force update the cache.
This gave a weird effect for users with a old rank that would never correctly update.
=> fix: rank text and cache

packages/extension/package-lock.json, packages/shared/src/components/LoginButton.tsx, packages/shared/src/components/LoginButtons.tsx, packages/shared/src/components/MainLayout.tsx, packages/shared/src/components/modals/LoginModal.tsx, packages/shared/src/lib/analytics.ts, packages/webapp/__tests__/MainLayout.tsx, packages/webapp/pages/register.tsx
We want to try out different copies for the login button in the header.
For this purpose I added a new feature `signup_button_copy` in Flagsmith. This feature will hold the string for the button.
Please note, in mobile resolution we will keep the current copy due to space restrictions.
I also migrated the relevant signup events to our in-house analytics tracking so we can monitor the performance of the experiment.
DD-362 #done
=> refactor: signup button copy experiment

packages/shared/src/components/Feed.tsx, packages/shared/src/components/HeaderRankProgress.tsx, packages/shared/src/components/LoginButton.tsx, packages/shared/src/components/MainFeedLayout.tsx, packages/shared/src/lib/featureManagement.ts
Following Lee's suggestion, I introduce a new enum that will make it easy to use feature flags.
=> refactor: use features enum to store available flags

packages/shared/src/components/PostsSearch.tsx, packages/shared/src/components/sidebar/Sidebar.spec.tsx, packages/shared/src/components/sidebar/Sidebar.tsx, packages/shared/src/components/sidebar/common.tsx, packages/webapp/components/RouterPostsSearch.tsx, packages/webapp/components/layouts/BookmarkFeedPage.tsx, packages/webapp/pages/history.tsx
In this PR we are fixing some edge-cases and re-evaluated the test cases we had.
The cases actually seem significant enough.
Decided to add a mobile render check for the sidebar to see if we are not breaking the mobile version.
- 0553e88add3d8e92b87bba3bdb65f4fac00491eb -> Added more space according to SC for the mobile version
- 8e89d4eae50933ddb1fcf149bf8eb07d37c95c2f -> Mobile backdrop was visible on desktop if you expand from mobile to desktop
- 275a38f96049cf01f1b939d8e789a9101919891b -> Reading history alignment was not set
- 22473237770ba8bee92b8aa86b3f881e0e5aaa2c -> Added a autoFocus attribute for the postSearch component
- 3c74a7d9fee0918135bc5b82245f13222a6e363f -> Added the mobile render test case for the sidebar
DD-350 #done
=> feat: test and fixes

packages/shared/src/components/sidebar/Sidebar.tsx, packages/shared/src/components/sidebar/common.tsx, packages/shared/src/styles/base.css
We had some issues with the mobile sidebar height on the mobile view because of the 100vh usage.
Also the share link was invisible on mobile devices.
Introducing a fallback for Safari to fix the push of the sidebar height.
=> fix: mobile sidebar height and invisible share text

packages/extension/src/newtab/App.tsx, packages/shared/__tests__/setup.ts, packages/shared/src/components/Settings.spec.tsx, packages/shared/src/components/Settings.tsx, packages/shared/src/contexts/BootProvider.tsx, packages/shared/src/contexts/SettingsContext.tsx, packages/shared/src/lib/boot.ts, packages/webapp/pages/_app.tsx
DD-337 #done
As part of serving the user's settings in a much faster time, we decided to move it to the boot query.
Since I was already working on the `SettingsContext`, I took the opportunity to refactor and apply some types with the strings we work with.
It may be noticed that the `const isExtension = process.env.TARGET_BROWSER;` was taken inside the component, the test was failing due to the fact the value was generated when we run the test, and simply overriding the value make it fail. So the component has to check it by the runtime to see if it actually has the correct value.
The related `boot` changes PR is now just waiting for additional checks but this should be safe for review. Related PR:
https://github.com/dailydotdev/daily-gateway/pull/394
=> refactor: user settings in boot query

packages/shared/src/components/ShareBar.tsx, packages/shared/src/lib/share.ts, packages/webapp/pages/posts/[id].tsx
When `window` is not yet defined, the shareable link can't be fetched yet.
=> fix: window is not defined yet on shareable link

packages/shared/src/components/modals/ResponsiveModal.module.css, packages/shared/src/components/modals/ResponsiveModal.tsx, packages/shared/src/components/modals/StyledModal.tsx
The values for responsive modal are being overridden due to the class selector prioritization.
Now we have added another selector to have higher priority when using `StyledModal`
Before:
Preview:
=> fix: responsive modal class selector prioritization

.idea/vcs.xml, packages/shared/package-lock.json, packages/shared/src/components/sidebar/Sidebar.tsx
`useNavButtonsNotLinks` was applied on all the actions even though some of them had to be links in the extension.
This PR splits the usage of this property between the different sections.
DD-376 #done
=> fix: use links instead of buttons for sidebar actions

packages/shared/src/components/ProfileMenu.tsx
DD-386 #done
Fix logout crash on the mobile version. The profile menu is rendered even when user is not available.
=> fix: profile menu to not render when user is empty

packages/shared/src/components/sidebar/Sidebar.tsx, packages/shared/src/components/sidebar/common.tsx, packages/webapp/pages/posts/[id].tsx
Fixed a placement issue of the mobile article page not being full width
Tooltip minimized hover was not covering the full space
=> fix: hotfixes relayout

packages/shared/src/components/ShareBar.tsx
Preview before the fix:
Preview after the fix:
=> fix: sharebar copied text placement

packages/shared/src/components/utilities.tsx
The new adjustments in auto flowing width for mobile where pushing the tablet size to not center.
Used the same approach as the main content part for rendering it correctly on all sizes.
=> fix: hotfix for the article view on tablet screens

.idea/vcs.xml, packages/shared/src/contexts/AlertContext.tsx, packages/shared/src/contexts/BootProvider.tsx
Due to our recent change in the boot provider, we mistakenly renamed the `updateAlerts` function.
It caused critical errors throughout the app when trying to call this function as it was undefined.
The most common case is when the feed filters had the alert on and the app need to turn off this alert by dispatching the call.
Key learning here is to use explicit types in functions like `useMemo` and create test cases to prevent it.
=> fix: update alerts function was not defined in the alerts context

packages/extension/package.json, packages/shared/src/components/LoginButton.tsx, packages/shared/src/components/MainLayout.tsx, packages/shared/src/components/sidebar/SidebarUserButton.tsx, packages/webapp/__tests__/MainLayout.tsx
Added the login button flagged version to be uniform.
Do note for the mobile sidebar version it will always render "Login" but at least this makes everything loaded from 1 component now.
DD-390 #done
=> fix: fix flagged version of login button

packages/shared/src/contexts/BootProvider.tsx
The cached data would be overwritten while updating on slow connections.
We introduced a temporary update state that has priority.
=> fix: on slow devices the boot would load after update overwritting

packages/shared/src/contexts/AuthContext.tsx
The reason for getting stuck on logout while at the registration page is we do `reload` only when logging out.
To better catch the case, we first check
- if there is any `redirect_uri` to utilize for redirection.
- if none - we redirect to our app's home page if it is logging out at the registration page (just to make sure to catch all cases).
- else we reload like how it is supposed to be before
=> fix: registration stuck-up on logout

packages/shared/src/contexts/AlertContext.tsx, packages/shared/src/contexts/BootProvider.tsx, packages/shared/src/hooks/useReadingRank.ts
DD-393 #done
The previous mechanism for identifying the `rankLastSeen` [was removed](https://github.com/dailydotdev/apps/pull/763/files#diff-591811d5ed8112fe53d4882f8cfd46634f04cb39e40a12c0086ef7fe21510158L76-L84) but I have also realized to use the same process the other providers do when checking for the remote value's availability.
=> fix: devcard notif should not show when explicitly defined

packages/shared/src/components/utilities.module.css, packages/shared/src/components/utilities.tsx, packages/webapp/components/posts/NewComment.tsx, packages/webapp/components/posts/PostWidgets.tsx, packages/webapp/pages/posts/[id].tsx
DD-392 #done
This might require a bit of focus when reviewing (sorry about that) since I have refactored the classes and made the containers to use fewer and simple classes as much as possible.
Also, instead of applying the classes in one line (if there's a lot of differences), with `classed` I realized it accepts a rest argument which we can utilize to separate the different screen classes (as it is a bit difficult for complex layouts in one line) for easier understanding and readability. But it depends if it makes sense, probably just my personal pov.
```
classed(
'tag',
'base classes'
'laptop classes',
'tablet classes'
)
```
The jumpy widgets' container was caused by the `right-0` position which sets the element to the edge initially.
I have used flexbox so it will automatically set …
=> refactor: article page classes layout

packages/shared/src/contexts/AuthContext.tsx, packages/webapp/pages/_app.tsx
Clicking the logout button on registration already works on the extension, but on the webapp, there needs an additional check whether we should `reload` to clear the local state and data (as it doesn't automatically clear up by the `window.location.replace` which should have been).
I have also found a bug (which I don't know if this should be directed at `nextjs` repo). In our `_app.tsx` file, it should detect when the user has arrived - like `window.location.reload` it goes through the `useEffect` as mentioned before it should also happen with `window.location.replace` since we are not using the `next/link` or `next/router` which is the native redirect to keep all local state and data.
Reproducing the bug mentioned above:
1. Register
2. Once the form is displayed, click our dailydev logo …
=> fix: redirect user to registration if not yet confirmed

packages/shared/src/components/utilities.tsx
There was an overhaul with the classes on the article page and to support backward compatibility for other pages, we will have to keep a class that to keep different pages centered as default.
=> fix: backwards compatibility - page to be centered

packages/shared/src/components/Settings.spec.tsx, packages/shared/src/components/sidebar/Sidebar.spec.tsx, packages/shared/src/contexts/BootProvider.tsx, packages/shared/src/contexts/SettingsContext.tsx
DD-399
Explicit test cases to ensure whenever new changes are introduced things won't be broken.
We have realized the two items below require attention:
- should utilize default front-end settings for a first-time user.
- should not override settings for an anonymous user and utilize local settings.
- should call `updateAlerts` with mock
~~should keep the stored local version on double execution (still discussing with Chris about this case)~~
=> test: update local alerts and mutation to be called

packages/webapp/pages/posts/[id].tsx
We introduced a `tablet:self-center` on the PageContainer class, however for the article page this needs to stretch on laptop devices.
There are edge cases where the sidebar would be longer than the main part, forcing this to "center" while we want to stretch this to get the borders show fully.
DD-426 #done
=> fix: :lipstick: Fixing the article position

packages/shared/src/components/history/ReadingHistory.spec.tsx, packages/shared/src/components/profile/ProfileForm.tsx, packages/shared/src/lib/dateFormat.spec.ts
Renamed the newsletter subscribe option from `Weekly Recap` to `Community Newsletter`
=> fix: updated the name of the newsletter subscription

packages/shared/src/components/sidebar/MyFeedButton.tsx, packages/shared/src/components/sidebar/Sidebar.spec.tsx, packages/shared/src/components/sidebar/Sidebar.tsx, packages/shared/src/components/sidebar/common.tsx, packages/shared/src/lib/featureManagement.ts
This PR introduces the MyFeedButton component.
This component can render based on the alert flag.
1. User already filtered something:
2. User hasn't filtered yet
Option 1 will show the My feed button
Option 2 will show the flagged text component.
The different states:
Filtered expanded:
Filtered small:
Unfiltered expanded:
Unfiltered small:
For this component we also introduced 4 new flagsmith values:
1. MyFeedButtonCopy = 'my_feed_button_copy',
2. MyFeedButtonColor = 'my_feed_button_color',
3. MyFeedExplainerCopy = 'my_feed_explainer_copy',
4. MyFeedExplainerColor = 'my_feed_explainer_color',
=> feat: added the MyFeedButton component

packages/shared/src/components/sidebar/MyFeedButton.tsx, packages/shared/src/components/sidebar/Sidebar.spec.tsx, packages/shared/src/components/sidebar/Sidebar.tsx, packages/shared/src/lib/featureManagement.ts
We accidentally removed the feed filter option for people who have the AB test set to false.
This PR reintroduces it.
By doing so we had to re-arrange the flag loading a bit.
DD-447 #done
=> fix: re-add the feed filters if the user has the ab test set to off

packages/shared/src/components/Feed.tsx, packages/shared/src/components/LoginButton.tsx, packages/shared/src/components/MainFeedLayout.tsx, packages/shared/src/components/modals/LoginModal.tsx, packages/shared/src/lib/featureManagement.ts
We decided to convert the existing Features Enum into a object containing the Flagsmith ID and the default value.
This way we remove any friction and make this file the single source of truth around flags.
Since a enum can't contain arrays of objects and a const object would introduce some changeable options I've decided to go for this class approach.
This gives us the abilities of an enum, while maintaining the dynamics of objects.
DD-448 #done
=> feat: Added a features class to maintain default states in one place

.idea/vcs.xml, packages/shared/src/hooks/analytics/useAnalyticsContextData.ts, packages/shared/src/hooks/analytics/useAnalyticsSharedProps.ts, packages/shared/src/hooks/analytics/useTrackLifecycleEvents.ts
Duration-based events capture the page state at the time when the event starts. This can create cases where at first the page state was passive (open new tab) so all the impressions are marked as passive, and then the user decided to focus on the tab and continue their use on our platform. So in this case we want to mark all these impressions as active impressions or any other event for that matter.
Another important change is to mark events as active if the user scrolled down the page. Even if the page state is passive the user can still scroll it. I think that if the user scrolls it means that they're active and we should adjust the state accordingly.
=> refactor: update page state for duration based events

packages/extension/src/newtab/MainFeedPage.tsx, packages/shared/src/components/MainFeedLayout.tsx, packages/shared/src/components/sidebar/MyFeedButton.tsx, packages/webapp/__tests__/MyFeedPage.tsx, packages/webapp/__tests__/PopularPage.tsx, packages/webapp/components/layouts/MainFeedPage.tsx, packages/webapp/pages/feed/[feedId].tsx, packages/webapp/pages/my-feed.tsx
DD-428 #done
DD-430 #done
A dedicated page for "My Feed" page/tab under `my-feed` route.
This PR also refactored the usage of popular page/tab to utilize anonymous feed query.
=> feat: my feed page

packages/shared/__tests__/setup.ts, packages/shared/src/components/Feed.spec.tsx, packages/shared/src/components/PostOptionsMenu.tsx, packages/shared/src/components/filters/AdvancedSettings.spec.tsx, packages/shared/src/components/filters/AdvancedSettings.tsx, packages/shared/src/components/filters/BlockedFilter.spec.tsx, packages/shared/src/components/filters/BlockedFilter.tsx, packages/shared/src/components/filters/FeedFilters.tsx, packages/shared/src/components/filters/FilterMenu.tsx, packages/shared/src/components/filters/TagsFilter.spec.tsx, packages/shared/src/components/filters/TagsFilter.tsx, packages/shared/src/components/filters/common.tsx, packages/shared/src/components/sidebar/Sidebar.spec.tsx, packages/shared/src/graphql/feedSettings.ts, packages/shared/src/hooks/useFeedSettings.ts, packages/shared/src/hooks/useMutateFilters.ts, packages/shared/src/hooks/useReportPost.ts, packages/shared/src/hooks/useTagAndSource.ts, packages/shared/src/lib/storageWrapper.ts, packages/webapp/__tests__/SourcePage.tsx, packages/webapp/__tests__/TagPage.tsx
DD-430 #done
[DD-442](https://dailydotdev.atlassian.net/jira/software/projects/DD/boards/1?selectedIssue=DD-442) #done - pre-existing issue (unblock a tag)
[DD-445](https://dailydotdev.atlassian.net/jira/software/projects/DD/boards/1?selectedIssue=DD-445) #done - pre-existing issue (reporting and hiding post)
[DD-446](https://dailydotdev.atlassian.net/jira/software/projects/DD/boards/1?selectedIssue=DD-446) #done - pre-existing issue (blocking a source and a tag)
This includes quite a few fixes since I was on it already and have thought of fixing it along the way.
The issues were:
- Unblock a tag on context menu after searching a tag
- Reporting a post as an anonymous user
- Hiding a post as an  anonymous user
- Blocking a tag as an  anonymous user
- Blocking a source as an anonymous user …
=> refactor: local storage utilization for feed filters

packages/webapp/components/posts/PostHeader.tsx
For some reason we had a check if the author was known.
If not we would never link to the source feed.
We can safely remove this check, which this PR does.
DD-400 #done
=> fix: the source was not always linking to the source feed

packages/shared/src/components/filters/FeedFilters.tsx, packages/shared/src/components/sidebar/MyFeedAlert.tsx, packages/shared/src/components/sidebar/MyFeedButton.tsx, packages/shared/src/components/sidebar/Sidebar.spec.tsx, packages/shared/src/components/sidebar/Sidebar.tsx, packages/shared/src/hooks/useFeedSettings.ts
DD-457 #done
DD-455 #done
~~Currently, the decision to identify whether the user has any filter is based on the `alerts.filter` which is used to display alerts, for us to declare a user has any filter is to check if there's an actual filter applied on their feed settings. The case results in the "My Feed" not being displayed.~~
Also, I noticed a false positive in one of the test cases namely `should remove feed filter button once user has filters`
I think the primary purpose of this test is to see that the button is not rendered anymore since the user has an existing filter. With that, it clicks the "Create my feed" button which should have not been there in the first place. Then it tests the `updateAlerts` to be called which should only happen when the user has clicked the close button …
=> fix: navigation not shown even when user has filters

.circleci/config.yml
Added a new job to test the build of the extension.
It happened in the past we introduced a breaking change only on the extension part, and it's critical to catch these issues early on.
This PR introduces a new job that runs parallel to the tests *(and uses the same cache in available)
DD-342 #done
=> Dd 342 extension build

packages/webapp/components/posts/AuthorOnboarding.tsx
The author onboarding element was missing spacing.
Added a margin bottom to offset it from the new comment block.
Laptop size:
Tablet size:
Mobile size:
DD-453 #done
=> fix: added spacing to the author onboarding element

packages/shared/src/components/profile/ProfileForm.tsx, packages/shared/src/contexts/BootProvider.tsx
When the registration finishes and we proceed with the redirection the boot query is not being requested which should actually happen as the data were updated (even on window.location.replace the state doesn't refresh).
For the accurate alerts to be displayed right after registration, the user needs to refetch the boot data.
=> fix: boot data invalidation

packages/shared/postcss.config.js
A hotfix for the extension to use the double require import, where next will handle it for us.
=> fix: postcss fix for the extension

packages/shared/src/components/sidebar/MyFeedButton.tsx, packages/shared/src/components/sidebar/Sidebar.tsx
Just as on our current implementation, we are not allowing feed filters to be changed on mobile hence, not seen in my feed nav item.
Preview:
=> fix: rendering my feed nav item on mobile

packages/shared/src/lib/featureManagement.ts
When I set up my new Mac and bootstrapped from scratch our development environment, I noticed that I receive critical errors on the first load. This happened when trying to access the flags object when it is still null. I use optional chaining to make sure we handle these situations correctly.
=> fix: access safely to the flags object

packages/shared/src/hooks/analytics/useTrackLifecycleEvents.ts, packages/shared/src/lib/lifecycle.ts
Our feed engine uses the client's indication of whether the session is active or not for certain decisions.
After some data analysis and debugging, I found out that there's some issue in how we track it.
The edge case opens new tab -> type URL -> navigate to the new URL will be marked as an active session.
This fix makes sure the user clicked somewhere in the window object or at least scrolled down a bit before the session was marked as active.
I also fixed an edge case where events were not sent on page unload.
=> fix: track active page state correctly

packages/shared/src/components/MainFeedLayout.tsx
Since we have changed the text for the label on our default feed algorithm, it expanded.
Before:
After:
=> fix: feed algorithm dropdown ui glitch

packages/shared/src/components/cards/CommentPopup.tsx, packages/shared/src/components/modals/NewCommentModal.spec.tsx, packages/shared/src/components/modals/NewCommentModal.tsx
DD-476 #done
On submitting a comment - it should return as soon as the input is noticed to be empty or contains spaces only.
=> fix: spaces only comment

packages/shared/src/components/MainFeedLayout.tsx
We where using a `gap-4` which caused all individual items in the most visited sites to space out.
I've decided to add separate margins to the dropdowns.
And add a items align so they are centered with the button.
Before:
After:
DD-478 #done
=> fix: :bug: Fixed a bug in the most visited sites stack

packages/shared/src/components/InteractionCounter.tsx, packages/shared/src/components/cards/Card.module.css, packages/shared/src/components/cards/Card.tsx, packages/shared/src/components/cards/TrendingFlag.tsx, packages/shared/src/components/comments/common.tsx, packages/shared/src/components/fields/Dropdown.tsx, packages/shared/src/components/filters/TagButton.tsx, packages/shared/src/components/filters/TagCategoryDropdown.tsx, packages/shared/src/components/modals/NewCommentModal.module.css, packages/shared/src/components/modals/NewCommentModal.tsx, packages/shared/src/components/multiLevelMenu/MultiLevelMenuDetail.tsx, packages/shared/src/components/multiLevelMenu/MultiLevelMenuMaster.tsx, packages/shared/src/components/profile/PostsSection.tsx, packages/shared/src/components/profile/ProfileTolltipContent.tsx, packages/shared/src/components/profile/common.module.css, packages/shared/src/components/profile/common.tsx, packages/shared/src/components/sidebar/common.tsx, packages/shared/src/styles/components/menu.css, packages/shared/src/styles/utilities.css, packages/webapp/components/KeywordManagement.tsx, packages/webapp/components/widgets/BestDiscussions.tsx, packages/webapp/components/widgets/SimilarPosts.tsx, packages/webapp/pages/404.tsx
Since the Tailwind `break-words` is broken by design, we decided to take hands in own matters and override those to make them do what they promise.
Giving us the `break-words` class to break words and `break-words-overflow` to define the overflow for breaking words.
I also took the liberty in this PR to clean-out no longer needed Tailwind classes for `transform`.
And found a couple weird edge cases I fixed:
1. When posts had the hot filter they did not match the full height:
(Fixed by adding the h-full to the card)
Related the z-index was off, so decided to force to `-1` to always be behind the cards
2. Profile bio had no overflow:
Fixed by adding `break-words`
=> fix: cleanup tailwind classes

packages/shared/src/components/filters/FeedFilters.tsx, packages/shared/src/components/sidebar/MyFeedButton.tsx
We removed the Feed Filter Button from rendering on the mobile version.
This made it impossible for people to open the feed filters from the menu.
I've added this button on the mobile version now.
DD-484 #done
=> fix: :lipstick: Feed Filter Button was not showing on mobile

packages/shared/src/components/cards/ShowMoreContent.tsx, packages/webapp/__tests__/PostPage.tsx
Fixing a bug when the summary is cut if not reaching threshold (300-350 characters).
=> fix: cut summary when not reaching threshold

packages/shared/src/hooks/useFeed.ts
We had an issue where the ad infinite query would not load on time.
this introduces a useEffect way of reloading the ads if they take longer than the next feed page.
=> hotfix: ad load

packages/shared/src/components/sidebar/MyFeedButton.tsx, packages/shared/src/components/sidebar/common.tsx
We weren't checking if the sidebar rendered value was false, this could cause the feed filter button to disappear on mobile devices.
DD-494 #done
=> fix: mobile feed filter button was not always rendering

docker-compose.yml
People where not able to spool up the apps docker image.
As mentioned before, might be worthwhile moving away from it at one stage, or rework how we want people to use it.
We don't actively maintain this image and every change on the API/Gateway can break this behaviour.
For now this fix will make sure it's up to date again.
=> chore: the docker postgres images was outdated

packages/extension/src/newtab/ShortcutLinks.spec.tsx, packages/shared/src/components/Feed.spec.tsx, packages/shared/src/components/Settings.spec.tsx, packages/shared/src/components/Settings.tsx, packages/shared/src/contexts/BootProvider.spec.tsx, packages/shared/src/contexts/SettingsContext.tsx, packages/shared/src/graphql/settings.ts
This PR adds the new toggle for Weekly goals widget in Customize settings. It is enabled by default and is toggable only for logged in users.
Untoggled:
Toggled:
Added the unit tests as well.
Comment: for the other toggles only the capital letter is in upper case. "Show Weekly goal widget" title seems inconsistent. WDYT?
DD-506 #done
=> feat: add weekly goals toggle in customize settings

packages/shared/src/components/fields/TextField.spec.tsx, packages/shared/src/components/fields/TextField.tsx, packages/shared/src/components/fields/common.tsx, packages/shared/src/components/profile/ProfileForm.tsx, packages/shared/src/hooks/useInputField.ts
The primary change to look for is the variation of the font colors based on which `fieldType` the input is. The `tertiary` is a new addition that is used already in the custom links so there are no pre-existing implementations of it.
The `compact` property is now gone and was replaced by being the `secondary` field type.
Primary is the common and default implementation of the text field.
This now supports icons inside the text field itself and the padding varies between having one or not.
- Did you introduce testing for this PR
- ☑️ Did you test the webapp? **Yes**
- ☑️ Did you test the extension? **Yes**
DD-495 #done
**Note:** just waiting for Tsahi's answer regarding the right icon but this should be alright to be reviewed.
=> refactor: text field guideline update

packages/shared/src/components/modals/SharedBookmarksModal.tsx
- Describe what this PR does
A notif when the user has clicked copy to clipboard. The design is based on how we display in `ShareBar` notif.
=> refactor: copied notif when copy to clipboard is clicked

packages/shared/src/components/SidebarRankProgress.spec.tsx, packages/shared/src/hooks/useReadingRank.ts
The current implementation breaks if the previous cache version is present.
I changed the cache key to fix this issue and ignore the existing cache.
=> fix: update cache key to prevent client error

packages/shared/src/lib/rank.ts
- Describe what this PR does
The app crashes on load for someone who has a legendary status the week prior.
=> fix: rank steps to display when legendary the week prior

packages/shared/src/components/history/ReadingHistoryItem.tsx, packages/webapp/pages/posts/[id].tsx
- Fallback image when the post doesn't have a banner image
Quick link: https://daily-webapp-e3cq2jddo-dailydotdev.vercel.app/posts/ziY-dEmqA
=> fix: fallback image for article without banner image

packages/shared/src/components/RankProgressWrapper.tsx, packages/shared/src/components/modals/RanksModal/RankBadgeItem.tsx, packages/shared/src/components/modals/RanksModal/RanksBadges.tsx, packages/shared/src/components/modals/RanksModal/common.tsx, packages/shared/src/components/modals/RanksModal/index.tsx, packages/shared/src/lib/rank.ts
The radial progress color must be consistent with the color in the sidebar. There's a discrepancy when the user is trying to re-earn the previous rank.
Fixed preview:
=> fix: radial progress color

packages/shared/src/components/modals/ModalCloseButton.tsx, packages/shared/src/components/modals/NewRankModal.tsx
- Realised we had this issue open in regards to the new rank modal, so perfect time to fix it.
- Is was possible for the rank text to be overlapping the close button
- By setting a fixed z-index we ensure it's always higher.
DD-499 #done
=> fix: in some cases the close button was below the rank text

packages/shared/src/components/modals/ModalCloseButton.tsx
- We removed the absolute position on the close button breaking the implementation
- Changed it back to absolute
- Fixed the position for the bookmarks (it was off from the top)
=> fix: :bug: We introduced a breaking close button in the bookmark branch

packages/shared/src/components/RankProgressWrapper.tsx, packages/shared/src/components/modals/RanksModal/RanksBadges.tsx, packages/shared/src/components/modals/RanksModal/common.tsx, packages/shared/src/components/modals/RanksModal/index.tsx
- We did not take the previous rank into account when it comes to the re-earn for the popup.
- Also fixed the state of the badges in the popup
=> fix: :bug: Fix the re-earn state for the popup modal

packages/shared/src/components/MainFeedLayout.tsx
- Forgot to add the actual filter check on the feed options
- This let to the button always to show, even when you filtered before.
=> fix: forgot to check the my feed button should actually be rendered

packages/webapp/pages/devcard.tsx
The sidebar overlaps on the content - we have now changed the breakpoints.
Max size before breaking:
=> fix: devcard overlap on sidebar

packages/shared/src/components/Rank.tsx, packages/shared/src/components/RankProgress.tsx, packages/shared/src/components/RankProgressWrapper.tsx, packages/shared/src/components/modals/NewRankModal.tsx, packages/shared/src/components/modals/RanksModal/RankBadgeItem.tsx, packages/shared/src/lib/rank.ts
- We didn't implement `getRank` everywhere 
- In this case it was failing in the `NewRankModal`
- `You earned the {RANKS[rank - 1].name?.toLowerCase()} rank`
- Should have been:
- `You earned the {RANKS[getRank(rank)].name?.toLowerCase()} rank`
The case is that for rank 0 it will try and get -1 which doesn't exists.
Because of this danger I decided to implement the `getRank` function everywhere this pattern was used.
It can't really break since it will check if it's 0 or not.
Tested for these use-cases on webapp and extension now.
=> fix: :bug: Fix breaking on non-existing rank call

packages/shared/src/components/MainLayout.tsx, packages/shared/src/components/MobileHeaderRankProgress.tsx
- We always rendered the mobile header rank wrapper
- This wrapper contains the `NewRankModal` so it would show up twice on desktop.
- Added a `sidebarRendered` prop to it so it will render the empty wrapper on desktop.
=> fix: :bug: Making sure the mobile rank only shows on mobile

packages/extension/src/newtab/CustomLinks.tsx, packages/shared/src/components/CreateMyFeedButton.tsx, packages/shared/src/components/MainFeedLayout.tsx
- Custom links should be hidden on tablet and below
- The dropdown should be in the same row with the title always
Previews:
=> fix: feed page header content placement

packages/shared/src/components/profile/ProfileTooltip.tsx, packages/shared/src/graphql/users.ts, packages/webapp/package-lock.json, packages/webapp/package.json, packages/webapp/pages/[userId]/index.tsx
- Profile Tooltip query to utilize version 2 of the reading rank
- Have also checked all existing implementations of query for `useReadingRank` all seem to use v2 now.
- Fixes the lacking of space in heatmap tooltip label
- Removed unused package
=> fix: profile tooltip rank version

packages/shared/src/components/MainFeedLayout.tsx
- Since we fixed the search bar to `flex-1` we actually had to make sure the header spans 100% of the width.
- It's the `LayoutHeader` which is only used on the feed pages and tested as you can see in the screens.
DD-559 #done
=> fix: width of the search bar

packages/shared/src/components/SidebarRankProgress.spec.tsx, packages/shared/src/hooks/useReadingRank.ts
- fixed a condition where it always passes when since the user is not yet loaded when triggered
DD-565 #done
=> fix: flaky tests for rank-related

packages/shared/src/components/modals/NewSourceModal.spec.tsx, packages/shared/src/components/modals/NewSourceModal.tsx
- Should now display the login modal whenever an anonymous user is requesting to add a new source
=> fix: display login when requesting source as anonymous user

packages/shared/src/components/FeedItemComponent.tsx, packages/shared/src/components/cards/AdCard.tsx, packages/shared/src/components/cards/AdList.tsx
- With the introduction of the dynamic font AB test we forgot to add the fonts to the ad cards
Test case:
=> fix: We forgot to add dynamic fonts on the ads

packages/extension/src/background/index.ts
- We forgot to remove the amplitude cache key
=> fix: remove amplitude cache key

docker-compose.yml
- We used a duplicate `db` image for the mysql and postgres image, this caused the postgres to exit pre-install
- Moved the postgres to it's own `pg` volume
N/A
N/A
=> build: Fixed a duplicate volumes issue

packages/shared/src/components/Markdown.tsx, packages/shared/src/components/PostsSearch.tsx, packages/shared/src/components/profile/ProfileTooltip.tsx, packages/shared/src/components/profile/ProfileTooltipContent.tsx, packages/shared/src/components/tooltips/BaseTooltip.tsx, packages/shared/src/components/tooltips/SimpleTooltip.tsx, packages/shared/src/hooks/analytics/useAnalyticsQueue.ts, packages/shared/src/hooks/useDebounce.spec.ts, packages/shared/src/hooks/useDebounce.ts, packages/shared/src/hooks/useUserMention.ts
- In my previous PR we introduced manual handling of state on where we should display the tooltip or not. Unfortunately, it introduced an edge case where the popup lost its interactiveness.
- Also refactored the use debounce hook to be cancellable
- Fixed the primary concern in this PR
Verified workability in this link: https://daily-webapp-i28cjgu9g-dailydotdev.vercel.app/posts/RcIbqXVDf
=> fix: interactiveness of mention popup

packages/shared/src/components/history/ReadingHistory.spec.tsx, packages/shared/src/lib/dateFormat.spec.ts, packages/webapp/pages/[userId]/index.tsx
- The core issue was when generating the heatmap - we have a function that creates an array, based on the week columns we will have to create.
- The concern came from the way we generate the start date - we utilize the function `new Date(0)` and set its year. Unfortunately, it looks like from `UTC-1` and lower, the value it returns is `31-12-1969` which is supposed to be `01-01-1970`.
- To avoid the incorrect start date, I have now explicitly defined that the calculation should start at `01-01-YYYY` based on the selected year.
- https://github.com/dailydotdev/daily/issues/501
DD-573 #done
=> fix: explicitly defining the start date of heatmap

packages/extension/package-lock.json, packages/webapp/package-lock.json, packages/webapp/package.json
I think the overload cache issue was caused only for users who used the webapp for a long time with an old service worker definition. The old SW didn't set a limit on the image cache, thus causing it to explode (my local cache was 4GB 🤯).
I update next-pwa to the latest version to make sure we are aligned with the newest settings and also confirmed locally that cache is limited to ~300mb.
I'm still not 100% what takes up all this storage because I tried to delete the caches one by one and still remained with ~170mb. But I think 300mb is a decent cap for now.
Closes dailydotdev/daily#372
DD-437 #done
=> build: update next-pwa to the latest version

.idea/misc.xml, packages/webapp/__tests__/PostPage.tsx, packages/webapp/pages/posts/[id].tsx
Earlier we removed the filter functionality of the `postsEngaged` subscription. This caused the article page to receive every event that is occurring in the system.
Unfortunately, we didn't handle the case where we receive an event of another post in the callback.
This is now fixed :)
DD-597 #done
=> fix: do not update article page on posts engaged event

packages/shared/src/hooks/usePostModalNavigation.ts
- The reason window is null, is when we navigate to the source page, the getStaticProps doesn't have the context of window yet, so it crashes.
=> fix: window being undefined

packages/shared/src/components/Feed.tsx, packages/shared/src/components/modals/PostModal.module.css
- fixes the jumpy UI on mobile devices (tablet and below screen sizes - since scrollbar doesn't take space on mobile devices)
- removed unnecessary top margin on tablet size for modal overlay
=> fix: jumpy ui on modal close for mobile devices.

.gitpod.yml, README.md, wait-for.sh
The new Gitpod config allows provisioning a new environment quickly.
This can be great for contributors and technical interviews.
=> build: add gitpod configuration

packages/shared/src/components/Feed.tsx, packages/shared/src/styles/base.css
- Tailwindcss has become quite annoying now. In the previous deployment, it recognizes the `pr-2` class, but the current one doesn't anymore.
- As much as I don't want to use module CSS, we have no choice but to utilize it since tailwindcss is pretty unstable as of the moment.
=> fix: feed jumpyness through module css

packages/shared/src/components/SidebarRankProgress.spec.tsx
Refactored the looped tests to work based on `jest.each` function.
This allows for the cleanup to happen more steadily.
- Change flaky test
Note: Flaky test still occur, we have to dive deeper into a proper cleanup solution
WT-10
=> fix: first start on cleaning up flaky tests

packages/webapp/pages/devcard.tsx
We no longer need to show the Star Wars themed devcards
- Removed the devcards from the code.
=> feat: remove star wars themed devcards

packages/shared/src/components/tooltips/SimpleTooltip.tsx
- Related concern: https://dailydotdev.slack.com/archives/C01L0QXQJNB/p1652520139195169
- For tooltips that are not of type string - the `aria-label` has a value of `false` due to the condition - we now set a condition to only add the property when necessary.
=> fix: tooltip's unnecessary aria-label

packages/webapp/components/CalendarHeatmap.tsx
- The current heatmap could have a reading day higher than the highest bin (if the sole day was exponantionally higher than the second highest)
- In this fix we ensure that a reading day higher than the highest bin always returns it's highest index.
Minimum viable test:
```js
const uniques = [1,2,3,4,7];
const binSize = Math.floor(uniques.length / 3);
console.log(uniques[Math.min(binSize*(5+1), uniques.length -1)]);
// Return 7
Array.from(new Array(3), (_, i) => uniques[Math.min(binSize * (i + 1), uniques.length - 1)])
// Return [ 2, 3, 4 ]
```
DD-621 #done
=> fix: the heatmap could have a read higher than bin value

packages/shared/src/components/ScrollToTopButton.tsx
- We didn't have a aria-label describing the scroll to top button
- Added aria-label as "scroll to top" to identify this button for screen readers
Before: It was simply called "button, group" in voiceover.
After it's called scroll to top, button, group
DD-622 #done
=> feat: add aria-label to scroll to top button

packages/webapp/next.config.js
- We included a HTML lang attribute on the extension, but not on the webapp
- This change introduces the lang attribute on the webapp as well.
Extension before:
Webapp before:
Webapp after:
DD-623 #done
=> feat: introducing HTML lang attribute for next app

packages/extension/src/companion/Companion.tsx, packages/extension/src/companion/CompanionContent.tsx, packages/extension/src/companion/CompanionContextMenu.tsx, packages/extension/src/companion/CompanionDiscussion.tsx, packages/extension/src/companion/CompanionMenu.tsx, packages/extension/src/companion/useBackgroundPaginatedRequest.ts, packages/extension/src/companion/useBackgroundRequest.ts, packages/extension/src/companion/useCompanionPostComment.ts, packages/shared/src/hooks/usePostComment.ts
- Added option to enable or disable listening for messages in background workers (inspired by react-query ❤️).
- Created a custom hook for managing the state and background workers in companion comments
- Changed the behavior for the comments button in the companion menu and in the context menu for viewing discussion
- It should now open a modal in the main menu comments button. If submitted, it will open the discussion panel
- The "View discussion" in Context menu should open the discussion panel.
=> refactor: companion menu comments button behavior

packages/extension/src/companion/Companion.tsx, packages/shared/src/lib/element.ts
- Should open the comments list even when the companion is minimized.
- Fixes the user mention on shadow dom with content editable (due to Selection API)
=> fix: toggling discussion and user mention

packages/extension/src/companion/Companion.tsx, packages/extension/src/companion/CompanionPopupButton.tsx, packages/extension/src/companion/useExtensionPermission.ts
- After further investigation, it seems the animation bug only happens on some sites - then I realized it is on those where we used to have an issue with enlarged dailydev logo at load.
- Now the animation should also be enabled only until the assets are loaded.
- The issue is when the transform property is forcing to render the animation.
- Also includes the fix for unintentionally showing the companion button.
Sample link:
https://blog.jetbrains.com/webstorm/2022/05/webstorm-2022-2-roadmap/
=> fix: companion animation bug

packages/extension/src/newtab/MainFeedPage.tsx
- We will now wait until the loading of the user finishes.
- Initially tried to use `loadedUserFromCache` but the profile component is not rendered until the `loadingUser` is false.
=> fix: companion button content shift

packages/webapp/pages/[userId]/index.tsx
- We initialised a `new Date()` in a wrong way, `01-01-2022` is not a valid format. (However Chrome seems super lenient I guess 🤷‍♂️
- Changed to `new Date(2022, 0, 1)` which is the supported format.
=> fix: date issue on FireFox

packages/shared/src/components/ShareBar.tsx, packages/shared/src/components/ShareMobile.tsx, packages/shared/src/components/ShareNewCommentPopup.tsx, packages/shared/src/components/post/PostWidgets.tsx, packages/shared/src/hooks/useCopyPostLink.ts, packages/shared/src/lib/share.ts
- We used to rely on the browser API to get URLs, but since we introduced the article modal for extension and webapp we need a more reliable source of URLs
- Changed to pass through the post commentsPermalink as this is always a valid url.
WT-110 #done
=> fix: shareable links for extension

packages/extension/src/companion/CompanionContextMenu.tsx, packages/extension/src/companion/CompanionMenu.tsx
- Change the view discussion button in the companion context to link to the post commentsPermalink as before.
WT-111 #done
=> fix: change view discussion to webapp post link

packages/extension/src/background/index.ts, packages/extension/src/companion/App.tsx, packages/extension/src/companion/Companion.spec.tsx, packages/extension/src/companion/Companion.tsx, packages/extension/src/companion/index.tsx, packages/extension/src/companion/useBackgroundRequest.ts, packages/extension/src/companion/useCompanionPostComment.ts, packages/shared/src/contexts/BootProvider.tsx, packages/shared/src/hooks/useRefreshToken.ts
I think this is one comment from our beta user has really helped us finding the root cause.
> As an FYI, I couldn’t commit the above message because of the “Access denied” error, but after a refresh of the page, I could. Same thing with the “markdown preview”, after the refresh it works. So perhaps a timing issue since I took a while to write the comment? Not sure, but I’ll keep an eye to see if I can reproduce it.
- We received quite a few feedback relating to making a comment. After further investigation, it was realized the token for making requests was not refreshed, meaning, every request gets rejected (upvotes/comments/upvotes modal/etc).
- We are now utilizing the custom hook used in boot for refreshing the token.
- Instead of re-requesting the whole boot data - we now instead …
=> fix: refresh token utilization

packages/extension/src/companion/index.tsx, packages/extension/src/content/index.tsx, packages/shared/src/contexts/SettingsContext.tsx
- A mutation observer that watches the changes with `document`. Sends a message when change is detected.
- Have tried window and document listeners for watching the URL change, but none has worked.
- Have also tried `browser.onUpdated.addEventListener` but had some issues with background worker.
Works on both Chrome and Firefox.
Steps to test:
1. Install the app from this build.
2. Visit https://dev.to/kbatavia12/project-ideas-frustrated-3lai
3. Navigate to devto's homepage (hides companion).
4. Search "Project ideas!!! (Frustrated)"
5. Open the same article
6. Should show companion again.
WT-116 #done
=> fix: companion state on spa site navigation

packages/extension/src/companion/common.tsx, packages/extension/src/companion/companionRequest.tsx, packages/shared/src/components/post/PostComments.tsx, packages/shared/src/lib/constants.ts
- Our companion request method was retuning `null` as a default, this causes react query to refresh to `null` then only to the actual data
- The fix introduced a optional object that can be returned, this optional object is the temporary previous object.
WT-124 #done
=> fix: prevent comments from reloading to placeholders

packages/extension/src/companion/CompanionContent.tsx, packages/extension/src/companion/CompanionDiscussion.tsx, packages/shared/src/components/post/NewComment.tsx
- Remodel the companion comment section
- Only the actual comments and title are scrollable now
See screenshot:
WT-119 #done
=> feat: change the companion comment scrollable section

packages/extension/src/companion/CompanionMenu.tsx, packages/shared/src/hooks/useKeyboardNavigation.ts
- Set the companion in collapsed form when `esc` key is pressed.
- Should not close when any of our modal is open. 
=> feat: close companion on escape key

packages/shared/src/components/modals/CommentBox.tsx
- The only input we have in our companion app is the comment box.
- Stopping the propagation on keypress.
WT-125 #done
=> fix: stop keypress propagation to avoid conflict with site's keybindings

packages/extension/public/css/daily-companion-app.css, packages/extension/src/companion/CompanionContent.tsx
- The copy link was currently conditionally rendered which is no longer needed
- We've now set the z-index of the companion to be the highest possible z-index so it will always be on top of everything.
WT-131 #done
=> fix: highest possible z-index and remove conditional copy link

packages/shared/src/lib/element.ts
As always, Firefox has some issues with our Companion 😆 
- The user mention feature wasn't working due to the specific object we're using when getting and setting the caret position (either window, document, or shadowroot's `ownerDocument`).
- There were also some differences with the offset when its companion for Firefox. 
Have tested out on both Firefox and Chrome 🚢 
WT-138 #done
=> fix: user mention in firefox

packages/shared/src/components/BookmarkFeedLayout.tsx, packages/shared/src/components/widgets/PostUsersHighlights.tsx
Few icons sizes and spacings were updated (found inconsistencies during testing)
=> fix: outline icons spacing and size

packages/shared/src/components/RecommendedMention.tsx, packages/shared/src/components/profile/UserShortInfo.tsx, packages/shared/src/components/utilities.tsx, packages/shared/src/lib/classed.ts
- New width of the user mention container
- Applied ellipsis on overflowing texts
Reference for the fix: https://dailydotdev.slack.com/archives/C02AA18RD1D/p1655126916308559?thread_ts=1655123456.781379&cid=C02AA18RD1D
Preview:
=> fix: text overflow on companion user mention

packages/extension/public/css/daily-companion-app.css
- We adapted font-rendering from each website, but we wanted to render smoothly
- This PR introduces the same font rendering for all websites so we uniform our companion fonts.
WT-108 #done
=> fix: font rendered different on some sites

packages/extension/src/background/index.ts
- The only way for us to identify whether the companion is active is if it was found in the DOM. Our mention user feature relies on it for which DOM to apply the tooltip.
- After further checking, our webapp was not yet included in our list to not initialize the companion.
Probably we need to come up with another option for identifying if companion was activated. Probably close the shadow DOM when no post was found from the link? Though this is probably up for a different discussion. Just laying down my thoughts.
DD-636 #done
=> fix: excluded list for companion - webapp mention feature not working

packages/shared/src/components/Markdown.tsx
- Append the tooltip to `document.body` so it won't get cut off by the modal's `overflow: hidden`.
Deployed at: https://preview.app.daily.dev/
Preview: 
WT-147 #done
=> fix: preview tooltip getting cut-off

packages/shared/src/components/MainFeedLayout.tsx, packages/shared/src/components/filters/TagsFilter.tsx, packages/shared/src/components/modals/CreateMyFeedModal.spec.tsx, packages/shared/src/components/modals/CreateMyFeedModal.tsx, packages/shared/src/components/sidebar/Sidebar.tsx, packages/shared/src/lib/featureManagement.ts
- We decided on a winning AB test
- Removed all spaghetti code related to create my feed modal
=> feat: cleanup my feed modal types to winner

packages/shared/src/components/comments/CommentAuthor.tsx, packages/shared/src/components/comments/ScoutBadge.tsx
- The comment icons had different sizes and spacing
WT-150 #done
=> fix: adjust scout comment icons

packages/shared/src/components/Feed.tsx, packages/shared/src/components/FeedItemComponent.tsx, packages/shared/src/components/LoginButton.tsx, packages/shared/src/components/cards/AdCard.tsx, packages/shared/src/components/cards/AdList.tsx, packages/shared/src/components/cards/Card.tsx, packages/shared/src/components/cards/PostCard.tsx, packages/shared/src/components/cards/PostList.tsx, packages/shared/src/components/utilities.tsx, packages/shared/src/lib/featureManagement.ts
- Cleanup unused experiments
- Text related ones remain active, but changed to winners
- Logic related ones get completely removed
Note: We should only turn them off once we deploy the extension to a new version and give it a week or so.
=> fix: cleanup unused and finished experiments

packages/shared/src/components/MainFeedLayout.tsx, packages/webapp/components/CookieBanner.module.css, packages/webapp/components/CookieBanner.tsx
- Z-index of the cookie banner was too low
- We didn't set the actual cache, so refresh would re-assess
=> fix: cookie z-index and intial value storage

packages/shared/src/components/ShareNewCommentPopup.tsx
Share comment icon size fixed and now uses standard way of changing size of the icon
=> fix: share comment icon size updated

packages/shared/src/lib/element.ts
- Have changed the decision process where the user mention tooltip will append the result so we won't have to bother from the list and ensure it will always be the actual DOM for webapp.
=> refactor: fetching shadow dom on extension only

packages/shared/src/components/PostsSearch.tsx, packages/shared/src/components/fields/AutoCompleteMenu.tsx
- After making a search on a mobile device, the UI shifts. We now set `0` width whenever the suggestion is not available.
- I have also found another issue where it won't display a suggestion after you hit enter and then type something. Should be fixed here as well.
WT-166 #done
=> fix: layout shift after making a search

packages/shared/src/components/modals/CommentBox.tsx
Now we use tailwind class instead of inline style, so it's our plugin can convert it from rem to pixels and it's solves issue with modal height in companion and we don't rely on site font size
=> fix: extension comment modal size

packages/shared/src/components/icons/Search/index.tsx
Default search icon size removed, because it is controlled by general icon component and now we have correct size of the icon in the sidebar
=> fix: sidebar icon size to match guideline

packages/shared/src/components/widgets/SimilarPosts.tsx
As we decided in our slack conversation label is updated from _show more_ to _view all_ to make it more clear for the user 
=> feat: similar posts button label updated

packages/shared/src/components/Feed.tsx
- We had a edge case where we never cleaned up the `hidden-scrollbar` when navigation without page-refresh.
WT-168 #done
=> fix: enable scroll for profile page coming from post modal

packages/shared/src/components/post/PostModalActions.tsx
- Fixes the missing tooltip when the post modal header is sticky.
- The close button has a tooltip, so no changes are needed for it.
Preview: 
=> fix: read article tooltip

packages/shared/src/components/CreateMyFeedButton.tsx, packages/shared/src/components/MainFeedLayout.tsx
- From the link, it looks like both elements need to be present even when the user has no filters yet.
https://miro.com/app/board/uXjVOPPtumw=/?invite_link_id=273386981736
Preview:
WT-172 #done
=> fix: header to display both create feed and dropdowns

packages/shared/src/components/icons/Facebook/index.tsx, packages/shared/src/components/profile/EditImageWithJoinedDate.tsx, packages/webapp/components/layouts/ProfileLayout/index.tsx
Found some small issues during testing on a preview env, so quickly fixed everything and one more time checked everything:
- Facebook icon filled is color and outlined is white now
- Profile twitter social icon is white
- GitHub icon size was wrong, because tailwind classnames were overwritten, so I changed it to inline styles for now (will be changed once we have icon sizes guideline)
=> fix: some small icon issues fixed

packages/extension/src/companion/CompanionPopupButton.tsx, packages/shared/src/components/tooltips/BaseTooltip.tsx
- After further checking, it seems the root cause of miscalculation in the offset (and had to use) was the max width that was set default from tippyjs. Our component exceeds it, but since the value was explicitly set, it has been thought to be the actual width.
- Also checked from the actual library if the removal of the max width is safe, and there seems to be no issue about it: https://github.com/atomiks/tippyjs/issues/451#issuecomment-473252780
There was also an issue before for its misplacement when the user is not logged in. This has resolved that issue as well. Have thoroughly checked and all seems to be in place now and much more stable.
Issues to close:
- https://github.com/dailydotdev/daily/issues/620
- https://github.com/dailydotdev/daily/issues/574
Will close the relevant …
=> fix: companion popup placement

packages/shared/src/lib/featureManagement.ts
- Closing the AB test winners for all flags
- Keeping the `companion_permission_placement` active as we might reintroduce soon
Winners described here: https://dailydotdev.atlassian.net/wiki/spaces/HAN/pages/edit-v2/234160129
WT-211 #done
=> chore: closing AB test for companion

packages/shared/src/components/fields/TextField.tsx, packages/shared/src/components/widgets/SocialShareIcon.tsx, packages/shared/src/styles/base.css, packages/shared/tailwind.config.js
- We had some issues with light-mode colors and the textfield
=> fix: modify share colors to reflect design

packages/shared/src/components/modals/CommentBox.tsx, packages/shared/src/components/modals/NewCommentModal.spec.tsx, packages/shared/src/components/modals/NewCommentModal.tsx, packages/shared/src/hooks/useUserMention.ts, packages/shared/src/lib/element.ts
- It was almost impossible to make a comment in FF previously. The root cause was the div contenteditable.
- The reason behind its usage was to natively support the dynamically changing height of the comment box.
- But since it is more important for the users to be able to make a comment, we decided to go back to using textarea.
- Moved from keydown to keyup as it is much more accurate of when we should trigger the mentions.
WT-134 #done
=> refactor: comment box from div contenteditable to textarea

packages/shared/src/components/cards/TrendingFlag.tsx, packages/shared/src/components/utilities.tsx
- The hot label should always render in white, regardless of the theme
WT-203 #done
=> fix: hot label text color

packages/shared/src/components/ProfilePicture.tsx
- When moving to native lazy loading we forgot to add the `object-cover` class to images.
- I went over the other native lazy loading modification, which all seem to have the class
WT-224 #done
=> fix: add object cover to profile images

packages/shared/src/components/MyFeedIntro.tsx
- The onboarding pill always overruled the `w-auto`
- Now we evaluate if a random width is needed, else we don't even invoke the state
WT-222 #done
=> feat: fix onboarding pill size

packages/extension/src/companion/CompanionDiscussion.tsx, packages/shared/src/components/post/NewComment.tsx, packages/shared/src/components/utilities.tsx
- The companion new comment bar was using responsive styles
- This affected the behaviour, as it supposed to show non-responsive inside the companion at all screen sizes
Before:
After:
WT-191 #done
=> fix: update companion new comment placement

packages/extension/src/background/index.ts, packages/shared/src/lib/strings.ts
- In this commit we removed the search params
- This was not intended, we only wanted to remove `#` and other weird symbols not the search params
- This fix introduces the whole search string
Edge case:
If the page has multiple search params for these allowed domains it won't be able to find them.
For instance:
```js
https://news.ycombinator.com/item?id=32069418 = valid
https://news.ycombinator.com/item?id=32069418&utm=blabla = not valid
```
Personally think it's good enough for now.
(It only affects domains where we allow querystrings)
| Type   | event_name  | …
=> fix: we removed search params on the companion side

packages/shared/src/components/MainFeedLayout.tsx
Shorcuts block is 50px (48px + 2px for border) and header size was 48px. Now header size is 50px, so no scroll on header and no cut offs for shortcuts block
DD-645 #done
=> fix: changed feed header height to remove scroll

packages/extension/src/companion/CompanionDiscussion.tsx
Now we have `overflow-x: hidden`, so there is no horizontal scroll, it also resolved an issue with start discussion button on a tabled resolution (check screenshots below)
Before:
After:
WT-245 #done
=> fix: companion discussion horizontal scroll 

packages/shared/src/hooks/useRefreshToken.ts, packages/shared/src/lib/boot.ts
- The value we use to check how much it should wait for our refresh token to be requested was `undefined` at initialization.
- It produces `NaN` due to arithmetic operation on `undefined`, so the setTimeout was thinking to fire at will.
- Also took the chance to remove the undefined search query parameter in the boot request.
WT-232 #done
=> fix: refresh token causing boot to refetch

docker-compose.yml
- There is a running issue where 10.8.3 runs on `jammy` but not all the testing environment can run this yet.
- The solution for now is to pin 10.8.2
This is not the recommend solution according to MariaBD you should pin a new package for development use, but this does not reflect our environment and gives innoDB issues.
Thus 10.8.2 is a safe option for now, especially seeing we only run this for GitPod really.
[Maria DB post](https://mariadb.org/new-service-quay-io-mariadb-foundation-mariadb-devel/)
[Issue on GitHub](https://stackoverflow.com/a/72417962)
| Type   | …
=> fix: pin mariadb version

packages/shared/src/components/Feed.spec.tsx, packages/shared/src/components/Feed.tsx, packages/shared/src/components/FeedItemComponent.tsx, packages/shared/src/components/cards/CommentPopup.tsx, packages/shared/src/contexts/FeaturesContext.tsx, packages/shared/src/hooks/feed/useFeedUpvotePost.ts, packages/shared/src/lib/featureManagement.ts
- Re-introducing the comment modal popup
WT-266 #done
=> feat: re-introduce comment popup as AB

packages/shared/src/components/Feed.spec.tsx, packages/shared/src/hooks/useFeed.ts
The second page of the feed onward should set the `active` query param to `true`
=> refactor: add active query param to ad request

packages/shared/src/components/Feed.module.css, packages/shared/src/components/Feed.tsx, packages/shared/src/components/MainLayout.tsx
- Our current header was always aligned with the feed size.
- On some sizes this really cut down the header.
Before and current laptopL and above
New smaller than laptopL
WT-210 #done
=> fix: make the header part of the feed independant

packages/shared/src/components/widgets/SimilarPosts.tsx, packages/shared/src/graphql/furtherReading.ts
- Link similar posts to internal links
WT-276 #done
=> fix: change similar post links to be interanl

packages/shared/src/components/comments/CommentActionButtons.tsx
- The delete button was not having enough space on the right
WT-274 #done
=> fix: comment share button space

packages/shared/src/components/cards/ActionButtons.tsx
- We used `medium` buttons, but they should always be `small`.
New v1 and v2:
WT-271 #done
=> fix: post button size was too big

packages/webapp/pages/_app.tsx
- After discussing this with Dominik, our current setup can actually share data across users on the server side
- By moving the ref inside the app via state it's bound to a single user
- Read more: [React Query Hydration](https://tanstack.com/query/v4/docs/guides/ssr#using-hydration)
WT-277 #done
=> feat: change instance ref for react query

packages/shared/src/components/ShareNewCommentPopup.tsx
- We used two secondary icons that should be primary for this case
New:
WT-268 #done
=> fix: comment share icon style

packages/shared/src/components/TagLinks.tsx
- Tags where linking relative instead of pointing to webapp
WT-281 #done
=> fix: taglinks should link to webapp

packages/shared/src/components/post/PostContent.tsx, packages/shared/src/components/utilities.tsx
Tags were too close to article title if there is no TLDR. No bottom margin will be added to title in this case to keep correct spacing  
WT-{293} #done
=> fix: add bottom spacing if there is no post summary

packages/shared/src/components/PostOptionsMenu.tsx, packages/shared/src/components/post/PostContent.tsx, packages/shared/src/components/post/PostModalActions.tsx, packages/shared/src/components/post/PostNavigation.tsx, packages/shared/src/components/post/PostWidgets.tsx, packages/shared/src/hooks/useReportPostMenu.ts
- The IDs of the reusable post-context menu were conflicting with different instances.
- Pass the ID as param to avoid conflict.
Have confirmed, there are no more multiple instances on opening the options at the modal (used to be 3 elements).
WT-297 #done
=> fix: post context menu ids

packages/shared/src/components/auth/AuthDefault.tsx, packages/shared/src/components/auth/AuthOptions.tsx, packages/shared/src/components/auth/AuthSignBack.tsx
- Store the last clicked provider used.
- When the user opens the modal that is only when it will be checked for which one was used the last one.
- Once the user has seen the "sign back in" form, it will remove the storage value so next signin will include allowing of registration.
WT-341 #done
=> feat: store last sign-in method

packages/shared/src/components/Feed.tsx, packages/shared/src/hooks/feed/useFeedOnPostClick.ts, packages/shared/src/hooks/useOnPostClick.ts
- Modify default actions to be click
- Side actions defined as what they intend to be
WT-366 #done
=> fix: event names click/modal

packages/shared/src/lib/auth.ts, packages/shared/src/lib/boot.ts, packages/webapp/pages/account/security.tsx
- Change email flow
NOTE:
- We probably want to check if the email is still available first
- @sshanzel Noticed that the privileged action modals works, but on verification it doesn't auto continue the flow, is that intended?
WT-331 #done
=> Wt 331 change email

packages/webapp/components/layouts/AccountLayout/SidebarNav.tsx, packages/webapp/components/layouts/AccountLayout/SidebarNavItem.tsx, packages/webapp/components/layouts/AccountLayout/index.tsx
- Reduce the padding based on how much border is being produced to keep the size consistent.
- Tried to apply border-box but didn't work
WT-383 #done
=> refactor: sidebar nav padding avoiding layout shift

packages/shared/src/components/auth/AuthOptions.tsx, packages/shared/src/hooks/useLogin.ts, packages/shared/src/hooks/usePrivilegedSession.ts, packages/shared/src/hooks/useWindowEvents.ts, packages/shared/src/lib/func.ts, packages/shared/src/lib/kratos.ts, packages/webapp/components/layouts/AccountLayout/Security/index.tsx, packages/webapp/pages/callback.tsx
- Create a hook that wraps the usage of window event to utilize an event key in determining if the call should proceed.
- Refactor old usage of window event to use the new one.
- Enforce sending an event key on post message function.
- Fix persisting the session verification modal on reload by making it live through current session only.
WT-378 #done
=> refactor: use window events to require key

packages/shared/src/contexts/AlertContext.tsx, packages/webapp/__tests__/TagPage.tsx, packages/webapp/pages/account/others.tsx
- Added the checked value for the switch component
- Changed alert filter to default true, this is the database default and it caused weird sideffect where re-render got the wrong default value.
WT-388 #done
=> Wt 388 fix accepted marketing

garden.yml, packages/shared/src/components/MyFeedIntro.tsx, packages/shared/src/components/modals/AccountDetailsModal.module.css, packages/shared/src/components/modals/CreateMyFeedModal.tsx, packages/shared/src/components/modals/ResponsiveModal.module.css, packages/shared/src/components/modals/StyledModal.module.css, packages/shared/src/components/modals/StyledModal.tsx, project.garden.yml
- The mobile my feed modal had bottom spacing for the footer which caused overscroll
- It was also not positioned at full-width on mobile
- Tested on desktop/mobile changes, yet to try on physical device (based on preview URL)
WT-391 #done
=> fix: my feed modal mobile was having some width issues and overflow scroll

packages/webapp/pages/callback.tsx
- Account recovery works purely on redirect, meaning, there will be no `window.opener` property, this is when we decide that it came from a password reset intention.
WT-398 #done
=> refactor: callback page to manage recovery

packages/shared/src/components/cards/ActionButtons.tsx, packages/shared/src/components/cards/PostCard.tsx, packages/shared/src/components/cards/PostCardHeader.tsx, packages/shared/src/components/cards/PostFooterOverlay.tsx, packages/shared/src/components/cards/PostList.tsx, packages/shared/src/components/cards/ReadArticleButton.tsx
- Refactored read article button to have an option of opening a new tab
- Refactor existing implementations (used search to find all).
- Tested in preview deployment and works as intended.
WT-306 #done
=> fix: read article button open new tab

packages/shared/src/components/auth/AuthDefault.tsx, packages/shared/src/components/auth/LoginForm.tsx
- Added a state to pass email from register to login screen
WT-433 #done
=> fix: remember email from register to login

packages/shared/src/components/auth/SocialRegistrationForm.tsx
- Because of the bigger font-size combination it pushed the width of the input.
- Setting the size to 1 will work because we use align-stretch
WT-429 #done
=> Wt 429 password field

packages/shared/src/components/modals/CloseButton.tsx, packages/shared/src/components/modals/ModalCloseButton.tsx, packages/webapp/components/layouts/AccountLayout/AccountPageContainer.tsx, packages/webapp/components/layouts/AccountLayout/SidebarNav.tsx, packages/webapp/components/layouts/AccountLayout/SidebarNavItem.tsx, packages/webapp/components/layouts/AccountLayout/common.tsx, packages/webapp/components/layouts/AccountLayout/index.tsx
- In our account details page, for when the width is for mobile devices, the side navigation should be toggleable.
WT-417 #done
WT-419 #done
=> fix: account details responsiveness

packages/shared/src/components/comments/MainComment.tsx, packages/shared/src/components/comments/SubComment.tsx, packages/shared/src/components/comments/common.tsx
- Added a active border to the highlighted comments
WT-308 #done
=> feat: added comment highlight to active comment

packages/shared/src/components/modals/CloseButton.tsx
- We spread the props to the button component, but then the `style` property was destructured and unused.
WT-454 #done
=> fix: close button not passing style property

packages/shared/src/components/MainLayout.tsx
- When the social registration form is present, we should not show the standalone social registration form.
WT-456 #done
=> fix: double social registration form

packages/shared/src/components/auth/EmailSignupForm.tsx
- From the image below (attached to the ticket), the button seems primary and disabled when the email is empty. As also explained in the ticket itself.
=> fix: submit button styling when email is filled

packages/shared/src/contexts/BootProvider.tsx
- After further investigation, it seems the `cachedData` is always undefined when executing from use profile form.
- To make it always up to date, it was missing a critical dependency.
- I'm actually wondering why on current production it behaves as intended.
WT-448 #done
=> fix: boot data always undefined

packages/shared/src/hooks/useLogin.ts, packages/shared/src/hooks/usePrivilegedSession.ts
- whoami call is not needed almost everytime but only at verifying sessions.
- Create a condition to let the query not execute.
WT-447 #done
=> refactor: disabling whoami call when unnecessary

packages/shared/src/components/auth/EmailVerificationSent.tsx
- The forgot password resend timer is already a minute.
WT-457 #done
=> fix: resend email verification timer set to a minute

packages/shared/src/contexts/AuthContext.tsx, packages/shared/src/contexts/BootProvider.tsx, packages/webapp/components/layouts/AccountLayout/index.tsx
- As per Ido, an empty screen should be okay for a placeholder on the profile pages.
- I also applied a redirect if the data is fetched already and user is not logged in.
WT-450 #done
=> refactor: accounts page placeholder

packages/shared/src/components/auth/AuthOptions.tsx
- Sometimes when you hit the provider and the callback closes, the user gets logged in but not closing the modal.
WT-440 #done
=> fix: close login modal when user is already available

packages/shared/src/components/auth/EmailSignupForm.tsx
- Make TOS and PP clickable and styled
WT-466 #done
=> fix: clickable tos pp

packages/shared/src/components/auth/AuthModal.tsx, packages/shared/src/components/auth/AuthOptions.tsx
- This AuthOptions component is reused at the v3 (dedicated login page), where there is no concept of modal, so we will have to use the props whenever the login was successful.
WT-483 #done
=> fix: on password login, close modal

packages/webapp/components/layouts/AccountLayout/Security/index.tsx
- Show password strength on profile page
WT-477 #done
=> fix: show password strenght for profile reset

packages/shared/src/components/MainLayout.tsx, packages/shared/src/lib/kratos.ts, packages/webapp/pages/reset-password.tsx
- Disable the submit button while the request is loading and was successful.
- Error management for when the token expired, kratos redirects to our page and should display a toast message.
WT-472 #done
=> fix: reset password loading indicator and error management

packages/eslint-rules/lib/rules/no-custom-color.js, packages/shared/src/components/modals/StyledModal.tsx, packages/shared/src/styles/base.css, packages/shared/tailwind.config.js, packages/webapp/pages/reset-password.tsx
- Add the new modal colors and added a new eslint rule exception for background gradient.
WT-527 #done
=> fix: new modal backdrop

packages/shared/src/components/auth/AuthModal.tsx, packages/shared/src/components/auth/AuthOptions.tsx
=> refactor: auth modal hiding graphics on verification sent

packages/shared/__tests__/fixture/auth.ts, packages/shared/src/components/auth/AuthModal.module.css, packages/shared/src/components/auth/AuthModal.tsx, packages/shared/src/components/auth/AuthOptions.tsx, packages/shared/src/components/auth/RegistrationForm.spec.tsx, packages/shared/src/components/modals/ConnectedUser.tsx, packages/shared/src/lib/kratos.ts, packages/shared/src/lib/strings.ts, packages/webapp/pages/account/security.tsx
- This also fixes the issue of not hiding the left-side graphics (headings).
- Should show connected accounts
Preview (the connected log-in methods aren't shown in the preview as it was only running locally):
WT-446 #done
=> feat: show connected accounts

packages/shared/src/components/auth/AuthOptions.tsx, packages/shared/src/components/modals/ConnectedUser.tsx
=> fix: consistency of using the same flow id for list providers query

packages/shared/src/components/widgets/Alert.tsx
- Small fix for mobile versions of the alert div
New:
WT-530 #done
=> fix: line-break bug for mobile screens

packages/shared/src/components/auth/AuthOptions.tsx, packages/shared/src/components/modals/ConnectedUser.tsx
- Safari has to open the window outside any async calls, this way the window is not considered a blocking popup
WT-439 #done
=> Wt 439 safari bug

packages/shared/src/components/fields/ImageInput.tsx, packages/webapp/components/layouts/AccountLayout/SidebarNav.tsx, packages/webapp/components/layouts/AccountLayout/SidebarNavItem.tsx, packages/webapp/components/layouts/AccountLayout/common.tsx, packages/webapp/pages/account/profile.tsx
- Fixes sidebar inactive items
- Fixes the account pages list spacing
- Refactored the ImageInput to include hover icon as props
WT-565 #done
WT-566 #done
WT-567 #done
=> fix: account details page sidebar

packages/shared/src/components/auth/LoginForm.tsx
- Password was pushed to two lines because double flex-1 on two elements.
- Flex grow to 2 on the password helps.
WT-556 #done
=> fix: forgot password

packages/shared/src/hooks/useProfileForm.ts
- We where using mutateAsync which does NOT handle errors on it's own.
- I decided to switch to mutate itself which is recommend by react query.
- More info on mutation promise: https://tanstack.com/query/v4/docs/guides/mutations#promises
Side note: Production it was visually half-working, but still throwing a unhandled error under the hood.
WT-555 #done
=> fix: catch username

packages/shared/src/components/Feed.tsx
When we track feed events, we attach the item row and column but they are calculated based on the wrong number of columns
=> fix: use the correct number of columns when calculating row and column

packages/shared/src/components/auth/AuthOptions.tsx
- Previously we didn't wait for the user to be valid so we could never continue the flow.
- Now we wait for the user and evaluate the action 
- Did have to use useEffect :(
WT-596 #done
=> fix: valid user flow

packages/shared/src/components/comments/MainComment.tsx, packages/shared/src/components/comments/SubComment.tsx
- The appending of the tooltip was not passed. Hence it was getting appended on the body where styles got adjusted.
WT-586 #done
=> fix: companion comment mention hover tooltip

packages/shared/src/lib/kratos.ts, packages/webapp/pages/reset-password.tsx
- Fix edge case where there is a mismatch with the `identities` user id and the `api` db user id but the same email. The user automatically gets logged out (our internal function for user not found).
- To be able to investigate easily, we ask the user to include the flow ID for sending feedback as this requires internal fix for matching their IDs.
- 
WT-604 #done
=> fix: reset password edge case

packages/shared/__tests__/fixture/auth.ts, packages/shared/src/hooks/useLogin.ts, packages/shared/src/hooks/usePrivilegedSession.ts, packages/webapp/__tests__/AccountSecurityPage.tsx, packages/webapp/components/layouts/AccountLayout/EmailSentSection.tsx, packages/webapp/components/layouts/AccountLayout/Security/index.tsx, packages/webapp/pages/account/security.tsx
- Allow unverified email of users to resend and not only when they changed email.
WT-609 #done
=> refactor: resend verification always shown if not verified

packages/shared/__tests__/fixture/auth.ts, packages/shared/src/lib/kratos.ts
- Change from kratos whoami to heimdall whoami
WT-609 #done
=> fix: whoami refresh

packages/shared/src/components/TagLinks.tsx, packages/shared/src/components/filters/TagOptionsMenu.tsx, packages/shared/src/lib/links.ts
Some tags are not URL friendly (such as C#) and must be encoded before used as links
=> fix: encode tag when using it as a link

packages/extension/src/newtab/App.tsx
- Extension should not call register endpoint on reload
=> feat: should not redirect to register endpoint if not confirmed

packages/shared/src/components/auth/LoginForm.tsx, packages/shared/src/components/fields/TextField.tsx
- The hint turns red once submitted but only when it has value
- This should fix the requirement for when the hint should also turn red if empty but must be a required field.
WT-619 #done
=> fix: invalid if required and empty

packages/shared/src/components/auth/VerifySessionModal.module.css
- The background color is inaccurate for the verify session modal. We should keep the default `tertiary`.
WT-614 #done
=> fix: verify session modal background

packages/webapp/components/layouts/AccountLayout/Security/index.tsx
We ignored the unlinked confirmation modal and unlinked the user immediately on button click
=> fix: show unlink confirmation modal before unlinking

packages/shared/src/lib/kratos.ts, packages/webapp/pages/account/security.tsx
When the account has only one oidc provider, kratos will throw an error when trying to unlink it. We display a toast if it happens
WT-622 #done
=> feat: show toast when an error occurs when unlinking

packages/shared/src/components/fields/PasswordField.spec.tsx, packages/shared/src/components/fields/PasswordField.tsx, packages/shared/src/components/fields/TextField.tsx, packages/shared/src/components/modals/SubmitArticleModal.spec.tsx, packages/shared/src/components/modals/SubmitArticleModal.tsx, packages/shared/src/hooks/useInputField.ts, packages/shared/src/hooks/useInputFieldFunctions.ts
Remove validation of fields on the first paint
WT-624 #done
=> fix: remove validation of fields on first paint

packages/shared/src/components/auth/common.tsx, packages/webapp/components/layouts/AccountLayout/Security/index.tsx
- There was an issue with the mismatch of keys to check for GitHub provider.
- The object had `gitHub` - the saved key was `github`. To keep things simple, I lowercased everything.
WT-631 #done
=> fix: signback key mismatch with github

packages/shared/src/components/auth/SocialRegistrationForm.tsx, packages/shared/src/components/fields/ImageInput.tsx, packages/webapp/pages/account/profile.tsx
Before the fix:
Result:
WT-632 #done
=> fix: stretched image in profile

packages/webapp/components/layouts/AccountLayout/index.tsx
- A race condition happens when the request just finished but the data for `profile` parameter is not yet reflecting the updated one.
- We instead wait until all is resolved.
WT-635 #done
=> fix: redirect race condition

packages/shared/src/components/profile/PostsSection.tsx
- The profile twitter field was off due to new textfield changes
New:
WT-641 #done
=> fix: twitter field

packages/shared/src/components/auth/AuthOptions.tsx, packages/shared/src/components/auth/LoginForm.spec.tsx, packages/shared/src/hooks/useLogin.ts
- We currently always recall the login flow, but this should not be the case for logged users. (Only in privileged actions)
WT-650 #done
=> fix: don't recall browser login for logged users

packages/shared/src/components/fields/PasswordField.tsx, packages/webapp/pages/reset-password.tsx
- The reset-password page was never showing the custom hints, due to strength priority.
- This fix will allow both options to work.
WT-649 #done
=> fix: password strength hints rendering

packages/shared/src/components/auth/common.tsx, packages/shared/src/styles/components/buttons.css
- Due to our dynamic setup I had to resort to some unwanted classname injection, but it works
- Only social icons now have more spacing 
WT-656 #done
=> fix: social icon more spacing

packages/extension/src/newtab/MainFeedPage.tsx, packages/shared/src/components/MainFeedLayout.tsx, packages/shared/src/components/filters/AdvancedSettings.tsx, packages/shared/src/components/filters/TagsFilter.tsx, packages/shared/src/components/sidebar/Sidebar.tsx, packages/shared/src/contexts/FeaturesContext.tsx, packages/shared/src/hooks/useDefaultFeed.ts, packages/shared/src/hooks/useFeedSettings.ts, packages/shared/src/hooks/useMutateFilters.ts, packages/shared/src/hooks/useMyFeed.ts, packages/shared/src/hooks/useTagAndSource.ts, packages/shared/src/lib/featureManagement.ts
- We don't usually tear down everything related to an experiment, but the `shouldShowMyFeed` is used in **a lot** of conditions which makes it difficult to easily get a grasp of the whole process.
- With fewer conditions, we will have less complexity and less time to understand the process flow.
=> refactor: my feed experiment conclusion cleanup

packages/shared/src/components/auth/AuthDefault.tsx, packages/shared/src/components/auth/EmailSignupForm.tsx
- We had a mismatch in the design of the button for V2, should be the purple one.
- Also adjusted the title usage to reflect wanted behaviour
WT-661 #done
=> fix: title for ABs and register button for V2

packages/shared/src/components/filters/FeedFilters.tsx, packages/shared/src/components/filters/FilterMenu.tsx
- I missed adding the unblocking modal for confirmation 🤦 
- Should be fixed in this PR.
Preview:
=> fix: missing unblock modal

packages/webapp/pages/_app.tsx
- With the removal of a useEffect in the new auth system we accidentally removed the init function for the cookie banner.
- We now use the existing useEffect to always call it.
WT-692 #done
=> fix: cookie banner was never initialized

packages/shared/src/components/MainFeedLayout.tsx, packages/shared/src/components/modals/CreateMyFeedModal.spec.tsx, packages/shared/src/components/modals/CreateMyFeedModal.tsx, packages/shared/src/lib/featureManagement.ts
- For the `v3` being concluded as the winner of the "my feed onboarding" experiment, this contains a code cleanup as part of our routine for when an experiment is concluded.
=> refactor: cleanup of my feed experiment

packages/extension/src/companion/CompanionContextMenu.tsx, packages/extension/src/companion/CompanionMenu.tsx, packages/shared/src/components/Feed.spec.tsx, packages/shared/src/components/Feed.tsx, packages/shared/src/components/FeedItemComponent.tsx, packages/shared/src/components/PostOptionsMenu.tsx, packages/shared/src/components/cards/ActionButtons.tsx, packages/shared/src/components/cards/PostCard.spec.tsx, packages/shared/src/components/cards/PostCard.tsx, packages/shared/src/components/cards/PostList.tsx, packages/shared/src/components/post/PostActions.tsx, packages/shared/src/components/post/PostContent.tsx, packages/shared/src/components/post/PostModalActions.tsx, packages/shared/src/components/post/PostNavigation.tsx, packages/shared/src/components/post/PostWidgets.tsx, packages/shared/src/contexts/FeaturesContext.tsx, packages/shared/src/lib/featureManagement.ts, packages/shared/src/lib/featureValues.ts
- We decided on a winner for the bookmark vs share (share in card won) 
- This means we can cleanup and remove all the conditional rendering
- I opted to keep the new onShare/onBookmark passing as it's way more extendable for future proofing
WT-711 #done
=> chore: cleanup winner experiment

packages/extension/src/companion/Companion.spec.tsx, packages/shared/src/components/Feed.spec.tsx, packages/webapp/__tests__/PostPage.tsx
- We had some issues with test cases for the post page, we have to await the renders
=> chore: fix bookmark tests

packages/shared/src/components/filters/TagOptionsMenu.tsx
- Hotfix for linking to the right tag
- We no longer support the tag.name type in this format (but it's supported as a interface elsewhere)
WT-720 #done
=> fix: set correct tag links

project.garden.yml
- As we moved from `master` to `main` - when updating remote dependencies, it fails due to the config still pointing to master.
=> fix: garden dependencies to point to main

packages/shared/src/components/alert/AlertPointer.tsx, packages/shared/src/components/filters/MyFeedHeading.tsx
=> fix: stacked my feed heading

packages/shared/src/components/Feed.tsx
- navigator is a window object, we should wait till client side is active to invoke them.
- wrapping set code in useEffect is the proven way to interact with them in server side rendered components
=> fix: navigator share server side

packages/shared/src/components/modals/ReportPostModal.tsx, packages/shared/src/components/modals/common/ModalFooter.tsx
Adds support for Modal footer and replicates the Report Article modal
WT-730 #done
=> feat: report modal and modal footer

packages/shared/src/components/modals/NewCommentModal.tsx, packages/shared/src/components/modals/common/Modal.tsx, packages/shared/src/components/modals/common/ModalBody.tsx, packages/shared/src/components/modals/common/ModalFooter.tsx, packages/shared/src/components/modals/common/ModalHeader.tsx, packages/shared/src/components/modals/common/ModalTabs.tsx, packages/shared/src/components/modals/common/types.ts
- Add support for tabs to the modals
WT-731 #done
=> feat: modal tabs and footer changes

packages/shared/src/components/Feed.tsx, packages/shared/src/lib/navigator.ts
- It seems impossible to test the full static behaviour so I couldn't add specific test cases for this.
- However decided to create a new `getNavigator` function which can be used on the Next static side to get the navigator.
- This removes the need for the useEffect hook.
WT-727 #done
=> fix: cleanup navigator use with it's own function

packages/shared/src/components/sidebar/ClickableNavItem.tsx, packages/shared/src/components/sidebar/Sidebar.tsx
- Fix two issues with tracking events
- Ensure impression only triggers once
- Ensure link tracking happens (wasn't passed on the nav item)
=> fix: squad tracking events

packages/shared/src/hooks/useAssetPreload.ts, packages/shared/src/hooks/useOnboardingModal.ts
- Created a hook for preloading assets
- Preloaded the onboarding intro image
Tested through:
Preview deployment for onboarding feed filters -> clear cache -> reload -> skip -> set feature onboarding v2 -> refresh -> open onboarding -> result is a bit slow
Deployment of this PR -> clear cache -> reload -> skip -> set feature onboarding v2 -> refresh -> open onboarding -> result is noticeable.
This won't also block any form of rendering as part of having `ref="preload"` attribute.
| Change/New | event …
=> feat: preload onboarding image

packages/shared/src/components/MainFeedLayout.tsx, packages/shared/src/contexts/BootProvider.tsx, packages/shared/src/contexts/FeaturesContext.tsx, packages/shared/src/hooks/useOnboardingModal.ts, packages/shared/src/lib/links.ts
- Issue was onboarding is loaded very quickly and does not wait for the boot data to finish yet.
- Fix is to include a variable to check whether the data was fetched already.
Tagged @idoshamun for raising the issue.
=> fix: await features flags availability

packages/shared/src/components/MainFeedLayout.tsx, packages/shared/src/contexts/BootProvider.tsx, packages/shared/src/contexts/FeaturesContext.tsx, packages/shared/src/hooks/useOnboardingModal.ts
- One issue could be a race condition where we were not awaiting the variable we use when updating them, then the useEffect gets triggered to open the modal again. This would ensure setting the value has happened first before closing them modal.
=> fix: onboarding trap

packages/shared/src/contexts/BootProvider.tsx
- Used the `firstLoad` parameter to make sure everything is loaded locally.
- The issue was that fetched was accurate, but we set the state which requires another loop, and by that time, the modal is already open.
=> fix: await first load of boot data

packages/shared/src/components/sidebar/MyFeedButton.tsx, packages/shared/src/components/sidebar/SquadButton.tsx, packages/shared/src/components/sidebar/common.tsx
- The sidebar top margin was not consistent and in some cases too big.
- Now it's always 40px regardless of the rendered first element
WT-772 #done
=> fix: sidebar top margin issue

packages/shared/src/components/modals/common/ModalFooter.tsx, packages/shared/src/components/utilities.tsx
- Added Justify enum for fully qualified classnames and ease of import for the modal footer
WT-771 #done #1386
=> fix: added fully qualified type for justify modal footers

packages/shared/src/components/Feed.tsx, packages/shared/src/components/Settings.tsx, packages/shared/src/components/fields/Dropdown.tsx, packages/shared/src/components/sidebar/SidebarListItem.tsx, packages/webapp/components/layouts/AccountLayout/common.tsx
- Design found a couple remaining issues that are now addressed.
WT-789 #done
=> fix: last open icon changes from design feedback

packages/shared/src/components/comments/MainComment.tsx, packages/shared/src/components/comments/SubComment.spec.tsx, packages/shared/src/components/comments/SubComment.tsx, packages/shared/src/components/notifications/EnableNotification.tsx, packages/shared/src/components/post/PostComments.tsx, packages/shared/src/components/post/PostContent.tsx
Added a notification prompt when the user creates a new comment.
=> feat: notification prompt after new comment

packages/shared/src/components/modals/common/Modal.tsx
=> fix: modal height issue on ios

packages/shared/src/components/modals/SteppedModal.tsx, packages/shared/src/components/tooltips/BaseTooltip.tsx, packages/shared/src/components/tooltips/SimpleTooltip.tsx
- Currently we don't show the tooltips on touch devices, however for the stepped modal this blocks the user flow, thus we force load it there.
=> fix: show tooltip for stepped modal error state

packages/shared/src/components/notifications/EnableNotification.tsx, packages/shared/src/styles/components/buttons.css, packages/webapp/pages/account/notifications.tsx
I didn't realize I was not able to create the PR last week.
- The design was if the user accepts, the banner should temporarily still be visible, and when they go back it should be gone. This is on "enabled" process.
Note: will fix merge conflict once in a while. Just doing some setups.
=> fix: enabled message temporary state

packages/shared/src/components/Feed.tsx, packages/shared/src/components/ScrollFeedFiltersOnboarding.tsx, packages/shared/src/contexts/FeaturesContext.tsx, packages/shared/src/hooks/feed/useFeedInfiniteScroll.ts, packages/shared/src/lib/analytics.ts, packages/shared/src/lib/featureManagement.ts, packages/shared/src/lib/featureValues.ts, packages/shared/src/lib/image.ts, packages/webapp/__tests__/TagPage.tsx
- Introduces the new scroll feed filter experiment
- In the current implementation it technically means it always shows directly on the feed (due to how we assign the new load)
Version 1:
Version 2:
| New | impression  | target_type: scroll block, target_id: [V1, V2] |
| New | click scroll block  | target_id: [V1, V2] |
> Note: Only shows up on desktop sizes
WT-806 #done
=> feat: introducing feed filter scroll experiment

packages/extension/src/newtab/ShortcutLinks.spec.tsx, packages/shared/src/components/buttons/Button.tsx, packages/shared/src/components/layout/MainLayoutHeader.tsx, packages/shared/src/components/notifications/FirstNotification.tsx, packages/shared/src/components/notifications/utils.ts, packages/shared/src/components/tooltips/utils.ts, packages/shared/src/contexts/BootProvider.spec.tsx, packages/shared/src/contexts/BootProvider.tsx, packages/shared/src/contexts/NotificationsContext.tsx, packages/shared/src/lib/boot.ts, packages/webapp/__tests__/BookmarksPage.tsx, packages/webapp/__tests__/MainLayout.tsx, packages/webapp/__tests__/MostDiscussedPage.tsx, packages/webapp/__tests__/MostUpvotedPage.tsx, packages/webapp/__tests__/MyFeedPage.tsx, packages/webapp/__tests__/NotificationsPage.tsx, packages/webapp/__tests__/PopularPage.tsx, packages/webapp/__tests__/SearchPage.tsx, packages/webapp/__tests__/register.tsx, packages/webapp/components/FooterNavBar.tsx, packages/webapp/pages/notifications.tsx
- Boot provider to pass down unread count.
- Bubble component and usage on bell icon for the unread count.
- Unread count local data mutation.
- Fixed the first notification to be readable state.
Currently deployed at preview 1. You should be able to see the bubble text on header.
https://preview.app.daily.dev/
=> refactor: boot data type to include notifications data

packages/shared/src/components/notifications/EnableNotification.tsx, packages/shared/src/components/notifications/FirstNotification.tsx, packages/shared/src/components/notifications/NotificationItem.spec.tsx, packages/shared/src/components/notifications/NotificationItem.tsx, packages/shared/src/components/notifications/NotificationItemAvatar.tsx, packages/shared/src/components/notifications/utils.ts, packages/shared/src/graphql/notifications.ts
=> fix: notifications page inaccuracies

packages/shared/src/components/sidebar/ContributeSection.tsx, packages/shared/src/components/sidebar/Sidebar.tsx, packages/shared/src/contexts/FeaturesContext.tsx, packages/shared/src/graphql/notifications.ts, packages/shared/src/hooks/useSubmitArticle.ts
- In the preview below, I just replaced the URL of the first notification locally just to simulate how it would look like.
https://user-images.githubusercontent.com/13744167/209301517-4344feaa-f789-418c-9374-a966ab3c76a8.mov
WT-802 #done
=> feat: handling granting scout access notification

packages/shared/src/components/notifications/EnableNotification.tsx, packages/shared/src/components/notifications/NotificationIcon.tsx, packages/webapp/components/FooterNavBar.tsx, packages/webapp/pages/account/notifications.tsx
- Bell icon not to show when zero on mobile.
- Margin between banner image and text (should not be shown on laptop below [based on Sketch](https://www.sketch.com/s/2867ec63-0966-4647-b1d7-b6fe696ba251/a/xr3m8WA)).
- Required additional margin between the close button and contents.
- Notification icons are not the same sizes.
- Email notification settings not showing accurate value.
- Using the wrong GIF on Enable Notification banner and size when enabled. …
=> fix: notification bugs

packages/shared/src/graphql/users.ts
- Add bio field to profile, went missing in the SSG update
WT-770 #done
=> fix: add bio field to profile query

packages/shared/src/contexts/BootProvider.tsx, packages/shared/src/contexts/OnboardingContext.tsx
- In the current implementation we wait for the cache to be existing, however we never checked against `null` value, only undefined.
- This might even fix some other edge-cases we have seen before.
- Also modified the modal to wait for this loaded state
WT-900 #done
=> fix: awaiting the cache load, currently could be null

packages/webapp/pages/account/notifications.tsx
=> fix: web push displayed toggle only when supported

packages/webapp/components/FooterNavBar.tsx
=> fix: hide notifications tab on anonymous

packages/shared/src/contexts/NotificationsContext.tsx, packages/webapp/pages/account/notifications.tsx
WT-905 #done
[WT-905]: https://dailydotdev.atlassian.net/browse/WT-905?atlOrigin=eyJpIjoiNWRkNTljNzYxNjVmNDY3MDlhMDU5Y2ZhYzA5YTRkZjUiLCJwIjoiZ2l0aHViLWNvbS1KU1cifQ
=> fix: hide push notification alert on settings when enabled

packages/shared/src/hooks/useMyFeed.ts
- After numerous retries and reproduction, we have been miserably unable to replicate the concern.
- In order to understand what could be causing the modal to persist, we are looking to monitor the logs on the area where it can only fail before sending the event for completing onboarding.
=> refactor: feed filters creation monitoring

packages/shared/src/components/utilities.tsx, packages/webapp/components/layouts/ProfileLayout/index.tsx
-  Hotfix for profile page, we introduced a wrong load of style names and added a overwrite on max-width
- Also removed a unused class
=> hotfix: issue with profile page

packages/extension/src/companion/CompanionDiscussion.tsx, packages/shared/src/components/ProfilePicture.tsx, packages/shared/src/components/comments/MainComment.tsx, packages/shared/src/components/comments/SubComment.tsx, packages/shared/src/components/comments/common.tsx, packages/shared/src/components/modals/CommentBox.tsx, packages/shared/src/components/modals/NewCommentModal.spec.tsx, packages/shared/src/components/modals/NewCommentModal.tsx, packages/shared/src/components/post/NewComment.tsx, packages/shared/src/components/post/PostComments.tsx
- Fixed comment popup copy.
- Refactored the comment highlight based on Tomer's response: https://dailydotdev.slack.com/archives/C03QZBF46JC/p1673266631899009?thread_ts=1673175579.259209&cid=C03QZBF46JC
Note: anonymous user placeholder is not yet available for the comment box
=> fix: comment highlight and placeholder

packages/shared/src/components/notifications/utils.ts
- Change the upvote icon color to green
WT-930 #done
=> fix: upvote icon color

packages/extension/src/companion/CompanionContextMenu.tsx, packages/extension/src/companion/CompanionMenu.tsx, packages/shared/src/components/PostOptionsMenu.tsx, packages/shared/src/components/PostOptionsReadingHistoryMenu.tsx, packages/shared/src/components/ShareMobile.tsx, packages/shared/src/components/ShareOptionsMenu.tsx, packages/shared/src/components/cards/ActionButtons.tsx, packages/shared/src/components/comments/CommentActionButtons.tsx, packages/shared/src/components/post/PostActions.tsx, packages/shared/src/lib/boot.ts
- Sifted through the code base for any implementations of comment/bookmark/share that are still using `avocado` for color and updated those.
- Updated some old implementations, such as the CompanionDiscussion area.
Guideline:
- Upvote - Avocado
- Comment - Blue cheese
- Bookmarks - Bun
- Share - Cabbage
WT-934 #done
=> fix: color consistency on buttons

packages/shared/src/components/ShareOptionsMenu.tsx, packages/shared/src/components/modals/NewSquadModal.tsx
- auto pick an article when the share button on the post card is clicked then selected "Post to your Squad".
Note: In the preview below, I manually made the menu item available even when the user already has Squads.
https://user-images.githubusercontent.com/13744167/213085847-51570497-006b-460d-bf4d-a7b80f545fba.mov
WT-922 #done
=> feat: auto pick article on post card share new squad

packages/shared/src/components/ShareOptionsMenu.tsx
- Only show active squads in the share context
WT-940 #done
=> feat: only show active squads

packages/shared/src/components/squads/SquadHeaderMenu.tsx
- Temporary remove restart tour 
WT-949 #done
=> fix: turn off restart tour

packages/shared/src/components/auth/AuthModal.tsx, packages/shared/src/contexts/AuthContext.tsx, packages/shared/src/graphql/squads.ts, packages/webapp/pages/squads/[handle]/[token].tsx
- Refactored `LoginState` to include optional properties such as `referral`.
- Since `referral` was already built, there are no further changes required in the backend/auth system.
- After checking the taxonomy, I think it would be better to do it in one go for the analytics.
WT-846 #done
=> feat: squad referral

packages/shared/src/components/comments/CommentActionButtons.spec.tsx, packages/shared/src/components/comments/CommentActionButtons.tsx
- We made the delete option inside a context menu which should also be shown when the user is a moderator.
- Also added a test case for it.
=> fix: hidden options button when moderator

packages/shared/src/components/buttons/Button.tsx, packages/shared/src/lib/click.ts
- Introducing a generic onClick handler that applies onClick + onMouseUp (for auxiliary input)
WT-961 #done
=> fix: introduced a combined click handler

packages/shared/src/components/modals/LockedSquadModal.tsx, packages/shared/src/components/sidebar/Sidebar.tsx, packages/shared/src/components/squads/Ready.tsx, packages/shared/src/graphql/squads.ts
- The referral token was missing on the copy field for invitation link.
- We instead fetch the Squad data on LockedModal open.
WT-958 #done
=> fix: missing referral token on locked squad for invitation link

packages/shared/src/components/modals/NewSourceModal.tsx, packages/shared/src/components/modals/PushNotificationModal.tsx, packages/shared/src/components/notifications/EnableNotification.tsx, packages/shared/src/lib/image.ts
- Note: when you dismiss the enable permission widget on comments (and other places), you won't see this too. Goes the same when you dismissed this popup.
- Updated the copy based on the discussion in Slack: https://dailydotdev.slack.com/archives/C01L0QXQJNB/p1674036243515409?thread_ts=1673854401.136469&cid=C01L0QXQJNB
WT-960 #done
=> fix: do not display when the notification request again when dismissed

packages/shared/src/components/squads/utils.tsx
- Update modal to latest sketch file.
WT-965 #done
=> fix: quit squad modal

packages/shared/src/components/cards/SourceButton.tsx, packages/shared/src/components/notifications/NotificationItemAvatar.tsx
- Fix source targetURL when coming from notification avatar
WT-968 #done
=> fix: squad link when coming from notification avatar

packages/shared/src/components/squads/Details.tsx, packages/shared/src/graphql/squads.ts
I was not able to test this locally, but hopefully it should be ok :)
=> fix: display the image in squad edit

packages/shared/src/components/modals/PostToSquadModal.tsx
- Invalidate squad feeds on posting new article
- Decided to invalidate because other content might have been added as well.
WT-969 #done
=> fix: refresh feed

packages/shared/src/components/sidebar/Sidebar.tsx, packages/shared/src/hooks/useCreateSquadModal.ts
- Introduced both the fact that users can have squads or have access to the feature to the auto show modal.
- Users who get access to the feature and **don't** have a squad yet get to see it
- Users who gain access but **are** part of a squad don`t get to see it.
WT-976 #done
=> fix: auto prompt to beta members only

packages/shared/src/hooks/usePostById.ts, packages/webapp/pages/posts/[id].tsx
- Changed loading state for posts.
- If Server side succeeds (normal posts) we simply show that as initialData
- If Server side fails (auth posts, squads) we fallback to client side rendering
- Modified how we show the data merge
WT-979 #done
=> fix: share post loading

packages/shared/src/components/comments/CommentAuthor.tsx, packages/shared/src/components/comments/CommentBox.tsx, packages/shared/src/components/comments/SubComment.tsx
- Fixes the issue where the timeline is showing on top of comment replies avatars.
- Also fixes the alignment of timeline as I noticed it not being centered of the author avatar.
WT-997 #done
=> fix: comment replies avatar z-index

packages/shared/src/components/comments/CommentBox.tsx
before: (changed the line color temporarily to make it seen on preview)
after:
=> fix: profile picture vertical line

packages/shared/src/components/modals/ShareModal.tsx, packages/shared/src/components/post/PostItemCard.tsx, packages/shared/src/graphql/comments.ts, packages/shared/src/graphql/feed.ts, packages/shared/src/graphql/fragments.ts, packages/shared/src/graphql/posts.ts, packages/shared/src/graphql/sources.ts, packages/shared/src/graphql/squads.ts, packages/shared/src/graphql/users.ts
- As discussed, when the user tries to share a Squad post, the link should be directed towards the original article.
- I have also refactored the fragments to be contained in a single `fragments` file as I was having some deps issues.
- I have also checked previous implementations of `Fragments` and the word `Fragment` itself should not be part of the name.
- Note: still waiting for Sab's response on which title should we display in the reading history. Title of the actual article or the user's commentary but feel free to review. …
=> fix: share modal content

packages/webapp/pages/squads/[handle]/index.tsx
=> fix: display custom 404 when squad is not found

packages/shared/src/components/notifications/FirstNotification.tsx, packages/shared/src/components/notifications/InAppNotification.tsx, packages/shared/src/components/notifications/NotificationIcon.tsx, packages/shared/src/components/notifications/NotificationItem.spec.tsx, packages/shared/src/components/notifications/NotificationItem.tsx, packages/shared/src/components/notifications/utils.ts, packages/shared/src/graphql/notifications.ts, packages/webapp/__tests__/NotificationsPage.tsx, packages/webapp/pages/notifications.tsx
- This introduces the new notification type `View`.
- Applied specific themes for new squad posts and member notifications.
Preview: 
WT-897 #done
=> refactor: notification type for squads and theme

packages/shared/src/components/comments/MainComment.tsx
- Missing append tooltip to property.
- In the preview deployment, you can see the fix.
=> fix: hover on comment author z-index

packages/shared/src/components/post/SquadPostContent.tsx
- Shared post is showing the squad as source instead of the actual article post.
WT-1014 #done
=> fix: shared post source on details

packages/shared/src/components/Feed.tsx, packages/shared/src/hooks/useFeed.ts, packages/shared/src/hooks/usePostModalNavigation.ts, packages/webapp/pages/squads/[handle]/index.tsx
- The viewed mutation is successfully sent but the local data in the feed where it indicates being viewed was not getting updated.
- This PR should fix the decision whether to locally make it viewed based on post type.
- Feel free to test it in preview deployment vs our production deployment.
WT-1012 #done
=> fix: update local viewed post based on type

packages/shared/src/hooks/usePostById.ts, packages/webapp/pages/posts/[id].tsx
- For some reason, the post is always considered `stale`.
- This is being fixed by refetching the data since the sole purpose of that is to check the cache if it is stale.
- Since we have decided to bring back refetching, I have fixed it here.
- With that in mind, I have also ensured to fix the issue we have that repeatedly loads NOT_FOUND article by disabling the fetch itself when the `initialData` is not found.
- The `initialData` is always null when an error has occurred (including NOT_FOUND), so I believe that is a right fix. …
=> fix: stale post when navigating from reading history

packages/shared/src/components/squads/SelectArticle.tsx, packages/shared/src/graphql/users.ts
- Optional function to only return public posts for reading history.
- See API as well: https://github.com/dailydotdev/daily-api/pull/1164
WT-996 #done
=> fix: option to only return public posts for select article

packages/shared/src/hooks/useInAppNotification.ts, packages/shared/src/hooks/useLazyModal.ts, packages/shared/src/hooks/usePrivilegedSession.ts, packages/shared/src/hooks/usePrompt.ts, packages/shared/src/hooks/useToastNotification.ts
While trying to cleanup console clutter during development in #1573 I noticed another error that happens passively while clicking through the app `Error: Missing queryFn` coming from `useQuery` usages.
This happens in pattern when using useQuery as state hook. Valid fix should be to add queryFn that just loads up the current data of the query (if exists). I looked at the rest of the code and I can see that on some other places it is using the same pattern (eg. `packages/shared/src/components/notifications/Toast.tsx`) so I think these were just missed accidentally.
As far as I can see this does not break anything because all of the hooks fallback and handle when data is present or `undefined`. …
=> fix: missing queryFn console error in useQuery usages

packages/shared/src/hooks/usePostById.ts, packages/shared/src/hooks/usePostComment.ts, packages/shared/src/hooks/usePostContent.ts
- The issue from the new comment latency is not actually the request time.
- After further investigation, we don't show the comments list component when the `post.numComments` is at 0.
- It happens to update (after some time, thinking it is after mutation latency) due to our real-time updates through `useSubscription`. That is why it only happens on a post's very first comment.
- To fix the issue, I have created a utility function to update the post cache.
- Also created a function to generate a post query key as it is used in a lot of areas but didn't want to update everything in this PR.
Log the …
=> fix: new comment latency updating local data

packages/shared/src/components/Feed.tsx, packages/shared/src/components/modals/PostToSquadModal.tsx, packages/shared/src/components/modals/ShareModal.tsx, packages/shared/src/components/widgets/SocialShare.tsx, packages/shared/src/hooks/useFeed.ts, packages/webapp/pages/squads/[handle]/index.tsx
- Since I was testing out some theory of the `refetch` could be the issue (but turns out to be not), I took the liberty of reverting the `refetch` as we always tend to prefer it enabled.
- I also tested out and it shows the loading skeleton as opposed to the current behavior of flickering 404 page.
- I checked to access it on incognito and no flicker whatsoever.
- I updated the `useFeed` hook to accept the options for enabling refetch on mount. This is unwanted for regular feeds, but feeds like `Source` should be okay.
- Automatically closes the Share modal once the transaction for sharing a post to a squad was successful.
Don't forget to update the [Analytics Taxonomy sheet](https://docs.google.com/spreadsheets/d/18Lv7zXges9QfVX5VYL1a-Hyl0e1sQ3sL …
=> fix: squad feed not updating after sharing new post

packages/shared/src/components/Feed.tsx, packages/shared/src/components/modals/ArticlePostModal.tsx, packages/shared/src/components/modals/SharePostModal.tsx, packages/shared/src/components/post/FixedPostNavigation.tsx, packages/shared/src/components/post/PostContent.tsx, packages/shared/src/components/post/PostNavigation.tsx, packages/shared/src/components/post/SquadPostContent.tsx, packages/shared/src/hooks/usePostModalNavigation.ts
first post:
last post:
only post:
middle post:
=> feat: disable next/prev buttons on post modal

packages/shared/src/components/Custom404.tsx, packages/shared/src/graphql/common.ts, packages/webapp/pages/posts/[id].tsx, packages/webapp/pages/squads/[handle]/index.tsx
- We never get the Forbidden page since we never provide any information if the Squad actually exists except the error thrown by the API, which I agree is the best way.
- I have consolidated the errors to easily manage returned error codes.
- Also fixed the 404 page responsiveness.
=> fix: not showing forbidden squad pages

packages/shared/src/components/ShareOptionsMenu.tsx
- The icon size set for Squad image was inconsistent with what we have for our existing items.
- All should now follow the `24px` box size.
Preview:
WT-1040 #done
=> fix: share options menu icon size consistency

packages/shared/src/components/ShareOptionsMenu.tsx, packages/shared/src/components/modals/LockedSquadModal.tsx, packages/shared/src/components/modals/NewSquadModal.tsx, packages/shared/src/components/modals/SquadInviteModal.tsx, packages/shared/src/components/modals/common/Modal.tsx, packages/shared/src/components/modals/common/ModalStepsWrapper.tsx, packages/shared/src/components/modals/common/types.ts, packages/shared/src/components/post/PostContent.tsx, packages/shared/src/components/post/SquadPostContent.tsx, packages/shared/src/components/sidebar/Sidebar.tsx, packages/shared/src/components/squads/InviteTextField.tsx, packages/shared/src/components/squads/Ready.tsx, packages/shared/src/components/squads/SquadHeaderMenu.tsx, packages/shared/src/components/squads/utils.tsx, packages/shared/src/components/widgets/SocialShare.tsx, packages/shared/src/graphql/posts.ts, packages/shared/src/hooks/useCreateSquadModal.ts, packages/shared/src/hooks/useDeleteSquad.ts, packages/shared/src/hooks/useLeaveSquad.ts, packages/shared/src/hooks/useOnPostClick.ts, packages/shared/src/hooks/usePostContent.ts, packages/shared/src/lib/analytics.ts, packages/shared/src/lib/feed.ts, packages/webapp/pages/squads/[handle]/[token].tsx, packages/webapp/pages/squads/[handle]/index.tsx
- Introduces new tracking events for the squads beta
- Introduced a new way to track optional prev/next on stepped modals, would love to hear your thoughts. After this PR we can modify the other implementation as well.
There are a bunch of new events, without noting them down here, I refer to the taxonomy sheet:
https://docs.google.com/spreadsheets/d/18Lv7zXges9QfVX5VYL1a-Hyl0e1sQ3sLr0OK8YZWKXI/edit#gid=2069206456
WT-951 #done
=> feat: introduces squad tracking events

packages/shared/src/components/widgets/SocialShare.tsx, packages/shared/src/graphql/users.ts
- The reading history query was missing the private property.
- Also fixed the selections of Squad to be the active ones only.
- Let's open a ticket to consolidating our queries to use a Fragment for better maintenance I think.
=> fix: missing private property in reading history query

packages/shared/src/components/post/PostContent.tsx, packages/webapp/pages/posts/[id].tsx
- This should make the missing header actions in the post page come back.
- Feel free to test it in the preview deployment of this PR.
Preview:
Mobile size:
Desktop size:
WT-1049 #done
=> fix: missing actions button on article page

packages/shared/src/components/post/SquadPostContent.tsx, packages/webapp/__tests__/SquadTokenPage.tsx, packages/webapp/pages/squads/[handle]/[token].tsx
- Responsiveness of the Squad join page was missed. There should be a button under the description when it is mobile.
- This also fixes the wrap (overflow) issue on the "members waiting" list.
- I also fixed the missing left margin on the shared post content's cover image.
Preview:
WT-1058 #done
=> fix: squad join page responsiveness

packages/shared/src/components/squads/SquadHeaderMenu.tsx, packages/shared/src/components/squads/SquadPageHeader.tsx, packages/shared/src/components/tooltips/ContextMenuItem.tsx
- Apply 24px padding when it is on mobile.
Preview:
WT-1052 #done
=> fix: feedback button overlapping with title

packages/webapp/pages/devcard.tsx
- The page was not consuming the whole space, hence, the devcard is at the top most.
- Also applied easy centering classes.
Preview:
=> fix: devcard page responsiveness

packages/shared/src/components/BookmarkFeedLayout.tsx, packages/shared/src/components/PostOptionsReadingHistoryMenu.tsx, packages/shared/src/hooks/useBookmarkPost.ts, packages/shared/src/lib/query.ts
We had two options, update the data locally or allow refetch when the cache is stale.
The reason we didn't go for the first one is, there could be instances when you bookmark a post, you might not have all the necessary information when you toggled the bookmark (i.e. in reading history) which will then update the cache (of bookmarks feed), we will have to fetch to ensure the data is complete, else, the bookmarks feed might malfunction.
=> fix: refetch of bookmarks to update

packages/webapp/pages/_app.tsx
Just enabling react query devtools. Devtools are automatically excluded from production bundle by `react-query`. 
- https://tanstack.com/query/v4/docs/react/devtools#install-and-import-the-devtools
- https://github.com/TanStack/query/blob/main/packages/react-query-devtools/src/index.ts
Also, there is no need to `dynamic` import because in production devtools component is empty so import breaks.
I think they are really useful to just see all the active queries on the page and then working back and finding them inside the codebase. Especially when someone is just starting.
Log the new/changed events …
=> feat: enable react query devtools

packages/shared/src/components/post/PostItemCard.tsx
- The metadata was contained and the line-clamp was not working since there were two elements to consider.
- Sketch reference used: https://www.sketch.com/s/2bc42f67-3e55-4c07-bcf6-90ecdf74182b/a/kaOkrGo#Inspect
- Preview on local development:
WT-1077 #done
=> fix: reading history overlap with metadata

packages/extension/src/background/index.ts, packages/extension/src/companion/App.tsx, packages/extension/src/companion/companionFetch.tsx, packages/extension/src/companion/companionRequest.tsx, packages/extension/src/companion/useCompanionActions.ts, packages/extension/src/content/index.tsx, packages/shared/src/hooks/analytics/useAnalyticsQueue.ts, packages/shared/src/lib/extension.ts
- In context of #1605 @sshanzel mentioned it would be cool to add `enum` for message type in extension. This will be even better if added after #733 because then we will be able to properly type `browser.runtime.sendMessage` with generic and disallow unknown message types completely. 
=> refactor: move to enum for extension message type

packages/webapp/pages/squads/[handle]/index.tsx
- Wait for the boot to be fetched before triggering the load of Squad related requests.
WT-1079 #done
=> fix: boot and squad race condition

packages/shared/src/components/modals/PostToSquadModal.tsx, packages/shared/src/components/squads/Comment.tsx
- Refactored to use `useMutation` to handle loading OOTB.
WT-1081 #done
=> fix: loading state when sharing a post

packages/shared/src/components/squads/InviteTextField.tsx
- Add tracking event for squad sharing
| Change| share squad invitation  | extra: { squad: "squad.id" } |
WT-1091 #done
=> fix: add tracking event to squad invite

packages/shared/src/lib/analytics.ts, packages/webapp/pages/squads/[handle]/index.tsx
- Add once-off tracking for forbidden squad page.
- Determine either squadId or fallback to handle if unauthorised request (for logging purpose)
| New | view squad forbidden  | extra: { squad: [squadId or handle] } |
WT-1096 #done
=> feat: add tracking event for forbidden squad

packages/shared/src/contexts/AlertContext.tsx, packages/shared/src/contexts/BootProvider.tsx, packages/shared/src/graphql/alerts.ts, packages/shared/src/hooks/useSquadOnboarding.ts
- Applied the newly introduced property in the backend for `Alerts` entity.
- Has backwards compatibility for those who viewed the tour already to update API.
- API PR: https://github.com/dailydotdev/daily-api/pull/1185
WT-1097 #done
=> refactor: squad tour viewed device sync

packages/shared/custom.d.ts
Noticed svg module resolution not working in shared so just added missing definition.
=> fix: svg module resolution error in shared

packages/shared/src/components/squads/SquadHeaderBar.tsx, packages/shared/src/components/squads/SquadMemberShortList.tsx
- Apologies for some of the changes, it was pretty tough to read through the elements of the `SquadHeaderBar` as there are many things going on, so I have decided to extract it to a new component.
- The actual changes that fixed the responsiveness issue are:
- Line 32: https://github.com/dailydotdev/apps/pull/1640/files#diff-13db82f69e64251bf61f24b0ae6b2d856e78937dc7817993ed6053655599ad49R32
- Line 43: https://github.com/dailydotdev/apps/pull/1640/files#diff-13db82f69e64251bf61f24b0ae6b2d856e78937dc7817993ed6053655599ad49R43
- Line 50: https://github.com/dailydotdev/apps/pull/1640/files#diff-13db82f69e64251bf61f24b0ae6b2d856e78937dc7817993ed6053655599ad49R50 …
=> fix: squad header bar responsiveness

packages/shared/src/components/modals/CommentBox.tsx, packages/shared/src/components/modals/NewCommentModal.spec.tsx, packages/shared/src/components/modals/NewCommentModal.tsx, packages/shared/src/components/post/PostComments.tsx, packages/shared/src/graphql/posts.ts, packages/shared/src/hooks/usePostComment.ts
I started my day with this task and was already half way through when I switched to fixing comments from my open PRs so I have decided to finish this off since it was almost done already.
Currently deployed at: https://preview2.app.daily.dev/
Feel free to click the comment button on the user you want to reply to!
This also fixes the issue with "edit comment" to focus the cursor on the very last character automatically.
Recording from preview deployment:
https://user-images.githubusercontent.com/13744167/222039676-d616c9a3-b88e-4270-bb2f-96f64550e868.mov
Don't forget to update the [Analytics Taxonomy sheet](https://docs.google.com/spreadsheets/d/18Lv7zXges9QfVX5VY …
=> feat: reply to user when comment button is clicked

packages/shared/src/components/ConditionalWrapper.tsx, packages/shared/src/components/cards/ActionButtons.tsx, packages/shared/src/components/cards/ArticlePostCard.tsx, packages/shared/src/components/cards/SharePostCard.tsx, packages/shared/src/components/cards/common.tsx
- For some reason classed + the functional evaluation was not working for middle-clicks
- Decided to make it more inline with our existing systems and use the `ConditionalWrapper` component
- Verified both layouts still work
- List now fires middle click + opens the article
- Also fixed a small typo
WT-1108 #done
=> fix: middle click for list mode

packages/extension/src/newtab/DndModal.tsx, packages/shared/src/components/fields/Radio.tsx, packages/shared/src/components/modals/NewSourceModal.tsx, packages/shared/src/components/modals/ReportPostModal.tsx
This is also deployed at preview2. Should now flex as intended.
Preview:
- There was a missing flex: 1
=> fix: source submission icons

packages/shared/src/components/auth/AuthOptions.tsx, packages/shared/src/contexts/AuthContext.tsx
- There was a chance for the registration flow to be stuck because of the user reefch not happening.
- Moved the refetch and actually log if it returns no user.
WT-1134 #done
=> fix: registration stuck issue

packages/shared/src/components/post/SquadPostContent.tsx, packages/webapp/components/layouts/ProfileLayout/index.tsx
- Fix the profile image size
- Accidentally got overwritten with icon sizes
WT-1139 #done
=> fix: user profile image size

packages/shared/src/components/fields/ImageInput.tsx
- Replace footnote error with toast in ImageInput, since former broke the UI in most cases
WT-{1137} #done
=> feat: show image errors in toast

packages/shared/src/components/tooltips/ChangelogTooltip.tsx
- changelog would span full width due to absolute positioned element not wrapping by default
* [Long summary text (max 300 chars)](https://user-images.githubusercontent.com/9803078/224270051-82e5e9e9-d06b-45dc-96f6-5de6c3cca8e1.png)
* [Short summary text](https://user-images.githubusercontent.com/9803078/224270046-36fe5e9e-4a78-48e0-9399-5adcad90931b.png)
* [No summary](https://user-images.githubusercontent.com/9803078/224270044-c9983e0c-6 …
=> fix: added range for changelog width to not span to full width

packages/extension/src/background/index.ts, packages/extension/src/companion/App.tsx, packages/extension/src/companion/Companion.spec.tsx, packages/extension/src/companion/CompanionContextMenu.tsx, packages/extension/src/companion/CompanionMenu.tsx, packages/extension/src/companion/index.tsx, packages/shared/src/components/modals/PostToSquadModal.tsx, packages/shared/src/components/modals/ShareModal.tsx, packages/shared/src/components/modals/common/Modal.tsx, packages/shared/src/components/profile/SourceProfilePicture.tsx, packages/shared/src/components/squads/Comment.tsx, packages/shared/src/graphql/squads.ts
* Put bookmark button in the companion widget between comment and share
* Add support for sharing posts to squads from companion
* Bonus: Submit commenatry on CMD+Enter like we have for comments
Everything was tested locally.
Sidenote: Some sites block our images from loading but it's a known issue as far as I recall. It's relevant for squad images and user images
=> feat(companion): show bookmark button and support share to squad

packages/extension/src/companion/App.tsx
- The companion was missing the prompt element thus disable was never working.
WT-1146 #done
=> fix: companion prompt issue

packages/extension/src/companion/Companion.tsx
- core issue was in post data coming from boot was persisted in local state inside `Companion`, this then did not react to cache updates that usually happen during comment posting/updates
- with this changes post data is now automatically updated during cache invalidation and other side effects that happen (same as in webapp), UI also updates automatically due to this
- comment count
- comment list
- post metadata
- NOTE here would be to refactor all of companion to just `useQuery` instead of props drilling but for now I just added it to the top to mimic `useState` …
=> fix(companion): new comment modal now closes after posting

packages/extension/src/companion/App.tsx
- As we use react-query in extension as well there is reason to not have devtools here too.
=> feat: add react query devtools for extension

packages/webapp/pages/history.tsx
- Show fallback empty page only if user has no bookmarks
- Show search results empty component if bookmark search has no results
- Fixes https://github.com/dailydotdev/daily/issues/765
* [No search results](https://user-images.githubusercontent.com/9803078/224854571-abc4b1b2-def2-4521-9052-ce9cfd842720.png)
WT-741 #done
=> fix: fallback is now triggered only if user has no bookmarks

packages/shared/src/components/post/PostComments.tsx
- Comment link is now always be visible inside the view (without sticky header overlap)
- Current implementation uses `scrollIntoViewOptions` to center comment into view
- `block: center` means center vertically
- `inline: nearest` is default value for horizontal alignment, since we do not have horizontal scroll it will always center of course
- check screenshots below for how it looks for different comment positions
- I think current method works well and fixes issue with sticky header by always positioning comment into center of view as best as it fits. It also uses `scrollIntoView` function which is made for this kind of thing.
- If we want to put scroll position just few px above comment box we could use `block: start` but the same issue with overlapping sticky header would happen …
=> fix: always center selected comment into view

packages/shared/package-lock.json, packages/shared/package.json, packages/shared/src/components/tooltips/ChangelogTooltip.spec.tsx, packages/shared/src/components/tooltips/ChangelogTooltip.tsx
- Fixes issue where extension update button would always result in error
- Browser polyfill was not loaded in production extension bundle (while it is loaded during development and exposed in `globalThis`)
- While I could not find core reason for this (looking at webpack configs and build script), I think it is due to this being the only place where polyfill is required inside the shared package
- To fix I added polyfill as shared dependency and lazy load it when extension update is requested
- I also checked other places and all of them are from extension package and already use polyfill so this bug is not present
Don't forget to update the [Analytics Taxonomy sheet](https://docs.google.com/spreadsheets/d/18Lv7zXges9QfVX5VYL1a-Hyl0e1sQ3sLr0OK8YZW …
=> fix: changelog browser polyfill in production extension bundle

packages/shared/src/contexts/NotificationsContext.tsx
- The memoized returned value was not getting updated, hence, when it should have been closed, it was still displayed.
WT-1174 #done
=> fix: close notification banner in notifications settings

packages/shared/src/components/modals/NewSquadModal.tsx, packages/shared/src/components/modals/SquadTourModal.tsx, packages/shared/src/components/sidebar/Sidebar.tsx, packages/shared/src/components/squads/SquadHeaderBar.tsx, packages/shared/src/components/squads/SquadHeaderMenu.tsx, packages/shared/src/components/squads/SquadPageHeader.tsx, packages/shared/src/components/squads/SquadTourPopup.tsx, packages/shared/src/hooks/useSquadTourClose.ts, packages/shared/src/hooks/useTutorial.spec.tsx, packages/shared/src/hooks/useTutorial.ts, packages/webapp/pages/squads/[handle]/index.tsx
- Prompt notifications only once tour is closed.
- @capJavert will cause some merge conflict with your one :)
WT-1175 #done
=> fix: add tutorial for notification prompt

packages/shared/src/components/post/PostSourceInfo.tsx, packages/shared/src/components/post/SquadPostContent.tsx, packages/webapp/pages/posts/[id].tsx
* Not sure why we had this snippet there but there's no reason to redirect the user to the permalink of the post when they land on the article page. We should either show 404 or show the article page.
* Clicking on the referred post section in the "share post" page should lead to another post page unless it's from the unknown source
* We shouldn't show the image and handle of the unknown source
=> fix: multiple fixes to "share post" page

packages/shared/src/components/squads/SharePostBar.tsx
- For the temporary fix of allowing existing private links and continuing the support for the Companion, we will make the change on FE only.
- If the error is FORBIDDEN, it means it exist, hence, continue with the process.
WT-1182 #done
=> fix: existing private links to still be submitted

packages/shared/src/lib/timezones.ts
- The offsets having a value of greater than 24 have exactly an excess of 24 on the offset itself.
- Refactored the function fetching the offset to also return the numerical value to be used for sorting.
WT-651 #done
WT-291 #done
=> fix: timezone order and offset

packages/extension/src/newtab/LinksForm.tsx, packages/shared/src/components/fields/SearchField.tsx, packages/shared/src/components/modals/NewSourceModal.tsx, packages/shared/src/components/modals/ShareModal.tsx, packages/shared/src/components/modals/SharedBookmarksModal.tsx, packages/shared/src/components/modals/SubmitArticleModal.tsx, packages/shared/src/components/profile/ProfileForm.tsx, packages/shared/src/components/squads/Comment.tsx, packages/shared/src/components/squads/InviteTextField.tsx, packages/shared/src/components/squads/SharePostBar.tsx
- The product has decided to remove the auto-fill suggested values when submitting a community link.
WT-1176 #done
=> refactor: community link submission autofill suggestions removal

packages/shared/src/lib/strings.ts
- Whitelist hyphens when mentioning a user.
- The function updated here are only used by the user mention feature.
Preview:
WT-1179 #done
=> refactor: user mention allowing hyphens to be used

packages/shared/src/components/modals/PostToSquadModal.tsx
- As mentioned here https://github.com/dailydotdev/apps/pull/1703#discussion_r1150726244
- this should only show toast for processing if link is being shared
=> fix: processing toast only show if private link submitted

packages/shared/src/components/Feed.tsx, packages/shared/src/components/PostOptionsMenu.tsx, packages/shared/src/components/modals/ArticlePostModal.tsx, packages/shared/src/components/modals/SharePostModal.tsx, packages/shared/src/components/post/PostContent.tsx, packages/shared/src/components/post/PostModalActions.tsx, packages/shared/src/components/post/PostNavigation.tsx, packages/shared/src/components/post/SquadPostContent.tsx, packages/shared/src/graphql/posts.ts, packages/shared/src/graphql/sources.ts, packages/shared/src/hooks/usePostMenuActions.ts, packages/shared/src/hooks/usePostModalNavigation.ts
- Return the current member and the permissions to check whether access is valid for deleting a post.
- Allow shared post author to delete their own posts.
WT-1202 #done
=> feat: delete post as a moderator/owner or author of shared post

packages/shared/src/graphql/feed.ts, packages/shared/src/graphql/posts.ts, packages/shared/src/lib/feed.ts
`feedMeta` is a new property provided by the feed service and used for analytics purposes.
Add a new property `feed_item_meta`
=> feat: send feed metadata with analytics events

packages/shared/src/graphql/fragments.ts, packages/shared/src/graphql/posts.ts
- CurrentMember was evaluating user?.id and this was missing from the fragment.
- Can't seem to find when it went missing, but added a fragment to avoid it in future. (This also uniforms currentMember needs)
WT-1222 #done
=> fix: feedback url was missing user id

packages/shared/src/components/PostOptionsMenu.tsx, packages/shared/src/components/post/PostModalActions.tsx, packages/shared/src/graphql/feed.ts, packages/shared/src/graphql/fragments.ts, packages/shared/src/graphql/posts.ts, packages/shared/src/graphql/users.ts, packages/shared/src/hooks/usePostMenuActions.ts
The context menu for post modal and the feed card was not unified in terms of behavior but using the same component.
Note: pointed to main as removing post is already available.
- Since both areas were using the same context menu component, we've updated how we identify allowing deletion of post.
- Also refactored the fragment to be unified so nothing will be missed out when looking for the information needed to identify whether the user can delete a post in the regular feed.
| Change/New | event name …
=> fix: missing context menu items on feed cards

packages/shared/src/components/profile/UserShortInfo.tsx, packages/shared/src/components/squads/SquadMemberItemAdditionalContent.tsx, packages/shared/src/components/squads/SquadMemberMenu.tsx
- Remove hover state on prompt styling
- Ensure it's centered in the block
WT-1228 #done
=> fix: prompt styling

packages/shared/src/components/post/SquadPostContent.tsx
- We set the with to occupy all space but only works on modal as we set its max width.
- To fix the issue above, we should also apply the max width we have for the modal, which was missing in the first place.
Preview:
WT-1230 #done
=> fix: missing container class for squad post page

packages/shared/src/components/PostOptionsMenu.tsx, packages/shared/src/components/post/PostComments.tsx, packages/shared/src/hooks/usePostMenuActions.ts
- Updated the post context menu label for deleting a post and prompt description.
- Updated the delete comment prompt's title and confirm color.
WT-1239 #done
WT-1240 #done
=> refactor: post context menu removing post label

packages/shared/src/components/squads/SquadMemberMenu.tsx
- Ensure moderators can only remove members and not other moderators or admins
WT-1249 #done
=> fix: remove only members

packages/shared/src/components/Feed.tsx, packages/shared/src/components/modals/ArticlePostModal.tsx, packages/shared/src/components/modals/BasePostModal.tsx, packages/shared/src/components/modals/SharePostModal.tsx, packages/shared/src/components/post/BasePostContent.tsx, packages/shared/src/components/post/PostContent.tsx, packages/shared/src/components/post/PostContentContainer.tsx, packages/shared/src/components/post/PostLoadingSkeleton.tsx, packages/shared/src/components/post/SquadPostContent.tsx, packages/shared/src/hooks/usePostById.ts, packages/webapp/pages/posts/[id].tsx
- Fixes the issue where forbidden throws an error instead of showing the 404 page. Since we now support requesting the static information to fill the page, our previous condition doesn't work anymore.
- Also saw some discrepancies on the loading page when the error happens. Since there are two kinds (page and modal) of when to display it, I have refactored it to render from where it needs to happen (page and modal) than fitting to all 4 cases (all combinations).
- Fixed some typos.
- Have tested all four cases thoroughly. Will test it in preview once a deployment gets free tomorrow.
- Code-wise though this should be reviewable. Feedback would be highly appreciated, had to test all 4 cases every change, so I might have missed something.
- …
=> fix: forbidden page throwing error

packages/shared/src/components/post/SquadPostContent.tsx, packages/shared/src/hooks/useMemberRoleForSource.ts
- With new later return we need to make props optional to not-break rendering.
WT-1250 #done
=> fix: optional data for when modal loading

packages/shared/src/hooks/useLazyModal.ts, packages/webapp/pages/_app.tsx
- Added global listener per comments here https://dailydotdev.slack.com/archives/C02E2C3C13R/p1681299753422359
- Added it to _app due to router not being available for extension and we do not really have any route changes that happen in extensions (anything that changes route goes to app.daily.dev)
- `popstate` event does not really work since it is not triggered for route changes
- My concern with this is that we are adding this for all lazy modals, we might want specific behaviour of not closing for specific modals
- I would alternatively implement calling `closeModal` inside event handlers eg. when clicking item `UserListModal`
Don't forget to update the [Analytics Taxonomy sheet](https://docs.google.com/spreadsheets/d/18Lv7zXges9QfVX5VYL1a-Hyl …
=> feat: add global listener to history change to close lazy modal

packages/shared/src/components/modals/common/ModalBody.tsx
- We where using `flex-1` on the textfield, but the parent was not actually a flex item so no flexing applied.
- Added it now to the modal body. (Tested various modals non seem breaking)
- The small bottom part is reserved space for the error message
WT-1255 #done
=> fix: edit comment height

packages/shared/__tests__/fixture/squads.ts, packages/shared/src/components/notifications/utils.ts, packages/shared/src/components/squads/SquadMemberBadge.tsx, packages/shared/src/components/squads/SquadMemberMenu.tsx, packages/shared/src/graphql/sources.ts, packages/webapp/__tests__/SquadFeedPage.tsx, packages/webapp/__tests__/SquadTokenPage.tsx
- Change all owner texts to admin
WT-1236 #done
=> fix: refactor owner to admin

packages/shared/src/components/squads/SquadMemberItemAdditionalContent.tsx, packages/shared/src/components/squads/SquadMemberMenu.tsx
- Small copy change see here: https://dailydotdev.slack.com/archives/C01L0QXQJNB/p1681479731311269?thread_ts=1681479342.294069&cid=C01L0QXQJNB
- And line break issue on the prompt
WT-1257 #done
=> fix: copy changes to be more inline and line-break fix

packages/webapp/components/layouts/AccountLayout/AccountPageContainer.tsx
- The issue mainly comes because of the dynamic url bar that shows/hides while scrolling on iOS
- `dvh` unit solves this because it accounts for those dynamic changes https://developer.mozilla.org/en-US/docs/Learn/CSS/Building_blocks/Values_and_units
- left the fallback to `vh` for browsers that do not support dynamic units
WT-1252 #done
=> fix: use dvh instead of vh to account for dynamic url bar on ios

packages/shared/src/components/fields/Radio.tsx, packages/shared/src/components/modals/EditSquadModal.tsx, packages/shared/src/components/squads/Details.tsx, packages/shared/src/graphql/fragments.ts, packages/shared/src/graphql/sources.ts, packages/shared/src/graphql/squads.ts
- Add memberInviteRole to squad create
- Add memberInviteRole to squad settings
- Update permissions to include new `Invite` permission
- Update fragments/mutations to accept `memberInviteRole` field
- update copy per design
- API implementation here https://github.com/dailydotdev/daily-api/pull/1240
Also includes WT-1265 since changes are closely related.
WT-1264 #done
=> feat: add member invite option to squad create and edit

packages/shared/src/hooks/usePostById.ts, packages/webapp/pages/posts/[id].tsx
- I fixed this earlier while waiting on some reviews but forgot to raise the PR 😅 
- Fixes the SEO preview.
- Fixes the loading not being seen.
- `isFallback` is NextJS telling that the getStaticProps is still loading.
Feel free to copy paste the link below on Slack and see if a preview shows up. Also visiting the link you should see the loading placeholder.
Quick link: https://daily-webapp-pe9dxfcqo-dailydotdev.vercel.app/posts/XlISrsqLo
=> fix: page seo and loading

packages/shared/src/components/ProfilePicture.tsx
- From the screenshot of the error, the issue seems to be coming from this component when the passed value is null.
Reference image:
=> fix: return null if object is null

packages/shared/src/hooks/usePostModalNavigation.ts
- I could not really get anything concrete on this so wanted to propose a different approach
- I also checked and this does not happen on Android phones I have on me Android 12 and 13
- As said in tasks and reports seems like iOS only issue when clicking "X" close button
- Also, if user just uses back button (instead of "X") scroll restoration works and they do not get jumped to top 
- To fix this I implemented a ref to save scroll position on feed when post modal gets opened, I keep it and when modal is closed by clicking on "X" I just restore that position and that works
- also it does not break desktop/other platforms since they just retain scroll normally
I know this does not fix the core issue but if iOS browser was conforming to the spec this would not even be the problem so I think …
=> feat: remember scroll position and restore after post modal close

packages/shared/src/components/cards/SharedPostCardFooter.tsx
- Fixed a fallback for our share post card
- Since we load this as a background image (needed for the 3 different render sizes) we can only rely on secondary notation for background-image. 
- Downside of the above: It loads the fallback image even when it's not shown (see image)
- **Do let me know what you think of this.**
WT-1275 #done
=> fix: fallback resolve for share post card

packages/shared/src/components/notifications/NotificationItemAttachment.tsx
- We weren't using the `Image` component which leverages fallback images.
WT-1260 #done
=> fix: add correct image component for fallback loading

packages/shared/src/components/modals/PostToSquadModal.tsx
- Tested locally. Works and able to post now through history.
=> fix: optional chaining unavailable object

packages/shared/src/components/Feed.tsx, packages/shared/src/components/ScrollFeedFiltersOnboarding.tsx, packages/shared/src/contexts/FeaturesContext.tsx, packages/shared/src/lib/featureManagement.ts, packages/shared/src/lib/featureValues.ts
- Cleanup experiment winner for scroll block
- Left analytics intact with winner value
WT-1306 #done
=> fix: clean up experiment winner for scroll block

packages/shared/src/components/MainLayout.tsx, packages/shared/src/components/notifications/EnableNotification.tsx, packages/shared/src/components/notifications/InAppNotification.tsx, packages/shared/src/components/notifications/utils.ts, packages/shared/src/hooks/useAuthVerificationRecovery.ts, packages/shared/src/hooks/useNotificationParams.ts, packages/shared/src/lib/analytics.ts, packages/shared/src/lib/links.ts, packages/webapp/pages/notifications.tsx
@rebelchris since we have merged the new notification type, I realized that it will now show up for everyone since we don't have yet an idea if people have subscribed since we just introduced the actions table.
This is basically the same PR of this https://github.com/dailydotdev/apps/pull/1775 but pointed to main,
=> fix: hide unnecessary notification

packages/shared/src/components/sidebar/common.tsx
Changing the overlay bg from grey for the mobile sidebar to the quaternary onion as per other overlays
=> feat: setting the overlay bg to the correct color for mobile sidebar

packages/shared/src/hooks/useActions.ts
- make sure optimistic update works when no actions are completed, currently optimistic update would not go through (API call worked)
- skip API call if action is completed locally, optimization to avoid calling `checkHasCompleted` in all places we use `completeAction`
=> feat: adjustments to useActions after some usage in other tickets

packages/shared/src/components/squads/SquadHeaderBar.tsx
- Realised that we have tooltips disabled by default on touch devices
- Since this is a specific case where we wanna show checklist status (eg. 0/5) `forceLoad` is used
=> fix: checklist status on touch devices

packages/shared/src/components/squads/SquadHeaderBar.tsx, packages/webapp/__tests__/SquadFeedPage.tsx
- Latest changes introduced some possibly flaky test cases
- Added missing completeAction nock when copying invite link since https://github.com/dailydotdev/apps/pull/1783 introduced it
=> fix(squads): invite permission tests

packages/shared/src/components/post/SquadPostContent.tsx
Since our input form accepts new line on its content, we should also be able to display the user's commentary with break lines.
Have deployed on preview2. Feel free to test it out 🥳 
https://preview2.app.daily.dev/
Sample post:
=> fix: squad post commentary breakline

packages/shared/src/components/post/PostFeedFiltersOnboarding.tsx, packages/webapp/pages/posts/[id].tsx
- While implementing checklist step for welcome post I noticed some display issues
Before (too much width and notification image not aligned):
After:
=> fix: welcome post modal width

packages/shared/src/components/modals/common/Modal.tsx
- With the migration of modals, we missed fixing the scrolling on long comments which had a discussion in the past already.
- For reference, this was the accepted design:
https://dailydotdev.slack.com/archives/C02AA18RD1D/p1651499956941809?thread_ts=1651144522.037189&cid=C02AA18RD1D
Preview:
WT-1330 #done
=> fix: replying to long comment scroll

packages/shared/src/components/cards/WelcomePostCard.tsx, packages/shared/src/components/squads/SquadPageHeader.tsx
- add pulse animation when squad first post is active
- add pulse animation when squad first comment is active
WT-1335 #done
=> feat(checklist): pulse animation on squad page depending on active step

packages/shared/src/graphql/users.ts
Fixes dailydotdev/daily#861
Fix the hashnode profile not showing on account profile.
Not able to take screenshots as we cant run auth in Gitpod.
=> fix: hashnode profile not showing on daily.dev account

packages/shared/src/components/Feed.tsx, packages/shared/src/components/PostOptionsMenu.tsx, packages/shared/src/components/post/PostComments.tsx, packages/shared/src/components/post/PostModalActions.tsx, packages/shared/src/hooks/usePostMenuActions.ts, packages/shared/src/lib/analytics.ts
- Awaiting Sab/Ido confirmation on using the post tracking in favor of adding manual sources
|New | delete post  | extra: { origin } |
|New | delete comment  |  |
WT-1331 #done
=> fix: added v4 related tracking events

packages/shared/src/components/checklist/SquadChecklistCard.tsx, packages/shared/src/lib/analytics.ts
- @capJavert as we don't have the new hook yet I still used the old useEffect hack to only fire once.
- The only one missing is `checklist completion` we need to find a way to unique identify it 
| New | impression (onboarding checklist) | extra: { squad } |
| New | checklist close | extra: { squad } |
WT-1328 #done
=> fix: add v5 tracking events

packages/shared/src/components/modals/NewSourceModal.tsx, packages/shared/src/components/modals/PostToSquadModal.tsx, packages/shared/src/components/notifications/EnableNotification.tsx, packages/shared/src/hooks/useEnableNotification.ts
- Have unified the process on whether to display the toggle or not. Feel free to check the difference between preview and preview2.
- Also, I think the toggle/banners won't show since we don't have a OneSignal dedicated for preview deployments.
https://preview.app.daily.dev/squads/newsquad123
https://preview2.app.daily.dev/squads/newsquad123
=> fix: notification toggle

packages/shared/src/components/cards/WelcomePostCard.tsx, packages/shared/src/components/checklist/ChecklistCard.spec.tsx, packages/shared/src/components/squads/SquadPageHeader.tsx, packages/shared/src/hooks/useChecklist.spec.tsx, packages/shared/src/hooks/useChecklist.ts
- Moved from useState to react query to have better control as multiple subscribers go to the same state
- Moved from active state to openState
WT-1360 WT-1363 #done
=> fix: move pulse states to react query and on OpenState

packages/shared/src/components/checklist/NotificationChecklistStep.tsx, packages/shared/src/contexts/NotificationsContext.tsx, packages/shared/src/hooks/useEnableNotification.ts
- Since we did an actual retro check from the BE, we don't need the use effect to identify whether the user is not yet subscribed.
- Made the checklist step to utilize our unified actions for notifications.
- Instead of relying on the use effect, we now explicitly complete the action once permission is granted.
=> fix: subscribe checklist

packages/shared/src/components/RecommendedMention.tsx, packages/shared/src/components/profile/UserShortInfo.tsx
Adding this prop to make the description optional, this has been added for mentions popup to exclude the description in this one location
WT-1365 #done
=> feat: Adding prop to hide description in UserShortInfo

packages/shared/src/components/post/WelcomePostContent.tsx
The welcome post was using a fixed width image so was breaking mobile i changed this to a max-width instead
WT-1372 #done
=> feat: changing welcome image to max-width and not fixed

packages/shared/src/components/modals/common/Modal.tsx
I remove the MobileL breakpoint for this modal as it was breaking using the h-full for mobile, setting it to h-auto made the modal container go the correct height for the content
WT-1371 #done
=> feat: fixing the mobile modal height to stop the modal bg cutting off

packages/shared/src/contexts/AnalyticsContext.tsx, packages/shared/src/contexts/NotificationsContext.tsx, packages/shared/src/hooks/analytics/useAnalyticsContextData.ts, packages/webapp/pages/popup/notifications/enable.tsx
Use OneSignal events to trigger proper tracking of events. I also made sure the popup sends all the events before closing by utilizing `sendBeacon`. Unfortunately, there is no way for me to test beside production because of OneSignal limitations.
=> fix: notification tracking

packages/shared/src/contexts/NotificationsContext.tsx, packages/webapp/pages/popup/notifications/enable.tsx
I found an edge case where permission is already granted on the device, but a new user is asking for push notifications
=> fix: second notification tracking

packages/shared/src/components/modals/SubmitArticleModal.tsx
Added a button to close the modal on submit article once you have submitted the article
=> feat: adding new modal footer button to close submit article modal

packages/shared/src/components/alert/AlertPointer.tsx, packages/shared/src/components/post/freeform/write/WriteFreeformContent.tsx, packages/shared/src/graphql/actions.ts, packages/shared/src/hooks/useActions.ts
- For first time users writing a post, whether editing (welcome post) or writing a new one, we should display an alert pointer.
WT-1352 #done
=> feat: first time writing post alert

packages/shared/src/components/checklist/SquadChecklistCard.tsx, packages/shared/src/components/squads/SquadHeaderBar.tsx, packages/shared/src/hooks/useActions.ts, packages/shared/src/hooks/useSquadChecklist.tsx
Adding a isFetched property to the useActions hook, this will allow components like the Tooltip for the checklist progress to not render till the data is fetched.
=> feat: Adding checklist ready property to wait for data before rendering components

packages/shared/src/components/Loader.tsx, packages/shared/src/components/fields/ImageInput.tsx, packages/shared/src/components/fields/MarkdownInput/MarkdownUploadLabel.tsx, packages/shared/src/components/fields/MarkdownInput/index.tsx, packages/shared/src/components/post/freeform/write/WriteFreeformContent.tsx, packages/shared/src/graphql/posts.ts, packages/shared/src/hooks/input/index.ts, packages/shared/src/hooks/input/useMarkdownInput.ts, packages/shared/src/hooks/input/useSyncUploader.ts, packages/shared/src/lib/textarea.ts, packages/webapp/pages/squads/[handle]/create.tsx
File upload by dropping files on the textarea or clicking the footer of the textarea itself.
The process flow is taken from the current behavior of GitHub's markdown input support for files. The upload process can be done with multiple files but each file is processed one after the other.
Have refactored to make the instance of the command class be created only once. …
=> feat: upload images on markdown

packages/shared/src/components/fields/BaseFieldContainer.tsx, packages/shared/src/components/fields/MarkdownInput/index.tsx, packages/shared/src/components/fields/TextField.tsx, packages/shared/src/components/post/freeform/write/WriteFreeformContent.tsx, packages/shared/src/components/post/freeform/write/WritePage.tsx, packages/shared/src/hooks/input/useMarkdownInput.ts, packages/webapp/pages/posts/[id]/edit.tsx, packages/webapp/pages/squads/[handle]/create.tsx
- Usage of persistent context would allow saving the changes on a local cache state.
- This also fixes the issue with the guideline for input on primary fields with uncontrolled states.
WT-1350 #done
=> feat: support local draft

packages/shared/src/components/post/freeform/write/WriteFreeformContent.tsx, packages/shared/src/hooks/input/useDiscardPost.ts, packages/webapp/pages/posts/[id]/edit.tsx, packages/webapp/pages/squads/[handle]/create.tsx
- Updated the copy for the cover image to Thumbnail.
- Fixed the freeform draft to wait for the cache to be loaded first.
=> fix: wait freeform draft and copy change

packages/shared/src/components/post/freeform/write/WriteFreeformContent.tsx, packages/shared/src/hooks/input/useDiscardPost.ts
- After further investigation, it seems the issue was not directly the keyboard navigation on mention but rather on the debounced function.
- When we try to mention someone, we type the `@` character where we trigger a debounce to update the draft, and during the process of selecting users to mention, the debounce await has finished and triggered the update of cache but it throws an error internally. It was due to the `draft` being nullable when referencing the `image` property to not be overwritten.
Log the …
=> fix: unstable mention navigation

packages/shared/src/components/fields/MarkdownInput/index.tsx, packages/shared/src/components/tooltips/BaseTooltip.tsx, packages/shared/src/components/tooltips/RecommendedMentionTooltip.tsx, packages/shared/src/hooks/input/useMarkdownInput.ts
- When a user clicks the textarea and points directly at a mention word, we should initialize back the mention for better UX.
- Also when the user clicks outside the tooltip, we should close it.
=> fix: comment mention click handlers

packages/shared/src/components/post/freeform/write/WriteFreeformContent.tsx, packages/shared/src/hooks/input/useDiscardPost.ts, packages/webapp/pages/posts/[id]/edit.tsx, packages/webapp/pages/squads/[handle]/create.tsx
- When a draft image is saved locally, we are displaying it when the user comes back, but since we don't apply the value to the element on load, we should properly check if there is anything available in the draft.
- Also refactored the submit function to simplify and to just receive the params then change it if necessary.
=> fix: draft image

packages/shared/src/hooks/input/useDiscardPost.ts, packages/webapp/pages/posts/[id]/edit.tsx, packages/webapp/pages/squads/[handle]/create.tsx
- squad.id is default identifier in draft inside `useDiscardPost` so this makes sure that correct one is used
=> feat: make sure correct draft key is created after post creation

packages/shared/src/components/cards/WelcomePostCardFooter.tsx, packages/shared/src/graphql/feed.ts
- Instead of rendering the raw content, we should use the html markdown content then strip all the tags.
- Would love to hear your thoughts on this.
Quick link: https://preview.app.daily.dev/squads/dailydev2
Before:
After:
=> fix: feed card rendering without tags

packages/shared/src/components/modals/CommentBox.tsx, packages/shared/src/components/squads/SharePostBar.tsx
- Our input boxes have been decided to be `17px`. Since the `MarkdownInput` and `SquadComment` is already up to date, below are only what's left:
- `CommentBox` when making comments.
- `SharePostBar` when submitting external links.
WT-1430 #done
=> refactor: comment boxes to make font to typo body

packages/shared/src/components/fields/MarkdownInput/SavingLabel.tsx, packages/shared/src/components/fields/MarkdownInput/index.tsx, packages/shared/src/components/post/freeform/write/WriteFreeformContent.tsx, packages/shared/src/contexts/WritePostContext.ts, packages/shared/src/hooks/input/useDiscardPost.ts, packages/shared/src/hooks/usePersistentContext.ts, packages/webapp/pages/squads/create.tsx
- Add a label based on whether the draft is being saved or if it is up to date.
=> feat: show an indicator when draft is saved and is saving

packages/shared/src/components/post/SquadPostContent.tsx
- Now that we have a dedicated page for editing a post, we don't need the button in the modal header anymore as we already have one option in the post options menu that redirects to the said editing post page.
=> refactor: post modal removing edit post button

packages/shared/src/components/cards/WelcomePostCard.tsx, packages/shared/src/components/cards/WelcomePostCardFooter.tsx, packages/shared/src/graphql/feed.ts
- The primary goal here was to sanitize all HTML outputs but after further investigation, it seems all of our implementation of HTML outputs are already sanitizing the content. Most of the implementations are using our `Markdown` component for displaying the HTML content (which does it out of the box).
- One rare instance is on the FeedCard, where we manually sanitize it to strip all the tags (recent implementation).
- With that in mind, I have come to realize that we don't need the `content` property on the `feed` anymore since we rely on the `contentHtml` property for feed display. I have also verified that it is not used elsewhere in the feed. This reduces the response size for the feed.
@idoshamun - tagged for visibility.
- Screenshots if …
=> fix: unnecessary content query

packages/shared/src/components/MainFeedLayout.tsx, packages/shared/src/components/alert/AlertPointer.tsx, packages/shared/src/components/filters/MyFeedHeading.tsx, packages/shared/src/components/post/freeform/write/WriteFreeformContent.tsx
- After further investigation, the root cause was the inconsistency of being centered on the component being used.
- Preview of the fix based on the current implementations:
Note: in companion, everything works as intended without any change which shows the fix actually did resolve the root cause.
WT-1408 #done
=> fix: my feed alert pointer

packages/webapp/pages/squads/[handle]/[token].tsx
- Mostly just spacing changes based on [the Sketch](https://www.sketch.com/s/2867ec63-0966-4647-b1d7-b6fe696ba251/a/lRK9Akd#Inspect)
Feel free to test it out here: https://daily-webapp-p18tuwyst-dailydotdev.vercel.app/squads/dailydev2/dDJYWNPj2hSj8Y5kT0Kto_9O2SKa3pG8d8rLbwNmFog
Previews:
WT-1398 #done
=> refactor: spacing on squad invitation page

packages/shared/src/components/Logo.tsx, packages/webapp/pages/join.tsx
On the lego referral join page there was content overlapping with teh logo and image of the person that sent the invite.
Below is how it now looks for mobile and desktop
WT-1453 #done
=> feat: fixing layout overlap on mobile join for lego referral

packages/shared/src/components/post/freeform/write/WriteFreeformContent.tsx, packages/shared/src/graphql/posts.ts, packages/shared/src/hooks/input/useMarkdownInput.ts
- message is now `File size exceeds the limit of 5 MB`
- updated props to use const export
WT-1426 #done
=> feat: error message now reflects file size limit

.gitpod.yml
- Temporary fix to support GitPod on Lerna 6
=> fix: stable set lerna version to 6

packages/shared/src/components/post/PostContent.tsx, packages/shared/src/components/post/SharePostContent.tsx, packages/webapp/pages/posts/[id]/index.tsx
- Added a option to go back to a squad on a article if the origin of flow was squad's
- Used query params as it should only flow if user moves via this flow
- Design is slightly adjusted to make things easier for now (will refactor in later stage, see discussion [here](https://dailydotdev.slack.com/archives/C051TNXSXR8/p1686750909746819))
WT-1395 #done
=> fix: add option to go back to squad from article

packages/shared/src/components/modals/post/CreateSharedPostModal.tsx
- Fix the missing toggle after migrating the sharing of post to a new modal.
=> fix: missing notification toggle on sharing post

packages/shared/package.json, pnpm-lock.yaml
- we had a jest version mismatch in `shared`
- It was leading to issues in different dev environments where jest configs were not right since versions of jest from 27+ have different defaults https://jestjs.io/blog/2021/05/25/jest-27 
=> feat: shared jest package versions now matches other packages

.circleci/config.yml, package.json, packages/shared/src/components/modals/comment/NewCommentModal.spec.tsx, pnpm-lock.yaml
- Make cache dependant on pnpm lock file
=> fix: create cache key for pnpm lock file

packages/shared/src/components/post/write/WriteLinkPreview.tsx
- The condition should only proceed when the Source is available then there will be two states, minimized and the normal one. The parenthesis should ensure the source availability first.
Also tested locally and works now.
=> fix: nullable source on preview

packages/shared/src/hooks/usePostMenuActions.ts, packages/shared/src/hooks/useUpdatePost.ts
- when clicking downvote from modal option menu mutation handlers were missing and state would go out of sync with upvote/downvote buttons in the post modal actions
=> fix: downvote option modal state

packages/shared/src/components/squads/SquadsToShare.tsx, packages/shared/src/components/widgets/SocialShareIcon.tsx
Setting logic to hide the create squad button in the SquadsToShare component so nothing renders related to squads if the user doesn't have squads access
WT-1477 #done
=> feat: hiding create new squad for anon users

packages/shared/src/components/widgets/SimilarPosts.tsx
Removing the bg-color set on the similar posts widget so it matches the rest of the widgets in the sidebar
WT-1461 #done
=> feat: removing the bg color from the similar posts sidebar widget

packages/shared/src/components/widgets/PostToc.tsx
Removed the bg color on the table of contents widget to bring it inline with the other widgets
WT-1476 #done
=> feat: removing the bg color to the table of contents widget

packages/extension/src/companion/CompanionContextMenu.tsx, packages/extension/src/companion/useCompanionActions.ts, packages/shared/src/components/Feed.spec.tsx, packages/shared/src/components/PostOptionsMenu.tsx, packages/shared/src/components/fields/Radio.tsx, packages/shared/src/components/fields/RadioItem.tsx, packages/shared/src/components/modals/ReportPostModal.tsx, packages/shared/src/graphql/posts.ts, packages/shared/src/hooks/useReportPost.ts
- Add another option to `ReportPostModal`
- Extend `RadioItem` to support `afterElement` (needed to render tags selection below radio)
- Update report post mutation to support tags as per https://github.com/dailydotdev/daily-api/pull/1319
WT-1446 #done
=> feat: added irrelevant tags option to report post modal

packages/shared/src/components/cards/ArticlePostCard.spec.tsx, packages/shared/src/components/cards/ArticlePostCard.tsx, packages/shared/src/components/cards/PostList.tsx, packages/shared/src/components/notifications/Toast.tsx, packages/shared/src/components/post/block/PostTagsPanel.tsx, packages/shared/src/hooks/post/useBlockPost.ts, packages/shared/src/hooks/usePostMenuActions.ts, packages/shared/src/hooks/useToastNotification.ts
- With the introduction of a reusable panel and actions for downvoting a post, implementation on cards became easy as expected.
- After downvoting, the panel to allow blocking or reporting of post should be displayed. 
Preview:
Currently deployed at preview2:
https://preview2.app.daily.dev/
WT-1442 #done
=> feat: block panel on article post cards

packages/shared/src/components/PostOptionsMenu.tsx, packages/shared/src/hooks/post/useBlockPost.ts, packages/shared/src/hooks/useFeedSettings.ts, packages/shared/src/hooks/useTagAndSource.ts
So the issue with article modal auto closing was only happening on "My feed" when blocking tag or source from the modal. All other actions like hide and report do not close modal (which is good ✅ ).
This PR does below changes to enable selective invalidation of feed queries when blocking tags/sources:
- move logic to invalidate feed queries on tags/settings change to `useTagAndSource` hook
- this proved to be smallest footprint change which fixes the underlying issue
- remove `useFeedSettings` useEffect that was triggering too often (and unused options/state related to it)
- invalidation is called from actions inside `useTagAndSource` directly
- add `shouldInvalidateQueries` to `useTagAndSource` since that hook is responsible for actual actions execution
- disable feed queries …
=> fix: avoid modal close on tags/source block

packages/shared/src/components/filters/UnblockCopy.tsx
- We had a small light mode color issue when using `text-white` it should be `text-theme-label-primary` in this case (white as well)
- I checked code base other implementation of `text-white` where good as they always on purple backgrounds
WT-1504 #done
=> fix: light mode white color issue

packages/shared/src/components/post/PostActions.tsx
- Just noticed an edge case where after downvoting and then clicking upvote the downvote is reversed but the post block panel is not hidden.
- Since panel is hidden if you undo downvote I think it should be hidden on upvote as well (since it undo's downvote under the hood)
=> feat: close block panel on upvote

packages/webapp/next.config.js, packages/webapp/package.json, pnpm-lock.yaml
- Since we are manually switching preact we don't need this plugin.
- Should make local environment faster
- Note: When enabling preact debug it get's slower again
=> Without next plugin preact

packages/shared/src/components/fields/MarkdownInput/index.tsx, packages/shared/tailwind.config.js
Currently there isn't a max-height for the MarkdownInput so it would break out of the modal container, so a max height has been added to the textarea
=> feat: setting a max height for the MarkdownInput

packages/shared/src/components/ProfileMenu.tsx
This one was still showing (even though we turned off the campaign) since it was not looking `isReady` param from hook.
=> feat: lego referral option is hidden from profile menu while off

packages/shared/src/components/widgets/SimilarPosts.tsx
The Similar Posts component had a different border color to the other components on the post sidebar so I updated it to match the others. Below is the screenshots for before and after.
WT-1507 #done
=> feat: Fixing the border color for Similar posts

package.json, packages/webapp/next.config.js, packages/webapp/package.json, patches/next-plugin-preact@3.0.7.patch, pnpm-lock.yaml
- looks like preact still needs some "magic" to work with next hot reload
- tried just adding https://github.com/preactjs/prefresh but it does not work with webpack integration
- reintroduced `next-plugin-preact` and patched it to not enable `preact/debug` because that was the core issue of why our webapp was slow in development
- long term we should really evaluate preact and how it integrates with Next 13 and above since it will probably block us down the road
| Change/New | event name  | extra: { …
=> fix: hot reload

packages/shared/src/components/PostOptionsMenu.tsx
- Currently edit post option would show and break the app if you are anonymous
WT-1511 #done
=> fix: only show edit post for logged users

packages/shared/src/components/fields/MarkdownInput/index.tsx
- In the initial implementation, we had `shouldMountInactive={false}` so that it won't send a mutation request for the preview on each type since the parameter of the query changes by not rendering the other tab when it is not opened.
- So when you click the submit button when the preview tab is opened, we tried to fetch the data from the Form for which the textarea is not rendered anymore due to the above condition.
- To fix it, we now render both ends anytime, but we will enable the query only when the `Preview` tab is active, and in that case, we have to track it through the state. Tested it locally, and works as normal now.
Don't forget to update the …
=> fix: submitting comment from preview tab

packages/shared/src/contexts/NotificationsContext.tsx, packages/webapp/pages/popup/notifications/enable.tsx
- Fix for tracking sources when it's an existing granted flow
- Also added a new optional event name to identify internally if these hit often
=> fix: notification tracking for existing grants

packages/shared/src/components/MainLayout.tsx
Instead of delaying all the pages, this fix delay only the feed pages. The rest are not applicable for onboarding.
This fixes the preview issue when sharing links. I also validated that the onboarding wall still works.
=> fix: delay loading of pages which applicable for onboarding

packages/extension/src/companion/useCompanionSettings.ts, packages/extension/src/companion/useExtensionPermission.ts
- Prevent the companion permission request, but push regardless
=> fix: companion permission grant

packages/extension/src/companion/useCompanionSettings.ts, packages/shared/src/components/fields/MarkdownInput/CommentMarkdownInput.tsx, packages/shared/src/components/fields/MarkdownInput/index.tsx
- One of the few things we adopted recently is to disable the submit button when the submission succeeded.
- I am unable to reproduce the case, so I instead apply our common code principle on forms.
=> fix: duplicate comments by keeping submit disabled

packages/shared/src/components/MainLayout.tsx
- Keep query params when redirecting for onboarding.
- Tested and tried to include the parameters. Also checked on extension and verified to be working.
=> fix: missing query params on redirect

packages/shared/src/components/tooltips/notifications/NotificationPreferenceMenu.tsx, packages/webapp/pages/notifications.tsx
- After the refactor, I mistakenly included the state inside the component when should be passed from top to down.
WT-1571 #done
=> fix: usage of state on context menu

packages/shared/src/hooks/useJoinSquad.ts
In `SquadJoinButton` we pass `joinSquad` to `showLogin`, but since in that function reference user is still for anonymous it actually clears the cache for `[squad, anonymous, handle]` and the new key (because user is logged) is `[squad, user.id, handle]`. Which then shows stale page like user is not part of squad. If you refresh the page he is of course. 
In this PR I clear all squad cache by `RequestKey.Squad` to make sure caches are cleared and user see proper join state after login.
Downside is that all the squad source query data (not the feed) will be invalidated in react query but since we do refetch that data on each visit to squad page it does not make any difference performance wise.
Alternative would be to provide [predicate function to …
=> fix: squad page cache after login

packages/shared/src/components/comments/CommentActionButtons.tsx, packages/shared/src/lib/auth.ts
Adding a check for report comment to see if you are logged in. If not you are presented with the login modal
WT-1568 #done
=> feat: adding login check for report comment

packages/shared/src/components/post/SquadPostAuthor.tsx
- Fix the missing links for SimilarPost section when it is a Squad post.
WT-1575 #done
=> fix: link on similar posts

packages/shared/src/lib/image.ts
- With the introduction of public posts there is a change images are empty for posts.
- I added a fallback to the fallback image, as it technically would never error state
=> hotfix: empty image fallback on profile

packages/shared/src/components/feeds/FeedContainer.tsx, packages/shared/src/components/squads/SquadJoinButton.tsx, packages/shared/src/components/squads/SquadMemberShortList.tsx, packages/webapp/pages/squads/index.tsx
- With the recent feed wrapper changes we accidental added padding twice
- I added a strict limit on the squad member card to render 3 on mobile and 5 max on desktop
- - Not sure it had impact on other places, but this fix should work reliable.
WT-1577 #done
=> fix: squad issues

packages/webapp/pages/squads/[handle]/index.tsx, packages/webapp/pages/squads/index.tsx
- Removed the custom padding of `0` on laptop size.
- Not sure if there was any reasoning behind this, if anyone has, please let us know.
Previews:
_Before the fix_
_After the fix_
WT-1584 #done
=> fix: squads and feed page padding

packages/shared/src/components/modals/Prompt.tsx, packages/shared/src/components/modals/common/Modal.tsx, packages/shared/src/components/notifications/InAppNotification.tsx, packages/shared/src/components/sidebar/common.tsx, packages/shared/tailwind.config.js, packages/webapp/pages/devcard.tsx, packages/webapp/pages/onboarding.tsx
- Introduced a z-index for the sidebar. The sidebar is meant to be on top of everything to allow user to navigate wherever they are.
- Issue was they were at z-index 3.
WT-1579 #done
=> fix: sidebar z-index

packages/shared/src/components/squads/SquadJoinButton.tsx, packages/shared/src/graphql/squads.ts, packages/shared/src/hooks/useJoinSquad.ts
- we had an edge case where sometimes after user joining or leaving squad the next Source API request would return stale data with `currentMember` as if user was still part of the squad.
Following flow would fail:
- join squad
- join mutation passes
- we invalidate source data locally (react query)
- source query fires API request for Source to refetch
- API request returns the stale data (like user is not a member)
I checked that order of requests on the frontend is valid and that join mutation request finishes before the Source request is made. So I don't think it is a frontend race condition.
This PR fixes the above where we actually reuse the response from join squad mutation. As bonus we make one less network request which is even better.
This fixes the issue but we are still not …
=> fix: stale squad response after join/leave

packages/shared/src/components/checklist/SquadFirstCommentChecklistStep.tsx, packages/shared/src/lib/image.ts
- We needed to update the say hi default comment
- As we don't have all the data on currentMember I decided to locally use the authContext
WT-1581 #done
=> fix: updated say hi comment default

packages/shared/src/components/sources/SourceCard.tsx
- Link image, name and handle to squad from `SourceCard`
WT-1594 #done
=> feat: make squad image and name/handle clickable

packages/shared/src/components/cards/WelcomePostCard.tsx
- As freeform and welcome both render as welcome post cards, we needed to ensure only welcome actually pulses on animation open
WT-1585 #done
=> fix: ensure pulse only on welcome post type

packages/shared/src/components/comments/MainComment.tsx, packages/shared/src/components/post/PostComments.tsx, packages/shared/src/components/post/PostEngagements.tsx, packages/shared/src/components/squads/SquadCommentJoinBanner.tsx
=> feat: dynamically show notification and join banners

packages/shared/src/components/RankProgressWrapper.tsx, packages/shared/src/components/SidebarRankProgress.spec.tsx
- do not show devcard popup when on squad pages
WT-1595 #done
=> feat: do not show devcard popup when on squad pages

packages/shared/src/hooks/useActions.ts, packages/shared/src/hooks/useJoinSquad.ts, packages/webapp/pages/squads/[handle]/edit.tsx
- There can be a difference between the invalidation of cache for us to fetch the user's completed actions over the background worker's finishing time.
- We instead push the finished action than relying on the API as we already expect this to happen.
WT-1583 #done
=> fix: checklist after joining squad

packages/shared/src/components/sources/SourceCard.spec.tsx, packages/shared/src/hooks/useActions.ts, packages/shared/src/hooks/useJoinSquad.ts, packages/webapp/__tests__/SquadTokenPage.tsx
- UserActions are immutable, we don't delete any data on this entity in any scenario, but since there can be some latency issues with background workers updating the finished actions, we need to keep the manually stored cache to avoid discrepancies with some checklists.
- We have two options, either merge it or disable the `refetchOnMount`. The latter is a good option too, though we will have to manually add to FE cache every actions that are registered in an async manner in the BE.
Log the new/changed events …
=> refactor: merging of finished actions

packages/shared/src/components/modals/squads/SquadNotificationsModal.tsx
- Squad settings toggles should work opposite ways
WT-1607 #done
=> fix: revert squad option toggle

packages/shared/src/graphql/sources.ts, packages/webapp/pages/squads/index.tsx
- do not show last card if squads data is not fetched
- added squads fetch in SSR (1 hour cache)
- updated types for the page
=> feat: squad page loading

packages/shared/src/components/squads/SquadPostListItem.tsx, packages/shared/src/graphql/fragments.ts, packages/shared/src/graphql/posts.ts
- Currently we showed the current member role for each similar post, this should be based on the role the author of set posts has
- Added the privileged member query to base info as we use it in multiple places to resolve roles
WT-1609 #done
=> fix: show correct member role for user

packages/shared/src/components/Feed.tsx, packages/shared/src/components/feeds/FeedContainer.tsx
- Did a refactor to move out certain const to keep the render function lean.
- Introduced a property on the container to place certain elements after the feed's grid. Everything about the fix should only be in this commit https://github.com/dailydotdev/apps/commit/b49ba3ca13da4c2eba4626f98e3063ef00d3ddb5
Preview:
WT-1612 #done
=> fix: onboarding scroll block placement

packages/shared/src/components/cards/ReadArticleButton.tsx, packages/shared/src/components/post/PostContent.tsx, packages/shared/src/components/post/SharePostContent.tsx
I have made titles link on the article page/modal as well as when you share a post to a squad the Read post button now links to the external article correctly
WT-1576 #done
=> feat: making title and read more buttons link to the correct place

packages/shared/src/components/auth/AuthDefault.tsx, packages/shared/src/components/auth/ProviderButton.tsx, packages/shared/src/components/auth/common.tsx
Adding a border so the google button is more visible on light mode. Screenshots added below
WT-1560 #done
=> feat: adding border to google buttons on light mode

packages/shared/src/components/PostsSearch.tsx, packages/shared/src/components/auth/AuthOptions.tsx, packages/shared/src/components/fields/MarkdownInput/index.tsx, packages/shared/src/components/fields/SearchField.tsx, packages/shared/src/components/history/ReadingHistoryEmptyScreen.tsx, packages/shared/src/components/tabs/TabContainer.spec.tsx, packages/shared/src/components/tabs/TabContainer.tsx, packages/shared/src/lib/query.ts, packages/webapp/__tests__/HistoryPage.spec.tsx, packages/webapp/components/RouterPostsSearch.tsx, packages/webapp/components/history/common.ts, packages/webapp/components/history/index.ts, packages/webapp/components/history/reading.tsx, packages/webapp/components/history/search.tsx, packages/webapp/pages/history.tsx
- Major change from the history page is to have the tabs option.
- Applied a useEffect to work with redirection if the primary opened tab should be the search history.
- Refactored the SearchField to apply the correct height (not sure why it suddenly shrinks in after the refactor but fixed now - preview are available for existing implementations).
- Since the history is not just a full page anymore, I have also updated the placeholder component.
Preview:
The search tab is pretty empty as we don't have yet the components and page to redirect to.
https://github.com/dailydotdev/apps/assets/13744167/cf2182d7-836a-4007-89b1-466c7bb98d7b
Existing implementations of the updated SearchField
Did you introduce any …
=> refactor: history page to be tabbed

packages/shared/src/components/squads/SquadsDirectoryHeader.tsx
The squad directory header icon currently has an icon but the beta text is also in the icon so we needed to offset the icon so that the icon itself is centered and not icon with beta text.
WT-1588 #done
[WT-1588]: https://dailydotdev.atlassian.net/browse/WT-1588?atlOrigin=eyJpIjoiNWRkNTljNzYxNjVmNDY3MDlhMDU5Y2ZhYzA5YTRkZjUiLCJwIjoiZ2l0aHViLWNvbS1KU1cifQ
=> feat: making the beta tag offset for the squad directory header

packages/shared/src/components/post/SquadPostAuthor.tsx, packages/shared/src/components/squads/SquadPostListItem.tsx
The role was showing in the similar posts for squads, but it was removed in this location only to reduce the information in this widget
WT-1618 #done
=> feat: adding option to hide role in SquadPostAuthor

packages/webapp/pages/squads/[handle]/[token].tsx
- We had a small overflow text issue on the squad token page.
Before:
After:
Also tested mobile version :)
WT-1629 #done
=> fix: overflow issue for squad invite page

packages/shared/src/graphql/squads.ts, packages/webapp/next-seo.ts, packages/webapp/pages/squads/[handle]/[token].tsx, packages/webapp/pages/squads/[handle]/index.tsx
Page is not `getServerSideProps` page. Caching is the same as `getStaticProps` only through cache header. This was needed to take into account query params `userid` and `cid` when squad page is shared as invitation. 
regular:
invite:
=> feat: add ssr seo to squad page

packages/shared/src/components/MainLayout.tsx
- Prevent double slash for onboarding
- Checked other url's seem fine
- Also tested the flow to see the useEffect wouldn't trigger twice, seems solid
WT-1631 #done
=> fix: prevent double slash for onboarding

packages/shared/src/components/feeds/FeedContainer.tsx, packages/shared/src/components/search/SearchBar.spec.tsx, packages/shared/src/components/search/SearchBar.tsx, packages/shared/src/components/search/SearchBarInput.tsx, packages/webapp/__tests__/SearchPage.tsx, packages/webapp/pages/search/index.tsx
Note: The component in itself was written amazingly, **this is purely a refactor** to break down the components and to ease the review down the line.
- To revamp the Feed Header, there are certain differences between the placements of the elements from the Search page but using the same `SearchInputBar`.
- Broke down the component to allow other implementations to have freedom of what to include.
- @TomDowling would love to hear your thoughts and if I missed anything as you are very familiar with the component 🙏  …
=> refactor: search input as a standalone component

packages/shared/src/components/onboarding/FilterOnboarding.tsx, packages/webapp/pages/onboarding.tsx
Currently after onboarding the flicker happens as the homepage loads before the user my-feed is ready. after a few seconds it is created and the page re-renders taking the user from popular to my-feed. This fix leaves the flow the same if you haven't selected any topics in the onboarding but wait for your feed if you have selected some
WT-1546 #done
=> feat: waiting to redirect from onboarding till feed is ready

packages/shared/src/components/post/PostItemCard.tsx
The classes were not being applied to the container if the item wasn't clickable. I added it to the article as conditional to fix this situation
WT-1660 #done
=> fix: broken layout when PostItemCard isn't clickable

packages/shared/src/components/notifications/Toast.tsx, packages/shared/src/hooks/useTimedAnimation.ts, packages/shared/tailwind.config.js
This stops the toasts timer resetting when scrolling or changing page. However, it does seem to have a performance issue as you scroll it almost freezes the timer as you scroll then continues. I have tried adapting the setInterval, using a useEffect and setTimeout instead all none of them improve this. If anyone has an ideas please do say otherwise agreed with Chris this was okay to progress as is
| Change/New | …
=> feat: checking if toast isAnimating before starting again

packages/shared/src/components/sources/SourceCard.tsx
- with the recent tailwind upgrade order of classes needs important, else the lowest one will be set
Before:
After:
=> hotfix: card padding squad directory

packages/shared/src/components/markdown.module.css
- Extension injects a `font-size: 75%` on chrome
- In order to obtain stability we need to set our default typos on markdown content
=> fix: hard set extension font size for markdown posts

packages/shared/src/components/post/write/SquadsDropdown.tsx
- Ensure new post page only shows active squads and squads you can actually post in
=> fix: squad post options verification

packages/webapp/pages/squads/[handle]/[token].tsx
- Move to stable CSS evaluation
- Was a minor issue where the initial load could not evaluate
Testing:
https://daily-webapp-c0knnvhg8-dailydotdev.vercel.app/squads/squadbuilders/CraBOge9V1SbrsqdwDYI6HlvhxemhutcndtKDq-YOwk
=> fix: squad invite page

packages/shared/src/components/squads/SquadsDirectoryHeader.tsx
- Squad description text was not rendering neat on mobile.
New mobile:
New tablet + sizes:
WT-1633 #done
=> fix: squad description text

packages/shared/src/components/search/SearchBarSuggestion.tsx, packages/shared/src/components/search/SearchBarSuggestionList.tsx, packages/shared/src/components/sidebar/Sidebar.spec.tsx, packages/shared/src/components/tabs/TabContainer.tsx, packages/shared/src/graphql/search.ts, packages/shared/src/lib/query.ts, packages/webapp/__tests__/HistoryPage.spec.tsx, packages/webapp/components/history/SearchEmpty.tsx, packages/webapp/components/history/SearchSkeleton.tsx, packages/webapp/components/history/common.ts, packages/webapp/components/history/index.ts, packages/webapp/components/history/search.tsx, packages/webapp/pages/history.tsx
**Note:** Don't update the branch yet.
- Fixed a bug in the tabbed container for using a controlled state.
- Search history loading state.
- Search history empty state.
- Rendering Search history list (infinite scroll).
WT-1645 #done
=> feat: search history page

packages/shared/src/components/post/FixedPostNavigation.tsx
- Issue aired with latest tailwind upgrade
- Basically the w-full before would get overwritten *(which is correct)
- Meaning we didn't even need it 😅
Before:
After:
WT-1687 #done
=> fix: modal header

packages/shared/src/components/search/SearchResult.tsx, packages/shared/src/graphql/search.ts, packages/shared/src/hooks/useChat.ts, packages/webapp/components/search/SearchV1Page.tsx
- Mutation to send search feedback.
- Pass down query key to easily update the chunk data.
- In progress state to identify whether to disable the feedback buttons.
WT-1685 #done
=> fix: sending search feedback

packages/shared/src/components/modals/SharePostModal.tsx, packages/shared/src/components/modals/common/Modal.tsx, packages/shared/src/components/post/FixedPostNavigation.tsx
- Yesterday I introduced a different approach of unsetting the width.
- But decided to go the safer route which we proposed before on certain widths, to simply add important notices to always have the right order where applicable.
=> fix: modal overwrite values

packages/shared/src/components/tabs/TabContainer.tsx, packages/webapp/pages/history.tsx
- It won't be possible to have the border from the inside out to the main layout.
- Feels like a hack though to stamp a div on top of everything.
- If you have any suggestions, feel free to shoot.
Previews:
WT-1696 #done
=> fix: border bottom on history page

packages/shared/src/components/search/SearchBarInput.tsx, packages/shared/src/components/search/SearchProgressBar.module.css, packages/shared/src/components/search/SearchProgressBar.tsx, packages/shared/src/graphql/search.ts, packages/shared/src/hooks/useChat.ts, packages/shared/src/lib/dateFormat.ts
- Introduce keyframes for the search progress bar.
- Whenever the status gets updated, we increment.
- When the `completedAt` has value, the progress should equal to the number of steps.
Preview:
https://github.com/dailydotdev/apps/assets/13744167/644737f5-0cd7-4af3-8dfa-1c1dc386617e
=> feat: search progress bar

packages/webapp/components/search/SearchV1Page.tsx
- Query parameters are always string.
- Due to the `toString` function, the undefined was turned into an actual string.
- This should prevent the re-trigger of prompt.
=> fix: query param undefined

packages/shared/src/components/search/SearchResult.tsx, packages/shared/src/styles/utilities.css
- Add feedback colors
WT-1711 #done
=> fix: add feedback colors

packages/shared/src/components/search/SearchHistoryButton.tsx
- Link to reading history with the search tab active
WT-1709 #done
=> fix: history popup link

packages/shared/src/components/search/SearchSourceList.tsx
- Remove source limit on mobile as we directly show all results
WT-1706 #done
=> fix: mobile source limit removal

packages/shared/src/components/search/SearchBarInput.tsx, packages/shared/src/components/search/SearchSourceList.tsx
- Made the input 100% height so the top/bottom padding are atleast sorted
- @capJavert You think that' sufficient enough? (For me the left/right are real edge-cases and have other buttons as well.
WT-1717 #done
=> fix: search input padding

packages/shared/src/hooks/usePostById.ts
Issue was that when commenting from modal we were trying to update single post cache. Since that one does not exist there was a runtime error in comment `onSuccess`. Comment would get posted but from UI it would look like it did not. User would then click comment again thus adding more then one comment.
We now skip cache update if there is not current single post cache.
This prevents cache update error when commenting from modal and also prevents filling partial post data to cache.
| Change/New | …
=> fix: do not set cache if post was not fetched

packages/shared/src/components/post/PostComments.tsx
As noted in https://github.com/dailydotdev/apps/pull/2101#issuecomment-1695410789 feed post cache is not updated correctly so numComments stays 0 even though user commented.
This created an edge case where if post had no comments it would always show "be first to comment" placeholder in modal since numComments would stay the same until post is refetched.
This fix evaluates postComments edges to get the real count which is updated since it is a separate cache item.
This is a temp fix until post feed cache is updated correctly for comments.
| Type   | event_name  | …
=> fix: evaluate edges length for comments count

packages/shared/src/components/RenderMarkdown.tsx
- remove language requirement when displaying code blocks
_no events changed_
WT-1738 #done
=> fix: properly display code even when the language is unknown

packages/shared/src/components/RenderMarkdown.tsx
_no events changes_
WT-1744 #done
=> fix: default to code when language missing

packages/shared/src/components/search/MobileSearch.tsx, packages/shared/src/components/search/SearchBarSuggestionList.tsx, packages/shared/src/components/tooltips/InteractivePopup.tsx
- Fix the wrapping of recommendation.
Preview:
WT-1708 #done
=> fix: mobile suggestion wrap

packages/shared/src/components/search/SearchSourceList.tsx
- `sources` can be undefined if query returns the error
- happend only on mobile because on desktop we use paginated which always wraps in array
- example where strict typechecking would caught this
- fixed with optional chaining but also notified Ido in original thread to check why the query `The best cam software is?` fails because it looks like it should return result
=> feat: search page crash mobile

packages/shared/src/components/TagLinks.tsx
- We had a small issue where the modal would be active.
- Basically we use prefetch false everywhere for these pages, it was just missing in this spot
WT-1681 #done
=> fix: tag navigation is breaking

packages/shared/src/components/markdown.module.css
- The overflow hidden is only applied to every `pre` child of the root element.
WT-1745 #done
=> fix: overlapping bg overspilling on borders

packages/shared/src/lib/textarea.ts
- The offset should be based on where the current line is at not the number of lines since it is only needed on lines after the first one.
This was reproducible locally and has been verified to work after the fix.
To reproduce, write multi-lined comments, for example:
```
Sample
Test
```
Then focus your cursor on the first line having it adjacent to the word `Sample`.
Should show the issue. After the code change, this doesn't happen anymore, and have verified commands on lines 2 onwards still work.
| …
=> fix: comment mention on multiple lines

packages/shared/src/components/search/SearchBar.tsx, packages/shared/src/components/search/SearchContainer.tsx
- While loading search results, don't display the error block
_no event changes_
WT-1749 #done
=> fix: generic error search fix

packages/extension/src/newtab/CustomLinks.tsx, packages/extension/src/newtab/MainFeedPage.tsx, packages/extension/src/newtab/ShortcutLinks.tsx
- Missing left margin on V1. The control should still be as it is.
WT-1751 #done
=> fix: alignment of extension buttons

packages/extension/src/newtab/App.tsx
- Cleanup unused prompt for analytics as we don't use 3rd party tracking anymore.
WT-1722 #done
=> refactor: unused prompt for analytics

packages/shared/src/hooks/chat/index.ts, packages/shared/src/hooks/chat/types.ts, packages/shared/src/hooks/chat/useChat.ts, packages/shared/src/hooks/chat/useChatSession.ts, packages/shared/src/hooks/chat/useChatStream.ts, packages/shared/src/hooks/index.ts, packages/shared/src/hooks/useChat.ts, packages/webapp/components/search/SearchV1Page.tsx
- Fixing issues related to search navigation and mixup of streaming and existing session results 
- More info here https://dailydotdev.slack.com/archives/C05EM7ZFQMQ/p1693402562918429
- split up useChat hook internally into two parts
- refactor query keys to avoid wildcard `new` and always load correct ID from `session_created` message.
- move all router logic to `SearchPage` since it is specific to that page
=> refactor: chat logic to support navigation and different sessions

packages/shared/src/components/search/SearchBarInput.tsx
- when we move to other search result we load its prompt to search input
- if we land on search input from history it loads the prompt for that search to search input
- if we query from feed page it loads the prompt to search input
=> feat: update input prompt for session when new chunk loads

packages/shared/src/components/search/SearchBarSuggestionList.tsx
- Usage of flex row over grid to fill the gaps.
- max-w doesn't support `1/2` or `1/3`.
WT-1754 #done
=> fix: recommendations alignment

packages/shared/src/graphql/search.ts
- Only append the q param if id is not existing
- Otherwise we always know what the ID is
WT-1756 #done
=> fix: only append q if id is not existing

packages/shared/src/components/search/SearchBarSuggestion.tsx, packages/shared/src/components/search/SearchBarSuggestionList.tsx
- I have no words to say, but, finally 😂 
Single line for recommendations as per requirement. We overflow the excess and hide it as necessary.
WT-1757 #done
=> fix: recommendation pills single line styling

packages/shared/src/components/feeds/FeedContainer.tsx
- The `flex-1` from the inside should have fixed the issue. But then the outside is setting the `flex-none` to disable it from the earlier versions.
- Also removed classes that exist from the inside already.
Don't forget to update the [Analytics Taxonomy sheet]
WT-1762 #done
=> fix: pushing button

packages/webapp/__tests__/SearchPage.tsx, packages/webapp/components/layouts/SearchLayout.tsx, packages/webapp/pages/search/index.tsx
- Introduce a layout to make search page work on both versions.
- Have verified locally to work on both ends.
WT-1763 #done
=> fix: control page layout

packages/shared/src/components/PostsSearch.tsx, packages/shared/src/components/fields/AutoCompleteMenu.tsx
- The motivation behind wrapping the component with `isOpen` was to avoid the unnecessary scroll that happens when it is always rendered.
- We reverted it back, but we now removed the hack of hiding it from the screen from doing a `top-full` that places it to the bottom-most part which results in scrollbar showing even when not needed.
WT-1773 #done
=> fix: top position hack

packages/shared/src/hooks/chat/useChatStream.ts
- initial error (like rate limit) did not show because I introduced the new query key based on current timestamp for each new query https://github.com/dailydotdev/apps/pull/2142#discussion_r1311516282
- this however made `useChatSession` to not know about it 🤦 
- in this PR I fallback to empty query key with `null` and clean it before each new query
- also makes less mess inside our react query devtools
=> fix: initial error not showing due to wrong queryKey

packages/shared/src/components/search/MobileSearch.tsx
- Contain the list with a scrollable element. This ensures the search input would be on top of the screen all the time.
WT-1774 #done
=> fix: mobile search scrolling list

packages/shared/src/components/onboarding/MemberAlready.tsx
- Missing items-center to horizontally center the elements.
- Unable to reproduce, hence, no screenshot. However to ensure it won't happen on any other layouts, we apply the CSS.
WT-1736 #done
=> fix: "already a member" element centered horizontally

packages/shared/src/components/auth/AuthForm.tsx
- Consuming the whole height opens up gaps in-between the elements.
Before the fix:
After the fix:
WT-1743 #done
=> fix: unnecessary spacing on registration form

packages/shared/src/components/search/SearchBarSuggestion.tsx, packages/shared/src/components/search/SearchBarSuggestionList.tsx, packages/shared/src/components/search/SearchHistory.tsx, packages/shared/src/graphql/search.ts
_No events changes_
WT-1779 #done
=> fix: ensure recommendation impression events are triggered on update

packages/shared/src/graphql/search.ts, packages/shared/src/hooks/chat/useChatStream.ts, packages/shared/src/lib/labels.ts
- Fixed an issue where `Unexpected error` doesn't stop the loading animation.
- After further investigation, the streaming stopped but technically the answer was produced completely in the BE. There are some issues that break the connection. We don't have yet a concrete identification of why it happens, so we instead sent a proper message over the generic one. [More info here.](https://dailydotdev.slack.com/archives/C01L0QXQJNB/p1693926299289879?thread_ts=1693830099.191299&cid=C01L0QXQJNB).
- Added the extra.code property to the analytics data.
| Type   | event_name …
=> refactor: streaming issue error code and message

packages/shared/src/components/search/MobileSearch.tsx, packages/shared/src/components/search/PlaceholderSearchSuggestion.tsx, packages/shared/src/components/search/SearchBarSuggestion.tsx, packages/shared/src/components/search/SearchBarSuggestionList.tsx, packages/shared/src/components/search/SearchHistory.tsx, packages/shared/src/components/search/SearchHistoryButton.tsx, packages/shared/src/graphql/search.ts, packages/shared/src/hooks/search/useSearchSuggestions.ts, packages/shared/src/lib/analytics.ts, packages/webapp/pages/history.tsx
To ensure the distinction between `SearchSession` and `SearchQuestion` objects is clear, we are renaming the `SearchSession.id` attribute to `SearcSession.sessionId` -- discussion started here: https://github.com/dailydotdev/apps/pull/2157#discussion_r1314869136
_no event changes_
=> refactor: rename `id` to `sessionId` on search history query results

packages/shared/src/graphql/search.ts
=> fix: correctly set the `sessionId` alias on search history query

packages/shared/src/components/cards/Card.module.css, packages/shared/src/components/cards/RaisedLabel.tsx
- We tried to convert existing animation to tailwind
- It kind of worked, but the z-index was not working, and unfortunately Tailwind won't allow for delayed animation on specific sub types, so had to revert back to CSS for complex animation timings.
See it work:
WT-1785 #done
=> fix: revert flag animation to css

packages/shared/src/components/auth/SignBackButton.tsx
- Not rendering `Continue as` block
- It will only render email 
- Fixes https://github.com/dailydotdev/daily/issues/977
=> fix: name can be undefined for social provider

packages/shared/src/components/markdown.module.css, packages/shared/src/components/modals/common/Modal.tsx, packages/shared/src/graphql/fragments.ts, packages/shared/src/graphql/posts.ts
- Couple of modal related fixes
- We recently set everything to antialiased, but forgot to expand to modal as it's outside the doc basically.
- We had a evaluation for `titleHtml` but it was missing from the basic post query (feed)
- Our markdown was missing pre space for paragraph enters
WT-1817 #done
=> fix: small modal related fixes

packages/shared/src/lib/query.ts, packages/webapp/pages/account/security.tsx
- After the recent change, connecting providers work, but doesn't reflect the status update until you refresh.
- Probably due to the disabledRefetch (removed it now since even just invalidating doesn't work).
- Invalidate query instead to ensure refetch.
=> fix: query invalidation of connected providers

packages/shared/src/components/modals/SubmitArticleModal.tsx
_self explanatory_
_N / A_
WT-1840 #done
=> fix: always pass a string to `className` prop

packages/shared/src/components/post/PostItemCard.tsx
- Prevent default on history close
- Similar as fix: https://github.com/dailydotdev/apps/pull/2186
WT-1842 #done
=> fix: prevent default on hide click

packages/shared/src/components/squads/Details.tsx
- fix: replace onChange with onBlur to set squad handle when focusing on next field
N/A
WT-1861 #done
=> fix: replace onChange with onBlur to set squad handle when focusing on next field

packages/shared/src/hooks/useTimedAnimation.ts
- leftover timer was causing set state when hook/component unmounts
- this makes sure timer is cleared when hook unmounts
WT-1851 #done
=> feat: clear interval when hook unmounts

packages/shared/src/components/profile/AccountDangerZone.tsx
- fix: invalid DOM nesting of `AccountDangerZone`
Replace `p` with `div`
N/A
=> fix: invalid DOM nesting of `AccountDangerZone`

packages/shared/src/components/PostOptionsReadingHistoryMenu.tsx
_self explanatory_
_N / A_
WT-1841 #done
=> fix: use the correct query key to update reading history cache

packages/shared/src/components/fields/MarkdownInput/index.tsx, packages/shared/src/components/post/NewComment.tsx
=> fix: don't nest button inside button

packages/shared/src/components/squads/SharePostBar.tsx
- sets the default value of the URL input to an empty string
**N / A**
WT-1846 #done
=> fix: make url input always controlled on share post bar

packages/shared/src/components/post/infinite/InfiniteReadingHistory.tsx
- duplicate key issue due to same post being read on different days
- added timestamp to make key unique
WT-1847 #done
=> fix: share post history duplicate key

packages/shared/src/components/Feed.spec.tsx
- fixes timeout errors on `waitFor`
N / A
WT-1834 #done
=> fix overlapping promises causing `act()` warnings

packages/shared/src/components/auth/AuthSignBack.tsx, packages/shared/src/components/auth/SignBackButton.tsx
- Fixes the Apple and GitHub icon to not be white on white background.
=> fix: GitHub and Apple icon to black on sign back in buttons

packages/shared/src/components/tooltips/Portal.tsx, packages/webapp/pages/notifications.tsx
- On the notifications page, we render the `Portal` as part of the whole UI, but then in the build time there is no context of the browser, hence, the `document` is not defined.
- This should prevent the build from failing.
WT-1778 #done
=> fix: build by checking whether portals would work

packages/shared/src/components/notifications/NotificationItem.tsx, packages/webapp/pages/notifications.tsx
- Avoid nested anchor tags.
- Create an overlay element to handle the event.
- Keep the user links to have the anchor tag.
=> refactor: nested anchor tags

packages/shared/src/components/notifications/NotificationItem.tsx, packages/shared/src/components/notifications/NotificationItemAvatar.tsx, packages/shared/src/components/profile/ProfileImageLink.tsx, packages/shared/src/graphql/notifications.ts
- The tooltip wasn't working anymore due to the overlay button.
- Title doesn't seem to be needed since we already have the aria-label.
=> fix: notification card z-index

packages/shared/src/components/layout/MainLayoutHeader.tsx
- I am really bothered by the lack of spacing between the elements (new post and notification bell).
I can't stand it anymore, I have to raise this PR. Preview after the fix:
=> fix: notification bell spacing

packages/shared/src/components/auth/RegistrationForm.tsx, packages/shared/src/components/auth/SocialRegistrationForm.tsx
- Change the onboarding gap for checkbox bottom (only registration and social registration)
=> fix: change onboarding checkbox gap

packages/shared/src/components/checklist/InviteMemberChecklistStep.tsx, packages/shared/src/components/squads/SquadHeaderBar.tsx, packages/shared/src/components/squads/SquadHeaderMenu.tsx, packages/webapp/__tests__/SquadFeedPage.tsx
- Reposition of the invite link and minor alignment issues
WT-1800 #done
=> fix: reposition copy link

packages/shared/src/components/cards/AdCard.tsx
- Allow ethical ads to show fully.
Before:
After:
WT-1864 #done
=> fix: allow ethical ads to render fully

packages/shared/src/components/auth/SocialRegistrationForm.tsx
- Missed the bottom margin on the social form
=> fix: missed one attribute for social

packages/webapp/pages/onboarding.tsx
- size of the topics filtering in onboarding
=> fix: size of filtering boxes

packages/extension/package.json, packages/shared/package.json, packages/shared/postcss.config.js, packages/webapp/package.json, packages/webapp/pages/onboarding.tsx, pnpm-lock.yaml
<table>
<tr>
<td><img src="https://github.com/dailydotdev/apps/assets/1681525/4278e793-b272-4b49-ba2f-0c5ea8487c03" />
<td><img src="https://github.com/dailydotdev/apps/assets/1681525/ec443932-c654-4192-b7e8-b7a11630237b" />
</table>
- Adds a postcss plugin to automagically supplement `100vh` with a `-webkit-fill-available`
- Fixes position of Next button during filtering
=> fix: set correct min/max height on iOS devices

packages/shared/src/lib/featureManagement.ts, packages/webapp/__tests__/MostDiscussedPage.tsx, packages/webapp/__tests__/MostUpvotedPage.tsx, packages/webapp/__tests__/MyFeedPage.tsx, packages/webapp/__tests__/PopularPage.tsx
- Set the default as 15 for feed version
=> fix: set default feed as 15

packages/extension/src/newtab/App.tsx, packages/extension/src/newtab/MainFeedPage.tsx, packages/shared/src/components/ExtensionOnboarding.tsx, packages/shared/src/components/MainLayout.tsx, packages/shared/src/components/Settings.tsx, packages/shared/src/components/onboarding/common.ts, packages/shared/src/components/tooltips/ChangelogTooltip.tsx, packages/shared/src/contexts/AuthContext.tsx, packages/shared/src/hooks/useCompanionTrigger.tsx, packages/shared/src/hooks/usePostModalNavigation.ts, packages/shared/src/lib/constants.ts, packages/webapp/pages/onboarding.tsx
- refactors onboarding title to a shared component
- creates onboarding component for extension
- prevents search bar hijacking on new tab
WT-1865 #done
=> fix: prevent search bar hijacking on new tab

packages/shared/src/components/post/write/CreatePostButton.tsx, packages/webapp/pages/squads/create.tsx
- when clicking the `New post` in the header while on a squad page, pre-select the squad when creating a new post.
WT-1803 #done
=> fix: pre-select squad on new post button

packages/shared/src/components/post/MarkdownPostContent.tsx
<table>
<tr>
<td><img src="https://github.com/dailydotdev/apps/assets/1681525/551c1fd9-0983-4d68-be41-35414c9c7027" />
<td><img src="https://github.com/dailydotdev/apps/assets/1681525/6d3b322c-3c00-4a63-b1da-9befe4130abc" />
</table>
- gives freeform post cover image a max height of 1000px
- when clicking the cover image it opens in a new tab
WT-1804 #done
=> fix: set max-height of freeform post cover to 1000px

packages/shared/src/components/modals/ShareModal.spec.tsx, packages/shared/src/components/modals/ShareModal.tsx, packages/shared/src/components/widgets/SocialShare.tsx
- Remove the Markdown input from the ShareModal.
- When clicking a Squad icon, we will then open the modal to share a post to Squad.
- Since the ShareModal was not used in the LazyModal enum, we won't have to make any changes with the LazyModal itself since only one instance is opened.
Preview:
https://github.com/dailydotdev/apps/assets/13744167/0b2bc640-3775-489b-8203-01e12181df82
WT-1794 #done
=> refactor: share modal ui to open separate form for squad

packages/shared/src/components/modals/ArticlePostModal.tsx, packages/shared/src/components/modals/BasePostModal.module.css, packages/shared/src/components/modals/BasePostModal.tsx, packages/shared/src/components/modals/SharePostModal.tsx, packages/shared/src/components/post/PostLoadingSkeleton.tsx, packages/shared/src/components/post/SquadPostContent.tsx
<table>
<tr>
<td>Before
<td>After
<tr>
<td><img src="https://github.com/dailydotdev/apps/assets/1681525/1b500a06-fc07-4d52-9805-68772e70a516">
<td><img src="https://github.com/dailydotdev/apps/assets/1681525/fc7d800d-2367-4394-818b-ffc1dc7a4be0">
</table>
- removes the background colour from the `post-content` class
WT-1867 #done
=> fix: remove background color on `post-content` class

packages/shared/src/components/GrowthBookProvider.tsx, packages/shared/src/contexts/BootProvider.tsx
- wait for boot to be completed before we set features
=> fix: wait for boot to be completed before we set features

packages/extension/src/newtab/MainFeedPage.tsx, packages/shared/src/components/MainFeedLayout.tsx, packages/shared/src/components/PostsSearch.tsx, packages/shared/src/components/feeds/FeedContainer.tsx, packages/shared/src/components/sidebar/DiscoverSection.tsx, packages/webapp/components/layouts/MainFeedPage.tsx, packages/webapp/components/search/SearchControlPage.tsx, packages/webapp/pages/posts/finder.tsx
- We have now a dedicated page for the old search which can be found at `/posts/finder`.
- As mentioned in Slack, we will now keep the item in the sidebar originally intended for search but the name will vary based on which version you are at.
- For extension users with AI search, we will redirect to the new page when the sidebar item is clicked.
- Since we still have the legacy Search, we will reuse the same component but refactor all the words from "Search" to "Post finder" as per Slack message.
- Have also tested on extension with legacy Search to not redirect and work as it currently is instead.
This is deployed in [preview2](https://preview2.app.daily.dev/posts/finder). …
=> feat: add post finder page as old search

packages/shared/src/components/cards/WelcomePostCardFooter.tsx
- We only want to allow text based HTML entities (*eg not images/headers/list etc)
- Decided to use a custom html parsing method to only allow text entities
WT-1879 #done
=> fix: allow string attributes

packages/shared/src/components/sources/SourceCard.spec.tsx, packages/shared/src/components/sources/SourceCard.tsx, packages/shared/src/styles/base.css, packages/shared/tailwind.config.js
- Re-align squad colors with theme colors for future options
=> fix: align squad colors with theme colors

packages/shared/src/contexts/BootProvider.tsx
- Disable refetch on mount for anonymous user as data could never change
- Add stale time of 30 seconds for boot
- We already manually invalidate on logging in/out 
- Idea is to reduce calls to boot that are unnecessary 
=> fix: optimize boot calls

packages/shared/src/components/cards/ArticlePostCard.tsx, packages/shared/src/components/cards/FeedbackCard.tsx
- fixes the card height change when feedback is shown
WT-1873 #done
=> fix: article card height on feedback

packages/shared/src/lib/config.ts, packages/webapp/next.config.js
- We had some legacy code that for the webapp routed traffic internally first
- We now remove this to directly call API and avoid re-routing latency (potentially, probably low impact)
WT-1886 #done
=> fix: convert webapp requests to api directly

packages/shared/src/hooks/useRegistration.ts
- JS Error object doesn't have a `toJSON` method so we need to manually serialize it first.
@idoshamun sample of what it would look like, does this align with your expectations?
```
[
{
"app_platform": "webapp",
"app_theme": "dark",
"feed_density": "eco",
"feed_layout": "cards",
"session_id": "npmXoijMzTzlIJDJfnUHL",
"user_first_visit": "2023-10-05T08:07:45.337Z",
"user_id": "lCLdgrrElIoTRLqmtDhNR",
"visit_id": "5JmZ3xm7ZiXa7TwTScUon",
"device_id": "46603749-9958-4796-a734-d1df79ac458c",
"screen_height": 1440,
"screen_width": 3440,
"page_referrer": "",
"window_height": 1240,
"window_width": 1039,
"page_state": "active",
"event_timestamp": "2023-10-05T09:12:46.343Z",
"event_id": "1696497166mkz6",
"event_page": "/onboarding",
"event_name": "registration initialization error",
"extra": …
```
=> fix: error serialization

packages/shared/src/components/MainLayout.tsx
- The bottom banner should only be applicable to feed pages
=> fix: feed bottom banner

packages/shared/src/components/cards/ArticlePostCard.tsx, packages/shared/src/components/cards/PlaceholderCard.tsx, packages/shared/src/components/cards/SharePostCard.tsx, packages/shared/src/components/cards/WelcomePostCard.tsx, packages/shared/tailwind.config.js
Forgot to adjust min-height on the other card types 😬 
- increases min-height on share post and freeform card
- set min-height on placeholder card
WT-1873 #done
=> fix: increase min height on share post, freeform and placeholder card

packages/shared/src/components/post/freeform/write/WriteFreeformContent.tsx, packages/shared/src/hooks/useInputFieldFunctions.ts
- Set the max length frontend wise for freeform title
- I noticed we didn't have it working when accessing the edit page, so decided to set validity once it's known.
Related API:
https://github.com/dailydotdev/daily-api/pull/1465
=> fix: set title length and validation

packages/shared/src/components/post/PostComments.tsx, packages/shared/src/hooks/useActions.ts, packages/shared/src/hooks/useFeedSettings.ts, packages/webapp/pages/squads/new.tsx
- We had some refetches happening on queries that we already manually set cache for or already refetch on timer.
Special request:
@capJavert and @omBratteng 
=> fix: optimize query loads

packages/shared/src/hooks/input/useDiscardPost.ts, packages/shared/src/hooks/input/useMarkdownInput.ts
- Fixed actual clearing of the freeform after posting
- Issue lied in only clearing the IDB value, not the react query cache so unsetting that manually to reset both ends
- Also noticed the content part was not setting, update issue
WT-1885 #done
=> fix: local clearing and initial set of content

packages/shared/src/hooks/input/useDiscardPost.ts
- Edge-case where you opened the create page without squad -> post in squad -> main key still set in IDB only
- This ensures we always clear the main key as well as the squad one
WT-1885 #done
=> fix: edge-case clean main key as well

packages/shared/src/components/post/freeform/write/WriteFreeformContent.tsx, packages/shared/src/hooks/input/useMarkdownInput.ts
- Optional chaining issue when editing freeform content
=> fix: needed optional chaining for shared post edit

packages/shared/src/components/Feed.tsx, packages/shared/src/hooks/useFeed.ts
- The request was to put ads not in the first place for squads.
- I added a extra criteria to only add a ad if there are at least 2 posts (so it doesn't show after welcome post)
- And added the option to add the ad preferably in 3th spot
I tried to make it as dynamic as possible, unfurtionally we don't really support great feed config per feed, something I think we should invest in down the line (talked about this before) 
For now this felt least intrusive and lean.
@idoshamun From your perspective would love to hear if it harms metrics that we perform the query for ads, but optionally don't render them? 
I thought about not querying at all, but it would delay the page
My feed: (unchanged)
Empty squad (only welcome)
Filled squad (after 3th position)
Did you introduce any new tracking …
=> fix: refactor ad placement for squads

packages/shared/src/components/post/write/CreatePostButton.tsx
- The New post button should be disabled when you have no access to post on any Squad.
My feed with Squads you can both post and not post
Squad feed with Squads you can both post and not post
Squad feed you can't post with Squads you can both post and not post
My feed with Squads only you can't post
WT-1811 #done
=> fix: disabled post button

packages/shared/src/components/squads/SharePostBar.tsx
- Fix the overlapping width classes.
- Fix the empty space when typing a link. Due to `tablet:flex-none` - in this case, we apply `!` on `flex-1` as it is conditionally being applied.
- Fix the spacing in-between the texts by adding a `.5` on the margin.
WT-1876 #done
=> fix: share post bar spacing

packages/shared/src/components/fields/MarkdownInput/index.tsx, packages/shared/src/lib/textarea.ts
- This fixes the issue when replying to someone and mention is included, focus will be at the end of the content.
- This also fixes the issue when you edit a comment, the focus would automatically be then at the end.
WT-1896 #done
=> fix: comment box input focus on the end

packages/shared/src/components/post/write/ShareLink.tsx, packages/shared/src/graphql/squads.ts, packages/shared/src/hooks/squads/usePostToSquad.ts
leftover item from the original PR for editing posts: https://github.com/dailydotdev/apps/pull/2259#discussion_r1360551010
API changes: https://github.com/dailydotdev/daily-api/pull/1487
n / a
WT-1801 #done
=> chore: don't pass `sourceId` on update post

packages/shared/src/components/auth/RegistrationForm.tsx, packages/shared/src/graphql/common.ts, packages/shared/src/graphql/users.ts, packages/shared/src/hooks/useProfileForm.ts, packages/webapp/pages/account/profile.tsx
- Make the APIs recent changes be the basis of the regex for handles and socials.
Note: since this regex won't allow the character dash `-`, it would affect the comment box as this is also the basis of the mentions triggers. Do we maybe want to allow it in the mention in the meantime?
WT-1897 #done
=> fix: regex handle uniformity

packages/shared/src/components/BookmarkFeedLayout.tsx, packages/shared/src/components/Feed.tsx, packages/shared/src/components/MainFeedLayout.tsx, packages/shared/src/components/MainLayout.tsx, packages/shared/src/components/PostOptionsMenu.tsx, packages/shared/src/components/layout/common.tsx, packages/shared/src/components/modals/SquadMemberModal.tsx, packages/shared/src/components/modals/UserListModal.tsx, packages/shared/src/components/squads/Members/BlockedMembersPlaceholder.tsx, packages/shared/src/components/squads/Members/index.ts, packages/shared/src/components/utilities/common.tsx, packages/shared/src/contexts/BootProvider.tsx, packages/shared/src/graphql/squads.ts, packages/shared/src/hooks/feed/useFeedName.ts, packages/shared/src/hooks/squads/useSquadActions.ts, packages/shared/src/hooks/usePostFeedback.ts, packages/shared/src/hooks/useTagAndSource.ts, packages/shared/src/lib/func.ts, packages/shared/src/lib/query.ts, packages/webapp/pages/sources/[source].tsx, packages/webapp/pages/squads/[handle]/index.tsx, packages/webapp/pages/tags/[tag].tsx
- In the Squad members modal, we should allow search.
- Fixed the generate query key function to not accept any kind of string but a rather more strict typing.
Preview:
WT-1815 #done
=> feat: search squad members

packages/shared/src/components/cards/PostSummary.tsx, packages/webapp/__tests__/PostPage.tsx
- Update TLDR limit to 330.
- Discussion [here](https://dailydotdev.slack.com/archives/C01473UNK9C/p1698149739497239?thread_ts=1698131764.163069&cid=C01473UNK9C).
=> fix: update TLDR treshold

packages/shared/src/components/referral/SearchReferralButton.tsx
- The right value should be typo-callout
=> fix: typo size on search referral button

packages/shared/src/components/search/SearchSourceList.tsx
- Prevent empty source render when done loading but sources still empty
=> fix: prevent empty source list render

packages/shared/src/contexts/BootProvider.tsx, packages/shared/src/hooks/referral/useReferralCampaign.ts, packages/shared/src/lib/query.ts
- Since this hook has multiple trigger points it would execute multiple times and query multiple times
- I added our default short stale time to ensure this doesn't happen on the same render basically
- Since it's not a super urgent visual interface this should be more then enough
=> fix: add stale time to avoid retriggers

packages/shared/src/components/feeds/FeedContainer.tsx, packages/shared/src/hooks/search/useSearchSuggestions.ts
- due to the usage of `useSearchSuggestions` in the main `FeedContainer`, this query was triggered regardless of wether the feature was enabled or not.
- adding a `disabled` argument which disables the query if `true`
N / A
WT-1786 #done
=> fix: disable search suggestions query when search is not enabled

packages/shared/src/components/notifications/NotificationItem.tsx, packages/shared/src/lib/element.ts
- added tabIndex={0} and role="link" in order to avoid disabling eslint for `jsx-a11y/no-static-element-interactions`
- added empty <span/> tag in order to avoid disabling eslint for `jsx-a11y/anchor-has-content`
- added onKeyDown event to make the link be clicked and work with Spacebar as well (as it was working as a button) in order to avoid disabling eslint for `jsx-a11y/click-events-have-key-events`
- Cleans up code from eslint-disbales
WT-1891 #done
=> fix: workaround to avoid eslint-disable

packages/shared/src/components/widgets/SocialShare.tsx
- the Copy Button displays a dark background when pressed and on blur.
- removing the "pressed" property resolves the issue.
=> :lipstick: fix copy icon bg color

packages/extension/tsconfig.jest.json, packages/extension/tsconfig.json, packages/shared/tsconfig.json, packages/webapp/tsconfig.jest.json, packages/webapp/tsconfig.json
- According to TS `es6` is a [good choice](https://www.typescriptlang.org/tsconfig#target) currently so let's pick this to have modern options, but not break to many things.
=> chore: bump target to es6

packages/shared/src/components/layout/MainLayoutHeader.tsx
- changes header position from fixed to sticky
- Fixes bug that makes the header buttons move when overflow changes.
- Changing header from fixed to sticky fixes the issue because in sticky position of header is defined from parent. 
Working solution video:
https://github.com/dailydotdev/apps/assets/36197304/e6ae9914-2de9-4211-b7c7-e2f9c98a5996
Video with issue present: 
https://github.com/dailydotdev/apps/assets/36197304/2bae2d1e-a192-432f-97d7-2ccd1652a349
WT-901 #done
=> fix: convert header position from fixed to sticky on laptop

packages/shared/src/components/MainLayout.tsx
- fix padding on main since header is now set to sticky
Before:
After
- remove padding on main
WT-901 #done
=> fix: remove padding on main, and adjust banner padding

packages/shared/src/components/tooltips/ChangelogTooltip.tsx
- remove max height from ChangelogTooltip component
- Fixes broken render of the ChangelogTooltip component that cuts off elements in the card if the text is long. 
Before:
After:
=> fix: remove max height from changelog popup

packages/shared/src/graphql/fragments.ts, packages/shared/src/graphql/posts.ts
- Mentioned by Nimrod he couldn't see views on his own post.
- After checking it turns out it doesn't show views inside a modal, but it does on the article page.
- This is due to different queries having/not having the data requested.
- I decided to uniform views in our post shared object so it will be always available
WT-1877 #done
=> fix: add views to shared object so it's uniform

packages/webapp/next.config.js
<table>
<tr>
<td>Before
<td>After
<tr>
<td><img src="https://github.com/dailydotdev/apps/assets/1681525/a112491b-e6b9-4c57-beab-dd1dd357e38d" />
<td><img src="https://github.com/dailydotdev/apps/assets/1681525/52d924a5-4131-486a-8ab9-b4f88ad27c3a" />
</table>
- Removes the extra `'` that is wrapping around the version parameter in webapp
This was only needed in extension when defining a plugin
=> fix: remove the `'` from version parameter

packages/shared/src/components/referral/SearchReferralButton.tsx
- Had to make the spacing for the search invite header 4px
=> fix: header spacing to 4px

packages/shared/src/components/widgets/SocialShare.tsx, packages/shared/src/components/widgets/SocialShareList.tsx
- Fix the title when sharing through email.
- The title for invite will utilize the same description we added.
- Fixed the email title to be passed from props. Hence, updated the implementation of sharing post.
=> fix: email title for sharing invite

packages/shared/src/components/modals/referral/GenericReferralModal.tsx, packages/shared/src/lib/analytics.ts, packages/webapp/components/invite/Referral.tsx, packages/webapp/pages/account/invite.tsx
~~Blocked: once the profile page changes is ready, I will update this PR for the relevant tracking events.~~
We will apply the proper analytics on the profile page widget on its own PR.
- Impression when the Generic Referral Popup is seen by the user.
- The copy link button has its built-in tracking and already added the required properties.
- Invite page
- Same copy referral event like the popup but with a different value for the target id
- On social share click, we send an event
- The Generic Referral Page should have an event of `download extension` instead of `accept invitation`.
Log the …
=> feat: generic referral campaign analytics
