packages/shared/src/hooks/input/useMarkdownInput.ts
- Initial content was again set when input was cleared because of the useEffect check
- added dirty flag to only do it once and allow user to clear the draft input
WT-1937 #done
=> fix: introduce dirty flag to prevent initial content after initial value

packages/shared/src/components/modals/referral/GenericReferralModal.tsx, packages/shared/src/components/referral/InviteLinkInput.tsx, packages/shared/src/components/widgets/ReferralWidget.tsx, packages/webapp/pages/account/invite.tsx
- Create a common component for copying link with input.
- The button should only copy link, nothing else, regardless of platform, OS, browser.
WT-1959 #done
=> fix: copy link buttons to just copy the link

packages/shared/src/components/tooltips/InteractivePopup.tsx
- Interactive popup should show the close button on mobile or when the user decides to always show it, similar to Squad Checklist.
WT-1958 #done
=> fix: missing close button on profile menu mobile

packages/extension/src/newtab/MainFeedPage.tsx, packages/shared/src/components/MainLayout.tsx, packages/shared/src/components/layout/MainLayoutHeader.tsx, packages/webapp/components/layouts/FeedLayout.tsx
- The new post should be stable in the header across the app.
WT-1954 #done
=> fix: new post button should show everywhere

packages/webapp/pages/account/invite.tsx
- From the discussion in Slack, we will adjust the spacing between the buttons.
Preview:
WT-1971 #done
=> fix: spacing between social share buttons

packages/webapp/components/invite/Referral.tsx
- Add a dot and a space in between the message.
Preview:
=> fix: referral join page copy

packages/shared/src/components/squads/SquadMemberShortList.tsx
- Nimrod requested we show the squad numbers with 1 fraction as we never imagined to go over these thousand numbers before.
Example:
=> fix: format k number with fraction

packages/shared/src/components/tooltips/InteractivePopup.tsx
- When the onClose property is null or undefined we should not show the close button as it would not do anything.
=> fix: should not show close button

packages/shared/src/components/tooltips/ChangelogTooltip.spec.tsx, packages/shared/src/components/tooltips/ChangelogTooltip.tsx, packages/shared/src/components/tooltips/InteractivePopup.tsx
- removed modal close an duse instead the close of interactive popup
- updated interactive popup close button to accept different button types
- removed all unused props fro changelog component
- Fixed spaces in update extension button
This PR fixes issues reported at: https://dailydotdev.slack.com/archives/C01L0QXQJNB/p1700121692463069
Video from extension:
https://github.com/dailydotdev/apps/assets/36197304/f9fd6d39-6991-49ce-a47d-e07b8086a7b7
=> fix: changelog button and close on update click

packages/shared/src/components/search/MobileSearch.tsx, packages/shared/src/components/tooltips/InteractivePopup.tsx
- Fix for the interactive popup to not show the wrapper if position is screen (meaning full size already)
WT-1955 #done
=> fix: mobile search evaluation for InteractivePopup

packages/shared/src/lib/rank.ts
- may be part of the issues causing some users to experience authentication issues - as per slack thread: https://dailydotdev.slack.com/archives/C01L0QXQJNB/p1700645470832879
N / A
=> fix: disallow non-existing rank indexes to be returned by `getRank`

.vscode/apps.code-workspace
Excludes searching from the dist or node_modules directories.
Always annoyed me when I tried to search for something, and VS Code would also show me lots of results from the compiled code from the `dist` directory for extension or `.next` for webapp.
This just sets the setting for the workspace to exclude searching in those directories.
=> fix(tools): exclude searching in dist and node_modules in the VS Code workspace

docker-compose.yml
- After verifying from GitPod's end, it seems the apostrophe is not needed.
=> fix: gitpod env variable

packages/shared/src/hooks/useFeedSettings.ts, packages/shared/src/hooks/useProfileTooltip.ts, packages/shared/src/lib/query.ts
We have a feature that when you hovers on a user profile image/name/handle, it would send a request to our server to fetch the user information. While doing so, every in and out of the cursor triggers the process, which means it would trigger the fetch again as well. By setting a stale time, we can avoid sending the request which data does not change very often. Users hardly update their user information once set, so setting a stale time of 30 minutes should be reasonable. Watch the network requests before and after on the section below: https://dailydotdev.atlassian.net/wiki/spaces/HAN/pages/691339518/Managing+GraphQL+loads#Profile-tooltip-sending-requests-on-every-hover …
=> fix: tooltip request overload

packages/shared/src/components/MainFeedLayout.tsx, packages/shared/src/components/onboarding/OnboardingHeader.tsx
- Old implementations where other way around, so decided to fix it as they showed wrong.
=> fix: media hooks evals

packages/shared/src/lib/kratos.ts
- covers more complex addresses such as alias email addresses
N / A
=> fix: encode the email passed in query params

packages/shared/src/components/video/YoutubeVideo.spec.tsx, packages/shared/src/components/video/YoutubeVideo.tsx, packages/storybook/stories/video.stories.tsx
- added new youtube video component that renders a div with iframe (the div is added to make sure about the aspect ratio mentioned in the DR)
-- the title is added and set as required as it helps with accessibility
- added storybook story about component
- added component test
Adds a component wrapper for the iframe youtube video content, that makes sure that the component is responsive in the 16:9 ratio
WT-1987 #done
=> feat: create video component wrapper

packages/shared/src/components/filters/BlockedFilter.tsx, packages/shared/src/components/filters/TagsFilter.tsx, packages/shared/src/components/markdown.module.css, packages/shared/src/components/modals/common/Modal.tsx, packages/shared/src/components/modals/referral/SearchReferralModal.tsx, packages/shared/src/components/multiLevelMenu/MultiLevelMenuMaster.tsx, packages/shared/src/components/post/FixedPostNavigation.tsx, packages/shared/src/components/post/freeform/write/WriteFreeformContent.tsx, packages/shared/src/components/squads/SquadEmptyScreen.tsx, packages/shared/src/components/utilities/common.tsx, packages/shared/src/styles/typography.ts, packages/shared/tailwind/typography.js, packages/webapp/components/invite/Referral.tsx, packages/webapp/components/layouts/AccountLayout/AccountContentSection.tsx, packages/webapp/pages/devcard.tsx, packages/webapp/pages/notifications.tsx, packages/webapp/pages/squads/[handle]/[token].tsx
- [Design](https://dailydotdev.slack.com/archives/C0381BQUEN9/p1701255543561259) removed the typo-headline in favor of using typo-body + font-bold
=> fix: replace headline with body + bold

packages/shared/src/lib/featureManagement.ts, packages/webapp/pages/onboarding.tsx
- AB test the onboarding's both title and subtitle.
- As discussed during the meeting, the feature value should be what is expected as opposed to the usual values of v1, v2, etc.
WT-2018 #done
=> feat: ab test onboarding title and subtitle

packages/shared/src/components/BookmarkFeedLayout.tsx, packages/shared/src/components/Feed.tsx, packages/shared/src/components/FeedItemComponent.tsx, packages/shared/src/components/PostOptionsMenu.tsx, packages/shared/src/components/fields/FilterCheckbox.tsx, packages/shared/src/components/filters/AdvancedSettings.spec.tsx, packages/shared/src/components/filters/AdvancedSettings.tsx, packages/shared/src/components/filters/ContentTypes.tsx, packages/shared/src/components/filters/ContentTypesFilter.tsx, packages/shared/src/components/filters/FeedFilters.tsx, packages/shared/src/components/filters/FilterMenu.tsx, packages/shared/src/contexts/AlertContext.tsx, packages/shared/src/graphql/feed.ts, packages/shared/src/graphql/feedSettings.ts, packages/shared/src/graphql/posts.ts, packages/shared/src/hooks/feed/index.ts, packages/shared/src/hooks/feed/useAdvancedSettings.ts, packages/shared/src/hooks/useFeedSettings.ts, packages/shared/src/hooks/useFindSquadWelcomePost.ts, packages/webapp/__tests__/BookmarksPage.tsx, packages/webapp/__tests__/SquadFeedPage.tsx, packages/webapp/pages/posts/[id]/index.tsx, packages/webapp/pages/squads/[handle]/index.tsx
- Introduced use advanced settings to manage users advanced settings.
- Refactor the Settings page for filters to use the said hook.
- Introduce a new tab for content_types.
- The selection contains just the video only, but once our advanced settings with `group` grows, this should trigger multiple mutations to update each item. Otherwise we must introduce a new mutation to update all at once.
Note: do we already have an intermediate branch to point this to?
| Change/New | event name  | extra: { ... } …
=> feat: video advanced settings

packages/shared/src/components/FeedItemComponent.tsx, packages/shared/src/components/cards/ArticlePostCard.tsx, packages/shared/src/components/cards/FeedbackCard.tsx, packages/shared/src/components/cards/common.tsx
- The reason there is no change with the UI is, that the `useVotePost` updates the local cache for specific post query, not the feed query.
- The upvote and downvote are inherently available from the cards so utilizing that instead as it follows the correct update of cache.
Deployed at https://preview3.app.daily.dev/
=> fix: feed card feedback actions

packages/shared/src/components/modals/SharedBookmarksModal.tsx, packages/shared/src/lib/rank.ts
- why the `rank` may be coming back as undefined is to be determined separately
N / A
WT-2036 #done
=> fix: make `getRank` resilient to undefined arguments being passed in

packages/shared/src/components/MainLayout.tsx
- We should respect the screenCentered variable that got removed initially.
Works on different screens now:
WT-2035 #done
=> fix: reintroduce the screenCentered variable

packages/shared/src/components/comments/MainComment.tsx, packages/shared/src/components/comments/SubComment.tsx, packages/shared/src/components/fields/MarkdownInput/CommentMarkdownInput.tsx, packages/shared/src/hooks/post/common.ts, packages/shared/src/hooks/post/useCommentEdit.ts
- The reason why the cache is not updating, we should now deep-clone the data we are trying to update. Else, if it is considered to be the same, no re-render is triggered.
- Another issue shows, that when editing the same comment for the second time in one session, the latest value is not displayed, so in order to always base from the query, we need to add another parameter to ensure the value and date match.
Seems like after the react-query upgrade we now need to deep clone objects.
| Change/New | …
=> fix: editing comments cache update

packages/shared/src/hooks/analytics/useAnalyticsQueue.ts
When sending analytics events from the companion, some of them were sent in the wrong format. This caused the api to ignore these events
=> fix: wrong analytics format in companion

packages/shared/src/components/cards/AdList.tsx, packages/shared/src/components/cards/Card.tsx, packages/shared/src/components/cards/PostList.tsx
- New list styling -> Removes the left source and places it on top.
Before:
After:
WT-2039 #done
=> fix: move list styling to new format

packages/shared/src/components/post/SharePostContent.tsx, packages/shared/src/components/post/common/SharedPostLink.tsx, packages/shared/src/lib/click.ts
- Introduced the [same component](https://github.com/dailydotdev/apps/blob/f8e5b0aea4564937115b9c41399782b4579657dc/packages/shared/src/components/post/common/SharedPostLink.tsx) found in the YT intermediate branch.
- Fix the missing analytics for go to link actions.
WT-2054 #done
=> fix: missing analytics for go to link action

packages/shared/src/components/image/LabeledImage.tsx
Fixes part of the bug in https://dailydotdev.atlassian.net/browse/WT-2053
The profile menu was showing the profile picture in the dropdown with square aspect ratio. This however mangled the profile picture unless the source picture was also in a square aspect ratio, which might not be the case.
Fixed by [adding `object-fit: cover` style](https://developer.mozilla.org/en-US/docs/Web/CSS/object-fit) to the `<img` element with [tailwind `object-cover` className](https://tailwindcss.com/docs/object-fit).
WT-2053 #done
=> fix: profile menu user image aspect ratio

packages/shared/src/components/image/LabeledImage.tsx, packages/webapp/components/layouts/ProfileLayout/index.tsx
- Remove effect/state in favor of memo.
WT-2056 #done
=> fix: leverage memo to avoid re-renders

packages/shared/src/components/Feed.spec.tsx, packages/shared/src/components/PostOptionsMenu.tsx
- We were missing actual block state when user clicks "Don't show posts from..:" 
- We use `feedSettings` to check the state and show it
- Added option to "Show posts from" when source is blocked which remove filter eg. follows source
WT-2013 #done
=> feat: add block state for post option

packages/shared/src/components/tooltips/ChangelogTooltip.tsx, packages/shared/tailwind.config.js
move max and min height to extend rather then override
=> fix: move max and min height to extend rather then override

packages/shared/src/components/modals/common/Modal.tsx
- With now tailwind defaults we need to remove the `max-h-full` on the modal (post modal)
Before:
After:
=> fix: post modal

packages/shared/src/components/Settings.tsx
- Unable to use `useFeedLayout` since it requires Feed context which is not available in this Modal.
- Don't show the density and layout when the user is under the experiment for feed layout.
Preview:
WT-2002 #done
=> fix: settings modal based on feed experiment

packages/shared/src/components/search/SearchBarSuggestion.tsx
- As we removed the default border radius the suggestion is actually better as medium to be more inline. (this was rendered before)
=> fix: buttonsize to be large

packages/shared/src/components/TagLinks.tsx
- The tag links didn't leverage the `buttonSize` prop so they both got `medium` and `xsmall` as classes.
Before:
After:
=> fix: tag link size wasn't leverage `buttonSize`

packages/shared/src/components/post/SquadPostContent.tsx
- Decide whether to use the shared post's type to use for the layout.
=> fix: usage of layout type

packages/shared/src/components/buttons/ButtonV2.tsx, packages/shared/src/components/profile/AccountDangerZone.tsx, packages/shared/src/components/profile/PostsSection.tsx, packages/shared/src/components/profile/ProfileButton.tsx, packages/shared/src/components/sidebar/SidebarUserButton.tsx, packages/webapp/components/layouts/AccountLayout/EmailForm.tsx, packages/webapp/components/layouts/AccountLayout/Security/AccountLoginSection.tsx, packages/webapp/components/layouts/AccountLayout/Security/index.tsx, packages/webapp/components/layouts/ProfileLayout/NavBar.tsx, packages/webapp/components/layouts/ProfileLayout/index.tsx
First iteration of moving to ButtonV2 in our components, more to come...
This one tackles ProfileButton, Profile Page and Account Settings pages.
Related: https://dailydotdev.atlassian.net/browse/WT-2017 
<br/>
=> chore: refactor profile page and account settings to ButtonV2

packages/shared/src/components/post/PostUpvotesCommentsCount.tsx, packages/webapp/__tests__/PostPage.tsx
Stops rendering an empty div if there are no comments or upvotes, reducing the black gap
<table>
<tr>
<td>Before
<td>After
<tr>
<td><img src="https://github.com/dailydotdev/apps/assets/1681525/a198f060-9444-494e-8bf5-24c570bac440">
<td><img src="https://github.com/dailydotdev/apps/assets/1681525/79ae7d87-3358-48c3-8859-758c05547cd5">
</table>
=> fix: do not render PostUpvotesCommentsCount if there are no comments or upvotes

packages/shared/package.json, packages/webapp/package.json
In last few weeks/moths (since react migration) I noticed our bundle size was rising incrementally with each PR. In partial this might be for not using lazy loading for some components and probably due to barrel files usage in project. But while looking at it I noticed we might be able to save on those KBs with enabling tree shaking of all unused code. 
Read more at: https://webpack.js.org/guides/tree-shaking/#mark-the-file-as-side-effect-free
Basically by declaring no side effects all unused code is remove from final bundle. I don't think we have any side effects because at the end our shared is bundled during webapp build so actually all the code needed is pulled there. 
Only side effect I could find was `lazysizes` import which at this point is legacy and we already mentioned we should …
=> feat: tree shaking barrel files webapp

packages/shared/src/components/post/ShareYouTubeContent.tsx
=> fix: top video margin in shared post content

packages/shared/src/components/onboarding/CreateFeedButton.tsx, packages/shared/src/components/onboarding/FilterOnboardingStep.tsx, packages/shared/src/components/onboarding/FilterOnboardingV4.tsx, packages/shared/src/components/onboarding/IntroductionOnboarding.tsx, packages/shared/src/components/onboarding/OnboardingHeader.tsx, packages/webapp/components/CookieBanner.tsx, packages/webapp/components/FooterNavBar.tsx, packages/webapp/components/KeywordManagement.tsx, packages/webapp/components/invite/AISearchInvite.tsx, packages/webapp/components/invite/Referral.tsx, packages/webapp/components/layouts/AccountLayout/AccountPageContainer.tsx, packages/webapp/components/layouts/AccountLayout/EmailSentSection.tsx, packages/webapp/pages/account/profile.tsx, packages/webapp/pages/devcard.tsx, packages/webapp/pages/onboarding.tsx, packages/webapp/pages/sources/[source].tsx, packages/webapp/pages/squads/[handle]/edit.tsx, packages/webapp/pages/tags/[tag].tsx
refactor to use ButtonV2 in `packages/webapp` and onboarding components
Fixed 1 bug with email form displaying two arrows on mobile:
Before:
After:
=> refactor: use ButtonV2 in webapp components and onboarding

packages/extension/src/companion/CompanionContent.tsx, packages/extension/src/companion/CompanionMenu.tsx, packages/extension/src/companion/CompanionPermission.tsx, packages/extension/src/companion/CompanionPopupButton.tsx, packages/extension/src/companion/CompanionToggle.tsx, packages/extension/src/newtab/CustomLinks.tsx, packages/extension/src/newtab/DndBanner.tsx, packages/extension/src/newtab/DndModal.tsx, packages/extension/src/newtab/MostVisitedSitesModal.tsx, packages/extension/src/newtab/ShortcutLinks.tsx, packages/extension/src/newtab/ShortcutLinksModal.tsx
refactored to use ButtonV2 in all of the files inside `packages/extension` directory
Related: https://dailydotdev.atlassian.net/browse/WT-2017
=> refactor: use ButtonV2 in extension directories

packages/shared/src/components/cards/ActionButtons.tsx
- When in insane mode, it checks if the post is of type `shared`, and then gets the permalink from the sharedPost
=> fix: check if shared post and use sharedPost permalink in insane mode

packages/shared/src/components/notifications/NotificationItem.tsx, packages/shared/src/components/notifications/NotificationItemAttachment.tsx, packages/shared/src/graphql/notifications.ts
- Adjust the `NotificationAttachment` component to identify whether to use the image component for video or not.
WT-2055 #done
=> refactor: post notification type

packages/shared/src/components/cards/PostMetadata.tsx, packages/shared/src/components/post/ShareYouTubeContent.tsx, packages/shared/src/components/utilities/common.spec.tsx, packages/shared/src/components/utilities/common.tsx
Creates a new function that formats the readTime as [discussed here](https://dailydotdev.slack.com/archives/C059GQ5RFP0/p1702562731056579).
I decided to also do it for read time, in the extreme cases the read time is over 60 minutes
=> feat: render watch time as 1h 23m

packages/shared/src/components/cards/ActionButtons.tsx, packages/shared/src/components/post/PostHeaderActions.tsx, packages/shared/src/components/post/SharePostContent.tsx, packages/shared/src/components/utilities/common.tsx, packages/shared/src/graphql/posts.ts
It just hides the read post button if the post is a freeform, as clicking on the card opens it. I was thinking about mimicking that on the button, but thought removing it made more sense. Let me know if I should re-introduce it.
Also updated the target link of the button if the article is a shared post that points to another squad.
=> fix: insane mode read post button

packages/shared/src/components/modals/OnboardingModal.tsx, packages/shared/src/components/modals/Prompt.tsx, packages/shared/src/components/post/PostComments.tsx, packages/shared/src/components/post/PostHeaderActions.tsx, packages/shared/src/components/squads/SquadMemberItemAdditionalContent.tsx, packages/shared/src/hooks/useAuthForms.ts, packages/shared/src/hooks/useDeleteSquad.ts, packages/shared/src/hooks/useLeaveSquad.ts, packages/shared/src/hooks/usePostMenuActions.ts, packages/shared/src/hooks/usePrompt.ts
Use ButtonV2 in all of the prompts. Also refactored the interface of the `usePrompt` hook to make it less ambiguous -> removed the `ok` and `cancel` fields from the `className` field. These were redundant, since we already had `okButton` and `cancelButton` fields on the options object itself, which allow to set the className and other button fields as well.
=> refactor: use ButtonV2 in all of the prompts

packages/shared/src/components/modals/Prompt.tsx
Reverts prompt conditions to the state prior to 
- #2437 
After fix:
=> fix: prompts not showing cancel button in some cases

packages/shared/src/components/cards/ActionButtons.tsx
- no options for freeform (and other internal read types)
- additional bookmark/share when experiment is active
Before:
After:
=> fix: actions rendering in list mode

packages/shared/src/components/post/RelatedPostsWidget.tsx
- currently the next arrow in related posts widget will always be active until user clicks on it and request checks if there is data
- this is due to using cursor pagination which does not include total
- with this we always prefetch next page so we can preemptively disable the button if there is no next page
=> fix: check if next page exists and disable pagination

packages/shared/src/components/image/VideoImage.tsx, packages/shared/src/components/notifications/NotificationItemAttachment.tsx
Fixes the width of video image in notifications, and reduces the size of the play icon
<table>
<tr>
<td>Before
<td>After
<tr>
<td>
</td>
<td><img width="383" alt="image" src="https://github.com/dailydotdev/apps/assets/1681525/982cf08f-2233-4766-906e-ead7471bdaee">
</table>
=> fix: image wrapper width in notifications

packages/shared/src/components/cards/PostCardFooter.tsx, packages/shared/src/components/cards/SharedPostCardFooter.tsx
Get's rid of the following react warning in dev tools console:
```
Warning: React does not recognize the `wrapperClassName` prop on a DOM element. If you intentionally want it to appear in the DOM as a custom attribute, spell it as lowercase `wrapperclassname` instead. If you accidentally passed it from a parent component, remove it from the DOM element.
```
=> fix: console warning when using wrapperClassName prop on plain image

packages/shared/src/hooks/useHideOnModal.ts
- Original [issue](https://dailydotdev.slack.com/archives/C01L0QXQJNB/p1701346072422259) 
- Basically the issue was that we add `hide-on-modal` class on next root when modal is active, it is controlled in `useHideOnModal` hook
- This class (after opening post modal once) would not be cleaned, which then would hide the feed when any other modal like share is active
- This was due to modal which called the hook `useHideOnModal` being unmounted because it was closed
- Here I add the cleanup to remove the class on unmount which fixes the issue
Before:
After:
| Type   | …
=> fix: cleanup hide modal class on hook unmount

packages/extension/src/contexts/ExtensionContext.tsx, packages/extension/src/newtab/App.tsx, packages/shared/src/components/ExtensionOnboarding.tsx, packages/shared/src/components/ExtensionPermissionsPrompt.tsx, packages/shared/src/contexts/ExtensionContext.tsx, packages/shared/src/hooks/useHostPermissionStatus.ts
- Replaces useRef with useState and adds it to `ExtensionContextProvider` to prevent prop drilling
- Render nothing while checking for host permissions
WT-2021 #done
=> fix: replace useRef with state

packages/shared/src/components/cards/Card.tsx, packages/shared/src/components/cards/CollectionCard/CollectionCardHeader.tsx, packages/shared/src/components/cards/SharedPostCardHeader.tsx, packages/shared/src/components/cards/SharedPostText.tsx, packages/shared/src/components/cards/WelcomePostCardHeader.tsx, packages/shared/tailwind.config.js
- After further investigation, there seem to be quite a few inaccuracies in the implementation of spacings around the card.
- Spacing between the user info and the post's title/description.
- Spacing between the title/description and the post's image.
- Even though the max height from the design is `364px`, it doesn't seem to fit the content even though all the other parts are accurate, such as the margins, paddings, image size, etc. - probably due to some line height or something else. Though this is a known issue that sometimes design are not 100% translatable in terms of the sizing. With that, the current card max height is `380px` and after fixing the spacings, it seems what we actually need is `388px`.
- Currently deployed at preview3. Screenshots below but feel free to check the …
=> fix: card height

packages/shared/src/components/cards/ArticlePostCard.tsx, packages/shared/src/components/cards/common/SquadPostCardHeader.tsx
- Fixed a merge issue.
- Fixed the card layout for mobile - there was a `mb-8` which is not really necessary due to the fact that we have an empty div with `flex-1` class.
=> fix: card on mobile layout

packages/shared/src/components/buttons/QuaternaryButton.tsx, packages/shared/src/components/cards/ActionButtons.tsx, packages/shared/src/components/tooltips/ChangelogTooltip.tsx
- With button v2 props, but rendering v1 it would not take size into account.
- This fixes the usecase of button v2 for action buttons
=> fix: action button sizes

packages/shared/src/components/cards/AdCard.tsx, packages/shared/src/components/cards/AdList.tsx, packages/shared/src/components/cards/CollectionCard/CollectionCard.tsx, packages/shared/src/components/cards/WelcomePostCard.tsx, packages/shared/src/components/cards/WelcomePostCardFooter.tsx, packages/shared/src/components/cards/common.tsx, packages/shared/src/hooks/post/usePostImage.ts
- Fixed the freeform card's max clamp. From the design it should have been 3 lines only, similar to article post card.
From Sketch:
Before fix:
After the fix:
=> fix: freeform card

packages/shared/src/components/profile/SocialChips.tsx
Long portfolio links broke the design of the page
Fixed version:
=> fix(profile): apply ellipsis on long social link

packages/shared/src/components/FeedLayout.tsx, packages/shared/src/hooks/useMedia.ts, packages/shared/src/lib/featureManagement.ts, packages/shared/src/styles/media.ts
3rd try - this time we are using different media queries depending on if the sidebar is rendered closed, rendered open or not rendered at all.
We do not need different configurations this way and align to the minimal size of 272px for the single card, as defined in Figma.
Before:
After:
Manually checked all the combinations of sidebar closed, open and not rendered at all and settings eco, cozy and roomy as well.
WT-2079 #done
=> fix overflowing action buttons on feed cards

packages/shared/src/components/widgets/SocialShareButton.tsx
- We removed the max width on the label in this [PR](https://github.com/dailydotdev/apps/commit/cc0fc7fddf42f8906ddde9ec9416dd8fb400edb8#diff-c51536179cd65e101734e0bc1ef33c9d3eea7d8b5e31b853212daacd43410a3bR50).
- @kopancek not sure this was intended, maybe it had a reason.
WT-2076 #done
=> fix: clashing labels

packages/shared/src/components/CalendarHeatmap.tsx, packages/shared/src/hooks/profile/useActivityTimeFilter.ts, packages/webapp/__tests__/ProfileIndexPage.tsx, packages/webapp/components/layouts/ProfileLayout/index.tsx
I forgot to set `screenCentered` for the profile page which ignored the sidebar.
Moreover, I set the heatmap to be dynamically responsive. Up until now, it was responsive only on fresh load. Which means the opening and closing the sidebar broke the page even with screen centered.
=> fix(profile): take into account sidebar for responsiveness

packages/shared/src/components/FeedLayout.tsx, packages/shared/src/styles/media.ts
After [slack discussion](https://dailydotdev.slack.com/archives/C01L0QXQJNB/p1704360982001079) and syncing with Tsahi, it seems the best way forward would be to limit the number of columns in feed layout to 6 at maximum. Showing 7 columns with sidebar open might skew our current metrics.
After:
=> hotfix: change maximum number of columns in feed layout to 6

packages/shared/src/components/sidebar/ClickableNavItem.tsx, packages/shared/src/components/sidebar/Section.tsx, packages/shared/src/components/sidebar/SquadSection.tsx, packages/shared/src/components/sidebar/common.tsx
<table>
<tr>
<td>Before
<td>After
<tr>
<td><img src="https://github.com/dailydotdev/apps/assets/1681525/0f1ec724-84be-4c53-8b26-1956c48c07d8">
<td><img src="https://github.com/dailydotdev/apps/assets/1681525/95056299-f664-4517-b214-70a7ce7d4f37">
<tr>
<td colspan="2">Bonus, added popover to truncated items<br><img src="https://github.com/dailydotdev/apps/assets/1681525/96fc10d7-7bd8-4014-8200-f3847a51dc9c"></td>
</table>
- Fixed truncating on sidebar items
- Added title to sidebar items to show popover on hover
=> fix: add text truncating to sidebar items

packages/shared/src/components/layout/MainLayoutHeader.tsx, packages/shared/src/components/post/write/CreatePostButton.tsx, packages/shared/src/components/profile/ProfileButton.tsx, packages/shared/src/components/referral/SearchReferralButton.tsx, packages/shared/src/components/sidebar/SidebarUserButton.tsx
Changes the border radius of buttons and button sizes in the main layout header, so that we are consistent across the board.
The figma design is here: https://www.figma.com/file/C7n8EiXBwV1sYIEHkQHS8R/daily.dev---Design-System?node-id=1886%3A8672&mode=dev
Before:
After:
=> fix: consistent border-radius and button sizes in main layout header and sidebar

packages/shared/src/components/squads/SquadPostListItem.tsx
- Small fix for squads that have articlePosts which don't have authors assigned. (Can happen in relatedArticles basically)
=> fix: public squad with articles didn't render

packages/shared/src/components/markdown.module.css
- The fix on the multi-line code block padding should now be applied.
- Though on the inline ones, I can't seem to find the right pseudo-class to apply the proper paddings.
Fix:
Sketch:
WT-1975 #done
=> fix: code block paddings

packages/shared/src/components/cards/CollectionCard/CollectionCard.tsx
- Not sure how we missed it, the bookmark action on cart did not work because of missing handler prop
- Noticed it when preparing collections demo
=> fix: bookmark not working for collection cards

packages/shared/src/components/alert/AlertPointer.tsx, packages/shared/src/components/filters/MyFeedHeading.tsx
- Placement of the alert pointer should depend on the layout/search experiment.
Previews of all the variations:
WT-2011 #done
=> refactor: feed settings button alert pointer

packages/shared/src/components/FeedItemComponent.tsx, packages/shared/src/components/InteractionCounter.tsx, packages/shared/src/components/auth/SignBackButton.tsx, packages/shared/src/components/buttons/OptionsButton.tsx, packages/shared/src/components/cards/AdAttribution.tsx, packages/shared/src/components/cards/AdCard.tsx, packages/shared/src/components/cards/AdList.tsx, packages/shared/src/components/cards/PlaceholderCard.tsx, packages/shared/src/components/cards/v1/ActionButtons.tsx, packages/shared/src/components/cards/v1/AdCard.tsx, packages/shared/src/components/cards/v1/AdLink.ts, packages/shared/src/components/cards/v1/ArticlePostCard.tsx, packages/shared/src/components/cards/v1/Card.tsx, packages/shared/src/components/cards/v1/CollectionCard.tsx, packages/shared/src/components/cards/v1/FeedItemContainer.tsx, packages/shared/src/components/cards/v1/FeedbackCard.tsx, packages/shared/src/components/cards/v1/PlaceholderCard.tsx, packages/shared/src/components/cards/v1/PostCardFooter.tsx, packages/shared/src/components/cards/v1/PostCardHeader.tsx, packages/shared/src/components/cards/v1/PostMetadata.tsx, packages/shared/src/components/cards/v1/RaisedLabel.tsx, packages/shared/src/components/cards/v1/SharePostCard.tsx, packages/shared/src/components/cards/v1/TypeLabel.tsx, packages/shared/src/components/cards/v1/WelcomePostCard.tsx, packages/shared/src/components/feeds/FeedContainer.tsx, packages/shared/tailwind.config.js
- Added copies of cards and other needed components into `/v1` folder
- Using the copied v1 cards based on type and feed v1 being on in `FeedItemComponent.tsx`
- Added proper borders and spacing around cards
- Changed the header of the card to show the type (for video and collection cards)
- Changed the display of the hot/pinned flag, based on figma designs
- Please do not focus your review on inner card details. I did some work already (mistakenly), but we do have subtasks to tackle the card contents, the card header and card footer (action buttons).
- The decision to make card copies in another directory was made in the DR.
WT-2004 #done
=> feat: feed layout v1 card layout implementation

packages/shared/src/components/PostOptionsMenu.tsx, packages/shared/src/hooks/feed/useAdvancedSettings.ts, packages/shared/src/hooks/useFeedSettings.ts
- When viewing a post page, and you try to follow/unfollow certain tags/sources/settings, the values do not update when you do any action.
- In this PR, we now consider the current state of the user's preference to reflect better the actual status.
- Introduced a new settings function to update the value based on the desired state. This was due to a bug encountered were the value is not getting updated after clicking undo (because of the memoized function).
| Change/New | event name  | extra: { ... } …
=> fix: post options menu state

packages/shared/src/components/PostOptionsMenu.tsx, packages/shared/src/components/ShareOptionsMenu.tsx, packages/shared/src/components/cards/v1/ActionButtons.tsx
- Bookmark on card should be based on the experiment not on the feed layout.
- For the post options menu, it should be the same.
MI-20 #done
=> refactor: post options menu removing bookmark

packages/shared/src/components/referral/SearchReferralButton.tsx
- As mentioned in the Slack, we are moving back to using a plain `button` element rather than our `Button` element. However, it can be argued that can probably just override the x-padding.
Preview:
MI-1 #done
=> fix: header button back to plain element

packages/shared/src/components/buttons/ButtonV2.tsx
- When the value is 0, it is considered falsy, the button thinks it should be an icon-only render.
Before:
After:
=> fix: button when value is 0

packages/shared/src/components/fields/Checkbox.tsx
- From the discussion, Checkboxes should now have a normal font-weight.
Reference: https://dailydotdev.slack.com/archives/C05TQL6HWTH/p1705395060244609
=> fix: checkbox font weight

packages/shared/src/components/post/collection/CollectionPillSources.tsx
Fixes bad implementation from before, where `className` prop was changed from a string to an object, but not all usages of the prop where refactored.
Also fixes an edge case when accessing fields of the `className` object, which could be potentially `undefined`.
This broke the visuals, because margins were not applied properly.
Before fix:
After fix:
MI-84 #done
=> fix: CollectionPillSources className prop treated as an object

packages/shared/src/hooks/useFeatureFeedLayoutV1.ts, packages/shared/src/hooks/useFeedLayout.ts, packages/shared/src/hooks/useOnPostClick.ts
Change the `useOnPostClick` hook implementation.
The flow is as following:
- If `ActiveFeedContext` provides `feedQueryKey`, behavior is the same as before
- If `shouldUseFeedLayoutV1` is `false`, behavior is the same as before
- If `shouldUseFeedLayoutV1` is `true` and `feedQueryKey` is undefined, we do the following:
1. Get all feed query keys from react query cache
2. For each feed query key:
1. Find the correct `page`, `index` and `post` item based on the `post.id`
2. Call the `updatePost` function with the `page`, `index`, `post`, and apply `read: true` 
3. Use the go back button on the post page
4. Profit from the updated cache 💪 
https://www.loom.com/share/461dd564a737480daca28722be801be1?sid=222b6c95-43fa-442c-a221-81bb4115007f 
MI-32 #done
=> feat: add feedback CTA loop from post page for feed layout v1

packages/shared/src/components/cards/v1/ArticlePostCard.tsx, packages/shared/src/components/cards/v1/FeedbackCard.tsx
- added the image component back to the feedback card (was removed as a part of the footer component)
n / a
MI-16 #done
=> fix: add image thumbnail back to the feedback card

packages/shared/src/hooks/useTruncatedSummary.ts
Root cause of the error:
n / a
WT-87 #done
=> fix: don't crash when trying to truncate a null title

packages/shared/src/contexts/ActiveFeedNameContext.tsx
- self explanatory
n / a
WT-33 #done
=> fix: cover edge cases where the user has not loaded yet when determining feed name

packages/shared/src/components/cards/RaisedLabel.tsx
=> fix: ensure the beta tag is hidden properly

packages/shared/src/components/cards/v1/AdCard.tsx, packages/shared/src/components/image/VideoImage.tsx
Adds `pointer-events-none` to Ad image and VideoImage. That way, clickling on the images the container click event is used -> opens the post.
MI-85 #done
=> fix: feed layout v1 ad and video image are not clickable

packages/shared/src/components/Feed.tsx, packages/shared/src/components/cards/v1/ActionButtons.tsx
Changes `onCommentClick` handler to not open the post modal on feed layout v1.
Changes comments action `<button>` to an `<a>` HTML element and adds `href` to point to the post page.
All tracking events should be fired the same way as they did previously. We also track the comment click the same way as we did previously for the feed layout version.
MI-92 #done
=> fix: comments button opens post page

packages/extension/src/newtab/CustomLinks.tsx, packages/extension/src/newtab/MainFeedPage.tsx, packages/shared/src/components/feeds/FeedContainer.tsx, packages/shared/tailwind.config.js
Changed paddings, margins, border color, etc. to adhere to Figma designs.
Added new arbitrary breakpoint - `[@media(width<=680px)]`, which is the same size as feed width. That way, we set the margin/padding around search bar and shortcuts at the right spot.
Before:
After:
Loom:
https://www.loom.com/share/953538f05f714772bd6efb7ea6e8521c?sid=453e64b4-41fd-4afc-9785-682c6bd32f91
MI-91 #done
=> fix: feed layout margins, paddings and breakpoints

packages/webapp/components/layouts/SearchLayout.tsx
- Enable search footer bar for the AI search page
=> fix: enable search footerbar

packages/shared/src/components/feeds/FeedContainer.tsx, packages/shared/src/components/onboarding/FeedReadyMessage.tsx
Fixes the onboarding `FeedReadyMessage` styling for feed layout v1.
Old feed
Feed Layout V1
MI-102 #done
=> fix: onboarding visuals

packages/shared/src/components/cards/v1/FeedItemContainer.tsx, packages/shared/src/components/cards/v1/TypeLabel.tsx
- As the color of card hover/focus state is with opacity based on the current card color, an extra div is needed to help the label achieve the same color without needing to add another color to our base css themes
- Added another div to surround the label and added appropriate theme-float color
- moved focus prop inside TypeLabel since it was needed to determine the inner div's classname
P.s difference in color is quite small so it's a bit hard to notice (more noticeable on light mode)
Before:
After:
- [ x] Have you done sanity checks in the webapp?
MI-111 #done
=> fix: background of label to be same as card

packages/shared/src/components/post/collection/CollectionPostContent.tsx
Added a margin in case there is customNavigation present
Before
After
Feed Layout Control unaffected
MI-105 #done
=> fix: add margin to post page collection pill

packages/shared/src/components/image/VideoImage.tsx
- The `h-auto` is consuming more height than intended.
- Applying the `h-fit` makes the container fit to the actual content.
- The control value uses the same component. Hence, should fix both ends.
I have thought of removing the floating `span` overlay at first, but it is probably needed in some cases. ~~Though not sure now whether that background overlay will ever be seen.~~
@dailydotdev/web-team does anyone know why we need that overlay? The color has a bit of opacity, which is why it is turning out to be **not** pitch-black.
Edit: is it probably for the actual overlay that makes the thumbnail a bit dark?
Before:
After:
Don't forget to update the [Analytics Taxonomy sheet](https://docs.google.com/spreadsheets/d/18Lv7zXges9QfVX5VYL1a-Hyl0e1sQ3sL …
=> fix: unnecessary video overlay

packages/shared/src/components/cards/v1/ArticlePostCard.tsx, packages/shared/src/components/cards/v1/SharedPostCardFooter.tsx, packages/shared/src/components/image/VideoImage.tsx
Reverted back to h-auto as default then override on v1. To fix the control, we set the `max-height: fit-content`. 
Tested 3 cases:
- Feed control
- Feed control shared video post
- Feed v1
Fixes the issue here: https://github.com/dailydotdev/apps/pull/2530#issuecomment-1903415156
=> fix: image overlay on both control and v1

packages/shared/src/components/cards/v1/Card.tsx, packages/shared/src/components/cards/v1/FeedItemContainer.tsx, packages/shared/src/components/cards/v1/RaisedLabel.tsx
- Added `border-radius: 16px` to the top border of a card.
- Changed positioning of the type label and flag so that they are `12px` from the side of the card.
- Removed padding from the flag label, so that it aligns with the design.
MI-110 #done
=> feat: align top border radius with latest design

packages/shared/src/components/cards/v1/FeedbackCard.tsx
- Moved the close icon button a size larger.
- Also fixed the placement since the existing values are from the control layout.
- Set max height if 80px for image on feedback UI.
Preview:
MI-96 #done
MI-97 #done
=> fix: feedback close icon and image max height

packages/shared/src/components/search/SearchBarSuggestionList.tsx
- The reason for the layout shift was that the pill's width was not set. Hence, it was not working and taking the supposed space.
- Fixed the consistency of the elements to avoid layout shifts by making them have the same height.
Preview but on Control since I can't test on Search locally.
https://github.com/dailydotdev/apps/assets/13744167/5026603b-9a51-4f92-a193-9b98dd15224d
MI-104 #done
=> fix: missing placeholder that causes layout shifts

packages/shared/src/components/cards/v1/ArticlePostCard.tsx, packages/shared/src/components/cards/v1/CollectionCard.tsx
Changes font size for summary to be consistent on extension as well.
Before
After
MI-114 #done
=> fix: set 16px font size for article summary

packages/shared/src/components/cards/v1/CollectionCard.tsx, packages/shared/src/components/cards/v1/SharePostCard.tsx, packages/shared/src/components/cards/v1/WelcomePostCard.tsx
Fixes missing click handler, because prop was not drilled down.
MI-115 #done
=> fix: add downvote click handler to other card types

packages/shared/src/components/post/SquadPostContent.tsx
- add margin on top of squad source to gain space with back button
MI-117 #done
=> fix: add margin on top of squad source

packages/shared/src/components/cards/v1/ActionButtons.tsx
- removed secondary type from button to get the type based on figma
- on button hover the color of nr of comments should be same color as the highlighted comments button
MI-116 #done
=> fix: comments button color and type

packages/shared/src/components/cards/v1/ActionButtons.tsx
- Moved number of upvotes inside upvotes button
- Added a separator div between downvote and upvote
MI-99 #done
=> fix: improve upvote/downvote design

packages/shared/src/components/cards/v1/ActionButtons.tsx
Adds  `ml-1` left  margin and `-mr-2` negative margin to the interaction counter.
That way, we align with figma - `12px` padding on the button and the number looks centered.
<br/>
<br/>
MI-118 #done
=> fix: padding around interaction counters on card ActionButtons

packages/shared/src/components/cards/v1/ArticlePostCard.tsx, packages/shared/src/components/cards/v1/Card.tsx, packages/shared/src/components/cards/v1/CollectionCard.tsx, packages/shared/src/components/cards/v1/WelcomePostCard.tsx
Sets card image as always `object-cover` and keeps aspect ratio to 1:1 at most. Wider images keep being wider.
https://www.loom.com/share/32069f44198343a6ace989791a9c5793?sid=09b36bc9-919b-47f3-b32d-ee0dad2358f1
MI-95 #done
=> fix: set card image to object-cover and keep max 1:1 aspect ratio

packages/shared/src/components/cards/v1/ActionButtons.tsx, packages/shared/src/components/cards/v1/ArticlePostCard.tsx, packages/shared/src/components/cards/v1/SharePostCard.tsx
- Fixes the tooltip for the comment button which has now become a link.
- Fixes the card's header to make the source name a link.
- Bookmark missing undo button seems to be the case since then, no changes needed, I think.
=> fix: feed layout comment tooltip and source link

packages/shared/src/components/feeds/FeedContainer.tsx, packages/shared/src/components/feeds/FeedGradientBg.tsx
- Replace the image by using CSS to avoid the square cut from both ends.
Preview:
99)
=> fix: search highlight effect

packages/shared/src/components/feeds/FeedGradientBg.tsx
Based on [figma spec](https://www.figma.com/file/nmfWPS7x3kzLUvYMkBx2kW/daily.dev---Dev-Mode?node-id=1882%3A12132&mode=dev), the position of the gradient div should be right above the search container.
=> fix: position of search gradient background

packages/shared/src/components/feeds/FeedGradientBg.tsx
- The size of the gradient bg is what causes it to overflow. Have set a max-width to prevent the scroll to show.
=> fix: horizontal scroll caused by bg

packages/shared/src/components/post/SharePostContent.tsx, packages/shared/src/components/post/ShareYouTubeContent.tsx
- While working on the YT section being clickable as a section and redirect, I noticed there are still missing analytics.
[Discussion](https://dailydotdev.slack.com/archives/C015T1Y237Z/p1702292038866539) in the past.
One of the recent PRs fixed the click on image analytics, but the title itself was not fixed.
=> fix: missing analytics

packages/shared/src/components/onboarding/FilterOnboardingV4.tsx
- missing relative positioning on new button because dots are absolute position
AS-81 #done
=> fix: onboarding tags not showing dots for similar tags

packages/shared/src/components/cards/ShowMoreContent.tsx, packages/shared/src/components/post/ShareYouTubeContent.tsx, packages/shared/src/components/post/common/SharedLinkContainer.tsx, packages/shared/src/components/utilities/SelectableLink.tsx, packages/shared/src/components/utilities/index.ts
- When clicking the whole section below of a YT content, it should redirect the user when it is a post found inside dailydev.
- When it is a shared external video, the user should do nothing.
- An edge case we were asked to cover: prevent default on click when the user is highlighting the content/selecting texts.
Currently deployed at preview2.
https://preview2.app.daily.dev/squads/youtubecontent
See the difference between the first and second post.
Preview:
https://github.com/dailydotdev/apps/assets/13744167/6f353d4b-6cd0-4715-a28f-6867337bbe3c
| Type   | …
=> fix: tldr section to navigate to post

packages/shared/src/components/GrowthBookProvider.tsx
- adding mobile attribute based on view size
- In order to run the feed layout experiment only on mobile we need a new attribute provided to growthbook
Based on the decision in slack [thread](https://dailydotdev.slack.com/archives/C061T644XV3/p1706629276404129?thread_ts=1706628190.527109&cid=C061T644XV3).
=> feat: add mobile attribute to growthbook

packages/shared/src/components/layout/MainLayoutHeader.tsx, packages/shared/src/components/streak/ReadingStreakButton.tsx, packages/shared/src/components/streak/popup/ReadingStreakPopup.tsx, packages/shared/src/graphql/users.ts, packages/shared/src/hooks/streaks/useReadingStreak.ts, packages/shared/src/lib/dateFormat.ts, packages/shared/src/lib/query.ts
- Utilized an existing query used in the heatmap to check whether the user has read from previous days but limited the amount.
- Fixed the issue when the popup is opened, it should close when the user clicks anywhere outside.
- Integrates the popup content with the live data.
The complete days indicated in the image below is true from the live data.
MI-78 #done
=> feat: reading streak button and popup integration

packages/shared/src/components/MainFeedLayout.tsx, packages/shared/src/components/SearchEmptyScreen.tsx, packages/shared/src/graphql/search.ts, packages/webapp/components/search/SearchControlPage.tsx
- Adjustments to empty state of the new search page
- Now by default the `/search` page does not show anything until you search
- Also made adjustments to no results page from AS-40 since it was connected closely
TODO:
AS-69 #done
=> feat: adjust search page and empty state

packages/shared/src/components/ExtensionOnboarding.tsx
- add z-index to button to be on top of the glow
- issue in slack https://dailydotdev.slack.com/archives/C01L0QXQJNB/p1707294893902169
=> hotfix: add z-index to button to be on top of the glow

packages/shared/src/components/Feed.tsx, packages/shared/src/components/MainFeedLayout.tsx, packages/shared/src/hooks/useScrollRestoration.ts, packages/webapp/pages/_app.tsx
=> feat: only restore on feed pages

packages/shared/src/hooks/useScrollRestoration.ts, packages/webapp/pages/_app.tsx
=> feat: collect restoration only on enabled pages

packages/shared/src/hooks/search/useSearchProviderSuggestions.ts
- Just remove suggestions when query changes to avoid focus lose if you focused one of the old suggestions when new ones display
=> feat: invalidate search suggestions on query change

packages/shared/src/components/post/FixedPostNavigation.tsx, packages/shared/tailwind.config.js
- Ensure the post navigation lays on top of the now sticky top header.
- Not perfect, but since mobile-UX will come this is the best solution for now (to avoid eating too much space there)
AS-109 #done
=> fix: ensure post navigation sit on top of header

packages/shared/src/components/search/SearchPanel/SearchPanelPostSuggestions.tsx
- search panel suggestion post links in extension were broken
- this opens them in webapp
=> fix: use webapp url so that links open there in extension

packages/shared/src/components/feeds/FeedContainer.tsx
- Fixes alignment and render of shortcuts in different feed layouts and experiments
Control:
Search V1:
Layout V1:
AS-108 #done
=> fix: alignment and render of shortcuts

packages/shared/src/components/layout/MainLayoutHeader.tsx, packages/shared/src/components/modals/common/Modal.tsx, packages/shared/src/components/sidebar/Sidebar.tsx, packages/shared/tailwind.config.js
- Make laptop header 64px across control and experiments to fix layout shift due to vary size
AS-110 #done
=> fix: layout shift on pages because of different header height

packages/shared/src/components/cards/Card.tsx, packages/shared/src/components/checklist/ChecklistCard.tsx
- created new styled component to remove the overrides on the Card component
- added max-w-fit
- fixes squad checklist not being able to show all content
MI-140 #done
=> fix: height of checklist to be based on content

packages/shared/src/components/profile/devcard/DevCard.tsx, packages/shared/src/components/profile/devcard/DevCardFooter.tsx
The tags are now vertically aligned
Profile picture border is set to 8px in all cases, not just for horizontally laid out card
=> fix: vertical align of tags + border width of profile image

packages/shared/src/components/profile/devcard/common.ts, packages/shared/src/lib/analytics.ts, packages/webapp/pages/devcard.tsx
- adds event in devcard actions
Did you introduce any new tracking events? Yes
Don't forget to update the [Analytics Taxonomy sheet](https://docs.google.com/spreadsheets/d/18Lv7zXges9QfVX5VYL1a-Hyl0e1sQ3sLr0OK8YZWKXI/edit#gid=0) This is updated
| New | generate devcard  | - |
| New | download devcard  | extra: { format: horizontal, vertical, x } |
| New | copy devcard code  | - |
| New | share devcard  | extra: { provider: native, copy link, whatsapp, twitter, facebook, reddit, linkedin, telegram, email } |
=> Feat add events devcard

packages/webapp/components/layouts/AccountLayout/index.tsx, packages/webapp/pages/bookmarks.tsx, packages/webapp/pages/filters.tsx, packages/webapp/pages/posts/[id]/edit.tsx, packages/webapp/pages/squads/[handle]/edit.tsx, packages/webapp/pages/squads/create.tsx, packages/webapp/pages/squads/new.tsx, packages/webapp/public/robots.txt
- Add more noindex/nofollow for pages that are private/unwanted in search results
=> fix: add noindex to private/unwanted pages

packages/shared/src/components/LoginButton.tsx, packages/shared/src/components/MainLayout.tsx, packages/shared/src/components/auth/AuthModal.tsx, packages/shared/src/components/auth/AuthOptions.tsx, packages/shared/src/components/auth/AuthenticationBanner.tsx, packages/shared/src/components/auth/OnboardingHeadline.tsx, packages/shared/src/components/auth/OnboardingRegistrationForm.tsx, packages/shared/src/components/auth/index.ts, packages/shared/src/components/banners/common.ts, packages/shared/src/components/banners/index.ts, packages/shared/src/components/layout/MainLayoutHeader.tsx, packages/shared/src/components/modals/NewRankModal.tsx, packages/shared/src/components/modals/OnboardingModal.tsx, packages/shared/src/components/post/BasePostContent.tsx, packages/shared/src/components/sidebar/SidebarUserButton.tsx, packages/shared/src/hooks/auth/index.ts, packages/shared/src/hooks/auth/useOnboarding.tsx, packages/shared/src/lib/featureManagement.ts, packages/shared/src/lib/featureValues.ts, packages/shared/src/styles/base.css, packages/shared/tailwind/overlay.js, packages/webapp/pages/onboarding.tsx, packages/webapp/pages/posts/[id]/index.tsx, packages/webapp/pages/signup.tsx
- Made the `AuthOptions` accept a `className` object to be applied on certain elements.
- Introduced `ignoreMessages` prop. This is because we will now be rendering two `AuthOptions` component. One for the banner, and one for the modal. We want the banner to only be utilized when clicking the provider buttons. The other (modal) auth options will be listening to the messages which will continue the process.
- Tracking events are intact since we just reused the same component.
Preview in action:
https://dailydotdev.slack.com/archives/C06K1LYU716/p1707947399158029?thread_ts=1707940049.888179&cid=C06K1LYU716
Don't forget to update the [Analytics Taxonomy sheet](https://docs.google.com/spreadsheets/d/18Lv7zXges9QfVX5VYL1a-Hyl0e1sQ3sLr0OK8YZWKXI/edit#gi …
=> feat: authentication banner

packages/webapp/components/layouts/ProfileLayout/index.tsx, packages/webapp/next.config.js, packages/webapp/public/robots.txt
Chris suggested a much better and failsafe approach. We should utilize noindex on the page itself.
I added a property for the profile which indicates whether it should add the noindex property.
=> refactor: use noindex instead of robots.txt

packages/shared/src/components/post/SquadPostAuthor.tsx, packages/shared/src/components/post/SquadPostContent.tsx, packages/shared/src/components/squads/SquadPostListItem.tsx
- Fixed the widget's content overflow - line clamp 1 was not working, so I manually added the common classes for ellipsis.
- Fixed some minor spacing issues.
=> fix: squad widgets content overflow

packages/shared/src/components/comments/PlaceholderComment.tsx, packages/shared/src/components/post/PostLoadingPlaceholder.tsx
- The `rounded-full` in the placeholder suddenly started working after the migration (was introduced way back) 🤔 
=> fix: placeholder roundness for post page

packages/shared/src/components/feeds/FeedContainer.tsx
- We decided to remove the gradient after onboarding.
=> fix: remove gradient after slack discussion

packages/webapp/pages/devcard.tsx
- removes sharing section from devcard
- decision coming from [slack](https://dailydotdev.slack.com/archives/C06FDFQC6QZ/p1708328543387319?thread_ts=1708002083.892319&cid=C06FDFQC6QZ)
I removed event: share devcard
=> fix: removing share section from devcard

packages/shared/src/components/auth/AuthOptions.tsx, packages/shared/src/components/auth/OnboardingRegistrationForm4d5.tsx
Adding new onboarding modal needed to show on the flow:
- its a modification of original modal
- added back email field/signup
- moved to separate component so we can easily manipulate until feature is done
- only adding view in this PR so that it can be used where needed per new spec
Some changes from design:
- modal background in design is popover, all our auth modals are tertiary
- email field has placeholder vs everywhere else its with label animating to top (so left it as that)
- title gradient is a slightly different, left it as in app currently
| Type   | …
=> feat: new onboarding modal

packages/shared/src/hooks/referral/useReferralCampaign.ts, packages/webapp/components/invite/AISearchInvite.tsx, packages/webapp/pages/join.tsx
- Discussion [here](https://dailydotdev.slack.com/archives/C063RS0QZTM/p1708271776431239) 
- I think it won't interfere with anything but people that got invites recently will be able to join 🙏 
=> feat: restore search join page for links that are already in the wild

packages/eslint-rules/lib/rules/no-custom-color.js, packages/shared/src/components/onboarding/OnboardingFeedHeader.tsx, packages/shared/src/lib/featureManagement.ts, packages/shared/src/styles/base.css, packages/shared/tailwind.config.js, packages/shared/tailwind/colors.js
- Styling issues for the header part.
- One [open](https://dailydotdev.slack.com/archives/C068F77M8Q7/p1708439180773429) question as the color for lightmode seems wrongly defined in Figma
Screens:
=> fix: added fixed header styling

packages/extension/webpack.config.js
- Since we don't use it on extension we need to exclude it from build.
=> fix: disable onesignal

.vscode/apps.code-workspace
Keep getting this change whenever I open apps in VSCode, so I presume it means that the extension has changed the default value from `true` to `explicit`.
=> fix: vscode eslint argument

packages/shared/src/components/auth/AuthOptions.tsx
- Fix the transition issue by waiting for the next tick before displaying the new UI.
- This ensures the window is opened.
- I also tried making the `onProviderClick` an async function that does the next tick but it might impact other areas, with that, I only kept the changes within the primary area of concern.
MI-175 #done
=> fix: transition to auth display

packages/shared/src/components/profile/ProfileImageLink.tsx
removes the `user` attribute that was unintentionally passed through to the HTML `<a>` element.
See slack discussion:
https://dailydotdev.slack.com/archives/C06FDFQC6QZ/p1708673722619149
=> fix: remove user attribute from source link

packages/extension/src/newtab/MainFeedPage.tsx, packages/shared/src/components/Feed.spec.tsx, packages/shared/src/components/MainFeedLayout.tsx, packages/shared/src/components/MainLayout.tsx, packages/shared/src/components/feeds/FeedContainer.tsx, packages/shared/src/components/filters/MyFeedHeading.tsx, packages/shared/src/components/layout/MainLayoutHeader.tsx, packages/shared/src/components/layout/common.tsx, packages/shared/src/components/sidebar/ManageSection.tsx, packages/shared/src/components/sidebar/Sidebar.spec.tsx, packages/shared/src/hooks/feed/useFeedName.ts, packages/shared/src/lib/featureManagement.ts, packages/shared/src/lib/featureValues.ts, packages/webapp/__tests__/BookmarksPage.tsx, packages/webapp/__tests__/SearchPage.tsx, packages/webapp/components/invite/AISearchInvite.tsx, packages/webapp/components/layouts/BookmarkFeedPage.tsx, packages/webapp/components/layouts/MainFeedPage.tsx, packages/webapp/components/layouts/MainFooterLayout.tsx, packages/webapp/components/layouts/SearchLayout.tsx, packages/webapp/components/search/SearchControlPage.tsx, packages/webapp/pages/history.tsx, packages/webapp/pages/search/chat/index.tsx, packages/webapp/pages/search/posts/index.tsx
- Cleanup winnig search experiment.
- @capJavert Greeting not really used now, but left the actual component as it's lazy loaded
AS-141 #done
=> fix: cleanup the search as winning experiment

packages/webapp/pages/devcard.tsx
- add missing tooltip for devcard theme buttons
- centered the tooltip, since it was off center before
=> chore: add missing tooltip for devcard theme buttons

packages/shared/src/components/auth/CodeVerificationForm.tsx, packages/shared/src/hooks/useAccountEmailFlow.ts
- With introducing the one-stop code flows we overwritten some of the recovery flow logic.
- This reintroduces/cleans this logic
- Verified locally all code flows work + all signups work
=> fix: recovery flow

packages/shared/src/components/profile/ProfileButton.tsx, packages/webapp/__tests__/MainLayout.tsx
- Sorry I can't take it anymore, I am being bothered by the flickering profile button on the header 😅 
- There seems to be an issue with our legacy lazy loading component.
- For context: we are moving away from it, and trying to utilize the native lazy loading feature.
Deployed at preview: https://preview.app.daily.dev/
=> fix: profile button flicker

packages/webapp/components/FooterNavBar.tsx
- Not the biggest fan of the fix, but apparently brave injects this user agent styling:
=> fix: ensure footer renders on brave browser

packages/shared/src/components/modals/streaks/NewStreakModal.tsx, packages/shared/src/components/modals/streaks/common.ts, packages/shared/src/hooks/streaks/useStreakMilestone.ts
New streak record modal is shown whenever the currentStreak >= maxStreak
MI-192 #done
=> fix: change condition to show streak record modal

packages/shared/src/components/sidebar/SidebarBottomSection.tsx, packages/webapp/pages/[userId]/index.tsx
<table>
<tr>
<td>Before
<td>After
<tr>
<td><img src="https://github.com/dailydotdev/apps/assets/1681525/c61b2f5e-9cfa-46be-b8a4-92a39367494f">
<td><img src=https://github.com/dailydotdev/apps/assets/1681525/b4024b9e-99c2-4fb3-b7e6-0abcdb2faf70>
</table>
- Hides the old rank progress from sidebar if part of streaks experiment
- Hides the old rank progress from profile page if part of streaks experiment
MI-196
=> fix: hide old rank progress if we show reading streak

packages/shared/src/hooks/useActions.ts
On logout (or if actions failed to fetch for any reason) the `isFetched` would be `true`. Which would mean logic that relies on actions being fetched so it can use `checkHasCompleted` would get falsy value which would then trigger any kind of logic as if action was not completed.
Example on reputation popup:
- user gets logged out
- after logout redirect actions still get to be fetched once (they fail because user is no longer authenticated)
- query is in error state but isFetched is true (because query did fetch once, no matter if it failed or not)
- logic checks `ack_rep_250` was completed, gets falsy and shows the modal
Fix uses `isLoading` instead of `isFetched` because `state.loading` for `useQuery` makes sure that query was once fetched succesfully or has cached data. 
I think …
=> fix: use loading state instead of fetched to handle error state

packages/shared/src/components/modals/streaks/NewStreakModal.tsx
- Fixed pluralisation of `days`
- Fixed typo in `in a league`
<table>
<tr>
<td>Before
<td>After
<tr>
<td>
<td>
</table>
MI-199
=> fix: pluralisation of `day`

packages/shared/src/components/streak/popup/DayStreak.tsx, packages/shared/src/components/tooltips/SimpleTooltip.tsx
- Added tooltips for weekend days
MI-194
=> fix: add missing tooltip for weekend days

packages/shared/src/components/streak/ReadingStreakButton.tsx
- in other words, if their streak is active
n / a
MI-193 #done
=> fix: use the correct icon if the user has read an article today

packages/shared/src/components/layout/HeaderLogo.tsx, packages/shared/src/components/layout/MainLayoutHeader.tsx, packages/shared/src/components/post/write/CreatePostButton.tsx, packages/shared/src/components/streak/ReadingStreakButton.tsx
| small streak | large streak |
| ------------ | ------------ |
| <img width="392" alt="Screenshot 2024-03-03 at 14 07 55" src="https://github.com/dailydotdev/apps/assets/1225100/64f78124-e3a1-4b72-98e4-706c1566401f"> |  <img width="392" alt="Screenshot 2024-03-03 at 14 08 38" src="https://github.com/dailydotdev/apps/assets/1225100/98c4bc9b-8f29-4107-93c8-b777925182c9">
|
N / A
MI-198 #done
=> fix: adjust mobile layout as per design when streaks are enabled

packages/shared/src/components/cards/PostMetadata.tsx, packages/shared/src/components/cards/common/SquadPostCardHeader.tsx, packages/shared/src/components/comments/CommentAuthor.tsx, packages/shared/src/components/comments/CommentBox.tsx, packages/shared/src/components/post/SquadPostAuthor.tsx, packages/shared/src/components/profile/ProfileLink.tsx, packages/shared/src/components/profile/UserMetadata.tsx, packages/shared/src/components/profile/UserShortInfo.tsx, packages/shared/src/components/utilities/common.tsx, packages/webapp/pages/account/invite.tsx
Truncates the really long user names and handles wherever I found them. There might still be places where I have not encountered them.
<table>
<tr>
<td>Before
<td>After
<tr>
<td>
<td>
</table>
AS-151
=> fix: truncate usernames in comment boxes

packages/shared/src/components/cards/AcquisitionFormCard.tsx
- Apply the correct background color and top margin when on mobile. Discussion: https://dailydotdev.slack.com/archives/C06CLJV4NFL/p1709641497119569
Preview:
=> fix: acquisition form card on mobile layout

packages/shared/src/components/cards/ShowMoreContent.tsx
- We need to overwrite to link color as there's a default color
- We already check manually if tag == A, but in this case it's not.
=> fix: right blue color for link

packages/shared/src/graphql/feed.ts
Sends the `refresh` variable into the query to be used, and not just as a variable added in #2728
=> fix: send refresh into the feed query

packages/shared/src/components/streak/ReadingStreakButton.tsx
- by default tooltips are disabled on mobile
=> fix: force the streaks tooltip to be displayed on mobile resolutions

packages/shared/src/components/post/SquadPostContent.tsx, packages/shared/src/components/profile/UserShortInfo.tsx
- fix overflow issue in upvoted modal
- fix overflow issue on public squad post page and modal
<table>
<tr>
<td>Before
<td>After
<tr>
<td>
<td>
</table>
=> fix: overflow on public squad post page and upvote modal

packages/shared/src/lib/analytics.ts, packages/webapp/pages/404.tsx
- Requested by Dave
|New | 404 page  |  |
=> fix: add tracking event for 404 page

packages/webapp/components/PostSEOSchema.tsx
- Since we only have youtubevideos we can simply use the pattern youtube embed URLs
Validated:
MI-207 #done
=> fix: add embedURL to youtube videos

packages/shared/src/components/image/Image.tsx
- The final fallback src was not used.
=> fix: final fallback image

packages/shared/src/components/notifications/NotificationItemAttachment.tsx
- With introducion of CardCover which has `h-40` this case would take `h-40` not the set `h-16` (Same for border)
@sshanzel I see you also [did](https://github.com/dailydotdev/apps/commit/46efc2bd2badd55f7c81828e09ac17abd39a63ab#diff-2bf1ebec09bd7c77dae66efcdb5eb936257ce95cf0bb79a5c27ea889018bc8f3L36) this on `SharedPostCardFooter` here luckily `h-auto` will take priority. Are there any edge-cases you can think of though?
=> fix: notification image size override

packages/shared/src/components/squads/SquadFeedHeading.tsx
- hide pinned posts button on squad page if they are not a member
<table>
<tr>
<td>Before
<td>After
<tr>
<td><img src="https://github.com/dailydotdev/apps/assets/1681525/08e8f2a6-9621-445d-9393-3cc44170a0ba">
<td><img src="https://github.com/dailydotdev/apps/assets/1681525/0a4d7676-996a-4212-b908-ea826e7a57b7">
</table>
AS-159
=> fix: don't show pinned posts if not a member

packages/shared/src/components/cards/SharedPostCardFooter.tsx
- By adding `flex` - we override the `display: -webkit-box` from the `line-clamp-*`.
- Removed flex to make the class work.
- Also changed the div to p to be semantically correct.
Quick link: https://preview3.app.daily.dev/squads/rustdevs
Preview:
MI-208 #done
=> fix: shared post card long lines

packages/shared/src/components/post/SquadPostContent.tsx
Discovered while fixing some other overflow issues that the padding of the widgets for public squad posts didn't match the normal posts. [Conferred with design that it should be 16px](https://dailydotdev.slack.com/archives/C01L0QXQJNB/p1709715348049359?thread_ts=1709659937.401039&cid=C01L0QXQJNB)
- fixed sidebar widgets for squad posts to be more consistent
<table>
<tr>
<td>Before
<td>After
<tr>
<td><img src="https://github.com/dailydotdev/apps/assets/1681525/e22333a4-a520-42bf-80f2-a76b444f998d">
<td><img src="https://github.com/dailydotdev/apps/assets/1681525/cdc53db0-aa77-4f8b-a1a0-fd72d2a77e17">
</table>
=> fix: padding consistency of squad sidebar widgets

packages/shared/src/components/streak/popup/ReadingStreakPopup.tsx
- Removal of background for total reading days.
=> fix: total reading days ui

packages/shared/src/components/Pill.tsx, packages/shared/src/components/post/collection/CollectionPostContent.tsx
- Make the collection pill on page clickable
AS-162 #done
=> fix: make collection tag clickable

packages/shared/src/components/layout/MainLayoutHeader.tsx
- Conditionally render the component so that when it is not enabled, we won't show even the loading state.
Preview:
=> fix: streaks placeholder

packages/shared/src/components/PostOptionsMenu.tsx, packages/shared/src/components/drawers/ListDrawer.tsx, packages/shared/src/components/drawers/ListDrawerItem.tsx
- Refactor the post options menu to utilize the drawer component on mobile.
Preview:
https://github.com/dailydotdev/apps/assets/13744167/280070e8-9661-4401-b682-569076901b93
MI-127 #done
=> refactor: post options menu to utilize drawer on mobile

packages/shared/src/components/PostOptionsMenu.tsx, packages/shared/src/components/drawers/ContextMenuDrawer.tsx, packages/shared/src/components/drawers/Drawer.tsx, packages/shared/src/components/drawers/ListDrawer.tsx, packages/shared/src/components/drawers/ListDrawerItem.tsx, packages/shared/src/components/drawers/common.ts, packages/shared/src/components/fields/Dropdown.tsx, packages/storybook/stories/drawers/ListDrawer.stories.tsx
- Drawer component for lists. Mostly utilized on mobile only (for now).
- Feel free to check the storybook component.
- For some reason, their array control is not working, had to make it comma-separated.
Preview:
https://github.com/dailydotdev/apps/assets/13744167/16e11181-e8d2-439c-830d-1e35ef7efd74
MI-125 #done
=> feat: new list drawer component

packages/extension/src/newtab/dnd.ts
- Not really sure when this changed, can't really find any documentation on this matter 🤯
=> fix: new default URL

packages/shared/src/components/ShareBar.spec.tsx, packages/shared/src/components/ShareBar.tsx, packages/shared/src/components/ShareOptionsMenu.tsx, packages/shared/src/components/modals/ShareModal.spec.tsx, packages/shared/src/components/profile/Header.tsx, packages/shared/src/components/widgets/SocialShare.tsx, packages/shared/src/components/widgets/SocialShareList.tsx, packages/shared/src/graphql/urlShortener.ts, packages/shared/src/hooks/index.ts, packages/shared/src/hooks/referral/useReferralCampaign.ts, packages/shared/src/hooks/useShareComment.ts, packages/shared/src/hooks/useShareOrCopyLink.ts, packages/shared/src/hooks/useSharePost.ts, packages/shared/src/hooks/useSquadInvitation.ts, packages/shared/src/hooks/utils/useGetShortUrl.ts, packages/shared/src/lib/query.ts, packages/shared/src/lib/referral.ts, packages/shared/src/lib/share.spec.ts, packages/shared/src/lib/share.ts, packages/webapp/pages/[userId]/index.tsx, packages/webapp/pages/account/invite.tsx, packages/webapp/pages/join.tsx
Adds `userId` and `cid` query params to all shared URLs.
Minifies the URL before sharing.
Modifies `copyLink` to send the same URL as well, in case `copyLink` feature flag is on. 
MI-188 #done
=> feat: add share tracking URL query parameters and shorten the links

packages/shared/src/components/post/FixedPostNavigation.tsx, packages/shared/src/components/post/PostContent.tsx, packages/shared/src/components/post/PostMenuOptions.tsx, packages/shared/src/components/post/PostNavigation.tsx, packages/shared/src/components/post/common.tsx
- Fix duplicated post context menu.
- Fix on hide to set the state.
=> fix: post options menu multiple instances

packages/shared/src/components/post/collection/CollectionSubscribeButton.tsx, packages/shared/src/lib/auth.ts
- Just waiting for confirmation from analytics team [here](https://dailydotdev.slack.com/archives/C015T1Y237Z/p1709901184845719)
| Change | open signup  | extra: { trigger: 'collection subscribe' } |
AS-173 #done
=> fix: add login trigger to subscribe button

packages/shared/src/components/squads/SquadHeaderMenu.tsx
- We shouldn't render this item if you're not a user
AS-174 #done
=> fix: don't render item if you not a member

packages/shared/src/components/cards/AcquisitionFormCard.tsx
The bottom border should not appear on the card. Switched to using CardV1 on mobile instead.
MI-188 #done
=> fix: acquisition card visuals on mobile

packages/shared/src/hooks/utils/useGetShortUrl.ts
This is my own doing, used the `generateQueryKey` function, but did not provide the user parameter. Which resulted in query keys being generated for `"anonymous"`, even though we only generate it for logged in users. Using the user ID there actually makes more sense, especially when debugging react query.
=> fix: use user instead of anonymous to generate short_url query key

packages/shared/src/components/cards/Card.tsx, packages/shared/src/components/cards/v1/Card.tsx
- Fix the height of card cover images across mobile screen sizes.
Previews:
=> fix: card cover image

packages/shared/src/components/filters/MyFeedHeading.tsx
- add loading state while refreshing
- make sure loading state is not displayed first time the feed is fetching
AS-179 #done
=> feat: add loading state while feed is refreshing

packages/shared/src/components/cards/SimilarPosts/SidePost.tsx, packages/shared/src/hooks/post/usePostImage.ts
- Fix the image to use when the recommended image is a shared post.
Deployed at preview: 
=> fix: recommended image for squad post

packages/shared/src/hooks/post/usePostImage.ts
- Prioritize usage of shared post image over the post.image since the post.image falls back to the default image if API finds out it is empty.
=> fix: image prioritization order

packages/shared/src/components/MainFeedLayout.tsx, packages/shared/src/components/PostsSearch.tsx, packages/shared/src/graphql/feed.ts, packages/shared/src/graphql/search.ts, packages/shared/src/hooks/search/useSearchProvider.spec.tsx, packages/shared/src/hooks/search/useSearchProvider.ts, packages/shared/src/hooks/search/useSearchProviderSuggestions.spec.tsx, packages/shared/src/lib/featureManagement.ts
- Option to experiment with different search versions
=> fix: enable switching of search via gb

packages/shared/src/components/cards/v1/Card.tsx, packages/shared/src/components/cards/v1/SharedPostCardFooter.tsx
- From Figma, the title and image should be side by side on mobile XL.
- https://www.figma.com/file/nmfWPS7x3kzLUvYMkBx2kW/daily.dev---Dev-Mode?node-id=2681%3A18553&mode=dev
=> fix: mobile xl

packages/shared/src/components/utilities/DateFormat.spec.tsx
- Noticed that due to relative time we can have flaky date format tests, [see test runs](https://app.circleci.com/pipelines/github/dailydotdev/apps?branch=experiments-helpers-story)
- For example if it is `01:00` subtracting 2 hours from current hours makes it `-1` which then makes `should render post time format as today` fail 
=> fix: flaky date format tests

packages/shared/src/components/widgets/SocialShareList.tsx, packages/shared/src/styles/base.css, packages/shared/tailwind.config.ts
- Chatted to Tsahi and this was actually a wrong color, should just be primary button color.
=> fix: remove email color option

packages/shared/src/styles/base.css, packages/shared/tailwind.config.ts, packages/webapp/pages/popup/notifications/enable.tsx
- Chatted to Tsahi and he's happy having it as this color variant. *(instead of the 60% opacity of 90 it was)
=> fix: remove cabbage blur color

packages/shared/src/components/FeedItemComponent.tsx, packages/shared/src/components/Pill.tsx, packages/shared/src/components/cards/MarketingCTA/MarketingCTACard.tsx, packages/shared/src/components/cards/MarketingCTA/MarketingCTAList.tsx, packages/shared/src/components/cards/MarketingCTA/common.tsx, packages/shared/src/components/cards/MarketingCTA/index.tsx, packages/shared/src/components/cards/index.ts, packages/shared/src/hooks/useFeed.ts
- Added the marketing card (split up the tasks so they smaller to review)
Card:
List:
Mobile:
You can add the following in useFeed to enable it locally.
```js
posts.splice(0, 0, {
variant: 'marketingCTA',
marketingCTA: {
type: 'card',
tagText: 'New release',
tagColor: 'avocado',
title: 'Introducing the Daily.dev browser extension',
description:
'Get the latest dev news and articles right in your browser.',
ctaUrl:
'https://chrome.google.com/webstore/detail/dailydev/hkngfbomfjfgbkejgjhgkemfkegjgjai',
ctaText: 'Install now',
image:
'https://res.cloudinary.com/daily-now/image/upload/f_auto,q_auto/v1/posts/156488021afcf2237083924ab90b5469?_a=AQAEufR',
},
});
``` …
=> fix: add marketing CTA card component

packages/shared/src/hooks/usePostMenuActions.ts
- Only members that can pin should be able to move pinned post ordering
AS-188 #done
=> fix: only members with allowPin can move pins

packages/shared/src/components/fields/MarkdownInput/SavingLabel.tsx, packages/shared/src/components/tabs/TabList.tsx
- The tablist had different padding then design intented
- We changed the saving text to be more minimal (@sshanzel I actually noticed we don't really use the `isUpdatingDraft` in many places, so not showing the `Saving` text was this known/intented?)
AS-189 #done
=> fix: minor spacing issues and spacing for mobile

packages/shared/src/components/tabs/TabContainer.spec.tsx, packages/shared/src/components/tabs/TabContainer.tsx
- adding a `url` prop to tabs
- trigger router navigation if tabs have urls
N / A
MI-136 #done
=> feat: update tabs components to work with URLs as well

packages/shared/src/components/buttons/Button.tsx, packages/shared/src/components/buttons/common.ts, packages/shared/src/components/drawers/Drawer.tsx, packages/shared/src/components/drawers/NavDrawer.tsx, packages/shared/src/components/drawers/NavDrawerItem.tsx, packages/shared/src/components/profile/Header.tsx, packages/shared/tailwind/buttons.ts, packages/storybook/stories/Button.stories.tsx, packages/storybook/stories/drawers/NavDrawer.stories.tsx
The `NavDrawer` is needed for implementing [Profile settings on mobile](https://www.figma.com/file/nmfWPS7x3kzLUvYMkBx2kW/daily.dev---Dev-Mode?node-id=999%3A2766&mode=dev) and probably some other parts I'm not aware off yet. Splitting it into it's own PR to make it easier to reuse in case others need it.
- Added `NavDrawer` component that reuses `Drawer` and adds some styling on top of it
- Added `NavDrawer` storybook
The component is not used anywhere, just in storybook for now.
MI-131 #done
=> feat: add navigation drawer

packages/shared/src/components/modals/ArticlePostModal.tsx, packages/shared/src/components/modals/CollectionPostModal.tsx, packages/shared/src/components/modals/SharePostModal.tsx, packages/shared/src/components/post/PostComments.tsx, packages/shared/src/hooks/usePostById.ts, packages/webapp/pages/posts/[id]/edit.tsx, packages/webapp/pages/posts/[id]/index.tsx
- I see we removed the `isLoading` state [https://github.com/dailydotdev/apps/commit/1d055018a4766bbe30cc0288a4da48eb31ff8824#diff-870e4cc6ee5c55dc1cb1004be[…]b31b354338ae02002a477637d1b9R32](https://github.com/dailydotdev/apps/commit/1d055018a4766bbe30cc0288a4da48eb31ff8824#diff-870e4cc6ee5c55dc1cb1004be92b1ef0237db31b354338ae02002a477637d1b9R32).
- Making it only work if cache for post would exist (so second open)
- Can't really backtrack the need, so decided to reimplement as intended before. (@DragosIorgulescu in case you know) …
=> fix: bring back post modal scroll header

packages/shared/src/components/Markdown.tsx, packages/shared/src/components/modals/ArticlePostModal.tsx, packages/shared/src/components/modals/CollectionPostModal.tsx, packages/shared/src/components/modals/SharePostModal.tsx, packages/shared/src/hooks/usePostNavigationPosition.ts, packages/shared/src/hooks/useScrollTopOffset.ts
- We actually had some race-condition that before wasn't as prominent due to 3 evaluations extra
- It now showed clearly by cleaning the code
- Also removed a unneeded useEffect and state manipulation in favor of existing `onAfterOpen` from the modal
=> fix: optimize scroll position and dependency links

packages/shared/src/components/post/SharePostContent.tsx, packages/shared/src/components/post/ShareYouTubeContent.tsx
- Just the temp fix to not render these if sharedPost is not available yet (SSR render)
- This ideally needs to render the placeholder (will do this separate tomorrow)
=> fix: don't render shared post if not loaded

packages/shared/src/components/post/common/PostContentShare.tsx
- On mobile, we need to display the copy link input and button vertically.
=> fix: copy link on mobile

packages/shared/src/components/notifications/EnableNotification.tsx, packages/shared/src/components/widgets/PostUsersHighlights.tsx, packages/shared/src/lib/analytics.ts
- Offer to subscribe to push notifications after source subscribe
- Available to test on [preview](https://preview2.app.daily.dev/)
Offer:
Subscribed:
AS-154 #done
=> feat: source subscribe push notifications

packages/shared/src/components/modals/SharePostModal.tsx, packages/shared/src/components/post/SquadPostContent.tsx, packages/shared/src/components/post/SquadPostWidgets.tsx
- In prep for the placeholders I decided to tackle this first else it be double work.
- We needed to add the sidebar to all squad post to make a uniform behaviour.
- Minus the share as it's pointless to share private squad posts
AS-195 #done
=> fix: add sidebar to private squad so it's uniform

packages/shared/src/components/PostOptionsMenu.tsx, packages/shared/src/components/drawers/ContextMenuDrawer.tsx, packages/shared/src/components/fields/PortalMenu.tsx, packages/shared/src/components/post/PostHeaderActions.tsx
- Fix allocations
- no longer allocates on feeds when post options container renders invisible, it only allocates if menu is open by user
- no longer allocates on other post types from read button
- No longer show subscribe options for squads since they have their own subscription from squad notification settings
=> feat: do not show squads and adjust allocations

packages/shared/src/components/search/SearchPanel/SearchPanel.tsx, packages/shared/src/components/search/SearchPanel/SearchPanelAction.tsx
Track search submit:
- when using provider actions
- when using "See more posts"
=> fix: add submit search tracking to panel actions

packages/shared/src/components/auth/OnboardingAnalytics.tsx, packages/webapp/pages/onboarding.tsx, packages/webapp/public/scripts/twitter.js
Request to add twitter tracking on onboarding just as we did for gtag and fb.
Slack message here: https://dailydotdev.slack.com/archives/C038JGDR2JK/p1710745205293519
=> feat: add twitter tracking to onboarding

packages/shared/src/components/PostOptionsMenu.tsx
- We now fetch notification preference on post pages with source subscribe experiment
- This avoid fetching it for squad posts which don't have the option in the first place
=> fix: do not fetch notification preference on squad post options

packages/shared/src/components/ScrollToTopButton.tsx
=> fix: scroll to top button size on mobile

packages/shared/src/components/fields/form/FormWrapper.tsx, packages/shared/src/components/modals/NewSourceModal.tsx, packages/shared/src/components/modals/SubmitArticleModal.tsx, packages/shared/src/components/modals/common/Modal.tsx, packages/shared/src/components/modals/common/ModalBody.tsx, packages/shared/src/components/modals/common/ModalFooter.tsx, packages/shared/src/components/modals/common/ModalHeader.tsx, packages/shared/src/components/modals/common/types.ts, packages/shared/src/components/modals/post/CreateSharedPostModal.tsx
- Wrap the Modal with form buttons when it is an action modal (definition from design team).
- Wrap New Source Modal.
- Wrap Submit Article Modal.
Previews:
MI-227 #done
=> refactor: submit article and new source modal to be wrapped in a form

packages/shared/src/components/modals/UserListModal.tsx
- Fix the spacing on upvote modal.
=> fix: upvote modal spacing

packages/shared/src/components/modals/Prompt.tsx
- Use Drawer on mobile for the prompt. Should also make the buttons max width on mobile.
=> fix: prompt by using drawer on mobile

packages/shared/src/components/squads/SquadMemberShortList.tsx
Fixes something that has annoyed me for ages. The height changes on the squad member list button once images have been loaded.
<table>
<tr>
<td>Before
<td><img src="https://github.com/dailydotdev/apps/assets/1681525/e469c798-d728-4b8b-b7b9-d17ee2820b94">
<tr>
<td>After
<td><img src="https://github.com/dailydotdev/apps/assets/1681525/187c660b-8d29-4627-9ef1-8bdd70def64d">
</table>
=> fix: height change of squad member list button when images are loaded

packages/shared/src/components/modals/common/Modal.tsx
- There is currently no distinction between at the time of closing and after close in our Drawer. Hence, executing both.
=> fix: after close modal

packages/shared/src/components/sidebar/DiscoverSection.tsx
- Since we don't wait for isActionsFetched it would always flash the new badge quickly.
- Decided to add this as raised [here](https://dailydotdev.slack.com/archives/C06LMML6A8N/p1711120684667839?thread_ts=1711120611.841409&cid=C06LMML6A8N). 
- Maybe we should actually add it to the default of `checkHasCompleted`? (not really sure though)
https://fix-new-flash.preview.app.daily.dev
=> fix: prevent flash of new

packages/shared/src/graphql/search.ts
- This endpoint doesn't have version, must have missed this in my implementation
https://hotfix-remove-version-search-session.preview.app.daily.dev
=> fix: accidently added version to this query

packages/shared/src/components/drawers/Drawer.tsx, packages/shared/src/components/drawers/ListDrawer.tsx, packages/shared/src/components/drawers/ListDrawerItem.tsx, packages/shared/src/components/fields/Dropdown.tsx, packages/shared/src/components/post/write/SquadsDropdown.tsx, packages/shared/src/components/profile/source/SourceShortInfo.tsx
- The dropdown for selecting Squads behave differently and should use the fullscreen as opposed to most of our dropdowns.
P.S. not a fan.
https://fix-squads-dropdown.preview.app.daily.dev
=> fix: squads dropdown

packages/shared/src/components/post/PostContentHeaderMobile.tsx
- The back button should purely act as the history back button.
- Thread: https://dailydotdev.slack.com/archives/C0650M2KX8E/p1711444583148789?thread_ts=1711372461.259189&cid=C0650M2KX8E
https://fix-navigation.preview.app.daily.dev
=> fix: go back navigation

packages/extension/src/background/index.ts
I noticed that the companion sends boot requests when you visit the webapp because we check for `http` protocol instead of `https`
https://ext-ignore-webapp.preview.app.daily.dev
=> fix: correctly ignore webapp for companion boot

packages/shared/src/hooks/useConditionalFeature.ts
- We had a small issue with onboarding if you where in the experiment, then complete onboarding the `shouldEvaluate` becomes false, but it would not retrigger unless you did a hard refresh on the page.
- This introduces a second trigger to always return false when already evaluated and this value changes
https://fix-second-eval-fix.preview.app.daily.dev
=> fix: second evaluation would have cache

packages/shared/src/components/onboarding/FilterOnboarding.tsx, packages/shared/src/components/onboarding/FilterOnboardingV4.tsx, packages/shared/src/components/onboarding/OnboardingFeedHeader.tsx
- In forced tag selection we wan't to make sure users follow the picking of 5 tags before they can get enrolled in my feed alert.
- Do note they actually get assigned the tags, but only get my feed trigger once they click the button 
https://fix-should-update-optional.preview.app.daily.dev
=> fix: in forced tag selection we shouldn't auto update

packages/webapp/components/FooterNavBar.tsx
- set the new navigation tabs behind a feature flag
- https://dailydotdev.slack.com/archives/C0650M2KX8E/p1711691923737429
https://130-footer-mobile-behind-feature-flag.preview.app.daily.dev
=> fix: add back previous footer nav items on mobile

packages/shared/src/components/feeds/FeedContainer.tsx, packages/shared/src/components/feeds/FeedNav.tsx, packages/shared/src/components/layout/common.tsx, packages/shared/src/components/notifications/NotificationsBell.tsx
Fixes the following:
---
---
---
---
N / A
MI-252
https://mi-252-mobile-layout-fixes.preview.app.daily.dev
=> fix: mobile ux layout fixes

packages/shared/src/components/layout/MainLayoutHeader.tsx
- adds back the search bar on mobile/tablet with the new layout
---
---
N / A
MI-252
https://mi-252-add-search-panel-to-search-mobile.preview.app.daily.dev
=> fix: render search bar on the new mobile layout

packages/shared/src/components/FeedSelector.tsx, packages/shared/src/components/layout/common.tsx
add close button to sort drawer and feed selector
MI-245 #done
https://mi-245-sort-drawer.preview.app.daily.dev
=> fix: add close button to sort drawer and feed selector

packages/shared/src/components/comments/CommentInputPage.tsx, packages/shared/src/components/fields/MarkdownInput/CommentMarkdownInput.tsx, packages/shared/src/hooks/post/useMutateComment.ts
- The primary reason it was not working out of the box was, that there are two instances of the `useCommentHook` and they have their states that manage whether the mutation is loading or done. Even though we have two instances, they are basically the same thing (same result and same props).
- It was just a matter of placement where the button for submission was rendered that made the difference and required two instances.
- To avoid having multiple separate states, we will just pass the ref of the hook being utilized. Otherwise, we will have to introduce a local state and send callbacks to monitor the submission of the form.
Don't forget to update the [Analytics Taxonomy sheet](https://docs.google.com/spreadsheets/d/18Lv7zXges9QfVX5VYL1a-Hyl0e1sQ3 …
=> fix: cmd/ctrl + enter to submit a comment

packages/shared/src/components/post/write/CreatePostButton.tsx, packages/webapp/components/FooterNavBar.tsx, packages/webapp/pages/squads/create.tsx
- the drawer is triggered only on mobile and when we are on the new mobile UX implementation
---
https://github.com/dailydotdev/apps/assets/1225100/c2f2d67f-617f-4f1c-84d5-5721e4f7192b
---
N / A
MI-252
https://mi-252-mobile-main-action-drawer.preview.app.daily.dev
=> feat: add a drawer selector on the mobile main footer action

packages/shared/src/components/profile/Header.tsx, packages/shared/src/components/profile/ProfileWidgets.tsx, packages/shared/src/components/profile/SocialChips.tsx, packages/shared/src/components/profile/SquadsList.tsx, packages/webapp/components/layouts/ProfileLayout/NavBar.tsx, packages/webapp/components/layouts/ProfileLayout/index.tsx
- bring gear icon in profile tablet
- make profile look like in mobile when in tablet
- open the menu like in mobile when clicking gear button in tablet
This ticket is done based on what was requested in title. 
I noticed that now after opening the new menu with gear like in mobile - if we click on the options, they do not behave like in mobile (customisation is open in a small modal not a full screen one). 
Personally think everything should open like in mobile from that menu, but would suggest also to check with product if we want everything to open like in mobile on that menu. 
Log the …
=> Mi 246 profile page

packages/shared/src/components/modals/NewSourceModal.tsx, packages/shared/src/components/squads/Details.tsx, packages/webapp/pages/squads/[handle]/edit.tsx, packages/webapp/pages/squads/new.tsx
- Add the missing title for the new source modal.
- Squad writing must be wrapped in form actions.
- Also fixed the uncentered image on mobile (first screenshot).
https://github.com/dailydotdev/apps/assets/13744167/e3d38d2b-c8fe-482b-8269-ec099b350e36
MI-251 #done
=> fix: new source and squad writing form issues

packages/shared/src/components/CommentFeed.tsx, packages/shared/src/components/MainFeedLayout.tsx, packages/shared/src/components/sidebar/Sidebar.tsx
=> fix: adjust discussed feed styles to match new mobile UX

packages/shared/src/components/feeds/FeedNav.tsx, packages/shared/src/components/sidebar/Sidebar.tsx, packages/shared/src/hooks/useActiveNav.tsx, packages/webapp/components/FooterNavBar.tsx
- adding a new hook to be used on the sidebar and feed nav as well
https://github.com/dailydotdev/apps/assets/1225100/550980a1-bf1b-4e69-a19b-8c6c1bbfef32
N / A
MI-259 #done
https://mi-259-footer-nav-active-states.preview.app.daily.dev
=> fix: refactor active states on mobile footer nav

packages/shared/src/components/comments/CommentInputOrPage.tsx, packages/shared/src/components/comments/CommentInputPage.tsx, packages/shared/src/components/fields/MarkdownInput/CommentMarkdownInput.tsx, packages/shared/src/contexts/WriteCommentContext.ts, packages/shared/src/hooks/post/useMutateComment.ts
- The reference was missing. Tested locally.
https://fix-making-comment.preview.app.daily.dev
=> fix: making a comment through header actions

packages/shared/src/components/checklist/SquadChecklistCard.tsx, packages/webapp/pages/account/others.tsx
- Fix missing close buttons of: timezone, feed options, and squad checklist.
Previews:
https://fix-close-buttons.preview.app.daily.dev
=> fix: missing close buttons

packages/shared/src/components/feeds/FeedNav.tsx, packages/shared/src/components/fields/Dropdown.tsx, packages/shared/src/components/filters/MyFeedHeading.tsx, packages/shared/src/components/layout/common.tsx, packages/shared/src/components/streak/ReadingStreakButton.tsx
---
---
N / A
MI-261 #done
https://mi-261-layout-action-buttons.preview.app.daily.dev
=> fix: use tertiary variant for feed action buttons on mobile

packages/shared/src/components/auth/CustomAuthBanner.tsx, packages/shared/src/components/sidebar/Sidebar.tsx, packages/webapp/components/layouts/ProfileLayout/index.tsx, packages/webapp/pages/account/profile.tsx, packages/webapp/pages/posts/[id]/index.tsx, packages/webapp/pages/squads/index.tsx
- extract out the banner component into the shared lib
src="https://github.com/dailydotdev/apps/assets/1225100/5bb98a59-fcbc-44af-a606-2f8717172f37">
---
N / A
MI-243 #done
https://mi-243-anonymous-top-banner.preview.app.daily.dev
=> feat: add auth banner to profile & squad pages

packages/shared/src/components/streak/ReadingStreakButton.tsx, packages/shared/src/components/streak/popup/ReadingStreakPopup.tsx
---
---
N / A
MI-267 #done
https://mi-267-streaks-drawer-mobile.preview.app.daily.dev
=> feat: use a drawer for the streaks tooltip on mobile

packages/shared/src/components/post/write/CreatePostButton.tsx, packages/webapp/components/FooterNavBar.tsx
N / A
MI-265 #done
https://mi-265-footer-nav-anon-user.preview.app.daily.dev
=> fix: add all nav items to the footer even for anon users

packages/webapp/components/FooterNavBar.tsx, packages/webapp/components/layouts/FooterNavBarLayout.tsx
Made the bottom navbar `fixed` instead of `sticky`. This reverts to previous behavior.
- N/A Have you done sanity checks in the extension?
- N/A Does this not break anything in companion?
MI-274 #done
https://mi-274-make-bottom-navbar-fixed-again.preview.app.daily.dev
=> mobile-ux: fix: bottom navbar position:fixed instead of sticky

packages/shared/src/components/comments/CommentContainer.tsx
- @kopancek I think with the addition of parent to global comment we broke this.
- Added conditional author check now to ensure rendering
- Solves: https://github.com/dailydotdev/daily/issues/1108
https://hotfix-reply-feed.preview.app.daily.dev
=> fix: reply feed author not existing

packages/shared/src/components/modals/post/CommentModal.tsx, packages/shared/src/graphql/comments.ts, packages/shared/src/graphql/fragments.ts
We originally added more fields to facilitate comment modal dialog. However we can get the same data by querying comment by Id when the modal itself is opened instead. That way, we do not unnecessary query fields, that we don't need to have most of the time.
See comments on the original PR:
- https://github.com/dailydotdev/apps/pull/2912#discussion_r1550978383
- https://github.com/dailydotdev/apps/pull/2912#discussion_r1550979025
https://chore-graphql-comment-fields.preview.app.daily.dev
=> chore: reduce number of fields we fetch for post comments

packages/webapp/pages/posts/[id]/index.tsx
- `query.id` was actually slug when accessing new slug URL for post page which would then propagate invalid id for stuff like vote mutations
https://fix-correct-post-id.preview.app.daily.dev
=> fix: always pass post id as ssr prop

packages/webapp/cache.js, packages/webapp/next.config.js
- Do not precache syntax highlighter chunks with [buildExcludes](https://github.com/shadowwalker/next-pwa?tab=readme-ov-file#:~:text=buildExcludes%20%2D%20an%20array%20of%20extra%20pattern%20or%20function%20to%20exclude%20files%20from%20being%20precached)
Before:
After:
https://fix-pwa-syntax-highlighter.preview.app.daily.dev
=> feat: ignore syntax highlighter assets in pwa

packages/shared/src/components/profile/ProfileSettingsMenu.tsx, packages/webapp/components/footer/FooterPlusButton.tsx
- Move the capacity to open the submit article modal to the plus button on the footer.
MI-269 #done
https://mi-269.preview.app.daily.dev
=> fix: missing submit article modal button

packages/shared/src/components/modals/common/Modal.tsx
- Since on mobile, all Modals are on full-screen, we don't need the borders on mobile anymore.
https://fix-unnecessary-border.preview.app.daily.dev
=> fix: unnecessary border

packages/webapp/components/footer/FooterPlusButton.tsx
- When opening the submit article screen, we should close the drawer.
=> fix: close drawer after clicking

packages/shared/src/hooks/utils/useThemedAsset.ts, packages/webapp/pages/_app.tsx
- Removed meta tags that were only useful for Internet Explorer or Windows 8 (both unsupported anymore)
- Changed the value of theme-color meta tag to reflect the selected theme default background color
MI-275 #done
https://mobile-ux-status-bar-color.preview.app.daily.dev
=> feat: change status bar background based on theme color

packages/webapp/components/FooterNavBar.tsx, packages/webapp/components/footer/FooterNavBarV1.tsx
- The fix here is very similar to the previous one, but the core issue was where we placed the padding. In here we put it on the actual main container.
MI-256 #done
https://mi-256-padding.preview.app.daily.dev
=> fix: footer navbar spacing

packages/webapp/components/FooterNavBar.tsx, packages/webapp/components/footer/FooterNavBarV1.tsx
Checked on actual mobile, it displays differently from web mobile 😞 
https://revert-2944-mi-256-padding.preview.app.daily.dev
=> Revert "fix: footer navbar spacing"

packages/webapp/pages/posts/[id]/index.tsx
Similar to https://github.com/dailydotdev/apps/pull/2940 the `id` passed in case of forbidden error from API was actually slug. `extensions.postId` was added to API to allow frontend to query it once it knows the user and its access.
https://github.com/dailydotdev/daily-api/pull/1811
https://fix-private-post-id.preview.app.daily.dev
=> fix: pass correct post id from forbidden error

packages/shared/src/components/cards/ArticlePostCard.tsx, packages/shared/src/components/cards/Card.tsx, packages/shared/src/components/cards/CollectionCard/CollectionCard.tsx, packages/shared/src/components/cards/PostTags.tsx, packages/shared/src/components/cards/v1/ArticlePostCard.tsx, packages/shared/src/components/cards/v1/CollectionCard.tsx, packages/shared/src/components/post/collection/CollectionPostContent.tsx, packages/shared/src/lib/featureManagement.ts, packages/shared/tailwind.config.ts, packages/webapp/components/FooterNavBar.tsx
- New experiment to show tags on the cards
- Also fixed a minor issue with articles cards having wrong margings
- And collections missing the tags on the modal/page
AS-236 #done
https://as-236-micro-show-tags-on-card.preview.app.daily.dev
=> fix: add new experiment to show tags on cards

packages/shared/src/hooks/post/usePostShareLoop.spec.ts, packages/shared/src/hooks/post/usePostShareLoop.ts
Fixed the `usePostShareLoop` hook so that it only returns `shouldShowOverlay === true` when it should - on user upvote action. Downvote or None should not cause the share loop to be shown.
Added unit test for the `usePostShareLoop` hook as well.
MI-281 #done
https://mi-281-fix-downvote-share-loop.preview.app.daily.dev
=> fix: post share loop showing on downvote

packages/webapp/components/FooterNavBar.tsx, packages/webapp/components/footer/FooterNavBarV1.tsx
- There is a known safe bottom space natively which is defined at the footer CSS module.
- The difference between previous implementations was the usage of it rather than the explicit `pb-6` class.
Also tested on simulator:
MI-256 #done
https://mi-256-native-footer.preview.app.daily.dev
=> fix: safe bottom padding

packages/shared/src/components/cards/PostTags.tsx
- Some edge-cases where long words at certain positions in the list would break.
- Added additional check to ensure atleast one tag even if longer
| Before    | After |
| -------- | ------- |
| <img width="713" alt="Screenshot 2024-04-09 at 05 52 43" src="https://github.com/dailydotdev/apps/assets/554874/9be9bb93-81fc-4731-a157-41eddc824be5"> | <img width="696" alt="Screenshot 2024-04-09 at 05 54 17" src="https://github.com/dailydotdev/apps/assets/554874/74bc59bc-c2e5-4803-953f-d9f7555a2a97"> |
| …
=> fix: ensure max length

packages/shared/src/components/modals/common/Modal.tsx
MI-284 #done
https://mi-284-upvoted-by-modal-bg.preview.app.daily.dev
=> fix: mobile ux modal should use default bg color

packages/shared/src/components/feeds/FeedContainer.tsx
When going to `/bookmarks` on new mobile ux page would break with:
```
Uncaught Error: ConditionalWrapper(...): Nothing was returned from render. This usually means a return statement is missing. Or, to render nothing, return null.
```
This was due to `actionButtons` being `undefined`.
https://hotfix-bookmarks-break-mobile-ux.preview.app.daily.dev
=> fix: return null if no actionButtons

packages/shared/src/components/filters/FeedFilters.tsx, packages/shared/src/components/modals/common/Modal.tsx, packages/shared/src/components/modals/common/ModalHeader.tsx, packages/shared/src/components/modals/common/ModalSidebar.tsx, packages/shared/src/components/modals/common/types.ts, packages/shared/src/components/sidebar/SidebarList.tsx
Related slack thread: https://dailydotdev.slack.com/archives/C0650M2KX8E/p1712672312237649
* Fixed navigation with modal sidebar on modal and refactored to make it easier to use.
* Removed left border
* Removed components that were never rendered
Before the interface was a bit quirky - the consumer of the modal needed to define a few functions and a state to determine if the nav is open. This is now changed in favor of supplying the modal with `defaultOpen` prop, which determines if the modal nav is open when it's first rendered instead.
MI-288 #done
https://mi-288-feed-filters-fix.preview.app.daily.dev
=> fix: feed filters modal ux inconsistencies for mobile

packages/shared/src/components/modals/SubmitArticleModal.spec.tsx, packages/shared/src/components/modals/SubmitArticleModal.tsx, packages/shared/src/components/sidebar/ContributeSection.tsx, packages/webapp/components/footer/FooterPlusButton.tsx
Slack thread here: https://dailydotdev.slack.com/archives/C0650M2KX8E/p1712666428589889
Changed the copy from `Submit article` to `Community picks` in:
- footer navbar when clicking on the plus button
- sidebar
- submit article modal header
- changed the copy of the submit button on the modal to just `Submit`
MI-286 #done
https://mi-286-submit-article-copy.preview.app.daily.dev
=> chore: change copy for the Submit Article modal and triggers of it

packages/shared/src/hooks/analytics/useAnalyticsSharedProps.ts
- While fixing https://github.com/dailydotdev/apps/pull/2972 I noticed `query_params` in events are not sent on initial page load for static pre-rendered pages until `useRouter.query` is hydrated
- I now merge them with `window.location.search` to include any initial params like `utm_`
=> fix: add initial query params to analytics events

packages/shared/src/components/filters/MyFeedHeading.tsx
Reported on slack: https://dailydotdev.slack.com/archives/C0650M2KX8E/p1712771505063679
The problem was caused by refresh icon changing it's size depending on if the user is on the feed page or not. Fixed that so that in new mobile layout, it does not change the refresh icon size. We already use the same condition for the feed settings icon.
https://github.com/dailydotdev/apps/assets/9974711/a5700598-e198-4c44-a1f1-5cee9824b8d9
MI-290 #done
https://mi-290-fix-header-layout-shift.preview.app.daily.dev
=> fix: layout shift when leaving/entering feed

packages/shared/src/components/RecommendedTags.tsx, packages/shared/src/graphql/sources.ts, packages/shared/src/lib/query.ts, packages/webapp/pages/sources/[source].tsx
- Render source related tags from the new endpoint
https://as-247-source-tags.preview.app.daily.dev
=> fix: render source related tags

packages/shared/src/components/modals/SharedBookmarksModal.spec.tsx, packages/shared/src/hooks/useCopy.ts, packages/shared/src/hooks/useCopyPostLink.ts, packages/shared/src/hooks/useSharePost.ts, packages/shared/src/hooks/utils/useGetShortUrl.ts
Related issue:
- https://dailydotdev.atlassian.net/browse/MI-291
Fixed the problem, when 2 clicks were required to copy link to clipboard. This was caused by 2 things:
1. Async operation to fetch the shortened URL, which can take 500ms or more.
2. Safari (and other browsers) strict limit on user-triggered events for clipboard operation, but [Safari is especially stringent and weird](https://bugs.webkit.org/show_bug.cgi?id=222262)
Refactored the code and introduced fixes:
- shortening is now part of the useCopy hook instead
- shortening is now a best effort operation
- if shortening fails, we still have the original URL with query params in the clipboard
- refactored to use `clipboard.write` with a `ClipboardItem` instead of `writeText`. This seems to be better supported in Safari. …
=> fix: share post link copy needs to be clicked twice

packages/extension/src/newtab/MainFeedPage.tsx, packages/shared/src/components/BookmarkFeedLayout.tsx, packages/shared/src/components/Feed.spec.tsx, packages/shared/src/components/MainFeedLayout.tsx, packages/shared/src/components/RecommendedTags.tsx, packages/shared/src/components/Settings.tsx, packages/shared/src/components/feeds/FeedContainer.tsx, packages/shared/src/hooks/useFeedLayout.ts, packages/shared/src/hooks/useOnPostClick.ts, packages/shared/src/lib/feed.ts, packages/shared/src/lib/query.ts, packages/webapp/pages/[userId]/posts.tsx, packages/webapp/pages/[userId]/upvoted.tsx, packages/webapp/pages/sources/[source].tsx, packages/webapp/pages/squads/[handle]/index.tsx, packages/webapp/pages/tags/[tag].tsx
- removal all feed related filters from feed layout hook
- added profile feeds on feedlayout hook to render the new cards
- adjusted some paddings and margins for the new cards on new feeds
- adjusted tests for desktop view
- Set the new cards in all feeds on mobile (bookmarks/squad feed/tags/sources)
- Set the new cards in profile posts & upvotes for both mobile and desktop
- We no longer open post modals in mobile/tablet in any feed
MI-254 #done …
=> feat: add feed layout without filters

packages/shared/src/components/profile/ProfileSettingsMenu.tsx
- On tablet mode, there is option to open the drawer for sharing a community link.
- Retain as per discussion.
https://fix-tablet-community.preview.app.daily.dev
=> fix: retain profile menu for community picks

packages/shared/src/components/search/SearchBarSuggestion.tsx
- Every resolution should only return one line for search history for now.
https://hotfix-search-mobile.preview.app.daily.dev
=> hotfix: mobile search results

packages/shared/src/components/ReputationUserBadge.tsx
Just fixes a small annoyance of mine 😬 
<table>
<tr>
<td>Before
<td>After
<tr>
<td><img src=https://github.com/dailydotdev/apps/assets/1681525/7b740efc-0272-4a5d-a341-31e589a305b4>
<td><img src=https://github.com/dailydotdev/apps/assets/1681525/14884e4f-509b-4fef-93d9-99ef337f50c5>
<tr>
<td colspan=2>Difference
<tr>
<td colspan=2><img src="https://github.com/dailydotdev/apps/assets/1681525/5b5b2ec6-624e-46da-a0d9-f99c592af6a4">
</table>
https://fix-misaligned-reputation.preview.app.daily.dev
=> fix: vertically aligns the reputation badge

packages/shared/src/components/auth/AuthOptions.tsx, packages/webapp/pages/onboarding.tsx
- We should only trigger the tracking on successful signup.
- This now happens on signup callback before choosing the tags
https://fix-marketing-tracking-signup-only.preview.app.daily.dev
=> fix: trigger tracking on signup only

packages/shared/src/components/feeds/FeedNav.tsx
- The set height was insufficient. `h-11` doesn't exist, so we used an arbitrary value.
Preview:
https://fix-insufficient-height.preview.app.daily.dev
=> fix: insufficient height for the header

packages/extension/src/newtab/ShortcutLinks.tsx
- Show a toast when hiding the shortcuts on V1
https://fix-toast-for-hiding-shortcuts.preview.app.daily.dev
=> fix: show toast when hiding shortcuts v1

packages/shared/src/components/auth/ReadingReminder.tsx
- Set text link to default design standard: https://dailydotdev.slack.com/archives/C0381BQUEN9/p1713274207359549?thread_ts=1712057885.487599&cid=C0381BQUEN9
https://fix-default-link-color.preview.app.daily.dev
=> fix: set default link color

packages/shared/src/components/MainLayout.tsx, packages/shared/src/hooks/useFeedLayout.ts
- screen centered should not be on profile
- Fixes bug mentioned in [thread](https://dailydotdev.slack.com/archives/C013BS9KXQA/p1713355130016499?thread_ts=1713355014.587089&cid=C013BS9KXQA)
https://fix-screen-profile-posts.preview.app.daily.dev
=> fix: screen centered on profile

packages/shared/src/components/feeds/FeedContainer.tsx, packages/shared/src/components/utilities/common.tsx, packages/shared/src/hooks/useFeedLayout.ts
- removed max width on mobile layout component that somehow shows up in desktop
- fixed paddings for mobile layout component 
- fixes search/sources/tags feed - [thread1](https://dailydotdev.slack.com/archives/C01L0QXQJNB/p1713373206302179), [thread2](https://dailydotdev.slack.com/archives/C01L0QXQJNB/p1713252987081529)
https://fix-feed-desktop.preview.app.daily.dev
=> fix: remove max width on feed desktop

packages/shared/src/hooks/usePostModalNavigation.ts
- The primary reason it is not found anymore by our modal processing is that we are now using the slug.
- Fix the check whether the slug matches the query.
MI-305 #done
=> fix: post modal navigation with slugs

packages/shared/src/components/Settings.tsx
- Hide the Weekly goal option when you are under streaks experiment.
MI-306 #done
https://mi-306.preview.app.daily.dev
=> fix: weekly goal option when on reading streaks

packages/webapp/__tests__/ProfileIndexPage.tsx, packages/webapp/pages/[userId]/index.tsx
- The weekly goal should not be shown for anonymous users since we are now moving to reading streaks.
MI-307 #done
https://mi-307.preview.app.daily.dev
=> fix: weekly goal displayed for anonymous user

packages/shared/src/components/Feed.spec.tsx, packages/shared/src/components/cards/ArticlePostCard.tsx, packages/shared/src/components/cards/CollectionCard/CollectionCard.tsx, packages/shared/src/components/cards/PostTags.tsx, packages/shared/src/components/cards/v1/ArticlePostCard.tsx, packages/shared/src/components/cards/v1/CollectionCard.tsx, packages/shared/src/lib/featureManagement.ts
- Tags on cards won 
AS-266 #done
https://as-266-cleanup-tags-cards.preview.app.daily.dev
=> feat: cleanup tags experiment

packages/shared/src/components/CommentFeed.tsx, packages/shared/src/components/MainFeedLayout.tsx, packages/shared/src/components/sidebar/DiscoverSection.tsx, packages/shared/src/components/sidebar/Sidebar.spec.tsx, packages/shared/src/graphql/comments.ts, packages/shared/src/hooks/useFeedLayout.ts, packages/shared/src/lib/featureManagement.ts, packages/webapp/__tests__/MostDiscussedPage.tsx, packages/webapp/__tests__/ProfileRepliesPage.tsx
- Discussion feed won
AS-267 #done
https://as-267-cleanup-discussion-feed.preview.app.daily.dev
=> feat: cleanup discussion feed experiment

packages/shared/src/components/search/SearchBarSuggestion.tsx, packages/shared/src/components/search/SearchPanel/SearchPanelPostSuggestions.tsx
- Added search recommendation tracking to click events
- Modify to include provider (matches other search queries
| Change| click - search rec | extra: { origin: Home Page, provider: posts } |
https://fix-search-rec-click.preview.app.daily.dev
=> fix: add click tracking to search rec

packages/shared/src/contexts/SettingsContext.tsx, packages/shared/src/lib/featureManagement.ts
- Whenever registration happens, we sync the local settings of our user, for example, when they switched to light mode, etc.
- In this case, we can be sure we will only apply the experiment on new users to set their default sidebar state value.
Kudos to @capJavert for the great idea.
MI-317 #done
https://mi-317-post-registration.preview.app.daily.dev
=> feat: experiment on sidebar state

packages/shared/src/components/drawers/Drawer.tsx, packages/shared/src/components/modals/Prompt.tsx
- Fix logout on mobile. The root cause was the drawer's placement that causes it to be behind the opened sidebar.
MI-326 #done
=> fix: logout on mobile (drawer not showing)

packages/shared/src/graphql/users.ts
- Acquisition channel was removed on the api side so setting this as string as well
https://hotfix-aquisition-channel.preview.app.daily.dev
=> fix: acquisition channel

packages/shared/src/hooks/analytics/useTrackLifecycleEvents.ts
When page is getting active again, send a dedicate event to signal that. Requested by Dave
https://page-active.preview.app.daily.dev
=> feat: send page active event

packages/shared/src/components/Feed.tsx
Fix loading placeholder always showing on squad pages. 
`const canFetchMore = allowFetchMore ?? queryCanFetchMore` would evaluate to `true` always because `??` only works with `null | undefined`.
https://fix-source-feed-fetch.preview.app.daily.dev
=> fix: use query can fetch by default for pagination

packages/shared/src/components/post/GoBackHeaderMobile.tsx
- The spacing seems lacking when the logo is only available.
Before:
After:
https://fix-header-spacing-logo.preview.app.daily.dev
=> fix: margin spacing when logo only

packages/shared/src/components/modals/BootPopups.tsx, packages/shared/src/hooks/useActions.ts, packages/webapp/pages/onboarding.tsx
- Fixes two things:
- 1. We use the same rule per prompt on when it should set the lastBootPopup (for some it's on show, some on close)
- 2. There was a issue with useActions hook where potentially it could return `isLoading: false` while no data was loaded, it's caused by react query mutations making isLoading to be false and data to exist.
- To solve 2 I introduced a internal state return that indicates whether data is loaded from the server, it should fix some edge-cases but not impact the existing hasAction check that happens for mutated data.
| Type   | …
=> fix: small boot prompt rules

packages/shared/src/components/post/PostActions.tsx
- QuarternaryButton doesn't work with passing variant-color it should for now always work based of solid className.
| ![Screenshot 2024-04-26 at 14 17 17](https://github.com/dailydotdev/apps/assets/554874/5cc6ccbd-553d-4243-9e15-7e74a8ce799b) | ![Screenshot 2024-04-26 at 14 42 39](https://github.com/dailydotdev/apps/assets/554874/648a9020-7242-47dc-b25f-124fffda08e3) |  …
=> fix: post page button colors

packages/webapp/pages/account/profile.tsx
Render dropdown menu as absolute on profile page.
Our dropdown component uses react-contexify library. This in turn renders the dropdown menu as a `position: fixed` component. When we scroll, this will be scrolled as well. The library circumvents this by adding `window.addEventListener` to the `'scroll'` event and hiding the dropdown menu when scroll happens. The problem is, that on profile page, it's not the window that scrolls, but the page container itself. The scroll event is not bubbled up by default, which causes this hiding not to happen.
Simple CSS fix is IMO preferable to touching the library and modifying the event handling. On other pages where `Dropdown` component is used, we don't have this problem. There's either no scrolling or the scrolling is done on the window object. …
=> fix: render experience level dropdown as absolute on profile page

packages/shared/src/components/MainLayout.tsx, packages/shared/src/components/layout/MainLayoutHeader.tsx
- We had two layout shift issues
- 1. Introduced by `!isLaptop` causing first load to be false, then true making the header not render
- 2. Introduced by a extra padding left which should only render after second load (same issue by defaults)
| https://github.com/dailydotdev/apps/assets/554874/d9b4df99-b2fa-4f02-828b-47f170ba4fcd | https://github.com/dailydotdev/apps/assets/554874/04ead7f6-629c-43b5-bc71-8fa3208f8699 | 
| Change/New | event name  | extra: { ... } …
=> fix: two layout shift issues

packages/shared/src/components/MainLayout.tsx
- Since we use padding to determine center of the main content we need to wait for settings to be loaded.
- We need to make sure this doesn't introduce weird UX
- We need to ensure it doesn't affect SEO crawler
https://fix-layout-shift.preview.app.daily.dev
=> fix: layout shift on sidebar movement

packages/shared/src/components/post/SquadPostWidgets.tsx, packages/shared/src/components/sources/SourceCard.tsx, packages/shared/src/components/squads/SquadHeaderBar.tsx, packages/shared/src/components/squads/SquadJoinButton.tsx, packages/shared/src/components/squads/SquadPageHeader.tsx, packages/shared/tailwind.config.ts
- [Add animation](https://dailydotdev.slack.com/archives/C069XNYMDGV/p1714371978328689?thread_ts=1714147361.826129&cid=C069XNYMDGV) on the sparkle based on Tomer's specs.
- [Fix the ordering](https://dailydotdev.slack.com/archives/C069XNYMDGV/p1714372075393149?thread_ts=1714022816.959379&cid=C069XNYMDGV) of the header items.
=> fix: squad page header and animation

packages/shared/src/components/layout/MainLayoutHeader.tsx, packages/shared/src/hooks/utils/useFeatureTheme.ts
- search bar had a background, we do not need to specify it, so I removed it
- modals now have the same background as body
MI-329 #done
https://mi-329-starwars-mobile-fixes.preview.app.daily.dev
=> feat: fixes for starwars theme on mobile

packages/shared/src/components/post/PostContent.tsx, packages/shared/src/components/post/SquadPostContent.tsx, packages/shared/src/components/post/collection/CollectionPostContent.tsx, packages/shared/src/hooks/post/useViewPost.ts
Do not update streak query cache when post is viewed, but was already read before.
Related issue:
https://dailydotdev.atlassian.net/browse/MI-230
MI-230 #done
https://mi-230-fix-streak-cache-read-posts.preview.app.daily.dev
=> fix: do not update streak cache on posts that were read already

.github/workflows/add-preview-domain.yml
Trigger preview domain on `ready_for_review` events, even though it should still work on a new draft PR...
=> fix: also trigger on `ready_for_review`

packages/shared/src/components/streak/popup/ReadingStreakPopup.tsx, packages/shared/src/hooks/post/useViewPost.ts, packages/shared/src/lib/dateFormat.spec.ts, packages/shared/src/lib/dateFormat.ts
Related slack thread: https://dailydotdev.slack.com/archives/C01L0QXQJNB/p1714142180431059
Several issues found with streaks popup have been fixed:
- if user had browser tab opened after date change (midnight), popup would never update correctly, because the streakDays were calculated on the module
- memoization of streaks was not done correctly, because it used the consts defined on the module (as mentioned above)
- `getTodayTz` was giving incorrect dates, e.g. '2024-05-03T13:12:11+02:00' would result in `2024-05-02T00:00:00` on my machine, resulting in -1 day skew
- switched to invalidating of the query for streak history and rely on API call being done instead of calculating and filling the cache on the UI side
No new events
MI-333 #done …
=> fix: streak popup updating with a delay

packages/shared/src/hooks/usePostModalNavigation.ts
- looks like close handler for modal introduced issue with back button not working because `onCloseModal` changed history to interfere with Next.js router
- back button now works when you are navigating between multiple tag pages by constantly selecting them eg. go to /tags/php (select tag) -> /tags/javascript -> back -> /tags/php (before URL would change but the page would stay the same as if you are on javascript page) …
=> fix: back button now correctly refreshes route

packages/shared/src/components/fields/ContextMenu.tsx
- The current menu drawer a href was not spanning the whole width, this solves that issue making the whole line clickable
https://hotfix-make-a-clickable.preview.app.daily.dev
=> hotfix: make whole a href clickable

packages/shared/src/components/MainFeedLayout.tsx, packages/shared/src/components/PostsSearch.tsx, packages/shared/src/hooks/search/useSearchProvider.ts
- Since this feature was created pre the new hooks and rules we didn't wait for enrollment
- This adjustment ensures we only enroll on query/search
https://as-296-search-enrollment.preview.app.daily.dev
=> fix: search enrollment event

packages/shared/src/components/PostOptionsMenu.tsx, packages/shared/src/components/feeds/SimilarEmptyScreen.tsx, packages/webapp/pages/posts/[id]/similar.tsx
- Added a empty state for similar posts
- Added a back navigation for mobile/tablet
AS-298 #done
https://as-298-empty-state.preview.app.daily.dev
=> fix: add empty screen

packages/shared/src/components/post/PostActions.tsx
- this experiment seemed to be affecting for bad the non mobile users, as we didn't find any reason why, we are making sure this experiment only enrols mobile users so we can see it's effect only on them. See thread for more info: https://dailydotdev.slack.com/archives/C02JAUF8HJL/p1714967983589999
- decision to do the change in thread [here](https://dailydotdev.slack.com/archives/C02JAUF8HJL/p1715067685797829)
- used conditional feature hook to only evaluate if it's mobile
https://fix-enrollment-share-experience.preview.app.daily.dev
=> fix: use useConditionalFeature to only enroll mobile users

packages/webapp/pages/posts/[id]/similar.tsx
- Since the vector provider doesn't support proper pagination yet we decided to query 100 by default to run the experiment on.
- https://dailydotdev.slack.com/archives/C04UN615UAF/p1715151579135949?thread_ts=1715072074.942399&cid=C04UN615UAF
https://hotfix-query-100-for-similar-feed.preview.app.daily.dev
=> fix: query 100 temporary for this experiment

packages/extension/src/companion/App.tsx, packages/extension/src/companion/Companion.spec.tsx, packages/extension/src/newtab/ShortcutLinks.spec.tsx, packages/shared/__tests__/fixture/squads.ts, packages/shared/src/components/Settings.spec.tsx, packages/shared/src/components/ShareBar.spec.tsx, packages/shared/src/components/modals/ShareModal.spec.tsx, packages/shared/src/components/post/write/CreatePostButton.tsx, packages/shared/src/components/post/write/SquadsDropdown.tsx, packages/shared/src/components/sidebar/SquadSection.tsx, packages/shared/src/components/squads/SquadsToShare.tsx, packages/shared/src/contexts/AuthContext.tsx, packages/shared/src/contexts/BootProvider.tsx, packages/shared/src/graphql/sources.ts, packages/shared/src/graphql/squads.ts, packages/shared/src/hooks/notifications/usePromotionModal.ts, packages/shared/src/hooks/squads/useSquads.ts, packages/shared/src/hooks/useBoot.ts, packages/shared/src/hooks/useDeleteSquad.ts, packages/shared/src/hooks/useJoinSquad.ts, packages/shared/src/hooks/useLeaveSquad.ts, packages/shared/src/lib/boot.ts, packages/shared/src/lib/query.ts, packages/webapp/__tests__/SquadFeedPage.tsx, packages/webapp/__tests__/SquadTokenPage.tsx, packages/webapp/pages/posts/[id]/edit.tsx, packages/webapp/pages/squads/[handle]/edit.tsx, packages/webapp/pages/squads/create.tsx, packages/webapp/pages/squads/index.tsx, packages/webapp/pages/squads/new.tsx
Related PRs:
- https://github.com/dailydotdev/apps/pull/3084
- https://github.com/dailydotdev/apps/pull/3096
Reintroducing the reverted code. Tested in production, that it works as intended.
MI-324 #done
https://mi-324-reapply-loading-squads-from-graphql.preview.app.daily.dev
=> MI-324 reapply loading squads from graphql

packages/shared/src/graphql/squads.ts, packages/webapp/pages/squads/index.tsx
- In coordination with making the API accept a boolean property to filter by flags.
- Reference: https://github.com/dailydotdev/daily-api/pull/1902
MI-348 #done
https://mi-348.preview.app.daily.dev
=> refactor: squads directory to fetch featured public squads only

packages/shared/src/graphql/squads.ts, packages/webapp/pages/squads/index.tsx
- Show only featured public squads in the directory.
- Reopening the PR to target main as the feature is now prioritized to be on production.
MI-348 #done
https://mi-348-featured.preview.app.daily.dev
=> refactor: squads directory to show featured only

packages/webapp/pages/squads/index.tsx
- Missing param results in different query fired during ssr pre-rendering
https://fix-squads-ssr.preview.app.daily.dev
=> fix(squads): match query in ssr to avoid pre-render difference

packages/shared/src/graphql/fragments.ts, packages/shared/src/graphql/users.ts
[More details on slack](https://dailydotdev.slack.com/archives/C06CUKX1P3N/p1715760110448429)
TLDR: our graphorm implementation cannot deal with children having timestamps without timezone. The `createdAt` field on `UserShortInfo` fragment was added to serve devcard requests. Easy fix was to remove the `createdAt` from the fragment and add the field directly to the devcard request. This is the easy fix.
Root cause fix would be to fix the graphorm implementation, but that's out of scope of public squad work.
https://fix-squad-graphql-query.preview.app.daily.dev
=> fix: squad graphql query

packages/shared/src/components/alert/AlertPointer.tsx
- Noticed an issue when writing a post. After clicking the dismiss (close) button on the Alert, it submits the form.
- On regular buttons, lint always tells to add a type on buttons. We can maybe incorporate it into our Button component.
#done
https://fix-alert-close.preview.app.daily.dev
=> fix: clicking the alert's close button submits form

packages/shared/src/components/auth/AuthOptions.tsx, packages/shared/src/components/auth/OnboardingAnalytics.tsx, packages/shared/src/lib/featureManagement.ts, packages/shared/src/lib/user.ts, packages/webapp/pages/onboarding.tsx
- only call trackAnalyticsSignUp on onboarding
- pass new user fetched data to the tracking function
- create event with experience level fb  
- Requested by Ido to have tracking on fb for experience
https://feat-new-fb-event.preview.app.daily.dev
=> Feat new fb event

packages/shared/src/components/filters/ContentTypesFilter.tsx
- If you navigated to feed filters on mobile it would crash the app due to `advancedSettings` being `undefined` still
https://fix-content-filters-crashing.preview.app.daily.dev
=> fix: advancedSettings can be undefined before fetched

packages/shared/src/lib/featureManagement.ts, packages/shared/src/lib/image.ts, packages/webapp/pages/onboarding.tsx
- We decided to no longer support video on onboarding page
AS-326 #done
https://as-326-cleanup-video-support.preview.app.daily.dev
=> chore: cleanup video support onboarding page

packages/shared/src/components/feeds/SimilarEmptyScreen.tsx
- Request to show different text if post title is not available/found.
AS-333 #done
https://as-333-similar-post-empty-state.preview.app.daily.dev
=> fix: similar post empty state text

packages/shared/src/components/Feed.tsx, packages/shared/src/components/feeds/FeedContainer.tsx, packages/shared/src/components/feeds/HorizontalFeed.tsx
- In SSR mode sometimes the feed would not render yet (due to waiting for settings to load)
- Thus the horizontal feed would miss it's execution for useEffect saying ref is empty.
- By moving to state we can set it as dependency (Thank @capJavert )
https://as-327-horizontal-back-button-fix.preview.app.daily.dev
=> fix: horizontal back button

packages/shared/src/components/squads/Members/PrivilegedMemberItem.tsx, packages/shared/src/components/squads/SquadPageHeader.tsx, packages/shared/src/lib/config.ts
- Fix the privileged member list orientation.
- Fix the dummy stats.
Before:
After:
https://fix-squad-header.preview.app.daily.dev
=> fix: squad page header

packages/shared/src/components/modals/squads/SubmitSquadForReviewModal.tsx, packages/shared/src/hooks/squads/usePublicSquadRequests.ts, packages/shared/src/hooks/useFeed.ts, packages/webapp/pages/squads/[handle]/index.tsx
- Fix the submission modal to automatically close and invalidate the query to reflect the correct status for the card.
- Fix the dismissal of card not reflecting immediately. After investigation, it was due to missing dependencies. 
- Fixed the condition for displaying the eligibility card.
MI-359 #done
https://mi-359.preview.app.daily.dev
=> fix: close modal on submission and hiding of card

packages/shared/src/components/modals/ShareModal.tsx, packages/shared/src/components/widgets/SocialShare.tsx
- There are two instances of Drawers, and since it closes on an outside click, the first Drawer thinks the user is clicking outside when in fact they were clicking on the second Drawer, which in fact is true.
- In order to understand when should we disable the close on outside click for the parent Drawer, we should track the state.
https://fix-share-squad.preview.app.daily.dev
=> fix: share to squad on mobile

packages/shared/src/components/squads/Details.tsx, packages/shared/src/graphql/squads.ts, packages/shared/src/hooks/squads/usePublicSquadRequests.ts, packages/shared/src/lib/config.ts, packages/webapp/pages/squads/[handle]/edit.tsx
- Cleanup of TODO comments.
- Update the form to handle toggling of privacy status based from [this PR](https://github.com/dailydotdev/daily-api/pull/1934).
https://fix-public-squads.preview.app.daily.dev
=> fix: public squads todo comments and privacy update

packages/shared/src/components/squads/Members/PrivilegedMemberItem.tsx, packages/shared/src/components/squads/SquadPageHeader.tsx, packages/shared/src/lib/config.ts
- Fix the amount of items to display when on mobile.
https://fix-mobile-list.preview.app.daily.dev
=> fix: mobile list count

packages/webapp/pages/squads/[handle]/index.tsx
- The condition should include the check whether the squad is already public or was approved in the past.
MI-361 #done
https://mi-361.preview.app.daily.dev
=> fix: condition when to display eligibility card

packages/shared/src/components/notifications/utils.ts
- Fix the color of the notification icon.
https://fix-notification-color.preview.app.daily.dev
=> fix: public squad approved notification bell color

packages/shared/src/components/Feed.tsx, packages/shared/src/hooks/feed/useFeedContextMenu.ts
- added feedname as an identifier for contextmenus in feed
- This fixes the issue with showing more then one context menu in card options, it was being caused especially in tags and sources page now that we have multiple feeds that contain the same values.
- issue reported here: https://dailydotdev.slack.com/archives/C01L0QXQJNB/p1716559704706499
MI-363 #done
https://fix-double-menus.preview.app.daily.dev
=> fix: issue with more then 1 context menu

packages/shared/src/components/ProfileMenu.tsx, packages/shared/src/components/drawers/NavDrawerItem.tsx, packages/shared/src/components/feeds/MobileFeedActions.tsx, packages/shared/src/components/layout/MainLayoutHeader.tsx, packages/shared/src/components/profile/ProfileSettingsMenu.tsx, packages/shared/src/components/referral/HypeButton.tsx, packages/shared/src/components/referral/HypeCampaign.tsx, packages/shared/src/components/referral/index.ts, packages/shared/src/components/sidebar/Sidebar.tsx, packages/shared/src/lib/featureManagement.ts, packages/shared/src/lib/image.ts, packages/shared/src/lib/links.ts, packages/webapp/pages/account/invite.tsx
AS-341
Some things might be a bit dirty code wise, as we hope to have it released in extension by tomorrow
https://as-341-hype-campaign.preview.app.daily.dev
=> feat: hype campaign

packages/shared/src/components/search/SearchPanel/SearchPanel.tsx, packages/shared/src/components/search/SearchPanel/common.tsx, packages/shared/src/graphql/search.ts, packages/shared/src/lib/featureManagement.ts
- Add google search provider
- User enrolled only when they actually see search panel action (same as tag experiment)
AS-347 #done
https://as-347-google-search-provider.preview.app.daily.dev
=> feat: add google search provider

packages/shared/src/graphql/feed.ts, packages/webapp/pages/feeds/[slugOrId]/edit.tsx
https://refetch-custom-feed-after-edit.preview.app.daily.dev
=> feat: refetch custom feed after edit

packages/shared/src/components/squads/Details.tsx, packages/shared/src/hooks/squads/usePublicSquadRequests.ts
- Existing public Squads, when checked by admins should automatically see the config to put it to private/public.
- To streamline the checking, we will do it at the hook where we return the status.
Slack thread: https://dailydotdev.slack.com/archives/C069XNYMDGV/p1716987326010879
https://fix-already-public-squads.preview.app.daily.dev
=> fix: already public squads don't need to check requests for approval

packages/shared/src/components/errors/Unauthorized.tsx
Fixes https://github.com/dailydotdev/daily/issues/1182
https://fix-back-home-button.preview.app.daily.dev
=> fix: add missing link to `Back home` on unauthorized page

packages/shared/src/components/search/SearchPanel/SearchPanel.tsx
Gives back control of `←` or `→` keys when inside input element so it is possible to navigate in input text.
AS-330
https://as-330-fix-arrow-keys-in-search-bar.preview.app.daily.dev
=> fix: don't override ← or → keys in search panel

packages/webapp/components/common.tsx, packages/webapp/pages/sources/index.tsx, packages/webapp/pages/tags/index.tsx
https://hotfix-breadcrumbs.preview.app.daily.dev
=> fix: breadcrumb state more inline with design

packages/shared/src/graphql/fragments.ts
This caused the invitations page to fail
Fixes https://github.com/dailydotdev/daily/issues/1190
https://fix-missing-createdat-in-user.preview.app.daily.dev
=> fix: add missing `createdAt` from user fragment

packages/shared/src/components/errors/SquadLoading.tsx
- Update skeleton loader.
Previews:
MI-370 #done
https://mi-370.preview.app.daily.dev
=> fix: squad page header skeleton

packages/webapp/pages/_app.tsx, packages/webapp/public/sitemap.xml
- Since we have very little pages public available/changing I decided to do a fully static sitemap (faster as well)
- Also added a rel to link it.
https://as-361-sitemap-rel.preview.app.daily.dev
=> fix: add sitemap and rel

.github/workflows/add-preview-domain.yml
Fixes preview domains that have an underscore in them, replaces them with a `-` instead.
https://fix-underscore-in-commits.preview.app.daily.dev
=> fix: replace `_` with `-` in preview domain

packages/shared/src/hooks/streaks/useReadingStreak.ts
Noticed that we try to fetch user streaks if not logged in.
Can be seen if you browse pages like https://app.daily.dev/squads when not logged in
https://fix-streaks-only-if-logged-in.preview.app.daily.dev
=> fix: only query reading streak if logged in

packages/extension/src/newtab/ShortcutLinks.tsx, packages/shared/src/components/filters/MyFeedHeading.tsx, packages/shared/src/components/layout/common.tsx, packages/shared/src/graphql/actions.ts, packages/shared/src/hooks/utils/useThemedAsset.ts, packages/shared/src/lib/featureManagement.ts, packages/shared/src/lib/featureValues.ts, packages/shared/src/lib/image.ts, packages/webapp/pages/onboarding.tsx
- add shortcuts ui experiment
- add new one first session UI
- add new "Shortcuts +" button when dismissed
TODO:
AS-352 #done
https://as-352-shortcuts-ui.preview.app.daily.dev
=> feat: add shortcuts ui experiment

packages/shared/__tests__/helpers/boot.tsx, packages/shared/src/components/layout/MainLayoutHeader.tsx
Adds the missing login and signup button in the header
<table>
<tr>
<td>Before
<td>After
<tr>
<td><img src="https://github.com/dailydotdev/apps/assets/1681525/0a03902a-bdac-4797-bba7-b6d84b2dbcf3">
<td><img src="https://github.com/dailydotdev/apps/assets/1681525/f3c68667-37c7-461c-b8d1-c9debacab42f">
</table>
https://fix-login-button-in-header.preview.app.daily.dev
=> fix: show header login buttons if not logged in

packages/shared/src/components/post/PostComments.tsx
Fix [Add a loader until the comments load](https://github.com/dailydotdev/daily/issues/1194)
-  Due to the default value of the `commentsCount ` variable being 0, when comments are loading, `commentsCount` is always equal to 0. I swapped the logic to render the loading component before rendering any other component.
=> fix: display spinner instead of first comment

packages/shared/src/components/Feed.tsx, packages/shared/src/components/PostOptionsMenu.tsx, packages/shared/src/components/modals/ShareModal.tsx, packages/shared/src/hooks/feed/useFeedContextMenu.ts, packages/shared/src/lib/featureManagement.ts
- Instead of doing all the prop drilling agian I decided to leverage the context addition I recently made.
- But now also add the right tracking opts for when a post modal is open
Event for feed:
Event for modal:
AS-362 #done
https://as-362-share-via-experiment.preview.app.daily.dev
=> feat: add share via experiment

packages/shared/src/lib/auth.ts, packages/webapp/components/layouts/AccountLayout/index.tsx
- Display the login screen when viewing an account page as an anonymous user.
Feel free to check the preview deployment.
Previews:
https://github.com/dailydotdev/apps/assets/13744167/16469448-d74e-468a-a463-e73b3795382d
MI-380 #done
https://mi-380.preview.app.daily.dev
=> fix: account pages when not logged in

packages/shared/src/graphql/keywords.ts, packages/shared/src/lib/featureManagement.ts, packages/shared/src/lib/image.ts, packages/webapp/pages/tags/[tag].tsx
- Ability to render roadmap links on tag pages (if flag exist on keyword)
- Related API: https://github.com/dailydotdev/daily-api/pull/1976
https://as-368-roadmap-link.preview.app.daily.dev
=> fix: roadmap links on tag pages

packages/shared/src/components/tabs/TabContainer.tsx
- Fixed a background on the tab container
| ![Screenshot 2024-06-12 at 10 55 23](https://github.com/dailydotdev/apps/assets/554874/8534ec88-3537-4d89-85ea-757eb31e4fdc) | ![Screenshot 2024-06-12 at 10 55 29](https://github.com/dailydotdev/apps/assets/554874/9d7152b7-c84c-423a-be75-2b2439a535bb) |
https://fix-tab-bar-bg.preview.app.daily.dev
=> fix: tabbar background addition

packages/webapp/pages/tags/[tag].tsx
- Remove social proof auth banners for tag page (roadmap.sh requirement)
https://chore-remove-social-proof-tag-page.preview.app.daily.dev
=> fix: remove social proof from tag page

packages/shared/src/components/cards/SharePostCard.tsx
- We need to render the share date not the actual post date
AS-372 #done
https://as-372-fix-shared-post-date.preview.app.daily.dev
=> fix: rendering of shared post date for exp

packages/shared/src/components/cards/PostCardFooter.tsx, packages/shared/src/components/cards/SharePostCard.tsx, packages/shared/src/components/cards/SharedPostCardFooter.tsx
- @capJavert Added a temporary workaround for this override.
- It's not ideal as the full implementation would take many, many changes but think for now it's safer atleast, let me know what you think.
https://fix-pass-props.preview.app.daily.dev
=> fix: pass props for shared post card

packages/shared/src/components/cards/SharePostCard.tsx
Removed in #3221 but got reverted in #3223.
This one we can keep, instead of re-assigning the variable when it is only used inside a ternary
=> fix: remove a param-reassign

packages/shared/src/hooks/feed/useFeedSurvey.ts
- Extra should be stringified object
https://hofix-feed-survey-tracking.preview.app.daily.dev
=> fix: tracking event wrong extra object

packages/shared/src/components/cards/CollectionCard/CollectionCard.tsx
- Just removed `className`, it was a leftover from initial implementation and it caused the different spacing
Before:
After:
AS-378 #done
https://as-378-fix-collection-card-actions.preview.app.daily.dev
=> fix: collection card actions

packages/shared/__tests__/fixture/squads.ts, packages/shared/src/lib/config.ts
Replace profile fallback image
<table>
<tr>
<td>Old
<td>New
<tr>
<td><img src="https://daily-now-res.cloudinary.com/image/upload/f_auto/v1664367305/placeholders/placeholder3">
<td><img src="https://res.cloudinary.com/daily-now/image/upload/s--O0TOmw4y--/f_auto/v1715772965/public/noProfile">
</table>
AS-389
https://as-389-replace-profile-fallback.preview.app.daily.dev
=> fix: replace profile fallback image

packages/shared/src/components/squads/Details.tsx, packages/shared/src/graphql/squads.ts, packages/webapp/pages/squads/[handle]/edit.tsx, packages/webapp/pages/squads/new.tsx
- added loading state to save button on squad edit
- there is an issue with a squad not being able to update their image, can't replicate properly but from the video looked like they submitted a lot of times and maybe it causes the requests to timeout and not update
- issue here: https://dailydotdev.slack.com/archives/C01L0QXQJNB/p1718680944874529
MI-392 #done
https://mi-392-squad-image-fix.preview.app.daily.dev
=> Mi 392 squad image fix

packages/shared/src/hooks/useFeedLayout.ts
- brought back isNullorUndefined for isLaptop with a slight change to what we had before
- now if isLaptop is null or undefined we set it to true, so the default layout is always the one in laptop, else we set it to whatever value isLaptop is
- This only introduced the edge cases we did mention before on tags/sources/bookmarks etc pages when doing SSR on mobile, which we deemed at that time not an issue since usually in mobile we move through page by client side rendering. (The issue is just an extra padding which doesn't look bad anyways) - decision this was ok was done here https://dailydotdev.slack.com/archives/C01L0QXQJNB/p1716278512251279
- fix on issue mentioned here https://dailydotdev.slack.com/archives/C02E2C3C13R/p1718888840253379
- this started happening again since we removed …
=> fix: set default laptop value even if undefined

packages/shared/src/hooks/useFeedLayout.ts, packages/webapp/pages/onboarding.tsx
- added pages to the set we use to validate
MI-394 #done
https://mi-394-posts-layout.preview.app.daily.dev
=> fix: add posts pages to use the new feed layout

packages/shared/src/components/layout/common.tsx
- The button should only be small if list mode and on mobile (which actually is always list mode)
https://github.com/dailydotdev/apps/assets/554874/77a786ed-0800-41e0-802e-139cfb920fa8
https://fix-button-size-desktop.preview.app.daily.dev
=> fix: turn off hotjar tracking

packages/shared/src/components/cards/ActionButtons.tsx, packages/shared/src/components/cards/list/CollectionList.tsx
- We somehow missed the onBookmarkClick for this list collection.
- I double checked all other usage of `ActionButton` inside `cards` pass it
AS-400 #done
https://as-400-bookmark-collection-list.preview.app.daily.dev
=> fix: bookmarking for collection list

packages/shared/src/components/auth/OnboardingLogs.tsx, packages/webapp/pages/onboarding.tsx
Android app starts the PWA with additional query param (aiid) that should be attached to our GA event
=> refactor: fetch instance id from query param

packages/shared/src/components/fields/MarkdownInput/index.tsx, packages/shared/src/components/tabs/TabContainer.tsx
- After further investigation, the issue seems to be not the border but the bg.
- After the mobile UX project, we made the bg to use the `default` but that should only be on the popup which is available on mobile only.
- For tablet and up, it should be `float`.
- For reference: https://www.figma.com/design/nmfWPS7x3kzLUvYMkBx2kW/daily.dev---Dev-Mode?node-id=6718-24966&m=dev
- Also fixed the minimum height issue when toggling left and right. 
Preview from Figma:
Fix recording:
https://github.com/dailydotdev/apps/assets/13744167/749e4782-9692-4820-a1bd-22c1fe675828
| …
=> fix: comment input header bg

packages/shared/src/components/cards/list/WelcomePostList.tsx
- adds margin when there's not image for laptop
- fixes issues reported:
- https://dailydotdev.slack.com/archives/C01L0QXQJNB/p1716906432720569
MI-399 #done
https://mi-399-list-card-no-image.preview.app.daily.dev
=> fix: margin on freeform cards

packages/shared/src/components/auth/AuthOptions.tsx
- @nensidosari found that the sign back in didn't work due to state refresh.
- Decided to move to use persistentContext to safe the chosen provider as it persists between navigations
- Also found a small bug where email registration didn't persist (only login did)
https://fix-sign-back-in.preview.app.daily.dev
=> fix: small issues with sign back in

packages/shared/src/components/filters/MyFeedHeading.tsx, packages/shared/src/hooks/useFeed.ts, packages/shared/src/lib/featureManagement.ts, packages/shared/src/lib/log.ts, packages/shared/src/lib/refreshFeed.ts
- Removal of the refresh feed button
- Decided to leave the option in FEED_QUERY and the icons :) 
AS-408 #done
https://as-408-remove-feed-refresh.preview.app.daily.dev
=> fix: remove refresh feed button

packages/shared/src/hooks/useInputFieldFunctions.ts, packages/shared/src/hooks/useProfileForm.ts, packages/webapp/pages/account/profile.tsx
- Solves two issues
- 1. Before we just to always redirect to the profile you where changing too, but on fails this would be invalid and show you someone else profile. So now we only redirect if mutation succeeds
- 2. The error wasn't shown in red (app wide issue) which this PR solves due to memo issue.
Disclaimer:
There is still a separate issue where it will reset what you filled out on error but tackling it as separate ticket.
AS-411  #done …
=> fix: profile update fixes

packages/shared/src/components/post/PostItemCard.tsx
- add prevent default
- Fixes issue on mobile where options click opens the post on history tab
- issue: https://dailydotdev.slack.com/archives/C01L0QXQJNB/p1716473698164619
MI-402 #done
https://mi-402-history-options.preview.app.daily.dev
=> fix: menu options click history tab

packages/shared/src/components/sidebar/SquadSection.tsx
New squad is now at bottom of list too
> [!CAUTION]
https://hotfix-new-squad-bottom.preview.app.daily.dev
=> fix: push new squad to bottom of list

packages/extension/src/newtab/ShortcutLinks.spec.tsx, packages/extension/src/newtab/ShortcutLinks.tsx, packages/shared/src/components/feeds/FeedContainer.tsx, packages/shared/src/hooks/utils/index.ts, packages/shared/src/hooks/utils/useShortcuts.ts, packages/shared/src/lib/featureManagement.ts
Cleanup onboarding_most_visited it won but only for users after set date.
Decided for this reason to abstract into a hook so the logic had one source of truth.
> [!CAUTION]
AS-425 #done 
https://as-425-cleanup-onboarding-most-visited.preview.app.daily.dev
=> fix: cleanup onboarding_most_visited

packages/extension/src/newtab/ShortcutLinks.spec.tsx, packages/extension/src/newtab/useShortcutLinks.tsx
- Fix the extension flaky test. Sometimes the evaluation happens without the re-render not yet finished. Hence, flaky result.
> [!CAUTION]
https://fix-flaky-extension.preview.app.daily.dev
=> fix: flaky extension test for shortcut links

packages/extension/src/contexts/ExtensionContext.tsx, packages/extension/src/lib/extensionScripts.ts, packages/extension/src/newtab/App.tsx, packages/shared/src/components/modals/common.tsx, packages/shared/src/components/modals/common/Modal.tsx, packages/shared/src/components/modals/common/types.ts, packages/shared/src/components/modals/firefoxPrivacy/FirefoxPrivacyModal.tsx, packages/shared/src/contexts/ExtensionContext.tsx, packages/shared/src/hooks/profile/useProfile.ts
Firefox has very strict privacy rules and thus we need to comply and offer a clear first interaction privacy setup.
As we don't provide any way for user to turn it off/deny it we need to present a "uninstall extension" prompt.
*ONLY SHOWS ON FF
Video of usecase:
https://github.com/dailydotdev/apps/assets/554874/8f9f1469-a18e-4ed6-b0f4-348ca5ab3d55
> [!CAUTION]
AS-429 #done
https://as-429-firefox-uninstaller.preview.app.daily.dev
=> fix: added privacy prompt for firefox

packages/shared/src/components/profile/SocialChips.tsx, packages/shared/src/lib/links.spec.ts, packages/shared/src/lib/links.ts
There was a issue if users pasted links as `google.com` or `www.google.com` it would simply redirect to app.daily.dev/URL.
Added a neater validation to ensure valid URL redirects, also strip unwanted protocols (like ftp)
> [!CAUTION]
AS-430 #done 
https://as-430-parse-as-links.preview.app.daily.dev
=> fix: link placement

packages/shared/src/components/modals/BootPopups.tsx
- Was not able to reproduce the actual issue but I observed all the evaluations we did when not showing the milestone.
- The only evaluation that could be the fault is the checking of actions they've made to hide the popup.
- There could be a race where the value returned is `undefined` which is considered as falsy.
- Also refactored usage of let. Not a fan of it as it is prone to being mutated somewhere else.
> [!CAUTION]
MI-410
https://mi-410.preview.app.daily.dev
=> fix: showing streak when disabled

packages/shared/src/components/Feed.spec.tsx
- Fix another flaky test. Previously it uses an async function that we awaits, by awaiting it, the alert has finished already and have reverted back to `off` state.
> [!CAUTION]
https://fix-flaky-feed.preview.app.daily.dev
=> fix: feed flaky test

packages/shared/src/components/post/PostActions.tsx, packages/shared/src/hooks/useSharePost.ts, packages/shared/src/lib/featureManagement.ts
Cleanup share_experience experiment (lost)
Also decided to remove openNativeShareOrPopup as it wasn't used and makes the hook a bit leaner.
> [!CAUTION]
AS-433 #done 
https://as-433-cleanup-share-experience.preview.app.daily.dev
=> chore: cleanup share_experience experiment

packages/shared/src/components/squads/SquadHeaderMenu.tsx
- Update ContextMenu with status that comes from context;
- fixes [#1260](https://github.com/dailydotdev/daily/issues/1260) ;
From mobile:
```
1. Go to 'Squads' 
2. Click on 'Your Squad X > option'
3. Open menu  '3 vertical dots' on the squad landing page
4. Observe
```
https://mi-419-fix-unable-to-leave-squad-on-mobile.preview.app.daily.dev/squads/nextjs
=> fix: unable to open context menu in squads from mobile;

packages/shared/src/components/modals/SubmitArticleModal.spec.tsx, packages/shared/src/components/modals/SubmitArticleModal.tsx
- Rather than wait for the user to close the modal after submission, we will instead close it and send a toast message.
- We should probably inform the product team about this engineering decsion.
> [!CAUTION]
MI-416 #done
https://mi-416.preview.app.daily.dev
=> refactor: community picks close on submission

packages/shared/src/components/Feed.tsx, packages/shared/src/components/FeedItemComponent.tsx
Probably legacy reasons we used to pass all items to each FeedItemComponent.
To only extract the one we need inside.
Instead we now can just pass the item we want to avoid spamming a big array each time.
> [!CAUTION]
https://chore-cleanup-item-passing.preview.app.daily.dev
=> chore: cleanup items passing

packages/shared/src/components/auth/AuthOptions.tsx
- Added redirect option in `onProfileSuccess` method
- User redirect to homepage after password reset
> Don't know if adding an option to this method is the right choice, open to feedback!
> Do I miss some event forcing redirect before `onSuccessfulRegistration`?
https://mi-417-forgot-password-flow-ends-up-in-tag-selection.preview.app.daily.dev
=> fix: user redirect to tag selection after password reset

packages/extension/src/newtab/ShortcutLinks/experiments/ShortcutLinksUIV1.tsx
Not sure when it broke but when testing something else I noticed the below button does nothing. I pushed it to use the same method to open menu as control version.
> [!CAUTION]
=> fix: clicking shortcuts options did nothing

packages/extension/src/newtab/ShortcutLinks/ShortcutOptionsMenu.tsx, packages/extension/src/newtab/ShortcutLinks/experiments/ShortcutLinksUIV1.tsx
On v1 we should open a context menu.
If I recall @ilasw added this specific react null render for storybook purpose so just removing for the sake of fixing the render (Tagging you so you aware)
(Control wasn't changes)
Now looks like:
> [!CAUTION]
https://hotfix-shortcut-options.preview.app.daily.dev
=> hotfix: shortcut options

packages/shared/src/components/layout/MainLayoutHeader.tsx
On mobile the search bar used to be `absolute` but to fix the `alertBanner` we made it `static` (default) which does't support z-index.
To fully fix it we move to `relative` to ensure it keeps it's `z-index` and won't break with alert banner.
Fixes:
https://github.com/dailydotdev/daily/issues/1284
> [!CAUTION]
AS-451 #done 
https://as-451-search-issue.preview.app.daily.dev
=> fix: search issue

packages/shared/src/graphql/bookmarks.ts
- Calling the reminder always results in `UNAUTHENTICATED`. It seems we have a new way now of calling queries/mutations to include the headers.
> [!CAUTION]
https://fix-reminder-call.preview.app.daily.dev
=> fix: bookmark reminder call by using gql client

packages/shared/src/components/cards/PostSummary.tsx, packages/shared/src/components/post/common/SharedLinkContainer.tsx
We have this [edge case](https://dailydotdev.slack.com/archives/C01L0QXQJNB/p1720729579314099) when sharing posts in squads.
This is a place where we render the TLDR with the option to hide it.
For this we use some JS calculations, which don't take the `show more` rendered height into account.
(Doesn't affect existing implementations as it just renders without the need for height wrapping.
Instead of relying on JS calculations I've decided to simply fix it with CSS magic :) 
First time ever using a [youtube video](https://www.youtube.com/watch?v=B_n4YONte5A) as a resource 😅
In action: (with CSS only)
https://github.com/user-attachments/assets/d79c2903-8be0-4498-b0de-314adbe0ae03
> [!CAUTION]
> Please make …
=> fix: tldr height for shared links

packages/shared/src/components/cards/PostCardFooter.tsx, packages/shared/src/components/cards/PostCardHeader.tsx, packages/shared/src/components/cards/common/SquadHeaderPicture.tsx, packages/shared/src/components/cards/list/PostCardHeader.tsx, packages/shared/src/components/cards/list/PostMetadata.tsx, packages/shared/src/lib/featureManagement.ts
- Experiment to show the author of the post.
- When user is enrolled, do not show the existing hover behavior for displaying the author itself.
Previews:
> [!CAUTION]
MI-445 #done
https://mi-445.preview.app.daily.dev
=> feat: author image on feed card

packages/shared/src/components/buttons/QuaternaryButton.tsx, packages/shared/src/components/cards/ActionsButtons/ActionButtons.tsx, packages/shared/src/components/cards/ArticlePostCard.tsx, packages/shared/src/components/cards/CollectionCard/CollectionCard.tsx, packages/shared/src/components/cards/SharePostCard.tsx, packages/shared/src/components/cards/WelcomePostCard.tsx, packages/shared/src/lib/featureManagement.ts
- add downvote to desktop cards
- downvote panel also added
- adjusted spacing based on new design
- all small icons per new design
- events send the same as from options -> downvote (which we already had)
> [!CAUTION]
AS-446 #done
https://as-446-card-downvote.preview.app.daily.dev
=> feat: add card downvote

packages/extension/package.json, packages/shared/src/components/squads/SquadPostListItem.tsx, packages/shared/src/components/widgets/BestDiscussions.tsx, packages/shared/src/components/widgets/FurtherReading.tsx, packages/shared/src/components/widgets/SimilarPosts.tsx, packages/shared/src/graphql/fragments.ts
- Aligned card heading and post titles in `SimilarPosts`;
- Fix bookmark icon ends on post title text;
- Added `public` field in `SourceShortInfo` fragment;
Static props from `packages/webapp/pages/posts/[id]/index.tsx` were loaded without the source's `public` field, causing query to pick from global feed. 
> [!CAUTION]
Mi-456
https://mi-456-more-posts-from-issues.preview.app.daily.dev
=> fix: more posts from source issue

packages/extension/src/companion/CompanionContent.tsx, packages/shared/src/components/cards/PostSummary.tsx, packages/shared/src/components/post/PostSummaryButton.tsx, packages/shared/src/graphql/actions.ts, packages/shared/src/hooks/experiments/index.ts, packages/shared/src/hooks/experiments/useSummaryActivation.ts, packages/shared/src/lib/featureManagement.ts
- A new experiment about TLDR.
- We will add an overlay when the user hasn't clicked the button yet.
- Should be applied across the app and to Companion.
Preview:
https://github.com/user-attachments/assets/8ca31696-a510-48f3-8315-63cb8c036884
> [!CAUTION]
MI-450
https://mi-450.preview.app.daily.dev
=> feat: generate tldr button experiment

packages/shared/src/components/MainLayout.tsx
- The check was too general. We should only open for now when it is coming from `notification`. Clicking from the lading page provides `utm_source=landing`.
> [!CAUTION]
https://fix-utm-check.preview.app.daily.dev
=> fix: popup to open only on notification utm source

packages/shared/src/components/PostOptionsMenu.tsx, packages/shared/src/components/post/write/ShareLink.tsx, packages/webapp/pages/posts/[id]/edit.tsx
- Trigger close `PostOptionsMenu` on `Edit post` click;
- Fix deleting `post.title` on form submit without doing any changes;
> [!CAUTION]
https://mi-461-fix-share-post-edit-in-a-squad.preview.app.daily.dev
=> fix: share post edit in a squad

packages/shared/src/components/squads/SquadCommentJoinBanner.tsx
Small edge-case where we didn't leverage state on modals for the just joined state.
It already worked on the actual page.
Video:
https://github.com/user-attachments/assets/a53dfb92-b4cb-40c4-ac88-049cbd6038fb
> [!CAUTION]
AS-479 #done 
https://as-479-squad-join-comment-fix.preview.app.daily.dev
=> fix: handle join state for modal

packages/shared/src/components/Feed.tsx, packages/shared/src/components/MainFeedLayout.tsx, packages/shared/src/hooks/search/useSearchResultsLayout.ts
Test isLoading only when shouldEvaluate as with disabled queries it might not evaluate.
> [!CAUTION]
https://chore-fix-search-loading.preview.app.daily.dev
=> fix: test loading state

packages/shared/src/components/notifications/InAppNotificationItem.tsx
- When the content reaches two lines, we need to apply the proper alignment fix.
> [!CAUTION]
MI-471
=> fix: items alignment on notification item

packages/shared/__tests__/fixture/feed.ts, packages/shared/src/components/post/PostContent.tsx, packages/shared/src/lib/featureManagement.ts, packages/webapp/__tests__/PostPage.tsx
Experiment was bypassed as winning.
> [!CAUTION]
AS-501 #done 
https://as-501-cleanup-origin-domain.preview.app.daily.dev
=> fix: cleanup origin_domain experiment

packages/shared/src/components/Feed.tsx, packages/shared/src/components/MainFeedLayout.tsx, packages/shared/src/components/search/SearchPanel/SearchPanel.tsx, packages/shared/src/components/search/SearchPanel/SearchPanelUserSuggestions.tsx, packages/shared/src/components/search/SearchPanel/common.tsx, packages/shared/src/components/search/SearchResults/SearchResultsLayout.tsx, packages/shared/src/components/search/SearchResults/SearchResultsUsers.tsx, packages/shared/src/components/widgets/PostUsersHighlights.tsx, packages/shared/src/graphql/search.ts, packages/shared/src/hooks/search/useSearchProvider.ts, packages/shared/src/lib/featureManagement.ts
Add search user suggestions query.
EDIT:
Also upgraded search page to include user results
As well as render the new laptop search page if no posts are found (as the side items might have results)
Related API:
https://github.com/dailydotdev/daily-api/pull/2124
> [!CAUTION]
AS-509 #done 
https://as-509-search-user-suggestions.preview.app.daily.dev
=> feat: add search user suggestions experiment

packages/webapp/pages/account/notifications.tsx
Changes the dropdown for the personalized digest time to drop up when there is no push notifications enabled.
This is a hotfix, and we should probably make it a bit more spatially aware to automagically select drop down direction
https://hotfix-digest-dropdown.preview.app.daily.dev
=> fix: set hour dropdown to up when there's no push enabled

packages/shared/src/components/modals/SlackIntegrationModal/SlackIntegrationModal.tsx, packages/shared/src/hooks/integrations/slack/useSlack.ts
Additional permissions for slack oauth to be able to access private channels.
API https://github.com/dailydotdev/daily-api/pull/2141
> [!CAUTION]
AS-521 #done
https://as-521-slack-private-channels.preview.app.daily.dev
=> feat: slack private channels

packages/shared/src/components/notifications/Toast.spec.tsx
Attempt to fix flaky test.
Basically due to timer inside Toast that cause re-renders (not within act, but we can't do that since we want it to render before)
> [!CAUTION]
https://fix-timer-test.preview.app.daily.dev
=> fix: timer test

packages/extension/src/newtab/ShortcutLinks/ShortcutLinks.tsx, packages/extension/src/newtab/ShortcutLinks/experiments/ShortcutLinksUIV1.tsx, packages/shared/src/hooks/utils/useShortcuts.ts, packages/storybook/stories/extension/ShortcutLinks.stories.tsx
- experiment is now going to work for existing users
- connect existing feature flag again instead of hardcoded
- do not show the popup if user already has some top sites
> [!CAUTION]
<!--
If relevant, please remove the comment HTML comment tags and fill the checkboxes below
AS-468 #done
https://as-468-shortcuts-followup.preview.app.daily.dev
=> feat: shortcuts followup experiment

packages/shared/src/components/comments/CommentActionButtons.tsx
Issue reported here: https://dailydotdev.slack.com/archives/C01L0QXQJNB/p1724128120556129
Fixes global error event thrown on extension when hovering over the action buttons of a comment. Seems to be caused by the tooltip wrapping the actions.
To fix changed appendTo parent instead of undefined. 
Tested webapp and chrome extension
https://fix-global-error-event.preview.app.daily.dev
=> fix: undefined append to tooltip - global error event

packages/webapp/__tests__/PostPage.tsx
Test is flaky due to it sometimes rendering twice (toast + inline message)
The changes make it more explicit which one to check for.
> [!CAUTION]
https://chore-flaky-downvote-test.preview.app.daily.dev
=> chore: fix flaky downvote test

packages/shared/src/graphql/squads.ts
Makes it a little bit easier to differentiate in metrics that this is actually querying Squads and not Sources (even though squads are sources)
https://chore-rename-sources-query.preview.app.daily.dev
=> chore: rename GraphQL operation name `Sources` to `Squads`

packages/webapp/pages/squads/index.tsx
Sets the stale time on the Squad directory page to 5 minutes, to not query on each visit.
https://fix-stale-time-squads-page.preview.app.daily.dev
=> fix: set stale time on Squads query

packages/shared/src/components/filters/ContentTypesFilter.tsx, packages/shared/src/components/filters/FeedFilters.tsx, packages/shared/src/components/profile/LanguageDropdown.tsx, packages/shared/src/lib/featureManagement.ts
Experiment post_title_language won
> [!CAUTION]
AS-545 #done 
https://as-545-cleanup-post-title-langua.preview.app.daily.dev
=> chore: cleanup post_title_language experiment (won)

packages/shared/src/components/Feed.tsx, packages/shared/src/components/FeedErrorScreen.tsx, packages/shared/src/hooks/useFeed.ts, packages/shared/src/hooks/utils/useThemedAsset.ts, packages/shared/src/lib/constants.ts, packages/shared/src/lib/image.ts
Option to display a feed error screen, since it's specific to feed and generic decided to implement on feed level. (instead of passing)
Also made overwrites to page container, so bear with me the existing ones are wrong, but didn't want to impact without testing them all.
Will only show on gardr error, else fallback to default behaviour of empty screen if available.
Screen cap:
[feed-error.webm](https://github.com/user-attachments/assets/3ac901ba-b4ca-472b-bf12-50e397c8e6e3)
Sizes and light mode:
> [!CAUTION]
https://feat-feed-error-screen.preview.app.daily.dev
=> feat: add feed error screen

packages/shared/src/graphql/users.ts, packages/shared/src/hooks/streaks/useStreakRecover.ts
- After restoring the streak, we need to update FE local cache to reflect the right value in the header.
- Tried to just set it manually based on the response, but UI was not changing. Used invalidate queries, and the UI updated.
> [!CAUTION]
=> fix: streak restore cache update on success

packages/shared/src/components/header/FeedExploreHeader.tsx, packages/shared/src/components/tabs/TabContainer.tsx, packages/shared/src/components/tabs/TabList.tsx
- Converts tabs on explore page to use `a` instead of `button`
https://as-543-buttons-to-links.preview.app.daily.dev
=> feat: add option to make TabList button be a element

packages/shared/src/components/sidebar/ClickableNavItem.tsx, packages/shared/src/components/sidebar/SquadSection.tsx, packages/shared/src/components/squads/SquadsDirectoryHeader.tsx, packages/shared/src/hooks/useSquadNavigation.ts
- convert "New squad" squad page button to anchor
- convert "New squad" sidebar button to anchor
- always show anchor element in sidebar
https://as-543-more-anchors.preview.app.daily.dev
=> refactor: convert buttons in sidebar to anchors

packages/shared/src/components/header/FeedExploreHeader.tsx, packages/shared/src/components/tabs/TabContainer.tsx, packages/shared/src/components/tabs/TabList.tsx
- Adds the missing href to tab items when they're anchors
> [!CAUTION]
https://as-543-fix-tab-links.preview.app.daily.dev
=> fix: add href to tab items if they're set

packages/shared/src/components/post/SquadPostAuthor.tsx
- role was set to admin not considering the value, changed to role
https://mi-500-squad-member-role-fix.preview.app.daily.dev
=> fix: squad role in post page

packages/shared/src/components/cards/squad/SquadList.tsx, packages/shared/src/components/squads/layout/SquadDirectoryLayout.tsx, packages/shared/src/components/squads/layout/SquadDirectoryNavbar.tsx, packages/shared/src/components/squads/layout/useSquadDirectoryLayout.ts, packages/shared/src/lib/constants.ts, packages/webapp/pages/squads/discover/index.tsx, packages/webapp/pages/squads/discover/my.tsx
- Previously, there were only two tabs, so it is easier to manage with just the state.
- But now that we have 3 or more tabs that work as a navigation link, making the behavior consistent across the items . Hence, creating a page for your Squads. Also makes it easier to point the user if they ask where to find all their Squads.
> [!CAUTION]
=> fix: my squads to be its own link

packages/shared/src/components/cards/squad/SquadGrid.spec.tsx, packages/shared/src/components/cards/squad/SquadGrid.tsx, packages/shared/src/components/cards/squad/SquadList.tsx, packages/shared/src/components/squads/SquadJoinButton.tsx, packages/shared/src/graphql/sources.ts
- The reason why the cards looked weird was, it was missing the border color, header image, and alignment of the elements.
- It was aliased to a different property to fit the previous card. But since we don't need the previous card anymore, we don't have to alias it. Also to avoid future confusion that it is actually part of the schema.
Preview:
> [!CAUTION]
MI-526
https://mi-526.preview.app.daily.dev
=> fix: squad card weird look

packages/shared/src/graphql/squads.ts, packages/shared/src/hooks/source/useSources.ts, packages/webapp/pages/squads/discover/[id].tsx, packages/webapp/pages/squads/discover/featured.tsx, packages/webapp/pages/squads/discover/index.tsx
- Sort the feeds by members count in descending order.
- Preview might not show the right sorting at the moment as we haven't updated the Squads count yet.
> [!CAUTION]
https://fix-squads-sorting.preview.app.daily.dev
=> fix: sorting squads feed by members count

packages/shared/src/components/feeds/FeedNav.tsx, packages/shared/src/components/sidebar/DiscoverSection.tsx, packages/shared/src/components/utilities/common.tsx, packages/shared/src/hooks/feed/useFeedName.ts, packages/shared/src/hooks/useActiveNav.tsx, packages/shared/src/hooks/useFeedLayout.ts, packages/shared/src/lib/query.ts
Discussed feed should be public available
API: https://github.com/dailydotdev/daily-api/pull/2265
> [!CAUTION]
AS-563 #done
https://as-563-public-discussed-feed.preview.app.daily.dev
=> fix: allow discussed feed to be public

packages/shared/src/components/contentPreference/FollowButton.tsx, packages/shared/src/components/sources/SourceActions/SourceActionsFollow.tsx, packages/shared/src/components/sources/SourceActions/SourceActionsNotify.tsx, packages/shared/src/components/widgets/PostUsersHighlights.tsx, packages/shared/src/graphql/comments.ts, packages/shared/src/graphql/contentPreference.ts, packages/shared/src/graphql/fragments.ts, packages/shared/src/graphql/furtherReading.ts, packages/shared/src/hooks/contentPreference/types.ts, packages/shared/src/hooks/contentPreference/useContentPreference.ts, packages/shared/src/hooks/usePostById.ts, packages/shared/src/lib/query.ts, packages/shared/src/types.ts, packages/webapp/__tests__/SourcePage.tsx
- reuse base components from `SourceActions` components (also adjusted them to match new follow designs)
- add `useContentPreference` hook for related mutations AS-580
- add `FollowButton` component (~~currently sends mutation but page refresh is needed to view new state~~)
- add support for follow of author/scout AS-572
- adjust fragments/queries 
TODO:
**!!! Opening this for review until I figure out invalidation of local cache. We can also probably merge this and use it to add the button around the app to not block other tasks.**
**!!! Update mutations handled for single post page only, we should be able to apply the concept elsewhere**
> [!CAUTION]
> Please make sure existing components are not …
=> feat: follow button

packages/shared/src/components/notifications/utils.ts
Option to mute user_post_added notification.
Follows common practice in app, we decided to enhance in phase 2 only as it requires many rewrites.
API: https://github.com/dailydotdev/daily-api/pull/2272
> [!CAUTION]
AS-574 #done 
https://as-574-notification-changes.preview.app.daily.dev
=> feat: notification changes

packages/shared/src/components/contentPreference/FollowButton.tsx, packages/shared/src/components/profile/Header.tsx, packages/shared/src/hooks/profile/useProfile.ts, packages/shared/src/hooks/profile/useProfileContentPreferenceMutationSubscription.ts, packages/shared/src/lib/user.ts, packages/webapp/components/layouts/ProfileLayout/index.tsx, packages/webapp/pages/[userId]/index.tsx
Since we currently only fetch client side on same user or no initial data we had to remove this.
As server isn't aware of the logged user.
There is a stale time so should be fine :) 
Also added the mutation invalidation handler.
> [!CAUTION]
AS-597 #done 
https://as-597-profile-follow-button.preview.app.daily.dev
=> feat: profile follow button

packages/shared/src/components/modals/SquadMemberModal.tsx, packages/shared/src/components/modals/common/ModalHeader.tsx
- On mobile, the modal is not closing due on certain edge cases.
> [!CAUTION]
https://fix-modal-closing.preview.app.daily.dev
=> fix: source member modal not closing

packages/shared/src/styles/utilities.css
Reverts dailydotdev/apps#3574
This affected the focus on the buttons. The fix should be exclusive to the card itself only.
https://revert-3574-card-border-missing.preview.app.daily.dev
=> Revert "updated utility.css to solve missing border issue"

packages/shared/src/components/modals/SquadMemberModal.tsx, packages/shared/src/components/modals/UpvotedPopupModal.tsx, packages/shared/src/hooks/contentPreference/useUsersContentPreferenceMutationSubscription.ts
Use the same hook from source members list to correctly show follow state in upvotes modal. 
> [!CAUTION]
https://fix-follow-mutation-upvotes.preview.app.daily.dev
=> fix: follow state in upvotes modal

packages/shared/src/components/auth/ForgotPasswordForm.spec.tsx, packages/shared/src/components/auth/LoginForm.spec.tsx, packages/shared/src/components/auth/RegistrationForm.spec.tsx
The a11y PR seem to have broken some tests because of how we focus the first elements on the forms (now either showing the label or placeholder). Not sure why these tests didn't fail on CI before the PR was merged. 
https://fix-tests.preview.app.daily.dev
=> fix: failing tests

packages/shared/src/components/HorizontalScroll/HorizontalScroll.tsx, packages/shared/src/components/cards/squad/SquadsDirectoryFeed.tsx, packages/shared/src/graphql/fragments.ts, packages/shared/src/hooks/source/useSources.ts, packages/webapp/pages/squads/index.tsx
- Adjusted the fragments so that only the necessary (or at least not heavy) properties are fetched for the cards.
- Utilized in view to check whether the element is in view to decide only then we will fetch the values.
Preview:
https://github.com/user-attachments/assets/88da62bc-0183-40fa-8061-66e1166eeb35
> [!CAUTION]
MI-561
https://mi-561.preview.app.daily.dev
=> refactor: avoid unnecessary calls and properties in squads directory page

packages/shared/src/components/feeds/FeedContainer.tsx, packages/shared/src/lib/query.ts
On mobile Squad directory page was not marked as active on navigation, quickly checked and was a 2 line fix
> [!CAUTION]
https://fix-squad-mobile-tab-item-active.preview.app.daily.dev
=> fix: change squad activeFeed name to reflect new path;

packages/shared/src/components/Feed.spec.tsx, packages/shared/src/components/modals/generic/common.ts, packages/shared/src/components/widgets/FurtherReading.spec.tsx, packages/shared/src/hooks/useBookmarkPost.ts
We no longer want to show the mobile app prompt after bookmarking (photo for reference)
> [!CAUTION]
AS-632 #done 
https://as-632-remove-bookmark-prompt.preview.app.daily.dev
=> chore: remove mobile app bookmark prompt

packages/webapp/__tests__/AccountNotificationsPage.tsx, packages/webapp/pages/account/notifications.tsx
Just noticed while testing cio issues. There was a missing condition to toggle follow when pressing parent email notification toggle.
> [!CAUTION]
https://fix-toggle-follow-email-settings.preview.app.daily.dev
=> fix: toggle follow if parent setting is toggled

packages/shared/src/components/search/SearchPanel/SearchPanelInput.tsx
Changed it so that the search experiment placeholder is shown both when the search is focused and not.
> [!CAUTION]
MI-589
https://mi-589.preview.app.daily.dev
=> fix: Change search experiment to show on both active/inactive state

packages/shared/src/components/tags/TagSelection.tsx
The random elements only need to happen on the first load of tags.
Before it would randomize every time you selected a different tag.
> [!CAUTION]
AS-638 #done 
https://as-638-randomize-onboarding-only.preview.app.daily.dev
=> fix: we only need to randomize once

packages/shared/src/components/fields/SearchField.tsx, packages/shared/src/components/fields/common.tsx, packages/shared/src/components/onboarding/EditTag.tsx, packages/shared/src/components/tags/TagSelection.tsx, packages/shared/src/lib/featureManagement.ts
Changed to the following states: (Already checked with Tomer)
We also added focus blue ring to default and disable the autofocus on mobile.
> [!CAUTION]
AS-633 #done 
https://as-633-search-focus-experiment.preview.app.daily.dev
=> feat: search focus experiment

packages/shared/src/components/squads/SquadPageHeader.tsx, packages/shared/src/graphql/fragments.ts
The category in squad header was using the squad id instead of the slug, which would result in an empty discover page.
> [!CAUTION]
MI-592
https://mi-592.preview.app.daily.dev
=> fix: Use slug instead of id when clicking category

packages/shared/src/components/cards/share/ShareList.tsx
In list mode -> shared post was not firing the tracking callback or respecting the openNewTab setting.
Another reason to more quickly move to a uniform approach 😅
It's really hard to debug which component renders/actually get's used.
> [!CAUTION]
https://fix-missed-passing-props.preview.app.daily.dev
=> fix: we missed firing events/openNewTab props

packages/extension/views/companion.html, packages/extension/views/newtab.html, packages/webapp/pages/_app.tsx
We have 3 apps that inject preconnect headers added all 3 now.
We should probably consider merging the 2 cloudinary ones into 1.
Discussion: https://dailydotdev.slack.com/archives/C02E2C3C13R/p1728887218700339
> [!CAUTION]
WT-2198 #done 
https://wt-2198-preconnect-headers.preview.app.daily.dev
=> feat: add the right preconnect headers

packages/shared/src/hooks/useTimedAnimation.ts
- All animations should be non-blocking.
- The state updates from displaying a toast notification come from the timer.
- This would make the toast animation non-blocking.
> [!CAUTION]
https://wt-2204.preview.app.daily.dev
=> refactor: use timed animation to be non-blocking

packages/extension/src/newtab/App.tsx, packages/webapp/pages/_app.tsx
- Reduces initial re-render.
- Same as with `useInAppNotification`, we don't actually need this instantiation.
- Tested on deleting a Squad, the prompt still showed.
> [!CAUTION]
https://fix-unnecessary-prompt.preview.app.daily.dev
=> fix: unnecessary hook instance of prompt

packages/webapp/components/footer/FooterWrapper.tsx, packages/webapp/components/footer/MobileFooterNavbar.tsx, packages/webapp/components/footer/common.ts, packages/webapp/components/layouts/FooterNavBarLayout.tsx
- properly lazy load components and separate concerns to avoid unused javascript loaded
- moved js for footer navbar needed only on mobile to it's own file and lazy load the component
Reports:
- Before: https://pagespeed.web.dev/analysis/https-app-daily-dev-posts-why-generalists-own-the-future-zavawfet1/33ckmjhzr9?form_factor=mobile
- After: https://pagespeed.web.dev/analysis/https-wt-2203-footer-navbar-lazy-load-preview-app-daily-dev-posts-why-generalists-own-the-future-zavawfet1/wvd02thnl7?form_factor=mobile
Analysis on unused JS for footer
Before: 
After:
> [!CAUTION]
WT-2203 #done …
=> chore: properly lazy load mobile footer

packages/shared/src/hooks/integrations/useSourceIntegrationQuery.ts
- because I returned `undefined` query would re-run each time because `undefined` is not valid anymore for `useQuery` since its counted as absence of value, you have to do `null`
> [!CAUTION]
https://fix-source-integration-query.preview.app.daily.dev
=> fix: source integration refetches on auth error

packages/shared/src/graphql/squads.ts, packages/shared/src/graphql/users.ts, packages/webapp/pages/squads/[handle]/index.tsx
Squad page not loading due to different way of calling query
> [!CAUTION]
https://fix-squad-load.preview.app.daily.dev
=> fix: squad load

.github/workflows/add-preview-domain.yml, .github/workflows/remove-preview-domain.yml
Should fix the preview domain issue in #3717
Vercel complains when the subdomain ends with a `-`, which is what happens in #3717, because when the branch `chore-remove-react-intersection-observer` is sliced to 32 chars, it ends up at `chore-remove-react-intersection-`. So this fix should strip out any trailing `-` / non-alphanumeric characters from the subdomain.
https://fix-preview-domain.preview.app.daily.dev
=> fix: remove any trailing non-alphanumeric characters from preview domains

packages/shared/src/components/badges/TopReaderBadge.tsx, packages/shared/src/graphql/fragments.ts, packages/shared/src/graphql/users.ts, packages/webapp/pages/badges/[badgeId].tsx
This is used for generation of the badge image
Depends on https://github.com/dailydotdev/daily-api/pull/2370
> [!CAUTION]
AS-660
https://as-660-badge-endpoint.preview.app.daily.dev
Demo devcard URL
https://as-660-badge-endpoint.preview.app.daily.dev/badges/e81c38aa-a8d6-4cf4-93e5-db24ec5daf30
=> feat: create endpoint to render the top reader badge

packages/webapp/__tests__/PostPage.tsx
Don't think it fully fixes it, but less prone to the issue.
This is a better actual resize to force.
The main issue is I think that we wrap the whole layout, and shouldn't really do that for this test.
But it's a bit bigger scope so trying this so long.
> [!CAUTION]
https://fix-flaky-test.preview.app.daily.dev
=> fix: flaky test

packages/extension/package.json
Build takes long now, and we actually only need Chrome at the moment.
(And yes I'm too lazy to type `npm run build:chrome` myself 😂
> [!CAUTION]
https://patch-build-chrome.preview.app.daily.dev
=> fix: we only need to build chrome

packages/shared/src/components/tabs/TabList.tsx
Due to callback getting called before redirect happens this item no longer exists.
(Mobile only issue)
Solves:
https://github.com/dailydotdev/daily/issues/1430
> [!CAUTION]
https://fix-deletion-custom-feeds.preview.app.daily.dev
=> fix: deletion of custom feeds

packages/shared/src/components/TopReaderIn.tsx, packages/shared/src/components/badges/TopReaderBadge.tsx, packages/shared/src/components/comments/CommentContainer.tsx, packages/shared/src/components/post/SquadPostAuthor.tsx, packages/shared/src/components/profile/UserShortInfo.tsx, packages/shared/src/graphql/comments.ts, packages/shared/src/graphql/fragments.ts, packages/shared/src/lib/user.ts
Depends on https://github.com/dailydotdev/daily-api/pull/2382
> [!CAUTION]
AS-670
https://as-670-top-reader-user-info.preview.app.daily.dev
https://as-670-top-reader-user-info.preview.app.daily.dev/posts/dream-machine--7agaxxtvx
=> feat: top reader in user short info

packages/shared/src/hooks/useSquadChecklist.tsx
Brave browser blocks OneSignal SDK from loading thus resulting the `isPushSupported` to return as `undefined`.
This fix ensures we cast to boolean to prevent falsy values.
Issue:
Solves:
https://github.com/dailydotdev/daily/issues/1558
> [!CAUTION]
https://fix-subscribe-state.preview.app.daily.dev
=> fix: subscribe state of oneSignal

packages/shared/src/components/badges/TopReaderBadge.tsx, packages/shared/src/components/modals/badges/TopReaderBadgeModal.tsx, packages/shared/src/components/profile/ActivitySection.tsx, packages/shared/src/components/profile/TopReaderWidget.tsx, packages/shared/src/graphql/fragments.ts, packages/shared/src/graphql/users.ts, packages/shared/src/hooks/useTopReader.ts, packages/shared/src/lib/constants.ts, packages/shared/src/lib/topReader.ts, packages/webapp/pages/[userId]/index.tsx
Depends on https://github.com/dailydotdev/daily-api/pull/2381
TODO:
> [!CAUTION]
AS-661
https://as-661-profile-top-reader.preview.app.daily.dev
=> feat: add top reader badges widget to user profile

packages/shared/src/components/image/Image.tsx
Since on mobile we now use srcset it takes priority over src, making onError not callback correct.
Added option to also onError change srcset if it exists.
> [!CAUTION]
https://hotfix-srcset-error.preview.app.daily.dev
=> fix: if srcset is set we need to error on it

packages/shared/src/components/badges/TopReaderBadge.tsx, packages/shared/src/components/modals/badges/TopReaderBadgeModal.tsx, packages/shared/src/components/profile/TopReaderWidget.tsx
Some keywords does not have a title, so we need to fallback to using the value instead
<table>
<tr>
<td>Before
<td>After
<tr>
<td><img src=https://github.com/user-attachments/assets/bde39c71-4bd7-4fdb-b49f-bfab49c1b8b3>
<td><img src=https://github.com/user-attachments/assets/788edd36-3e6d-4ed3-b7ec-2c74749519d6>
</table>
> [!CAUTION]
https://as-510-keyword-fallback.preview.app.daily.dev
=> fix: fallback to keyword value when title does not exist

packages/shared/src/components/drawers/Drawer.tsx, packages/shared/src/components/modals/badges/TopReaderBadgeModal.tsx, packages/shared/src/components/modals/common/Modal.tsx
The close button in the modal called `onRequestClose` directly, which unmounted the component and didn't let the drawer close properly.
So now I just hide the button on mobile, and use the native close button in the drawer. Now it also animates the closing.
I noticed that modals/drawers on mobile did not trigger the `onAfterOpen` which is often used to send analytics events. This might've caused some events not being sent from mobile.
It now uses a `useEffect` to call `onAfterOpen` once on mount, and then `onAfterClose` once upon unmount, similar to how `ReactModal` uses  `componentWillMount`/`componentWillUnmount` 
https://as-680-fix-drawer-close.preview.app.daily.dev
=> refactor: use native close button in drawer instead

packages/shared/src/components/cards/ad/AdGrid.tsx, packages/shared/src/components/cards/ad/AdList.tsx
Since we won't roll out ad package yet we need to remove this for now.
Left the component so we can easily bring it back.
> [!CAUTION]
AS-720 #done 
https://as-720-remove-ad-button.preview.app.daily.dev
=> fix: remove ad button

packages/shared/src/contexts/PaymentContext.tsx, packages/shared/src/lib/constants.ts
I noticed our default webappUrl is actually set to `/` now (on prod as well)
but Paddle expects fully qualified domain, so just hardcoding it for now. (didn't have better solution)
> [!CAUTION]
https://fix-qualified-url.preview.app.daily.dev
=> fix: need fully qualified URL

packages/shared/src/components/cards/Freeform/FreeformList.tsx, packages/shared/src/components/cards/article/ArticleList.tsx, packages/shared/src/components/cards/collection/CollectionList.tsx, packages/shared/src/components/cards/share/ShareList.tsx, packages/shared/src/components/modals/squads/PostModerationModal.tsx, packages/shared/src/components/post/freeform/write/WriteFreeformContent.tsx, packages/shared/src/components/post/write/ShareLink.tsx, packages/shared/src/components/squads/moderation/SquadModerationItem.tsx, packages/shared/src/components/squads/moderation/SquadModerationItemContextMenu.tsx, packages/shared/src/components/squads/utils.tsx, packages/shared/src/contexts/WritePostContext.tsx, packages/shared/src/graphql/posts.ts, packages/shared/src/graphql/sources.ts, packages/shared/src/graphql/squads.ts, packages/shared/src/hooks/input/useDiscardPost.ts, packages/shared/src/hooks/source/useSourcePostModeration.ts, packages/shared/src/hooks/source/useSourcePostModerationById.ts, packages/shared/src/hooks/useTruncatedSummary.ts, packages/shared/src/lib/query.ts, packages/webapp/pages/posts/[id]/edit.tsx
- Make the edit page be reusable to post moderation request.
- At first I thought of writing a whole edit page solely for the post moderation, but realized that it would be just the same and whole lot of copy-pasting. Would love to hear some thoughts if anyone thinks a dedicated page is a good option. Keep in mind that the internal components updated here would still have the same changes.
- Also updated the types and graphql schemas to better reflect our standard when it comes to related entities.
- I've tested both freeform and sharing internal posts.
TODO:
> [!CAUTION]
MI-622 #done
https://mi-622.preview.app.daily.dev
=> feat: edit source post moderation entity

packages/shared/src/components/modals/post/CreateSharedPostModal.tsx, packages/shared/src/components/post/write/ShareLink.tsx, packages/shared/src/components/squads/SharePostBar.tsx, packages/shared/src/components/squads/utils.tsx, packages/shared/src/contexts/WritePostContext.tsx, packages/shared/src/graphql/posts.ts, packages/shared/src/hooks/source/useSourcePostModeration.ts, packages/shared/src/hooks/squads/usePostToSquad.ts, packages/webapp/pages/posts/[id]/edit.tsx, packages/webapp/pages/squads/create.tsx
Added prompt modal on edit, as well as moving remaining create/edit flows into usePostToSquad.
Originally when I updated this I tried to consolidate everything in as few callbacks as possible. That was a mistake. Made it confusing to work with and caused some weird behaviors, so I decided on just giving each action its own callback.
> [!CAUTION]
MI-584 #done
MI-619 #done
[MI-584]: https://dailydotdev.atlassian.net/browse/MI-584?atlOrigin=eyJpIjoiNWRkNTljNzYxNjVmNDY3MDlhMDU5Y2ZhYzA5YTRkZjUiLCJwIjoiZ2l0aHViLWNvbS1KU1cifQ
=> feat: prompt modal on edit

packages/shared/src/components/modals/squads/PostModerationModal.tsx, packages/shared/src/components/squads/moderation/SquadModerationItemContextMenu.tsx, packages/shared/src/hooks/squads/useSourceModerationList.ts
- Source avatar too big
- Close button not aligned to right
- Too much padding in modal body (32 vs 24)
- Shared post has too much margin
- Content being rendered even if not present (with margins)
| <img width="751" alt="image" src="https://github.com/user-attachments/assets/f9a12ed5-6117-45b5-afa8-bb4efc816e89"> | <img width="727" alt="image" src="https://github.com/user-attachments/assets/8721b50f-61c8-4f5e-bc28-6a2f7372aa96"> | 
> [!CAUTION]
https://fix-modal-preview-ui.preview.app.daily.dev
=> fix: preview modal ui to match figma

packages/webapp/pages/squads/new.tsx
- Default values for member posting role should be `member` then have the moderation turned on.
- Reference: https://dailydotdev.slack.com/archives/C07GFU7DX8X/p1731333591730799?thread_ts=1731333291.352049&cid=C07GFU7DX8X
> [!CAUTION]
https://fix-default-values.preview.app.daily.dev
=> fix: default values when creating a squad

packages/shared/src/components/plus/PlusDesktop.tsx, packages/shared/src/components/plus/PlusInfo.tsx, packages/shared/src/components/plus/PlusMobile.tsx, packages/shared/src/contexts/PaymentContext.tsx, packages/webapp/pages/plus/index.tsx, packages/webapp/pages/plus/payment.tsx
Decided to split into lazy loaded components and render different on view.
(mobile+tablet is one and desktop)
This way we can better control how things load and look.
> [!CAUTION]
AS-719 #done 
https://as-719-mobile-flow.preview.app.daily.dev
=> feat: mobile view flow

packages/webapp/pages/plus/index.tsx, packages/webapp/pages/plus/payment.tsx
Was a minor layout shift where router wouldn't be ready and show mobile unintentional.
Also made payment noindex
> [!CAUTION]
https://fix-prevent-layout-shift.preview.app.daily.dev
=> fix: prevent layout shift on desktop

packages/shared/src/components/layout/common.tsx, packages/shared/src/components/squads/SquadTabs.tsx, packages/webapp/pages/squads/[handle]/edit.tsx, packages/webapp/pages/squads/[handle]/moderate.tsx
- Add gap between button and title
- SquadTabs was rendered on loading showing `Pending Posts` even if the squad have no moderation settings. I removed this component from the loading state and refactored to make it consistent through the pages 
> [!CAUTION]
https://fix-moderation-ui.preview.app.daily.dev
=> fix: moderation flow small UI issues

packages/shared/src/components/modals/post/CreateSharedPostModal.tsx, packages/shared/src/hooks/squads/usePostToSquad.ts, packages/webapp/pages/squads/new.tsx
- Fix the callback when moderation was a success. This tells the component to clear out the URL.
> [!CAUTION]
https://mi-628.preview.app.daily.dev
=> fix: clear out url after sharing an external link for moderation.

packages/shared/src/components/ProfileMenu.tsx, packages/shared/src/components/UpgradeToPlus.tsx, packages/shared/src/components/plus/PlusInfo.tsx, packages/shared/src/components/profile/Header.tsx, packages/shared/src/components/profile/ProfileSettingsMenu.tsx, packages/shared/src/components/sidebar/SidebarDesktop.tsx, packages/shared/src/components/sidebar/SidebarTablet.tsx, packages/shared/src/contexts/PaymentContext.tsx, packages/shared/src/hooks/usePlusSubscription.ts, packages/shared/src/lib/log.ts
- [Upgrade subscription](https://docs.google.com/spreadsheets/d/18Lv7zXges9QfVX5VYL1a-Hyl0e1sQ3sLr0OK8YZWKXI/edit?gid=1800717040#gid=1800717040&range=A3:A5)
- [Manage subscription](https://docs.google.com/spreadsheets/d/18Lv7zXges9QfVX5VYL1a-Hyl0e1sQ3sLr0OK8YZWKXI/edit?gid=1800717040#gid=1800717040&range=A27:A29)
- [Change billing cycle](https://docs.google.com/spreadsheets/d/18Lv7zXges9QfVX5VYL1a-Hyl0e1sQ3sLr0OK8YZWKXI/edit?gid=1800717040#gid=1800717040&range=A6:A8)
- [Complete checkout](https://docs.google.com/spreadsheets/d/18Lv7zXges9QfVX5VYL1a-Hyl0e1sQ3sLr0OK8YZWKXI/edit?gid=1800717040#gid=1800717040&range=A12:A16)
- [Warning checkout](https://docs.google.com/spreadsheets/d/18Lv7zXges9QfVX5VYL1a-Hyl0e1sQ3sLr0OK8YZWKXI/edit?gid=1800717040#gid= …
=> fix: add analytics to plus

packages/shared/src/components/post/PostEngagements.tsx, packages/shared/src/hooks/useFeed.ts
Removes ads from feed and comments if user is plus user.
> [!CAUTION]
AS-740
https://as-740-ad-free.preview.app.daily.dev
=> feat: ad-free feed when plus user

packages/shared/src/components/modals/squads/PostModerationModal.tsx
Close button isn't showing on mobile right now
> [!CAUTION]
https://fix-moderation-modal-preview-mob.preview.app.daily.dev
=> fix: enable close button on mobile

packages/shared/src/components/squads/moderation/SquadModerationItem.tsx
Tried hyphens and word breaks. Hyphens was inconsistent. Did not work on long links. Word break worked consistently.
> [!CAUTION]
MI-643 #done
https://mi-643.preview.app.daily.dev
=> fix: Added break-words to post moderation item

packages/shared/src/components/profile/ProfileTooltip.tsx
Linked Issue: [#1596](https://github.com/dailydotdev/daily/issues/1596)
You can read about this issue in detail in the linked issue comment where I have explain in detail with video.
After:
https://github.com/user-attachments/assets/b0f1897d-fba1-495a-9d3b-2c866ef45810
> [!CAUTION]
=> fix: wrong DevCard on hover

packages/shared/src/components/Feed.tsx, packages/shared/src/hooks/useFeed.ts, packages/shared/src/lib/log.ts
Add event to track frontend empty feeds.
Example return:
```js
{
"event_name": "feed empty",
"target_id": "postsupvoted",
"extra": "{\"version\":1,\"period\":7}"
}
```
| New | feed empty  | extra: { feed variables (dynamic object) } |
> [!CAUTION]
AS-783 #done 
https://as-783-feed-empty-log.preview.app.daily.dev
=> feat: add logging for empty feed from FE

packages/shared/src/components/BookmarkFeedLayout.tsx, packages/shared/src/components/filters/ContentTypesFilter.tsx, packages/shared/src/components/modals/common.tsx, packages/shared/src/components/modals/common/types.ts, packages/shared/src/components/modals/soon/AdvancedCustomFeedSoonModal.tsx, packages/shared/src/components/modals/soon/BookmarkFolderSoonModal.tsx, packages/shared/src/components/sidebar/ClickableNavItem.tsx, packages/shared/src/components/sidebar/SidebarDesktop.tsx, packages/shared/src/components/sidebar/common.tsx, packages/shared/src/components/sidebar/sections/BookmarkSection.tsx, packages/shared/src/components/sidebar/sections/CustomFeedSection.tsx, packages/shared/src/components/sidebar/sections/MainSection.tsx, packages/shared/src/contexts/SettingsContext.tsx, packages/shared/src/graphql/settings.ts, packages/shared/src/lib/image.ts, packages/shared/src/lib/log.ts, packages/webapp/pages/feeds/new.tsx
- add new soon modals
- connect them to entry points
- feed settings under content types & languages
- custom feeds on click on "new feed"
- bookmarks on click on new bookmark
Engineering decision, for each of these blocks:
If you are a plus member I just hide them (because you still are waiting for the feature but you are already a plus member. 
| Change| upgrade subscription | target_id: advanced custom feed soon modal |
| Change| upgrade subscription | target_id: bookmark folder soon modal |
| Change| upgrade subscription | target_id: feed settings |
> [!CAUTION] …
=> feat: entry points plus

packages/shared/src/hooks/streaks/useReadingStreak.ts
I see we actually to refetch streak when post is not read (so that should get correct data), but the issue is redirector fires only after that so sometimes streak is still not updated (its async).
```js
if (!post.read) {
checkReadingStreak(); // but redirect happens in parallel + cdc is async
}
```
In this PR I increase the timeout until we refetch streak on article click. Usually when all systems are nominal streak update happens in 400-600ms, so 1000ms should catch most of those cases and webapp should show correct state after refetch. 
This is a patch and long term fix should be done on API, see [thread](https://dailydotdev.slack.com/archives/C02E2C3C13R/p1733322909829059?thread_ts=1732891413.168089&cid=C02E2C3C13R) for more info on that. 
Did …
=> feat: increase streak check timeout

packages/shared/src/hooks/post/useSmartTitle.ts, packages/shared/src/hooks/usePostById.ts
Reverts to use initialData again, but use memoization of title
> [!CAUTION]
https://as-788-revert-initaldata.preview.app.daily.dev
=> fix: revert to using initialData again

packages/shared/src/components/squads/moderation/SquadModerationItem.tsx
* Added flex-1 to image so that it lines up with the buttons below 
> [!CAUTION]
MI-673 #done
https://mi-673.preview.app.daily.dev
=> fix: huge squad post moderation image

packages/shared/src/components/modals/bookmark/MoveBookmarkModal.tsx
Changed it so we pass the name of the folder, so we don't have to *guess* if it was moved to Quick Saves or not.
> [!CAUTION]
https://mi-678.preview.app.daily.dev
=> fix: Display correct folder name in toast

packages/shared/src/hooks/log/useLogSharedProps.ts
On the first visit `user_registration_date` is not set properly
WT-2247 #done
https://wt-2247.preview.app.daily.dev
=> fix: update analytics shared props on signup

packages/shared/src/components/feeds/FeedNav.tsx, packages/shared/src/components/tabs/TabContainer.spec.tsx, packages/shared/src/components/tabs/TabList.tsx
Add truncating if long names are used.
> [!CAUTION]
AS-814 #done 
https://as-839-tab-bar-truncate.preview.app.daily.dev
=> fix: add truncate on long names

packages/webapp/pages/feeds/[slugOrId]/edit.tsx, packages/webapp/pages/feeds/new.tsx
Edit/creation blocked for now.
Only weird for non enrolled members as we simply redirect without notion.
But since we plan to ship fast it should be fine.
> [!CAUTION]
AS-859 #done
https://as-859-block-custom-feeds.preview.app.daily.dev
=> fix: block custom feeds for now (edit/creation)

packages/shared/src/components/squads/utils.tsx
This reverts commit 9a7f72b7d9b720c580107121ddd04ef0c9bfe716.
- Posting as mod now works but breaks posting as a regular user.
> [!CAUTION]
https://revert-posting.preview.app.daily.dev
=> Revert "fix: moderation permission (#3982)"

packages/shared/src/hooks/useShareComment.ts, packages/shared/src/hooks/useShareOrCopyLink.ts, packages/shared/src/lib/func.ts
Use native share only on mobile. Us boomers can't copy link with the shitty apple native share on Mac
https://allow-native-share-mobile.preview.app.daily.dev
=> fix: allow native share only on mobile

packages/shared/src/components/CustomFeedOptionsMenu.tsx, packages/shared/src/components/profile/Header.tsx, packages/shared/src/components/sources/SourceActions/index.tsx, packages/shared/src/hooks/constants.ts, packages/shared/src/hooks/useShareOrCopyLink.ts, packages/shared/src/lib/log.ts, packages/shared/src/lib/referral.ts, packages/webapp/pages/join.tsx, packages/webapp/pages/tags/[tag].tsx
Added the new CustomFeedOptionsMenu to profile, tag and source pages. Have not done anything to squad page yet, as that is a button in an already existing menu, and can be added with [AS-842](https://dailydotdev.atlassian.net/browse/AS-842)
> [!CAUTION]
AS-853 #done
AS-854 #done
AS-855 #done
AS-856 #done
[AS-842]: https://dailydotdev.atlassian.net/browse/AS-842?atlOrigin=eyJpIjoiNWRkNTljNzYxNjVmNDY3MDlhMDU5Y2ZhYzA5YTRkZjUiLCJwIjoiZ2l0aHViLWNvbS1KU1cifQ
https://as-853.preview.app.daily.dev
=> feat: Reusable 3 dots for adding to custom feed

packages/shared/src/components/TagLinks.tsx, packages/webapp/pages/tags/index.tsx
Because of the `!line-clamp-2` which is needed we need to do some special magic.
The initial fix was to set all cases of TagLinks to be different size, but this affected other areas of the code.
This new one only affects the tag overview page to be bigger (for rendering the purple dot)
Solves.
https://github.com/dailydotdev/apps/pull/3907
> [!CAUTION]
https://chore-fix-tag-render.preview.app.daily.dev
=> chore: fix tag rendering

packages/extension/src/newtab/MainFeedPage.tsx, packages/shared/src/components/CustomFeedEmptyScreen.tsx, packages/shared/src/components/FeedEmptyScreen.tsx, packages/shared/src/components/MainFeedLayout.tsx, packages/shared/src/components/feeds/FeedNav.tsx, packages/shared/src/components/feeds/FeedSettings/FeedSettingsEdit.tsx, packages/shared/src/components/feeds/FeedSettings/FeedSettingsEditHeader.tsx, packages/shared/src/components/feeds/FeedSettings/types.ts, packages/shared/src/components/feeds/FeedSettings/useFeedSettingsEdit.tsx, packages/shared/src/components/feeds/MobileFeedActions.tsx, packages/shared/src/components/layout/common.tsx, packages/shared/src/components/sidebar/Sidebar.tsx, packages/shared/src/components/sidebar/SidebarDesktop.tsx, packages/shared/src/components/sidebar/sections/CustomFeedSection.tsx, packages/shared/src/components/sidebar/sections/MainSection.tsx, packages/shared/src/components/tabs/TabContainer.tsx, packages/shared/src/components/tabs/TabList.tsx, packages/shared/src/hooks/feed/useCustomDefaultFeed.ts
If the user has selected a custom feed as main, it will be shown as the main feed on the base path "/"
> [!CAUTION]
AS-858 #done
https://as-858.preview.app.daily.dev
=> feat: Display custom feed as default when set

packages/shared/src/components/filters/BlockedWords.tsx
Ensure feed id's get passed correctly for blocked words
> [!CAUTION]
AS-872 #done 
https://as-872-blocked-words-per-feed.preview.app.daily.dev
=> fix: ensure blocked words work per feed

packages/shared/src/components/layout/common.tsx
@capJavert This should only not render if not in experiment right?
So enrolled - not plus will see it, but it will redirect to homepage...?
> [!CAUTION]
https://as-883-remove-button.preview.app.daily.dev
=> fix: remove if not enrolled

packages/shared/src/components/plus/PlusList.tsx, packages/shared/src/components/sidebar/SidebarList.tsx
Several issues with the modal sidebar nav list.
- it had bg-inherit (inherit was `transparent`) - set to bg-default now.
- it didn't have top-0 so it offset with the new header
- it wasn't full height so small items would show below it
> [!CAUTION]
https://as-881-mobile-fix.preview.app.daily.dev
=> fix: mobile modal list fixes

packages/shared/src/lib/feed.ts
I'm really not sure why Ante made it render a different feed on new/edit pages.
But this should work.
> [!CAUTION]
AS-890 #done 
https://as-890-custom-feed-form.preview.app.daily.dev
=> fix: add custom feed form same feed

packages/shared/src/lib/feed.ts, packages/webapp/components/layouts/MainFeedPage.tsx
Ensure we can render my feed as a background for when editing it.
Otherwise return custom feed background as feed.
> [!CAUTION]
https://hotfix-my-feed-edit.preview.app.daily.dev
=> fix: my feed edit feed

packages/shared/src/components/CustomFeedEmptyScreen.tsx, packages/shared/src/components/buttons/DeleteCustomFeed.tsx, packages/shared/src/components/layout/common.tsx
fix: allow deletion of custom feed for people not plus (enrolled/non enrolled)
> [!CAUTION]
AS-889 #done 
https://as-889-feed-deletion.preview.app.daily.dev
=> fix: feed deletion

packages/shared/src/components/squads/Members/BlockedMembersPlaceholder.tsx
Fixes the empty state bottom push:
> [!CAUTION]
https://chore-fix-padding.preview.app.daily.dev
=> fix: padding on blocked members not found

packages/shared/src/components/cards/ActionsButtons/ActionButtons.tsx, packages/shared/src/components/cards/common/list/ActionButtons.tsx, packages/shared/src/lib/featureManagement.ts
https://dailydotdev.slack.com/archives/C02JAUF8HJL/p1735716046928839
> [!CAUTION]
https://mi-710.preview.app.daily.dev
=> chore: cleanup experiment upvote counter always visible

packages/shared/src/components/squads/moderation/SquadModerationItem.tsx
There's a deadzone on the avatar in squad post moderation. Clicking it does nothing, presumably some interference with how we pass click events. Just setting the pointer events to none is a quick and easy fix because we aren't passing anything to it anyway.
> [!CAUTION]
https://mi-711.preview.app.daily.dev
=> fix: Deadzone in squad post moderation item avatar

packages/shared/src/components/feeds/FeedSettings/FeedSettingsEditHeader.tsx
We should call save function when on filter page as well as general.
Edge-case when you change something and toggle away it doesn't save, but we should address seperately.
> [!CAUTION]
AS-911 #done 
https://as-911-saving-filter-bug.preview.app.daily.dev
=> fix: bug with saving filters

packages/shared/src/hooks/useTimedAnimation.ts
This reverts commit f17d1e0c017703d10c34b593a15ae8c3075abe46.
- This reverts the usage of `useTransition` on toast notification that caused the laggy experience.
- Tested locally and worked as intended.
> [!CAUTION]
https://mi-715.preview.app.daily.dev
=> Revert "refactor: use timed animation to be non-blocking (#3671)"

packages/shared/src/components/modals/common.tsx, packages/shared/src/components/modals/common/types.ts, packages/shared/src/components/modals/report/ReportUserModal.tsx, packages/shared/src/report.ts
Report / block user modal. Will be triggered when user presses any "block {user_name}" button. If block button is pressed, the block checkbox will be checked and disabled, as user is required to report if also blocking.
Will also be used on "report user" buttons. Here the "block {username}" checkbox will not be default checked, and user can toggle it.
Currently reporting/blocking will yield an error because the backend has not been updated to receive report entity type "user"
> [!CAUTION]
MI-741 #done
https://mi-741.preview.app.daily.dev
=> feat: ReportUserModal

packages/shared/src/components/auth/RegistrationForm.tsx, packages/shared/src/components/auth/SocialRegistrationForm.tsx, packages/shared/src/components/profile/LanguageDropdown.tsx, packages/shared/src/lib/user.ts
As @omBratteng mentioned before JS adds a empyt object when using `null` as enum value.
However decided to fix it inside the component by resetting index (1) (extra null)
This way it works for all users of this component
> [!CAUTION]
https://chore-onboarding-language.preview.app.daily.dev
=> fix: onboarding language fix

packages/shared/src/components/contentPreference/FollowButton.tsx
Currently this component is only looking for a current status, which means that if the entity is blocked by the current user, it will show as "following".
> [!CAUTION]
https://mi-747.preview.app.daily.dev
=> fix: Should not show following when blocked

packages/webapp/pages/posts/[id]/index.tsx
To prevent spammers from impacting our SEO, we need to make sure we don't index their posts
https://posts-noindex.preview.app.daily.dev
=> refactor: noindex post pages based on the author

packages/shared/src/components/streak/popup/ReadingStreakPopup.tsx, packages/shared/src/contexts/SettingsContext.tsx, packages/shared/src/graphql/settings.ts, packages/shared/src/hooks/streaks/useStreakTimezoneOk.ts
- moved to API so extension also has it when once set
https://github.com/dailydotdev/daily-api/pull/2600
> [!CAUTION]
https://as-914-reading-streak-setting-ap.preview.app.daily.dev
=> feat: move timezone ignore setting to api

packages/extension/src/newtab/App.tsx
Checking if onboarding is ready seems not necessary in extension from my testing. Re-unpacked the extension a few times to check if it would flash the onboarding screen, didn't seem to do so
> [!CAUTION]
https://mi-759.preview.app.daily.dev
=> fix: flash onboard screen

packages/extension/webpack.config.js
Chrome doesn't accept any [RHC](https://developer.chrome.com/docs/extensions/develop/migrate/remote-hosted-code).
Since we don't ever use/render the Turnstile I just use webpack magic to never include the package in build output.
It is used in some component, but this can't render on extension anyway (auth modal)
> [!CAUTION]
https://hotfix-exclude-turnstile-extensi.preview.app.daily.dev
=> fix: exclude turnstile for extension build

packages/shared/src/components/comments/CommentActionButtons.tsx
I believe the issue was caused by checking post.author.username instead of comment.author.username 😅 
The reported post is not crashing on preview:
https://mi-766.preview.app.daily.dev/posts/theoretical-engineers-fkatmixvy
> [!CAUTION]
https://mi-766.preview.app.daily.dev
=> fix: Missing username

packages/shared/src/components/sidebar/Section.tsx, packages/shared/src/components/sidebar/sections/BookmarkSection.tsx
- Root cause: the sidebar when toggled to be minimized on desktop, then viewed the mobile version, the app hides the section itself.
- By setting a parameter to say this should always be visible on mobile, the issue should be fixed.
> [!CAUTION]
https://fix-toggled-bookmarks.preview.app.daily.dev
=> fix: sidebar sections always visible

packages/shared/src/components/plus/PlusCheckoutContainer.tsx, packages/shared/src/components/plus/PlusDesktop.tsx, packages/shared/src/components/plus/PlusPlus.tsx, packages/shared/src/components/plus/PlusUnavailable.tsx, packages/shared/src/contexts/PaymentContext.tsx, packages/shared/src/lib/constants.ts, packages/shared/src/lib/featureManagement.ts, packages/webapp/pages/plus/payment.tsx
- also includes case where user is plus already
(I know icon is wrong in screenshots, it was fixed)
Desktop:
Mobile:
> [!CAUTION]
AS-950
https://as-950-plus-unavailable.preview.app.daily.dev
=> feat: support plus unavailable

packages/shared/src/components/post/PostContent.tsx, packages/shared/src/components/post/ShareYouTubeContent.tsx, packages/shared/src/components/video/YoutubeVideo.spec.tsx, packages/shared/src/components/video/YoutubeVideo.tsx, packages/shared/src/components/video/YoutubeVideoWithoutConsent.tsx
https://dailydotdev.slack.com/archives/C01L0QXQJNB/p1737996847135729
> [!CAUTION]
https://fix-yt-video.preview.app.daily.dev
=> fix: redirect to watch youtube video without consent

packages/webapp/pages/posts/[id]/edit.tsx
Encountered this during testing of real time translation, but it has been an issue since we introduced content-language header. Because we send the `content-language` header when you have a different content language set, we fetch the translated title and fill it into the edit form.
<table>
<tr>
<td>Before
<td>After
<tr>
<td>Content-language set to German (fetched German translation)
Content-language set default (fetched original title)
</td>
<td>Content-language set to German (fetched original title)
Content-language set default (fetched original title)
</td>
<table>
https://fix-original-title-in-post-edit.preview.app.daily.dev
=> fix: unset content-language header on post edit

packages/shared/src/components/cards/common/PostCardHeader.tsx, packages/shared/src/components/post/SharePostContent.tsx, packages/shared/src/lib/constants.ts, packages/webapp/pages/posts/[id]/edit.tsx
Adds a deleted render when shared posts get deleted.
On the card we no longer show the `Read post` button as it can't link anywhere.
On the modal/page we render as such:
> [!CAUTION]
https://feat-deleted-render.preview.app.daily.dev
=> feat: add deleted render for shared posts

packages/shared/src/contexts/AuthContext.tsx, packages/shared/src/hooks/useCookieBanner.ts
Don't show cookie banner and disable third-party tracking in ios (for now)
https://ios-tracking.preview.app.daily.dev
=> refactor: disable tracking in ios native

packages/shared/src/contexts/PaymentContext.tsx, packages/shared/src/lib/featureManagement.ts, packages/shared/src/lib/featureValues.ts
- We will define another "Custom data" from Paddle to ensure we will be able to find the right product option as it is getting harder to set unique criteria when looking for an item.
- Reference: https://dailydotdev.slack.com/archives/C02E2C3C13R/p1738074996696679
> [!CAUTION]
https://refactor-appsid.preview.app.daily.dev
=> fix: usage of apps id from paddle

packages/shared/src/graphql/posts.ts
Post `placeholder` has been deprecated for at least 3 years, and I don't see anywhere where it is used.
https://github.com/dailydotdev/daily-api/blame/ab1a21106e1cf6ab665f5e5a0348355f1eac17bf/src/schema/posts.ts#L478-L481
https://cleanup-deprecated-gql.preview.app.daily.dev
=> chore: cleanup `placeholder` from GQL

packages/shared/src/components/post/SharePostContent.tsx
Expanded sidebar on smaller devices caused overflow issues:
How it looks with the changes:
https://github.com/user-attachments/assets/4076c72e-bf96-4b5a-93e1-4ee5e6804fa3
> [!CAUTION]
https://wt-2251.preview.app.daily.dev
=> fix: shared post unreadable on tablet

packages/shared/src/components/plus/PlusCheckoutContainer.tsx, packages/shared/src/components/plus/PlusDesktop.tsx, packages/shared/src/contexts/PaymentContext.tsx, packages/shared/src/lib/featureManagement.ts
- Fix to display that checkout is available when user is a Plus member and wants to gift a user.
- Updated the right id for the gifting price id.
> [!CAUTION]
https://fix-availability.preview.app.daily.dev
=> fix: gifting while user is a Plus member already

packages/shared/src/components/post/SharePostContent.tsx, packages/webapp/pages/posts/[id]/index.tsx
2 more changes related to shared post (one more for cards coming once we get design)
1st:
Any private post now renders as private with a read post button that links to squad. (reminder: card change still coming)
2nd:
Viewing private posts should show unauthorised message not the 404.
> [!CAUTION]
https://chore-shared-post-changes.preview.app.daily.dev
=> chore: shared post private changes

packages/shared/src/components/auth/RegistrationForm.tsx, packages/shared/src/components/auth/SocialRegistrationForm.tsx
Remove language option during registration due to user confusion over posts being translated.
> [!CAUTION]
https://mi-781.preview.app.daily.dev
=> feat: remove language selection from registration

packages/shared/src/hooks/auth/useOnboarding.tsx, packages/webapp/pages/onboarding.tsx
- Fixes the `isOnboardingReady` evaluation.
- Fixes the issue introduced by updating the props.
- Updated the deps cycle.
- Tested each login flows.
> [!CAUTION]
https://revert-revert-condition.preview.app.daily.dev
=> fix: onboarding ready condition and missing deps

packages/shared/src/hooks/post/useSmartTitle.ts, packages/shared/src/hooks/translation/useTranslation.ts
- fetch title from kvasir if its not available
- also needs https://github.com/dailydotdev/kvasir/pull/5
> [!CAUTION]
https://as-966-smart-title-hook-kvasir.preview.app.daily.dev
=> feat: add kvasir support to smart title hook

packages/shared/src/components/post/smartPrompts/PromptButtons.tsx, packages/shared/src/contexts/SettingsContext.tsx, packages/shared/src/graphql/settings.ts, packages/shared/src/hooks/prompt/useSmartPrompt.ts
Storing the last prompt and swapping that one to the first spot.
I'm not 100% sure on the realtime swap that happens now. Going to check with product.
> [!CAUTION]
https://as-976-store-last-prompt.preview.app.daily.dev
=> feat: store last prompt

packages/webapp/pages/callback.tsx
Redirect callback page to the native app so we can complete the process there
https://ios-oauth.preview.app.daily.dev
=> feat: ios oauth support

packages/shared/src/components/plus/GiftReceivedPlusModal.tsx, packages/shared/src/components/plus/PlusPlus.tsx
- We should not show the button to manage subscription when user was just gifted. https://dailydotdev.slack.com/archives/C081Q26LZ3K/p1739196673669699?thread_ts=1739189289.357419&cid=C081Q26LZ3K
> [!CAUTION]
https://fix-gifted.preview.app.daily.dev
=> fix: displayed ui when gifted

packages/webapp/components/layouts/PlusLayout/PlusLayout.tsx, packages/webapp/pages/_app.tsx, packages/webapp/pages/onboarding.tsx, packages/webapp/pages/welcome/index.tsx
Instead of adding them to specific pages, I rather have them everywhere in the webapp. We have some concerns about attribution so I'd like to see if this improves the situation.
The only caveat is hotjar. This means it will record all the sessions if we enable it. We should consider moving hotjar out and put it only where we need it. Right now it's disabled anyway
https://global-pixels.preview.app.daily.dev
=> refactor: move pixels to _app

packages/shared/src/components/cards/share/ShareGrid.tsx, packages/shared/src/graphql/feed.ts
Fix to render state of deleted/private posts.
As it only targets squad feeds we only need to worry about grid view. (there's no list view in squads)
> [!CAUTION]
AS-1005 #done 
https://as-1005-shared-post-grid.preview.app.daily.dev
=> fix: shared post grid render

packages/shared/src/components/comments/CommentActionButtons.tsx, packages/shared/src/components/modals/award/GiveAwardModal.tsx, packages/shared/src/components/modals/common.tsx, packages/shared/src/components/modals/common/types.ts, packages/shared/src/lib/auth.ts
Added simple award from comment option
Added empty placeholder modal for award system
> [!CAUTION]
AS-995 #done 
https://as-995-gift-comment.preview.app.daily.dev
=> fix: show award modal on comments

packages/shared/src/components/modals/BootPopups.tsx
@capJavert mentioned that this popup should not be showing to app users on iOS
> [!CAUTION]
https://mi-815.preview.app.daily.dev
=> feat: should not show marketing ideation on iOS app

packages/shared/src/components/plus/PlusList.tsx, packages/shared/src/components/plus/PlusListItem.tsx
Bit tricky because it's the only one with different icon and typography options.
I saw it was kind of prepared but only on list level.
Note:
- Icon and copy still outdated
> [!CAUTION]
https://as-984-core-plus-bonus.preview.app.daily.dev
=> fix: add cores as plus bonus

packages/shared/src/components/feeds/CustomFeedSlider.tsx
> [!CAUTION]
https://mi-823.preview.app.daily.dev
=> fix: show highlighted custom default feed on extension

packages/extension/src/newtab/ShortcutLinks/ShortcutLinks.spec.tsx, packages/extension/webpack.config.js, packages/shared/src/contexts/PaymentContext.tsx
Ideally it shouldn't show the whole context, but I don't want to block long.
@sshanzel is going to re-evaluate anyway.
This will simply not init paddle (As it's empty) on extension.
> [!CAUTION]
https://chore-disable-paddle-extension.preview.app.daily.dev
=> chore: disable extension to load paddle sdk

packages/shared/src/components/modals/BootPopups.tsx
`onAfterClose` was not set in the right place, so it could cause issues where you'd see a popup right after another popup.
=> fix: `onAfterClose` in the right place for marketingCtaPlus

packages/shared/src/contexts/PaymentContext.tsx
Fixes a small typo in the `CHECKOUT_COMPLETED` event for paddle. `localCurrenct` -> `localCurrency`
https://paddle-payment-event-fix-localcu.preview.app.daily.dev
=> fix: fix typo in checkout completed event `localCurrenct` -> `localCurrency`

packages/shared/src/components/feeds/CustomFeedSlider.tsx
Wraps the feed button in a `Link` so we can soft-navigate between the pages. 
https://fix-use-link-for-custom-feed-but.preview.app.daily.dev
=> fix: wrap `Button` in `Link` to not hard-navigate

packages/shared/src/components/profile/AccountDangerZone.tsx, packages/shared/src/components/widgets/DangerZone.tsx, packages/shared/src/hooks/usePlusSubscription.ts, packages/shared/src/lib/plus.ts, packages/shared/src/lib/user.ts, packages/webapp/components/layouts/AccountLayout/Security/index.tsx
Because we can't cancel a subscription on behalf of a user, we can't let the user delete their account until they have cancelled their subscription
<table>
<tr>
<td>Can delete
<td>Prevented from deletion
<tr>
<td><img src="https://github.com/user-attachments/assets/403ae99e-d381-49e9-b420-2ab3e77f7865">
<td><img src="https://github.com/user-attachments/assets/da9ea42b-aa0c-49cd-a15f-bfab300a4f88">
</table>
https://fix-disable-deletion-when-active.preview.app.daily.dev
=> fix: disable account deletion button when user has active storekit subscription

packages/webapp/public/.well-known/apple-app-site-association
Once the app is approved and published, we can re-allow deep links into iOS
AS-1006
https://as-1006-remove-plus-exclusion.preview.app.daily.dev
=> fix: re-allow plus pages to deep link into the app

packages/shared/src/components/ProfileMenu.tsx, packages/shared/src/components/profile/ProfileSettingsMenu.tsx
On larger iPads, it uses the desktop profile menu, so need to make it trigger the native modal.
https://fix-manage-subscription-ios.preview.app.daily.dev
=> fix: show manage subscription sheet on larger tablets

Tiltfile
Add new function to only include `Tiltfile` if it exists, and don't throw an error.
https://dailydotdev.slack.com/archives/C02E2C3C13R/p1742369827333029
https://fix-no-fail-if-not-exist.preview.app.daily.dev
=> fix: only include `Tiltfile` if it exists

packages/shared/src/components/plus/PlusExtension.tsx, packages/shared/src/components/plus/PlusMarketingModal.tsx, packages/shared/src/components/plus/PlusWebapp.tsx
Fixes the issue of the app crashing when closing the modal. Seems to have been caused by the boot data being cleared before a refresh happens, which causes the app to re-render once before actually closing it, at which point the data is null.
There's been some recent changes that introduce states, which may have caused this to start happening suddenly.
The fix was to call `closeModal` before `clearMarketingCta`, but I also added a few checks around the code, so that if there's another issue with the flags at some point, it won't crash the entire app.
References:
[REPORT 1](https://github.com/dailydotdev/daily/issues/1807)
[REPORT 2
](https://github.com/dailydotdev/daily/issues/1806)
> [!CAUTION]
> Please …
=> fix: plus marketing cta modal crash on close

packages/shared/src/hooks/log/useLogQueue.ts
The Fylla Devtools can natively listen for web traffic, but for sendBeacon we need to send messages to the extension.
https://fylla-devtools.preview.app.daily.dev
=> feat: post messages for log events so that Fylla Devtools can use it

packages/shared/src/components/footer/FooterLinks.tsx
- Fixes the missing bottom margin in footer links when no comments are present.  
- Ensures consistent spacing regardless of whether comments exist.  
- Adjusts the footer layout to prevent it from appearing broken when no comments are available.  
---
Did you introduce any new tracking events?  
---
Did you introduce any new experiments?  
---
> [!CAUTION]  
> Please make sure existing components are not breaking/affected by this PR.  
---
Fixes #[1808](https://github.com/dailydotdev/daily/issues/1808)
---
This PR ensures a consistent UI experience by fixing an issue where the footer spacing was incorrect when no comments were present. 🚀
=> Fix: Added bottom margin to footer links for better spacing and consistent layout

packages/shared/src/components/modals/award/BuyCoresModal.tsx, packages/shared/src/components/modals/award/GiveAwardModal.tsx
Fixes overflow background on the award/ core modal.
Could also solve it by adding `overflow: hidden` on the Modal component, but it could cause unexpected errors.
https://fix-bg-overflow.preview.app.daily.dev
=> fix: overflow gradient background on award modal

packages/shared/src/components/comments/CommentContainer.tsx, packages/shared/src/components/post/PostActions.tsx
Show the comment remark properly and invalidate comments if note is present.
(needed to make parent relative, not sure why we didn't always do it already.. (seems to not break anything)
> [!CAUTION]
AS-1065
https://as-1065-note-post-award.preview.app.daily.dev
=> fix: add note post award

packages/shared/src/contexts/GiveAwardModalContext.tsx, packages/shared/src/lib/links.ts, packages/webapp/pages/cores/index.tsx, packages/webapp/pages/cores/payment.tsx
- buy cores through cores page instead of modal in extension
- add support for `next` param to redirect back from cores pages
> [!CAUTION]
<!--
If relevant, please remove the comment HTML comment tags and fill the checkboxes below
AS-1053
AS-1058
https://buy-award-extension.preview.app.daily.dev
=> feat: extension buy cores

packages/shared/src/components/modals/award/BuyCoresModal.tsx, packages/shared/src/components/modals/award/GiveAwardModal.tsx
- Use `useViewSize` to prevent flash of buy cores modal at top of page
- Show award modal when closing buy cores modal
----
Started with adding a state to track when to go back to award, but if I'm not wrong, all cases should lead back to award modal.
=> fix: prevent position flash of buy cores modal

packages/shared/src/components/post/PostActions.tsx
- Show award icon as secondary when I have not gifted
<table>
<tr>
<td>Before
<td>After
<tr>
<td><img src=https://github.com/user-attachments/assets/33bbc1e5-c83b-4710-bd23-015b6b7ba6de>
<td><img src=https://github.com/user-attachments/assets/5839e276-2c58-4ae4-b41a-0c02be1f83f9>
</table>
AS-1074
https://as-1074-fix-award-icon-post-acti.preview.app.daily.dev
=> fix: show award icon as secondary when I have not gifted

packages/shared/src/components/notifications/InAppNotificationItem.tsx
```
Warning: validateDOMNesting(...): <a> cannot appear as a descendant of <a>. Error Component Stack
```
The in-app notification toast has a nested anchor element, and the error message annoyed me in local env, so fixed it by using same method as cards by floating anchor element.
https://fix-notification-nested-anchor.preview.app.daily.dev
=> fix: remove nested anchor element in in-app notification toast

packages/shared/src/components/onboarding/OnboardingHeader.tsx, packages/webapp/pages/onboarding.tsx
I noticed on the one step checkout in onboarding we showed a double plus badge.
https://dailydotdev.slack.com/archives/C01L0QXQJNB/p1743752915105479
Not sure why it was introduced as there's already one.
> [!CAUTION]
https://fix-double-plus-badge.preview.app.daily.dev
=> fix: noticed we showed a double plus badge

packages/shared/src/components/notifications/NotificationIcon.tsx, packages/shared/src/components/notifications/utils.ts, packages/shared/src/lib/log.ts, packages/shared/src/lib/user.ts, packages/webapp/__tests__/AccountNotificationsPage.tsx, packages/webapp/pages/account/notifications.tsx
- Adds notification icon for award
- Toggle award notification
AS-987
AS-1050
https://as-1050-award-notification.preview.app.daily.dev
=> feat: add award notification

packages/shared/src/features/onboarding/hooks/useStepTransition.ts
Introduce new hook to dispatch the transition request
MI-858 #done
MI-858
https://mi-858.preview.app.daily.dev
=> feat: useStepTransition

packages/shared/src/features/onboarding/steps/FunnelLoading.tsx, packages/shared/src/features/onboarding/types/funnel.ts
Since we are now loading all the screens at the same time, we need a property to tell the loading screen when it should start loading.
Also removed the unnecessary cleanup from the second useEffect
> [!CAUTION]
https://update-loading-screen.preview.app.daily.dev
=> feat(funnels): add isActive prop to Loading Screen

packages/shared/src/hooks/useQuerySubscription.ts, packages/shared/src/hooks/useUpdateQuery.ts
> [!CAUTION]
https://typed-queries-proposal.preview.app.daily.dev
=> feat: typed queries proposal

packages/shared/src/features/onboarding/steps/FunnelLoading.tsx
Having onTransition be a dependency in the useEffect that called it when the loading was finished caused an infinite re-render, which crashed the app.
> [!CAUTION]
https://fix-loading-screen-crash-after-c.preview.app.daily.dev
=> fix(funnels): remove dependency from useEffect

packages/shared/src/features/common/components/FormInputRating.spec.tsx, packages/shared/src/features/common/components/FormInputRating.tsx, packages/shared/src/features/onboarding/steps/FunnelQuiz.tsx
Align dependent on this [PR](https://github.com/dailydotdev/freyja/pull/19) as props not in the schema get filtered out.
Also added label support for "rating" type quiz. I removed the "label" from the actual rating buttons and just added the index there. There's nothing in the spec about allowing labels there, and considering their sizes, its not intended, so we will use labels purely for the first and last inputs (as is in editor) to show a min/max label.
> [!CAUTION]
https://quiz-fix.preview.app.daily.dev
=> feat(funnels): add align to quiz and rating labels

packages/shared/src/components/post/PostActions.tsx
The ConditionalWrapper with a SimpleTooltip causes the DOM to change and the list of actions to be refer to a non-existent node, causing the calculation to be wrong.
https://fix-award-overflow.preview.app.daily.dev
=> fix: ensure the adjustActions has the correct DOM when trying to calculate action width

packages/shared/src/components/Feed.spec.tsx, packages/webapp/__tests__/Callback.spec.tsx, packages/webapp/pages/callback.tsx
- What I observed from the recording that Denis sent, the auth is pushing through and the callback page is functioning. However, the listeners are not executing accordingly.
- I think the issue is something similar to the past issues where post message is not working as intended.
> [!CAUTION]
https://callback-webview-ig.preview.app.daily.dev
=> refactor: condition whether to send broadcast message

packages/shared/src/components/profile/ProfileButton.tsx
Wraps the Wallet button in the header in a Link to prevent hard navigate
https://ux-wrap-wallet-button-in-link.preview.app.daily.dev
=> fix: wrap Wallet button in header in `Link` to prevent hard-navigate

packages/webapp/next.config.ts
Adds a well-known URL redirect that is often used by password managers to link directly to the change password page of a website. It's just a simple redirect to whatever page we set.
https://well-known/change-password.preview.app.daily.dev
=> feat: `/.well-known/change-password`

packages/shared/src/features/onboarding/shared/SocialRegistration.tsx, packages/shared/src/features/onboarding/types/funnelEvents.ts
Add missing `data-funnel-track` property to social registration buttons so we can track them
https://signup-funnel-track.preview.app.daily.dev
=> fix(funnels): missing data-funnel-track for social signup

packages/shared/src/components/modals/common/ModalSidebar.tsx
The feed setting modal (ModalSidebar) needs to scroll only the content section.
Mentioned here:
https://dailydotdev.slack.com/archives/C01L0QXQJNB/p1741507698404249
> [!CAUTION]
https://fix-overscroll-modal.preview.app.daily.dev
=> fix: overscroll modal

packages/shared/src/components/ProfileMenu/sections/AccountSection.tsx, packages/shared/src/components/profile/ProfileButton.spec.tsx
Temporarily revert Settings in profile menu to open Customize modal until the new settings pages are in place.
https://tmp-fix-show-customize.preview.app.daily.dev
=> fix(tmp): open customize on profile menu settings

packages/shared/src/components/comments/CommentAuthor.tsx, packages/shared/src/components/comments/CommentContainer.tsx, packages/storybook/stories/components/comments/CommentContainer.stories.tsx
We needed a double truncate here.
Due to the award option had to re-arrange some sections and pull the date apart as it always shows fully.
The username & name can now truncate both.
After fix:
> [!CAUTION]
https://fix-truncating.preview.app.daily.dev
=> fix: double truncating on comment section

packages/shared/src/features/onboarding/shared/utils.ts, packages/shared/src/features/onboarding/steps/FunnelRegistration.tsx, packages/webapp/pages/callback.tsx
- Same issue fixed here: https://github.com/dailydotdev/apps/commit/bbeafdaf720db4309d298b7a65061fe0fa0dfc68
- Where the user is trying to login with an email that is already associated with another account.
- The only difference here, this is to fix the redirect flow because we now have to support auth for both redirect and callback postMessage :hide_the_pain:
- Context: when a user from Facebook in-app browser tries to login, and the case above happened, the user should be redirected to the params we sent (`redirect_to` or `return_to`) - those params when initializing a flow will only be utilized when the flow was successful. With the edge case above, it is considered a failed flow so the redirection falls back to our callback page instead of the redirect params we sent.
- Using session …
=> fix: in-app redirect existing email

packages/shared/src/features/onboarding/shared/FunnelStepper.tsx, packages/shared/src/features/onboarding/types/funnel.ts
- default is hidden
> [!CAUTION]
https://feat-remove-cookie-banner.preview.app.daily.dev
=> feat: add support for conditional cookie consent banner display

packages/shared/src/components/ProfileMenu/sections/AccountSection.tsx, packages/shared/src/components/profile/ProfileButton.spec.tsx
Temporarily re-adds account details icon to profile menu dropdown
https://tmp-fix-profile-dropdown.preview.app.daily.dev
=> fix: temporarily add account details item

packages/shared/src/components/auth/RegistrationForm.tsx, packages/shared/src/lib/auth.ts
- Disable the create account button while Cloudflare Turnstile has not loaded.
- Fix the eslint hook disable rule
- Show an error if Turnstile is not loaded after 5 seconds
https://dailydotdev.slack.com/archives/C01L0QXQJNB/p1745824704486649
https://fix-turnstile-disable-create-acc.preview.app.daily.dev
=> fix: disable button and show error if Turnstile is not loaded

packages/shared/src/components/modals/award/GiveAwardModal.tsx
Missed this check for plural/singular on post awards count, we have it already on comments.
> [!CAUTION]
https://fix-awards-count-plural.preview.app.daily.dev
=> fix: awards count plural

packages/webapp/pages/settings/subscription.tsx
Fix the manage subscription button link for iOS app so that it does not open Paddle in background
https://fix-settings-subscription-manage.preview.app.daily.dev
=> fix: use proper link for manage subscription on subscription settings page

packages/shared/src/contexts/payment/Paddle.tsx, packages/shared/src/hooks/usePaddlePayment.ts
The paddle refactor introduced an issue that caused `complete checkout` coming from Plus to not include the target type property. This is now fixed and I set target type as required field
https://complete-checkout-fix.preview.app.daily.dev
=> fix: send target type with complete checkout

packages/shared/src/components/ProfileMenu/sections/MainSection.tsx, packages/shared/src/components/credit/BuyCreditsButton.tsx, packages/shared/src/components/profile/ProfileSettingsMenu.tsx
Noticed that new settings did not have cores check for cores UI.
> [!CAUTION]
https://fix-cores-settings.preview.app.daily.dev
=> fix: hide cores settings ui if user has no access

packages/shared/src/components/ProfileMenu/ProfileMenu.tsx, packages/shared/src/components/ProfileMenu/sections/AccountSection.tsx, packages/shared/src/components/ProfileMenu/sections/MainSection.tsx, packages/shared/src/components/profile/ProfileButton.spec.tsx, packages/shared/src/components/profile/ProfileSettingsMenu.tsx
- Add route change event listener to close profile menu on route change
- Moves the logout section into `accountPageItems` and reduce code duplication
- Use the correct URLs for settings pages
https://fix-close-profile-menu.preview.app.daily.dev
=> fix: close profile menu on route change

packages/shared/src/components/cards/common/WelcomePostCardFooter.tsx, packages/shared/src/features/onboarding/shared/utils.ts
- For some reason, the build on storybook fails due to importing the sanitize directly from the package.
- Although it is kinda better because we have a common function that we use properly when sanitizing content.
- I think there is a deeper issue with package compats with storybook and our app, although I don't think it is worth half a day of investigation just to fix it.
> [!CAUTION]
https://chore-storybook.preview.app.daily.dev
=> fix: storybook

packages/shared/src/components/onboarding/Plus/OnboardingPlusControl.tsx, packages/shared/src/components/onboarding/Plus/OnboardingPlusVariation.tsx, packages/shared/src/lib/featureValues.ts
- We removed the annual special and the comparison card was dependent to it. Made the state kept at loading.
- Quick fix is to set it to annual, later on we can add this as a configuration.
> [!CAUTION]
https://fix-onboarding.preview.app.daily.dev
=> fix: use annual for the card comparison

packages/shared/src/components/UpgradeToPlus.tsx, packages/shared/src/lib/func.ts
- Add a check if `ios` exists in document class list
- Render the `UpgradeToPlus` button on iOS native
https://fix-detect-ios.preview.app.daily.dev
=> fix: add step to `isIOSNative` and render `UpgradeToPlus` btn on iOS

packages/shared/src/features/onboarding/shared/FunnelStepCtaWrapper.tsx, packages/shared/src/features/onboarding/steps/FunnelFact/FunnelFactWrapper.tsx, packages/shared/src/features/onboarding/types/funnel.ts, packages/shared/src/styles/components/buttons.css
- Button ping animation based on configuration.
- The animation should inherit the color we are currently using. So both theme should work as intended, even using specific colors we have for buttons.
- Since the animation was pretty simple, we didn't use Lottie as it would just add complexity for the simple animation.
Preview:
https://github.com/user-attachments/assets/fdbbd4ed-a89c-476d-8998-a4ec14ea0297
From the design team:
https://github.com/user-attachments/assets/8553b0e3-fa25-4d57-84ba-46447eae3abd
> [!CAUTION]
MI-898
https://mi-898-pulse.preview.app.daily.dev
=> feat: button ping animation

packages/shared/src/components/plus/PlusAdjustQuantity.tsx, packages/shared/src/components/plus/PlusInfo.tsx, packages/shared/src/components/plus/PlusProductToggle.tsx, packages/shared/src/contexts/BuyCoresContext.tsx, packages/shared/src/contexts/payment/BasePaymentProvider.tsx, packages/shared/src/contexts/payment/StoreKit.tsx, packages/shared/src/contexts/payment/context.ts, packages/shared/src/features/organizations/components/manageSeats/PreviewChanges.tsx, packages/shared/src/graphql/paddle.ts, packages/shared/src/hooks/usePaddlePayment.ts, packages/shared/src/hooks/useProductPricing.ts, packages/shared/src/lib/log.ts, packages/webapp/pages/plus/payment.tsx
- Adds tracking events to seat quantity component
- Add `plan_type` and `team_size` in extra for paddle events
- Refactor `plus/payment` page to use the `useProductPricingByIds` hook instead
- Refactor `PlusAdjustQuantity` to only have one on change definition
AS-1132
https://as-1132-analytics.preview.app.daily.dev
=> fix: add missing analytics events

packages/shared/src/components/plus/PlusAdjustQuantity.tsx
- Adds min-w-0 to the input wrapper
- Fix overflow on organization invite page
<table>
<tr>
<td>Before
<td>After
</tr>
<tr>
<td><img src="https://github.com/user-attachments/assets/3fa7f95a-cc58-45ef-a2e4-17578096ae7d">
<td><img src="https://github.com/user-attachments/assets/6f32f43c-af71-414c-9013-8abef145cf5b">
</tr>
<tr>
<td><img src="https://github.com/user-attachments/assets/0403086c-435e-42cc-b0d6-ac036fc509f5">
<td><img src="https://github.com/user-attachments/assets/566d118e-4722-46cf-8499-f00f2c673c31">
</tr>
</table>
https://fix-org-team-size-adjuster-input.preview.app.daily.dev
=> fix: min width on input field wrapper

packages/webapp/pages/join/organization.tsx
Forgot to actually commit this change in #4547 🙈 
- Fix overflow on organization invite page
<table>
<tr>
<td>Before
<td>After
</tr>
<tr>
<td><img src="https://github.com/user-attachments/assets/0403086c-435e-42cc-b0d6-ac036fc509f5">
<td><img src="https://github.com/user-attachments/assets/566d118e-4722-46cf-8499-f00f2c673c31">
</tr>
</table>
https://fix-org-team-size-adjuster-input.preview.app.daily.dev
=> fix: overflow on organization invite page

packages/webapp/pages/settings/organization/[orgId]/members.tsx
Use internal `Link` component for organisation member dropdown
https://fix-org-dropdown-link.preview.app.daily.dev
=> fix: use internal `Link` for dropdown

packages/shared/src/graphql/sources.ts, packages/shared/src/hooks/source/usePrivateSourceJoin.ts, packages/webapp/pages/sources/[source].tsx, packages/webapp/pages/squads/[handle]/index.tsx
Redirects to user page when tried to access user source as machine or squad source.
AS-1161
https://as-1161-hide-user-source.preview.app.daily.dev
=> fix: redirect user source to user page

packages/shared/src/components/cards/Freeform/FreeformList.tsx, packages/shared/src/components/cards/article/ArticleList.tsx, packages/shared/src/components/cards/common/PostCardHeader.tsx, packages/shared/src/components/cards/common/SquadPostCardHeader.tsx, packages/shared/src/components/cards/common/list/PostCardHeader.tsx, packages/shared/src/components/cards/share/ShareList.tsx, packages/shared/src/components/post/SquadPostContent.tsx, packages/shared/src/components/post/SquadPostWidgets.tsx
- Hides the source in post page when the source is user source
- Hides the source on list cards
- Hides the source on grid cards
AS-1162
https://as-1162-hide-source-icon.preview.app.daily.dev
=> feat: hide source when source is user source

packages/shared/src/components/post/PostItemCard.tsx
Show the correct source image in reading history for when the source is user. And add fallback to sharedPostTitle when there's no title
<table>
<tr>
<td>Before
<td>After
</tr>
<tr>
<td><img src="https://github.com/user-attachments/assets/0647bac7-590a-4cb5-94ed-bc50f7493a0e">
<td><img src="https://github.com/user-attachments/assets/531ee803-5720-43a3-a1f3-2f1a14a407e7">
</tr>
</table>
https://fix-reading-history.preview.app.daily.dev
=> fix: show correct source avatar in reading history

packages/shared/src/components/buttons/BookmarkButton.tsx, packages/shared/src/components/feeds/FeedNav.tsx, packages/shared/src/components/notifications/NotificationsBell.tsx
Currently the notification bell on tablet is quite buggy:
https://github.com/user-attachments/assets/0bc7b03a-d83d-4773-aaab-641eb76fcec2
This change fixes it and positions it top right:
https://github.com/user-attachments/assets/b8a9532f-9697-4cd5-ab50-2609ebf2a7c7
> [!CAUTION]
MI-931
https://mi-931.preview.app.daily.dev
=> fix: reposition notification bell on tablet

packages/shared/src/components/post/SquadPostAuthor.tsx, packages/shared/src/components/post/SquadPostContent.tsx
When post is from user source, we hade user role badge.
https://dailydotdev.slack.com/archives/C01L0QXQJNB/p1752069987089189
https://fix-hide-admin-user-source.preview.app.daily.dev
=> fix: hide source role when user source

packages/shared/src/hooks/input/useMarkdownInput.ts, packages/shared/src/lib/__tests__/markdown.test.ts, packages/shared/src/lib/markdown.ts
**Before the fix:**
Paste URL into `[](url)` selection → Results in `[]([url](https://example.com))`
**After the fix:**
Paste URL into `[](url)` selection → Results in normal paste behavior (no markdown link creation)
https://markdown-link-fix.preview.app.daily.dev
=> fix: pasting link to markdown

packages/shared/src/hooks/contentPreference/useContentPreference.ts, packages/shared/src/lib/log.ts
Before the fix: we passed the username/source name/etc
After the fix: we pass the type of entity as we should (user/tag/source/etc)
https://follow-events-fix.preview.app.daily.dev
=> fix: pass the right entity name to content preference functions

packages/shared/src/components/notifications/NotificationFollowUserButton.tsx, packages/shared/src/components/notifications/NotificationItem.tsx, packages/shared/src/components/notifications/utils.ts, packages/shared/src/components/sources/SourceActions/SourceActionsFollow.tsx
API: https://github.com/dailydotdev/daily-api/pull/2933
> [!CAUTION]
AS-1170
https://as-1170-user-follow-notification.preview.app.daily.dev
AS-1170
=> feat: user follow notification

packages/shared/src/components/modals/post/boost/BoostPostModal.tsx
- This thing should be two separate buttons.
- One points to the wallet, one opens the Cores Modal.
> [!CAUTION]
https://fix-wallet-button.preview.app.daily.dev
=> fix: modal header button to wallet

packages/shared/src/components/modals/award/BuyCoresModal.tsx
- Compared to Cores page where the openCheckout is called, in here at the Modal, we don't as long as `paddle` is not available which is always the case for iOS.
> [!CAUTION]
https://fix-mobile-checkout.preview.app.daily.dev
=> fix: ios cores checkout

packages/shared/src/components/post/PostSourceInfo.tsx, packages/shared/src/components/post/SquadPostContent.tsx
Issue with showing double follow button
(Basically if source is user type we shouldn't show the source one)
Also fixed minor truncate-overlap issue on mobile.
> [!CAUTION]
https://fix-user-source-styling.preview.app.daily.dev
=> fix: mobile user source issues solved

packages/shared/src/components/modals/post/boost/AdsDashboardModal.tsx, packages/shared/src/components/modals/post/boost/BoostPostModal.tsx, packages/shared/src/components/modals/post/boost/BoostedPostModal.spec.tsx, packages/shared/src/components/modals/post/boost/BoostedPostViewModal.tsx, packages/shared/src/components/modals/post/boost/common.ts, packages/shared/src/components/modals/utils/ActionSuccessModal.tsx, packages/shared/src/components/post/FixedPostNavigation.tsx, packages/shared/src/components/post/GoBackHeaderMobile.tsx, packages/shared/src/components/post/PostContent.tsx, packages/shared/src/components/post/PostHeaderActions.tsx, packages/shared/src/components/post/PostMenuOptions.tsx, packages/shared/src/components/post/PostSourceInfo.tsx, packages/shared/src/components/post/SquadPostContent.tsx, packages/shared/src/components/post/collection/CollectionPostContent.tsx, packages/shared/src/features/boost/BoostNewPostStrip.tsx, packages/shared/src/features/boost/BoostPostButton.tsx, packages/shared/src/features/boost/CampaignList.tsx, packages/shared/src/features/boost/CampaignListView.tsx, packages/shared/src/features/boost/useShowBoostButton.ts, packages/shared/src/graphql/actions.ts, packages/shared/src/graphql/post/boost.ts, packages/shared/src/hooks/post/usePostBoost.ts, packages/shared/src/hooks/post/usePostBoostEstimation.ts, packages/shared/src/hooks/post/usePostBoostMutations.ts, packages/shared/src/lib/constants.ts, packages/shared/src/lib/image.ts, packages/shared/src/styles/custom.ts, packages/shared/src/svg/TooltipArrow.tsx, packages/webapp/pages/squads/create.tsx
- I tried to separate the changes per commit, but the list below is the supposed changes.
- Flow change: creating a new post for "Everyone" should now redirect to the post page.
- Display the banner on **post page** (only) when the user has just posted something.
- Changed the color of the Boost button. Thankfully.
- BoostPostModal must have a link pointing to docs.
- After successfully boosting a post, we display a success state. The link to docs should be present there too as a secondary cta.
- Also updated the cover image for this UI.
- AdsDashboard modal must have the link pointing to the docs page.
- Removed engagements metric.
- Replaced Clicks with Unique reach.
- Changed copy of the title.
- Changed copy of the description.
- Must have a link pointing to the docs page.
Hopefully …
=> feat: boost newly created post banner and modal adjustments

packages/shared/src/components/modals/post/boost/BoostPostModal.tsx, packages/shared/src/lib/constants.ts
- The new link does not yet point to anything. For now, we should use the initial rebrandly link until Sab fixes the new link. Basically they will point to the same thing.
> [!CAUTION]
https://fix-rebrandly-link.preview.app.daily.dev
=> fix: rebrandly link for boost docs

packages/extension/src/companion/App.tsx
Missed a `updateSquads` in the App.tsx for the companion.
https://fix-missing-updatesquads.preview.app.daily.dev
=> fix: add missing updateSquads to companion

packages/webapp/components/footer/FooterWrapper.tsx
Remove the comment section on brief posts
https://dailydotdev.slack.com/archives/C08R2QZJBDK/p1754736886608409
<table>
<tr>
<td>Before
<td>After
</tr>
<tr>
<td><img width="430" height="932" alt="image" src="https://github.com/user-attachments/assets/4a1372ec-a4aa-48e9-ab04-1c4e5e10d982" />
<td><img width="430" height="932" alt="image" src="https://github.com/user-attachments/assets/f113f1e0-e5f2-4c4e-92fe-26d1642181da" />
</tr>
</table>
https://fix-hide-comments-on-brief.preview.app.daily.dev
=> fix: hide comment input on brief posts on mobile

packages/shared/src/features/boost/useShowBoostButton.ts
Hide the post boost button on brief posts.
https://dailydotdev.slack.com/archives/C01L0QXQJNB/p1754737093684189
<table>
<tr>
<td>Before
<td>After
</tr>
<tr>
<td><img width="430" height="932" alt="image" src="https://github.com/user-attachments/assets/4a1372ec-a4aa-48e9-ab04-1c4e5e10d982" />
<td><img width="430" height="932" alt="image" src="https://github.com/user-attachments/assets/5dc400f6-031a-460f-9684-3ee2c11f46e0" />
</tr>
<tr>
<td><img width="762" height="200" alt="image" src="https://github.com/user-attachments/assets/f346b68c-1032-4c1d-987e-69628a0b811c" />
<td><img width="762" height="200" alt="image" src="https://github.com/user-attachments/assets/c3d3b197-f33b-4dc5-89bb-50587c4c5b47" />
</tr>
</table>
https://fix-hide-boost-button-on-brief.preview.app.daily.dev
=> fix: hide boost button on brief

packages/shared/src/components/cards/common/PostTags.tsx
Noticed a slight edge-case on the calculation, was .22 pixels off per tag, so increased to 20 for the very small tags (c, etc)
Solves:
https://github.com/dailydotdev/daily/issues/1929
> [!CAUTION]
https://fix-post-tags.preview.app.daily.dev
=> fix: adjust tag width for edge-case

packages/shared/src/components/notifications/EmailNotificationsTab.tsx, packages/shared/src/components/notifications/NotificationSwitch.tsx, packages/shared/src/hooks/notifications/useNotificationSettings.ts
The logic for the "unsubscribe all emails" button at the bottom of the email tab was reversed. it should be toggled ON when everything is unsubscribed, and OFF when one or more email notification types are subscribed.
I also disable it when its toggled on, since as far as I understand from the copy, toggling it off is not supposed to subscribe you to everything.
> [!CAUTION]
MI-972
https://mi-972.preview.app.daily.dev
=> fix: reverse functionality for the unsubscribe all emails button

packages/extension/src/newtab/App.tsx, packages/shared/src/graphql/users.ts, packages/shared/src/hooks/useCheckLocation.ts, packages/shared/src/lib/query.ts, packages/shared/src/lib/user.ts, packages/webapp/pages/_app.tsx
Thought I already opened this one 🤦 
Introduces the frontend call the set location once-off for now.
> [!CAUTION]
https://feat-store-location.preview.app.daily.dev
=> feat: store user location once-off for now

packages/shared/src/components/Feed.tsx, packages/shared/src/components/FeedItemComponent.tsx, packages/shared/src/components/marketingCta/MarketingCtaBriefing.tsx, packages/shared/src/components/marketingCta/common.tsx, packages/shared/src/graphql/actions.ts, packages/shared/src/lib/log.ts
- Added new marketing CTA component for briefing;
- Added log events for impression/dismiss card;
> [!CAUTION]
MI-969
https://mi-969-brief-retool-card.preview.app.daily.dev
=> feat: added new marketingCta brief card in myfeed

packages/shared/src/components/dropdown/DropdownMenu.tsx
<table>
<tr>
<td>Before
<td>After
</tr>
<tr>
<td><img width="280" height="291" alt="image" src="https://github.com/user-attachments/assets/99c56422-ea25-44a3-b2e0-83dc405d7ded" />
<td><img width="279" height="290" alt="image" src="https://github.com/user-attachments/assets/30ab8da8-57e4-46a7-85af-7dd1a43a3207" />
</tr>
<tr>
<td><img width="165" height="74" alt="image" src="https://github.com/user-attachments/assets/dfa56e8c-7a88-40b0-9aab-d3f872776d49" />
<td><img width="165" height="74" alt="image" src="https://github.com/user-attachments/assets/10d07ac4-6734-4231-a354-5873e49f167b" />
</tr>
</table>
https://hug-a-pixel.preview.app.daily.dev
=> fix: dropdown menu pixel sticking out 🤗 

packages/shared/src/components/post/brief/BriefPostContent.tsx
Hope I covered all versions as there is many 😅
We should always apply the top padding not sure why it wasn't.
Also moved the alert box inside the render basically. (it was only inside 1 header bit)
> [!CAUTION]
https://fix-briefing-padding.preview.app.daily.dev
=> fix: small issue with briefing padding and alert placement

packages/shared/src/graphql/users.ts
Was confused why I saw queries for User when on notification preferences
`User` -> `NotificationSettings`
=> fix: name of notificationSettings query

packages/shared/src/lib/config.ts, packages/webapp/pages/onboarding.tsx
- There are two changes here:
- First, when using GitPod, we bypass auth and set a test user. This means onboarding should never be hit. It would just confuse GitPod users.
- Second is the long standing issue that server-side requests were not working due to CORS. We should call API directly to avoid CORS issues in these situations.
- Verified the changes and worked as intended.
> [!CAUTION]
https://chore-gitpod-env.preview.app.daily.dev
=> fix: gitpod env on server-side pages and improved experience

packages/shared/src/features/boost/BoostedViewModal.tsx
- Since we omit sensitive data when sending back campaign by id, this might break the modal since it won't have access to the properties we need to display.
> [!CAUTION]
https://fix-boost-notification.preview.app.daily.dev
=> fix: non-author viewing boosted modal

packages/webapp/components/layouts/OpportunityProtectedLayout.tsx, packages/webapp/pages/opportunity/[id]/decline.tsx, packages/webapp/pages/opportunity/[id]/done.tsx, packages/webapp/pages/opportunity/[id]/notify.tsx, packages/webapp/pages/opportunity/[id]/passive-done.tsx, packages/webapp/pages/opportunity/[id]/preference-done.tsx, packages/webapp/pages/opportunity/[id]/preference.tsx, packages/webapp/pages/opportunity/[id]/questions.tsx
Add a layer of protection so that you cannot directly access the accept/decline pages of an opportunity, you must go via listing page
https://fix-protect-accept-pages.preview.app.daily.dev
=> feat: add protections against directly accessing accept/reject pages

packages/shared/src/components/fields/DragDrop.tsx, packages/shared/src/features/fileUpload/hooks/useDragAndDrop.ts, packages/shared/src/features/fileUpload/hooks/useFileInput.tsx, packages/shared/src/features/fileUpload/hooks/useFileValidation.ts
I need to create a upload component that is just a button, and to not duplicate the code, I've extracted the file validation and handling into re-usable hooks.
Also included some changes from #4778 like custom icon, remove file from list and spacing adjustments.
https://reusable-file-upload.preview.app.daily.dev
=> refactor: split DragDrop into re-usable hooks

packages/webapp/pages/_app.tsx, packages/webapp/pages/helloworld/index.tsx, packages/webapp/pages/onboarding.tsx
Adding `HydrationBoundary` to global app so we can [reduce boiler plate](https://tanstack.com/query/v5/docs/framework/react/guides/ssr#optional---remove-boilerplate), and automagically have option for hydration on a global level.
re disussion https://github.com/dailydotdev/apps/pull/4896#discussion_r2357870402
https://feat-global-hydration-boundary.preview.app.daily.dev
=> feat: add hydration boundary to _app

packages/shared/src/features/opportunity/queries.ts, packages/webapp/components/layouts/hydrationLayout.tsx, packages/webapp/pages/settings/job-preferences.tsx
Use ISR for fetching the initial autocomplete results. These keywords won't change often, so we can set high stale time and cache too.
AS-1209
https://as-1209-isr-initial-keywords.preview.app.daily.dev
=> feat: ISR fetch the initial keyword autocomplete

packages/shared/src/components/post/write/CreatePostButton.tsx, packages/webapp/__tests__/PostPage.tsx
- I think next week Monday should be an okay date to filter users created before that to participate.
> [!CAUTION]
MI-1013
https://mi-1013-user.preview.app.daily.dev
=> fix: show tooltip on existing users only

packages/shared/src/features/opportunity/components/ClearEmploymentAgreementButton.tsx, packages/shared/src/features/opportunity/components/ClearResumeButton.tsx, packages/shared/src/features/opportunity/components/UploadEmploymentAgreementButton.tsx, packages/shared/src/lib/log.ts
Some extra analytics events for uploading and clearing cv/ employment agreement. Not originally in taxonomy, but thought could be nice to have.
https://extra-analytics.preview.app.daily.dev
=> feat: add extra analytics for cv and employment agreement upload

packages/shared/src/components/post/write/CreatePostButton.tsx
- Month index on Date constructor from 9 is October. The check must be September :hide_the_pain:
> [!CAUTION]
https://fix-month-index.preview.app.daily.dev
=> fix: month index should've been september (8)

packages/shared/src/features/opportunity/components/CVOverlay.tsx
<table>
<tr>
<td>Before
<td>After
</tr>
<tr>
<td><img width="430" height="932" alt="image" src="https://github.com/user-attachments/assets/cc991c1f-0070-4613-8c61-43def57cb172" />
<td><img width="430" height="932" alt="image" src="https://github.com/user-attachments/assets/68d6d445-43e3-472c-b491-e7bc907f2757" />
</tr>
</table>
https://fix-cv-overlay-buttons.preview.app.daily.dev
=> fix: buttons on cv overlay for opportunity on mobile

packages/shared/package.json, packages/shared/src/features/onboarding/shared/FunnelStepCtaWrapper.tsx, packages/shared/tailwind.config.ts, packages/webapp/package.json, packages/webapp/pages/opportunity/[id]/index.tsx, pnpm-lock.yaml
(Reminds me of my first PR #587)
Adds a new tailwind util plugin for easily accessing the safe-area- env variables so that we don't need to do raw `style` props.
<table>
<tr>
<td>Before
<td>After
</tr>
<tr>
<td><img width="446" height="991" alt="image" src="https://github.com/user-attachments/assets/112dd7c3-f073-4ec3-a544-2930e268564e" />
<td><img width="446" height="991" alt="image" src="https://github.com/user-attachments/assets/50c4be95-956c-4365-9899-09b6695b46f9" />
</tr>
</table>
Additionally it fixes z issues on response buttons when being recruiter (edge-case)
https://fix-footer-on-mobile.preview.app.daily.dev
=> fix: add extra padding on mobile

packages/shared/src/hooks/input/useMarkdownInput.ts
We should early return if user is typing `:`+special character.
It basically means they not wanting the emoji completer.
See it in action:
https://github.com/user-attachments/assets/574c0d8e-c20a-4373-a32c-075b92fef7a1
Solves:
https://github.com/dailydotdev/daily/issues/1974
> [!CAUTION]
https://feat-emoji-regex-fix.preview.app.daily.dev
=> fix: emoji regex early return

packages/shared/src/components/marketingCta/MarketingCtaModal.tsx
If no tag is set we should still render a close button.
It will just be asbolute to not add more height above the text.
(Small overlap on really long words)
> [!CAUTION]
https://feat-marketing-cta-close.preview.app.daily.dev
=> fix: always add close to marketing CTA

packages/shared/src/components/tooltips/RecommendedEmojiTooltip.tsx, packages/shared/src/hooks/input/useMarkdownInput.ts
Since sometimes when you type, the top 5 results don't give you what you want, I decided to add a scroll and show more results
For example; Before, when you would type :heart - there was still a chance you got 5 results that weren't the ❤️ , so now you're stuck not being able to get the emoji.
Also added some functionality to scroll the window with the user's selected emoji (for keyboard support)
https://github.com/user-attachments/assets/89383f3b-570a-4b15-8359-ea0b346c982d
> [!CAUTION]
https://show-all-emoji-results.preview.app.daily.dev
=> feat: show more emoji results
