packages/shared/src/lib/featureManagement.ts
packages/webapp/pages/onboarding.tsx

AS-376 #done
https://as-376-cleanup-onboarding-flip.preview.app.daily.dev

chore: cleanup onboarding_flip experiment

---

packages/shared/src/components/post/PostEngagements.tsx
packages/webapp/pages/posts/[id]/edit.tsx
packages/webapp/pages/squads/create.tsx

- complete some actions on the frontend so squad checklist completes dynamically
- also fix redirect if title is changed of freeform/squad post
AS-380 #done
https://as-380-fix-squad-checklist.preview.app.daily.dev

fix: squad checklist steps completion

---

packages/webapp/pages/onboarding.tsx

https://fix-enable-hotjar.preview.app.daily.dev

fix: enable hotjar for a day :)

---

packages/shared/src/components/auth/AuthOptions.tsx
packages/shared/src/components/auth/AuthenticationBanner.tsx
packages/shared/src/components/auth/OnboardingRegistrationForm.tsx
packages/shared/src/lib/featureManagement.ts
packages/shared/src/lib/featureValues.ts

AS-390
<table>
<tr>
<td>Before
<td>After
<tr>
<td><img src=https://github.com/dailydotdev/apps/assets/1681525/29d91a35-aa33-4a90-ba7f-e1c96c22f98a>
<td><img src=https://github.com/dailydotdev/apps/assets/1681525/6495731f-5a85-41cc-a26f-69d85dbc2de3>
</table>
https://as-390.preview.app.daily.dev

feat: smaller onboarding banner

---

packages/shared/src/components/search/SearchPanel/SearchPanel.tsx
packages/shared/src/lib/featureManagement.ts
packages/shared/src/lib/func.ts

AS-392
<table>
<tr>
<td>Before
<td>After
<tr>
<td><img src="https://github.com/dailydotdev/apps/assets/1681525/9a042ab4-20f1-4e20-a269-f039643dc459">
<td><img src="https://github.com/dailydotdev/apps/assets/1681525/543c8bbe-6b32-455c-91cc-b81af694ca5d">
</table>
https://as-392-search-google-cleanup.preview.app.daily.dev

fix: cleanup `search_google` experiment

---

packages/webapp/pages/onboarding.tsx

https://fix-turn-off-hotjar.preview.app.daily.dev

fix: turn off hotjar tracking

---

packages/webapp/next.config.js

For fun, that's all. 🤓
[X-Recruiting header](https://protocolguard.com/resources/what-is-the-x-recruiting-header/)
```
❯ curl -I https://x-recruiting.preview.app.daily.dev/
HTTP/2 200
...
x-recruiting: We are hiring! Check https://daily.dev/careers for more info!
```
https://x-recruiting.preview.app.daily.dev

feat: `X-Recruiting` header 😈

---

packages/shared/src/components/search/SearchPanel/SearchPanel.tsx
packages/shared/src/lib/featureManagement.ts

AS-401 #done
https://as-401-cleanup-search-sources.preview.app.daily.dev

chore: cleanup experiment search_sources

---

packages/shared/src/components/cards/list/PlaceholderList.tsx

- Small fix to ensure mobile rendering.
In action both sides:
AS-404 #done
https://as-404-placeholder-list-fix.preview.app.daily.dev

fix: placeholder list mobile

---

packages/shared/src/graphql/sources.ts

- Another issue with fragment changes :'( 
AS-406 #done
https://as-406-source-redirector.preview.app.daily.dev

fix: type was removed from this fragment :(

---

packages/shared/src/components/feeds/MobileFeedActions.tsx
packages/shared/src/components/post/GoBackHeaderMobile.tsx
packages/shared/src/components/profile/Header.tsx
packages/shared/src/components/profile/ProfileButton.tsx
packages/shared/src/hooks/useActiveNav.tsx
packages/shared/src/lib/featureManagement.ts
packages/webapp/components/footer/FooterNavBarTabs.tsx

Moves notifications to bottom
AS-398
https://as-398-notification-micro.preview.app.daily.dev

feat: add notifications on footer on mobile

---

packages/shared/src/components/ProfileMenu.tsx

- decision here https://dailydotdev.slack.com/archives/C01L0QXQJNB/p1719414471930779?thread_ts=1719400618.669299&cid=C01L0QXQJNB
https://fix-change-account-icon.preview.app.daily.dev

fix: change account details icon

---

packages/webapp/components/FooterNavBar.tsx
packages/webapp/components/footer/FooterNavBarTabs.tsx
packages/webapp/components/footer/FooterPlusButton.tsx

- Fixes the copy of the notifications button
- Fixes the post button to be centered
- Fixes multiple copies of notifications button
https://as-398-fix.preview.app.daily.dev

fix: minor fixes for notifications on bottom

---

packages/shared/src/components/auth/OnboardingLogs.tsx
packages/webapp/pages/onboarding.tsx
packages/webapp/public/scripts/fb.js
packages/webapp/public/scripts/gtag.js
packages/webapp/public/scripts/reddit.js
packages/webapp/public/scripts/tiktok.js
packages/webapp/public/scripts/twitter.js

Send user id as part of the pixel to better match it with our data. Also refactored a bit
https://improve-pixels.preview.app.daily.dev

refactor: improve pixels data

---

.github/pull_request_template.md

- update template and hides some details if not needed
https://chore-pr-template-update-2.preview.app.daily.dev

Chore pr template update 2

---

packages/shared/src/components/profile/ProfileSettingsMenu.tsx
packages/storybook/stories/drawers/NavDrawer.stories.tsx

This page got removed a while back
> [!CAUTION]
<!--
Copy and paste the below line outside the HTML comment tags to link this PR to the ticket in Jira
AS-418 #done 
https://as-418-remove-other-settings.preview.app.daily.dev

fix: page got removed a while back

---

packages/shared/src/components/feeds/MobileFeedActions.tsx
packages/shared/src/components/profile/Header.tsx
packages/shared/src/components/profile/ProfileWidgets.spec.tsx
packages/shared/src/hooks/useActiveNav.tsx
packages/shared/src/lib/featureManagement.ts
packages/webapp/components/FooterNavBar.tsx
packages/webapp/components/footer/FooterNavBarTabs.tsx

> [!CAUTION]
https://as-417-cleanup-notifications-nav-bar.preview.app.daily.dev

fix: cleanup notifications_nav_bar

---

packages/shared/src/components/auth/AuthenticationBanner.tsx
packages/shared/src/lib/featureManagement.ts
packages/shared/src/lib/featureValues.ts

Cleanup lost experiment: onboarding_banner
> [!CAUTION]
AS-422 #done 
https://as-422-cleanup-onboarding-banner.preview.app.daily.dev

chore: cleanup lost onboarding_banner

---

packages/shared/src/components/Logo.tsx
packages/shared/src/components/onboarding/OnboardingHeader.tsx

- Logo non clickable on onboarding pages
Did you introduce any new experiments? No
> [!CAUTION]
MI-407 #done
https://mi-407-logo-non-clickable.preview.app.daily.dev

feat: make logo disabled in onboarding pages

---

packages/shared/src/components/comments/AdAsComment.tsx
packages/shared/src/components/post/PostEngagements.tsx
packages/shared/src/lib/featureManagement.ts
packages/shared/src/lib/featureValues.ts

Cleanup ads_post_page experiment (it won)
Small fix for ads with short description (bottom 2 lines should always be on a new row)
| ![image](https://github.com/dailydotdev/apps/assets/554874/26e7d5de-8021-4968-93a3-ad6e70b1f585) | ![image](https://github.com/dailydotdev/apps/assets/554874/42ca1248-9cd3-41af-a7ac-0689b282d61d) | 
> [!CAUTION]
AS-426 #done 
https://as-426-cleanup-ads-post-page.preview.app.daily.dev

fix: cleanup ads on post page

---

packages/shared/src/hooks/profile/useProfile.ts
packages/webapp/pages/[userId]/index.tsx

- The `useProfile` hook is used in different places, for some reason, if we use placeholderData, it triggers loop of re-rendering. I think it could be that the data referenced object is becoming unstable (highly unlikely though).
- To fix the issue, we used `initialData` which sets the returned object than using a placeholder object.
- Also applied StaleTime.
> [!CAUTION]
https://fix-profile.preview.app.daily.dev

fix: use profile hook looping reloads

---

packages/shared/__tests__/fixture/auth.ts
packages/shared/src/hooks/useLogin.ts
packages/shared/src/lib/kratos.ts
packages/webapp/pages/account/security.tsx

- The primary concern here is the `email` on security page not being displayed.
- After further investigation, it seems the result of the API has been changed. This resulted in null values since it was accessing the wrong object properties.
- Also made verify session modal broken in some sense (after verification, nothing would happen, but if you close the modal, and re-verify, it would work since you finished the verification. Just the result was not accurate).
> [!CAUTION]
MI-411 #done
https://mi-411.preview.app.daily.dev

fix: whoami returned object mapping

---

packages/shared/src/components/auth/SocialRegistrationForm.tsx
packages/shared/src/lib/auth.ts

Added a length check on the experienceLevel (to be safe)
Also added a track below the hint checks so we can see what actually gets parsed (omitting all sensitive data)
> [!CAUTION]
https://hotfix-signup-tracking.preview.app.daily.dev

hotfix: signup form tracking

---

packages/shared/src/hooks/utils/useShortcuts.ts

Allow new shortcuts to render for team
> [!CAUTION]
https://hotfix-enable-shortcut-team.preview.app.daily.dev

fix: re-enable shortcuts for team members

---

packages/shared/src/components/RelatedSources.tsx
packages/shared/src/lib/errors.ts
packages/webapp/pages/sources/[source].tsx
packages/webapp/pages/sources/index.tsx
packages/webapp/pages/tags/index.tsx
packages/webapp/pages/users.tsx

Inspired by Ante, decided to see how bad apps repo was 
This is just a small portion of type safety :) 
> [!CAUTION]
https://chore-strict-first-batch.preview.app.daily.dev

chore: first part of strict mode enabling

---

packages/shared/src/hooks/vote/useVote.ts

Move to state for now, validated it works, but we can always switch if people have other ideas.
> [!CAUTION]
https://hotfix-voting.preview.app.daily.dev

fix: voting on comments

---

packages/shared/src/hooks/useBookmarkProvider.ts
packages/shared/src/lib/featureManagement.ts

Cleanup bookmark_provider experiment it won.
> [!CAUTION]
AS-434 #done
https://as-434-cleanup-bookmark-provider.preview.app.daily.dev

chore: cleanup bookmark_provider experiment

---

packages/shared/src/components/footer/FooterLinks.tsx
packages/shared/src/lib/featureManagement.ts

Experiment won, can be cleaned up
> [!CAUTION]
AS-435 #done
https://as-435-cleanup-onboarding-links.preview.app.daily.dev

chore: cleanup onboarding_links experiment

---

packages/shared/src/components/cards/CollectionCard/CollectionCard.tsx

Action button placement was missing the top spacing.
Copied this from welcome post as they basically the same rendering.
| ![Screenshot 2024-07-08 at 14 01 31](https://github.com/dailydotdev/apps/assets/554874/bdd93088-7a12-43a6-9d5a-fef6b5fe0ea2) | ![Screenshot 2024-07-08 at 15 11 06](https://github.com/dailydotdev/apps/assets/554874/d0565f92-7a94-4482-bef8-27d4a1f96894) | 
> [!CAUTION]
AS-438 #done 
https://as-438-collection-action-placement.preview.app.daily.dev

fix: collection action button placement

---

packages/shared/src/components/fields/HourDropdown.tsx
packages/shared/src/components/fields/ImageInput.tsx
packages/shared/src/contexts/AuthContext.tsx
packages/shared/src/graphql/users.ts
packages/shared/src/lib/query.ts
packages/webapp/__tests__/AccountProfilePage.tsx
packages/webapp/components/layouts/AccountLayout/EmailForm.tsx
packages/webapp/pages/[userId]/posts.tsx
packages/webapp/pages/[userId]/replies.tsx
packages/webapp/pages/[userId]/upvoted.tsx
packages/webapp/pages/account/notifications.tsx
packages/webapp/pages/account/profile.tsx
packages/webapp/pages/account/security.tsx

Some more work around strict mode for webapp (so far)
> [!CAUTION]
https://chore-strict-v2.preview.app.daily.dev

fix: manage to do some more strict related items

---

packages/shared/src/components/checklist/GoPublicStep.tsx
packages/shared/src/components/squads/Details.tsx
packages/shared/src/components/squads/PublicSquadEligibilityCard.tsx
packages/shared/src/components/squads/PublicSquadSubmissionActions.tsx
packages/shared/src/hooks/squads/usePublicSquadRequests.ts

- created `PublicSquadSubmissionActions`;
- added missing cta for public request in checklist;
- implemented component for shared logic;
- fixed wrong condition in `isQueryEnabled`  on `Details.tsx`;
> [!CAUTION]
https://mi-439-application-for-public-squad-doesn-t-work.preview.app.daily.dev

fix: application for public squad

---

packages/shared/src/components/post/write/SquadsDropdown.tsx
packages/shared/src/components/squads/SquadPageHeader.tsx
packages/shared/src/components/withFeaturesBoundary.tsx
packages/shared/src/graphql/squads.ts
packages/shared/src/hooks/squads/usePublicSquadRequests.ts
packages/shared/src/hooks/squads/useSquad.ts
packages/shared/src/lib/constants.ts
packages/webapp/pages/roast.tsx
packages/webapp/pages/search/chat/index.tsx
packages/webapp/pages/search/posts/index.tsx
packages/webapp/pages/squads/[handle]/[token].tsx
packages/webapp/pages/squads/[handle]/edit.tsx
packages/webapp/pages/squads/[handle]/index.tsx
packages/webapp/pages/squads/create.tsx
packages/webapp/pages/squads/index.tsx

Revert "chore: round 3 of tsc"

---

packages/webapp/pages/welcome/index.tsx

Forgot to push commit for noindex for `/welcome`
> [!CAUTION]
<!--
Copy and paste the below line outside the HTML comment tags to link this PR to the ticket in Jira
AS-410

feat: noindex welcome page

---

packages/webapp/pages/welcome/index.tsx

Update to match design.
Before:
After:
> [!CAUTION]
<!--
Copy and paste the below line outside the HTML comment tags to link this PR to the ticket in Jira
AS-410
https://as-410-welcome-page-margin.preview.app.daily.dev

feat: adjust sign up cta margin/size

---

packages/shared/src/hooks/vote/useVote.ts

- The primary issue was the upvote not working.
- To temporarily fix, we use the state instead.
- After further investigation, there seems to be a race condition when using the `isLoading` from the same mutation. Since we are using the `isLoading` from the same mutation, instantly after calling it (before reaching the first line of the function), the state has already updated that `isLoading` is `true` in turn, it just returns early on.
- Introduced a wrapper function to handle the `isloading` beforehand.
> [!CAUTION]
https://mi-436.preview.app.daily.dev

refactor: usage of isloading within the same mutation

---

packages/shared/src/components/MainFeedLayout.tsx
packages/shared/src/components/header/FeedExploreHeader.tsx

Related to new feed explore on actual device there was some overscroll.
Need to e2e test now, but should work.
> [!CAUTION]
https://hotfix-tabbar-overflow.preview.app.daily.dev

fix: noticed a small overflow on actual device.

---

packages/shared/src/lib/index.ts
packages/shared/src/lib/links.ts
packages/webapp/pages/welcome/index.tsx

> [!CAUTION]
https://welcome-page-preserve-query.preview.app.daily.dev

feat: preserve query on automatic welcome redirect

---

packages/webapp/pages/welcome/index.tsx

`version` & `ranking` were missing
> [!CAUTION]
https://welcome-page-feed-variables.preview.app.daily.dev

feat: update welcome page feed variables

---

packages/shared/src/components/cards/ArticlePostCard.spec.tsx
packages/shared/src/components/cards/CollectionCard/CollectionCard.spec.tsx
packages/shared/src/components/cards/PostTags.tsx
packages/shared/src/components/cards/SharePostCard.spec.tsx
packages/shared/src/components/cards/list/CardCover.tsx
packages/shared/src/hooks/feed/useFeedTags.ts

- Introduced some calculations to identify how many tags we can put.
- ~~This is only applied to list mode, as per spec, but we can actually use this on cards as well. I think it is better to consolidate the calculation.~~
- Both cards and list will use the same calculation as it is based on what value you will pass to the hook.
- Feel free to test on preview.
Preview:
> [!CAUTION]
MI-448 #done
https://mi-448.preview.app.daily.dev/
https://mi-448.preview.app.daily.dev

fix: max count on card tags

---

packages/shared/src/components/cards/common/SquadPostCardHeader.tsx

- Fix squad post image in feed for the experiment.
> [!CAUTION]
https://fix-author-image.preview.app.daily.dev

fix: squad post image in feed

---

packages/webapp/pages/posts/index.tsx
packages/webapp/pages/sources/index.tsx
packages/webapp/pages/tags/index.tsx
packages/webapp/pages/users.tsx

- Adds missing SEO for a few pages
https://dailydotdev.slack.com/archives/C01L0QXQJNB/p1721679355829699
> [!CAUTION]
https://fix-seo.preview.app.daily.dev

fix: add missing SEO for leaderboard page

---

packages/shared/src/components/cards/list/CardCover.tsx
packages/shared/src/hooks/feed/useCardCover.tsx

- Fix the copy based on the discussion.
- Also noticed an issue with the image when overlay is displayed.
Image issue before:
bookmarked state
normal state:
After the fix:
bookmarked state:
normal state:
> [!CAUTION]
https://fix-reminder-title.preview.app.daily.dev

fix: bookmark reminder overlay copy

---

packages/shared/src/components/cards/WelcomePostCard.tsx
packages/shared/src/components/cards/common/SquadPostCardHeader.tsx

- Make freeform cards look similar to article cards.
Quick link: https://mi-452.preview.app.daily.dev/squads/devtools
> [!CAUTION]
https://mi-452.preview.app.daily.dev

fix: post metadata on experiment for author image

---

packages/webapp/pages/account/profile.tsx

- refetch profile after update, noticed when testing social links
- this is done by manually reloading the page (so that query client refetches)
- proper fix for this would be to utilize [on demand revalidation](https://nextjs.org/docs/pages/building-your-application/data-fetching/incremental-static-regeneration#on-demand-revalidation), verified this method works locally but I did not want to complicate here since revalidating could be expensive with the new Vercel pricing)
- the SSR cache will still contain old data for next 60s (due to ssr cache) but on hydration it changes to correct one
> [!CAUTION] …

feat: refetch profile after update

---

packages/shared/src/components/notifications/utils.ts

- Add the missing icon for bookmark reminder types
Preview:
> [!CAUTION]
https://fix-reminder-icon.preview.app.daily.dev

fix: bookmark reminder icon in notifications page

---

packages/webapp/__tests__/PostPage.tsx
packages/webapp/components/PostSEOSchema.tsx

No task, but noticed this more and more with our platform having more squads, I think sufficient fix so we don't have "null" in description on shared post.
> [!CAUTION]
https://fix-shared-seo-description.preview.app.daily.dev

fix: seo description of shared posts

---

packages/shared/src/components/cards/common/SquadPostCardHeader.tsx

- Fix the Source image size on post cards (grid layout).
- ~~TODO: test on prod.~~ looks good now.
> [!CAUTION]
MI-459
https://mi-459.preview.app.daily.dev

fix: source image for squad posts on card

---

packages/shared/src/components/post/common/PostContentReminder.tsx

- Fix the copy and the alignment.
Preview:
> [!CAUTION]
MI-467
https://mi-467.preview.app.daily.dev

fix: post content reminder copy and alignment

---

packages/shared/src/components/post/SharePostContent.tsx

<table>
<tr>
<td>Before
<td>After
<tr>
<td><img src="https://github.com/user-attachments/assets/084f9cf8-e34e-489e-8c8d-9a5dd2d72d1b">
<td><img src="https://github.com/user-attachments/assets/5f81c736-e08e-454e-9c17-c769f2a61de0">
</table>
> [!CAUTION]
https://fix-truncate.preview.app.daily.dev

fix: shared link title overflow

---

packages/shared/src/components/post/PostSummaryButton.tsx
packages/shared/src/hooks/utils/useThemedAsset.ts

- I noticed on Figma, the design team used static colors rather than using themed ones.
> [!CAUTION]
https://fix-pepper-bg.preview.app.daily.dev

fix: pepper bg across themes

---

packages/shared/src/hooks/usePersonalizedDigest.ts

- digest refetches on every mount, page navigation and so on due to missing stale time, added 5 minutes, it can be even more but it should suffice to not refetch all the time, and on any change we update cache locally from mutation
- a lot of hits can be seen in [tracing](https://console.cloud.google.com/traces/list?referrer=search&authuser=2&project=devkit-prod&pageState=(%22traceFilter%22:(%22chips%22:%22%255B%257B_22k_22_3A_22graphql.operation.name_22_2C_22t_22_3A10_2C_22v_22_3A_22_5C_22PersonalizedDigest_5C_22_22_2C_22s_22_3Atrue_2C_22i_22_3A_22graphql.operation.name_22%257D%255D%22),%22traceIntervalPicker%22:(%22groupValue%22:%22PT1H%22,%22customValue%22:null))) as well
> [!CAUTION]
> Please make sure …

feat: add stale time so digest does not refetch constantly

---

packages/shared/src/components/CloseButton.tsx
packages/shared/src/components/fields/ImageInput.tsx
packages/shared/src/components/post/freeform/write/WriteFreeformContent.tsx
packages/webapp/pages/account/profile.tsx

- Fix the relative position.
- Fix the title to "Remove image".
TODO:
- Test in preview
> [!CAUTION]
MI-458
https://mi-458.preview.app.daily.dev

fix: image input relative position to the remove button

---

packages/shared/src/components/MainFeedLayout.tsx
packages/shared/src/components/feeds/FeedNav.tsx
packages/shared/src/components/layout/MainLayoutHeader.tsx
packages/shared/src/components/search/SearchPanel/SearchPanelInput.tsx
packages/shared/src/components/sidebar/Sidebar.tsx
packages/shared/src/hooks/useActiveNav.tsx
packages/shared/src/lib/featureManagement.ts
packages/webapp/components/FooterNavBar.tsx
packages/webapp/components/footer/FooterNavBarTabs.tsx

Experiment `mobile_explore_tab` won and can be applied.
> [!CAUTION]
AS-478 #done 
https://as-478-cleanup-mobile-explore-tab.preview.app.daily.dev

chore: remove experiment as it won

---

packages/shared/src/components/layout/MainLayoutHeader.tsx

We should render the search bar for anonymous user
We already handle on click to open the signup modal.
> [!CAUTION]
https://fix-search-annonymous.preview.app.daily.dev

fix: add search bar for annonymous users

---

packages/shared/src/components/post/SquadPostWidgets.tsx

New copy provided by product.
> [!CAUTION]
https://as-482-squad-copy-change.preview.app.daily.dev

chore: update copy change

---

packages/shared/src/components/typography/Typography.tsx

Styles did not apply at all because of `classed` helper. 
> [!CAUTION]
https://fix-typography-classes.preview.app.daily.dev

fix: correctly apply typography classes

---

packages/shared/src/components/comments/AdAsComment.tsx
packages/shared/src/graphql/posts.ts

.
https://ad-bg-color.preview.app.daily.dev

fix: add provided bg color to ad in post page

---

.github/workflows/add-preview-domain.yml

https://fix-preview-domain-workflow.preview.app.daily.dev

fix: support empty PRs

---

packages/shared/src/hooks/source/useSourceActionsNotify.ts
packages/shared/src/lib/log.ts

- Add tracking event "source" type 
> [!CAUTION]
https://fix-notify-event-target-type.preview.app.daily.dev

fix: add target type;

---

packages/shared/src/components/cards/PostMetadata.tsx
packages/shared/src/components/post/PostContent.tsx
packages/shared/src/components/post/common.tsx
packages/shared/src/graphql/fragments.ts
packages/shared/src/graphql/posts.ts
packages/shared/src/lib/featureManagement.ts

Adds a domain exposure to modal/post page for articles.
> [!CAUTION]
https://as-493-post-domain-experiment.preview.app.daily.dev

feat: add origin_domain experiment

---

packages/shared/src/components/profile/ProfileWidgets.spec.tsx
packages/shared/src/components/profile/SocialChips.tsx
packages/shared/src/lib/log.ts

> [!CAUTION]
https://track-social-clicks.preview.app.daily.dev

feat: track social clicks

---

.github/workflows/add-preview-domain.yml
.github/workflows/remove-preview-domain.yml

https://fix-preview-max-length-of-the-su.preview.app.daily.dev

fix: truncate preview subdomain to max 32 chars

---

packages/webapp/next-seo.ts

Optimise default OG image - see thread https://dailydotdev.slack.com/archives/C02AA18RD1D/p1723099768261979?thread_ts=1722759609.853999&cid=C02AA18RD1D
https://chore-update-default-og.preview.app.daily.dev

chore: update default og

---

packages/shared/src/components/cards/ActionsButtons/ActionButtons.tsx
packages/shared/src/lib/featureManagement.ts

Cleanup card_downvote experiment (won)
> [!CAUTION]
AS-514 #done
https://as-514-cleanup-card-downvote.preview.app.daily.dev

chore: cleanup card_downvote experiment

---

packages/shared/src/components/ProfilePicture.tsx
packages/shared/src/components/squads/SquadHeaderBar.tsx
packages/shared/src/components/squads/SquadMemberShortList.tsx

Based on [thread](https://dailydotdev.slack.com/archives/C069XNYMDGV/p1723553196263239)  I adjusted styles a bit with CEO of the night. 
Before:
After:
> [!CAUTION]
https://squad-actions-styles.preview.app.daily.dev

feat: adjust styles for squad actions

---

packages/extension/src/companion/Companion.tsx
packages/shared/src/components/Greeting.tsx
packages/shared/src/components/Markdown.tsx
packages/shared/src/components/PostsSearch.tsx
packages/shared/src/components/drawers/Drawer.tsx
packages/shared/src/components/filters/TagsFilter.tsx
packages/shared/src/components/modals/SquadMemberModal.tsx
packages/shared/src/components/onboarding/FilterOnboardingV4.tsx
packages/shared/src/components/post/freeform/write/WriteFreeformContent.tsx
packages/shared/src/hooks/input/useDebouncedUrl.ts
packages/shared/src/hooks/log/useLogQueue.ts
packages/shared/src/hooks/search/useSearchProviderSuggestions.ts
packages/shared/src/hooks/streaks/useReadingStreak.ts
packages/shared/src/hooks/useDebounce.ts
packages/shared/src/hooks/useDebounceFn.spec.ts
packages/shared/src/hooks/useDebounceFn.ts
packages/shared/src/hooks/useInputFieldFunctions.ts
packages/shared/src/hooks/useProgressAnimation.ts
packages/shared/src/hooks/useRefreshToken.ts
packages/shared/src/hooks/useTagAndSource.ts
packages/shared/src/hooks/useTimedAnimation.ts
packages/shared/src/hooks/useTimer.ts
packages/shared/src/lib/featureManagement.ts
packages/shared/src/lib/func.ts

Noticed our old useDebounce hook is more useDebounceFn,
in this case I just want a debounced value so added the normal version as well.
> [!CAUTION]
https://chore-search-debounce.preview.app.daily.dev

chore: add search debounce

---

packages/shared/src/lib/dateFormat.ts

Relative days per month was 28 should be 30.
```
A calendar month may contain 28 to 31 calendar days; the average is 30.437.
```
See also:
https://www.builder.io/blog/relative-time#:~:text=Here%20is%20one%20simple%20solution%20in%20TypeScript%3A
Tested on Ole-Martin's [original](https://dailydotdev.slack.com/archives/C01L0QXQJNB/p1722251208503719) issue and fixed it.
> [!CAUTION]
AS-525 #done 
https://as-525-relative-time-issue.preview.app.daily.dev

fix: relative month calculation

---

packages/shared/src/components/post/common/PostContentReminder.tsx
packages/shared/src/hooks/feed/useCardCover.tsx

I updated the read it later copy to `Don’t have time now? Set a reminder` 
https://hotfix-readt-it-later-copy.preview.app.daily.dev

hotfix: update the reading reminder copy

---

packages/webapp/next.config.js

> [!CAUTION]
https://sitemap-fix.preview.app.daily.dev

fix: rewrite sitemaps to the api

---

packages/shared/src/components/search/SearchPanel/SearchPanelSourceSuggestions.tsx

Give source handle priority in redirect
> [!CAUTION]
AS-530 #done 
https://as-530-source-handle-prio.preview.app.daily.dev

fix: give source handle priority in redirect

---

packages/webapp/next-seo.ts

Request here: https://dailydotdev.slack.com/archives/C02AA18RD1D/p1724209707037859
https://chore-update-og.preview.app.daily.dev

chore: update main og

---

packages/shared/src/components/filters/AdvancedSettings.tsx
packages/shared/src/components/filters/BlockedFilter.tsx
packages/shared/src/components/filters/ContentTypesFilter.tsx
packages/shared/src/components/filters/FilterSwitch.tsx
packages/shared/src/components/filters/SourceItemList.tsx
packages/shared/src/components/filters/SourceItemRow.tsx
packages/shared/src/components/filters/TagItemList.tsx
packages/shared/src/components/filters/TagItemRow.tsx
packages/shared/src/components/filters/TagsFilter.tsx

Agreed upon in https://github.com/dailydotdev/apps/pull/3469#discussion_r1725121813, just moving it separately so I don't bloat the changes in that PR. 
Basically spacings are now all the same across all filter views.
> [!CAUTION]
https://standardize-filter-spacing.preview.app.daily.dev

feat: standardize filter views spacing

---

packages/shared/src/components/modals/SubmitArticleModal.tsx

We support changing it from API already, but noticed this part was always hardcoded to 3 :) 
> [!CAUTION]
https://fix-make-alert-dynamic.preview.app.daily.dev

fix: make the limit alert dynamic

---

packages/shared/src/hooks/source/usePrivateSourceJoin.ts

Logged in users that were not part of squad would get 404 on private squad links shared from slack.
Basically I broke it in one of the last commits before slack release where I added `isLoggedIn` condition, now I removed that and also added guard so it only redirects you if you are not part of the squad.
> [!CAUTION]
https://fix-slack-join-logged-users.preview.app.daily.dev

fix: slack source join for logged in users

---

packages/shared/src/components/modals/SubmitArticleModal.tsx

Makes the alert copy dynamic:
Solves:
https://github.com/dailydotdev/daily/issues/1356
> [!CAUTION]
https://chore-fix-alert-copy.preview.app.daily.dev

chore: make alert copy dynamic

---

packages/shared/src/components/feeds/FeedNav.tsx
packages/shared/src/components/sidebar/Sidebar.tsx

See request:
https://dailydotdev.slack.com/archives/C077LGDK7AL/p1724420475989739?thread_ts=1724420235.221879&cid=C077LGDK7AL
> [!CAUTION]
https://chore-rename-new-feed.preview.app.daily.dev

chore: rename new feed to custom feed

---

packages/shared/src/components/streak/StreakReminderSwitch.tsx

Issue raised here: https://dailydotdev.slack.com/archives/C01L0QXQJNB/p1724668054704439
https://fix-text-overlap.preview.app.daily.dev

fix: text overlap

---

packages/shared/src/components/VerifiedCompanyUserBadge.tsx
packages/shared/src/components/profile/UserMetadata.tsx

Adds a tiny border around company badge icons
https://company-badge-border.preview.app.daily.dev

fix: add border to company images

---

packages/shared/src/components/cards/ArticlePostCard.spec.tsx
packages/shared/src/components/cards/Freeform/FreeformGrid.tsx
packages/shared/src/components/cards/Freeform/FreeformList.tsx
packages/shared/src/components/cards/PostCardFooter.tsx
packages/shared/src/components/cards/PostCardHeader.tsx
packages/shared/src/components/cards/common/SquadHeaderPicture.tsx
packages/shared/src/components/cards/common/SquadPostCardHeader.tsx
packages/shared/src/components/cards/list/PostCardHeader.tsx
packages/shared/src/lib/featureManagement.ts

Cleanup author_image - experiment inconclusive but it was decided to rollout
https://dailydotdev.slack.com/archives/C02JAUF8HJL/p1724745093905179
https://mi-513-author-image-cleanup.preview.app.daily.dev

chore: cleanup author_image

---

packages/shared/src/hooks/integrations/useSourceIntegrationQuery.ts

Noticed due to forbidden error (we limit only admins to access source slack integration) the `SourceIntegration` query would retry few times if you were not admin of squad.
In the changes I now ignore that status code as well as we did for not found. 
> [!CAUTION]

fix(slack): handle forbidden to avoid retry

---

packages/shared/src/graphql/fragments.ts
packages/shared/src/graphql/squads.ts

Noticed we not loading usershortinfo fragment everywhere
This fixes that, so we get all short info needs everyhwere
> [!CAUTION]
https://chore-user-short-info.preview.app.daily.dev

chore: fix user short info everywhere

---

packages/shared/src/graphql/fragments.ts
packages/shared/src/graphql/squads.ts

We have the ongoing date issue on sub sub queries,
so for now keeping the abstraction layer until we can fully resolve it to userShortInfo
> [!CAUTION]
https://chore-fix-companies-squads.preview.app.daily.dev

fix: company info on squads

---

packages/shared/src/components/cards/Leaderboard/CompanyTopList.tsx
packages/shared/src/components/cards/Leaderboard/LeaderboardListItem.tsx
packages/shared/src/graphql/leaderboard.ts
packages/webapp/pages/users.tsx

Adds company leaderboard to leaderboard page 
> [!CAUTION]
https://chore-add-company-leaderboard.preview.app.daily.dev

feat: add company leaderboard

---

packages/shared/src/graphql/common.ts
packages/shared/src/hooks/useFeed.ts
packages/shared/src/lib/query.ts

This will handle the garmr error and avoid retries when it happens.
Follow up will be dedicated error screen.
> [!CAUTION]
https://fix-handle-garmr-retry.preview.app.daily.dev

fix: handle garmr retry exclusion

---

packages/shared/src/components/search/SearchResults/SearchResultsLayout.tsx
packages/shared/src/hooks/useFeedLayout.ts
packages/shared/src/lib/featureManagement.ts

Cleanup (went for the easy way as it's least intrusive and keeps implementations)
> [!CAUTION]
AS-547 #done 
https://as-547-cleanup-search-list-mode.preview.app.daily.dev

chore: cleanup search list mode (won)

---

packages/webapp/public/scripts/gtag.js

https://ga-fixes.preview.app.daily.dev

fix: some google analytics fixes

---

packages/shared/src/components/squads/SquadHeaderBar.tsx
packages/shared/src/components/squads/SquadPageHeader.tsx
packages/shared/src/graphql/sources.ts

- Adjusted font size/colors/margins
- Smaller buttons for Public/Featured
- Added report toggle in squad menu
- Changed icon for public squads
> [!CAUTION]
https://mi-509-squad-header-changes.preview.app.daily.dev

feat: implement squad header changes

---

packages/shared/src/components/modals/streaks/StreakRecoverModal.spec.tsx
packages/shared/src/components/modals/streaks/StreakRecoverModal.tsx

- Basically moved from check in UI (alerts) to `displayToast` function call with the right args
- Other small changes to tests
> [!CAUTION]
https://fix-flacky-test-recover.preview.app.daily.dev

test: try to remove flaky tests

---

packages/shared/src/components/cards/squad/SquadList.tsx

- Change SquadList to make it consistent through mobile views
> [!CAUTION]
https://fix-squad-list-cta.preview.app.daily.dev

fix: try to change to secondary variant

---

README.md

fix typo in README.md 
I was in the process of setting up the project. I noticed the updated node version to 20.12 in the .nvmrc file. But it was not updated in the README.md 
> [!CAUTION]

fix typo: update README.md

---

packages/shared/src/components/tabs/TabList.tsx

> [!CAUTION]
https://fix-links-post-page.preview.app.daily.dev

fix: prevent anchor navigation on post page

---

packages/shared/src/components/auth/OnboardingSteps/EditTag.tsx
packages/webapp/pages/onboarding.tsx

- send the right props to create feed button on feed preview onboarding
MI-537 #done
https://mi-537-onboarding-feed-preview.preview.app.daily.dev

fix: button on feed preview section onboarding

---

packages/shared/src/components/modals/streaks/StreakRecoverModal.tsx
packages/shared/src/hooks/notifications/useStreakRecoverModal.ts
packages/shared/src/hooks/streaks/useStreakRecover.ts

Reverts dailydotdev/apps#3548
https://revert-3548-mi-465-alert-on-unpo.preview.app.daily.dev

Revert "feat: display message to user if recover no longer available;"

---

packages/webapp/pages/squads/discover/index.tsx

- Display squads both in featured and category carousel
> [!CAUTION]
https://mi-544-discover-page-not-showing.preview.app.daily.dev/squads/discover

feat: display squads both in featured and category carousel

---

packages/shared/src/components/RenderMarkdown.tsx
packages/shared/src/components/post/PostCodeSnippets.tsx
packages/shared/src/components/post/PostContent.tsx
packages/shared/src/lib/log.ts

Added the new events :) 
If yes please remove the comment HTML comment tags and fill the table below
Log the new/changed events below: (All post events :) )
| New | copy snippet  | extra: { ... } |
| New | next snippet  | extra: { ... } |
| New | previous snippet  | extra: { ... } |
> [!CAUTION]
https://fix-snippet-tracking-events.preview.app.daily.dev

fix: add snippet tracking events

---

packages/shared/src/components/HorizontalScroll/HorizontalScroll.spec.tsx
packages/shared/src/components/HorizontalScroll/HorizontalScrollHeader.tsx
packages/shared/src/components/HorizontalScroll/useCalculateVisibleElements.ts
packages/shared/src/components/HorizontalScroll/useHorizontalScrollHeader.spec.tsx
packages/shared/src/components/HorizontalScroll/useHorizontalScrollHeader.tsx
packages/webapp/__tests__/SourcePage.tsx
packages/webapp/__tests__/TagPage.tsx

- disables next button when there are not enough elements in the view (fixes tag/sources page horizontal scroll as well)
design decision [here](https://dailydotdev.slack.com/archives/C069XNYMDGV/p1726732424418799?thread_ts=1726649072.226739&cid=C069XNYMDGV)
> [!CAUTION]
MI-541 #done
https://mi-541-fix-scroll-actions.preview.app.daily.dev

Mi 541 fix scroll actions

---

packages/shared/src/components/contentPreference/FollowButton.tsx
packages/shared/src/components/modals/UserFollowingModal.tsx
packages/shared/src/components/profile/UserShortInfo.tsx
packages/shared/src/components/sources/SourceActions/SourceActionsFollow.tsx
packages/shared/src/components/sources/SourceActions/SourceActionsNotify.tsx
packages/shared/src/graphql/contentPreference.ts
packages/shared/src/graphql/fragments.ts
packages/shared/src/graphql/posts.ts
packages/shared/src/graphql/squads.ts
packages/shared/src/lib/user.ts

Known issue that we don't invalidate, Ante is working on this seperate.
> [!CAUTION]
AS-573 #done 
https://as-573-user-modal-list-follow.preview.app.daily.dev

feat: add follow button to user modal list

---

packages/shared/src/components/cards/squad/SquadsDirectoryFeed.tsx
packages/shared/src/components/cards/squad/UnfeaturedSquadGrid.tsx
packages/webapp/pages/squads/discover/[id].tsx
packages/webapp/pages/squads/discover/index.tsx

- make cards same
> [!CAUTION]
MI-542 #done
https://mi-542-fix-unfeatured-squad-card.preview.app.daily.dev

Mi 542 fix unfeatured squad card

---

packages/shared/src/components/ProfileMenu.tsx
packages/shared/src/components/feeds/MobileFeedActions.tsx
packages/shared/src/components/filters/FeedFilters.tsx
packages/shared/src/components/filters/FollowingFilter.tsx
packages/shared/src/components/layout/common.tsx
packages/shared/src/components/profile/UserShortInfo.tsx
packages/shared/src/hooks/useLazyModal.ts
packages/shared/src/lib/log.ts
packages/shared/src/lib/user.ts
packages/webapp/pages/account/notifications.tsx

- Add new tab in feed preferences
- Adds two new checkboxes for notifications
> [!CAUTION]
AS-579
https://as-579-settings.preview.app.daily.dev

feat: following tab in feed preferences

---

packages/shared/src/components/squads/layout/SquadDirectoryLayout.tsx

- wait for settings to load before showing anything
> [!CAUTION]
MI-545 #done
https://mi-545-fix-layout-shifts.preview.app.daily.dev

fix: layout shifts

---

packages/webapp/pages/squads/discover/[id].tsx
packages/webapp/pages/squads/discover/index.tsx

- mobile layout on categories
- title on mobile for categories
> [!CAUTION]
https://fix-mobile-layout-squad-categori.preview.app.daily.dev

fix: mobile layout squad categories

---

packages/shared/src/components/comments/CommentActionButtons.tsx
packages/shared/src/components/post/PostComments.tsx
packages/shared/src/components/post/useCommentContentPreferenceMutationSubscription.ts
packages/shared/src/hooks/auth/useIsSpecialUser.ts
packages/shared/src/lib/query.ts
packages/shared/src/lib/user.ts

- add comment option menu item
- add mutation subscription handler to update post comments cache
> [!CAUTION]
<!--
Copy and paste the below line outside the HTML comment tags to link this PR to the ticket in Jira
AS-570

feat: comment option follow

---

packages/shared/src/components/squads/settings/SquadCategoryDropdown.tsx

- Moved to `useSquadCategories` hook for dropdown
> [!CAUTION]
https://fix-category-dropdown.preview.app.daily.dev

fix: category dropdown

---

packages/shared/src/components/squads/settings/SquadDangerZone.tsx

- squad instead of account
https://fix-typo-squad-edit.preview.app.daily.dev

fix: typo squad

---

packages/shared/src/components/cards/squad/SquadsDirectoryFeed.tsx
packages/webapp/pages/squads/discover/my.tsx

- not show members in my squad https://dailydotdev.slack.com/archives/C069XNYMDGV/p1726872246644799
- button working on mobile https://dailydotdev.slack.com/archives/C069XNYMDGV/p1726897403685179 & https://dailydotdev.slack.com/archives/C069XNYMDGV/p1726898361240879
https://fix-public-squad-issues.preview.app.daily.dev

fix: button not clicking in mobile, members in my squads

---

packages/shared/src/components/squads/layout/SquadDirectoryLayout.tsx

- from nimrods request https://dailydotdev.slack.com/archives/C069XNYMDGV/p1726839965150909
https://fix-button.preview.app.daily.dev

fix: button to primary

---

packages/shared/src/components/post/PostSourceInfo.tsx

- Make the source handle clickable.
> [!CAUTION]
https://mi-548.preview.app.daily.dev

fix: source handle must be clickable

---

packages/shared/src/components/profile/ProfileTooltip.tsx

- Primary issue is that, the tooltip is attached to the parent, and the main container (modal) includes a hidden overflow property.
- This is one thing, getting cut off from the screen itself is a different issue on its own.
Like mentioned, cut off from the screen is entirely a different issue. The concern from this PR has been fixed as shown below:
Before fix:
After the fix:
> [!CAUTION]
https://mi-550.preview.app.daily.dev

fix: append devcard to body

---

packages/shared/src/hooks/profile/useProfile.ts

Ensure query only fires when we have the right data.
> [!CAUTION]
https://fix-profile-enabled.preview.app.daily.dev

fix: profile enabled query

---

packages/shared/src/components/PostOptionsMenu.tsx
packages/shared/src/components/comments/CommentActionButtons.tsx
packages/shared/src/components/contentPreference/FollowButton.tsx
packages/shared/src/components/filters/FollowingFilter.tsx
packages/shared/src/components/modals/SquadMemberModal.tsx
packages/shared/src/components/modals/UpvotedPopupModal.tsx
packages/shared/src/components/modals/UserFollowersModal.tsx
packages/shared/src/components/modals/UserFollowingModal.tsx
packages/shared/src/components/modals/UserListModal.tsx
packages/shared/src/components/modals/squads/PrivilegedMembersModal.tsx
packages/shared/src/components/post/PostWidgets.tsx
packages/shared/src/components/profile/UserList.tsx
packages/shared/src/components/profile/UserShortInfo.tsx
packages/shared/src/components/search/SearchResults/SearchResultsUsers.tsx
packages/shared/src/components/squads/SquadPageHeader.tsx
packages/shared/src/components/widgets/PostUsersHighlights.tsx
packages/shared/src/graphql/fragments.ts
packages/shared/src/hooks/contentPreference/types.ts
packages/shared/src/hooks/contentPreference/useContentPreference.ts
packages/shared/src/hooks/contentPreference/useSourceContentPreferenceMutationSubscription.ts
packages/shared/src/hooks/source/useSourceActionsNotify.ts
packages/shared/src/hooks/useTagAndSource.ts
packages/shared/src/lib/log.ts
packages/shared/src/lib/user.ts

- add events for follow (existing events just changed enum names so they are not source specific)
| Change | follow | extra: { origin: `user upvotes list` } |
| Change | follow | extra: { origin: `user followers list` } |
| Change | follow | extra: { origin: `user following list` } |
| Change | follow | extra: { origin: `follow filter` } |
> [!CAUTION]
AS-596
https://as-596-log-events.preview.app.daily.dev

feat: events for follow

---

packages/shared/src/components/post/write/SquadsDropdown.tsx

https://dailydotdev.slack.com/archives/C069XNYMDGV/p1727269027146849
https://fix-new-post-squad-creation.preview.app.daily.dev

Fix new post squad creation

---

packages/shared/src/components/squads/settings/PermissionSection.tsx

As per request https://dailydotdev.slack.com/archives/C02AA18RD1D/p1727269244960479
https://fix-oly-mod-post.preview.app.daily.dev

fix: change to only moderator post

---

packages/storybook/stories/atoms/ProfilePicture.stories.tsx
packages/storybook/stories/components/profile/ProfilePicture.stories.tsx

Added ProfilePicture component to Storybook
> [!CAUTION]
MI-554
https://storybook-git-mi-554-dailydotdev.vercel.app/?path=/story/components-profile-profilepicture--default

feat: Add ProfilePicture component to Storybook

---

packages/shared/src/components/post/write/SquadsDropdown.tsx
packages/shared/src/components/squads/settings/PermissionSection.tsx

https://github.com/dailydotdev/apps/pull/3591#pullrequestreview-2330253460
https://fix-oly-mod-post.preview.app.daily.dev

fix: add defaults to create new squad through post creation

---

packages/shared/src/components/cards/ActionsButtons/ActionButtons.tsx
packages/shared/src/components/cards/Leaderboard/UserTopList.tsx
packages/shared/src/components/cards/list/ActionButtons.tsx

Since it's a inline button the iconOnly doesn't trigger so with this fix we emulate it closer to what it does for the other button.
> Also fixed for the list mode
> [!CAUTION]
https://wt-2180-upvote-padding.preview.app.daily.dev

fix: upvote button size

---

packages/extension/package.json
packages/shared/package.json
packages/webapp/package.json
pnpm-lock.yaml

Update dependency :) 
Works locally
> [!CAUTION]
https://chore-up-react-swipeable.preview.app.daily.dev

chore: update react swipeable

---

packages/webapp/__tests__/AccountSecurityPage.tsx
packages/webapp/components/layouts/AccountLayout/EmailForm.tsx

The submit buttons in the form were calling "onClick" instead of "onSubmit", which prevented the HTML validation from triggering. However, when having two submit buttons in one form we have to differentiate between which one is clicked. Now there's a shared submit handler that checks the name of the submit button and calls the appropriate submit function.
> [!CAUTION]
MI-501
https://mi-501.preview.app.daily.dev

fix: HTML Email validator on account page fix

---

packages/shared/src/components/RenderMarkdown.tsx

Nimrod requested this small change to make it clearer
> [!CAUTION]
https://chore-copy-change.preview.app.daily.dev

chore: copy change

---

packages/shared/src/components/contentPreference/FollowButton.tsx
packages/shared/src/hooks/contentPreference/useContentPreference.ts
packages/shared/src/lib/auth.ts

Show follow button when not logged in
> [!CAUTION]
https://follow-button-anon.preview.app.daily.dev

feat: show follow button when anon

---

packages/shared/src/components/modals/post/CommentModal.tsx

- Fix comment modal on mobile
> [!CAUTION]
MI-566
https://fix-comment-mobile.preview.app.daily.dev

fix: comment modal on mobile

---

packages/shared/src/components/search/SearchPanel/SearchPanelInput.tsx
packages/shared/src/lib/featureManagement.ts

Introduced a feature for experimenting with search text, particularly placeholder in this case.
> [!CAUTION]
MI-564
https://mi-564.preview.app.daily.dev

feat: micro experiment search placeholder

---

packages/shared/src/components/filters/helpers.ts
packages/shared/src/graphql/feedSettings.ts

Frontend for showing the squad filter.
[squad-filter.webm](https://github.com/user-attachments/assets/fae8308b-b8ac-40e9-bab5-ba361822b5b0)
Related API:
https://github.com/dailydotdev/daily-api/pull/2304
> [!CAUTION]
AS-625 #done 
https://as-625-squad-filter.preview.app.daily.dev

feat: allow filtering of squads

---

packages/shared/src/lib/config.ts
packages/webapp/next.config.js

- Fix GitPod CORS issue by proxying the api.
- Tested in GitPod. Works as intended.
> [!CAUTION]
https://fix-gitpod.preview.app.daily.dev

fix: gitpod cors issue

---

packages/shared/src/components/sidebar/Sidebar.tsx

Url not working in extension
https://fix-url-extension.preview.app.daily.dev

fix: url for extension

---

packages/extension/src/newtab/App.tsx
packages/shared/__tests__/helpers/boot.tsx
packages/shared/src/components/Feed.spec.tsx
packages/shared/src/components/checklist/SharePostChecklistStep.tsx
packages/shared/src/components/modals/ArticlePostModal.tsx
packages/shared/src/components/modals/CollectionPostModal.tsx
packages/shared/src/components/modals/OnboardingModal.tsx
packages/shared/src/components/modals/SharePostModal.tsx
packages/shared/src/components/onboarding/FilterOnboardingStep.tsx
packages/shared/src/components/onboarding/IntroductionOnboarding.tsx
packages/shared/src/components/onboarding/index.ts
packages/shared/src/components/post/BasePostContent.tsx
packages/shared/src/contexts/OnboardingContext.tsx
packages/shared/src/graphql/feed.ts
packages/shared/src/hooks/useMyFeed.ts
packages/shared/src/hooks/useSquadChecklist.tsx
packages/storybook/stories/components/HorizontalScroll.stories.tsx
packages/storybook/stories/extension/ShortcutLinks.stories.tsx
packages/webapp/__tests__/SourcePage.tsx
packages/webapp/__tests__/SquadTokenPage.tsx
packages/webapp/__tests__/TagPage.tsx
packages/webapp/pages/_app.tsx
packages/webapp/pages/onboarding.tsx
packages/webapp/pages/posts/[id]/index.tsx

Reverts dailydotdev/apps#3619
Some reason now on production I don't get the onboarding flow 
https://revert-3619-as-631-cleanup-unuse.preview.app.daily.dev

Revert "chore: cleanup unused flow"

---

packages/shared/src/components/cards/Freeform/FreeformGrid.tsx
packages/shared/src/components/cards/Freeform/FreeformList.tsx
packages/shared/src/components/squads/SquadHeaderBar.tsx
packages/shared/src/components/squads/SquadPageHeader.tsx

No longer need the pulse animations (missed cleanup last time)
> [!CAUTION]
AS-634 #done 
https://as-634-remove-pulse-animations.preview.app.daily.dev

fix: remove pulse animations

---

packages/shared/src/components/PostOptionsMenu.tsx

> [!CAUTION]
https://fix-follow-option-me.preview.app.daily.dev

fix: hide option if user is yourself

---

packages/shared/src/components/TrustedCompanies.tsx

fix: 500K to 1M

---

packages/shared/src/components/auth/OnboardingRegistrationForm.tsx

- remove google auth from in app browsers
MI-594 #done
https://mi-594-remove-google-inapp.preview.app.daily.dev

fix: remove google auth from in app browsers

---

packages/extension/src/background/index.ts
packages/extension/src/newtab/App.tsx
packages/shared/src/lib/featureManagement.ts
packages/shared/src/lib/func.ts

- Enroll users only when the cache data is found.
> [!CAUTION]
https://fix-onboarding-enrollment.preview.app.daily.dev

fix: onboarding enrollment

---

packages/shared/src/components/modals/SlackIntegrationModal/useSlackIntegrationModal.ts

Next error if we don't make this conditional :(
> [!CAUTION]

fix: slack integration conditional eval

---

packages/webapp/pages/squads/create.tsx

> [!CAUTION]
https://fix-tslint.preview.app.daily.dev

fix: ts lint

---

packages/shared/src/components/filters/FollowingFilter.tsx
packages/shared/src/components/modals/UserListModal.tsx
packages/shared/src/components/profile/UserList.tsx

Default value for `UserList` was `true` which then shows follow button on places we don't need currently. 
> [!CAUTION]
https://fix-invite-friends-follow.preview.app.daily.dev

fix: follow button showing by default in user lists

---

packages/shared/src/components/notifications/utils.ts

Added the pending icon to notifications
> [!CAUTION]
MI-582
https://mi-582.preview.app.daily.dev

feat: Add pending notification icon

---

packages/shared/src/graphql/feed.ts

Send period to comment feed query.
Related: https://github.com/dailydotdev/daily-api/pull/2327
> [!CAUTION]
AS-644 #done 
https://as-644-period-filter-comment-fee.preview.app.daily.dev

fix: enable period filter on comment feed

---

packages/shared/src/components/post/freeform/write/WriteFreeformContent.tsx
packages/shared/src/components/post/write/ShareLink.tsx
packages/shared/src/contexts/WritePostContext.tsx
packages/webapp/pages/squads/create.tsx

Due to [this](https://github.com/dailydotdev/apps/pull/3644) fix we are now rendering both forms which share the same ID.
This conflicts with HTML validation making it so that mobile users couldn't post.
This solves: https://github.com/dailydotdev/daily/issues/1490
> [!CAUTION]
https://fix-new-post-mobile.preview.app.daily.dev

fix: mobile new post was rendering two forms with 1 button

---

packages/shared/src/components/cards/common/Card.module.css

This fixes the border radius issue on the article cards. (Issue- #1411)
> [!CAUTION]
AS-#1411 #done
or
MI-#1411 #done

fix: focus border radius for feed cards

---

packages/shared/src/contexts/PushNotificationContext.tsx

- We don't actually need the OneSignal SDK in the extension as it only works in webapp.
> [!CAUTION]
https://fix-onesignal.preview.app.daily.dev

refactor: onesignal condition to be not extension

---

packages/shared/src/components/fields/form/FormWrapper.tsx
packages/shared/src/components/fields/form/common.tsx
packages/shared/src/components/modals/report/ReportModal.tsx
packages/webapp/pages/posts/[id]/edit.tsx
packages/webapp/pages/squads/create.tsx

The mobile version had some missed issues:
- Edit posts didn't work due to missing formId ref
- Some modals where not always spanning full-width which I added to FormWrapper as it should apply to all mobile ones.
> [!CAUTION]
https://fix-mobile-fixes.preview.app.daily.dev

fix: couple mobile issues

---

packages/shared/src/components/post/SquadPostWidgets.tsx

Linked Issue: (https://github.com/dailydotdev/daily/issues/1496)
This fixes the text overflowing in the squad description when you post a link in the squad description. 
Note: I can't test this due to some issues that I have commented in the issue comments. But thanks to @omBratteng for giving the quick fix. this was assigned to me so I am just creating pr so this issue doesn't hang for a long time. Thanks.
> [!CAUTION]

fix: text overflow post side widget

---

packages/shared/src/contexts/BootProvider.tsx

- We have a function that stores data to the local storage when we update the data (called `updateLocalBootData` - the line above the fix). Before doing so, the function filters which properties should only be stored.
- The function does not exclude the `visit` property, and this property contains the session information that is sent along with other analytics properties.
- The property is removed when updating profile information (happens after onboarding), settings,  and/or alerts. Hence, it is noticeable in new users as we might be utilizing this property to filter new users data.
> [!CAUTION] …

fix: boot data analytics

---

packages/shared/src/components/MainFeedLayout.tsx
packages/shared/src/components/MainLayout.tsx
packages/shared/src/hooks/usePostById.ts
packages/webapp/components/layouts/MainFeedPage.tsx

- post pages (and other main layout pages) would return nothing in SSR due to `isAuthReady` always being false
- this fixes SEO missing
- also fixed loading condition for post hook to now show loading when initialData is available
- fix page level SEO not showing on feed layout pages (also improve first paint time for those)
- adjust sidebar so it renders only client side (aprox. after hydration) without blocking rest of the content
> [!CAUTION]
https://fix-ssr-blank-screen.preview.app.daily.dev

fix: ssr blank screen

---

packages/extension/package.json
packages/shared/package.json
packages/webapp/package.json
pnpm-lock.yaml

We actually don't use this anymore, so best to cleanup :) 
> [!CAUTION]
https://chore-remove-unused-dep.preview.app.daily.dev

chore: remove unused dependency

---

packages/extension/package.json
packages/shared/package.json
packages/webapp/package.json
pnpm-lock.yaml

Lots of breaking changes in 16, but so far doesn't seem like we use any.
Reading material: https://github.com/graphql/graphql-js/discussions/3346
> [!CAUTION]
https://chore-upgrade-graphql.preview.app.daily.dev

chore: upgrade graphQL

---

packages/eslint-config/package.json
packages/extension/package.json
packages/extension/tsconfig.json
packages/shared/package.json
packages/shared/src/hooks/useFeedLayout.ts
packages/shared/tsconfig.json
packages/storybook/package.json
packages/storybook/tsconfig.json
packages/webapp/package.json
packages/webapp/tsconfig.json
pnpm-lock.yaml

Trying to bump Typescript to latest
> [!CAUTION]
https://chore-typescript-bump.preview.app.daily.dev

chore: typescript bump

---

packages/shared/src/components/cards/common/list/CardCover.tsx

> [!CAUTION]
https://hotfix-replace.preview.app.daily.dev

fix: handle empty image properly

---

packages/shared/src/components/Feed.spec.tsx

Debugged locally and found some culprits 🤦 
Basically we fired 2 of the same mock, so 1 would always remain open and affect the test below.
Then I also decided to split in annonymous/logged in describes to have more seperation.
I do feel it can still be flaky in the whole suite when run concurrent, but let's see.
> [!CAUTION]
https://chore-fix-flaky-tests.preview.app.daily.dev

fix: flaky tests

---

packages/shared/src/components/modals/badges/TopReaderBadgeModal.tsx

Just minor code de-duplication
> [!CAUTION]
https://as-510-dedpulicate-functions.preview.app.daily.dev

feat: top reader badges

---

packages/shared/src/components/search/SearchPanel/SearchPanelDropdown.tsx

Fixes https://github.com/dailydotdev/daily/issues/1560
Issue was that `React` did not actually get imported, and was imported from a different package.
> [!CAUTION]
https://hotfix-import-react.preview.app.daily.dev

fix: import react in `SearchPanelDropdown`

---

packages/shared/src/components/profile/ActivitySection.tsx
packages/shared/src/components/profile/ReadingTagsWidget.tsx

This line is no longer applicable.
Also decided to clean the component as there's no further use for these elements. (legacy part anyway)
Solves:
https://github.com/dailydotdev/daily/issues/1358
> [!CAUTION]
https://fix-remove-activity-line.preview.app.daily.dev

fix: remove subtitle element

---

packages/shared/src/components/modals/BootPopups.tsx
packages/shared/src/components/modals/badges/TopReaderBadgeModal.tsx
packages/shared/src/hooks/modals/useTopReaderModal.ts
packages/shared/src/lib/log.ts

https://dailydotdev.slack.com/archives/C078JGTQ9AT/p1730516769731889?thread_ts=1730327620.162489&cid=C078JGTQ9AT
Added `origin` as extra
https://docs.google.com/spreadsheets/d/18Lv7zXges9QfVX5VYL1a-Hyl0e1sQ3sLr0OK8YZWKXI/edit?gid=1801144038#gid=1801144038
> [!CAUTION]
https://as-510-modal-origin.preview.app.daily.dev

feat: add origin to top reader modal log events

---

packages/shared/src/components/LazyImage.tsx

Small edge-case where props could be undefined, this is safer regardless.
(Raised via boundary error inspection)
> [!CAUTION]
https://hotfix-props-undefined.preview.app.daily.dev

fix: edge-case fix

---

packages/webapp/__tests__/PostPage.tsx

Hopefully fixes it
https://fix-disable-flaky-tests.preview.app.daily.dev

fix: temporarily disable flaky tests

---

packages/shared/src/components/cards/squad/SquadGrid.tsx

The buttons should render in the same style.
Not sure why we made the exception, but according to Tsahi [here](https://dailydotdev.slack.com/archives/C01473UNK9C/p1730966697555099?thread_ts=1730957943.883429&cid=C01473UNK9C) it's not needed.
Solves: https://github.com/dailydotdev/daily/issues/1576
> [!CAUTION]
https://chore-fix-button-consitency.preview.app.daily.dev

fix: button consitency

---

packages/extension/src/newtab/CustomLinks.tsx
packages/extension/src/newtab/ShortcutLinks/experiments/ShortcutLinksUIV1.tsx

Was annoying it doesn't resolve to local API :) 
> [!CAUTION]
https://chore-use-apiurl.preview.app.daily.dev

chore: add apiUrl instead of hardcoded

---

packages/shared/src/components/post/SquadPostAuthor.tsx

> [!CAUTION]
AS-679
https://as-510-fix-truncate.preview.app.daily.dev
https://as-510-fix-truncate.preview.app.daily.dev/posts/bhV2regOP

fix: add shrink to squad post author link

---

packages/shared/src/components/profile/TopReaderWidget.tsx
packages/shared/src/components/typography/Typography.tsx

https://dailydotdev.slack.com/archives/C013J24CWUC/p1730998452032899?thread_ts=1730998235.952759&cid=C013J24CWUC
> [!CAUTION]
https://as-510-click-tag.preview.app.daily.dev

feat: make tag clickable

---

packages/shared/src/contexts/PushNotificationContext.tsx
packages/webapp/pages/onboarding.tsx

- Skip the step when PN is not supported.
> [!CAUTION]
https://fix-pn-onboarding.preview.app.daily.dev

fix: unsupported push notifications

---

packages/shared/src/styles/base.css
packages/shared/tailwind/colors/action.ts

Add plus color guidelines
> [!CAUTION]
https://as-713-plus-colors.preview.app.daily.dev

feat: add plus color guidelines

---

packages/shared/src/components/cards/ad/AdGrid.tsx
packages/shared/src/components/cards/ad/AdList.tsx
packages/shared/src/components/cards/ad/common/RemoveAd.tsx
packages/shared/src/components/cards/common/list/FeedItemContainer.tsx

Added remove button to ad card that was missing from design earlier
> [!CAUTION]
https://as-696-ad-list-card.preview.app.daily.dev

feat: remove ad button from ad list card

---

packages/shared/src/components/modals/squads/PostModerationModal.tsx
packages/shared/src/components/squads/moderation/SquadModerationItem.tsx
packages/shared/src/components/squads/moderation/SquadModerationItemContextMenu.tsx
packages/shared/src/components/squads/moderation/SquadModerationList.tsx
packages/shared/src/components/squads/moderation/useSourceModerationItem.ts
packages/shared/src/graphql/squads.ts
packages/shared/src/hooks/squads/useSourceModerationList.ts

- added pending posts context menu
- delete mutation for pending posts
- fix modal approve/reject visible by non-moderator 
- renamed `useSquadPostModeration` into `useSourceModerationList`
> [!CAUTION]
https://feat-moderation-item-context-men.preview.app.daily.dev

feat: added pending posts context menu and delete mutation

---

packages/shared/src/components/Logo.tsx
packages/shared/src/components/UpgradeToPlus.tsx
packages/shared/src/components/layout/HeaderLogo.tsx
packages/shared/src/components/sidebar/SidebarTablet.tsx

Got the design for tablet
> [!CAUTION]
https://as-700-tablet.preview.app.daily.dev

fix: add plus button and plus logo to sidebar menu on tablet

---

packages/shared/src/components/UpgradeToPlus.tsx
packages/webapp/components/layouts/PlusLayout/PlusHeader.tsx

> [!CAUTION]
AS-717
https://as-717-go-back.preview.app.daily.dev

fix: add go-back functionality to Back button on plus page

---

packages/shared/src/components/FeedErrorScreen.tsx
packages/shared/src/components/GrowthBookProvider.tsx
packages/shared/src/components/errors/ServerError.tsx
packages/shared/src/contexts/BootProvider.tsx

Fix: [#1593](https://github.com/dailydotdev/daily/issues/1593)
When the production down page is show when the error occurs the production down page was not centered in the screen.
After:
> [!CAUTION]

fix:production-down page is not centered on the screen

---

packages/shared/src/components/Logo.tsx
packages/shared/src/components/PlusUserBadge.tsx
packages/shared/src/components/ProfileMenu.tsx
packages/shared/src/components/layout/HeaderLogo.tsx
packages/shared/src/components/profile/Header.tsx
packages/shared/src/components/profile/ProfileSettingsMenu.tsx
packages/shared/src/components/profile/UserShortInfo.tsx
packages/shared/src/components/profile/devcard/DevCard.tsx
packages/shared/src/components/widgets/PostUsersHighlights.tsx
packages/shared/src/graphql/comments.ts
packages/shared/src/graphql/fragments.ts
packages/shared/src/lib/user.ts

The tooltip value was broken.
See also https://github.com/dailydotdev/daily-api/pull/2440
<table>
<tr>
<td>Before
<td>After
<tr>
<td><img src="https://github.com/user-attachments/assets/5be891fe-e21c-492d-96f1-732157928fc7">
<td><img src="https://github.com/user-attachments/assets/6071b1ba-fdc2-4404-91dd-d4937bd68f4f">
</table>
> [!CAUTION]

fix: show plus member since

---

packages/shared/src/components/plus/PlusList.tsx
packages/shared/src/lib/image.ts
packages/webapp/components/layouts/PlusLayout/PlusLayout.tsx
packages/webapp/pages/plus/index.tsx

Fixes several review issues.
- bg image
- spacing
- layout shift preserve space
- different icon
> [!CAUTION]
https://fix-review-feedback.preview.app.daily.dev

fix: review feedback

---

packages/shared/src/components/squads/SquadHeaderBar.tsx

- Fixed variant according to design
> [!CAUTION]
https://fix-pending-post-button.preview.app.daily.dev

fix: squad pending posts button variant

---

packages/webapp/pages/squads/[handle]/moderate.tsx

Reference: https://github.com/dailydotdev/apps/pull/3641#discussion_r1841652976
> [!CAUTION]
https://fix-ssr-error-private-squads.preview.app.daily.dev

fix: moved query only client side, removed error for unauthorized page;

---

packages/shared/src/hooks/squads/usePostToSquad.ts

> [!CAUTION]
https://fix-first-post-checklist.preview.app.daily.dev

fix: mark first post step completed after submit pending post

---

packages/webapp/components/layouts/PlusLayout/PlusHeader.tsx

> [!CAUTION]
AS-728
https://as-728-fix-back-button.preview.app.daily.dev

fix: navigate to main page if navigated directly

---

packages/webapp/pages/plus/success.tsx

Exclude for bots/crawling
> [!CAUTION]
AS-731 #done 
https://as-731-noindex-success.preview.app.daily.dev

fix: noindex/nofollow to success page

---

packages/shared/src/hooks/squads/usePostToSquad.ts
packages/webapp/pages/posts/[id]/edit.tsx
packages/webapp/pages/squads/[handle]/moderate.tsx

- Common function for the redirection.
- Fix executing an optional function.
> [!CAUTION]
https://fix-edit-callback.preview.app.daily.dev

fix: error after editing a post moderation

---

packages/shared/src/components/PlusUserBadge.tsx
packages/shared/src/components/ProfileMenu.tsx
packages/shared/src/components/UpgradeToPlus.tsx
packages/shared/src/components/layout/HeaderLogo.tsx
packages/shared/src/components/profile/Header.tsx
packages/shared/src/components/profile/ProfileSettingsMenu.tsx
packages/shared/src/components/profile/ProfileWidgets.tsx
packages/shared/src/components/profile/UserMetadata.tsx
packages/shared/src/contexts/PaymentContext.tsx
packages/shared/src/hooks/usePlusSubscription.ts
packages/shared/src/lib/featureManagement.ts

> [!CAUTION]
https://as-718-experiment.preview.app.daily.dev

fix: plus buttons behind feature flag

---

packages/shared/src/contexts/BootProvider.tsx
packages/shared/src/contexts/PaymentContext.tsx
packages/webapp/components/layouts/PlusLayout/PlusLayout.tsx
packages/webapp/pages/plus/index.tsx

> [!CAUTION]
https://as-696-fix-direct-plus.preview.app.daily.dev

fix: fetch plan types if direct visit to plus page

---

packages/webapp/components/layouts/PlusLayout/PlusHeader.tsx

> [!CAUTION]
AS-732
https://as-732.preview.app.daily.dev

fix: plus header hydration

---

packages/shared/src/components/ProfileMenu.tsx
packages/shared/src/components/profile/ProfileSettingsMenu.tsx
packages/shared/src/lib/constants.ts

> [!CAUTION]
AS-737
https://as-737-manage-plus.preview.app.daily.dev

fix: use correct manage plus link

---

packages/shared/src/components/PlusUserBadge.tsx
packages/shared/src/components/UpgradeToPlus.tsx
packages/shared/src/components/plus/PlusDesktop.tsx
packages/shared/src/components/sidebar/SidebarDesktop.tsx
packages/shared/src/lib/auth.ts
packages/webapp/components/layouts/PlusLayout/PlusLayout.tsx

> [!CAUTION]
AS-738
https://as-738-auth-wall.preview.app.daily.dev

fix: show login modal

---

packages/shared/src/components/TopReaderIn.tsx
packages/shared/src/graphql/fragments.ts

<table>
<tr>
<td>Before
<td>
<a href="https://app.daily.dev/posts/aOU5hM597#c-VHs4AoS6A">https://app.daily.dev/posts/aOU5hM597#c-VHs4AoS6A</a>
<tr>
<td>After
<td>
<a href="https://top-reader-keyword-value-fallbac.preview.app.daily.dev/posts/aOU5hM597#c-VHs4AoS6A">https://top-reader-keyword-value-fallbac.preview.app.daily.dev/posts/aOU5hM597#c-VHs4AoS6A</a>
</table>
> [!CAUTION]
https://top-reader-keyword-value-fallbac.preview.app.daily.dev

fix: fallback to keyword value if title flag does not exist

---

packages/shared/src/contexts/FeedContext.tsx

> [!CAUTION]
AS-746
https://as-746-enrolment.preview.app.daily.dev

fix: only enroll in feed page sizes when not plus member

---

packages/webapp/pages/plus/payment.tsx

Due to items-center it wouldn't force the h-full correctly.
> [!CAUTION]
https://as-748-payment-mobile.preview.app.daily.dev

fix: mobile payment screen full size

---

packages/shared/src/hooks/squads/useSourceModerationList.ts

- Update the reasons based on Nimrod's decision.
- This also fixes the overflow issue since the content is now much shorter.
> [!CAUTION]
https://mi-634.preview.app.daily.dev

refactor: reject reason options

---

packages/shared/src/contexts/PaymentContext.tsx

Disable discount option
> [!CAUTION]
https://as-749-turn-off-discounts.preview.app.daily.dev

feat: turn off discount option

---

.vscode/apps.code-workspace

https://fix-vscode-settings.preview.app.daily.dev

fix: add TypeScript VSCode related settings

---

packages/shared/src/components/layout/DefaultSquadHeader.tsx
packages/shared/src/components/modals/squads/PostModerationModal.tsx
packages/shared/src/components/squads/Details.tsx
packages/shared/src/components/squads/SquadTabs.tsx
packages/shared/src/components/squads/moderation/SquadEmptyScreen.tsx
packages/shared/src/components/squads/moderation/SquadModerationEmptyScreen.tsx
packages/shared/src/components/squads/moderation/SquadModerationItem.tsx
packages/shared/src/components/squads/moderation/SquadModerationList.tsx
packages/webapp/pages/squads/[handle]/moderate.tsx

refactor: moved empty screen to standalone file
fix: center text on mobile
fix: align tabs with heading above tablet
fix: add moderation item border-b missing from design
fix: max-height missing in moderation modal
fix: squad settings heading based on role
fix: edit page missing bold, fixed also padding
fix: edit page missing font props
> [!CAUTION]
https://fix-moderation-ui.preview.app.daily.dev

fix: adjust squad moderation approval ui (modal, tabs, headings, ...)

---

packages/shared/src/components/plus/PlusInfo.tsx

Makes whole billing cycle row clickable
> [!CAUTION]
AS-747
https://as-747-whole-row-clickable.preview.app.daily.dev

refactor: make whole row clickable

---

packages/shared/src/components/plus/PlusInfo.tsx

https://dailydotdev.slack.com/archives/C07V6888KML/p1732034361547639
> [!CAUTION]
https://chore-remove-plus-line.preview.app.daily.dev

chore: remove still on the fence link

---

packages/shared/src/components/modals/report/ReportSourceModal.tsx

onRequestClose was destructured here, so need to pass it seperately.
> [!CAUTION]
AS-757 #done 
https://as-757-close-report-squad.preview.app.daily.dev

fix: add close button to report squad

---

packages/shared/src/components/fields/SearchField.tsx
packages/shared/src/components/onboarding/EditTag.tsx
packages/shared/src/components/tags/TagSelection.tsx
packages/shared/src/lib/featureManagement.ts

Experiment lost
> [!CAUTION]
https://as-754-cleanup-search-style-vers.preview.app.daily.dev

chore: cleanup search_style_version lost

---

packages/shared/src/components/search/SearchPanel/SearchPanelInput.tsx
packages/shared/src/lib/featureManagement.ts

Experiment lost cleanup needed
> [!CAUTION]
AS-760 #done 
https://as-760-cleanup-search-placeholde.preview.app.daily.dev

chore: cleanup search_placeholder

---

packages/shared/src/components/onboarding/EditTag.tsx
packages/shared/src/components/tags/TagSelection.tsx
packages/shared/src/lib/featureManagement.ts

Experiment won, it's now the default
> [!CAUTION]
AS-756 #done 
https://as-756-cleanup-onboarding-shuffl.preview.app.daily.dev

chore: cleanup onboarding_shuffle_tags exp

---

packages/shared/src/components/search/SearchPanel/SearchPanelDropdown.tsx
packages/shared/src/components/search/SearchResults/SearchResultsLayout.tsx
packages/shared/src/lib/featureManagement.ts

Experiment won, so can be applied directly.
> [!CAUTION]
AS-759 #done 
https://as-759-cleanup-search-users.preview.app.daily.dev

chore: cleanup search_users exp

---

packages/shared/src/components/Pixels.tsx
packages/shared/src/components/auth/AuthModal.tsx
packages/shared/src/contexts/PaymentContext.tsx
packages/webapp/components/layouts/PlusLayout/PlusLayout.tsx
packages/webapp/pages/onboarding.tsx
packages/webapp/pages/welcome/index.tsx

I refactor a bit the pixels setup to easily add it to other pages and track different events
> [!CAUTION]
https://checkout-pixel.preview.app.daily.dev

chore: add pixel tracking for payment

---

packages/shared/src/contexts/FeedContext.tsx

https://fix-feed-page-sizes.preview.app.daily.dev

fix: deconstruct feedPageSizes

---

packages/shared/src/components/plus/PlusDesktop.tsx
packages/shared/src/components/plus/PlusMobile.tsx
packages/shared/src/contexts/PaymentContext.tsx

Had to re-use existing paddle if already init
And move to useEffect on desktop.
> [!CAUTION]
AS-758 #done 
https://as-758-payment-loading.preview.app.daily.dev

fix: minor changes for payment loading

---

packages/shared/src/contexts/PaymentContext.tsx
packages/shared/src/lib/constants.ts

Fixes missing complete checkout event not firing
> [!CAUTION]
AS-763
https://as-763-missing-event.preview.app.daily.dev

fix: use nextjs router to redirect to success page

---

packages/shared/src/components/PlusUserBadge.tsx
packages/shared/src/components/cards/ad/common/RemoveAd.tsx
packages/shared/src/lib/log.ts

> [!CAUTION]
https://fix-event-on-remove-ads.preview.app.daily.dev

fix: add missing upgrade to plus events

---

packages/webapp/pages/squads/[handle]/index.tsx

> [!CAUTION]
https://fix-squads-ssr.preview.app.daily.dev

fix: squads ssr when referring user is present

---

packages/shared/src/contexts/SettingsContext.tsx
packages/webapp/components/layouts/PlusLayout/PlusLayout.tsx

PlusLayout only support dark mode so we have to force it.
This addition enables a overwrite to settings.
Keep in mind the cleanup needed to happen manually.
To me it's more of a temporary hotfix and we should just support light mode.
Desktop:
[desktop.webm](https://github.com/user-attachments/assets/6b791655-3821-4fec-b4a4-a3319f313003)
Mobile:
https://github.com/user-attachments/assets/f4dade24-b570-4c33-8291-2f9a077f4187
> [!CAUTION]
https://chore-force-layout-mode.preview.app.daily.dev

fix: option to force layout mode for layouts

---

packages/shared/src/lib/ads.ts

I was trying to be clever...
> [!CAUTION]
https://fix-anon-post-page.preview.app.daily.dev

fix: don't return null

---

packages/shared/src/components/Feed.tsx
packages/shared/src/components/FeedItemComponent.tsx
packages/shared/src/components/cards/ad/AdGrid.tsx
packages/shared/src/components/cards/ad/AdList.tsx
packages/shared/src/components/cards/ad/common/AdImage.tsx
packages/shared/src/components/cards/ad/common/AdRefresh.tsx
packages/shared/src/components/cards/ad/common/RemoveAd.tsx
packages/shared/src/components/cards/ad/common/common.tsx
packages/shared/src/components/comments/AdAsComment.tsx
packages/shared/src/components/comments/CommentContainer.tsx
packages/shared/src/components/comments/MainComment.tsx
packages/shared/src/hooks/feed/useAutoRotatingAds.ts
packages/shared/src/hooks/feed/useLogImpression.ts
packages/shared/src/lib/ads.ts

Adds refresh button to ads in feed and comments.
| New | [refresh](https://docs.google.com/spreadsheets/d/18Lv7zXges9QfVX5VYL1a-Hyl0e1sQ3sLr0OK8YZWKXI/edit?gid=0#gid=0&range=B79)  | Same as ad click |
> [!CAUTION]
AS-769
https://as-769-refresh-ad.preview.app.daily.dev

feat: ad-refresh on feed cards

---

packages/webapp/components/layouts/AccountLayout/Profile/VerifiedCompanyBadge/VerifiedCompanyBadgeSection.tsx

https://dailydotdev.slack.com/archives/C07EA1E1XME/p1732290974385259
> [!CAUTION]
https://fix-clear-unverified-company-ema.preview.app.daily.dev

fix: add button to clear unverified company emails

---

packages/shared/src/hooks/post/useViewPost.ts
packages/shared/src/hooks/streaks/useReadingStreak.ts

- Until refresh, there can be an edge case where streak is not updated yet from the UI side of things.
- I've also searched the codebase for any other place where `lastViewAt` was used and all should've been covered.
> [!CAUTION]
https://fix-streak.preview.app.daily.dev

fix: streak usage of last view at to timezone considered

---

packages/shared/src/components/Pixels.tsx
packages/shared/src/lib/links.ts
packages/webapp/next.config.ts
packages/webapp/pages/_app.tsx
packages/webapp/public/manifest.json

- for now this will overwrite only `_next/static` requests
- after this I am gonna also move `/public` JS files to something like `/public/assets` so we can manually use CDN URL for those as well
- preview also works so it can be tested I added an origin override
> [!CAUTION]
https://static-cdn.preview.app.daily.dev

feat: add cdn asset prefix

---

packages/shared/src/components/filters/BlockedWords.tsx
packages/shared/src/lib/log.ts

Missed this plus badge:
And noticed one tracking event had misformed info
> [!CAUTION]
https://hotfix-missed-elements.preview.app.daily.dev

fix: missed two elements

---

packages/shared/src/components/plus/PlusListItem.tsx

> [!CAUTION]
https://fix-plus-list-tooltip.preview.app.daily.dev/plus

fix: tooltip on mobile plus list

---

packages/shared/src/components/plus/PlusListItem.tsx
packages/shared/src/components/tooltips/BaseTooltipContainer.tsx

- Fix text alignment of tooltip content.
Preview:
> [!CAUTION]
https://fix-tooltip.preview.app.daily.dev

fix: tooltip text alignment

---

packages/shared/src/components/filters/BlockedWords.tsx
packages/shared/src/components/filters/TagButton.tsx

> [!CAUTION]
https://fix-remove-hashtag.preview.app.daily.dev

fix: remove hashtag

---

packages/shared/src/hooks/squads/useSquadPendingPosts.ts

@capJavert Mentioned that pending posts query was missing status in the query key, which could lead to potential issues. Quickly added it as suggested.
> [!CAUTION]
https://add-status-to-key.preview.app.daily.dev

fix: Add status to query key

---

packages/extension/src/companion/useCompanionSettings.ts

Edge-case for Brave browser which doesn't expose scripting if not granted.
Thus cannot be called like this.
It won't break as companion is not active and user disabling it anyway.
Logged here:
https://dailydotdev.slack.com/archives/C01L0QXQJNB/p1733152985907399
> [!CAUTION]
https://fix-conditional-calling.preview.app.daily.dev

fix: conditional calling function

---

packages/shared/src/components/filters/ContentTypesFilter.tsx
packages/shared/src/components/filters/FeedFilters.tsx

Before:
After:
> [!CAUTION]
https://fix-mobile-plus-box-width.preview.app.daily.dev

fix: mobile plus box width

---

packages/shared/src/components/filters/FeedFilters.tsx

:hidethepain: it disabled vertical scroll
> [!CAUTION]
https://fix-mobile-plus-box-scroll.preview.app.daily.dev

fix: settings box scroll

---

packages/shared/src/contexts/SettingsContext.tsx
packages/shared/src/graphql/settings.ts

> [!CAUTION]
AS-801
https://as-801.preview.app.daily.dev

feat: add `clickbaitShieldEnabled` setting

---

packages/shared/src/components/filters/ContentTypesFilter.tsx

Toggles clickbait shield on and off
> [!CAUTION]
AS-809
https://as-788-toggle-clickbait-shield.preview.app.daily.dev/

 feat: toggle clickbait shield on and off

---

packages/shared/src/components/feeds/FeedNav.tsx
packages/shared/src/components/tabs/TabContainer.tsx
packages/shared/src/components/tabs/TabList.tsx

- add modal handler for plus entry point in feed nav, see [thread](https://dailydotdev.slack.com/archives/C01L0QXQJNB/p1733310994510699)
> [!CAUTION]
https://mobile-new-feed-entry-point.preview.app.daily.dev

feat: add entry point to feed nav

---

packages/shared/src/components/buttons/Button.tsx
packages/shared/src/components/buttons/ToggleClickbaitShield.tsx
packages/shared/src/components/buttons/common.ts
packages/shared/src/components/filters/ContentTypesFilter.tsx
packages/shared/src/components/filters/FeedFilters.tsx
packages/shared/src/components/filters/helpers.ts
packages/shared/src/components/layout/common.tsx
packages/shared/src/hooks/useContextMenu.ts

> [!CAUTION]
AS-802
https://as-802-clickbait-shield-feed-too.preview.app.daily.dev

feat: add toggle Clickbait Shield button to feeds

---

packages/shared/src/graphql/fragments.ts

Depends on https://github.com/dailydotdev/daily-api/pull/2502
> [!CAUTION]
AS-806
https://as-806-post-title-clickbait.preview.app.daily.dev

feat: add `clickbaitTitleDetected` to post queries

---

packages/webapp/pages/following.tsx

Following page needs to be protected as it needs user data
> [!CAUTION]
https://fix-following-feedback.preview.app.daily.dev

fix: following should be protected page

---

packages/shared/src/components/cards/Freeform/FreeformGrid.tsx
packages/shared/src/components/cards/article/ArticleGrid.tsx
packages/shared/src/components/cards/article/ArticleList.tsx
packages/shared/src/components/cards/common/ClickbaitShield.tsx
packages/shared/src/components/cards/common/PostTags.tsx
packages/shared/src/components/cards/share/ShareGrid.tsx
packages/shared/src/components/cards/share/ShareList.tsx
packages/shared/src/graphql/actions.ts
packages/shared/src/graphql/feed.ts
packages/shared/src/graphql/posts.ts

> [!CAUTION]
AS-804
https://as-804-clickbait-shield-on-card.preview.app.daily.dev

feat: add Clickbait Shield to cards

---

packages/extension/package.json
packages/shared/package.json
packages/shared/src/lib/user.ts
pnpm-lock.yaml

Think we can actually get rid of node-fetch by now?
But this fixed a build issue on firefox regardless for now.
> [!CAUTION]
https://fix-typesafety-node-fetch.preview.app.daily.dev

fix: minor fix for typesafety node-fetch

---

packages/shared/src/components/ConditionalWrapper.tsx
packages/shared/src/components/cards/Freeform/FreeformGrid.tsx
packages/shared/src/components/cards/Freeform/FreeformList.tsx
packages/shared/src/components/cards/article/ArticleGrid.tsx
packages/shared/src/components/cards/article/ArticleList.tsx
packages/shared/src/components/cards/common/ClickbaitShield.tsx
packages/shared/src/components/cards/share/ShareGrid.tsx
packages/shared/src/components/cards/share/ShareList.tsx
packages/shared/src/components/filters/ContentTypesFilter.tsx
packages/shared/src/components/modals/ClickbaitShieldModal.tsx
packages/shared/src/components/modals/common.tsx
packages/shared/src/components/modals/common/types.ts
packages/shared/src/components/plus/ClickbaitTrial.tsx
packages/shared/src/components/post/FixedPostNavigation.tsx
packages/shared/src/components/post/MarkdownPostContent.tsx
packages/shared/src/components/post/PostContent.tsx
packages/shared/src/components/post/common/PostClickbaitShield.tsx
packages/shared/src/graphql/posts.ts
packages/shared/src/hooks/feed/useLogImpression.ts
packages/shared/src/hooks/post/useSmartTitle.ts
packages/shared/src/hooks/usePostById.ts
packages/shared/src/hooks/usePostContent.ts
packages/shared/src/lib/image.ts
packages/shared/src/lib/log.ts
packages/shared/src/lib/query.ts

- Adds clickbait shields to posts
- Fetches smart title when clicking on shield
> [!CAUTION]
AS-805
https://as-805-add-clickbait-shield-on-p.preview.app.daily.dev

feat: add clickbait shield to posts

---

packages/shared/src/lib/user.ts
packages/webapp/components/layouts/ProfileLayout/index.tsx

We need to upgrade our jest one day, until then we need to support node-fetch on testcases.
Jest 26 doesn't support fetch from node, and by including it, you can't nock anything.
For now decided to remove-usage but keep it for tests for now.
> [!CAUTION]
https://chore-node-fetch-test-only.preview.app.daily.dev

chore: only node-fetch on tests

---

packages/shared/src/hooks/post/useSmartTitle.ts

https://dailydotdev.slack.com/archives/C0811D22VPG/p1733429048416709
> [!CAUTION]
https://as-788-pass-isplus-on-log.preview.app.daily.dev

fix: pass isPlus on post log event

---

packages/shared/src/components/modals/ClickbaitShieldModal.tsx
packages/shared/src/hooks/usePostById.ts

Because SSG data doesn't contain smart title, we can't use it, and must rely on the client fetched one.
> [!CAUTION]
https://as-788-fix-initial-title-on-post.preview.app.daily.dev

fix: don't use inital ssg data on post page when plus user

---

packages/shared/src/components/layout/common.tsx

Solves:
https://dailydotdev.slack.com/archives/C01L0QXQJNB/p1733410232064249
Think when we did the shortcut cleanup we accidentally removed all actions not just the shortcut one.
| ![image](https://github.com/user-attachments/assets/6b943955-b763-4888-881a-84a5d1d81da4) | ![Screenshot 2024-12-06 at 11 55 39](https://github.com/user-attachments/assets/6ec3797e-e275-487e-b813-2b73e3e7492b) | 
> [!CAUTION]
https://fix-tablet-settings.preview.app.daily.dev

fix: bring back filters on tablet

---

packages/shared/src/components/buttons/ToggleClickbaitShield.tsx
packages/shared/src/components/filters/ContentTypesFilter.tsx

> [!CAUTION]
AS-788
https://as-788-invalidate-feed.preview.app.daily.dev

fix: invalidate feed query

---

packages/shared/src/components/buttons/ToggleClickbaitShield.tsx
packages/shared/src/contexts/ActiveFeedContext.tsx

Just to follow our coding style of hooks for using contexts
> [!CAUTION]
https://useactivefeedcontext.preview.app.daily.dev

refactor: create `useActiveFeedContext` hook

---

packages/shared/src/components/Feed.spec.tsx
packages/shared/src/components/Feed.tsx
packages/shared/src/contexts/FeedContext.tsx
packages/shared/src/hooks/useFeed.ts
packages/shared/src/lib/featureManagement.ts
packages/shared/src/lib/feed.ts

Reverts dailydotdev/apps#3894
we found the edge case on prod, will see to adjust
https://revert-3894-ad-repeat-logic.preview.app.daily.dev

Revert "feat: ad repeat logic"

---

packages/shared/src/hooks/post/useSmartTitle.ts

<table>
<tr>
<td>Before
<td>After
<tr>
<td><img src="https://github.com/user-attachments/assets/8da7a424-d447-41ed-9250-0584f20310b3">
<td><img src="https://github.com/user-attachments/assets/e52232a7-d480-48f7-af9d-e935c2c6e181">
</table>
> [!CAUTION]
https://as-788-fix-shared-posts.preview.app.daily.dev

fix: smart titles on shared posts

---

packages/shared/src/components/Feed.spec.tsx
packages/shared/src/components/Feed.tsx
packages/shared/src/contexts/FeedContext.tsx
packages/shared/src/hooks/useFeed.ts
packages/shared/src/lib/ads.ts
packages/shared/src/lib/constants.ts
packages/shared/src/lib/featureManagement.ts
packages/shared/src/lib/feed.ts

Original logic from https://github.com/dailydotdev/apps/pull/3894 that was reverted.
Missed the edge case where ads can be returned empty which would prompt constant requests until ad requirement is fulfilled. 
Fix is in this commit https://github.com/dailydotdev/apps/pull/3939/commits/ac140fc51c12a17aa5cd31d421ecf1b5bc6f1a0f
> [!CAUTION]
https://ad-repeat-logic.preview.app.daily.dev

feat: ad repeat logic 2

---

packages/shared/src/graphql/bookmarks.ts
packages/shared/src/graphql/posts.ts

Changes in API make gql to throw error because field do not exist
> [!CAUTION]
https://fix-bookmarks-prod.preview.app.daily.dev

fix: bookmark generate client error after API changes

---

packages/shared/src/hooks/post/useSmartTitle.ts

> [!CAUTION]
https://as-788-fix-error-toast.preview.app.daily.dev

fix: show toast message on clickbait shield toggle error

---

packages/shared/src/components/cards/common/ClickbaitShield.tsx
packages/shared/src/components/post/common/PostClickbaitShield.tsx
packages/shared/src/hooks/post/useSmartTitle.ts

Fixes the tooltips for clickbait shield
> [!CAUTION]
https://as-788-fix-shield-tooltips.preview.app.daily.dev

fix: shield tooltips

---

packages/shared/src/components/filters/BlockedWords.tsx

Forgot extension needed hard set on types:
> [!CAUTION]
https://chore-fix-typosizing.preview.app.daily.dev

fix: typesizing

---

packages/shared/src/components/SharedByUserBanner.tsx
packages/shared/src/components/contentPreference/FollowButton.tsx
packages/shared/src/components/post/PostContent.tsx
packages/shared/src/components/post/PostHeaderActions.tsx
packages/shared/src/components/post/SquadPostContent.tsx
packages/shared/src/components/post/collection/CollectionPostContent.tsx
packages/shared/src/components/squads/moderation/SquadModerationItem.tsx
packages/shared/src/contexts/BootProvider.tsx
packages/shared/src/graphql/users.ts
packages/shared/src/hooks/contentPreference/useContentPreferenceStatusQuery.ts
packages/shared/src/hooks/useMedia.ts
packages/shared/src/hooks/useViewSize.ts
packages/shared/src/hooks/user/useUserShortByIdQuery.ts
packages/shared/src/lib/log.ts
packages/shared/src/lib/query.ts
packages/webapp/__tests__/PostPage.tsx
packages/webapp/next.config.ts
packages/webapp/pages/posts/[id]/index.tsx
packages/webapp/pages/posts/[id]/share/index.tsx

Moves to SSR rendering for shared post from concept here:
https://github.com/dailydotdev/apps/pull/3941
And fixes some hydratation issues from here:
https://github.com/dailydotdev/apps/pull/3880
If we detect userID in url we will render this new section:
> [!CAUTION]
AS-817 #done 
https://as-817-sharing-funnel-post.preview.app.daily.dev

feat: link sharing funnel post page

---

packages/webapp/pages/following.tsx

Add seo data for following feed
> [!CAUTION]
https://chore-following-seo-data.preview.app.daily.dev

chore: add following SEO data

---

packages/shared/src/components/onboarding/OnboardingAndroidApp.tsx
packages/shared/src/components/profile/ProfileSettingsMenu.tsx
packages/shared/src/lib/featureManagement.ts
packages/webapp/pages/onboarding.tsx

* Removed bottom links as agreed [here](https://dailydotdev.slack.com/archives/C0381BQUEN9/p1733811070377239?thread_ts=1732780166.207429&cid=C0381BQUEN9)
* Made minor updates to positioning to make it look correct on more screen sizes
* Moved the feature to its own variable to mirror the ios PWA
> [!CAUTION]
https://mi-630-update-android-screen.preview.app.daily.dev

chore: Update android onboarding

---

packages/shared/src/components/plus/PlusList.tsx

Nimrod wanted a change in order here.
https://dailydotdev.slack.com/archives/C07V6888KML/p1733908360898789
> [!CAUTION]
https://fix-order-items.preview.app.daily.dev

fix: order of items in list

---

packages/shared/src/hooks/bookmark/useCreateBookmarkFolder.ts

- sort sidebar folders when adding new one
> [!CAUTION]
https://feat-folders-az-sorting.preview.app.daily.dev

feat: sort sidebar folders when adding new one

---

packages/shared/src/components/PostOptionsMenu.tsx
packages/shared/src/components/post/PostMenuOptions.tsx
packages/shared/src/graphql/posts.ts

https://github.com/dailydotdev/daily-api/pull/2511
> [!CAUTION]
AS-822
https://as-822-manual-clickbait.preview.app.daily.dev

feat: add admin option to manually protect posts with clickbait shield

---

packages/shared/src/components/plus/PlusList.tsx

> [!CAUTION]
https://fix-coming-soon-bookmarks.preview.app.daily.dev

fix: bookmarks folder coming soon

---

packages/shared/src/components/BookmarkFeedLayout.tsx
packages/shared/src/hooks/useActiveNav.tsx
packages/shared/src/hooks/useFeedLayout.ts
packages/shared/src/lib/query.ts

| <img width="492" alt="image" src="https://github.com/user-attachments/assets/1392920e-b872-46b7-a0de-83e1501cf975" /> | <img width="492" alt="image" src="https://github.com/user-attachments/assets/00d6a0cd-226a-4731-813c-20f66dd07c9e" /> | 
> [!CAUTION]
https://fix-bookmark-mobile-layout.preview.app.daily.dev

fix: bookmark mobile layout missed navbar

---

packages/shared/src/components/bookmark/BookmarkFolderContextMenu.tsx

Fix preview:
> [!CAUTION]
https://mi-686.preview.app.daily.dev

fix: delete prompt title word breaks

---

packages/shared/src/graphql/users.ts
packages/webapp/components/layouts/AccountLayout/Profile/index.tsx

- Utilize the new mutation to clear image based on presets.
> [!CAUTION]
https://fix-clear-cover.preview.app.daily.dev

fix: clear image with the new mutation

---

packages/shared/src/components/feeds/FeedSettings/FeedSettingsEdit.tsx
packages/shared/src/components/feeds/FeedSettings/FeedSettingsEditBody.tsx
packages/shared/src/components/feeds/FeedSettings/FeedSettingsEditContext.tsx
packages/shared/src/components/feeds/FeedSettings/FeedSettingsEditHeader.tsx
packages/shared/src/components/feeds/FeedSettings/types.ts
packages/shared/src/components/feeds/FeedSettings/useFeedSettingsEdit.tsx
packages/shared/src/components/filters/FeedFilters.tsx
packages/shared/src/components/modals/common/ModalSidebar.tsx
packages/shared/src/components/sidebar/SidebarList.tsx
packages/shared/src/components/sidebar/SidebarListItem.tsx
packages/shared/src/graphql/feed.ts
packages/webapp/pages/feeds/[slugOrId]/edit.tsx

- new modal (to replace FeedFilters, not yet removed but will be closer to epic launch)
- took a modal base from above
- top level context to manage data/form/submission
> [!CAUTION]
https://as-844-feed-settings-edit.preview.app.daily.dev

feat: feed settings modal

---

packages/shared/src/components/auth/PostAuthBanner.tsx
packages/shared/src/lib/featureManagement.ts

Cleanup post_banner_personalized (won)
> [!CAUTION]
MI-702 #done
https://mi-702.preview.app.daily.dev

chore: Cleanup post_banner_personalized

---

packages/shared/src/components/feeds/FeedSettings/FeedSettingsEdit.tsx
packages/shared/src/components/feeds/FeedSettings/sections/FeedSettingsContentPreferencesSection.tsx
packages/shared/src/components/fields/FilterCheckbox.tsx
packages/shared/src/graphql/feedSettings.ts
packages/shared/src/hooks/feed/useAdvancedSettings.ts
packages/shared/src/hooks/useMutateFilters.ts

API changes https://github.com/dailydotdev/daily-api/pull/2543
> [!CAUTION]
https://as-847-feed-settings-preferences.preview.app.daily.dev

feat: add preferences section

---

packages/shared/src/components/auth/PostAuthBanner.tsx

> [!CAUTION]
https://fix-failing-tests.preview.app.daily.dev

fix: Failing tests should now work

---

packages/shared/src/components/feeds/FeedSettings/FeedSettingsEdit.tsx
packages/shared/src/components/feeds/FeedSettings/sections/FeedSettingsFiltersSection.tsx
packages/shared/src/components/feeds/FeedSettings/types.ts
packages/shared/src/components/feeds/FeedSettings/useFeedSettingsEdit.tsx
packages/shared/src/graphql/feed.ts
packages/shared/src/graphql/fragments.ts
packages/shared/src/lib/constants.ts

- API changes pending (validation) https://github.com/dailydotdev/daily-api/pull/2546
> [!CAUTION]
https://as-814-feed-settings-filters.preview.app.daily.dev

feat: feed settings filters

---

packages/shared/src/components/FeedEmptyScreen.tsx
packages/shared/src/components/buttons/ToggleClickbaitShield.tsx
packages/shared/src/components/cards/common/ClickbaitShield.tsx
packages/shared/src/components/feeds/FeedSettings/FeedSettingsEdit.tsx
packages/shared/src/components/feeds/FeedSettings/sections/FeedSettingsGeneralSection.tsx
packages/shared/src/components/feeds/FeedSettings/useFeedSettingsEdit.tsx
packages/shared/src/components/feeds/FeedSettingsButton.tsx
packages/shared/src/components/feeds/MobileFeedActions.tsx
packages/shared/src/components/filters/MyFeedHeading.tsx
packages/shared/src/components/layout/common.tsx
packages/shared/src/components/post/common/PostClickbaitShield.tsx
packages/shared/src/components/sidebar/sections/CustomFeedSection.tsx
packages/shared/src/hooks/useOnboardingChecklist.tsx

- load my feed when user goes to edit it
- replace feed filters modal with the page
- also replace lazy modal opens with navigation (and cleanup logic)
- add icons to feed sidebar
- adjust edit settings based on feed type
- update feed settings button copy to match across feed
> [!CAUTION]
https://as-866-my-feed-edit.preview.app.daily.dev

feat: edit my feed in new UI

---

packages/shared/src/components/feeds/FeedSettings/components/BlockedSourceList.tsx
packages/shared/src/components/feeds/FeedSettings/components/BlockedTagList.tsx
packages/shared/src/components/feeds/FeedSettings/components/BlockedUserList.tsx
packages/shared/src/components/filters/BlockedWords.tsx
packages/shared/src/graphql/contentPreference.ts
packages/shared/src/hooks/contentPreference/useBlockedQuery.ts

> [!CAUTION]
https://chore-remove-userid.preview.app.daily.dev

chore: blocked doesn't need userid

---

packages/shared/src/components/filters/BlockedWords.tsx
packages/shared/src/graphql/contentPreference.ts
packages/shared/src/hooks/contentPreference/useBlockedQuery.ts

Refactor for useBlockedQuery.
> [!CAUTION]
https://chore-refactor-blocked-user.preview.app.daily.dev

chore: to refactor blocked user query

---

packages/shared/src/components/onboarding/OnboardingAndroidApp.tsx
packages/shared/src/lib/log.ts

Added event logging to download android app button on onboarding
> [!CAUTION]
MI-704
https://mi-704.preview.app.daily.dev/
https://mi-704.preview.app.daily.dev

chore: add logevent to download android app

---

packages/shared/src/components/profile/SourceList.tsx
packages/shared/src/components/profile/SourceListPlaceholder.tsx
packages/shared/src/components/profile/TagList.tsx
packages/shared/src/components/profile/TagListPlaceholder.tsx

Add the correct placeholders
> [!CAUTION]
https://as-869-placeholders.preview.app.daily.dev

fix: the placeholders

---

packages/shared/src/components/contentPreference/FollowButton.tsx
packages/shared/src/components/feeds/FeedSettings/components/BlockedUserList.tsx
packages/shared/src/components/feeds/FeedSettings/components/FollowingUserList.tsx
packages/shared/src/components/profile/UserShortInfo.tsx
packages/shared/src/hooks/contentPreference/useFollowContentPreferenceMutationSubscription.ts

Several fixes for user following.
We might need to add more requestKeys to the evaluation, for now this is what I've found to work.
> [!CAUTION]
AS-870 #done 
https://as-870-user-follow-fixes.preview.app.daily.dev

fix: user follow fixes

---

packages/shared/src/components/cards/ActionsButtons/ActionButtons.tsx
packages/shared/src/components/cards/common/list/ActionButtons.tsx
packages/shared/src/lib/featureManagement.ts

- Make upvote counter visible also when value is 0
Name : `always_visible_upvote_counter`
Available options: boolean (true/false)
Enrollment for users that see the Card/List ActionsButtons (feed, post page, modal, etc...) 
> [!CAUTION]
https://mi-689-upvotes-count-experiment.preview.app.daily.dev

feat: upvotes count experiment

---

packages/shared/src/components/feeds/FeedSettings/sections/FeedSettingsFiltersSection.tsx

[ref](https://dailydotdev.slack.com/archives/C06LKPZAZ1T/p1734531952145789?thread_ts=1734531548.784989&cid=C06LKPZAZ1T)
> [!CAUTION]
AS-871 #done
https://as-871.preview.app.daily.dev

feat: Show errors on content thresholds per guideline

---

packages/shared/src/components/MainFeedLayout.tsx
packages/shared/src/components/PostOptionsMenu.tsx

> [!CAUTION]
AS-852 #done
https://as-852.preview.app.daily.dev

feat: Post options menu based on context

---

packages/shared/src/components/buttons/GetExtensionButton.tsx

> [!CAUTION]
https://mi-706.preview.app.daily.dev

fix: Fix extension banner experiment button width

---

packages/shared/src/components/profile/SourceList.tsx

Use source links correctly
> [!CAUTION]
https://as-891-source-links.preview.app.daily.dev

fix: source links

---

packages/extension/src/companion/Companion.tsx
packages/extension/src/newtab/App.tsx
packages/shared/src/contexts/AuthContext.tsx
packages/shared/src/contexts/BootProvider.tsx
packages/shared/src/hooks/log/useLogContextData.ts
packages/shared/src/hooks/log/useLogPageView.ts
packages/shared/src/hooks/log/useLogQueue.ts
packages/shared/src/hooks/referral/useJoinReferral.spec.tsx

Reverts dailydotdev/apps#3759
https://revert-3759-fix-analytics-boot.preview.app.daily.dev

Revert "fix: analytics at boot time"

---

packages/shared/src/lib/constants.ts

Add order by blocked by API:
https://github.com/dailydotdev/daily-api/pull/2563
> [!CAUTION]
https://as-877-order-by-date.preview.app.daily.dev

fix: order by date

---

packages/shared/src/components/layout/common.tsx

Ensure feed settings show for my feed :) 
> [!CAUTION]
https://hotfix-feed-settings.preview.app.daily.dev

feat: feed settings my feed

---

packages/shared/src/components/feeds/FeedSettings/FeedSettingsEditHeader.tsx

All tabs besides the general tab should simply show a mockup "save" button that simply closes the modal to mimic a save. (everything is realtime saving)
> [!CAUTION]
https://chore-save-button.preview.app.daily.dev

chore: save button

---

packages/shared/src/components/feeds/FeedSettings/FeedSettingsEditHeader.tsx

Remove button on my feed.
> [!CAUTION]
https://fix-main-feed-button.preview.app.daily.dev

fix: don't show button on my feed

---

packages/shared/src/components/auth/AuthenticationBanner.tsx
packages/shared/src/components/banners/personalized/GeoPersonalizedBanner.tsx
packages/shared/src/components/banners/personalized/SocialPersonalizedBanner.tsx
packages/shared/src/components/banners/personalized/UserPersonalizedBanner.tsx
packages/shared/src/lib/featureManagement.ts

Experiment lost, can be cleaned up
> [!CAUTION]
https://chore-cleanup-post-banner-extens.preview.app.daily.dev

chore: cleanup post_banner_extension_prompt

---

packages/shared/src/components/modals/common.tsx
packages/shared/src/components/modals/common/types.ts
packages/shared/src/components/modals/plus/SmartPromptModal.tsx
packages/shared/src/components/post/PostContent.tsx
packages/shared/src/lib/log.ts

TODO: Awaiting right image
> [!CAUTION]
AS-908 #done 
https://as-908-smart-prompt-modal.preview.app.daily.dev

feat: smart prompt modal

---

packages/shared/src/components/banners/personalized/UserPersonalizedBanner.tsx

> [!CAUTION]
https://mi-712.preview.app.daily.dev

fix: Missing cleanup on post auth banner

---

packages/shared/src/hooks/contentPreference/useFollowingQuery.ts

"Following" modal should now correctly fetch more users
> [!CAUTION]
WT-2244 #done
https://wt-2244.preview.app.daily.dev

fix: Infinite scroll on following modal

---

packages/shared/src/components/cards/Freeform/FreeformList.tsx

| -------- | ------- |
| ![Screenshot 2025-01-06 at 9 25 38 PM](https://github.com/user-attachments/assets/81e97e86-684c-4b46-b8b9-8b3f76dfed9c) | ![Screenshot 2025-01-06 at 9 26 36 PM](https://github.com/user-attachments/assets/1682c204-3957-4259-a7a7-881f7807765d) |
> [!CAUTION]
https://fix-freeform.preview.app.daily.dev

fix: freeform spacing between actions and title

---

packages/shared/src/components/modals/plus/SmartPromptModal.tsx
packages/shared/src/components/post/smartPrompts/PromptButtons.tsx
packages/shared/src/lib/image.ts

Render the modal on mobile views
> [!CAUTION]
https://as-910-mobile-modal.preview.app.daily.dev

fix: render modal on mobile

---

packages/shared/src/components/profile/Header.tsx
packages/shared/src/hooks/contentPreference/types.ts
packages/shared/src/hooks/contentPreference/useContentPreference.ts

[Reason](https://dailydotdev.slack.com/archives/C07GVUM114N/p1736956570525519?thread_ts=1736956481.201049&cid=C07GVUM114N)
> [!CAUTION]
https://mi-757.preview.app.daily.dev

fix: No longer open report modal when reporting user

---

packages/shared/src/graphql/users.ts

See API PR https://github.com/dailydotdev/daily-api/pull/2601
> [!CAUTION]
https://fix-read-history-calendar.preview.app.daily.dev

fix: user read history calendar

---

packages/shared/src/hooks/contentPreference/useContentPreference.ts

https://mi-760.preview.app.daily.dev/

fix: cache invalidation

---

packages/shared/src/contexts/PaymentContext.tsx

- Lower price were evaluated based on formatted price (string), moved to unformatted (int) check.
> [!CAUTION]
https://mi-764-fix-plus-discount.preview.app.daily.dev

fix: plus wrong discounted price

---

packages/shared/src/components/auth/RegistrationForm.tsx

> [!CAUTION]
https://verify-skip-dev.preview.app.daily.dev

feat: skip verification in dev

---

packages/shared/src/lib/featureManagement.ts
packages/webapp/pages/onboarding.tsx

The experiment won, so we are keeping it!
Added an extra check to see if they're already on the PWA or not.
> [!CAUTION]
https://mi-761.preview.app.daily.dev

chore: Cleanup ios PWA experiment

---

packages/shared/src/components/profile/ProfileWidgets.spec.tsx
packages/shared/src/components/profile/SocialChips.tsx

> [!CAUTION]
https://bsy-chip-correction.preview.app.daily.dev

fix: Minor label correction on bsky

---

packages/shared/src/components/BookmarkFeedLayout.tsx
packages/shared/src/hooks/useFeedLayout.ts

This reverts commit 6e1f6730fa21ad93107f00e301421e967bc6fe93.
> [!CAUTION]
https://revert-hydration-fix.preview.app.daily.dev

Revert "fix: hydration issues (#4090)"

---

packages/webapp/pages/account/privacy.tsx

fix: page title on privacy page

---

packages/shared/src/components/modals/user/CookieConsentItem.tsx
packages/shared/src/components/modals/user/CookieConsentModal.spec.tsx
packages/shared/src/components/video/YoutubeVideoWithoutConsent.tsx
packages/shared/src/hooks/useCookieConsent.ts

- Adjust spacings and remove source on mobile.
- Set the others to false by default.
> [!CAUTION]
https://fix-mobile-view.preview.app.daily.dev

fix: source is hidden on mobile

---

packages/shared/src/components/streak/popup/ReadingStreakPopup.tsx

Closes https://github.com/dailydotdev/daily/issues/1715
> [!CAUTION]
https://fix-streak-settings-link-extensi.preview.app.daily.dev

fix: streak settings link in extension

---

packages/shared/src/components/plus/PlusCheckoutContainer.tsx
packages/shared/src/components/plus/PlusDesktop.tsx
packages/shared/src/components/plus/PlusPlus.tsx
packages/shared/src/components/plus/PlusUnavailable.tsx
packages/shared/src/contexts/PaymentContext.tsx
packages/webapp/pages/plus/payment.tsx

Currently missing gift text since it is not live yet. 
Opened from https://github.com/dailydotdev/apps/pull/4101 since it contains `isPlusAvailable` logic
> [!CAUTION]
AS-951 #done
https://as-951-plus-already.preview.app.daily.dev

feat: user is plus already

---

packages/shared/src/components/post/PostComments.tsx

[On mobile (below 420PX), we remove the padding around the comments](https://www.figma.com/design/nmfWPS7x3kzLUvYMkBx2kW/daily.dev---Dev-Mode?node-id=23027-18359&m=dev)
> [!CAUTION]
https://mi-769.preview.app.daily.dev

feat: fix comment padding on mobile

---

packages/shared/src/graphql/fragments.ts

Closes dailydotdev/daily#1633
> [!CAUTION]
https://mi-772.preview.app.daily.dev

fix: Add collapsed pins property

---

packages/shared/src/components/ProfileMenu.tsx
packages/shared/src/components/UpgradeToPlus.tsx
packages/shared/src/components/profile/ProfileSettingsMenu.tsx
packages/shared/src/contexts/PushNotificationContext.tsx
packages/shared/src/lib/func.ts
packages/shared/src/styles/globals.css
packages/shared/src/styles/ios.css

Remove Plus and embed ios specific styles.
https://more-ios.preview.app.daily.dev

feat: ios native review followup

---

packages/shared/src/components/auth/OnboardingRegistrationForm.tsx
packages/webapp/pages/onboarding.tsx

On iOS native first login screen render google and apple login:
Don't show plus in onboarding if isIOSnative.
> [!CAUTION]
https://chore-ios-fixes.preview.app.daily.dev

fix: ios review

---

packages/shared/src/components/profile/LanguageDropdown.tsx
packages/shared/src/hooks/useLanguage.ts
packages/shared/src/lib/boot.ts
packages/shared/src/lib/featureManagement.ts
packages/shared/src/lib/user.ts

> [!CAUTION]
https://feat-more-languages.preview.app.daily.dev

refactor: use remote config for valid languages

---

packages/shared/src/components/feeds/FeedSettingsButton.tsx
packages/shared/src/lib/labels.ts
packages/webapp/pages/feeds/[slugOrId]/edit.tsx

- when user is not plus and they try to edit custom feed they get an prompt to upgrade
- also redirect to homepage if someone goes to edit feed directly
> [!CAUTION]
https://custom-feed-improvements-2.preview.app.daily.dev

feat: custom feed settings prompt when not plus

---

packages/shared/src/components/onboarding/OnboardingPlusStep.tsx
packages/shared/src/components/plus/PlusInfo.tsx
packages/shared/src/components/plus/PlusList.tsx

new feature copy and ordering
add smart prompts in coming soon
> [!CAUTION]
https://com-975.preview.app.daily.dev

feat: optimized copy for /plus

---

packages/shared/src/components/squads/SharePostBar.tsx

Fix clipping of the url in share post bar 
https://github.com/user-attachments/assets/158d7c99-ac89-44a4-b9cf-18661955aaf0
> [!CAUTION]
https://mi-778.preview.app.daily.dev

fix: share post bar clipping

---

packages/shared/src/components/onboarding/OnboardingHeader.tsx
packages/shared/src/components/plus/PlusDesktop.tsx
packages/shared/src/components/plus/PlusInfo.tsx
packages/shared/src/components/plus/PlusMobile.tsx
packages/shared/src/components/plus/common.ts
packages/shared/src/lib/featureManagement.ts
packages/webapp/pages/onboarding.tsx
packages/webapp/pages/plus/index.tsx

- Replace the Plus page from onboarding with the Plus checkout page.
> [!CAUTION]
https://mi-776.preview.app.daily.dev

feat: plus checkout on onboarding experiment

---

packages/shared/src/components/Pixels.tsx
packages/shared/src/components/ProfileMenu.tsx
packages/shared/src/lib/geo.ts
packages/webapp/pages/account/privacy.tsx
packages/webapp/public/scripts/fb.js
packages/webapp/public/scripts/gtag.js

Instead of not loading them which affects our marketing performance, there's a consent mode we can utilize.
Also design requested to show privacy page to everyone.
https://consent-mode.preview.app.daily.dev

fix: use consent mode for google and facebook

---

packages/shared/src/contexts/PaymentContext.tsx

- Enable showing promo codes.
> [!CAUTION]
https://fix-missing-discount.preview.app.daily.dev

fix: missing discount field from Paddle

---

packages/shared/src/components/post/SharePostContent.tsx

We should only hit private if the sharedPost is in a squad and private.
Else `unknown` would also hit (which is 90% of squad shared)
You can try here:
https://fix-share-private.preview.app.daily.dev/squads/cso
These where all showing the private thing before :) 
> [!CAUTION]
https://fix-share-private.preview.app.daily.dev

fix: only hit private on squads

---

packages/shared/src/components/onboarding/OnboardingPlusStep.tsx
packages/shared/src/components/plus/PlusInfo.tsx
packages/shared/src/components/plus/PlusList.tsx
packages/shared/src/components/plus/PlusPlus.tsx

> [!CAUTION]
https://hotfix-copy-changes.preview.app.daily.dev

Hotfix: minor copy changes to several Plus properties

---

packages/shared/src/contexts/AuthContext.tsx
packages/shared/src/contexts/PaymentContext.tsx
packages/webapp/pages/onboarding.tsx

- The `PaymentContext` is not available from all pages, only when it needs to be.
- The concern is, even before rendering the Context, we must identify if it should be allowed.
- To make it more accessible, I added the check from the auth context.
> [!CAUTION]
https://fix-onboarding-plus.preview.app.daily.dev

fix: onboarding plus for valid countries only

---

packages/shared/src/contexts/PaymentContext.tsx

> [!CAUTION]
https://chore-filter-new-pricing.preview.app.daily.dev

refactor: payment context to filter out gifting pricing

---

packages/shared/src/lib/constants.ts
packages/shared/src/lib/func.ts
packages/webapp/pages/callback.tsx

- There is currently an issue with Facebook login (using incognito). For some reason, on first instance, it is not sending the message through our event listeners on others tab.
- There is a modern way of working with sending messages across tabs, and that is by using the [Broadcast Channel API](https://developer.mozilla.org/en-US/docs/Web/API/Broadcast_Channel_API).
- There are no listeners to the broadcast hence nothing will be affected. I will be testing this through the previews. Unfortunately, this needs to be in main since the callbacks from social providers are always directed at prod.
Inspired by this potential [OSS contribution](https://github.com/dailydotdev/apps/pull/3599).
> [!CAUTION]
> Please …

experimental: usage of broadcast channel

---

packages/shared/src/components/video/YoutubeVideoWithoutConsent.tsx

Consent space was missing:
| ![Screenshot 2025-02-06 at 15 14 16](https://github.com/user-attachments/assets/38f3314a-57a0-41d6-87bc-6abbc1db1b9f) | ![Screenshot 2025-02-06 at 15 15 52](https://github.com/user-attachments/assets/78c062bb-a282-4983-89c1-f89f0fcb4460) | 
> [!CAUTION]
https://fix-consent-space.preview.app.daily.dev

fix: issue with consent space

---

packages/shared/src/graphql/feed.ts
packages/shared/src/graphql/fragments.ts
packages/shared/src/graphql/posts.ts
packages/shared/src/hooks/post/useSmartTitle.ts
packages/shared/src/hooks/translation/useTranslation.ts

- need to do testing e2e when kvasir is merged https://github.com/dailydotdev/kvasir/pull/5
> [!CAUTION]
https://as-965-use-translate-update.preview.app.daily.dev

feat: new translate endpoint and fields support

---

packages/webapp/components/layouts/AccountLayout/SidebarNav.tsx
packages/webapp/components/layouts/AccountLayout/common.tsx

Privacy link didn't work on mobile and also we need to show this page to everyone
https://privacy-fix.preview.app.daily.dev

fix: show privacy on mobile to everyone + link fix

---

packages/shared/src/components/onboarding/OnboardingPlusStep.tsx
packages/shared/src/components/plus/PlusDesktop.tsx
packages/shared/src/components/plus/PlusInfo.tsx

- Solves https://dailydotdev.slack.com/archives/C01L0QXQJNB/p1738834873238209
> [!CAUTION]
https://feat-onboarding-plus-skeleton.preview.app.daily.dev

feat: add plus skeleton in onboarding

---

packages/shared/src/hooks/auth/useOnboarding.tsx

Breaks all anonymous pages
We need to find different fix for problem.
> [!CAUTION]
https://hotfix-redirect.preview.app.daily.dev

fix: this breaks annonymous pages now, urgent

---

packages/shared/src/components/plus/PlusList.tsx

This is now ready
> [!CAUTION]
https://fix-ready-feature.preview.app.daily.dev

fix: smart prompt is now ready

---

packages/shared/src/components/cards/socials/SocialIconButton.tsx

> [!CAUTION]
https://mi-789.preview.app.daily.dev

feat: use shortlink in social icon button

---

packages/shared/src/components/profile/ProfileSettingsMenu.tsx
packages/shared/src/components/sidebar/sections/ResourceSection.tsx
packages/shared/src/lib/constants.ts

- advertise link in sidebar
> [!CAUTION]
https://mi-788-sidebar-advertise-cta.preview.app.daily.dev

feat: add advertise link in sidebar

---

packages/shared/src/graphql/feed.ts
packages/shared/src/graphql/fragments.ts
packages/shared/src/graphql/posts.ts
packages/shared/src/hooks/translation/useTranslation.ts
packages/shared/src/hooks/usePostById.ts

> [!CAUTION]
AS-979
https://as-979-translate-titlehtml.preview.app.daily.dev

feat: translate `titleHtml`

---

packages/shared/src/components/MainFeedLayout.tsx

Higher request limit for the search post page.
This is to quickly deal with large amount of private posts.
> [!CAUTION]
https://fix-search-post-limit.preview.app.daily.dev

fix: higher post results

---

packages/shared/src/lib/log.ts
packages/webapp/components/layouts/AccountLayout/Profile/index.tsx
packages/webapp/components/layouts/ProfileLayout/index.tsx

https://profile-events.preview.app.daily.dev

feat: add profile related events

---

packages/webapp/pages/_app.tsx

https://update-user-id-ios.preview.app.daily.dev

chore: send user id to native ios

---

packages/shared/src/components/plus/PlusList.tsx

> [!CAUTION]
https://copy-changes-to-plus.preview.app.daily.dev

feat: minor copy changes to Plus features

---

packages/shared/src/components/plus/PlusExtension.tsx
packages/shared/src/components/plus/PlusListModalSection.tsx
packages/shared/src/components/plus/PlusMarketingModal.tsx
packages/shared/src/components/plus/PlusMobileDrawer.tsx
packages/shared/src/components/plus/PlusWebapp.tsx
packages/shared/src/contexts/PaymentContext.tsx

As per Nimrod's feedback, I added an extra step to the webapp portion of the ideation tool. Now, just like the other steps, you have to click a button to show the checkout.
Flow demo:
https://github.com/user-attachments/assets/9bff2a2d-8457-4d52-8ea9-d1ba10b1ee84
> [!CAUTION]
MI-801 #done
https://mi-801.preview.app.daily.dev

feat: add extra step on webapp plus ideation

---

packages/shared/src/components/MainFeedLayout.tsx

With the proper filter in place we don't need as big page size for search.
https://github.com/dailydotdev/daily-api/pull/2664
> [!CAUTION]
https://chore-page-size.preview.app.daily.dev

fix: page size on search

---

packages/shared/src/components/cards/share/ShareGrid.tsx

Fixes the broken test.
https://fix-test.preview.app.daily.dev

fix: memoize shared post footer

---

.gitpod.yml
packages/webapp/package.json

Turns out we needed the flag 🙈 
https://fix-adhoc-tls.preview.app.daily.dev

fix: re-add ca to dev

---

packages/shared/src/components/cards/common/PostCardHeader.tsx
packages/shared/src/components/cards/common/list/hooks.ts
packages/shared/src/components/post/PostHeaderActions.tsx
packages/shared/src/components/post/SharePostContent.tsx
packages/shared/src/lib/featureManagement.ts

- Unified copy for all types of posts. We will use `Visit link` for everything.
- Feature value is boolean since video and non-video types will have different default values which will just make it harder to maintain.
> [!CAUTION]
https://mi-803.preview.app.daily.dev

feat: visit link copy for all types of posts

---

packages/shared/src/contexts/PaymentContext.tsx

Use name over description.
Description is meant to be an internal thing.
Also modifying the API.
> [!CAUTION]
https://fix-name-description-paddle.preview.app.daily.dev

fix: use name over description

---

packages/webapp/pages/plus/success.tsx

- Marketing CTA crashes the page randomly.
- For reference: https://github.com/dailydotdev/apps/pull/4209#discussion_r1964022584
Related issue: https://github.com/dailydotdev/daily/issues/1761
> [!CAUTION]
https://fix-success-page.preview.app.daily.dev

fix: plus success page crashing

---

packages/webapp/public/.well-known/apple-app-site-association

> [!CAUTION]
https://fix-plus-pages-apple-association.preview.app.daily.dev

feat: exclude plus pages opening the app for now

---

packages/shared/src/lib/constants.ts
packages/webapp/pages/plus/success.tsx

- New button on the plus success page.
Previews:
> [!CAUTION]
MI-804 #done
https://mi-804-button.preview.app.daily.dev

refactor: plus success page to plus overview docs

---

packages/shared/src/hooks/useConditionalFeature.ts

The previous implementation was subject to a race condition. The Growthbook instance could have been updated, but we never refetch the query in this case.
This implementation follows the approach of `useFeatureValue` with an additional step to check before enrolling the user.
https://fix-conditional-feature.preview.app.daily.dev

fix: race condition in conditional feature

---

packages/shared/src/components/post/SquadPostWidgets.tsx

[Report](https://dailydotdev.slack.com/archives/C01L0QXQJNB/p1740574397329979?thread_ts=1740543470.720169&cid=C01L0QXQJNB)
> [!CAUTION]
https://fix-squad-card-widget.preview.app.daily.dev

fix: squad card widget

---

.pnpmfile.cjs
packages/shared/package.json
pnpm-lock.yaml

Updates our GrowthBook package to make devtools work again. Not final version, need to wait for https://github.com/dailydotdev/growthbook/pull/3 to be merged first to get the correct hash.
https://fix-growthbook.preview.app.daily.dev

fix: update growthbook

---

.circleci/config.yml
packages/shared/src/components/post/SquadPostWidgets.tsx

We actually don't really use this, and it's flaky now.
> [!CAUTION]
https://chore-disable-build.preview.app.daily.dev

chore: disable build

---

packages/shared/src/components/onboarding/OnboardingPlusStep.tsx

> [!CAUTION]
https://fix-tosorted-error.preview.app.daily.dev

fix: removed toSorted as not fully supported

---

packages/shared/src/hooks/useLogin.ts
packages/webapp/pages/callback.tsx

- There could be an instance where `window.postMessage` is available but still the listener is not getting the message.
- Since FB is one we know that is always faulty, we fallback with this.
> [!CAUTION]
https://fix-facebook-referrer.preview.app.daily.dev

refactor: sending broadcast message if no post message or from facebook

---

packages/extension/src/lib/extensionScripts.ts
packages/extension/src/manifest.json
packages/shared/__tests__/fixture/squads.ts
packages/storybook/stories/components/cards/Squad/SquadGrid.stories.tsx

https://replace-local-com.preview.app.daily.dev

fix: replace all `local.com` with `local.fylla.dev`

---

packages/shared/src/components/plus/PlusExtension.tsx
packages/shared/src/components/plus/PlusInfo.tsx
packages/shared/src/components/plus/PlusList.tsx
packages/shared/src/components/plus/PlusListModalSection.tsx
packages/shared/src/components/plus/PlusTrustReviews.tsx
packages/shared/src/components/plus/PlusWebapp.tsx

Updated the ideation modal to have the reviews that were recently introduced:
> [!CAUTION]
https://mi-816.preview.app.daily.dev

feat: add reviews to plus marketing modal section

---

packages/shared/src/components/ProfilePicture.tsx
packages/shared/src/styles/base.css
packages/webapp/pages/earnings.tsx

Mockup components for earnings dashboard.
Most is mocked in same file as not sure on final implementation needs.
> [!CAUTION]
https://as-986-earnings.preview.app.daily.dev

feat: earnings

---

packages/shared/src/components/award/AwardButton.tsx
packages/shared/src/components/comments/CommentActionButtons.tsx
packages/shared/src/components/modals/award/GiveAwardModal.tsx
packages/shared/src/components/profile/Awards.tsx
packages/shared/src/components/profile/Header.tsx
packages/shared/src/contexts/GiveAwardModalContext.tsx
packages/webapp/pages/[userId]/index.tsx

Shows awards on profile (no interaction needed)
Added button to award user if not you
- Waiting for design as I want to uniform the modal more. (Added type to context so we know there's no comment step)
> [!CAUTION]
https://as-997-award-profile.preview.app.daily.dev

fix: show award on profile

---

packages/shared/src/contexts/AuthContext.tsx
packages/shared/src/contexts/BootProvider.tsx
packages/shared/src/lib/auth.ts
packages/shared/src/lib/boot.ts

Not used anywhere anymore
https://chore-remove-islegacylogout.preview.app.daily.dev

chore: cleanup `isLegacyLogout`

---

packages/shared/src/components/cards/common/PostTags.tsx
packages/shared/src/components/squads/moderation/SquadModerationItem.tsx
packages/shared/src/hooks/feed/useFollowPostTags.ts

Described issue [here](https://dailydotdev.slack.com/archives/C01L0QXQJNB/p1740821687697359)
> [!CAUTION]
MI-824
https://crashing-post-moderation.preview.app.daily.dev

fix: post tags crashing moderation page

---

packages/shared/src/components/post/tags/PostTagList.tsx

Add wrap to flex container for tags.
| <img width="370" alt="image" src="https://github.com/user-attachments/assets/d999334f-a913-45af-9251-eba343bac310" /> | <img width="370" alt="image" src="https://github.com/user-attachments/assets/bafd42f8-962b-488d-a4e6-56c1697d8720" /> | 
> [!CAUTION]
https://fix-tag-overflow.preview.app.daily.dev/posts/the-best-100-free-ui-ux-resources-for-every-designer-developer-nqusebn4o
https://fix-tag-overflow.preview.app.daily.dev

fix: tags are not going in new line

---

packages/shared/src/components/post/PostEngagements.tsx
packages/shared/src/contexts/SettingsContext.tsx
packages/shared/src/graphql/settings.ts

- Make sorting comments persist across platforms.
- Relevant API: https://github.com/dailydotdev/daily-api/pull/2676
> [!CAUTION]
https://mi-807.preview.app.daily.dev

feat: sort comments by across platforms

---

packages/shared/src/components/credit/BuyCreditsButton.tsx
packages/shared/src/components/modals/award/GiveAwardModal.tsx

Just the mock button for now:
> [!CAUTION]
https://feat-buy-credit-mock.preview.app.daily.dev

feat: buy credit mock (not functional)

---

packages/shared/src/components/plus/PlusOptionRadio.tsx
packages/shared/src/components/post/tags/PostTagList.tsx
packages/shared/src/graphql/paddle.ts

Requires https://github.com/dailydotdev/daily-api/pull/2683
> [!CAUTION]
https://fix-marketing-popup-extension.preview.app.daily.dev

fix: marketing popup extension showing wrong prices

---

packages/shared/src/components/auth/RegistrationForm.tsx

https://dailydotdev.slack.com/archives/C02E2C3C13R/p1741161469474239
https://fix-turnstile-theme.preview.app.daily.dev

fix: use `auto` theme on turnstile

---

packages/shared/src/components/onboarding/OnboardingPlusStep.tsx

> [!CAUTION]
https://fix-onboarding-yearly-price.preview.app.daily.dev

fix: sort onboarding prices

---

packages/shared/src/components/ProfileMenu.tsx
packages/shared/src/components/plus/PlusIOS.tsx
packages/shared/src/components/plus/PlusOptionRadio.tsx
packages/shared/src/components/profile/ProfileSettingsMenu.tsx
packages/shared/src/contexts/BootProvider.tsx
packages/shared/src/contexts/PaymentContext.tsx
packages/shared/src/graphql/users.ts
packages/shared/src/hooks/usePlusSubscription.ts
packages/shared/src/lib/featureManagement.ts
packages/shared/src/lib/func.ts
packages/shared/src/lib/ios.ts
packages/shared/src/lib/plus.ts
packages/shared/src/lib/user.ts
packages/webapp/pages/_app.tsx
packages/webapp/pages/account/subscription.tsx
packages/webapp/pages/plus/index.tsx

Todo: 
> [!CAUTION]
AS-1006
https://as-1006-plus-ios.preview.app.daily.dev

feat: purchase plus via iOS app

---

.github/pull_request_template.md
.github/workflows/add-preview-domain.yml

Updates the PR workflow to extract Jira ticket from branch name and adds it to the PR description, if it can detect it from the branch name.
AS-0000
https://as-0000-workflow-to-auto-comment.preview.app.daily.dev

feat: github workflow to automagically add Jira ticket to PR description

---

packages/shared/src/components/plus/PlusIOS.tsx
packages/shared/src/components/plus/PlusInfo.tsx
packages/shared/src/components/profile/ProfileSettingsMenu.tsx
packages/shared/src/contexts/payment/StoreKit.tsx
packages/shared/src/lib/ios.ts

https://as-1006-fixes.preview.app.daily.dev
AS-1006

fix: limit to team members and show warning message if using outdated app

---

packages/shared/src/contexts/PushNotificationContext.tsx
packages/shared/src/lib/auth.ts
packages/shared/src/lib/ios.ts
packages/webapp/context/PixelsContext.tsx
packages/webapp/pages/_app.tsx

Updates the pre-existing message handlers to use the new utils
Not blocking for iOS release #4260
https://refactor-ios-message-handling.preview.app.daily.dev

refactor: improve DX for message handling with iOS

---

packages/shared/src/components/cores/CoreAmountNeeded.tsx
packages/shared/src/components/cores/CoreFAQ.tsx
packages/shared/src/components/cores/CoreOptionButton.tsx
packages/shared/src/components/cores/CoreOptionList.tsx
packages/shared/src/components/credit/BuyCreditsButton.tsx
packages/shared/src/components/modals/award/BuyCoresModal.tsx
packages/shared/src/components/modals/award/GiveAwardModal.tsx
packages/shared/src/contexts/BuyCoresContext.tsx
packages/shared/src/contexts/GiveAwardModalContext.tsx
packages/shared/src/styles/base.css
packages/shared/tailwind/colors/action.ts
packages/webapp/components/layouts/CoresLayout.tsx
packages/webapp/pages/cores/index.tsx

Add the buy core flow and buy core page.
Context based so it's dynamic.
> [!CAUTION]
https://as-990-buy-cores-flow.preview.app.daily.dev

feat: buy cores flow

---

packages/shared/src/components/plus/PlusIOS.tsx
packages/shared/src/components/plus/PlusInfo.tsx
packages/shared/src/lib/func.ts
packages/shared/src/lib/utils.ts

- Adds a new event listener to listen for the `iap-loading` events added in https://github.com/dailydotdev/ios/pull/12
AS-1006
https://as-1006-loading.preview.app.daily.dev

feat: loading indicator

---

packages/shared/src/components/award/AwardButton.tsx
packages/shared/src/components/comments/CommentActionButtons.tsx
packages/shared/src/components/modals/award/GiveAwardModal.tsx
packages/shared/src/components/post/PostActions.tsx
packages/shared/src/components/post/PostUpvotesCommentsCount.tsx
packages/shared/src/components/profile/Header.tsx
packages/shared/src/contexts/BootProvider.tsx
packages/shared/src/contexts/GiveAwardModalContext.tsx
packages/shared/src/graphql/comments.ts
packages/shared/src/graphql/fragments.ts
packages/shared/src/graphql/furtherReading.ts
packages/shared/src/graphql/njord.ts
packages/shared/src/graphql/posts.ts
packages/shared/src/lib/query.ts
packages/shared/src/lib/user.ts

- connect basic award post/user flow
- mutations and cache updates
- balance update in boot
- fetch products
- award count
Also needs https://github.com/dailydotdev/daily-api/pull/2688
To test locally you need njord and some feature flags, let me know and I'll share the setup, we should have local setup next week 🤞 
> [!CAUTION]
https://award-post.preview.app.daily.dev

feat: award post/user

---

packages/shared/src/components/plus/PlusIOS.tsx

Fixes edge case where you get sent to the success page when on the plus page and you already have a subscription and it renews in the background, causing the success event message to be sent, and sending you to the success page.
AS-1006
https://as-1006-fix-backround-renewal.preview.app.daily.dev

fix: only listen for purchase-result when continuing

---

packages/shared/src/components/auth/AuthOptions.tsx
packages/shared/src/components/auth/EmailCodeVerification.tsx
packages/shared/src/components/auth/OnboardingRegistrationForm.tsx
packages/shared/src/components/auth/SignupDisclaimer.tsx
packages/shared/src/components/feeds/FeedNav.tsx
packages/shared/src/components/feeds/FeedPreviewControls.tsx
packages/shared/src/lib/featureManagement.ts
packages/webapp/components/banner/CookieBanner.tsx
packages/webapp/pages/onboarding.tsx

- The experiment won.
- Reference: https://dailydotdev.slack.com/archives/C02JAUF8HJL/p1741675315823169?thread_ts=1741672570.343109&cid=C02JAUF8HJL
> [!CAUTION]
https://chore-cleanup-papercuts.preview.app.daily.dev

chore: clean up onboarding papercuts

---

packages/shared/src/hooks/useCookieConsent.ts

- We don't store or access the cookies when using extension, hence we won't need to show the banner as we are not collecting anything.
- Discussion: https://dailydotdev.slack.com/archives/C01L0QXQJNB/p1741698617723709?thread_ts=1741685052.536169&cid=C01L0QXQJNB
> [!CAUTION]
https://fix-yt.preview.app.daily.dev

fix: yt overlay being shown

---

packages/webapp/components/layouts/AccountLayout/Security/index.tsx

**Link to issue:** https://github.com/dailydotdev/daily/issues/1783
This PR corrects a grammatical issue in the **Security settings** menu under the header **"Add login account"**. The original text was:  
> "Add more accounts to ensure you never lose access to your daily.dev profile and to make login quick and easy cross device"  
The phrase **"cross device"** is grammatically incorrect. It has been revised to:  
> "Add more accounts to ensure you never lose access to your daily.dev profile and to make logging in quick and easy across devices."
- Changed **"cross device"** → **"across devices"** for proper grammar.  
- Changed **"make login"** → **"make logging in"** for more natural readability.  
No.
No. …

fix: correct grammar in Security settings text under 'Add login account'

---

packages/shared/src/components/award/AwardButton.tsx
packages/shared/src/components/comments/CommentActionButtons.tsx
packages/shared/src/components/comments/CommentContainer.tsx
packages/shared/src/components/post/PostActions.tsx
packages/shared/src/contexts/GiveAwardModalContext.tsx
packages/shared/src/graphql/comments.ts
packages/shared/src/graphql/fragments.ts
packages/shared/src/graphql/njord.ts

Not final design due to missing reward assets, but all the state is connected
API https://github.com/dailydotdev/apps/pull/4279
> [!CAUTION]
https://award-comment.preview.app.daily.dev

feat: award comment

---

packages/shared/src/components/auth/EmailCodeVerification.tsx
packages/shared/src/hooks/useAccountEmailFlow.ts
packages/shared/src/hooks/useTimer.ts

- Start the timer of OTP to avoid resending another code that can confuse the user.
- More context: https://dailydotdev.slack.com/archives/C02AA18RD1D/p1741855170749749
> [!CAUTION]
https://fix-email-code.preview.app.daily.dev

fix: email code by starting the timer on load

---

packages/shared/src/components/plus/PlusExtension.tsx
packages/shared/src/components/plus/PlusListModalSection.tsx
packages/shared/src/lib/featureManagement.ts

- Allow experimenting on the plus screen takeover.
> [!CAUTION]
MI-832
https://mi-832.preview.app.daily.dev

feat: plus screen takeover experiment

---

Tiltfile

Adds include for njord tilt file so it can be started

feat: add njord tilt reference

---

packages/shared/src/components/profile/ProfileSettingsMenu.tsx
packages/shared/src/contexts/payment/StoreKit.tsx

Removes the team member only flag and opens it up for supported app versions.
AS-1006
https://as-1006-release.preview.app.daily.dev

fix: release plus to all supported iOS

---

packages/shared/src/components/modals/BootPopups.tsx
packages/shared/src/components/plus/PlusIOS.tsx
packages/shared/src/components/plus/PlusMarketingModal.tsx

Adds support the for plus marketing CTA on iOS. Mostly for tablet, as mobile takes you to plus page.
> [!CAUTION]
AS-1030
https://as-1030-plus-marketing-ios.preview.app.daily.dev

fix: add support for plus marketing CTA on iOS

---

packages/shared/package.json
packages/shared/src/components/comments/CommentActionButtons.tsx
packages/shared/src/components/cores/CoreAmountNeeded.tsx
packages/shared/src/components/cores/CoreOptionButton.tsx
packages/shared/src/components/cores/CoreOptionList.tsx
packages/shared/src/components/credit/BuyCreditsButton.tsx
packages/shared/src/components/modals/award/BuyCoresModal.tsx
packages/shared/src/components/modals/award/GiveAwardModal.tsx
packages/shared/src/components/profile/ProfileButton.tsx
packages/shared/src/contexts/BuyCoresContext.tsx
packages/shared/src/contexts/payment/context.ts
packages/shared/src/graphql/njord.ts
packages/shared/src/graphql/paddle.ts
packages/shared/src/lib/image.ts
packages/shared/src/lib/query.ts
packages/webapp/package.json
packages/webapp/pages/cores/index.tsx
packages/webapp/pages/earnings.tsx
pnpm-lock.yaml

- balance display is connected from boot
- connected logic of fetching and selecting core products
- minor design/flow adjustments
- checkout and transaction processing (currently done with http pulling, since our websockets pods are a mess)
- optimistic data and transactions
- minor fixes
API https://github.com/dailydotdev/daily-api/pull/2701
> [!CAUTION]
https://purchase-cores.preview.app.daily.dev

feat: purchase cores

---

packages/shared/src/components/auth/ForgotPasswordForm.spec.tsx
packages/shared/src/hooks/useAccountEmailFlow.ts

Heimdall works as follows:
- Signup
- Get code
- Validate code against signup flow
In case of resend 
- Create new empty flow
- Validate code against new flow
What we did:
In case of resend
- Try to send new code on old flow -> throws error
- Validate new code against old flow
This PR might seem a bit messy, due to the manual query data setting, but it's because we use flows seperate.
See my comment here for more future proof idea:
https://dailydotdev.atlassian.net/wiki/spaces/HAN/pages/1517649933/Improvement+ideas?force_transition=08a0ce1a-b5df-4e9e-a434-d9b383ea091c
> [!CAUTION]
https://fix-resend-new-flow.preview.app.daily.dev

fix: resend new flow

---

packages/shared/src/components/plus/PlusIOS.tsx
packages/shared/src/contexts/payment/StoreKit.tsx
packages/shared/src/hooks/useIOSError.ts
packages/webapp/pages/_app.tsx

Added a new EventDispatcher on iOS that has a couple more events we can use.
And added comments for future removal once v1.6 is low enough.
Only adds stuff, so doesn't break existing app.
> [!CAUTION]
https://chore-ios-more-events.preview.app.daily.dev

fix: add more logs on iOS subscription

---

packages/shared/src/components/cores/BuyCore.tsx
packages/shared/src/components/cores/CoreOptionButton.tsx
packages/shared/src/components/cores/FeaturedCoresWidget.tsx
packages/shared/src/components/cores/TransactionItem.tsx
packages/shared/src/components/credit/BuyCreditsButton.tsx
packages/shared/src/components/fields/ProgressBar.tsx
packages/shared/src/components/icons/CreditCard/filled.svg
packages/shared/src/components/icons/CreditCard/index.tsx
packages/shared/src/components/icons/CreditCard/outlined.svg
packages/shared/src/components/icons/index.ts
packages/shared/src/components/modals/award/BuyCoresModal.tsx
packages/shared/src/components/modals/award/GiveAwardModal.tsx
packages/shared/src/components/plus/PlusList.tsx
packages/shared/src/components/post/PostActions.tsx
packages/shared/src/contexts/BuyCoresContext.tsx
packages/shared/src/graphql/fragments.ts
packages/shared/src/graphql/njord.ts
packages/shared/src/lib/constants.ts
packages/shared/src/lib/dateFormat.ts
packages/shared/src/lib/transaction.tsx
packages/shared/src/lib/utils.ts
packages/shared/src/types.ts
packages/webapp/pages/cores/index.tsx
packages/webapp/pages/earnings.tsx

> [!CAUTION]
https://earnings-dashboard.preview.app.daily.dev

feat: earnings dashboard data

---

packages/shared/src/contexts/payment/Paddle.tsx

> [!CAUTION]
MI-835
https://mi-835-plus-checkout-one-step.preview.app.daily.dev

feat: add plus checkout in one page

---

packages/shared/src/components/modals/award/GiveAwardModal.tsx
packages/shared/src/contexts/GiveAwardModalContext.tsx

<table>
<tr>
<td>Before
<td>After
<tr>
<td><img src=https://github.com/user-attachments/assets/8c3a4742-2ee3-45a5-a6e7-85b1d2f0be4f>
<td><img src=https://github.com/user-attachments/assets/d350395a-66b2-43bb-9be6-1f9e998b77c3>
</table>
AS-1055
https://as-1055-show-user-icon.preview.app.daily.dev

fix: show profile image when no awards already exist on post

---

packages/shared/src/components/feeds/FeedSettings/sections/FeedSettingsTagsSection.tsx

This was set to only filter locally, maybe at one stage for POC around custom feeds or onboarding feed? (CC: @capJavert  you recall anything?)
However when set to local it doesn't persist to would only affect local state not fire the mutation.
It already happened for the first screen, so simply removed that local only state.
Solves:
https://github.com/dailydotdev/daily/issues/1786
> [!CAUTION]
https://fix-my-tag-filter.preview.app.daily.dev

fix: my tag filter

---

packages/shared/src/components/profile/ProfileButton.tsx

Add tooltip full value:
> [!CAUTION]
AS-1056
https://as-1056-tooltip-format.preview.app.daily.dev

fix: add tooltip full value

---

packages/shared/src/components/comments/CommentActionButtons.tsx
packages/shared/src/components/post/PostActions.tsx
packages/shared/src/components/profile/Header.tsx
packages/shared/src/components/profile/ProfileButton.tsx
packages/shared/src/lib/cores.ts
packages/shared/src/lib/user.ts
packages/webapp/components/layouts/CoresLayout.tsx
packages/webapp/pages/[userId]/index.tsx
packages/webapp/pages/cores/index.tsx
packages/webapp/pages/earnings.tsx

AS-1061
https://as-1061-hide-award-ui.preview.app.daily.dev

fix: hide cores and awards when role is none

---

packages/shared/src/components/UpgradeToPlus.tsx

The experiment colors didn't take the original passed color into account (thus mix them)
Also noticed some of the ones needed hardcoded text colors. (as they fully custom already)
> [!CAUTION]
https://fix-experiment-colors.preview.app.daily.dev

fix: experiment colors

---

packages/shared/src/components/cores/CoreFAQ.tsx
packages/shared/src/components/cores/common.tsx
packages/shared/src/components/plus/common.tsx
packages/shared/src/types.ts

Updates cores FAQ
AS-1051
https://as-1051-cores-faq.preview.app.daily.dev

chore: update cores FAQ

---

packages/shared/src/components/fields/RadioItem.tsx
packages/shared/src/features/onboarding/shared/PricingPlan.module.css
packages/shared/src/features/onboarding/shared/PricingPlan.spec.tsx
packages/shared/src/features/onboarding/shared/PricingPlan.tsx
packages/shared/src/features/onboarding/shared/PricingPlans.spec.tsx
packages/shared/src/features/onboarding/shared/PricingPlans.tsx
packages/shared/src/features/onboarding/shared/index.ts
packages/storybook/stories/components/onboarding/PricingPlan.stories.tsx
packages/storybook/stories/components/onboarding/PricingPlans.stories.tsx

Introduce the pricing plan and pricing plans component. 
Highly customizable and has two variations.
Figma:  https://www.figma.com/design/nmfWPS7x3kzLUvYMkBx2kW/daily.dev---Dev-Mode?node-id=27351-6351&m=dev
https://funnels-pricing.preview.app.daily.dev

feat(funnels): pricing plans

---

packages/shared/src/components/comments/CommentActionButtons.tsx
packages/shared/src/components/post/PostActions.tsx
packages/shared/src/components/profile/Header.tsx
packages/shared/src/graphql/fragments.ts
packages/shared/src/graphql/users.ts
packages/shared/src/lib/cores.ts

Add new function that will determine if creator can accept cores.
And new render related function which combines state of user & creator to determine if we should show the buttons or not.
> [!CAUTION]
AS-1062
https://as-1062-creator-core-role.preview.app.daily.dev

fix: add creator core role evaluation

---

packages/shared/src/features/onboarding/shared/Reviews.tsx
packages/shared/src/features/onboarding/shared/index.ts
packages/storybook/stories/components/onboarding/Reviews.stories.tsx

Introduce the reviews component. Horizontally scrollable and fully customizable.
Figma: https://www.figma.com/design/nmfWPS7x3kzLUvYMkBx2kW/daily.dev---Dev-Mode?node-id=27352-35307&m=dev
Screenshot:
https://funnels-reviews.preview.app.daily.dev

feat(funnels): reviews

---

packages/shared/src/features/onboarding/shared/Box.tsx
packages/shared/src/features/onboarding/shared/CreditCards.tsx
packages/shared/src/features/onboarding/shared/ImageReview.tsx
packages/shared/src/features/onboarding/shared/Reviews.tsx
packages/shared/src/features/onboarding/shared/Stars.tsx
packages/shared/src/features/onboarding/shared/index.ts
packages/storybook/stories/components/onboarding/Box.stories.tsx
packages/storybook/stories/components/onboarding/ImageReview.stories.tsx

Introduce a new component to display a single review with an image
Figma:  https://www.figma.com/design/nmfWPS7x3kzLUvYMkBx2kW/daily.dev---Dev-Mode?node-id=27351-12179&m=dev
Screenshot:
https://review-image.preview.app.daily.dev

feat(funnels): image review

---

packages/shared/src/graphql/fragments.ts
packages/shared/src/graphql/njord.ts
packages/webapp/pages/wallet.tsx

API: https://github.com/dailydotdev/daily-api/pull/2736
> [!CAUTION]
https://transaction-fee-value.preview.app.daily.dev

feat: transaction fee value

---

packages/shared/src/graphql/actions.ts
packages/shared/src/graphql/njord.ts
packages/shared/src/lib/query.ts
packages/webapp/pages/_app.tsx

See API for more info https://github.com/dailydotdev/daily-api/pull/2737
> [!CAUTION]
https://check-cores-role.preview.app.daily.dev

feat: check cores role

---

packages/shared/src/features/onboarding/steps/FunnelPaymentSuccessful.spec.tsx
packages/shared/src/features/onboarding/steps/FunnelPaymentSuccessful.tsx
packages/shared/src/features/onboarding/types/funnel.ts
packages/storybook/stories/components/onboarding/FunnelPaymentSuccessful.stories.tsx

Added the "Payment successful" page for the funnels. Note that in the figma design, the background references the css var "--Blur-blur-glass". I found this in our styles as "bg-blur-glass", but it didn't seem to do anything. So I just added the normal blur and it looks the same as the blur in the design, no extra coloring, so I think we can just go with that.
[DESIGN](https://www.figma.com/design/nmfWPS7x3kzLUvYMkBx2kW/daily.dev---Dev-Mode?node-id=27364-100713&m=dev)
> [!CAUTION]
MI-848
https://mi-848.preview.app.daily.dev

feat(funnels): FunnelPaymentSuccessful Page

---

packages/shared/src/components/modals/award/BuyCoresModal.tsx
packages/shared/src/contexts/BuyCoresContext.tsx

Show error screen if processing fails
AS-1078
https://as-1078-max-retries-error.preview.app.daily.dev

fix: show error screen if processing fails

---

packages/shared/src/components/CustomFeedEmptyScreen.tsx
packages/shared/src/components/feeds/FeedSettings/components/SmartPrompts.tsx
packages/shared/src/components/feeds/FeedSettings/sections/FeedSettingsAISection.tsx
packages/shared/src/components/modals/ClickbaitShieldModal.tsx
packages/shared/src/components/modals/bookmark/BookmarkFolderModal.tsx
packages/shared/src/components/modals/plus/SmartPromptModal.tsx
packages/shared/src/components/modals/soon/BookmarkFolderSoonModal.tsx
packages/shared/src/components/plus/PlusMobileDrawer.tsx
packages/shared/src/components/plus/PostUpgradeToPlus.tsx

Wraps the upgrade to plus button in Link to use soft-navigate when navigating to plus page
> [!CAUTION]
https://fix-ux-soft-navigate-upgrade-plu.preview.app.daily.dev

fix: wrap button in Link to use soft navigate

---

packages/shared/src/components/Icon.tsx
packages/shared/src/components/modals/award/BuyCoresModal.tsx
packages/shared/src/lib/image.ts
packages/webapp/components/layouts/CoresLayout.tsx
packages/webapp/pages/cores/index.tsx

On mobile the get more screen needed to look different:
Now:
Discussion:
https://dailydotdev.slack.com/archives/C07VA1FJTDK/p1744190332685519
> [!CAUTION]
AS-1093
https://as-1093-mobile-get-more.preview.app.daily.dev

fix: mobile get more screen

---

packages/webapp/public/.well-known/apple-app-site-association

> [!CAUTION]
https://fix-apple-association-json.preview.app.daily.dev

fix: our apple association was not valid json for some time

---

packages/shared/src/features/onboarding/shared/DiscountTimer.spec.tsx
packages/shared/src/features/onboarding/shared/DiscountTimer.tsx
packages/shared/src/features/onboarding/steps/FunnelPricing.spec.tsx
packages/shared/src/features/onboarding/steps/FunnelPricing.tsx
packages/storybook/stories/components/onboarding/DiscountTimer.stories.tsx
packages/storybook/stories/components/onboarding/FunnelPricing.stories.tsx

- Added isActive prop to DiscountTimer component to control timer behavior.
- Updated tests to verify timer functionality based on isActive state.
- Enhanced storybook examples to demonstrate active and inactive states for both components.
https://discount-is-active.preview.app.daily.dev

feat: implement isActive prop for DiscountTimer and FunnelPricing components

---

packages/shared/__tests__/fixture/loggedUser.ts

Unable to build extension locally because missing type

fix: update type in test fixure

---

packages/shared/src/components/feeds/FeedSettings/components/SmartPrompts.tsx
packages/shared/src/components/feeds/FeedSettings/sections/FeedSettingsAISection.tsx
packages/shared/src/components/profile/LanguageDropdown.tsx

- feat: add new top block upgrade to plus
- fix: remove upgrade CTA in each section
- fix: update copy of translate section
- fix: disable language dropdown if not plus
AS-1089
https://as-1089-update-feed-settings.preview.app.daily.dev

fix: update feed settings

---

packages/shared/src/lib/featureManagement.ts
packages/webapp/pages/onboarding.tsx

Code was interfering with new changes needed
And it needed to be cleaned up: https://dailydotdev.slack.com/archives/C02JAUF8HJL/p1741974262240679?thread_ts=1739257296.427369&cid=C02JAUF8HJL
> [!CAUTION]
https://fix-cleanup-experiment.preview.app.daily.dev

fix: cleanup failed experiment

---

packages/shared/src/contexts/BuyCoresContext.tsx

> [!CAUTION]
https://fix-checkout-update-cores.preview.app.daily.dev

fix: checkout update cores

---

packages/shared/src/components/credit/BuyCreditsButton.tsx
packages/shared/src/components/modals/award/BuyCoresModal.tsx
packages/shared/src/components/modals/award/GiveAwardModal.tsx
packages/shared/src/components/profile/Header.tsx
packages/shared/src/hooks/useCoresFeature.ts
packages/webapp/components/layouts/CoresLayout.tsx
packages/webapp/pages/wallet.tsx

- hide purchase of Cores on iOS until IAP support
- added new hook for check
- hidden from
- buy credits button (hide +)
- mobile header on profile, hide +
- cores layout (cores and payment page), no access
- wallet hide sidebar options and buy cta
- buy more cores prompt, add insufficient funds disabled button
> [!CAUTION]
https://cores-ui-ios-app.preview.app.daily.dev

feat: cores ui ios app

---

packages/shared/src/components/PostOptionsMenu.tsx
packages/shared/src/lib/log.ts

- Add `Translate` to post context menu
AS-1089
https://as-1089-translate-context-menu.preview.app.daily.dev

feat: add Translate to post context menu

---

packages/shared/src/components/feeds/FeedSettings/useFeedSettingsEdit.tsx
packages/shared/src/components/feeds/FeedSettingsButton.tsx
packages/shared/src/components/plus/GiftPlusModal.tsx
packages/shared/src/components/plus/PlusExtension.tsx
packages/shared/src/components/plus/PlusMobile.tsx
packages/shared/src/lib/constants.ts
packages/webapp/pages/plus/payment.tsx

- Replaces all cases of `${webappUrl}plus` with `plusUrl`
https://chore-use-plusurl.preview.app.daily.dev

chore: replace `${webappUrl}plus` with `plusUrl`

---

packages/shared/src/components/onboarding/CreateFeedButton.tsx
packages/shared/src/components/onboarding/OnboardingHeader.tsx
packages/shared/src/components/onboarding/Plus/OnboardingPlusControl.tsx
packages/shared/src/components/onboarding/Plus/OnboardingPlusVariation.tsx
packages/shared/src/components/onboarding/Plus/PlusSuccess.tsx
packages/shared/src/components/onboarding/Plus/common.tsx
packages/shared/src/components/onboarding/common.ts
packages/shared/src/components/plus/PlusComparingCards.tsx
packages/shared/src/contexts/payment/Paddle.tsx
packages/shared/src/contexts/payment/StoreKit.tsx
packages/shared/src/contexts/payment/context.ts
packages/shared/src/contexts/payment/index.tsx
packages/shared/src/lib/featureManagement.ts
packages/webapp/pages/onboarding.tsx

Move onboarding plus payment step into onboarding flows.
This way we don't open new tab.
Had to modify the callbacks a bit.
And don't mind the `onClickNext` mess it was always messy 😂
> [!CAUTION]
AS-1095
https://as-1095-onboarding-plus-payment.preview.app.daily.dev

feat: onboarding plus payment

---

packages/shared/src/graphql/fragments.ts
packages/shared/src/graphql/posts.ts
packages/shared/src/hooks/post/useSmartTitle.ts
packages/shared/src/hooks/translation/useTranslation.ts

- Requests translations of summary field when post modal / page
AS-1089
https://as-1089-translate-summary.preview.app.daily.dev

feat: add summary to post translation request

---

packages/shared/src/features/onboarding/shared/FunnelStepper.tsx
packages/shared/src/features/onboarding/steps/FunnelPricing.tsx
packages/shared/src/features/onboarding/store/funnelStore.tsx

> [!CAUTION]
https://fix-pricing-step-timer.preview.app.daily.dev

fix(funnels): pricing step timer reset

---

packages/shared/src/components/comments/CommentActionButtons.tsx
packages/shared/src/components/comments/CommentContainer.tsx

Regression from https://github.com/dailydotdev/apps/pull/4381
- also hide award icon if no access
> [!CAUTION]
https://fix-awards-count-comment.preview.app.daily.dev

fix: show award count on comment when user is author

---

packages/shared/src/components/feeds/FeedSettings/FeedSettingsTitle.tsx
packages/shared/src/components/feeds/MobileFeedActions.tsx

This pull request includes changes to the `FeedSettingsTitle` and `MobileFeedActions` components to improve the layout and URL structure.
Layout improvement:
* [`packages/shared/src/components/feeds/FeedSettings/FeedSettingsTitle.tsx`](diffhunk://#diff-38cc87da8af6973e4409d0a44929773cc32734c25867fcdd1369d89e48cebd69L28-R36): Changed the container element from `div` to `span` for better inline layout handling.
URL structure improvement:
* [`packages/shared/src/components/feeds/MobileFeedActions.tsx`](diffhunk://#diff-e0cc61cbd614682c6010b346ae94092369709eb3fb4f24e6bdf3b7d4b0254643L58-R58): Removed an unnecessary slash from the URL path when linking to the user's profile.
https://fix-minor-semantics.preview.app.daily.dev

fix: two minor semantic issues

---

packages/shared/__tests__/setup.ts
packages/shared/src/components/auth/AuthOptionsInner.tsx
packages/shared/src/contexts/AuthContext.tsx
packages/shared/src/hooks/useRegistration.ts
packages/shared/src/lib/constants.ts
packages/shared/src/lib/featureManagement.ts
packages/webapp/pages/onboarding.tsx

When an user finishes the funnel, we want to send them to finish the onboarding. However, currently we have some logic that in certain cases will logout the user automatically. This PR seeks to prevent that. Additionally, if the user comes from a funnel, they should not be shown the plus step in onboarding
> [!CAUTION]
MI-857
https://mi-857.preview.app.daily.dev

feat(funnels): prevent auto-logout

---

packages/shared/src/contexts/AuthContext.tsx
packages/shared/src/features/onboarding/hooks/useFunnelCookies.ts
packages/shared/src/features/onboarding/shared/FunnelStepCtaWrapper.tsx
packages/shared/src/features/onboarding/shared/FunnelStepper.tsx
packages/webapp/pages/helloworld/index.tsx

> [!CAUTION]
https://feat-ssr-cookie-banner.preview.app.daily.dev

feat: SSR check for cookie banner

---

packages/shared/src/features/onboarding/hooks/useFunnelCookies.ts
packages/shared/src/features/onboarding/shared/FunnelStepBackground.tsx
packages/shared/src/features/onboarding/shared/FunnelStepCtaWrapper.tsx
packages/shared/src/features/onboarding/shared/FunnelStepper.tsx
packages/shared/src/features/onboarding/steps/FunnelLoading.tsx
packages/shared/src/features/onboarding/steps/FunnelPaymentSuccessful.tsx
packages/webapp/pages/helloworld/index.tsx

https://cookies-fix-funnels.preview.app.daily.dev

fix: ssr support and layout fix for cookie banner

---

packages/shared/src/features/onboarding/shared/ProgressBar.tsx

> [!CAUTION]
https://fix-funnel-progress-color.preview.app.daily.dev

fix(funnels): background color for progress bar

---

packages/shared/src/features/onboarding/steps/FunnelRegistration.spec.tsx
packages/shared/src/features/onboarding/steps/FunnelRegistration.tsx

- Made the signup page to fix the screen even with cookie banner
> [!CAUTION]
https://fix-signup-layout-with-cookies.preview.app.daily.dev

fix(funnels): adjust gradient height in funnel registration component

---

packages/shared/src/features/onboarding/steps/FunnelRegistration.tsx

- When the user goes through the funnel with in-app browser, we redirect them rather than our original callback flow.
- The issue was that, when the account used is already registered, the registration flow gets converted to a login flow.
- To make the redirection work with registration flow, we pass a `redirect_to` param when initializing it.
- With login flow, the param must be `return_to`.
- We are now passing both to support both cases.
- Also modified the way we send the `onTransition` flow. There is a good chance that it is going to be sent more than once which will affect our analytics.
> [!CAUTION] …

fix: redirect funnel

---

packages/shared/src/components/feeds/FeedNav.tsx
packages/shared/src/components/feeds/MobileFeedActions.tsx
packages/shared/src/components/filters/MyFeedHeading.tsx
packages/shared/src/components/sidebar/sections/MainSection.tsx

- Adds Settings link to sidebar
- Replaces feed filter with settings on mobile
- Adds feed filter to custom feeds on mobile
AS-1098
https://as-1098-settings-button.preview.app.daily.dev

feat: add settings icon to main sidebar

---

packages/shared/src/components/auth/AuthOptionsInner.tsx
packages/shared/src/components/auth/SocialRegistrationForm.tsx

> Need product team approval before merge
> [!CAUTION]
https://feat-funnel-signup-copy-change.preview.app.daily.dev

feat(funnels): update title/cta for Plus users in SocialRegistrationForm

---

packages/shared/src/features/onboarding/hooks/useFunnelTracking.ts
packages/shared/src/features/onboarding/types/funnelEvents.ts

> [!CAUTION]
https://fix-funnel-mouse-event-log.preview.app.daily.dev

fix(funnels): change mouse track events for better clarity

---

packages/shared/src/components/post/PostActions.tsx

Actually fix it this time #4422
https://but-actually-fix-it-this-time-30.preview.app.daily.dev

fix: also add canAward to dependency array

---

packages/webapp/__tests__/Callback.spec.tsx
packages/webapp/pages/__tests__/callback.spec.tsx

- We work quite a lot of auth-related features lately, to ensure things are going to work still as intended, I've written (vibe-coded rather) a few tests.
> [!CAUTION]
https://chore-callback-test.preview.app.daily.dev

test: callback page

---

packages/shared/src/components/comments/CommentContainer.tsx

Prevent the award from looking weird as they not all square images.
Mentioned here:
https://dailydotdev.slack.com/archives/C01L0QXQJNB/p1744792740215629
> [!CAUTION]
https://fix-award-stretch.preview.app.daily.dev

fix: object fit for awards on comments

---

packages/shared/src/components/fields/form/FormWrapper.tsx
packages/webapp/components/layouts/AccountLayout/Profile/index.tsx

The styling was missing.
Solves:
https://github.com/dailydotdev/daily/issues/1792
> [!CAUTION]
https://fix-profile-styling.preview.app.daily.dev

fix: edit profile header styling

---

packages/shared/src/components/Feed.spec.tsx
packages/shared/src/components/modals/report/ReportPostModal.tsx
packages/shared/src/report.ts

Updated post report reasons when selecting a reason to report the post. Depends on this [PR](https://github.com/dailydotdev/daily-api/pull/2784)
> [!CAUTION]
MI-808
https://mi-808.preview.app.daily.dev

feat: update post report reasons

---

packages/shared/src/components/streak/popup/DayStreak.tsx
packages/shared/src/components/streak/popup/ReadingStreakPopup.tsx
packages/shared/src/hooks/usePersistentContext.ts
packages/webapp/components/layouts/AccountLayout/SidebarNav.tsx
packages/webapp/components/layouts/AccountLayout/common.tsx
packages/webapp/pages/account/appearance.tsx
packages/webapp/pages/account/customization/streaks.tsx
packages/webapp/pages/account/notifications.tsx

- Removes the bottom section from the streaks popover
- Creates new streaks account page
- https://www.figma.com/design/nmfWPS7x3kzLUvYMkBx2kW/daily.dev---Dev-Mode?node-id=25307-6020&m=dev
- https://www.figma.com/design/nmfWPS7x3kzLUvYMkBx2kW/daily.dev---Dev-Mode?node-id=25620-33422&m=dev
AS-1098
https://as-1098-streaks.preview.app.daily.dev

feat: streaks account page

---

packages/shared/src/components/LazyImage.tsx
packages/shared/src/components/post/MarkdownPostContent.tsx
packages/shared/src/graphql/fragments.ts
packages/shared/src/graphql/posts.ts

Basically copy LazyImage and pipe in the `flags.coverVideo`, only used internally for our needs
Preview for Cores changelog https://video-cover.preview.app.daily.dev/posts/cores-awards-j48nvz0sg
> [!CAUTION]
https://video-cover.preview.app.daily.dev

feat: internal video cover

---

packages/shared/src/lib/transaction.tsx

- just fallback for receive transaction not having product, eg. when it assigned from system/marketing
> [!CAUTION]
https://transaction-receive-item.preview.app.daily.dev

feat: transaction receive item

---

packages/webapp/components/layouts/AccountLayout/FeedSettingsLayout.tsx
packages/webapp/components/layouts/AccountLayout/SidebarNav.tsx
packages/webapp/components/layouts/AccountLayout/index.tsx
packages/webapp/pages/account/feed/ai.tsx
packages/webapp/pages/account/feed/blocked.tsx
packages/webapp/pages/account/feed/general.tsx
packages/webapp/pages/account/feed/preferences.tsx
packages/webapp/pages/account/feed/sources.tsx
packages/webapp/pages/account/feed/tags.tsx

New account pages for feed settings
https://www.figma.com/design/nmfWPS7x3kzLUvYMkBx2kW/daily.dev---Dev-Mode?node-id=25636-19117&m=dev
AS-1098
https://as-1098-feed-settings.preview.app.daily.dev

feat: feed settings account page

---

packages/shared/src/components/profile/ProfileButton.tsx

Due to `Link` not accepting tooltip was not showing:
> [!CAUTION]
https://fix-cores-tooltip.preview.app.daily.dev

fix: cores tooltip anchor ref

---

packages/shared/src/components/ProfileMenu/ProfileMenuHeader.tsx
packages/shared/src/components/ProfileMenu/ProfileSectionItem.spec.tsx
packages/shared/src/components/ProfileMenu/ProfileSectionItem.tsx
packages/shared/src/components/profile/ProfileSettingsMenu.tsx

Increases the font size for the settings menu on mobile
https://dailydotdev.slack.com/archives/C0381BQUEN9/p1746770871807799
https://adjust-font-variant-mobile-setti.preview.app.daily.dev

fix: adjust typography type on settings menu for mobile

---

packages/shared/src/components/post/PostActions.tsx

When post has no award `int > undefined` is `false`, so if no award we now also just show current awarded icon.
> [!CAUTION]
https://fix-award-update-count.preview.app.daily.dev

fix: show first award next to count

---

packages/shared/src/components/comments/CommentActionButtons.tsx
packages/shared/src/components/modals/UserListModal.tsx
packages/shared/src/components/modals/award/GiveAwardModal.tsx
packages/shared/src/components/modals/award/ListAwardsModal.tsx
packages/shared/src/components/modals/common.tsx
packages/shared/src/components/modals/common/types.ts
packages/shared/src/components/post/PostUpvotesCommentsCount.tsx
packages/shared/src/components/profile/UserShortInfo.tsx
packages/shared/src/contexts/GiveAwardModalContext.tsx
packages/shared/src/graphql/njord.ts
packages/shared/src/lib/log.ts
packages/shared/src/lib/query.ts
packages/shared/src/lib/user.ts

- list awards for post/comment
- also add "Show all" button on give award modal to see all awards
API: https://github.com/dailydotdev/daily-api/pull/2802
| New | credits events | extra: { origin: awards list } |
> [!CAUTION]
https://list-awards.preview.app.daily.dev

feat: list awards

---

packages/shared/src/features/onboarding/steps/FunnelProfileForm.tsx
packages/shared/src/features/onboarding/types/funnel.ts
packages/webapp/pages/helloworld/index.tsx

- Use the param on where to redirect after finishing the funnel.
- Also fixed the headline on FunnelForm to be sanitized.
> [!CAUTION]
https://redirect-funnel.preview.app.daily.dev

feat: redirect to parameter after finishing the funnel

---

packages/shared/src/components/cores/CoreOptionButton.tsx
packages/shared/src/components/icons/Core/index.tsx
packages/shared/src/components/post/PostActions.tsx
packages/shared/src/graphql/njord.ts

- adjust cores fallback
- use base Cores image for fallback on Cores options
- invalidate profile awards summary cache on award
- fix `staleTIme` param typo
> [!CAUTION]
https://misc-cores-adjustments.preview.app.daily.dev

feat: misc cores adjustments

---

packages/shared/src/components/modals/award/ListAwardsModal.tsx
packages/shared/src/components/profile/UserShortInfo.tsx
packages/shared/src/graphql/fragments.ts
packages/shared/src/graphql/njord.ts
packages/shared/src/lib/user.ts

Using transaction value instead of product value, see https://github.com/dailydotdev/daily-api/pull/2813
> [!CAUTION]
https://transaction-value-awards.preview.app.daily.dev

feat: use transaction value when showing awards

---

packages/shared/src/components/post/PostActions.tsx

Invalidates specific award list for currently awarded post/comment. It does not refetch immediately only if user opens modal. 
> [!CAUTION]
https://invalidate-awards-list.preview.app.daily.dev

feat: invalidate award list after awarding

---

packages/shared/src/components/buttons/Button.tsx
packages/shared/src/components/cards/common/list/ActionButtons.tsx
packages/shared/src/contexts/AuthContext.tsx
packages/shared/src/contexts/ProgressiveEnhancementContext.tsx
packages/shared/src/features/common/hooks/useWindowScroll.ts
packages/shared/src/features/onboarding/shared/FunnelStepper.tsx
packages/shared/src/features/onboarding/shared/StepHeadline.tsx
packages/shared/src/features/onboarding/steps/FunnelFact/FunnelFact.spec.tsx
packages/shared/src/features/onboarding/steps/FunnelFact/FunnelFactCentered.tsx
packages/shared/src/features/onboarding/steps/FunnelFact/FunnelFactDefault.tsx
packages/shared/src/features/onboarding/steps/FunnelFact/index.tsx
packages/shared/src/features/onboarding/steps/FunnelLoading.tsx
packages/shared/src/features/onboarding/steps/FunnelPaymentSuccessful.tsx
packages/shared/src/features/onboarding/types/funnel.ts
packages/shared/src/hooks/index.ts
packages/storybook/stories/components/onboarding/FunnelCheckout.stories.tsx
packages/storybook/stories/components/onboarding/FunnelFact.stories.tsx

- Support a new layout for type `fact`.
- Introduce `centered` where the gaps and paddings are adjusted based on the config.
- Since there was one too many changes, I've decided to create a new component instead to make it easier to manage rather than having numerous ternary operators.
Current:
New layout (centered):
> [!CAUTION]
MI-892
https://mi-892.preview.app.daily.dev

feat: centered layout for funnel fact type

---

packages/shared/src/features/onboarding/steps/FunnelCheckout.tsx
packages/shared/src/hooks/usePaddlePayment.ts

Since customers should be able to buy a subscription without being signed in, we need to remove the required login check
> [!CAUTION]
MI-882
https://mi-882.preview.app.daily.dev

feat: remove logged in requirement from funnelCheckout

---

packages/shared/src/features/onboarding/hooks/useFunnelNavigation.ts
packages/shared/src/features/onboarding/shared/FunnelStepper.spec.tsx
packages/shared/src/features/onboarding/shared/FunnelStepper.tsx
packages/shared/src/features/onboarding/steps/FunnelCheckout.tsx
packages/shared/src/features/onboarding/steps/FunnelPaymentSuccessful.tsx
packages/shared/src/features/onboarding/steps/FunnelRegistration.tsx
packages/shared/src/hooks/usePaddlePayment.ts
packages/webapp/pages/helloworld/index.tsx

This is the intermediate (final) branch for the subscription before registration [RFC](https://dailydotdev.atlassian.net/wiki/spaces/HAN/pages/1600127008/RFC-121+-+Subscription+before+registration#Option-2%3A-Create-a-new-table-for-unclaimed-items)
> [!CAUTION]
MI-881
https://mi-881-sub-before-registration.preview.app.daily.dev

feat: subscription before registration in funnel

---

packages/shared/src/components/plus/common.tsx

> [!CAUTION]
https://feat-update-faq-plus.preview.app.daily.dev

feat: update Plus FAQ

---

packages/shared/src/components/cards/common/PostTags.tsx
packages/shared/src/hooks/feed/useFollowPostTags.ts
packages/shared/src/lib/featureManagement.ts

- The experiment lost.
- Reference: https://dailydotdev.slack.com/archives/C02JAUF8HJL/p1742458721436499
> [!CAUTION]
https://chore-cleanup-tags-experiment.preview.app.daily.dev

chore: cleanup tags order experiment

---

packages/webapp/components/Pixels.tsx
packages/webapp/pages/helloworld/index.tsx

Add hotjar to funnels and load it immediately when possible
https://funnels-hotjar.preview.app.daily.dev

feat(funnels): add hotjar support

---

packages/shared/src/components/AnimatedAward.tsx
packages/shared/src/components/comments/CommentActionButtons.tsx
packages/shared/src/components/comments/CommentAwardActions.tsx
packages/shared/src/components/comments/CommentContainer.tsx
packages/shared/src/components/comments/MainComment.spec.tsx
packages/shared/src/components/comments/SubComment.spec.tsx
packages/shared/src/components/utilities/DateFormat.spec.tsx
packages/shared/src/hooks/useViewSize.ts
packages/shared/src/lib/dateFormat.spec.ts
packages/shared/src/lib/dateFormat.ts
packages/webapp/pages/_app.tsx

Various fixes from [figma](https://www.figma.com/board/8W8mR8Zwo4af93d3vzLsav/comments-fix?node-id=0-1&p=f&t=EGEVBfNZGVCVQlNI-0) in regards to comments size/overflow, especially mobile optimizations. See figma and specific commits for changes.
Also added [easter egg](https://dailydotdev.slack.com/archives/C07VA1FJTDK/p1747331432584079)
> [!CAUTION]
https://fix-comments.preview.app.daily.dev

fix: comments

---

packages/shared/src/components/cards/Freeform/FreeformList.tsx
packages/shared/src/components/cards/common/PostCardHeader.tsx
packages/shared/src/components/cards/common/list/hooks.ts
packages/shared/src/components/post/PostEngagements.tsx
packages/shared/src/components/post/PostHeaderActions.tsx
packages/shared/src/components/post/SharePostContent.tsx
packages/shared/src/hooks/feed/useCardCover.tsx
packages/shared/src/lib/featureManagement.ts
packages/shared/src/lib/image.ts
packages/webapp/pages/onboarding.tsx

- post_visit_link: lost: https://github.com/dailydotdev/apps/commit/0013092acc78fe50486b0f59f6b155bc5f114dbd.
- onboarding_android: lost (have been cleaned up already. just the const was the one existing): https://github.com/dailydotdev/apps/commit/69c9efb39a73862aaa972797b849ad075926c76e.
- social_share: won: https://github.com/dailydotdev/apps/commit/eb79e4f9b027719085841f2a59bc83938b0bae45.
- onboarding_visual: won (turn to const config): https://github.com/dailydotdev/apps/commit/3c9fe7f2a8e5a48a458bd913b987a801110af4ee
> [!CAUTION]
https://chore-more-cleanups.preview.app.daily.dev

chore: more experiment cleanups

---

packages/webapp/pages/_app.tsx

> [!CAUTION]
https://app-store-banner-funnel.preview.app.daily.dev

feat: hide app store banner in the funnel

---

packages/shared/src/components/modals/streaks/StreakRecoverModal.spec.tsx
packages/shared/src/components/modals/streaks/StreakRecoverModal.tsx
packages/shared/src/graphql/users.ts
packages/shared/src/hooks/streaks/useStreakRecover.ts
packages/shared/src/lib/log.ts
packages/shared/src/lib/transaction.tsx

API: https://github.com/dailydotdev/daily-api/pull/2831
| Change| any | extra: { origin: streak restore } |
> [!CAUTION]
https://streak-restore-cores.preview.app.daily.dev

feat: streak restore with cores

---

docker-compose.yml

The gitpod API was not spooling up due to some recent changes.
(mainly missing env stuff)
Solves:
https://github.com/dailydotdev/daily/issues/1853
> [!CAUTION]
https://fix-gitpod.preview.app.daily.dev

fix: gitpod

---

packages/shared/src/components/cards/Freeform/FreeformList.tsx

- Dom purify being used directly causes the build to fail.
- I think it is because it depends on window/document to be present, which is not available on build.
- The common function used here checks that.
- The story for "Color" though still is broken. I'll look into that in a separate PR. This is just to make the build pass.
> [!CAUTION]

fix: storybook on build

---

packages/shared/src/hooks/usePaddlePayment.ts

Adding the `data-hj-allow-iframe` attribute to the paddle iframe as described in [this doc](https://help.hotjar.com/hc/en-us/articles/115011624347-Can-I-Track-iframes-Inside-Heatmaps-and-Recordings) to see if it will allow us to record hotjar properly. 
> [!CAUTION]
MI-906
https://mi-906.preview.app.daily.dev

feat: add hotjar attribute to iframe

---

packages/shared/src/features/onboarding/steps/FunnelCheckout.tsx

- Preload the Checkout form so when the user lands, the form is already intact.
Preview:
https://github.com/user-attachments/assets/382bd44c-8125-46ea-b7b7-7b7ea94c6219
> [!CAUTION]
MI-907
https://mi-907.preview.app.daily.dev

refactor: pricing checkout render in the bg

---

packages/shared/src/features/organizations/graphql.ts
packages/shared/src/features/organizations/hooks/useOrganization.ts
packages/shared/src/lib/image.ts
packages/webapp/pages/join/organization.tsx
packages/webapp/pages/settings/organization/[orgId]/billing.tsx
packages/webapp/pages/settings/organization/[orgId]/general.tsx
packages/webapp/pages/settings/organization/[orgId]/members.tsx

Adds missing functionality to the member context menu:
- Remove organization member
- Update organization member role
- Toggle organization member seat
- Some cleanup of hooks
https://github.com/dailydotdev/daily-api/pull/2842
AS-1120
https://as-1120-manage-members.preview.app.daily.dev

feat: update organization members

---

packages/shared/src/features/organizations/graphql.ts
packages/shared/src/features/organizations/hooks/useOrganization.ts
packages/shared/src/lib/image.ts
packages/webapp/pages/join/organization.tsx
packages/webapp/pages/settings/organization/[orgId]/billing.tsx
packages/webapp/pages/settings/organization/[orgId]/general.tsx
packages/webapp/pages/settings/organization/[orgId]/members.tsx

Adds mutation and hooks up the delete button to it, so that it is possible to delete an organization.
https://github.com/dailydotdev/daily-api/pull/2841
AS-1123
https://as-1123-delete-organzation.preview.app.daily.dev

feat: delete organzation

---

packages/webapp/pages/helloworld/index.tsx

Fix theme flicker in the funnel as reported by @idoshamun [here](https://dailydotdev.slack.com/archives/C08J2D9NKPU/p1747828524220019)
Issue seems to have been caused by waiting for `isAuthReady` before setting the correct theme. This became very visible when using light theme because the default theme is dark.
> [!CAUTION]
MI-904
https://mi-904.preview.app.daily.dev

fix: theme flicker in funnel

---

packages/webapp/pages/join/organization.tsx

Missed some paddings
https://fix-org-invite-padding-mobie.preview.app.daily.dev

fix: add some padding on join organization invite screen on mobile

---

packages/shared/src/components/plus/PlusProductToggle.tsx
packages/shared/src/contexts/BuyCoresContext.tsx
packages/shared/src/contexts/payment/BasePaymentProvider.tsx
packages/shared/src/contexts/payment/ChromeExtension.tsx
packages/shared/src/contexts/payment/Paddle.tsx
packages/shared/src/contexts/payment/context.ts
packages/shared/src/hooks/usePaddlePayment.ts
packages/shared/src/lib/log.ts

Replace atom with context data which should be more predicatable, [thread](https://dailydotdev.slack.com/archives/C07V6888KML/p1749123350454189)
> [!CAUTION]
https://fix-payment-type-mixup.preview.app.daily.dev

fix: payment type mixup

---

packages/webapp/pages/plus/payment.tsx

We had a infinite loop because of ref on html vs callback being re-called.
> [!CAUTION]
https://fix-mobile-checkout-renders.preview.app.daily.dev

fix: mobile checkout renders

---

packages/shared/src/hooks/useCoresFeature.ts

> [!CAUTION]
https://enable-cores-iap-for-all.preview.app.daily.dev

feat: enable cores iap for all

---

packages/shared/src/features/onboarding/steps/FunnelPaymentSuccessful.spec.tsx
packages/shared/src/features/onboarding/steps/FunnelPaymentSuccessful.tsx

> [!CAUTION]
MI-916
https://mi-916.preview.app.daily.dev

feat: remove background image in payment successful light mode

---

packages/shared/src/hooks/useCoresFeature.ts

Should solve:
https://dailydotdev.slack.com/archives/C01L0QXQJNB/p1749642117834309
> [!CAUTION]
https://fix-dynamic-eval.preview.app.daily.dev

fix: dynamic load

---

packages/shared/src/components/cards/brief/BriefCard.tsx
packages/shared/src/styles/custom.ts

Really the pain with gradients, at the end opted to use styles/custom because colors are not standard as well.
> [!CAUTION]
https://brief-card.preview.app.daily.dev

feat: brief card

---

packages/shared/src/components/notifications/NotificationsBell.tsx
packages/storybook/mock/boot.ts

Small issues found during testing
> [!CAUTION]
https://chore-hotfix-sb.preview.app.daily.dev

fix: small issues found in testing

---

packages/shared/src/components/widgets/PostToc.tsx

Solves: https://github.com/dailydotdev/daily/issues/1840
Also noticed we don't truncate here on mobile or desktop.
After:
> [!CAUTION]
https://wt-fix-toc.preview.app.daily.dev

fix: TOC rendering

---

packages/shared/src/features/onboarding/components/OnboardingPlusVariationV1.tsx

After fix:
> [!CAUTION]
https://fix-carousel-variation-onboardin.preview.app.daily.dev

fix: center carousel version of pricing

---

packages/shared/src/components/CalendarHeatmap.tsx
packages/shared/src/components/RadialProgress.tsx
packages/shared/src/components/comments/PlaceholderCommentList.tsx
packages/shared/src/components/containers/CarouselIndicator.tsx
packages/shared/src/components/fields/CodeField.tsx
packages/shared/src/components/history/ReadingHistoryPlaceholder.tsx
packages/shared/src/components/profile/SourceListPlaceholder.tsx
packages/shared/src/components/profile/TagListPlaceholder.tsx
packages/shared/src/components/profile/UserShortInfoPlaceholder.tsx
packages/shared/src/hooks/useFeed.ts

Initially just fixed [the error from here](https://dailydotdev.slack.com/archives/C01L0QXQJNB/p1749726022914639), but went overboard and added `Math.max` to everywhere I could see it could possibly received external negative number.
https://fix-negative-squad-member-amount.preview.app.daily.dev

fix: ensure created array always receives a non-negative number

---

packages/shared/package.json
packages/shared/src/components/dropdown/DropdownMenu.tsx
packages/shared/src/components/dropdown/style.css
packages/storybook/stories/components/DropdownMenu.stories.tsx
pnpm-lock.yaml

Radix based dropdown menu.
Want to implement it one at a time as it works very different from our current one.
Probably we'll need some wrapping components for different ones.
> [!CAUTION]
https://feat-dropdown-menu.preview.app.daily.dev

feat: added Radix based dropdown menu

---

packages/shared/src/components/cards/common/PostCardHeader.tsx
packages/shared/src/components/cards/common/SquadPostCardHeader.tsx
packages/shared/src/components/cards/common/list/PostCardHeader.tsx
packages/shared/src/components/cards/entity/EntityCard.tsx
packages/shared/src/components/cards/entity/SourceEntityCard.tsx
packages/shared/src/components/cards/entity/UserEntityCard.tsx
packages/shared/src/graphql/fragments.ts

Added the hovercard to another component and tweaked the colors of the menu in the source entity card
> [!CAUTION]
MI-922
https://mi-922.preview.app.daily.dev

feat: add HoverCard to SquadPostCardHeader

---

packages/shared/src/components/bookmark/BookmarkFolderContextMenu.tsx
packages/shared/src/components/dropdown/DropdownMenu.tsx

Move bookmark context menu to the new one.
(Needs the other PR for some styling upgrades we did)
> [!CAUTION]
https://fix-bookmark-options-menu.preview.app.daily.dev

fix: upgrade bookmark option menu

---

packages/shared/src/components/Feed.spec.tsx

Forgot to update test on feedName change
> [!CAUTION]
https://fix-failing-tests.preview.app.daily.dev

fix: failing test cases

---

packages/shared/src/components/modals/ArticlePostModal.tsx
packages/shared/src/components/modals/BasePostModal.tsx
packages/shared/src/components/modals/CollectionPostModal.tsx
packages/shared/src/components/modals/SharePostModal.tsx
packages/shared/src/components/modals/squads/PostModerationModal.tsx
packages/shared/src/components/post/BasePostContent.tsx
packages/shared/src/components/post/PostContent.tsx
packages/shared/src/components/post/PostHeaderActions.tsx
packages/shared/src/components/post/PostMenuOptions.tsx
packages/shared/src/components/post/PostNavigation.tsx
packages/shared/src/components/post/PostSourceInfo.tsx
packages/shared/src/components/post/PostWidgets.tsx
packages/shared/src/components/post/SharePostContent.tsx
packages/shared/src/components/post/ShareYouTubeContent.tsx
packages/shared/src/components/post/SquadPostContent.tsx
packages/shared/src/components/post/SquadPostWidgets.tsx
packages/shared/src/components/post/collection/CollectionPostContent.tsx
packages/shared/src/components/post/collection/CollectionPostHeaderActions.tsx
packages/shared/src/components/post/collection/CollectionPostWidgets.tsx
packages/shared/src/components/post/collection/CollectionSubscribeButton.tsx
packages/shared/src/components/post/common.tsx
packages/webapp/pages/posts/[id]/index.tsx

Some minor forgotten changes in the follow update.
* The "fixed" nav is supposed to be visible on the modals at all time now, but with less buttons
* Moved the "post actions" buttons from the widgets to line up with the source
> [!CAUTION]
MI-923
[DESIGN](https://www.figma.com/design/nmfWPS7x3kzLUvYMkBx2kW/daily.dev---Dev-Mode?node-id=23268-26862&m=dev)
https://mi-923.preview.app.daily.dev

feat: post navigation updates

---

packages/shared/src/hooks/usePostModalNavigation.ts
packages/shared/src/hooks/useRouterMemory.ts

- add in memory router that mimics partial of next/router for usage in post modal
- we just switch the hook based on feature detection of extension
- browser back buttons do not work in extension, but this is how it was with previous implementation as well since extension does not have concept of pages
> [!CAUTION]
https://fix-modal-router-extension.preview.app.daily.dev

fix: use in memory router for extension post modal

---

packages/shared/src/graphql/fragments.ts

Source cards in the post widgets [not counting upvotes](https://dailydotdev.slack.com/archives/C01L0QXQJNB/p1750932907977249) cause missing property in fragment
> [!CAUTION]
MI-925
https://mi-925.preview.app.daily.dev

feat: add totalUpvotes on source in post

---

Tiltfile

https://add-skadi.preview.app.daily.dev

chore: add commented out skadi include in tiltfile

---

packages/shared/src/components/cards/entity/EntityCard.tsx
packages/shared/src/components/feeds/FeedSettings/sections/FeedSettingsGeneralSection.tsx
packages/shared/src/components/modals/squads/PostModerationModal.tsx
packages/shared/src/components/post/PostSourceInfo.tsx
packages/shared/src/components/utilities/Link.tsx
packages/webapp/hooks/useSharedByToast.tsx

Removes the type fixes as they shouldn't actually been there, and added missing `a` element
https://actually-fix-eslint-prevent-next.preview.app.daily.dev

fix: add missing `a` and apply the props to those instead

---

packages/shared/src/components/cards/collection/CollectionGrid.spec.tsx

This test keeps failing and is tagged as flaky because its looking for the wrong classes
> [!CAUTION]
https://update-flaky-test.preview.app.daily.dev

fix: add correct classes to test

---

packages/shared/src/components/post/write/ShareLink.tsx
packages/shared/src/components/post/write/SquadsDropdown.tsx
packages/shared/src/components/profile/source/SourceShortInfo.tsx
packages/shared/src/graphql/squads.ts
packages/webapp/pages/squads/create.tsx

AS-1158
https://as-1158-post-to-user-source.preview.app.daily.dev

feat: add option to post to user source

---

packages/extension/src/newtab/MainFeedPage.tsx
packages/shared/src/components/PostsSearch.tsx
packages/shared/src/contexts/search/SearchContext.tsx

Ensure context wrapped correct way.
(moving the one function down a bit)
> [!CAUTION]
https://fix-context-wrap.preview.app.daily.dev

fix: context wrapping

---

packages/shared/src/components/post/PostHeaderActions.tsx
packages/shared/src/features/boost/CampaignListItem.tsx
packages/shared/src/features/boost/CampaignListView.tsx
packages/shared/src/graphql/post/boost.ts
packages/shared/src/lib/ads.ts

- When a post is completed, it is called `INACTIVE` in our DB rather than `COMPLETED`, but we want to show the latter for better understanding.
- Fixed progress bar for when the campaign is not `active` anymore, which means, it is either completed or cancelled.
- Also fixed the endpoint to enable post boost
> [!CAUTION]
MI-888
https://mi-888-card-modal.preview.app.daily.dev

fix: displayed state and dates management

---

packages/shared/src/components/FeedItemComponent.tsx
packages/shared/src/components/ProfileMenu/sections/AccountSection.tsx
packages/shared/src/components/cards/common/PostMetadata.tsx
packages/shared/src/features/boost/CampaignListView.tsx
packages/shared/src/graphql/post/boost.ts

- Render AdPixel on FeedItemComponent when type is Ad and is a Post Boost.
- Also removed the date create when boosted on Feed. Reference: https://dailydotdev.slack.com/archives/C083ALBSFLJ/p1752072697805029?thread_ts=1752070988.486969&cid=C083ALBSFLJ
> [!CAUTION]
MI-888
https://mi-888-ad-pixel.preview.app.daily.dev

feat: support rendering of ad pixel for analytics

---

packages/shared/src/components/cards/entity/SquadEntityCard.tsx
packages/shared/src/components/squads/SquadHeaderBar.tsx
packages/shared/src/components/squads/SquadHeaderMenu.tsx

Note:
We already have this issue currently. but won't fix in scope of this PR.
Also I want to abstract the DropdownMenuItem loop to it's own component, but we'll do it in the next PR.
> [!CAUTION]
https://chore-squad-header-menu.preview.app.daily.dev

chore: squad header menu change

---

packages/shared/src/components/dropdown/DropdownMenu.tsx

Missed the last merge conflict change 😅
> [!CAUTION]
https://hotfix-link-styling.preview.app.daily.dev

fix: missed link classes

---

packages/shared/src/components/integrations/UserIntegrationItem.tsx

Move to new dropdown
> [!CAUTION]
https://chore-user-integration.preview.app.daily.dev

chore: user integration

---

packages/shared/src/components/modals/post/boost/BoostPostModal.tsx
packages/shared/src/graphql/post/boost.ts
packages/shared/src/hooks/post/usePostBoostMutations.ts

- Update the post boost estimate query. We just need the post's id now.
> [!CAUTION]
MI-888
https://mi-888-fix-estimate.preview.app.daily.dev

fix: estimated reach query

---

packages/shared/src/components/brief/BriefListItem.tsx
packages/shared/src/components/cards/brief/BriefCard/BriefCardReady.tsx
packages/shared/src/components/post/brief/BriefPostContent.tsx

- double click event on brief list items
- click event not firing on brief ready
- complete action when brief is viewed as well
> [!CAUTION]
https://brief-tracking-fixes.preview.app.daily.dev

fix: brief tracking

---

packages/shared/src/components/post/PostSourceInfo.tsx

> [!CAUTION]
https://hotfix-current-member.preview.app.daily.dev

fix: current member

---

packages/shared/src/components/Feed.tsx
packages/shared/src/components/cards/brief/BriefCard/BriefCard.tsx
packages/shared/src/components/cards/brief/BriefCard/BriefCardDefault.tsx
packages/shared/src/components/cards/brief/BriefCard/BriefCardFeed.tsx
packages/shared/src/components/cards/brief/BriefCard/BriefCardLoading.tsx
packages/shared/src/components/cards/brief/BriefCard/BriefCardReady.tsx
packages/webapp/pages/briefing/index.tsx

[Requested](https://dailydotdev.slack.com/archives/C01L0QXQJNB/p1752559204118999) by Nimrod
> [!CAUTION]
https://brief-styling-adjustment.preview.app.daily.dev

feat: brief styling adjustment

---

packages/shared/src/components/ProfileMenu/ProfileSectionItem.tsx
packages/shared/src/components/modals/post/boost/AdsDashboardModal.tsx
packages/shared/src/components/profile/ProfileSettingsMenu.tsx

- Add the missing "Ads dashboard" item on mobile.
- Also changed from Primary to Secondary color for items. Reference: https://dailydotdev.slack.com/archives/C01473UNK9C/p1752654131811049
> [!CAUTION]
https://fix-mobile-menu.preview.app.daily.dev

fix: missing ads dashboard item on mobile

---

packages/extension/src/companion/CompanionDiscussion.tsx
packages/shared/src/components/post/NewComment.tsx
packages/shared/src/components/post/PostEngagements.tsx
packages/webapp/components/footer/FooterWrapper.tsx

Lazy loading does not work in companion because JS chunks are loaded on origin of the website that is opened and not our own. Replace with sync import inside companion.
> [!CAUTION]

fix: comment modal in companion

---

packages/shared/src/components/squads/SquadPageHeader.tsx

Before 🙈 
After 😎 
> [!CAUTION]
MI-946
https://mi-946.preview.app.daily.dev

fix: sizing on description and post bar in list mode

---

packages/shared/src/components/feeds/FeedContainer.tsx
packages/shared/src/components/profile/ProfileWidgets.tsx
packages/shared/src/features/profile/components/FeelingLazy.tsx
packages/shared/src/features/profile/components/ProfileUploadBanner.tsx
packages/shared/src/features/profile/hooks/useUploadCv.ts
packages/shared/src/lib/image.ts
packages/webapp/components/layouts/ProfileLayout/index.tsx
packages/webapp/components/layouts/SettingsLayout/Profile/index.tsx

> [!CAUTION]
https://fix-cover.preview.app.daily.dev

fix: linkedin instruction cover

---

packages/shared/src/features/profile/components/FeelingLazy.tsx

- The space wasn't really working. Used margin instead.
> [!CAUTION]
https://fix-minor-upload.preview.app.daily.dev

fix: spacing in between the texts

---

packages/shared/src/components/feeds/FeedContainer.tsx
packages/shared/src/components/profile/ProfileWidgets.tsx
packages/shared/src/features/profile/components/ProfileUploadBanner.tsx
packages/shared/src/features/profile/hooks/useUploadCv.ts
packages/shared/src/lib/log.ts

Add event tracking for CV upload
> [!CAUTION]
https://feat-cv-upload-event-tracking.preview.app.daily.dev

Feat cv upload event tracking

---

packages/shared/src/components/containers/InfiniteScrolling.tsx
packages/shared/src/components/modals/post/boost/AdsDashboardModal.tsx
packages/shared/src/features/boost/BoostHistoryLoading.tsx
packages/shared/src/features/boost/CampaignList.tsx
packages/shared/src/hooks/post/usePostBoost.ts

- Loading placeholder.
- Applied infinite scrolling.
Preview of loading:
> [!CAUTION]
https://fix-infinite-scrolling.preview.app.daily.dev

fix: ads dashboard infinite scrolling

---

packages/shared/src/features/profile/hooks/useUploadCv.ts
packages/shared/src/hooks/post/usePostBoostMutations.ts

- As per product team, we won't have to support `doc` files now. Just `docx`.
> [!CAUTION]
https://fix-file-formats.preview.app.daily.dev

chore: remove doc file support

---

packages/storybook/.storybook/main.ts
packages/storybook/mock/hooks.ts
packages/storybook/mock/hooks/useConditionalFeature.ts

- remove global hooks mock
- add single mock for useConditionalFeature
- this now allows avoiding index usage which was breaking storybook due to mocks
> [!CAUTION]
https://fix-storybook-mocks.preview.app.daily.dev

fix: storybook mock

---

packages/shared/src/components/profile/ProfileWidgets.tsx

- When the banner is displayed, we should not show the widget. It would just send a duplicate impression event.
> [!CAUTION]
https://fix-impression.preview.app.daily.dev

fix: displaying the widget unnecessarily

---

packages/shared/src/components/fields/DragDrop.tsx
packages/shared/src/components/profile/ProfileWidgets.tsx
packages/shared/src/features/profile/components/ProfileUploadBanner.tsx

- On mobile, we should display some text on the upload. Tested all the variants and screensizes as shown below:
The main changes are these two:
To ensure everything still worked as intended:
> [!CAUTION]
https://fix-upload-profile.preview.app.daily.dev

fix: upload profile widget

---

packages/shared/src/components/feeds/FeedContainer.tsx

> [!CAUTION]
https://fix-banner.preview.app.daily.dev

fix: banner on specific pages only

---

packages/shared/src/components/squads/SquadPageHeader.tsx

Missed one center element.
> [!CAUTION]
https://fix-missed-center.preview.app.daily.dev

fix: missed one center point

---

packages/webapp/pages/briefing/index.tsx
packages/webapp/pages/posts/[id]/index.tsx

Missed the actual page change on the hardpages. (padding/margin was done)
> [!CAUTION]
https://fix-actual-page-width.preview.app.daily.dev

fix: forgot the actual pages width

---

packages/webapp/components/footer/FooterWrapper.tsx

Solves:
https://dailydotdev.slack.com/archives/C01L0QXQJNB/p1753443323217219
No longer showing the plus button on posts pages
Also fixed small issue in rendering, it didn't show footer on settings and the evaluation seemed off.
> [!CAUTION]
https://fix-exclude-plus-button.preview.app.daily.dev

fix: exclude plus button on post pages

---

packages/shared/src/components/post/common/PostClickbaitShield.tsx

Think we introduced the clickbait prompt box later which messed up some styling.
New:
> [!CAUTION]
https://fix-clickbait-styling.preview.app.daily.dev

fix: minor issues with clickbait styling

---

packages/shared/src/features/boost/BoostNewPostStrip.tsx
packages/shared/src/hooks/utils/useThemedAsset.ts
packages/shared/src/lib/image.ts

> [!CAUTION]
https://fix-light-mode.preview.app.daily.dev

fix: light mode image on boost strip

---

.github/workflows/e2e-tests.yml

Passes username and password from secret to step environment
https://fix-playwrigth-ci-env.preview.app.daily.dev

fix: pass secret to env

---

packages/playwright/playwright.config.ts
packages/playwright/tests/login.spec.ts

We have 2 cookie bars 😅
> [!CAUTION]
https://fix-cookie-test.preview.app.daily.dev

Fix cookie test

---

packages/shared/src/graphql/post/boost.ts
packages/shared/src/hooks/post/usePostBoostEstimation.ts

- When fetching for the reach, we should always send the budget whether there is no yggdrasil id or tags available.
- Also, if the post is 5 minutes old, yggdrasil for sure has run already, and if the tags and ID are still not available (due to bug), we will just send the estimation request, as it won't make sense to keep polling.
> [!CAUTION]
https://fix-polling.preview.app.daily.dev

refactor: send budget regardless of tags availability

---

packages/webapp/components/layouts/SettingsLayout/Profile/index.tsx

Solves: https://github.com/dailydotdev/daily/issues/1928
> [!CAUTION]
https://fix-experience-level-dropdown.preview.app.daily.dev

fix: was not rendering due to absolute positions

---

packages/shared/src/components/cards/common/PostTags.tsx
packages/shared/src/components/typography/Typography.tsx
packages/shared/src/graphql/actions.ts
packages/webapp/pages/jobs/[id]/index.tsx

https://www.figma.com/design/nmfWPS7x3kzLUvYMkBx2kW/daily.dev---Dev-Mode?node-id=34336-12313&m=dev
AS-1181
https://as-1181-job-listing.preview.app.daily.dev

feat: add intermediate branch for jobs sections

---

packages/shared/src/components/notifications/EmailNotificationsTab.tsx
packages/shared/src/components/notifications/InAppNotificationsTab.tsx
packages/shared/src/components/notifications/NotificationSwitch.tsx
packages/shared/src/components/notifications/PersonalizedDigest.tsx
packages/shared/src/components/notifications/PresidentialBriefingNotification.tsx
packages/shared/src/components/notifications/utils.ts
packages/shared/src/components/post/brief/BriefPostContent.tsx
packages/shared/src/graphql/users.ts
packages/shared/src/hooks/notifications/useNotificationSettings.ts
packages/shared/src/hooks/usePersonalizedDigest.ts
packages/webapp/__tests__/AccountNotificationsPage.tsx

Syncing up digest/brief with notification flags properly, and moving away from the flags in the `userPersonalizedDigest` table.
[Backend PR](https://github.com/dailydotdev/daily-api/pull/2992)
> [!CAUTION]
MI-980
https://mi-980.preview.app.daily.dev

feat: sync brief with notification flags

---

packages/shared/src/components/MainLayout.tsx
packages/webapp/components/layouts/NoSidebarLayout.tsx
packages/webapp/pages/jobs/[id]/notify.tsx

Adds notify page (should not show back on mobile)
> [!CAUTION]
https://feat-jobs-notify.preview.app.daily.dev

feat: add notify page

---

packages/shared/src/components/ProgressCircle.tsx
packages/shared/src/components/fields/BaseFieldContainer.tsx
packages/shared/src/components/fields/Textarea.tsx
packages/shared/src/components/fields/common.tsx
packages/webapp/pages/jobs/[id]/questions.tsx

Add the questions step
> [!CAUTION]
https://feat-questions.preview.app.daily.dev

feat: questions step

---

packages/webapp/pages/jobs/[id]/decline.tsx
packages/webapp/pages/jobs/[id]/index.tsx
packages/webapp/pages/jobs/[id]/notify.tsx
packages/webapp/pages/jobs/[id]/preference.tsx
packages/webapp/pages/jobs/welcome.tsx

Introduces preference screen (decided to inline for now until we know more on placement)
Also added links so we can have click-through demo :) 
> [!CAUTION]
https://fix-link-jobs.preview.app.daily.dev

fix: link all job pages together

---

packages/shared/src/components/dropdown/DropdownMenu.tsx

Fix lint issue
> [!CAUTION]
https://chore-fix-lint.preview.app.daily.dev

chore: fix lint

---

packages/shared/src/components/post/analytics/PostShortInfo.tsx

> [!CAUTION]
https://share-post-analytics-info.preview.app.daily.dev

feat: adjust shared post analytics info and link

---

packages/shared/src/components/modals/SquadNotificationSettingsModal.tsx

for the squad notifications modal. Previous fix removed overflow completely, but should've only done so for horizontal
> [!CAUTION]
https://make-squad-notifications-modal-s.preview.app.daily.dev

fix: make only the horizontal scroll hidden

---

packages/shared/src/graphql/posts.ts
packages/shared/src/hooks/squads/usePostToSquad.ts

Related to: https://github.com/dailydotdev/daily-api/pull/3009
Closes https://github.com/dailydotdev/daily/issues/1537
https://handle-preview-redirects.preview.app.daily.dev

fix: handle properly redirect links for shared post

---

packages/shared/src/components/analytics/ImpressionsChart.tsx
packages/shared/src/components/post/PostUpvotesCommentsCount.tsx
packages/shared/src/components/post/analytics/PostShortInfo.tsx
packages/shared/src/features/boost/BoostPostButton.tsx
packages/shared/src/features/posts/PostOptionButton.tsx
packages/shared/src/lib/user.ts
packages/webapp/pages/posts/[id]/analytics/index.tsx

Adjust entry points for launch
> [!CAUTION]
https://post-analytics-entrypoints.preview.app.daily.dev

feat: entry points

---

packages/webapp/pages/posts/[id]/analytics/index.tsx

> [!CAUTION]
https://fix-private-post-analytics-page.preview.app.daily.dev

fix: private post crashing analytics page on refresh

---

packages/shared/src/components/fields/ImageInput.tsx
packages/shared/src/components/squads/Details.tsx
packages/shared/src/graphql/fragments.ts
packages/shared/src/graphql/squads.ts
packages/shared/src/hooks/utils/useFileInput.ts

- Allow user to upload header image that will be utilized for the Squads directory.
> [!CAUTION]
MI-984
https://mi-984.preview.app.daily.dev

feat: allow user to upload header image

---

packages/shared/src/components/cards/squad/SquadsDirectoryFeed.tsx
packages/shared/src/components/modals/utils/ActionSuccessModal.tsx
packages/shared/src/components/post/analytics/BoostingLabel.tsx
packages/shared/src/components/post/analytics/PostShortInfo.tsx
packages/shared/src/components/squads/SquadHeaderBar.tsx
packages/shared/src/features/boost/BoostSourceButton.tsx
packages/shared/src/features/boost/CampaignListItemPost.tsx
packages/shared/src/graphql/campaigns.ts
packages/webapp/pages/posts/[id]/analytics/index.tsx

- Fixes boosted label unnecessarily on every first item on every row.
- Fixes layout shift.
- Fixes ads dashboard image on shared posts.
- Fixes the Squads requirement UI.
- Fixes the Boosting label on Analytics page.
- Boost Squad button should not be shown to private Squads.
Note: test is failing due to not checking for Cores while in testing phase.
> [!CAUTION]
https://fix-squad-directory.preview.app.daily.dev

fix: squad boost feedback

---

packages/shared/src/components/cards/ad/squad/SquadAdGrid.tsx
packages/shared/src/components/cards/ad/squad/SquadAdList.tsx
packages/shared/src/components/cards/squad/SquadGrid.tsx
packages/shared/src/components/cards/squad/SquadsDirectoryFeed.tsx
packages/shared/src/components/cards/squad/common/types.ts
packages/shared/src/features/boost/BoostButton.tsx
packages/shared/src/features/boost/BoostSourceButton.tsx
packages/shared/src/features/boost/BoostSquadModal.tsx
packages/shared/src/features/boost/CampaignListItemPost.tsx
packages/shared/src/styles/custom.ts

Should fix the items below:
- The top text on "Boost your squad modal" should not change - but we need to add the link t lead to docs.
- squad should upload profile pic before being able to boost - fallback not accepted
- color of boost button should not be with gradient - we should align it with the one in analytics page
- border of boosted squad should be grey in featured section
- boosted label on squad card (featured section and feed) should be (blue) the same color as in post analytics
> [!CAUTION]
https://fix-squad-boost-sync.preview.app.daily.dev

fix: squad boost sync

---

packages/shared/src/components/FeedItemComponent.tsx
packages/shared/src/components/cards/ad/squad/SquadAdGrid.tsx
packages/shared/src/components/cards/ad/squad/SquadAdList.tsx
packages/shared/src/components/cards/ad/squad/common.ts
packages/shared/src/components/cards/squad/SquadGrid.tsx
packages/shared/src/components/cards/squad/SquadList.tsx
packages/shared/src/components/cards/squad/SquadsDirectoryFeed.tsx
packages/shared/src/components/cards/squad/common/types.ts
packages/shared/src/components/cards/squad/common/useSquadsDirectoryLogging.ts

- Two events are being registered for this PR. Impression and Click.
- Both for Squads Directory and regular Feed. As for the clicking of joining the Squad button, it should be there already along with completed event (tested and confirmed).
> [!CAUTION]
https://squad-boost-analytics.preview.app.daily.dev

feat: squads feed boost analytics

---

packages/shared/src/components/cards/ad/common/AdPixel.tsx

Fire only when in view, see [thread](https://dailydotdev.slack.com/archives/C08093PANBA/p1756996403510169)
> [!CAUTION]
https://fix-pixel.preview.app.daily.dev

fix: pixel

---

packages/shared/src/components/cards/common/PostTags.tsx

We currently apply w-full it takes parent width.
But sometimes we have a clickbait shield there, sometimes not.
In case it does -> it shows width without this shield. => overflowing tags.
By adding flex-1 we shrink it/expand it to max regardless of what's left from it.
> [!CAUTION]
https://fix-tags.preview.app.daily.dev

fix: calculation of tags

---

packages/shared/src/components/cards/Freeform/FreeformGrid.tsx
packages/shared/src/components/cards/share/ShareGrid.tsx

We decided to uniform the card spacing across types for now.
Everything else uses mx-4 now, so applying mx-4 to all.
> [!CAUTION]
https://fix-uniform-spacing.preview.app.daily.dev

fix: uniform missed card spacing

---

packages/shared/src/components/notifications/NotificationDescriptionIcon.tsx
packages/shared/src/components/notifications/NotificationIcon.tsx
packages/shared/src/components/notifications/NotificationItem.tsx
packages/shared/src/components/notifications/utils.ts

Adds new opportunity type.
Needed to add descriptionIcon wrapper for it.
And style option for icon due to gradient.
> [!CAUTION]
https://feat-opportunity-notification.preview.app.daily.dev

feat: opportunity notification

---

packages/shared/src/features/opportunity/components/NoOpportunity.tsx
packages/webapp/pages/jobs/[id]/index.tsx

Empty screen when opportunity is not found
AS-1186
https://as-1186-empty-screen.preview.app.daily.dev
https://as-1186-empty-screen.preview.app.daily.dev/jobs/a
https://as-1186-empty-screen.preview.app.daily.dev/jobs/89f3daff-d6bb-4652-8f9c-b9f7254c9af1

feat: empty screen

---

packages/shared/src/components/opportunity/PreferenceOptionsForm.tsx
packages/shared/src/features/opportunity/graphql.ts
packages/shared/src/features/opportunity/queries.ts
packages/shared/src/features/opportunity/types.ts
packages/shared/src/lib/query.ts
packages/shared/src/lib/utils.ts
packages/webapp/pages/opportunity/[id]/decline.tsx
packages/webapp/pages/opportunity/[id]/notify.tsx
packages/webapp/pages/opportunity/[id]/passive-done.tsx
packages/webapp/pages/opportunity/[id]/preference-done.tsx
packages/webapp/pages/opportunity/[id]/preference.tsx
packages/webapp/pages/opportunity/[id]/questions.tsx
packages/webapp/pages/opportunity/welcome.tsx
packages/webapp/pages/settings/job-preferences.tsx

AS-1203
https://as-1203-fetch-opp-pref.preview.app.daily.dev

feat: fetch user candidate preferences

---

packages/shared/src/components/opportunity/PreferenceOptionsForm.tsx
packages/shared/src/features/opportunity/graphql.ts
packages/shared/src/features/opportunity/types.ts

Toggle custom keywords on job preference page
AS-1210
https://as-1210-toggle-keywords.preview.app.daily.dev

feat: toggle custom keywords

---

packages/extension/src/companion/App.tsx

- remaining thing from [chore: cleanup show_squad_unread_posts (](https://github.com/dailydotdev/apps/commit/ba487ec38065726dcf9fc00fce8eb1b796355680)
> [!CAUTION]

fix: remove updateSquads from app extension

---

packages/shared/src/components/feeds/FeedSettings/sections/FeedSettingsContentPreferencesSection.tsx
packages/shared/src/components/filters/helpers.ts
packages/shared/src/components/onboarding/ContentTypes/ContentTypes.tsx
packages/shared/src/components/onboarding/ContentTypes/helpers.ts
packages/shared/src/features/onboarding/steps/FunnelInstallPwa.tsx

- Rather than having another specific type, we now filter the advanced settings based on an array element we can just update whenever we have a new type. If we want to take this further, we can have this configurable through the DB.
Previews:
> [!CAUTION]
MI-1015
https://mi-1015.preview.app.daily.dev

refactor: content preference to support polls

---

packages/webapp/pages/opportunity/[id]/decline.tsx

Properly set the candidate status from the decline opportunity page
https://fix-set-preference-decline.preview.app.daily.dev

fix: properly set candidate status on decline page

---

packages/shared/src/components/buttons/UploadButton.tsx
packages/shared/src/components/fields/DragDrop.tsx
packages/shared/src/features/fileUpload/hooks/useFileValidation.ts
packages/shared/src/features/opportunity/components/ClearResumeButton.tsx
packages/shared/src/features/opportunity/components/UploadCVButton.tsx
packages/webapp/pages/settings/job-preferences.tsx

- Adds a new UploadButton component, that rendes a button and a hidden upload input field.
- Upload CV from job preference page
AS-1214
https://as-1214-upload-cv.preview.app.daily.dev

feat: upload CV from job preferences page

---

packages/shared/src/components/Pill.tsx
packages/shared/src/components/post/write/CreatePostButton.tsx
packages/shared/src/components/tabs/TabContainer.tsx
packages/shared/src/components/tabs/TabList.tsx
packages/shared/src/components/tooltip/Tooltip.tsx
packages/shared/src/graphql/actions.ts
packages/webapp/__tests__/PostPage.tsx
packages/webapp/pages/squads/create.tsx

- Requirement is, we should not show the tooltip again, whether the user interacted with it or not.
> [!CAUTION]
MI-1013
https://mi-1013.preview.app.daily.dev

feat: new post type tooltip

---

packages/shared/src/components/opportunity/PreferenceOptionsForm.tsx
packages/shared/src/features/opportunity/components/CandidatePreferenceButton.tsx
packages/shared/src/features/opportunity/components/JobOpportunityButton.tsx
packages/shared/src/features/opportunity/components/NoOpportunity.tsx
packages/shared/src/features/opportunity/components/ResponseButtons.tsx
packages/shared/src/features/opportunity/mutations.ts
packages/shared/src/lib/log.ts
packages/webapp/pages/opportunity/[id]/decline.tsx
packages/webapp/pages/opportunity/[id]/done.tsx
packages/webapp/pages/opportunity/[id]/index.tsx
packages/webapp/pages/opportunity/[id]/notify.tsx
packages/webapp/pages/opportunity/[id]/passive-done.tsx
packages/webapp/pages/opportunity/[id]/preference.tsx
packages/webapp/pages/opportunity/[id]/questions.tsx
packages/webapp/pages/opportunity/welcome.tsx
packages/webapp/pages/settings/job-preferences.tsx

Adds analytics logging
AS-1211
https://as-1211-analytics.preview.app.daily.dev

feat: add analytics logging

---

packages/shared/src/components/filters/useFeedContentTypeAction.tsx
packages/shared/src/features/posts/PostOptionButton.tsx
packages/shared/src/hooks/feed/useAdvancedSettings.ts

- Support Poll type to be blocked/unblocked as content type.
- Refactored to dynamically support whichever type that must be toggleable.
> [!CAUTION]
MI-1015
https://mi-1015-context.preview.app.daily.dev

refactor: post options menu to support content types blocking

---

packages/shared/src/features/opportunity/components/ClearEmploymentAgreementButton.tsx
packages/shared/src/features/opportunity/components/UploadCVButton.tsx
packages/shared/src/features/opportunity/components/UploadEmploymentAgreementButton.tsx
packages/shared/src/features/opportunity/graphql.ts
packages/shared/src/features/opportunity/mutations.ts
packages/shared/src/features/opportunity/types.ts
packages/webapp/pages/settings/job-preferences.tsx

Implements the uploading and deletion of the employment agreement.
https://github.com/dailydotdev/daily-api/pull/3132
AS-1217
https://as-1217-add-agreement-upload.preview.app.daily.dev

feat: upload employment agreement

---

packages/shared/src/features/opportunity/components/CVExists.tsx
packages/shared/src/features/opportunity/components/CVOverlay.tsx
packages/shared/src/features/opportunity/components/UploadCVButton.tsx
packages/webapp/pages/opportunity/welcome.tsx

show different box when uploaded CV exists on welcome page
https://fix-show-different-when-cv-exist.preview.app.daily.dev

feat: show different box when uploaded CV exists on welcome page

---

packages/shared/src/features/opportunity/components/CVOverlay.tsx
packages/shared/src/features/profile/components/FeelingLazy.tsx
packages/webapp/pages/opportunity/[id]/index.tsx

- Flash of no opportunity when loading
- Hide footer bar when no match
https://opportunity-fixes.preview.app.daily.dev

fix: opportunities fixes

---

packages/shared/src/components/modals/common/ModalClose.tsx
packages/shared/src/components/modals/utils/ActionSuccessModal.tsx
packages/shared/src/features/boost/BoostPostModal.tsx
packages/shared/src/features/boost/BoostSquadModal.tsx
packages/shared/src/lib/image.ts

Requested by design product.
> [!CAUTION]
https://boosting-copy-changes.preview.app.daily.dev

feat: boosting copy changes

---

packages/shared/src/components/modals/squads/PostModerationModal.tsx
packages/shared/src/components/squads/moderation/SquadModerationItem.tsx
packages/shared/src/components/squads/moderation/SquadModerationItemContextMenu.tsx
packages/shared/src/features/posts/PostOptionButton.tsx

> [!CAUTION]
MI-1044
https://mi-1044.preview.app.daily.dev

fix: remove edit button from polls

---

packages/webapp/pages/opportunity/[id]/index.tsx

Use correct var for recruiter info
https://fix-opp-recruiters.preview.app.daily.dev

fix: recruiters info on opportunity page

---

packages/shared/src/components/post/PostUpvotesCommentsCount.tsx

[REF](https://dailydotdev.slack.com/archives/C01L0QXQJNB/p1758715615627689?thread_ts=1758714583.624089&cid=C01L0QXQJNB)
> [!CAUTION]
MI-1045
https://mi-1045.preview.app.daily.dev

feat: remove hasStats check

---

packages/shared/src/components/cards/poll/PollOptions.tsx

fix: click on card to open the post page/modal when user has voted or…
> [!CAUTION]
MI-1050
MI-1050
https://mi-1050-poll-card-click.preview.app.daily.dev

fix: click on card to open the post page/modal when user has voted 

---

packages/shared/src/components/cards/poll/PollList.tsx

When you copy paste boilerplate and don't look quite close enough 🥴 
> [!CAUTION]
MI-1055
https://mi-1055.preview.app.daily.dev

fix: missing metadata on user source

---

packages/shared/src/components/cards/poll/PollGrid.tsx
packages/shared/src/components/cards/poll/PollList.tsx

- counting poll as viewed when user casts vote. - decision here https://dailydotdev.slack.com/archives/C07GYGWLLKS/p1758718682565169?thread_ts=1758717699.015469&cid=C07GYGWLLKS
> [!CAUTION]
MI-1051
MI-1051
https://mi-1051-poll-views.preview.app.daily.dev

feat: set poll as viewed when voting

---

packages/shared/src/components/opportunity/OpportunityEditContext.tsx
packages/shared/src/components/opportunity/OpportunityEditModal/OpportunityEditContentModal.tsx
packages/shared/src/components/opportunity/OpportunitySteps.tsx
packages/shared/src/lib/labels.ts
packages/shared/src/lib/schema/opportunity.ts
packages/webapp/pages/opportunity/[id]/approved.tsx
packages/webapp/pages/opportunity/[id]/index.tsx
packages/webapp/pages/opportunity/[id]/questions-setup.tsx

Completed flow connecting the pages. Some styling is still off, will take to fix with real data next week.
> [!CAUTION]
https://job-edit-flow.preview.app.daily.dev

feat: job edit flow

---

packages/shared/src/components/opportunity/OpportunityEditModal/OpportunityEditContentModal.tsx
packages/shared/src/components/opportunity/OpportunityEditModal/OpportunityEditInfoModal.tsx
packages/shared/src/components/opportunity/OpportunityEditModal/OpportunityEditQuestionModal.tsx
packages/shared/src/components/opportunity/OpportunitySteps/OpportunityStepsInfo.tsx
packages/shared/src/features/opportunity/graphql.ts
packages/shared/src/features/opportunity/mutations.ts

From comment https://github.com/dailydotdev/apps/pull/4947#discussion_r2393858268
> [!CAUTION]
https://refactor-mutations-job.preview.app.daily.dev

refactor: mutations for job

---

packages/shared/src/components/opportunity/OpportunityEditContext.tsx
packages/shared/src/features/opportunity/graphql.ts
packages/shared/src/features/opportunity/types.ts

API: https://github.com/dailydotdev/daily-api/pull/3182
> [!CAUTION]
https://job-edit-draft.preview.app.daily.dev

feat: can only edit draft opportunities

---

packages/webapp/pages/opportunity/[id]/index.tsx

> [!CAUTION]
https://fix-content-edge.preview.app.daily.dev

fix: rounded corner on content accordion edge

---

packages/shared/src/components/post/write/MultipleSourceSelect.tsx

> [!CAUTION]
https://fix-multiselect-name-overflow.preview.app.daily.dev

fix: prevent text overflow in MultipleSourceSelect button labels

---

packages/shared/src/components/post/PostUpvotesCommentsCount.tsx
packages/shared/src/graphql/fragments.ts
packages/shared/src/graphql/posts.ts
packages/webapp/__tests__/PostPage.tsx

API: https://github.com/dailydotdev/daily-api/pull/3195
> [!CAUTION]
https://public-analytics-impressions.preview.app.daily.dev

feat: show impressions instead of views
